# -*- coding: utf-8 -*-
"""Stage 5 library pack I: Python web/async depth, mobile libs, UI component libs."""

LIBS_5I = [
    # ---------- Backend и API: Python (deepen) ----------
    ("lib-starlette", "Starlette", "Backend и API", "https://www.starlette.io/", "openSource", "python,asgi,lightweight,foundation", "pip install starlette",
     "Lightweight ASGI framework that FastAPI itself is built on top of.",
     "Лёгкий ASGI-фреймворк, на котором построен сам FastAPI.",
     "Use it directly when you want ASGI routing and middleware without FastAPI's validation layer."),
    ("lib-uvicorn", "Uvicorn", "Backend и API", "https://www.uvicorn.org/", "openSource", "python,asgi,server,production", "pip install uvicorn",
     "The standard ASGI server for running FastAPI, Starlette and Litestar apps.",
     "Стандартный ASGI-сервер для запуска приложений FastAPI, Starlette и Litestar.",
     "Run it behind Gunicorn with uvicorn workers in production for process management and restarts."),
    ("lib-httpx-2", "HTTPX (async)", "Backend и API", "https://www.python-httpx.org/async/", "openSource", "python,http-client,async,requests-like", "pip install httpx",
     "Async-capable HTTP client for Python with a requests-compatible API.",
     "Асинхронный HTTP-клиент для Python с API, совместимым с requests.",
     "Reuse one AsyncClient across requests — creating a client per call throws away connection pooling."),
    ("lib-asyncio-tools", "AnyIO", "Backend и API", "https://anyio.readthedocs.io/", "openSource", "python,async,structured-concurrency,portable", "pip install anyio",
     "Structured concurrency for Python that works on both asyncio and Trio backends.",
     "Структурированная конкурентность для Python, работает и на asyncio, и на Trio.",
     "Task groups guarantee child tasks are awaited or cancelled — no more silently orphaned background tasks."),
    ("lib-celery-beat", "Celery Beat", "Очереди и события", "https://docs.celeryq.dev/en/stable/userguide/periodic-tasks.html", "openSource", "python,scheduling,cron,periodic", "",
     "The periodic-task scheduler that ships with Celery, a distributed cron replacement.",
     "Планировщик периодических задач в составе Celery — распределённая замена cron.",
     "Run exactly one beat process cluster-wide, or every scheduled task fires once per beat instance."),
    ("lib-arq", "arq", "Очереди и события", "https://arq-docs.helpmanual.io/", "openSource", "python,async,redis,jobs", "pip install arq",
     "Async job queue for Python built on asyncio and Redis, lighter than Celery.",
     "Асинхронная очередь задач для Python на asyncio и Redis, легче Celery.",
     "A natural fit when your app is already fully async — Celery's sync-first model fights asyncio codebases."),

    # ---------- UI и frontend: component libraries (deepen) ----------
    ("lib-park-ui", "Park UI", "UI и frontend", "https://park-ui.com/", "openSource", "components,ark-ui,panda-css,accessible", "",
     "Styled components built on Ark UI and Panda CSS, framework-agnostic across React/Vue/Solid.",
     "Стилизованные компоненты на Ark UI и Panda CSS, работают в React/Vue/Solid.",
     "One component API across three frameworks is useful for teams maintaining more than one frontend stack."),
    ("lib-ark-ui", "Ark UI", "UI и frontend", "https://ark-ui.com/docs/overview/introduction", "openSource", "headless,accessible,state-machines,multi-framework", "npm i @ark-ui/react",
     "Headless accessible components driven by state machines, for React, Vue and Solid.",
     "Headless доступные компоненты на конечных автоматах для React, Vue и Solid.",
     "Its state-machine foundation makes complex widget behavior (comboboxes, date pickers) genuinely reliable."),
    ("lib-nextui", "HeroUI (NextUI)", "UI и frontend", "https://www.heroui.com/docs/guide/introduction", "openSource", "react,components,tailwind,themeable", "npm i @heroui/react",
     "Modern React component library built on Tailwind with a strong default aesthetic.",
     "Современная библиотека React-компонентов на Tailwind с сильной эстетикой по умолчанию.",
     "Renamed from NextUI to HeroUI — older tutorials referencing NextUI describe the same library."),
    ("lib-daisyui", "daisyUI", "UI и frontend", "https://daisyui.com/docs/install/", "openSource", "tailwind,components,css-only,themes", "npm i -D daisyui",
     "Tailwind plugin adding semantic component classes, no JavaScript required.",
     "Плагин Tailwind, добавляющий семантические классы компонентов, без JavaScript.",
     "Pure CSS means it works in any framework or plain HTML — no React/Vue dependency at all."),
    ("lib-shoelace", "Shoelace / Web Awesome", "UI и frontend", "https://shoelace.style/", "openSource", "web-components,framework-agnostic,accessible", "npm i @shoelace-style/shoelace",
     "Framework-agnostic UI components built as standard web components.",
     "UI-компоненты, не зависящие от фреймворка, построены как стандартные web components.",
     "Web components work in any framework or none, which makes them a safe bet for long-lived design systems."),
    ("lib-primevue", "PrimeVue", "UI и frontend", "https://primevue.org/introduction/", "openSource", "vue,components,datatable,enterprise", "npm i primevue",
     "Large Vue component suite with a particularly capable DataTable.",
     "Большой набор Vue-компонентов с особенно мощной таблицей DataTable.",
     "Its DataTable covers virtual scroll, grouping, filtering and export — rarely worth rebuilding by hand."),

    # ---------- Мобильная разработка (deepen) ----------
    ("lib-react-native-reanimated", "React Native Reanimated", "Мобильная и desktop разработка", "https://docs.swmansion.com/react-native-reanimated/", "openSource", "react-native,animation,ui-thread,gestures", "npm i react-native-reanimated",
     "Runs animations on the UI thread in React Native, avoiding JS-bridge jank.",
     "Выполняет анимации в UI-потоке React Native, избегая подтормаживаний из-за JS-моста.",
     "Worklets run on the UI thread — that separation is exactly why gestures stay smooth under JS load."),
    ("lib-react-native-gesture-handler", "RN Gesture Handler", "Мобильная и desktop разработка", "https://docs.swmansion.com/react-native-gesture-handler/", "openSource", "react-native,gestures,native,touch", "npm i react-native-gesture-handler",
     "Native-driven gesture recognition for React Native, replacing the built-in touch system.",
     "Нативное распознавание жестов для React Native вместо встроенной системы касаний.",
     "Pairs with Reanimated so a gesture can drive an animation entirely off the JS thread."),
    ("lib-flutter-bloc-2", "flutter_bloc", "Мобильная и desktop разработка", "https://bloclibrary.dev/", "openSource", "flutter,state,bloc,events", "flutter pub add flutter_bloc",
     "Event-driven state management for Flutter with a strict, testable separation of concerns.",
     "Событийное управление состоянием Flutter со строгим тестируемым разделением ответственности.",
     "Its explicitness pays off in large teams; it is heavier than Riverpod for a small app."),
    ("lib-go-router", "go_router", "Мобильная и desktop разработка", "https://pub.dev/packages/go_router", "openSource", "flutter,routing,deep-links,declarative", "flutter pub add go_router",
     "Declarative routing for Flutter with deep linking and nested navigation support.",
     "Декларативная маршрутизация Flutter с поддержкой deep links и вложенной навигации.",
     "The official recommendation for Navigator 2.0 — hand-rolling Navigator 2.0 directly is rarely worth it."),
    ("lib-dio", "Dio", "Мобильная и desktop разработка", "https://pub.dev/packages/dio", "openSource", "flutter,http,interceptors,dart", "flutter pub add dio",
     "HTTP client for Dart with interceptors, retries and request cancellation.",
     "HTTP-клиент для Dart с интерцепторами, повторами и отменой запросов.",
     "Interceptors are the clean place to attach auth headers and refresh expired tokens app-wide."),
]
