# -*- coding: utf-8 -*-
"""Stage 5 library pack F: databases/ORM depth, testing depth, image/design depth."""

LIBS_5F = [
    # ---------- Базы данных и ORM (deepen) ----------
    ("lib-drizzle-kit", "Drizzle Kit", "Базы данных и ORM", "https://orm.drizzle.team/kit-docs/overview", "openSource", "migrations,drizzle,cli,schema", "npm i -D drizzle-kit",
     "Migration generation and schema push tooling for Drizzle ORM.",
     "Генерация миграций и push схемы для Drizzle ORM.",
     "drizzle-kit push is fast for prototyping; switch to generated migration files before production."),
    ("lib-knex", "Knex.js", "Базы данных и ORM", "https://knexjs.org/guide/", "openSource", "sql,query-builder,node,migrations", "npm i knex",
     "SQL query builder for Node supporting Postgres, MySQL, SQLite and more.",
     "Построитель SQL-запросов для Node с поддержкой Postgres, MySQL, SQLite и других.",
     "Use it as a query builder, not a full ORM — it stays close to real SQL, which many teams prefer."),
    ("lib-typeorm", "TypeORM", "Базы данных и ORM", "https://typeorm.io/", "openSource", "typescript,orm,decorators,active-record", "npm i typeorm",
     "TypeScript ORM supporting both Active Record and Data Mapper patterns.",
     "TypeScript ORM с поддержкой паттернов Active Record и Data Mapper.",
     "Pick Data Mapper (repositories) over Active Record for anything beyond a small project — it tests more easily."),
    ("lib-mikroorm", "MikroORM", "Базы данных и ORM", "https://mikro-orm.io/docs/installation", "openSource", "typescript,orm,unit-of-work,identity-map", "npm i @mikro-orm/core",
     "TypeScript ORM built around the Unit of Work and Identity Map patterns from Doctrine.",
     "TypeScript ORM на паттернах Unit of Work и Identity Map, вдохновлён Doctrine.",
     "The Identity Map means the same row loaded twice in one request is the same object — no accidental double-fetch."),
    ("lib-diesel-rust", "Diesel", "Базы данных и ORM", "https://diesel.rs/guides/", "openSource", "rust,orm,compile-time,sql", "cargo add diesel",
     "Rust ORM and query builder that checks queries against the schema at compile time.",
     "ORM и построитель запросов Rust, проверяет запросы по схеме на этапе компиляции.",
     "A typo in a column name is a compile error here, not a runtime SQL exception."),
    ("lib-libsql", "libSQL", "Базы данных и ORM", "https://github.com/tursodatabase/libsql", "openSource", "sqlite,fork,edge,embedded-replicas", "",
     "Open-source SQLite fork adding embedded replicas and remote access, the engine behind Turso.",
     "Открытый форк SQLite с поддержкой встроенных реплик и удалённого доступа — движок Turso.",
     "Embedded replicas sync a local copy for reads while writes still go to the primary — near-zero read latency."),

    # ---------- Тестирование и качество (deepen further) ----------
    ("lib-cypress-2", "Cypress Component Testing", "Тестирование и качество", "https://docs.cypress.io/guides/component-testing/overview", "openSource", "testing,components,cypress,isolated", "",
     "Mount and test individual components in isolation using the Cypress test runner.",
     "Монтирование и тестирование отдельных компонентов изолированно через раннер Cypress.",
     "Component tests run much faster than full e2e tests — use them for logic-heavy components specifically."),
    ("lib-web-test-runner", "Web Test Runner", "Тестирование и качество", "https://modern-web.dev/docs/test-runner/overview/", "openSource", "testing,web-components,browser,esm", "npm i -D @web/test-runner",
     "Runs tests in real browsers using native ES modules, framework-agnostic.",
     "Запускает тесты в реальных браузерах на нативных ES-модулях, независимо от фреймворка.",
     "Good default for testing plain web components without pulling in a full framework's test setup."),
    ("lib-mutmut", "Mutmut", "Тестирование и качество", "https://mutmut.readthedocs.io/", "openSource", "python,mutation-testing,coverage,quality", "pip install mutmut",
     "Mutation testing for Python: checks whether your tests actually catch introduced bugs.",
     "Мутационное тестирование для Python: проверяет, реально ли тесты ловят внесённые баги.",
     "High line coverage with low mutation-kill rate is the classic sign of tests that assert too little."),
    ("lib-stryker-mutator", "StrykerJS", "Тестирование и качество", "https://stryker-mutator.io/docs/stryker-js/introduction/", "openSource", "javascript,mutation-testing,quality,typescript", "npx stryker init",
     "Mutation testing for JavaScript and TypeScript projects.",
     "Мутационное тестирование для проектов JavaScript и TypeScript.",
     "Run it occasionally on critical modules, not on every CI run — mutation testing is inherently slow."),
    ("lib-schemathesis", "Schemathesis", "Тестирование и качество", "https://schemathesis.readthedocs.io/", "openSource", "api-testing,openapi,fuzzing,python", "pip install schemathesis",
     "Property-based API testing generated directly from an OpenAPI or GraphQL schema.",
     "Property-based тестирование API, генерируемое прямо из схемы OpenAPI или GraphQL.",
     "Point it at your OpenAPI spec and it finds edge cases no one thought to write a manual test for."),

    # ---------- Изображения и дизайн (deepen further) ----------
    ("lib-konva", "Konva", "Изображения и дизайн", "https://konvajs.org/docs/", "openSource", "canvas,2d,interactive,javascript", "npm i konva",
     "2D canvas library for interactive graphics: drag, resize, layer, animate shapes.",
     "2D canvas-библиотека для интерактивной графики: перетаскивание, изменение размера, слои, анимация фигур.",
     "Reach for this over raw canvas whenever shapes need to be individually clickable or draggable."),
    ("lib-fabric-js", "Fabric.js", "Изображения и дизайн", "https://fabricjs.com/docs/", "openSource", "canvas,editor,svg,interactive", "npm i fabric",
     "Canvas library built specifically for image-editor-style interactive applications.",
     "Canvas-библиотека, созданная специально для приложений в духе редакторов изображений.",
     "Its object model (with built-in selection, resize handles) is the fastest path to a mini Canva clone."),
    ("lib-sharp-cli", "sharp-cli", "Изображения и дизайн", "https://github.com/vseventer/sharp-cli", "openSource", "images,cli,batch,resize", "npm i -g sharp-cli",
     "Command-line wrapper around Sharp for batch image resizing and format conversion.",
     "CLI-обёртка над Sharp для пакетного изменения размера и конвертации формата изображений.",
     "Useful in a build script for resizing a whole assets folder without writing Node code."),
    ("lib-imagemagick", "ImageMagick", "Изображения и дизайн", "https://imagemagick.org/script/command-line-processing.php", "openSource", "images,cli,conversion,classic", "apt install imagemagick",
     "The long-standing command-line image manipulation toolkit, still relevant for batch scripts.",
     "Давний инструмент командной строки для обработки изображений, всё ещё актуален для batch-скриптов.",
     "For anything beyond simple resize/convert, check Sharp or libvips first — both wrap similar capability faster."),
]
