# -*- coding: utf-8 -*-
"""Stage 5 library pack N: PHP/Ruby ecosystems, email/templating, misc backend."""

LIBS_5N = [
    # ---------- Backend и API: PHP ----------
    ("lib-laravel", "Laravel", "Backend и API", "https://laravel.com/docs", "openSource", "php,framework,eloquent,fullstack", "composer create-project laravel/laravel",
     "The dominant PHP framework: ORM, queues, auth and templating in one opinionated package.",
     "Доминирующий PHP-фреймворк: ORM, очереди, аутентификация и шаблоны в одном пакете.",
     "Its ecosystem (Forge, Vapor, Livewire) is a large part of the value beyond the framework itself."),
    ("lib-symfony", "Symfony", "Backend и API", "https://symfony.com/doc/current/index.html", "openSource", "php,components,enterprise,framework", "composer create-project symfony/skeleton",
     "Component-based PHP framework, widely used for larger enterprise applications.",
     "Компонентный PHP-фреймворк, широко используется в крупных корпоративных приложениях.",
     "Its components are usable standalone — Laravel itself builds on several of them."),
    ("lib-livewire", "Livewire", "UI и frontend", "https://livewire.laravel.com/docs", "openSource", "php,laravel,reactive,server-rendered", "composer require livewire/livewire",
     "Builds reactive UIs in Laravel using PHP instead of a JavaScript framework.",
     "Строит реактивные интерфейсы в Laravel на PHP вместо JavaScript-фреймворка.",
     "Removes the separate SPA entirely for CRUD-heavy admin interfaces, at the cost of more server round-trips."),
    ("lib-filament-php", "Filament", "Backend и API", "https://filamentphp.com/docs", "openSource", "php,laravel,admin-panel,crud", "composer require filament/filament",
     "Admin panel and CRUD builder for Laravel, generated from your Eloquent models.",
     "Конструктор админ-панели и CRUD для Laravel, генерируется из моделей Eloquent.",
     "A full admin interface in an afternoon if your models are already well defined."),

    # ---------- Backend и API: Ruby ----------
    ("lib-rails", "Ruby on Rails", "Backend и API", "https://guides.rubyonrails.org/", "openSource", "ruby,framework,convention,fullstack", "gem install rails",
     "The convention-over-configuration framework that shaped modern web development.",
     "Фреймворк convention-over-configuration, сформировавший современную веб-разработку.",
     "Hotwire (Turbo + Stimulus) covers most interactivity without a separate frontend framework."),
    ("lib-hotwire", "Hotwire", "UI и frontend", "https://hotwired.dev/", "openSource", "ruby,rails,turbo,stimulus", "",
     "HTML-over-the-wire interactivity: Turbo for navigation, Stimulus for sprinkles of JS.",
     "Интерактивность через HTML по проводу: Turbo для навигации, Stimulus для точечного JS.",
     "The philosophical opposite of an SPA — send HTML, not JSON, and keep state on the server."),
    ("lib-sidekiq", "Sidekiq", "Очереди и события", "https://github.com/sidekiq/sidekiq/wiki", "mixed", "ruby,jobs,redis,background", "gem install sidekiq",
     "The standard background job processor for Ruby, backed by Redis.",
     "Стандартный обработчик фоновых задач для Ruby на Redis.",
     "Make jobs idempotent — Sidekiq retries on failure, and a non-idempotent job double-charges someone eventually."),
    ("lib-rspec", "RSpec", "Тестирование и качество", "https://rspec.info/documentation/", "openSource", "ruby,testing,bdd,specs", "gem install rspec",
     "Behaviour-driven testing framework, the Ruby community's testing standard.",
     "Фреймворк BDD-тестирования, стандарт тестирования в Ruby-сообществе.",
     "Its readable spec syntax doubles as documentation of intended behaviour."),

    # ---------- Почта и уведомления: templating ----------
    ("lib-react-email", "React Email", "Почта и уведомления", "https://react.email/docs/introduction", "openSource", "email,react,templates,components", "npm i @react-email/components",
     "Build email templates with React components instead of nested HTML tables.",
     "Создание email-шаблонов на React-компонентах вместо вложенных HTML-таблиц.",
     "It compiles down to the table-based HTML email clients actually need — you just never write it by hand."),
    ("lib-mjml", "MJML", "Почта и уведомления", "https://documentation.mjml.io/", "openSource", "email,templates,responsive,markup", "npm i mjml",
     "Markup language that compiles to responsive, client-compatible email HTML.",
     "Язык разметки, компилируемый в адаптивный HTML писем, совместимый с почтовыми клиентами.",
     "Solves the Outlook rendering problem specifically, which is where most hand-written email HTML breaks."),
    ("lib-maizzle", "Maizzle", "Почта и уведомления", "https://maizzle.com/docs", "openSource", "email,tailwind,templates,build", "npm i @maizzle/cli",
     "Email framework letting you build templates with Tailwind CSS utility classes.",
     "Email-фреймворк, позволяющий строить шаблоны на утилитарных классах Tailwind CSS.",
     "It inlines the CSS at build time, since most email clients still ignore external stylesheets."),
    ("lib-nodemailer", "Nodemailer", "Почта и уведомления", "https://nodemailer.com/", "openSource", "email,smtp,node,sending", "npm i nodemailer",
     "The standard Node library for sending email over SMTP or provider APIs.",
     "Стандартная Node-библиотека для отправки почты по SMTP или через API провайдеров.",
     "Use a real sending service rather than raw SMTP from your app server — deliverability depends on reputation."),

    # ---------- Шаблонизация ----------
    ("lib-handlebars", "Handlebars", "Backend и API", "https://handlebarsjs.com/guide/", "openSource", "templating,logic-less,javascript,server", "npm i handlebars",
     "Logic-less templating for JavaScript, usable server-side and in the browser.",
     "Шаблонизация без логики для JavaScript, работает на сервере и в браузере.",
     "Its deliberate lack of logic pushes computation into your code, which keeps templates readable."),
    ("lib-jinja2", "Jinja2", "Backend и API", "https://jinja.palletsprojects.com/", "openSource", "templating,python,flask,server", "pip install jinja2",
     "The standard Python templating engine, used by Flask, Ansible and many others.",
     "Стандартный шаблонизатор Python, используется во Flask, Ansible и многих других проектах.",
     "Enable autoescaping explicitly outside Flask — it is off by default in raw Jinja2, which invites XSS."),
    ("lib-liquid", "Liquid", "Backend и API", "https://shopify.github.io/liquid/", "openSource", "templating,ruby,safe,user-editable", "gem install liquid",
     "Safe templating language designed for user-editable templates, created by Shopify.",
     "Безопасный язык шаблонов для пользовательского редактирования, создан Shopify.",
     "Safe to expose to end users, unlike most template engines which can execute arbitrary code."),

    # ---------- Состояние и данные: caching ----------
    ("lib-redis-om", "Redis OM", "Состояние и данные", "https://redis.io/docs/latest/integrate/redisom-for-node-js/", "openSource", "redis,object-mapping,search,node", "npm i redis-om",
     "Object mapping for Redis with indexing and search, across several languages.",
     "Объектное отображение для Redis с индексацией и поиском, для нескольких языков.",
     "Turns Redis into a queryable document store rather than only a key-value cache."),
    ("lib-dragonfly", "Dragonfly", "Состояние и данные", "https://www.dragonflydb.io/docs", "openSource", "redis-compatible,memory,performance,multithreaded", "",
     "Redis-compatible in-memory store built multi-threaded for higher throughput per node.",
     "Redis-совместимое in-memory хранилище, многопоточное, с более высокой пропускной способностью на узел.",
     "Drop-in wire compatibility means existing Redis clients work unchanged while using fewer instances."),
    ("lib-valkey", "Valkey", "Состояние и данные", "https://valkey.io/docs/", "openSource", "redis-fork,open-source,linux-foundation,cache", "",
     "Linux Foundation fork of Redis created after Redis changed its licence.",
     "Форк Redis под управлением Linux Foundation, созданный после смены лицензии Redis.",
     "Fully BSD-licensed, which matters if your organization avoids source-available licences."),
]
