# -*- coding: utf-8 -*-
"""Stage 5 library pack AK: job queues, durable workflow engines, schedulers, orchestrators."""

LIBS_5AK = [
    # ---------- Очереди задач ----------
    ("lib-rq", "RQ", "Очереди и события", "https://python-rq.org/docs/", "openSource", "python,redis,simple,jobs", "pip install rq",
     "Simple Python job queue backed by Redis.",
     "Простая очередь задач Python на основе Redis.",
     "Far less to configure than Celery when you only need to run functions in the background."),
    ("lib-dramatiq", "Dramatiq", "Очереди и события", "https://dramatiq.io/", "openSource", "python,reliable,rabbitmq,redis", "pip install dramatiq",
     "Python task processing library emphasising reliability and simplicity.",
     "Библиотека обработки задач Python с упором на надёжность и простоту.",
     "Its defaults around retries and acknowledgement are safer than Celery's out of the box."),
    ("lib-huey", "Huey", "Очереди и события", "https://huey.readthedocs.io/", "openSource", "python,lightweight,redis,scheduling", "pip install huey",
     "Lightweight Python task queue with periodic task support.",
     "Лёгкая очередь задач Python с поддержкой периодических задач.",
     "Small enough to read end to end, which makes debugging queue behaviour genuinely feasible."),
    ("lib-bee-queue", "Bee-Queue", "Очереди и события", "https://github.com/bee-queue/bee-queue", "openSource", "node,redis,fast,simple", "npm i bee-queue",
     "Fast Redis-backed job queue for Node, focused on short live jobs.",
     "Быстрая очередь задач для Node на Redis, ориентированная на короткие задачи.",
     "Optimized for throughput on short jobs where BullMQ's richer features are unnecessary."),
    ("lib-agenda", "Agenda", "Очереди и события", "https://github.com/agenda/agenda", "openSource", "node,mongodb,scheduling,jobs", "npm i agenda",
     "MongoDB-backed job scheduling for Node.",
     "Планирование задач для Node на основе MongoDB.",
     "Useful when you already run MongoDB and would rather not add Redis for queues alone."),
    ("lib-graphile-worker", "Graphile Worker", "Очереди и события", "https://worker.graphile.org/", "openSource", "postgres,node,jobs,low-latency", "npm i graphile-worker",
     "Postgres-backed job queue for Node with very low latency.",
     "Очередь задач для Node на Postgres с очень низкой задержкой.",
     "Using LISTEN/NOTIFY rather than polling is what keeps latency in milliseconds."),
    ("lib-pg-boss", "pg-boss", "Очереди и события", "https://github.com/timgit/pg-boss", "openSource", "postgres,node,jobs,transactional", "npm i pg-boss",
     "Job queue for Node built entirely on Postgres.",
     "Очередь задач для Node, полностью построенная на Postgres.",
     "Enqueuing inside the same transaction as your data change removes a whole class of consistency bug."),
    ("lib-river-queue", "River", "Очереди и события", "https://riverqueue.com/docs", "openSource", "go,postgres,transactional,type-safe", "",
     "Postgres-backed job queue for Go with transactional enqueueing.",
     "Очередь задач для Go на Postgres с транзакционной постановкой задач.",
     "Its transactional guarantee means a job never runs for a transaction that rolled back."),
    ("lib-asynq", "Asynq", "Очереди и события", "https://github.com/hibiken/asynq", "openSource", "go,redis,jobs,web-ui", "go get github.com/hibiken/asynq",
     "Simple, reliable Redis-backed task queue for Go with a web dashboard.",
     "Простая надёжная очередь задач для Go на Redis с веб-дашбордом.",
     "Its dashboard makes inspecting and retrying failed jobs straightforward without extra tooling."),
    ("lib-machinery", "Machinery", "Очереди и события", "https://github.com/RichardKnop/machinery", "openSource", "go,distributed,brokers,workflows", "",
     "Distributed task queue for Go supporting several broker backends.",
     "Распределённая очередь задач для Go с поддержкой нескольких брокеров.",
     "Its chains and chords express multi-step job workflows without a separate orchestrator."),
    ("lib-faktory", "Faktory", "Очереди и события", "https://github.com/contribsys/faktory/wiki", "mixed", "language-agnostic,jobs,server,sidekiq-author", "",
     "Language-agnostic background job server from the author of Sidekiq.",
     "Языконезависимый сервер фоновых задач от автора Sidekiq.",
     "Workers in different languages share one queue, which per-language libraries cannot do."),
    ("lib-sidekiq-enterprise", "Sidekiq Enterprise", "Очереди и события", "https://sidekiq.org/products/enterprise.html", "paid", "ruby,jobs,rate-limiting,reliability", "",
     "Commercial Sidekiq tier adding rate limiting, batches and reliable fetch.",
     "Коммерческий уровень Sidekiq с ограничением частоты, батчами и надёжной выборкой.",
     "Reliable fetch is the feature that prevents job loss when a worker is killed mid-job."),

    # ---------- Durable execution и оркестрация ----------
    ("lib-hatchet", "Hatchet", "Очереди и события", "https://docs.hatchet.run/home", "openSource", "postgres,durable,dag,workers", "",
     "Postgres-backed distributed task queue with durable DAG workflows.",
     "Распределённая очередь задач на Postgres с надёжными DAG-workflow.",
     "Combines a queue and a workflow engine, which usually means running two separate systems."),
    ("lib-dbos", "DBOS", "Очереди и события", "https://docs.dbos.dev/", "openSource", "durable-execution,postgres,typescript,python", "npm i @dbos-inc/dbos-sdk",
     "Durable execution as a library, storing workflow state in Postgres.",
     "Durable execution в виде библиотеки, хранящей состояние workflow в Postgres.",
     "It is a library, not a cluster, so a crashed process resumes without operating a workflow service."),
    ("lib-resonate", "Resonate", "Очереди и события", "https://docs.resonatehq.io/", "openSource", "durable-promises,async,distributed,simple", "",
     "Durable promises making distributed async calls resumable after failure.",
     "Durable promises, делающие распределённые асинхронные вызовы восстанавливаемыми после сбоя.",
     "The promise abstraction is far smaller to learn than a full workflow DSL."),
    ("lib-golem-cloud", "Golem", "Очереди и события", "https://learn.golem.cloud/", "openSource", "durable,wasm,invincible,components", "",
     "Durable computing platform running WebAssembly components that survive restarts.",
     "Платформа durable-вычислений, запускающая WebAssembly-компоненты, переживающие перезапуски.",
     "WASM state snapshotting means ordinary code becomes durable without workflow-specific structuring."),
    ("lib-cadence", "Cadence", "Очереди и события", "https://cadenceworkflow.io/docs/", "openSource", "workflows,uber,durable,fault-tolerant", "",
     "Fault-tolerant workflow orchestration engine from Uber.",
     "Отказоустойчивый движок оркестрации workflow от Uber.",
     "Temporal was forked from it and carries most of the community — check both before choosing."),
    ("lib-conductor", "Conductor", "Очереди и события", "https://docs.conductor-oss.org/", "openSource", "workflows,netflix,json,microservices", "",
     "Microservice orchestration engine originally built at Netflix.",
     "Движок оркестрации микросервисов, изначально созданный в Netflix.",
     "Workflows are JSON definitions, so non-developers can review the orchestration logic."),
    ("lib-zeebe", "Camunda 8 (Zeebe)", "Очереди и события", "https://docs.camunda.io/docs/components/zeebe/zeebe-overview/", "mixed", "bpmn,workflow,scalable,orchestration", "",
     "Horizontally scalable BPMN workflow engine behind Camunda 8.",
     "Горизонтально масштабируемый BPMN-движок workflow, лежащий в основе Camunda 8.",
     "Its event-sourced design handles far higher process throughput than the older Camunda 7 engine."),
    ("lib-quartz-scheduler", "Quartz Scheduler", "JVM экосистема", "https://www.quartz-scheduler.org/documentation/", "openSource", "java,scheduling,cron,clustering", "",
     "Mature Java job scheduling library with clustering support.",
     "Зрелая библиотека планирования задач для Java с поддержкой кластеризации.",
     "Clustered mode ensures a scheduled job fires once across instances, not once per instance."),
    ("lib-spring-batch", "Spring Batch", "JVM экосистема", "https://docs.spring.io/spring-batch/reference/", "openSource", "java,batch,chunking,restartable", "",
     "Batch processing framework for large-volume JVM jobs.",
     "Фреймворк пакетной обработки для крупных задач на JVM.",
     "Chunk-based processing with restart from the last checkpoint is what suits it to very long jobs."),
    ("lib-luigi", "Luigi", "Data engineering", "https://luigi.readthedocs.io/", "openSource", "python,pipelines,dependencies,spotify", "pip install luigi",
     "Python pipeline framework from Spotify for dependency-resolved batch jobs.",
     "Python-фреймворк пайплайнов от Spotify для пакетных задач с разрешением зависимостей.",
     "Simpler than Airflow, though largely superseded by it and by Prefect for new work."),
    ("lib-mage-ai", "Mage", "Data engineering", "https://docs.mage.ai/", "openSource", "pipelines,notebooks,hybrid,data", "pip install mage-ai",
     "Data pipeline tool blending notebook-style development with production scheduling.",
     "Инструмент пайплайнов данных, сочетающий разработку в стиле ноутбуков с продакшн-планированием.",
     "Each block runs and previews independently, which shortens the pipeline debugging loop."),
    ("lib-orchest", "Orchest", "Data engineering", "https://docs.orchest.io/", "openSource", "pipelines,visual,notebooks,kubernetes", "",
     "Visual pipeline builder connecting notebooks and scripts.",
     "Визуальный конструктор пайплайнов, связывающий ноутбуки и скрипты.",
     "Project activity has slowed considerably — verify maintenance before adopting it."),

    # ---------- Управляемая оркестрация ----------
    ("lib-cloudflare-queues", "Cloudflare Queues", "Очереди и события", "https://developers.cloudflare.com/queues/", "freeTier", "serverless,queues,workers,batching", "",
     "Managed message queues integrated with Cloudflare Workers.",
     "Управляемые очереди сообщений, интегрированные с Cloudflare Workers.",
     "Batched consumers reduce invocation count, which is what keeps serverless queue costs low."),
    ("lib-cloudflare-workflows", "Cloudflare Workflows", "Очереди и события", "https://developers.cloudflare.com/workflows/", "freeTier", "durable,serverless,steps,workers", "",
     "Durable multi-step workflows running on Cloudflare Workers.",
     "Надёжные многошаговые workflow, выполняемые на Cloudflare Workers.",
     "Each step's result is persisted, so a workflow resumes mid-run rather than restarting."),
    ("lib-aws-step-functions", "AWS Step Functions", "Очереди и события", "https://docs.aws.amazon.com/step-functions/", "paid", "aws,state-machines,serverless,orchestration", "",
     "Managed state machine orchestration across AWS services.",
     "Управляемая оркестрация конечных автоматов между сервисами AWS.",
     "Express workflows cost far less than standard ones for short high-volume executions."),
    ("lib-azure-durable-functions", "Azure Durable Functions", "Очереди и события", "https://learn.microsoft.com/en-us/azure/azure-functions/durable/", "paid", "azure,serverless,orchestration,code-first", "",
     "Stateful serverless orchestration written as ordinary code on Azure Functions.",
     "Serverless-оркестрация с состоянием, написанная обычным кодом на Azure Functions.",
     "Orchestrator code must be deterministic — replays re-execute it from the start every time."),
    ("lib-google-cloud-workflows", "Google Cloud Workflows", "Очереди и события", "https://cloud.google.com/workflows/docs", "paid", "gcp,yaml,serverless,orchestration", "",
     "Serverless orchestration of Google Cloud and HTTP services defined in YAML.",
     "Serverless-оркестрация сервисов Google Cloud и HTTP, описанная в YAML.",
     "Billed per step, so a chatty workflow costs more than one that batches its calls."),
]
