# -*- coding: utf-8 -*-
"""Stage 5 API pack X: headless commerce platforms, storefronts, headless and traditional CMS."""

APIS_5X = [
    # ---------- Коммерция: headless платформы ----------
    ("api-saleor", "Saleor", "Платежи и commerce", "https://docs.saleor.io/", "openSource", "graphql,headless,python,commerce", "",
     "GraphQL-first headless commerce platform written in Python.",
     "Headless-платформа коммерции с приоритетом GraphQL, написанная на Python.",
     "Its single GraphQL schema covers storefront and admin, so one client library serves both."),
    ("api-vendure", "Vendure", "Платежи и commerce", "https://docs.vendure.io/", "openSource", "typescript,graphql,headless,plugins", "npx @vendure/create",
     "TypeScript headless commerce framework built around a plugin architecture.",
     "TypeScript-фреймворк headless-коммерции, построенный вокруг архитектуры плагинов.",
     "Extending it means writing a plugin in the same TypeScript as your app, not a separate templating layer."),
    ("api-commercetools", "commercetools", "Платежи и commerce", "https://docs.commercetools.com/", "paid", "enterprise,headless,composable,api-first", "",
     "Enterprise composable commerce platform with a fully API-first model.",
     "Корпоративная composable-платформа коммерции с полностью API-first моделью.",
     "Its projection and product-type model is powerful but demands real upfront data modelling."),
    ("api-swell", "Swell", "Платежи и commerce", "https://developers.swell.is/", "freeTier", "headless,subscriptions,flexible,api", "",
     "Headless commerce backend with strong subscription and custom-model support.",
     "Headless-бэкенд коммерции с сильной поддержкой подписок и произвольных моделей данных.",
     "Handles subscription commerce natively, which most headless platforms bolt on through plugins."),
    ("api-crystallize", "Crystallize", "Платежи и commerce", "https://crystallize.com/learn", "freeTier", "headless,graphql,content-commerce,pim", "",
     "Combined product information management and headless commerce over GraphQL.",
     "Совмещённое управление информацией о товарах и headless-коммерция через GraphQL.",
     "Treating rich content and product data as one system suits catalogues that sell through storytelling."),
    ("api-shopware", "Shopware", "Платежи и commerce", "https://developer.shopware.com/", "openSource", "php,symfony,headless,europe", "",
     "PHP commerce platform with both traditional and headless storefront options.",
     "PHP-платформа коммерции с традиционной и headless витриной.",
     "Widely used in German-speaking markets, with local payment and tax handling built in."),
    ("api-magento", "Adobe Commerce (Magento)", "Платежи и commerce", "https://developer.adobe.com/commerce/webapi/rest/", "mixed", "php,enterprise,rest,graphql", "",
     "Long-established PHP commerce platform with REST and GraphQL APIs.",
     "Давно устоявшаяся PHP-платформа коммерции с REST и GraphQL API.",
     "Powerful but operationally heavy — factor hosting and upgrade effort into any comparison."),
    ("api-bigcommerce", "BigCommerce", "Платежи и commerce", "https://developer.bigcommerce.com/docs/build", "paid", "saas,headless,catalog,storefront", "",
     "SaaS commerce platform usable both hosted and as a headless backend.",
     "SaaS-платформа коммерции, используемая и как хостинг, и как headless-бэкенд.",
     "No transaction fees on its own plans, unlike several competitors that take a cut per order."),
    ("api-spree", "Spree Commerce", "Платежи и commerce", "https://docs.spreecommerce.org/", "openSource", "ruby,rails,headless,multi-store", "",
     "Ruby on Rails commerce platform with headless APIs and multi-store support.",
     "Платформа коммерции на Ruby on Rails с headless API и поддержкой нескольких магазинов.",
     "A natural fit if your team already runs Rails — it extends like any other Rails engine."),
    ("api-solidus", "Solidus", "Платежи и commerce", "https://guides.solidus.io/", "openSource", "ruby,rails,fork,stable", "",
     "Community-governed Rails commerce platform, forked from Spree for stability.",
     "Платформа коммерции на Rails под управлением сообщества, форк Spree ради стабильности.",
     "Its stricter backwards-compatibility policy is the main reason teams choose it over Spree."),
    ("api-sylius", "Sylius", "Платежи и commerce", "https://docs.sylius.com/", "openSource", "php,symfony,headless,customizable", "",
     "Symfony-based commerce platform aimed at heavily customized B2B and B2C stores.",
     "Платформа коммерции на Symfony для сильно кастомизированных B2B и B2C магазинов.",
     "Built as a Symfony application, so customization is ordinary framework work rather than plugin hooks."),
    ("api-bagisto", "Bagisto", "Платежи и commerce", "https://devdocs.bagisto.com/", "openSource", "laravel,php,multi-vendor,free", "",
     "Laravel-based open-source commerce platform with multi-vendor support.",
     "Открытая платформа коммерции на Laravel с поддержкой мультивендорности.",
     "Free multi-vendor marketplace support is unusual — most platforms sell that as an add-on."),

    # ---------- Витрины и конструкторы сайтов ----------
    ("api-webflow", "Webflow API", "CMS и контент", "https://developers.webflow.com/", "freeTier", "cms,visual,sites,designer", "",
     "APIs for Webflow site content, CMS collections and e-commerce data.",
     "API для контента сайтов Webflow, коллекций CMS и данных e-commerce.",
     "Its CMS API turns a visually designed site into a headless content source for other apps."),
    ("api-framer", "Framer", "UI и frontend", "https://www.framer.com/developers/", "freeTier", "design,sites,components,react", "",
     "Visual site builder whose custom components are ordinary React code.",
     "Визуальный конструктор сайтов, где кастомные компоненты — обычный React-код.",
     "Dropping real React components into a visual canvas covers what a no-code builder cannot express."),
    ("api-wix-headless", "Wix Headless", "CMS и контент", "https://dev.wix.com/docs/go-headless", "freeTier", "headless,commerce,bookings,apis", "",
     "Wix business APIs (stores, bookings, data) usable from your own frontend.",
     "Бизнес-API Wix (магазины, бронирования, данные), используемые из вашего собственного фронтенда.",
     "Its bookings and events APIs are useful even if you never render a Wix-hosted page."),
    ("api-squarespace", "Squarespace API", "CMS и контент", "https://developers.squarespace.com/", "paid", "commerce,inventory,orders,sites", "",
     "APIs for Squarespace commerce inventory, orders and profiles.",
     "API для товарных остатков, заказов и профилей Squarespace.",
     "Read-oriented and fairly narrow — it complements a Squarespace site rather than replacing its backend."),

    # ---------- Headless CMS ----------
    ("api-keystone", "Keystone", "CMS и контент", "https://keystonejs.com/docs", "openSource", "graphql,typescript,schema,admin-ui", "",
     "TypeScript headless CMS generating a GraphQL API and admin UI from your schema.",
     "Headless CMS на TypeScript, генерирующая GraphQL API и админку из вашей схемы.",
     "Schema changes regenerate both the API and the admin interface, keeping them permanently in sync."),
    ("api-tina-cms", "TinaCMS", "CMS и контент", "https://tina.io/docs", "freeTier", "git-backed,markdown,visual-editing,react", "",
     "Git-backed CMS with visual editing that commits content changes as ordinary commits.",
     "CMS на основе Git с визуальным редактированием, сохраняющая изменения контента обычными коммитами.",
     "Content stays in the repository, so it branches, reviews and rolls back exactly like code."),
    ("api-decap-cms", "Decap CMS", "CMS и контент", "https://decapcms.org/docs/intro/", "openSource", "git-backed,static-sites,markdown,netlify", "",
     "Git-based CMS for static sites, formerly Netlify CMS.",
     "CMS на основе Git для статических сайтов, ранее Netlify CMS.",
     "Runs entirely in the browser against the Git provider's API, so there is no CMS server to host."),
    ("api-hygraph", "Hygraph", "CMS и контент", "https://hygraph.com/docs", "freeTier", "graphql,federation,headless,content", "",
     "GraphQL-native headless CMS with content federation across sources.",
     "GraphQL-нативная headless CMS с федерацией контента из разных источников.",
     "Federation pulls remote data into the same GraphQL query as your content, removing a stitching layer."),
    ("api-datocms", "DatoCMS", "CMS и контент", "https://www.datocms.com/docs", "freeTier", "graphql,images,headless,structured", "",
     "Headless CMS with strong structured content modelling and image processing.",
     "Headless CMS с сильным структурированным моделированием контента и обработкой изображений.",
     "Its image API handles cropping and format negotiation, so you need no separate media service."),
    ("api-buttercms", "ButterCMS", "CMS и контент", "https://buttercms.com/docs/api/", "paid", "blog,headless,simple,seo", "",
     "Headless CMS focused on adding a blog and marketing pages to an existing app.",
     "Headless CMS для добавления блога и маркетинговых страниц в существующее приложение.",
     "Deliberately narrow — a blog in an afternoon, rather than a general content platform."),
    ("api-cosmic", "Cosmic", "CMS и контент", "https://www.cosmicjs.com/docs", "freeTier", "headless,rest,graphql,objects", "",
     "Headless CMS with a flexible object model and both REST and GraphQL access.",
     "Headless CMS с гибкой объектной моделью и доступом через REST и GraphQL.",
     "Its generic object model adapts to non-article content that blog-shaped CMSes handle badly."),
    ("api-builder-io", "Builder.io", "CMS и контент", "https://www.builder.io/c/docs/developers", "freeTier", "visual-editing,headless,components,personalization", "",
     "Visual content platform where marketers compose pages from your real components.",
     "Визуальная контент-платформа, где маркетологи собирают страницы из ваших реальных компонентов.",
     "Registering your design-system components keeps visually built pages on brand automatically."),
    ("api-plasmic", "Plasmic", "CMS и контент", "https://docs.plasmic.app/learn/", "freeTier", "visual-builder,codegen,components,react", "",
     "Visual builder that generates or integrates with real React codebases.",
     "Визуальный конструктор, генерирующий код или интегрирующийся с реальными React-проектами.",
     "Its codegen mode produces components you own outright, avoiding permanent platform lock-in."),
    ("api-ghost", "Ghost", "CMS и контент", "https://ghost.org/docs/", "openSource", "publishing,newsletters,memberships,headless", "",
     "Publishing platform with built-in newsletters, memberships and a content API.",
     "Издательская платформа со встроенными рассылками, подписками и content API.",
     "Newsletters and paid memberships are native, which replaces a separate email and billing stack."),
    ("api-wordpress-rest", "WordPress REST API", "CMS и контент", "https://developer.wordpress.org/rest-api/", "openSource", "wordpress,headless,posts,ubiquitous", "",
     "REST API built into WordPress, enabling headless use of any WordPress site.",
     "REST API, встроенный в WordPress, позволяющий использовать любой сайт WordPress как headless.",
     "Given WordPress's share of the web, this is often the fastest route to an existing content archive."),
    ("api-craft-cms", "Craft CMS", "CMS и контент", "https://craftcms.com/docs", "mixed", "php,flexible,graphql,content-modelling", "",
     "PHP CMS known for flexible content modelling and a clean authoring experience.",
     "PHP-CMS, известная гибким моделированием контента и удобным интерфейсом редактора.",
     "Its matrix fields handle irregular page structures that rigid post-and-page models cannot."),
    ("api-umbraco", "Umbraco", "CMS и контент", "https://docs.umbraco.com/", "openSource", "dotnet,csharp,headless,enterprise", "",
     "Open-source .NET CMS with both traditional and headless delivery.",
     "Открытая .NET CMS с традиционной и headless доставкой контента.",
     "The default pick for content sites in a .NET shop, where PHP CMSes mean a second stack."),
    ("api-kirby", "Kirby", "CMS и контент", "https://getkirby.com/docs/guide", "paid", "php,file-based,no-database,flexible", "",
     "File-based PHP CMS storing content as plain text files with no database.",
     "Файловая PHP-CMS, хранящая контент в обычных текстовых файлах без базы данных.",
     "No database means backup is a file copy and the whole site is version-controllable."),
    ("api-statamic", "Statamic", "CMS и контент", "https://statamic.dev/", "mixed", "laravel,flat-file,php,antlers", "",
     "Laravel-based CMS that can store content flat-file or in a database.",
     "CMS на Laravel, хранящая контент в плоских файлах или в базе данных.",
     "Flat-file mode gives Git-tracked content while keeping the full Laravel ecosystem available."),

    # ---------- Контент в коде ----------
    ("api-astro-content", "Astro Content Collections", "CMS и контент", "https://docs.astro.build/en/guides/content-collections/", "openSource", "astro,typed,markdown,build-time", "",
     "Type-safe local content collections validated at build time in Astro.",
     "Типобезопасные локальные коллекции контента с проверкой на этапе сборки в Astro.",
     "Schema validation turns a malformed frontmatter field into a build error rather than a runtime blank."),
    ("api-contentlayer", "Contentlayer", "CMS и контент", "https://contentlayer.dev/docs", "openSource", "typed,markdown,mdx,nextjs", "",
     "Transforms local Markdown and MDX into typed data for your application.",
     "Преобразует локальные Markdown и MDX в типизированные данные для приложения.",
     "Maintenance has stalled — Velite and Keystatic are the actively developed alternatives."),
    ("api-velite", "Velite", "CMS и контент", "https://velite.js.org/", "openSource", "typed,markdown,zod,build-time", "npm i velite",
     "Turns Markdown, MDX and YAML into type-safe data validated with Zod schemas.",
     "Превращает Markdown, MDX и YAML в типобезопасные данные с валидацией по Zod-схемам.",
     "Zod schemas mean content validation reuses the same types your application code already uses."),
    ("api-keystatic", "Keystatic", "CMS и контент", "https://keystatic.com/docs", "openSource", "git-backed,local,editor,typescript", "",
     "Git-backed content editor running locally or against GitHub, with typed schemas.",
     "Редактор контента на основе Git, работающий локально или через GitHub, с типизированными схемами.",
     "Its local mode edits files on disk directly, which makes authoring work offline with no server."),
]
