# -*- coding: utf-8 -*-
"""Stage 5 library pack X: MLOps pipelines, model serving, inference runtimes, data quality."""

LIBS_5X = [
    # ---------- MLOps: пайплайны и оркестрация ----------
    ("lib-kubeflow", "Kubeflow", "MLOps и эксперименты", "https://www.kubeflow.org/docs/", "openSource", "kubernetes,pipelines,ml,platform", "",
     "ML platform running training pipelines and notebooks on Kubernetes.",
     "ML-платформа, запускающая обучающие пайплайны и ноутбуки в Kubernetes.",
     "Heavy to operate — worth it only if you already run Kubernetes and need multi-team isolation."),
    ("lib-metaflow", "Metaflow", "MLOps и эксперименты", "https://docs.metaflow.org/", "openSource", "pipelines,python,netflix,versioning", "pip install metaflow",
     "Netflix's framework for structuring ML workflows as versioned Python flows.",
     "Фреймворк Netflix для структурирования ML-workflow как версионируемых Python-потоков.",
     "Local runs and cloud runs use identical code, so you scale up without rewriting the pipeline."),
    ("lib-zenml", "ZenML", "MLOps и эксперименты", "https://docs.zenml.io/", "openSource", "pipelines,portable,stacks,mlops", "pip install zenml",
     "Portable ML pipelines that swap backends without changing pipeline code.",
     "Переносимые ML-пайплайны, меняющие бэкенды без изменения кода пайплайна.",
     "Its stack abstraction is the point — the same pipeline runs on local, Kubeflow or Vertex."),
    ("lib-flyte", "Flyte", "MLOps и эксперименты", "https://docs.flyte.org/", "openSource", "workflows,typed,kubernetes,reproducible", "",
     "Strongly typed workflow orchestrator for data and ML, with caching and versioning.",
     "Строго типизированный оркестратор workflow для данных и ML с кэшированием и версионированием.",
     "Task-level caching skips recomputation across runs, which is a large saving on expensive training steps."),
    ("lib-determined-ai", "Determined AI", "MLOps и эксперименты", "https://docs.determined.ai/", "openSource", "training,hyperparameter,distributed,gpu", "",
     "Deep learning training platform with distributed training and hyperparameter search.",
     "Платформа обучения глубоких сетей с распределённым обучением и подбором гиперпараметров.",
     "Its GPU scheduling and preemption handle shared cluster contention that plain scripts do not."),
    ("lib-ray-train", "Ray Train", "MLOps и эксперименты", "https://docs.ray.io/en/latest/train/train.html", "openSource", "distributed,training,ray,scaling", "pip install 'ray[train]'",
     "Distributed training library scaling PyTorch and TensorFlow jobs across a Ray cluster.",
     "Библиотека распределённого обучения, масштабирующая задачи PyTorch и TensorFlow по кластеру Ray.",
     "Wrapping an existing single-node training loop is usually a few lines, not a rewrite."),
    ("lib-horovod", "Horovod", "MLOps и эксперименты", "https://horovod.readthedocs.io/", "openSource", "distributed,allreduce,mpi,training", "pip install horovod",
     "Distributed deep learning training framework built on ring all-reduce.",
     "Фреймворк распределённого обучения глубоких сетей на основе ring all-reduce.",
     "Largely superseded by native PyTorch DDP — check whether you still need the extra dependency."),
    ("lib-deepspeed", "DeepSpeed", "MLOps и эксперименты", "https://www.deepspeed.ai/getting-started/", "openSource", "training,zero,memory,large-models", "pip install deepspeed",
     "Training optimization library whose ZeRO stages cut memory use for very large models.",
     "Библиотека оптимизации обучения: стадии ZeRO снижают потребление памяти для очень больших моделей.",
     "ZeRO-3 lets a model larger than one GPU's memory train by sharding optimizer state and parameters."),
    ("lib-megatron-lm", "Megatron-LM", "MLOps и эксперименты", "https://github.com/NVIDIA/Megatron-LM", "openSource", "training,tensor-parallel,nvidia,large-models", "",
     "NVIDIA's framework for training very large transformers with tensor and pipeline parallelism.",
     "Фреймворк NVIDIA для обучения очень крупных трансформеров с тензорным и конвейерным параллелизмом.",
     "Aimed at multi-node GPU clusters — overkill unless you are training models at billion-parameter scale."),

    # ---------- Обслуживание моделей ----------
    ("lib-seldon-core", "Seldon Core", "MLOps и эксперименты", "https://docs.seldon.ai/seldon-core-2", "openSource", "serving,kubernetes,inference,graphs", "",
     "Kubernetes-native model serving with inference graphs and explainability hooks.",
     "Kubernetes-нативное обслуживание моделей с графами инференса и хуками объяснимости.",
     "Inference graphs let you chain transformers, models and explainers as one deployed unit."),
    ("lib-kserve", "KServe", "MLOps и эксперименты", "https://kserve.github.io/website/latest/", "openSource", "serving,kubernetes,serverless,autoscaling", "",
     "Serverless model inference on Kubernetes with scale-to-zero.",
     "Serverless-инференс моделей в Kubernetes с масштабированием до нуля.",
     "Scale-to-zero makes hosting many rarely-used models affordable, unlike always-on deployments."),
    ("lib-triton-server", "Triton Inference Server", "MLOps и эксперименты", "https://docs.nvidia.com/deeplearning/triton-inference-server/", "openSource", "nvidia,serving,gpu,multi-framework", "",
     "NVIDIA's inference server running models from many frameworks with dynamic batching.",
     "Сервер инференса NVIDIA, запускающий модели многих фреймворков с динамическим батчингом.",
     "Dynamic batching alone often doubles GPU throughput versus serving requests one at a time."),
    ("lib-cortex-ml", "Cortex", "MLOps и эксперименты", "https://github.com/cortexlabs/cortex", "openSource", "serving,aws,autoscaling,inference", "",
     "Model deployment platform for AWS with autoscaling inference APIs.",
     "Платформа развёртывания моделей для AWS с автомасштабируемыми API инференса.",
     "Project activity has slowed considerably — verify maintenance status before adopting it."),

    # ---------- Рантаймы инференса ----------
    ("lib-openvino", "OpenVINO", "Локальные модели", "https://docs.openvino.ai/", "openSource", "intel,inference,cpu,optimization", "pip install openvino",
     "Intel's toolkit for optimizing and running inference on CPUs, iGPUs and NPUs.",
     "Набор инструментов Intel для оптимизации и запуска инференса на CPU, встроенных GPU и NPU.",
     "Makes CPU-only inference genuinely viable for vision models, which is its main practical use."),
    ("lib-tensorrt", "TensorRT", "Локальные модели", "https://docs.nvidia.com/deeplearning/tensorrt/", "free", "nvidia,inference,optimization,gpu", "",
     "NVIDIA's inference optimizer producing highly tuned GPU engines from trained models.",
     "Оптимизатор инференса NVIDIA, создающий высокооптимизированные GPU-движки из обученных моделей.",
     "Engines are built for a specific GPU and driver version — rebuild them when the hardware changes."),
    ("lib-coreml-tools", "Core ML Tools", "Локальные модели", "https://apple.github.io/coremltools/docs-guides/", "openSource", "apple,on-device,conversion,ios", "pip install coremltools",
     "Converts trained models into Core ML format for on-device Apple inference.",
     "Конвертирует обученные модели в формат Core ML для инференса на устройствах Apple.",
     "Quantize during conversion — on-device model size affects app download size directly."),
    ("lib-tflite", "LiteRT (TensorFlow Lite)", "Локальные модели", "https://ai.google.dev/edge/litert", "openSource", "mobile,edge,inference,quantization", "",
     "On-device inference runtime for mobile, embedded and edge hardware.",
     "Рантайм инференса на устройстве для мобильных, встраиваемых и edge-платформ.",
     "Post-training quantization to int8 typically cuts model size fourfold with modest accuracy loss."),
    ("lib-apache-tvm", "Apache TVM", "Локальные модели", "https://tvm.apache.org/docs/", "openSource", "compiler,optimization,hardware,portable", "",
     "Compiler stack that auto-tunes models for a wide range of hardware backends.",
     "Компиляторный стек, автоматически тюнингующий модели под широкий набор аппаратных бэкендов.",
     "Auto-tuning takes hours but produces kernels beating hand-written ones on unusual hardware."),
    ("lib-ggml", "GGML", "Локальные модели", "https://github.com/ggml-org/ggml", "openSource", "tensor,c,quantization,cpu", "",
     "Minimal C tensor library behind llama.cpp and whisper.cpp, tuned for quantized CPU inference.",
     "Минимальная C-библиотека тензоров, лежащая в основе llama.cpp и whisper.cpp, для квантованного CPU-инференса.",
     "Zero dependencies and a single file output is why it ports to phones, browsers and microcontrollers."),
    ("lib-sglang", "SGLang", "Локальные модели", "https://docs.sglang.ai/", "openSource", "serving,llm,throughput,structured", "pip install sglang",
     "High-throughput LLM serving runtime with prefix caching and structured output support.",
     "Высокопроизводительный рантайм обслуживания LLM с кэшированием префиксов и структурированным выводом.",
     "Its RadixAttention prefix cache is a large win when many requests share a long system prompt."),
    ("lib-tgi", "Text Generation Inference", "Локальные модели", "https://huggingface.co/docs/text-generation-inference/", "openSource", "huggingface,serving,llm,production", "",
     "Hugging Face's production LLM serving container with continuous batching.",
     "Продакшн-контейнер обслуживания LLM от Hugging Face с непрерывным батчингом.",
     "Continuous batching keeps the GPU busy between requests, unlike static batch inference."),
    ("lib-jan-ai", "Jan", "Локальные модели", "https://jan.ai/docs", "openSource", "desktop,local-llm,offline,privacy", "",
     "Open-source desktop app for running LLMs entirely offline.",
     "Открытое desktop-приложение для полностью офлайнового запуска LLM.",
     "Exposes an OpenAI-compatible local endpoint, so existing client code points at it unchanged."),

    # ---------- Эксперименты и трекинг ----------
    ("lib-wandb", "Weights & Biases", "MLOps и эксперименты", "https://docs.wandb.ai/", "freeTier", "tracking,experiments,artifacts,visualization", "pip install wandb",
     "Experiment tracking with run comparison, artifact versioning and hosted dashboards.",
     "Отслеживание экспериментов со сравнением запусков, версионированием артефактов и облачными дашбордами.",
     "Free for personal and academic work, which covers most individual research use."),
    ("lib-comet-ml", "Comet ML", "MLOps и эксперименты", "https://www.comet.com/docs/v2/", "freeTier", "tracking,experiments,model-registry,monitoring", "pip install comet-ml",
     "Experiment tracking and model registry with production monitoring.",
     "Отслеживание экспериментов и реестр моделей с мониторингом в продакшне.",
     "Its model registry ties a deployed model back to the exact run that produced it."),
    ("lib-neptune-ai", "Neptune.ai", "MLOps и эксперименты", "https://docs.neptune.ai/", "freeTier", "tracking,metadata,experiments,scale", "pip install neptune",
     "Experiment metadata store built for very high volumes of logged runs.",
     "Хранилище метаданных экспериментов, рассчитанное на очень большие объёмы логируемых запусков.",
     "Handles thousands of concurrent runs better than most alternatives, which matters for large sweeps."),
    ("lib-aim-stack", "Aim", "MLOps и эксперименты", "https://aimstack.readthedocs.io/", "openSource", "tracking,self-host,ui,comparison", "pip install aim",
     "Self-hosted experiment tracker with a fast comparison UI and no account required.",
     "Self-hosted трекер экспериментов с быстрым интерфейсом сравнения и без регистрации.",
     "Fully local, so it works for research on data that cannot leave your network."),

    # ---------- Версионирование и качество данных ----------
    ("lib-lakefs", "lakeFS", "Data engineering", "https://docs.lakefs.io/", "openSource", "data-versioning,git-like,object-storage,branches", "",
     "Git-like branching, committing and rollback over object-storage data lakes.",
     "Git-подобное ветвление, коммиты и откат поверх озёр данных в объектном хранилище.",
     "Branch the lake before a risky transformation — rollback is instant and costs no data copy."),
    ("lib-pachyderm", "Pachyderm", "Data engineering", "https://docs.pachyderm.com/", "mixed", "data-versioning,pipelines,lineage,kubernetes", "",
     "Data versioning and pipelines with automatic lineage tracking on Kubernetes.",
     "Версионирование данных и пайплайны с автоматическим отслеживанием происхождения в Kubernetes.",
     "Pipelines rerun only on the data that actually changed, which is its core efficiency claim."),
    ("lib-soda-core", "Soda Core", "Data engineering", "https://docs.soda.io/", "openSource", "data-quality,checks,yaml,testing", "pip install soda-core",
     "Data quality checks written in a readable YAML dialect and run against your warehouse.",
     "Проверки качества данных на читаемом YAML-диалекте, выполняемые против вашего хранилища.",
     "Its check language is approachable enough that analysts write their own quality rules."),
    ("lib-evidently", "Evidently", "AI-оценка и safety", "https://docs.evidentlyai.com/", "openSource", "drift,monitoring,reports,ml", "pip install evidently",
     "Detects data and model drift, producing shareable reports and monitoring dashboards.",
     "Обнаруживает дрейф данных и модели, формируя отчёты и дашборды мониторинга.",
     "Drift detection catches silent model degradation long before accuracy metrics visibly drop."),
    ("lib-deepchecks", "Deepchecks", "AI-оценка и safety", "https://docs.deepchecks.com/", "openSource", "validation,testing,ml,suites", "pip install deepchecks",
     "Test suites validating data and models, from splits and leakage to performance.",
     "Наборы тестов, проверяющие данные и модели — от сплитов и утечек до производительности.",
     "Its train/test leakage checks catch a mistake that silently inflates every offline metric."),
    ("lib-whylogs", "whylogs", "AI-оценка и safety", "https://docs.whylabs.ai/docs/whylogs-overview/", "openSource", "profiling,logging,drift,lightweight", "pip install whylogs",
     "Lightweight data profiling that logs statistical summaries rather than raw records.",
     "Лёгкое профилирование данных: логирует статистические сводки вместо сырых записей.",
     "Profiles contain no raw data, so they can leave a regulated environment when the data cannot."),
]
