# -*- coding: utf-8 -*-
"""Stage 5 library pack AO: self-hosted PaaS, configuration management, container runtimes, local Kubernetes."""

LIBS_5AO = [
    # ---------- Хостинг и self-hosted PaaS ----------
    ("lib-vercel", "Vercel", "Облако и деплой", "https://vercel.com/docs", "freeTier", "frontend,serverless,edge,nextjs", "npm i -g vercel",
     "Frontend hosting platform with serverless and edge functions.",
     "Платформа хостинга фронтенда с serverless и edge-функциями.",
     "Its bandwidth pricing is the line that surprises people — check it before a traffic spike does."),
    ("lib-netlify", "Netlify", "Облако и деплой", "https://docs.netlify.com/", "freeTier", "jamstack,static,functions,forms", "npm i -g netlify-cli",
     "Static site and serverless function hosting with built-in forms and identity.",
     "Хостинг статических сайтов и serverless-функций со встроенными формами и идентификацией.",
     "Its form handling covers a contact form with no backend at all, which is genuinely useful."),
    ("lib-coolify", "Coolify", "Облако и деплой", "https://coolify.io/docs/", "openSource", "self-hosted,paas,docker,heroku-alternative", "",
     "Self-hosted platform-as-a-service, an open alternative to Heroku and Vercel.",
     "Self-hosted платформа как сервис, открытая альтернатива Heroku и Vercel.",
     "One VPS running it replaces several paid hosting subscriptions, at the cost of owning the ops."),
    ("lib-dokploy", "Dokploy", "Облако и деплой", "https://docs.dokploy.com/", "openSource", "self-hosted,paas,docker-compose,simple", "",
     "Self-hosted deployment platform built around Docker Compose.",
     "Self-hosted платформа развёртывания, построенная вокруг Docker Compose.",
     "If your app already has a compose file, deployment is essentially just pointing it at a server."),
    ("lib-caprover", "CapRover", "Облако и деплой", "https://caprover.com/docs/get-started.html", "openSource", "self-hosted,paas,docker-swarm,one-click", "",
     "Self-hosted PaaS on Docker Swarm with one-click application templates.",
     "Self-hosted PaaS на Docker Swarm с шаблонами приложений в один клик.",
     "Its one-click apps cover most self-hosted services people actually want to run."),
    ("lib-dokku", "Dokku", "Облако и деплой", "https://dokku.com/docs/getting-started/installation/", "openSource", "self-hosted,paas,git-push,buildpacks", "",
     "Minimal Heroku-style PaaS deploying via git push on a single host.",
     "Минималистичный PaaS в стиле Heroku с развёртыванием через git push на одном хосте.",
     "It reproduces the Heroku workflow faithfully, which makes migrating off Heroku straightforward."),
    ("lib-kamal", "Kamal", "Облако и деплой", "https://kamal-deploy.org/docs/installation/", "openSource", "deployment,docker,ruby,zero-downtime", "gem install kamal",
     "Deploys containers to any server over SSH, from the Rails team.",
     "Развёртывает контейнеры на любой сервер через SSH, разработка команды Rails.",
     "Deliberately targets plain servers rather than Kubernetes, which is the whole appeal."),

    # ---------- Управление конфигурацией ----------
    ("lib-saltstack", "Salt", "Инфраструктура как код", "https://docs.saltproject.io/", "openSource", "configuration-management,remote-execution,fast,python", "",
     "Configuration management and remote execution built for very large fleets.",
     "Управление конфигурацией и удалённое выполнение для очень больших парков машин.",
     "Its event-driven message bus executes across thousands of nodes far faster than SSH-based tools."),
    ("lib-chef", "Chef", "Инфраструктура как код", "https://docs.chef.io/", "mixed", "configuration-management,ruby,cookbooks,compliance", "",
     "Ruby-based configuration management with reusable cookbooks.",
     "Управление конфигурацией на Ruby с переиспользуемыми cookbook.",
     "Its compliance scanning is often the reason it persists in regulated enterprises."),
    ("lib-puppet", "Puppet", "Инфраструктура как код", "https://www.puppet.com/docs", "mixed", "configuration-management,declarative,agent,enterprise", "",
     "Declarative configuration management with an agent-based pull model.",
     "Декларативное управление конфигурацией с агентной pull-моделью.",
     "Agents continuously reconcile drift, unlike push tools that only apply when you run them."),
    ("lib-cfengine", "CFEngine", "Инфраструктура как код", "https://docs.cfengine.com/", "mixed", "configuration-management,lightweight,convergent,original", "",
     "The original configuration management system, with a very small agent footprint.",
     "Первая система управления конфигурацией с очень малым размером агента.",
     "Its tiny agent still suits embedded and heavily constrained systems others cannot reach."),
    ("lib-packer", "Packer", "Инфраструктура как код", "https://developer.hashicorp.com/packer/docs", "openSource", "images,hashicorp,automation,multi-cloud", "",
     "Builds identical machine images for multiple platforms from one configuration.",
     "Создаёт идентичные образы машин для разных платформ из одной конфигурации.",
     "Baking dependencies into the image cuts boot time versus configuring instances after launch."),

    # ---------- Локальные виртуальные машины ----------
    ("lib-vagrant", "Vagrant", "Разработка и DevOps", "https://developer.hashicorp.com/vagrant/docs", "openSource", "vm,development,reproducible,boxes", "",
     "Manages reproducible virtual machine development environments.",
     "Управляет воспроизводимыми средами разработки на виртуальных машинах.",
     "Largely displaced by containers, but still the right tool when you need a real kernel."),
    ("lib-multipass", "Multipass", "Разработка и DevOps", "https://documentation.ubuntu.com/multipass/", "openSource", "ubuntu,vm,lightweight,canonical", "",
     "Launches Ubuntu virtual machines on demand from a single command.",
     "Запускает виртуальные машины Ubuntu по требованию одной командой.",
     "Fastest way to get a disposable Ubuntu VM on macOS or Windows for testing install scripts."),
    ("lib-lima", "Lima", "Разработка и DevOps", "https://lima-vm.io/docs/", "openSource", "linux-vm,macos,containers,file-sharing", "",
     "Runs Linux virtual machines on macOS with automatic file and port forwarding.",
     "Запускает виртуальные машины Linux на macOS с автоматическим пробросом файлов и портов.",
     "It underpins Colima and Rancher Desktop, so many people run it without realizing."),
    ("lib-colima", "Colima", "Разработка и DevOps", "https://github.com/abiosoft/colima", "openSource", "docker,macos,lima,free", "brew install colima",
     "Container runtime for macOS, a free alternative to Docker Desktop.",
     "Рантайм контейнеров для macOS, бесплатная альтернатива Docker Desktop.",
     "No licence fee for commercial use, which is Docker Desktop's main friction in companies."),
    ("lib-orbstack", "OrbStack", "Разработка и DevOps", "https://docs.orbstack.dev/", "mixed", "macos,docker,fast,lightweight", "",
     "Fast, lightweight Docker and Linux machine runtime for macOS.",
     "Быстрый лёгкий рантайм Docker и Linux-машин для macOS.",
     "Noticeably faster startup and lower battery drain than Docker Desktop on the same hardware."),

    # ---------- Контейнерные рантаймы ----------
    ("lib-podman", "Podman", "Разработка и DevOps", "https://docs.podman.io/", "openSource", "containers,daemonless,rootless,redhat", "",
     "Daemonless container engine with rootless containers by default.",
     "Движок контейнеров без демона, по умолчанию с rootless-контейнерами.",
     "Rootless by default removes the root-equivalent access that Docker group membership grants."),
    ("lib-containerd", "containerd", "Разработка и DevOps", "https://containerd.io/docs/", "openSource", "runtime,cncf,core,kubernetes", "",
     "Core container runtime used by Docker and most Kubernetes clusters.",
     "Базовый рантайм контейнеров, используемый Docker и большинством кластеров Kubernetes.",
     "You are almost certainly already running it, whether or not you interact with it directly."),
    ("lib-cri-o", "CRI-O", "Service mesh и Kubernetes", "https://github.com/cri-o/cri-o", "openSource", "kubernetes,runtime,minimal,cri", "",
     "Lightweight container runtime built specifically for Kubernetes.",
     "Лёгкий рантайм контейнеров, созданный специально для Kubernetes.",
     "Implements only what Kubernetes needs, which is a smaller surface than containerd."),
    ("lib-gvisor", "gVisor", "Безопасность и секреты", "https://gvisor.dev/docs/", "openSource", "sandboxing,kernel,isolation,google", "",
     "Application kernel providing strong container isolation.",
     "Прикладное ядро, обеспечивающее сильную изоляцию контейнеров.",
     "Intercepting syscalls in userspace costs some performance and buys real multi-tenant isolation."),
    ("lib-kata-containers", "Kata Containers", "Безопасность и секреты", "https://katacontainers.io/docs/", "openSource", "vm-isolation,containers,security,oci", "",
     "Runs containers inside lightweight virtual machines for hardware-level isolation.",
     "Запускает контейнеры внутри лёгких виртуальных машин для аппаратной изоляции.",
     "VM-grade isolation with a container interface, which suits running untrusted customer workloads."),
    ("lib-firecracker", "Firecracker", "Облако и деплой", "https://firecracker-microvm.github.io/", "openSource", "microvm,aws,fast-boot,serverless", "",
     "MicroVM technology behind AWS Lambda, booting in milliseconds.",
     "Технология microVM, лежащая в основе AWS Lambda, с запуском за миллисекунды.",
     "Millisecond boots with full VM isolation is what makes secure multi-tenant serverless possible."),

    # ---------- Операционные системы для контейнеров ----------
    ("lib-bottlerocket", "Bottlerocket", "Облако и деплой", "https://bottlerocket.dev/", "openSource", "container-os,aws,minimal,immutable", "",
     "Minimal immutable Linux distribution purpose-built for running containers.",
     "Минималистичный неизменяемый дистрибутив Linux, созданный для запуска контейнеров.",
     "No package manager and no shell means a far smaller attack surface than a general-purpose OS."),
    ("lib-talos-linux", "Talos Linux", "Service mesh и Kubernetes", "https://www.talos.dev/latest/", "openSource", "kubernetes,immutable,api-driven,minimal", "",
     "Immutable Kubernetes-only Linux managed entirely through an API.",
     "Неизменяемый Linux исключительно для Kubernetes, управляемый полностью через API.",
     "There is no SSH at all — configuration changes go through the API, which forces real reproducibility."),

    # ---------- Локальный и лёгкий Kubernetes ----------
    ("lib-k3d", "k3d", "Service mesh и Kubernetes", "https://k3d.io/", "openSource", "k3s,docker,local,fast", "brew install k3d",
     "Runs k3s clusters inside Docker for fast local Kubernetes.",
     "Запускает кластеры k3s внутри Docker для быстрого локального Kubernetes.",
     "Multi-node local clusters start in seconds, which suits testing scheduling behaviour."),
    ("lib-minikube", "Minikube", "Service mesh и Kubernetes", "https://minikube.sigs.k8s.io/docs/", "openSource", "local,kubernetes,addons,learning", "",
     "Local Kubernetes cluster with a large set of optional addons.",
     "Локальный кластер Kubernetes с большим набором опциональных дополнений.",
     "Its addons enable ingress and metrics with one command, which suits learning and demos."),
    ("lib-microk8s", "MicroK8s", "Service mesh и Kubernetes", "https://microk8s.io/docs", "openSource", "canonical,lightweight,snap,edge", "",
     "Lightweight single-package Kubernetes from Canonical.",
     "Лёгкий Kubernetes в одном пакете от Canonical.",
     "Its snap packaging makes installation and upgrades a single command on Ubuntu."),
    ("lib-k0s", "k0s", "Service mesh и Kubernetes", "https://docs.k0sproject.io/", "openSource", "lightweight,single-binary,zero-friction,production", "",
     "Kubernetes distribution shipped as a single binary with no OS dependencies.",
     "Дистрибутив Kubernetes в виде одного бинарника без зависимостей от ОС.",
     "One binary and no host dependencies makes it unusually easy to run on unusual hardware."),
    ("lib-rancher", "Rancher", "Service mesh и Kubernetes", "https://ranchermanager.docs.rancher.com/", "openSource", "multi-cluster,management,ui,suse", "",
     "Multi-cluster Kubernetes management platform with a full web interface.",
     "Платформа управления множеством кластеров Kubernetes с полноценным веб-интерфейсом.",
     "Managing clusters across several clouds from one place is where it earns its keep."),
    ("lib-openshift", "OpenShift", "Service mesh и Kubernetes", "https://docs.redhat.com/en/documentation/openshift_container_platform", "mixed", "redhat,enterprise,kubernetes,opinionated", "",
     "Red Hat's enterprise Kubernetes platform with integrated developer tooling.",
     "Корпоративная платформа Kubernetes от Red Hat с интегрированными инструментами разработки.",
     "Its stricter security defaults reject containers running as root, which surprises most first deployments."),
    ("lib-nomad", "Nomad", "Облако и деплой", "https://developer.hashicorp.com/nomad/docs", "openSource", "orchestration,simple,hashicorp,multi-workload", "",
     "Workload orchestrator running containers, binaries and virtual machines.",
     "Оркестратор нагрузок, запускающий контейнеры, бинарники и виртуальные машины.",
     "Substantially simpler than Kubernetes, and it schedules non-container workloads Kubernetes cannot."),
    ("lib-docker-swarm", "Docker Swarm", "Облако и деплой", "https://docs.docker.com/engine/swarm/", "openSource", "orchestration,simple,built-in,compose", "",
     "Container orchestration built into Docker, configured with compose files.",
     "Оркестрация контейнеров, встроенная в Docker и настраиваемая через compose-файлы.",
     "In maintenance rather than active development, but still the simplest path to multi-host containers."),

    # ---------- Виртуализация ----------
    ("lib-lxd", "LXD", "Облако и деплой", "https://documentation.ubuntu.com/lxd/", "openSource", "system-containers,vm,canonical,lightweight", "",
     "System container and virtual machine manager from Canonical.",
     "Менеджер системных контейнеров и виртуальных машин от Canonical.",
     "System containers behave like lightweight VMs, which suits workloads that expect a full init system."),
    ("lib-incus", "Incus", "Облако и деплой", "https://linuxcontainers.org/incus/docs/main/", "openSource", "fork,containers,vm,community", "",
     "Community fork of LXD under the Linux Containers project.",
     "Форк LXD под управлением сообщества в рамках проекта Linux Containers.",
     "Forked after LXD moved under Canonical's CLA, and now carries much of the community development."),
    ("lib-proxmox", "Proxmox VE", "Облако и деплой", "https://pve.proxmox.com/pve-docs/", "openSource", "virtualization,kvm,lxc,web-ui", "",
     "Open-source virtualization platform combining KVM virtual machines and LXC containers.",
     "Открытая платформа виртуализации, объединяющая виртуальные машины KVM и контейнеры LXC.",
     "The standard choice for a self-hosted homelab or small-office virtualization host."),
]
