# -*- coding: utf-8 -*-
"""Stage 5 library pack AU: auth providers, passwordless and passkeys, web3 login, framework auth."""

LIBS_5AU = [
    # ---------- Провайдеры идентификации ----------
    ("lib-stack-auth", "Stack Auth", "Аутентификация", "https://docs.stack-auth.com/", "openSource", "open-source,nextjs,self-host,clerk-alternative", "npm i @stackframe/stack",
     "Open-source authentication and user management, an alternative to Clerk.",
     "Открытая аутентификация и управление пользователями, альтернатива Clerk.",
     "Self-hostable, which removes the per-user pricing that hosted auth services charge."),
    ("lib-okta", "Okta", "Аутентификация", "https://developer.okta.com/docs/", "paid", "enterprise,sso,workforce,saml", "",
     "Enterprise identity platform for workforce and customer authentication.",
     "Корпоративная платформа идентификации для сотрудников и клиентов.",
     "Enterprise buyers frequently require it, which often decides the choice regardless of technical merit."),
    ("lib-amazon-cognito", "Amazon Cognito", "Аутентификация", "https://docs.aws.amazon.com/cognito/", "freeTier", "aws,user-pools,oauth,scalable", "",
     "AWS user directory and authentication service.",
     "Служба каталога пользователей и аутентификации от AWS.",
     "Cheap at scale and awkward to work with — budget more integration time than the docs suggest."),
    ("lib-entra-external-id", "Microsoft Entra External ID", "Аутентификация", "https://learn.microsoft.com/en-us/entra/external-id/", "freeTier", "microsoft,customer-identity,b2c,policies", "",
     "Microsoft's customer identity service, formerly Azure AD B2C.",
     "Служба клиентской идентификации Microsoft, ранее Azure AD B2C.",
     "Its custom policy language is powerful and genuinely difficult — plan for a learning curve."),
    ("lib-firebase-auth", "Firebase Authentication", "Аутентификация", "https://firebase.google.com/docs/auth", "freeTier", "google,mobile,providers,simple", "",
     "Authentication service with many social providers and mobile SDKs.",
     "Служба аутентификации с множеством социальных провайдеров и мобильными SDK.",
     "The fastest path to working login in a mobile app, and hard to migrate away from later."),

    # ---------- Беспарольная аутентификация и passkeys ----------
    ("lib-webauthn", "WebAuthn", "Аутентификация", "https://developer.mozilla.org/en-US/docs/Web/API/Web_Authentication_API", "free", "standard,passkeys,phishing-resistant,browser", "",
     "The browser standard behind passkeys and hardware security keys.",
     "Браузерный стандарт, лежащий в основе passkey и аппаратных ключей безопасности.",
     "Phishing resistance is structural here — the credential is bound to the origin and cannot be replayed."),
    ("lib-passkeys", "Passkeys", "Аутентификация", "https://passkeys.dev/", "free", "passwordless,fido,sync,cross-device", "",
     "Passwordless credentials that sync across a user's devices.",
     "Беспарольные учётные данные, синхронизируемые между устройствами пользователя.",
     "Keep a fallback method — account recovery is the hard part of any passkey rollout."),
    ("lib-simplewebauthn", "SimpleWebAuthn", "Аутентификация", "https://simplewebauthn.dev/docs/", "openSource", "webauthn,typescript,server,browser", "npm i @simplewebauthn/server",
     "TypeScript libraries for implementing WebAuthn on both server and browser.",
     "TypeScript-библиотеки для реализации WebAuthn на сервере и в браузере.",
     "It handles the attestation parsing that makes raw WebAuthn implementation error-prone."),
    ("lib-hanko", "Hanko", "Аутентификация", "https://docs.hanko.io/", "openSource", "passkeys,passwordless,self-host,components", "",
     "Open-source passkey-first authentication with drop-in web components.",
     "Открытая аутентификация с приоритетом passkey и готовыми веб-компонентами.",
     "Its prebuilt component gives a working passkey flow without designing one yourself."),
    ("lib-corbado", "Corbado", "Аутентификация", "https://docs.corbado.com/", "freeTier", "passkeys,fallback,integration,analytics", "",
     "Passkey authentication with automatic fallback for unsupported devices.",
     "Аутентификация по passkey с автоматическим откатом для неподдерживаемых устройств.",
     "Device support is still uneven, so the fallback path is what makes passkeys deployable today."),
    ("lib-passage", "Passage by 1Password", "Аутентификация", "https://docs.passage.id/", "freeTier", "passkeys,1password,passwordless,elements", "",
     "Passwordless authentication service from 1Password.",
     "Служба беспарольной аутентификации от 1Password.",
     "Its prebuilt elements cover the whole passkey enrolment and login flow."),
    ("lib-magic-link", "Magic", "Аутентификация", "https://magic.link/docs", "freeTier", "passwordless,email,wallet,sdk", "npm i magic-sdk",
     "Passwordless login via email links, with optional wallet support.",
     "Беспарольный вход по ссылкам в письме с опциональной поддержкой кошельков.",
     "Email deliverability becomes your login availability — monitor it as a production dependency."),

    # ---------- Web3 аутентификация ----------
    ("lib-privy", "Privy", "Web3 и блокчейн", "https://docs.privy.io/", "freeTier", "web3,embedded-wallets,onboarding,auth", "npm i @privy-io/react-auth",
     "Authentication with embedded wallets for onboarding non-crypto users.",
     "Аутентификация со встроенными кошельками для онбординга пользователей без криптоопыта.",
     "Embedded wallets let someone use a web3 app without ever installing a browser extension."),
    ("lib-dynamic-xyz", "Dynamic", "Web3 и блокчейн", "https://docs.dynamic.xyz/", "freeTier", "web3,wallets,auth,multi-chain", "npm i @dynamic-labs/sdk-react-core",
     "Wallet connection and authentication across many chains.",
     "Подключение кошельков и аутентификация в множестве блокчейнов.",
     "Its wallet connector handles the long tail of wallets that hand-rolled integrations miss."),
    ("lib-web3auth", "Web3Auth", "Web3 и блокчейн", "https://web3auth.io/docs/", "freeTier", "mpc,social-login,keys,non-custodial", "npm i @web3auth/modal",
     "Non-custodial key management using social logins and MPC.",
     "Некастодиальное управление ключами через социальные логины и MPC.",
     "Splitting the key across parties means a social login never gives anyone full custody."),

    # ---------- Аутентификация в фреймворках ----------
    ("lib-iron-session", "Iron Session", "Аутентификация", "https://github.com/vvo/iron-session", "openSource", "stateless,cookies,encrypted,nextjs", "npm i iron-session",
     "Stateless sessions stored in signed and encrypted cookies.",
     "Stateless-сессии в подписанных и зашифрованных cookie.",
     "No session store to run, at the cost of not being able to revoke a session server-side."),
    ("lib-devise", "Devise", "Backend и API", "https://github.com/heartcombo/devise", "openSource", "rails,ruby,authentication,modular", "gem install devise",
     "The standard authentication solution for Rails applications.",
     "Стандартное решение аутентификации для приложений Rails.",
     "Its modules cover confirmation, lockout and recovery, which are the parts people forget to build."),
    ("lib-spring-security", "Spring Security", "JVM экосистема", "https://docs.spring.io/spring-security/reference/", "openSource", "java,spring,authorization,filters", "",
     "Comprehensive authentication and authorization for Spring applications.",
     "Полноценная аутентификация и авторизация для приложений Spring.",
     "Powerful and easy to misconfigure — its filter chain rewards reading the reference properly."),
    ("lib-laravel-sanctum", "Laravel Sanctum", "Backend и API", "https://laravel.com/docs/sanctum", "openSource", "laravel,tokens,spa,api", "composer require laravel/sanctum",
     "Lightweight API token and SPA authentication for Laravel.",
     "Лёгкая аутентификация API-токенами и для SPA в Laravel.",
     "Its SPA mode uses cookies rather than tokens, which avoids storing credentials in the browser."),
    ("lib-doorkeeper", "Doorkeeper", "Backend и API", "https://doorkeeper.gitbook.io/guides", "openSource", "oauth2,rails,provider,ruby", "gem install doorkeeper",
     "OAuth 2 provider for Rails applications.",
     "Провайдер OAuth 2 для приложений Rails.",
     "Use it when you need to be an OAuth provider — being a consumer is a much simpler problem."),
    ("lib-django-allauth", "django-allauth", "Backend и API", "https://docs.allauth.org/", "openSource", "django,social-login,providers,mfa", "pip install django-allauth",
     "Authentication for Django covering local accounts, social login and MFA.",
     "Аутентификация для Django с локальными аккаунтами, социальным входом и MFA.",
     "It supports dozens of social providers, which is most of the value over Django's built-in auth."),
    ("lib-flask-login", "Flask-Login", "Backend и API", "https://flask-login.readthedocs.io/", "openSource", "flask,sessions,python,minimal", "pip install flask-login",
     "Session management for Flask applications.",
     "Управление сессиями для приложений Flask.",
     "It handles sessions only — password hashing and registration remain entirely yours to build."),
    ("lib-nextauth", "NextAuth.js", "Аутентификация", "https://next-auth.js.org/", "openSource", "nextjs,providers,legacy,sessions", "npm i next-auth",
     "Authentication for Next.js, now continued as Auth.js.",
     "Аутентификация для Next.js, продолженная как Auth.js.",
     "New projects should start on Auth.js — this name refers to the older Next.js-only line."),
]
