# -*- coding: utf-8 -*-
"""Stage 5 pricing pack J: object storage, image delivery and CDN services."""

PAID_5J = [
("paid-backblaze-b2","Backblaze B2 (pricing)","Облако и деплой","https://www.backblaze.com/cloud-storage/pricing","paid","storage,pricing,per-gb,egress",
 "Object storage billed per gigabyte stored, with free egress to partner networks.",
 "Объектное хранилище с оплатой за гигабайт хранения и бесплатным трафиком к партнёрским сетям.",
 "Free egress through Cloudflare is where the real saving over S3 comes from, not the storage rate.",
 "usage","from ~$6 per TB per month","10GB free storage","https://www.backblaze.com/cloud-storage/pricing"),
("paid-wasabi","Wasabi (pricing)","Облако и деплой","https://wasabi.com/cloud-object-storage/pricing","paid","storage,pricing,flat,no-egress",
 "Flat per-terabyte storage pricing with no egress or request charges.",
 "Фиксированная цена за терабайт хранения без платы за трафик и запросы.",
 "Its 90-day minimum retention means short-lived data is billed as if it stayed for months.",
 "usage","from ~$6.99 per TB per month","free trial","https://wasabi.com/cloud-object-storage/pricing"),
("paid-filebase","Filebase (pricing)","Облако и деплой","https://filebase.com/pricing/","paid","storage,pricing,per-gb,ipfs",
 "Decentralized storage gateway billed per gigabyte stored and transferred.",
 "Шлюз децентрализованного хранения с оплатой за гигабайт хранения и передачи.",
 "You pay for the S3 interface and pinning, which raw IPFS would leave you to operate yourself.",
 "usage","from ~$5.99 per TB per month","free tier of 5GB","https://filebase.com/pricing/"),
("paid-cloudflare-images","Cloudflare Images (pricing)","Изображения и дизайн","https://developers.cloudflare.com/images/pricing/","paid","images,pricing,per-image,delivery",
 "Image storage and delivery billed per stored image and per images delivered.",
 "Хранение и доставка изображений с оплатой за хранимое изображение и за доставленные изображения.",
 "Variants cost nothing extra, so serving many sizes from one original is the efficient pattern.",
 "usage","from ~$5 per 100k stored images","free tier via transformations","https://developers.cloudflare.com/images/pricing/"),
("paid-fastly-io","Fastly Image Optimizer (pricing)","Изображения и дизайн","https://www.fastly.com/pricing","paid","cdn,pricing,per-request,add-on",
 "Edge image transformation billed as an add-on to Fastly CDN usage.",
 "Преобразование изображений на edge как дополнение к использованию CDN Fastly.",
 "Only makes sense if Fastly is already your CDN — as a standalone image service it is expensive.",
 "usage","custom quote (add-on to CDN usage)","free trial credit","https://www.fastly.com/pricing"),
("paid-akamai-image-manager","Akamai Image & Video Manager (pricing)","Изображения и дизайн","https://www.akamai.com/products/image-and-video-manager","paid","cdn,pricing,enterprise,add-on",
 "Image and video optimization sold as an add-on to Akamai delivery contracts.",
 "Оптимизация изображений и видео как дополнение к контрактам доставки Akamai.",
 "Enterprise CDN contract territory — not something bought independently for a single site.",
 "custom","custom quote","product demo","https://www.akamai.com/products/image-and-video-manager"),
("paid-keycdn","KeyCDN (pricing)","Облако и деплой","https://www.keycdn.com/pricing","paid","cdn,pricing,per-gb,pay-as-you-go",
 "Content delivery billed per gigabyte transferred, varying by region.",
 "Доставка контента с оплатой за переданный гигабайт, ставка зависит от региона.",
 "No monthly minimum, which makes it viable for a low-traffic site that a CDN contract would not.",
 "usage","from ~$0.04 per GB","free trial credit","https://www.keycdn.com/pricing"),
("paid-devin","Devin (pricing)","Разработка и DevOps","https://devin.ai/pricing","paid","agent,pricing,acu,subscription",
 "Autonomous coding agent billed in agent compute units on a monthly plan.",
 "Автономный агент кодирования с оплатой в единицах агентных вычислений по месячному плану.",
 "Cost per completed task varies enormously with task clarity — pilot on well-scoped work first.",
 "subscription","from ~$20 per month plus usage","free trial credit","https://devin.ai/pricing"),
("paid-amp-code","Amp (pricing)","Разработка и DevOps","https://ampcode.com/manual#pricing","paid","agent,pricing,usage,tokens",
 "Agentic coding tool billed by token usage rather than a seat licence.",
 "Агентный инструмент кодирования с оплатой по расходу токенов, а не за место.",
 "Usage billing suits occasional heavy sessions better than a flat per-seat subscription.",
 "usage","pay-as-you-go by token usage","free trial credit","https://ampcode.com/manual#pricing"),
("paid-augment-code","Augment Code (pricing)","Разработка и DevOps","https://www.augmentcode.com/pricing","paid","assistant,pricing,per-user,subscription",
 "Codebase-aware assistant billed per developer per month.",
 "Ассистент с пониманием кодовой базы и оплатой за разработчика в месяц.",
 "Its retrieval over huge repositories is what justifies the premium over generic completion tools.",
 "subscription","from ~$50 per user per month","free trial","https://www.augmentcode.com/pricing"),
("paid-greptile","Greptile (pricing)","Тестирование и качество","https://www.greptile.com/pricing","paid","code-review,pricing,per-developer,subscription",
 "AI code review billed per active developer per month.",
 "AI-ревью кода с оплатой за активного разработчика в месяц.",
 "Billing on active developers rather than repository count suits a monorepo team well.",
 "subscription","from ~$30 per developer per month","free trial","https://www.greptile.com/pricing"),
("paid-ellipsis","Ellipsis (pricing)","Тестирование и качество","https://www.ellipsis.dev/pricing","paid","code-review,pricing,per-seat,subscription",
 "AI pull request reviewer billed per seat.",
 "AI-ревьюер pull request с оплатой за место.",
 "Free for open-source repositories, which makes evaluating it on real code straightforward.",
 "subscription","from ~$20 per seat per month","free for open source","https://www.ellipsis.dev/pricing"),
("paid-vast-ai","Vast.ai (pricing)","Локальные модели","https://vast.ai/pricing","paid","gpu,pricing,per-hour,marketplace",
 "GPU rental billed per hour at rates set by individual hosts.",
 "Аренда GPU с почасовой оплатой по ставкам, устанавливаемым отдельными хостами.",
 "Interruptible instances cost a fraction of on-demand, which suits checkpointed training runs.",
 "usage","from ~$0.20 per hour","free trial credit","https://vast.ai/pricing"),
("paid-midjourney","Midjourney (pricing)","Изображения и дизайн","https://docs.midjourney.com/hc/en-us/articles/29273914197901","paid","image-generation,pricing,subscription,gpu-minutes",
 "Image generation sold as monthly plans with fast GPU time allowances.",
 "Генерация изображений по месячным планам с квотой быстрого GPU-времени.",
 "The lower tiers exhaust fast hours quickly, after which generation queues behind other users.",
 "subscription","from ~$10 per month","no free tier","https://docs.midjourney.com/hc/en-us/articles/29273914197901"),
("paid-magnific","Magnific AI (pricing)","Изображения и дизайн","https://magnific.ai/pricing","paid","upscaling,pricing,credits,subscription",
 "AI upscaling sold as monthly credit allowances.",
 "AI-апскейлинг с месячной квотой кредитов.",
 "Each upscale consumes credits by output size, so large images drain a plan fast.",
 "subscription","from ~$39 per month","no free tier","https://magnific.ai/pricing"),
("paid-freepik-api","Freepik API (pricing)","Изображения и дизайн","https://www.freepik.com/api/pricing","paid","stock,pricing,credits,licensing",
 "Stock assets and generation sold as API credits with commercial licensing.",
 "Стоковые ресурсы и генерация в виде API-кредитов с коммерческой лицензией.",
 "The licence covering commercial use is a substantial part of what the credits buy.",
 "credits","from ~$0.004 per credit","free trial credits","https://www.freepik.com/api/pricing"),
("paid-prodigy","Prodigy (pricing)","Данные и ML","https://prodi.gy/buy","paid","annotation,pricing,one-time,perpetual",
 "Annotation tool sold as a one-time perpetual licence per user.",
 "Инструмент разметки с единоразовой бессрочной лицензией на пользователя.",
 "A perpetual licence with no subscription is unusual now, and cheap over a project's life.",
 "one-time","from ~$390 per user","free demo","https://prodi.gy/buy"),
("paid-encord","Encord (pricing)","Компьютерное зрение","https://encord.com/pricing/","paid","annotation,pricing,enterprise,custom",
 "Enterprise annotation platform sold on annual contracts.",
 "Корпоративная платформа разметки по годовым контрактам.",
 "Priced for teams running annotation as an ongoing operation, not a one-off dataset build.",
 "custom","custom quote","free trial","https://encord.com/pricing/"),
("paid-v7-darwin","V7 (pricing)","Компьютерное зрение","https://www.v7labs.com/pricing","paid","annotation,pricing,per-seat,enterprise",
 "Annotation platform billed per seat with usage tiers.",
 "Платформа разметки с оплатой за место и тарифами по объёму использования.",
 "Its medical imaging support is the reason to pay over open-source annotation tools.",
 "subscription","custom quote (per seat)","free trial","https://www.v7labs.com/pricing"),
("paid-labelbox-2","Labelbox (pricing)","Данные и ML","https://labelbox.com/pricing/","paid","annotation,pricing,units,subscription",
 "Data labelling billed in labelling units plus platform fees.",
 "Разметка данных с оплатой в единицах разметки плюс плата за платформу.",
 "Its free tier covers a small dataset fully, which makes evaluation straightforward.",
 "subscription","free tier, then custom quote","free tier","https://labelbox.com/pricing/"),
("paid-kili-technology","Kili Technology (pricing)","Данные и ML","https://kili-technology.com/pricing","paid","annotation,pricing,per-seat,custom",
 "Annotation platform sold per seat on annual contracts.",
 "Платформа разметки с оплатой за место по годовым контрактам.",
 "Its quality metrics are the differentiator when annotation is outsourced at scale.",
 "custom","custom quote","free trial","https://kili-technology.com/pricing"),
("paid-superannotate","SuperAnnotate (pricing)","Данные и ML","https://www.superannotate.com/pricing","paid","annotation,pricing,per-seat,marketplace",
 "Annotation platform billed per seat, with annotation teams sold separately.",
 "Платформа разметки с оплатой за место; команды разметчиков оплачиваются отдельно.",
 "Platform and workforce are separate line items — a quote for one understates the total.",
 "custom","custom quote","free trial","https://www.superannotate.com/pricing"),
("paid-scale-ai","Scale AI (pricing)","Данные и ML","https://scale.com/pricing","paid","labeling,pricing,per-label,managed",
 "Managed labelling billed per labelled item, varying by task complexity.",
 "Управляемая разметка с оплатой за размеченный элемент в зависимости от сложности задачи.",
 "Per-item pricing makes budgeting easy and makes large datasets genuinely expensive.",
 "usage","custom quote (per labelled item)","product demo","https://scale.com/pricing"),
("paid-surge-ai","Surge AI (pricing)","Данные и ML","https://www.surgehq.ai/pricing","paid","human-data,pricing,per-task,quality",
 "Human data collection billed per completed task.",
 "Сбор данных от людей с оплатой за выполненную задачу.",
 "It pays annotators above market rate, which raises both quality and your per-task cost.",
 "usage","custom quote (per task)","product demo","https://www.surgehq.ai/pricing"),
("paid-toloka","Toloka (pricing)","Данные и ML","https://toloka.ai/pricing/","paid","crowdsourcing,pricing,per-task,commission",
 "Crowdsourcing billed as the price you set per task plus a platform commission.",
 "Краудсорсинг с оплатой по установленной вами цене за задачу плюс комиссия платформы.",
 "You set the reward, so quality and speed are directly under your control — and your budget.",
 "usage","your task price plus platform commission","free trial credit","https://toloka.ai/pricing/"),
("paid-mturk","Amazon Mechanical Turk (pricing)","Данные и ML","https://aws.amazon.com/mturk/pricing/","paid","crowdsourcing,pricing,commission,per-task",
 "Crowdsourcing billed as your task reward plus an AWS commission per assignment.",
 "Краудсорсинг с оплатой вашего вознаграждения за задачу плюс комиссия AWS за назначение.",
 "The commission rises for tasks needing multiple workers, which quality control usually requires.",
 "usage","20% commission on top of your task reward","free tier credit","https://aws.amazon.com/mturk/pricing/"),
("paid-buildkite","Buildkite (pricing)","Разработка и DevOps","https://buildkite.com/pricing","paid","ci,pricing,per-user,hybrid",
 "Hosted CI control plane billed per user, with agents on your own infrastructure.",
 "Размещённый управляющий слой CI с оплатой за пользователя; агенты — на вашей инфраструктуре.",
 "You pay for orchestration and supply the compute, which is cheaper at high build volume.",
 "subscription","from ~$20 per user per month","free for small teams","https://buildkite.com/pricing"),
("paid-bamboo","Bamboo (pricing)","Разработка и DevOps","https://www.atlassian.com/software/bamboo/pricing","paid","ci,pricing,perpetual,agents",
 "On-premise CI server licensed by number of remote build agents.",
 "Локальный CI-сервер с лицензией по числу удалённых агентов сборки.",
 "Agent count, not user count, drives the price — parallelism is what you are actually buying.",
 "one-time","from ~$1200 per agent tier","free trial","https://www.atlassian.com/software/bamboo/pricing"),
("paid-travis-ci","Travis CI (pricing)","Разработка и DevOps","https://www.travis-ci.com/pricing/","paid","ci,pricing,credits,concurrency",
 "Hosted CI sold as build credits or concurrency-based plans.",
 "Размещённый CI в виде кредитов сборки или планов по числу параллельных задач.",
 "Its open-source free tier ended, which is why most projects migrated to GitHub Actions.",
 "subscription","from ~$64 per month","free trial credits","https://www.travis-ci.com/pricing/"),
("paid-octopus-deploy","Octopus Deploy (pricing)","Разработка и DevOps","https://octopus.com/pricing","paid","deployment,pricing,per-target,subscription",
 "Deployment automation billed by number of deployment targets.",
 "Автоматизация развёртывания с оплатой по числу целевых окружений.",
 "Target count grows with your infrastructure, so model it against your real environment list.",
 "subscription","from ~$360 per year for 10 targets","free tier for small deployments","https://octopus.com/pricing"),
("paid-buildjet","BuildJet (pricing)","Разработка и DevOps","https://buildjet.com/for-github-actions/pricing","paid","runners,pricing,per-minute,github-actions",
 "GitHub Actions runners billed per minute at roughly half GitHub's rate.",
 "Раннеры GitHub Actions с поминутной оплатой примерно вдвое дешевле тарифа GitHub.",
 "Cheaper per minute and faster per job, so the saving compounds on both axes.",
 "usage","from ~$0.004 per minute","free trial minutes","https://buildjet.com/for-github-actions/pricing"),
("paid-actuated","Actuated (pricing)","Разработка и DevOps","https://actuated.com/pricing","paid","runners,pricing,subscription,self-hosted",
 "Self-hosted runner orchestration billed as a monthly subscription per server.",
 "Оркестрация self-hosted раннеров с месячной подпиской за сервер.",
 "You supply the hardware; the subscription buys the microVM isolation and scheduling.",
 "subscription","from ~$249 per month","free trial","https://actuated.com/pricing"),
("paid-ddia","Designing Data-Intensive Applications (pricing)","Гайды и практики","https://dataintensive.net/buy.html","paid","book,pricing,one-time,reference",
 "Reference book on data systems, bought once in print or digital form.",
 "Справочная книга по системам данных, покупается один раз в печатном или цифровом виде.",
 "One of the few technical books worth buying in print — you will return to it for years.",
 "one-time","from ~$50 for the book","free sample chapter","https://dataintensive.net/buy.html"),
("paid-readwise","Readwise (pricing)","Книги и знания","https://readwise.io/pricing","paid","highlights,pricing,subscription,per-user",
 "Highlight collection and review sold as a monthly subscription.",
 "Сбор и повторение выделений по месячной подписке.",
 "Its Reader app is included, which changes the comparison against standalone read-later services.",
 "subscription","from ~$9.99 per month","free 30-day trial","https://readwise.io/pricing"),
("paid-kaedim","Kaedim (pricing)","Анимация и 3D","https://www.kaedim3d.com/pricing","paid","3d,pricing,per-model,subscription",
 "Concept-art-to-3D conversion billed per generated model on a monthly plan.",
 "Конвертация концепт-арта в 3D с оплатой за модель по месячному плану.",
 "Human quality control is included in the per-model price, which fully automated tools omit.",
 "subscription","from ~$150 per month","free trial models","https://www.kaedim3d.com/pricing"),
("paid-alpha3d","Alpha3D (pricing)","Анимация и 3D","https://www.alpha3d.io/pricing/","paid","3d,pricing,per-asset,ecommerce",
 "Automated 2D-to-3D conversion billed per generated asset.",
 "Автоматическая конвертация 2D в 3D с оплатой за созданный ассет.",
 "Per-asset pricing suits a product catalogue where you know the item count in advance.",
 "usage","custom quote (per asset)","free trial","https://www.alpha3d.io/pricing/"),
("paid-move-ai","Move AI (pricing)","Анимация и 3D","https://www.move.ai/pricing","paid","motion-capture,pricing,per-minute,subscription",
 "Markerless motion capture billed by minutes of processed footage.",
 "Безмаркерный захват движения с оплатой по минутам обработанного видео.",
 "Still far below traditional mocap studio rates, which is the comparison that matters.",
 "subscription","from ~$365 per month","free trial minutes","https://www.move.ai/pricing"),
("paid-rokoko","Rokoko (pricing)","Анимация и 3D","https://www.rokoko.com/products","paid","motion-capture,pricing,hardware,one-time",
 "Motion capture suits sold as hardware, with optional software subscriptions.",
 "Костюмы захвата движения продаются как оборудование с опциональной подпиской на софт.",
 "The suit is a one-time cost; check which software features need an ongoing subscription.",
 "one-time","from ~$2500 for a suit","free software tier","https://www.rokoko.com/products"),
("paid-layer-ai","Layer.ai (pricing)","Изображения и дизайн","https://layer.ai/pricing","paid","game-art,pricing,per-seat,studio",
 "Game art production platform sold per seat to studios.",
 "Платформа производства игрового арта с оплатой за место для студий.",
 "Priced for a studio pipeline rather than an individual artist experimenting.",
 "custom","custom quote (per seat)","product demo","https://layer.ai/pricing"),
("paid-soundraw","Soundraw (pricing)","Музыка и медиа","https://soundraw.io/pricing","paid","music,pricing,subscription,unlimited",
 "AI music generation on a monthly subscription with unlimited downloads.",
 "Генерация музыки по месячной подписке с неограниченными загрузками.",
 "Licence terms differ between personal and business plans — check before commercial release.",
 "subscription","from ~$16.99 per month","free generation without download","https://soundraw.io/pricing"),
("paid-minimax-hailuo","MiniMax Hailuo (pricing)","Видео и медиа","https://www.minimax.io/price","paid","video,pricing,per-generation,api",
 "Video generation billed per generated clip through the API.",
 "Генерация видео с оплатой за созданный клип через API.",
 "Cost per second of usable footage is the real metric — several attempts usually precede a keeper.",
 "usage","from ~$0.30 per video generation","free trial credit","https://www.minimax.io/price"),
("paid-synthesia","Synthesia (pricing)","Видео и медиа","https://www.synthesia.io/pricing","paid","avatars,pricing,minutes,subscription",
 "Avatar video platform billed by minutes of generated video per month.",
 "Платформа видео с аватарами и оплатой по минутам генерации в месяц.",
 "Custom avatars of a real person cost extra and require that person's recorded consent.",
 "subscription","from ~$29 per month","free demo video","https://www.synthesia.io/pricing"),
("paid-argil","Argil (pricing)","Видео и медиа","https://www.argil.ai/pricing","paid","avatars,pricing,subscription,videos",
 "Avatar clone video generation on a monthly plan with video quotas.",
 "Генерация видео с клоном-аватаром по месячному плану с квотой на видео.",
 "Built around producing many short videos from one clone, which is where the quota model fits.",
 "subscription","from ~$39 per month","free trial","https://www.argil.ai/pricing"),
]
