# -*- coding: utf-8 -*-
"""Stage 5 library pack AJ: state and forms, validation schemas, API clients, RPC and serialization."""

LIBS_5AJ = [
    # ---------- Состояние ----------
    ("lib-mobx", "MobX", "Состояние и данные", "https://mobx.js.org/README.html", "openSource", "reactive,observable,state,transparent", "npm i mobx",
     "Transparent reactive state management driven by observables.",
     "Прозрачное реактивное управление состоянием на основе наблюдаемых значений.",
     "Components re-render from tracked reads automatically, with no selector functions to maintain."),
    ("lib-recoil", "Recoil", "Состояние и данные", "https://recoiljs.org/docs/introduction/getting-started", "openSource", "react,atoms,facebook,experimental", "npm i recoil",
     "Atom-based state management for React, originally from Meta.",
     "Управление состоянием React на основе атомов, изначально из Meta.",
     "Development has stopped — Jotai offers the same atom model and is actively maintained."),

    # ---------- Маршрутизация и формы ----------
    ("lib-wouter", "Wouter", "UI и frontend", "https://github.com/molefrog/wouter", "openSource", "react,routing,tiny,hooks", "npm i wouter",
     "Minimal React router in roughly two kilobytes.",
     "Минималистичный React-роутер размером около двух килобайт.",
     "Covers hook-based routing for small apps where React Router's size is hard to justify."),
    ("lib-tanstack-form", "TanStack Form", "UI и frontend", "https://tanstack.com/form/latest/docs/overview", "openSource", "forms,type-safe,framework-agnostic,validation", "npm i @tanstack/react-form",
     "Type-safe form state management across React, Vue, Solid and Angular.",
     "Типобезопасное управление состоянием форм для React, Vue, Solid и Angular.",
     "Its validation adapters accept Zod or Valibot schemas, reusing types you already have."),
    ("lib-felte", "Felte", "UI и frontend", "https://felte.dev/docs/svelte/getting-started", "openSource", "svelte,forms,validation,extensible", "npm i felte",
     "Extensible form library for Svelte, Solid and React.",
     "Расширяемая библиотека форм для Svelte, Solid и React.",
     "Its extender API adds persistence or reporters without touching form logic."),
    ("lib-sveltekit-superforms", "Superforms", "UI и frontend", "https://superforms.rocks/", "openSource", "sveltekit,forms,progressive-enhancement,validation", "npm i sveltekit-superforms",
     "SvelteKit form library working with and without JavaScript enabled.",
     "Библиотека форм для SvelteKit, работающая с включённым и выключенным JavaScript.",
     "Progressive enhancement means the form still submits if the client bundle fails to load."),
    ("lib-conform", "Conform", "UI и frontend", "https://conform.guide/", "openSource", "react,forms,web-standards,progressive", "npm i @conform-to/react",
     "Form validation built on the browser's native constraint validation API.",
     "Валидация форм на основе нативного API проверки ограничений браузера.",
     "Building on the platform means server-side validation and client-side stay naturally in sync."),

    # ---------- Схемы валидации ----------
    ("lib-yup", "Yup", "Утилиты", "https://github.com/jquense/yup", "openSource", "validation,schema,javascript,forms", "npm i yup",
     "Schema validation library long paired with Formik.",
     "Библиотека валидации схем, давно используемая вместе с Formik.",
     "Zod's TypeScript inference is stronger — prefer it unless you already depend on Yup."),
    ("lib-joi", "Joi", "Утилиты", "https://joi.dev/api/", "openSource", "validation,schema,node,server-side", "npm i joi",
     "Powerful server-side object schema validation for Node.",
     "Мощная серверная валидация схем объектов для Node.",
     "Its conditional and dependency rules express constraints that simpler validators cannot."),
    ("lib-typebox", "TypeBox", "Утилиты", "https://github.com/sinclairzx81/typebox", "openSource", "json-schema,typescript,static-types,validation", "npm i @sinclair/typebox",
     "Builds JSON Schema and TypeScript types from a single definition.",
     "Строит JSON Schema и типы TypeScript из одного определения.",
     "Producing real JSON Schema means the same definition drives OpenAPI docs and runtime checks."),
    ("lib-io-ts", "io-ts", "Утилиты", "https://gcanti.github.io/io-ts/", "openSource", "runtime-types,functional,decoding,fp-ts", "npm i io-ts",
     "Runtime type validation built on fp-ts codecs.",
     "Рантайм-валидация типов на кодеках fp-ts.",
     "Its functional style suits fp-ts codebases; Zod is friendlier for everyone else."),
    ("lib-attrs", "attrs", "Утилиты", "https://www.attrs.org/", "openSource", "python,classes,boilerplate,validators", "pip install attrs",
     "Python classes without boilerplate, with validators and converters.",
     "Классы Python без шаблонного кода, с валидаторами и конвертерами.",
     "It predates and inspired dataclasses, and still offers features the standard library lacks."),
    ("lib-cattrs", "cattrs", "Утилиты", "https://catt.rs/", "openSource", "python,serialization,structuring,attrs", "pip install cattrs",
     "Structures and unstructures Python objects to and from plain data.",
     "Преобразует объекты Python в простые данные и обратно.",
     "Separating serialization from the class definition keeps model classes free of encoding concerns."),
    ("lib-voluptuous", "Voluptuous", "Утилиты", "https://github.com/alecthomas/voluptuous", "openSource", "python,validation,schema,simple", "pip install voluptuous",
     "Simple Python data validation library used widely in configuration handling.",
     "Простая библиотека валидации данных Python, широко используемая для конфигураций.",
     "Home Assistant validates every integration's configuration with it, which is a strong endorsement."),

    # ---------- Генерация клиентов и SDK ----------
    ("lib-orval", "Orval", "Backend и API", "https://orval.dev/", "openSource", "openapi,codegen,react-query,typescript", "npm i -D orval",
     "Generates typed API clients and React Query hooks from OpenAPI specs.",
     "Генерирует типизированные API-клиенты и хуки React Query из OpenAPI-спецификаций.",
     "It also generates MSW mocks from the same spec, so tests and client never drift."),
    ("lib-kubb", "Kubb", "Backend и API", "https://kubb.dev/", "openSource", "openapi,codegen,plugins,typescript", "npm i -D @kubb/cli",
     "Plugin-based generator turning OpenAPI specs into clients, types and mocks.",
     "Генератор на плагинах, превращающий OpenAPI-спецификации в клиенты, типы и моки.",
     "Its plugin model lets you emit exactly the artifacts your stack needs and nothing else."),
    ("lib-hey-api", "Hey API", "Backend и API", "https://heyapi.dev/", "openSource", "openapi,typescript,client,codegen", "npm i -D @hey-api/openapi-ts",
     "Modern TypeScript client generator for OpenAPI specifications.",
     "Современный генератор TypeScript-клиентов для OpenAPI-спецификаций.",
     "Its output is readable TypeScript you can actually debug, unlike heavily abstracted generators."),
    ("lib-speakeasy", "Speakeasy", "Backend и API", "https://www.speakeasy.com/docs", "freeTier", "sdk,codegen,openapi,multi-language", "",
     "Generates production-quality SDKs in many languages from an OpenAPI spec.",
     "Генерирует SDK продакшн-качества на многих языках из OpenAPI-спецификации.",
     "Generated SDKs include retries and pagination, which naive generators leave to the caller."),
    ("lib-stainless", "Stainless", "Backend и API", "https://www.stainless.com/docs", "paid", "sdk,codegen,quality,api-first", "",
     "SDK generation platform behind several major AI provider client libraries.",
     "Платформа генерации SDK, на которой построены клиентские библиотеки нескольких крупных AI-провайдеров.",
     "The OpenAI and Anthropic SDKs are generated with it, which is a useful quality reference."),
    ("lib-fern", "Fern", "Backend и API", "https://buildwithfern.com/learn", "freeTier", "sdk,docs,openapi,codegen", "",
     "Generates SDKs and API documentation from a single API definition.",
     "Генерирует SDK и документацию API из одного определения API.",
     "Docs and SDKs from one source removes the usual drift between them."),

    # ---------- Документация и клиенты API ----------
    ("lib-redocly", "Redocly", "Документация и контекст", "https://redocly.com/docs/", "mixed", "openapi,docs,linting,portal", "npm i -D @redocly/cli",
     "OpenAPI documentation rendering plus spec linting and bundling.",
     "Рендеринг документации OpenAPI вместе с линтингом и сборкой спецификаций.",
     "Its linter catches spec problems that break generated clients before anyone generates one."),
    ("lib-scalar", "Scalar", "Документация и контекст", "https://guides.scalar.com/", "openSource", "openapi,docs,api-client,modern", "npm i @scalar/api-reference",
     "Modern OpenAPI reference renderer with a built-in request client.",
     "Современный рендерер справочника OpenAPI со встроенным клиентом запросов.",
     "Readers can try endpoints inside the docs, which cuts the path from reading to a first call."),
    ("lib-swagger-ui", "Swagger UI", "Документация и контекст", "https://swagger.io/tools/swagger-ui/", "openSource", "openapi,docs,interactive,standard", "npm i swagger-ui",
     "The long-standing interactive renderer for OpenAPI specifications.",
     "Давний интерактивный рендерер спецификаций OpenAPI.",
     "Universally recognizable, though newer renderers are considerably faster on large specifications."),
    ("lib-bruno", "Bruno", "Тестовые и mock API", "https://docs.usebruno.com/", "openSource", "api-client,git-friendly,offline,collections", "",
     "API client storing collections as plain files in your repository.",
     "API-клиент, хранящий коллекции обычными файлами в вашем репозитории.",
     "Collections version and merge like code, which cloud-synced clients make awkward."),
    ("lib-hoppscotch", "Hoppscotch", "Тестовые и mock API", "https://docs.hoppscotch.io/", "openSource", "api-client,web,lightweight,self-host", "",
     "Lightweight open-source API client that runs in the browser.",
     "Лёгкий открытый API-клиент, работающий в браузере.",
     "Nothing to install, and self-hostable when requests must stay inside your network."),
    ("lib-insomnia", "Insomnia", "Тестовые и mock API", "https://docs.insomnia.rest/", "mixed", "api-client,graphql,grpc,design", "",
     "API client and design tool supporting REST, GraphQL and gRPC.",
     "API-клиент и инструмент проектирования с поддержкой REST, GraphQL и gRPC.",
     "Its gRPC support is unusual among general API clients and saves reaching for grpcurl."),
    ("lib-yaak", "Yaak", "Тестовые и mock API", "https://yaak.app/docs", "mixed", "api-client,desktop,rust,git-sync", "",
     "Desktop API client built in Rust with optional Git synchronization.",
     "Desktop API-клиент на Rust с опциональной синхронизацией через Git.",
     "Fast and offline-first, with none of the account requirements newer clients have added."),
    ("lib-postman-flows", "Postman Flows", "Тестовые и mock API", "https://learning.postman.com/docs/postman-flows/overview/", "freeTier", "postman,visual,workflows,no-code", "",
     "Visual workflow builder chaining API requests inside Postman.",
     "Визуальный конструктор workflow, связывающий API-запросы внутри Postman.",
     "Useful for prototyping a multi-step integration before writing any code for it."),
    ("lib-rapidapi", "RapidAPI", "Тестовые и mock API", "https://docs.rapidapi.com/", "freeTier", "marketplace,api-hub,discovery,billing", "",
     "API marketplace with unified authentication and billing across providers.",
     "Маркетплейс API с единой аутентификацией и биллингом для разных провайдеров.",
     "Convenient for discovery, though calling a provider directly is usually cheaper in production."),

    # ---------- RPC и сериализация ----------
    ("lib-connect-rpc", "Connect RPC", "Backend и API", "https://connectrpc.com/docs/introduction", "openSource", "grpc,http,browser,protobuf", "",
     "Protobuf RPC that works over plain HTTP and directly from browsers.",
     "Protobuf RPC, работающий поверх обычного HTTP и напрямую из браузеров.",
     "Its endpoints are curl-friendly, unlike gRPC's binary framing over HTTP/2."),
    ("lib-grpc-web", "gRPC-Web", "Backend и API", "https://github.com/grpc/grpc-web", "openSource", "grpc,browser,proxy,protobuf", "",
     "Brings gRPC to browsers through a translating proxy.",
     "Приносит gRPC в браузеры через транслирующий прокси.",
     "The required proxy is real infrastructure — Connect RPC avoids it entirely."),
    ("lib-twirp", "Twirp", "Backend и API", "https://twitchtv.github.io/twirp/docs/intro.html", "openSource", "rpc,protobuf,simple,http", "",
     "Simple protobuf RPC framework over HTTP from Twitch.",
     "Простой protobuf RPC-фреймворк поверх HTTP от Twitch.",
     "Deliberately smaller than gRPC — no streaming, and correspondingly less to operate."),
    ("lib-capnproto", "Cap'n Proto", "Backend и API", "https://capnproto.org/", "openSource", "serialization,zero-copy,rpc,fast", "",
     "Zero-copy serialization with no encoding or decoding step.",
     "Сериализация без копирования, не требующая шагов кодирования и декодирования.",
     "Reading a field is a pointer dereference, which is why it beats protobuf on latency-critical paths."),
    ("lib-flatbuffers", "FlatBuffers", "Backend и API", "https://flatbuffers.dev/", "openSource", "serialization,zero-copy,google,games", "",
     "Google's zero-copy serialization library, widely used in games.",
     "Библиотека сериализации без копирования от Google, широко используемая в играх.",
     "Accessing one field without parsing the whole buffer is what suits it to per-frame data."),
    ("lib-apache-avro", "Apache Avro", "Data engineering", "https://avro.apache.org/docs/", "openSource", "serialization,schema-evolution,kafka,compact", "",
     "Compact binary serialization with strong schema evolution rules.",
     "Компактная бинарная сериализация со строгими правилами эволюции схемы.",
     "Its schema evolution rules are why it dominates Kafka topics with long-lived data."),
    ("lib-apache-thrift", "Apache Thrift", "Backend и API", "https://thrift.apache.org/docs/", "openSource", "rpc,serialization,cross-language,facebook", "",
     "Cross-language RPC and serialization framework originating at Facebook.",
     "Кроссязыковой фреймворк RPC и сериализации, созданный в Facebook.",
     "Broad language coverage, though gRPC has taken over most new development."),
    ("lib-cbor", "CBOR", "Backend и API", "https://cbor.io/", "free", "serialization,binary,json-like,iot", "",
     "Compact binary format modelled on the JSON data model, an IETF standard.",
     "Компактный бинарный формат по модели данных JSON, стандарт IETF.",
     "Common in IoT and WebAuthn where JSON's size and parsing cost matter."),
    ("lib-bson", "BSON", "Backend и API", "https://bsonspec.org/", "openSource", "binary,json,mongodb,types", "",
     "Binary JSON encoding with extra types, used natively by MongoDB.",
     "Бинарная кодировка JSON с дополнительными типами, нативно используемая в MongoDB.",
     "Its date and binary types survive round trips that plain JSON turns into strings."),
]
