# -*- coding: utf-8 -*-
"""Stage 5 library pack AN: agent frameworks, model routing, API gateways, API observability and security."""

LIBS_5AN = [
    # ---------- Агентные и AI фреймворки ----------
    ("lib-voltagent", "VoltAgent", "AI и агенты", "https://voltagent.dev/docs/", "openSource", "typescript,agents,observability,tools", "npm i @voltagent/core",
     "TypeScript agent framework with built-in tracing of agent runs.",
     "TypeScript-фреймворк агентов со встроенной трассировкой запусков.",
     "Seeing each tool call and decision in a trace is what makes agent debugging tractable."),
    ("lib-motia", "Motia", "AI и агенты", "https://www.motia.dev/docs", "openSource", "backend,agents,steps,polyglot", "npx motia@latest create",
     "Unified backend framework where APIs, jobs and agents are all steps.",
     "Единый бэкенд-фреймворк, где API, задачи и агенты — это шаги одного типа.",
     "Steps can be written in different languages within one workflow, which few frameworks allow."),
    ("lib-genkit", "Genkit", "AI-фреймворки", "https://genkit.dev/docs/get-started/", "openSource", "google,ai,flows,typescript", "npm i genkit",
     "Google's framework for building AI features with typed flows and local tracing.",
     "Фреймворк Google для AI-функций с типизированными потоками и локальной трассировкой.",
     "Its developer UI replays flows locally, which shortens the prompt iteration loop considerably."),

    # ---------- Маршрутизация моделей ----------
    ("lib-semantic-router", "Semantic Router", "AI-фреймворки", "https://github.com/aurelio-labs/semantic-router", "openSource", "routing,embeddings,fast,decisions", "pip install semantic-router",
     "Routes requests by embedding similarity instead of an LLM call.",
     "Маршрутизирует запросы по сходству эмбеддингов вместо вызова LLM.",
     "An embedding comparison is milliseconds and cents cheaper than asking a model to classify intent."),
    ("lib-routellm", "RouteLLM", "AI-фреймворки", "https://github.com/lm-sys/RouteLLM", "openSource", "routing,cost-optimization,research,quality", "pip install routellm",
     "Routes queries between strong and weak models to cut cost at similar quality.",
     "Маршрутизирует запросы между сильными и слабыми моделями, снижая стоимость при сопоставимом качестве.",
     "Most queries do not need the largest model — the research behind it quantifies how many."),
    ("lib-notdiamond", "Not Diamond", "AI-фреймворки", "https://docs.notdiamond.ai/", "freeTier", "routing,model-selection,quality,automatic", "pip install notdiamond",
     "Automatically selects the best model per query from your configured set.",
     "Автоматически выбирает лучшую модель под каждый запрос из настроенного набора.",
     "Its router is trained on benchmarks, so it generalizes better than a hand-written heuristic."),
    ("lib-unify-ai", "Unify", "AI-фреймворки", "https://docs.unify.ai/", "freeTier", "routing,benchmarks,unified-api,providers", "",
     "Unified API across providers with routing driven by live quality and latency benchmarks.",
     "Единый API для разных провайдеров с маршрутизацией по актуальным замерам качества и задержки.",
     "Routing on live benchmarks adapts automatically when a provider degrades."),
    ("lib-requesty", "Requesty", "AI-фреймворки", "https://docs.requesty.ai/", "freeTier", "gateway,routing,caching,cost-tracking", "",
     "LLM gateway with routing, caching and per-request cost attribution.",
     "LLM-шлюз с маршрутизацией, кэшированием и учётом стоимости по каждому запросу.",
     "Per-request cost attribution is what lets you find which feature is actually driving the bill."),
    ("lib-cloudflare-ai-gateway", "Cloudflare AI Gateway", "AI-фреймворки", "https://developers.cloudflare.com/ai-gateway/", "freeTier", "gateway,caching,rate-limiting,analytics", "",
     "Proxy layer adding caching, rate limiting and analytics to any AI provider.",
     "Прокси-слой, добавляющий кэширование, ограничение частоты и аналитику к любому AI-провайдеру.",
     "Adding it is a base URL change, and the response caching often pays for itself immediately."),

    # ---------- API-шлюзы ----------
    ("lib-kong-gateway", "Kong Gateway", "Backend и API", "https://developer.konghq.com/gateway/", "mixed", "api-gateway,plugins,lua,scalable", "",
     "Widely deployed API gateway with a large plugin ecosystem.",
     "Широко распространённый API-шлюз с большой экосистемой плагинов.",
     "Its AI plugins add prompt caching and token rate limiting in front of LLM providers."),
    ("lib-apisix", "Apache APISIX", "Backend и API", "https://apisix.apache.org/docs/apisix/getting-started/", "openSource", "api-gateway,dynamic,etcd,high-performance", "",
     "High-performance API gateway with fully dynamic configuration.",
     "Высокопроизводительный API-шлюз с полностью динамической конфигурацией.",
     "Routes change without a reload, which matters when configuration updates are frequent."),
    ("lib-tyk", "Tyk", "Backend и API", "https://tyk.io/docs/", "openSource", "api-gateway,go,management,graphql", "",
     "Open-source API gateway and management platform written in Go.",
     "Открытый API-шлюз и платформа управления, написанные на Go.",
     "Its GraphQL federation support inside the gateway is unusual in this category."),
    ("lib-krakend", "KrakenD", "Backend и API", "https://www.krakend.io/docs/", "openSource", "api-gateway,aggregation,stateless,declarative", "",
     "Stateless API gateway that aggregates several backend calls into one response.",
     "Stateless API-шлюз, объединяющий несколько бэкенд-вызовов в один ответ.",
     "Aggregation at the gateway removes a whole backend-for-frontend service in many architectures."),
    ("lib-gravitee", "Gravitee", "Backend и API", "https://documentation.gravitee.io/", "openSource", "api-management,event-native,portal,access-control", "",
     "API management platform covering REST, GraphQL and event streams.",
     "Платформа управления API для REST, GraphQL и потоков событий.",
     "Its event-native support exposes Kafka topics as managed APIs, which most gateways cannot."),
    ("lib-wso2-api-manager", "WSO2 API Manager", "Backend и API", "https://apim.docs.wso2.com/", "openSource", "api-management,enterprise,governance,portal", "",
     "Full open-source API management suite with governance and a developer portal.",
     "Полный открытый набор управления API с governance и порталом разработчика.",
     "Enterprise-oriented and heavy — overkill unless you genuinely need formal API governance."),
    ("lib-zuplo", "Zuplo", "Backend и API", "https://zuplo.com/docs", "freeTier", "api-gateway,edge,typescript,programmable", "",
     "Programmable API gateway running at the edge, configured in TypeScript.",
     "Программируемый API-шлюз на edge, настраиваемый на TypeScript.",
     "Custom policies are ordinary TypeScript, avoiding the Lua or config-DSL layer other gateways impose."),
    ("lib-blackbird", "Blackbird", "Backend и API", "https://www.getambassador.io/docs/blackbird", "freeTier", "api-development,mocking,gateway,ambassador", "",
     "API development platform with instant mock endpoints and gateway integration.",
     "Платформа разработки API с мгновенными mock-эндпоинтами и интеграцией со шлюзом.",
     "Spinning up a mock from a spec lets client work start before any backend exists."),

    # ---------- Наблюдаемость API ----------
    ("lib-treblle", "Treblle", "Мониторинг и аналитика", "https://docs.treblle.com/", "freeTier", "api-observability,documentation,security-scoring,realtime", "",
     "API observability with automatic documentation and security scoring.",
     "Observability API с автоматической документацией и оценкой безопасности.",
     "Documentation generated from real traffic stays accurate, unlike a spec that drifts from the code."),
    ("lib-moesif", "Moesif", "Мониторинг и аналитика", "https://www.moesif.com/docs/", "freeTier", "api-analytics,monetization,billing,user-behaviour", "",
     "API analytics with usage-based billing and customer behaviour tracking.",
     "Аналитика API с биллингом по использованию и отслеживанием поведения клиентов.",
     "Its metering feeds usage-based billing directly, which few analytics tools attempt."),
    ("lib-apitoolkit", "APIToolkit", "Мониторинг и аналитика", "https://apitoolkit.io/docs/", "freeTier", "api-monitoring,anomalies,contracts,errors", "",
     "API monitoring detecting breaking changes and payload anomalies.",
     "Мониторинг API, обнаруживающий ломающие изменения и аномалии в полезной нагрузке.",
     "It flags a field that silently changed type, which error-rate monitoring never catches."),
    ("lib-akita", "Akita (Postman Insights)", "Мониторинг и аналитика", "https://www.postman.com/product/insights/", "freeTier", "api-discovery,traffic,drift,postman", "",
     "Infers API models from live traffic to reveal undocumented endpoints.",
     "Выводит модели API из живого трафика, выявляя недокументированные эндпоинты.",
     "Discovering endpoints nobody documented is usually the first step in taming a legacy API."),

    # ---------- Безопасность API ----------
    ("lib-escape-tech", "Escape", "Безопасность и секреты", "https://docs.escape.tech/", "paid", "api-security,dast,graphql,discovery", "",
     "API security testing with strong GraphQL and business-logic coverage.",
     "Тестирование безопасности API с сильным покрытием GraphQL и бизнес-логики.",
     "GraphQL introspection abuse is a class of flaw generic web scanners do not look for."),
    ("lib-42crunch", "42Crunch", "Безопасность и секреты", "https://docs.42crunch.com/", "freeTier", "openapi,security,audit,conformance", "",
     "OpenAPI security auditing and runtime conformance enforcement.",
     "Аудит безопасности OpenAPI и контроль соответствия во время выполнения.",
     "Auditing the spec catches missing auth definitions before a single line is implemented."),
    ("lib-stackhawk", "StackHawk", "Безопасность и секреты", "https://docs.stackhawk.com/", "freeTier", "dast,ci,api-security,developer-first", "",
     "Developer-focused dynamic security testing built to run in CI.",
     "Динамическое тестирование безопасности для разработчиков, рассчитанное на запуск в CI.",
     "Scanning against a running test environment in the pipeline catches issues pre-merge."),
    ("lib-salt-security", "Salt Security", "Безопасность и секреты", "https://salt.security/", "paid", "api-security,runtime,behavioural,enterprise", "",
     "Runtime API security using behavioural analysis to detect attacks.",
     "Безопасность API во время выполнения с поведенческим анализом для обнаружения атак.",
     "Behavioural baselining catches business-logic abuse that signature-based tools miss entirely."),
    ("lib-traceable", "Traceable", "Безопасность и секреты", "https://docs.traceable.ai/", "paid", "api-security,distributed-tracing,protection,discovery", "",
     "API security built on distributed tracing for full request context.",
     "Безопасность API на основе распределённой трассировки с полным контекстом запроса.",
     "Tracing across services shows the full path of an attack, not just the entry point."),
    ("lib-noname-security", "Akamai API Security", "Безопасность и секреты", "https://techdocs.akamai.com/api-security/docs", "paid", "api-security,discovery,posture,enterprise", "",
     "Enterprise API discovery and posture management, formerly Noname Security.",
     "Корпоративное обнаружение API и управление их защищённостью, ранее Noname Security.",
     "Its shadow API discovery finds endpoints that no inventory or spec ever recorded."),
    ("lib-impart-security", "Impart Security", "Безопасность и секреты", "https://docs.impart.security/", "paid", "api-security,waf,runtime,rules", "",
     "Runtime API protection with programmable detection rules.",
     "Защита API во время выполнения с программируемыми правилами обнаружения.",
     "Rules deploy without a restart, so a live attack can be mitigated in minutes."),
]
