# -*- coding: utf-8 -*-
"""Stage 5 pricing pack J: object storage, image delivery and CDN services."""

PAID_5J = [
("paid-backblaze-b2","Backblaze B2 (pricing)","Облако и деплой","https://www.backblaze.com/cloud-storage/pricing","paid","storage,pricing,per-gb,egress",
 "Object storage billed per gigabyte stored, with free egress to partner networks.",
 "Объектное хранилище с оплатой за гигабайт хранения и бесплатным трафиком к партнёрским сетям.",
 "Free egress through Cloudflare is where the real saving over S3 comes from, not the storage rate.",
 "usage","from ~$6 per TB per month","10GB free storage","https://www.backblaze.com/cloud-storage/pricing"),
("paid-wasabi","Wasabi (pricing)","Облако и деплой","https://wasabi.com/cloud-object-storage/pricing","paid","storage,pricing,flat,no-egress",
 "Flat per-terabyte storage pricing with no egress or request charges.",
 "Фиксированная цена за терабайт хранения без платы за трафик и запросы.",
 "Its 90-day minimum retention means short-lived data is billed as if it stayed for months.",
 "usage","from ~$6.99 per TB per month","free trial","https://wasabi.com/cloud-object-storage/pricing"),
("paid-filebase","Filebase (pricing)","Облако и деплой","https://filebase.com/pricing/","paid","storage,pricing,per-gb,ipfs",
 "Decentralized storage gateway billed per gigabyte stored and transferred.",
 "Шлюз децентрализованного хранения с оплатой за гигабайт хранения и передачи.",
 "You pay for the S3 interface and pinning, which raw IPFS would leave you to operate yourself.",
 "usage","from ~$5.99 per TB per month","free tier of 5GB","https://filebase.com/pricing/"),
("paid-cloudflare-images","Cloudflare Images (pricing)","Изображения и дизайн","https://developers.cloudflare.com/images/pricing/","paid","images,pricing,per-image,delivery",
 "Image storage and delivery billed per stored image and per images delivered.",
 "Хранение и доставка изображений с оплатой за хранимое изображение и за доставленные изображения.",
 "Variants cost nothing extra, so serving many sizes from one original is the efficient pattern.",
 "usage","from ~$5 per 100k stored images","free tier via transformations","https://developers.cloudflare.com/images/pricing/"),
("paid-fastly-io","Fastly Image Optimizer (pricing)","Изображения и дизайн","https://www.fastly.com/pricing","paid","cdn,pricing,per-request,add-on",
 "Edge image transformation billed as an add-on to Fastly CDN usage.",
 "Преобразование изображений на edge как дополнение к использованию CDN Fastly.",
 "Only makes sense if Fastly is already your CDN — as a standalone image service it is expensive.",
 "usage","custom quote (add-on to CDN usage)","free trial credit","https://www.fastly.com/pricing"),
("paid-akamai-image-manager","Akamai Image & Video Manager (pricing)","Изображения и дизайн","https://www.akamai.com/products/image-and-video-manager","paid","cdn,pricing,enterprise,add-on",
 "Image and video optimization sold as an add-on to Akamai delivery contracts.",
 "Оптимизация изображений и видео как дополнение к контрактам доставки Akamai.",
 "Enterprise CDN contract territory — not something bought independently for a single site.",
 "custom","custom quote","product demo","https://www.akamai.com/products/image-and-video-manager"),
("paid-keycdn","KeyCDN (pricing)","Облако и деплой","https://www.keycdn.com/pricing","paid","cdn,pricing,per-gb,pay-as-you-go",
 "Content delivery billed per gigabyte transferred, varying by region.",
 "Доставка контента с оплатой за переданный гигабайт, ставка зависит от региона.",
 "No monthly minimum, which makes it viable for a low-traffic site that a CDN contract would not.",
 "usage","from ~$0.04 per GB","free trial credit","https://www.keycdn.com/pricing"),
]
