# -*- coding: utf-8 -*-
"""Stage 5 library pack AP: animation, scroll effects, carousels, image editing, creative canvas."""

LIBS_5AP = [
    # ---------- Анимация ----------
    ("lib-framer-motion", "Motion for React", "Анимация и 3D", "https://motion.dev/docs/react", "openSource", "react,animation,gestures,layout", "npm i motion",
     "Declarative React animation with layout transitions and gesture support.",
     "Декларативная анимация React с переходами раскладки и поддержкой жестов.",
     "Its layout animations interpolate between positions automatically, which is hard to hand-write."),
    ("lib-svelte-motion", "Svelte Transitions", "Анимация и 3D", "https://svelte.dev/docs/svelte/transition", "openSource", "svelte,built-in,transitions,spring", "",
     "Svelte's built-in transition, animation and spring primitives.",
     "Встроенные примитивы переходов, анимаций и пружин в Svelte.",
     "Being part of the compiler means transitions add no runtime animation library to the bundle."),

    # ---------- Скролл-эффекты ----------
    ("lib-scrollreveal", "ScrollReveal", "Анимация и 3D", "https://scrollrevealjs.org/", "openSource", "scroll,reveal,animations,simple", "npm i scrollreveal",
     "Reveals elements with animation as they enter the viewport.",
     "Показывает элементы с анимацией по мере их появления в области просмотра.",
     "A plain IntersectionObserver now does most of this with no dependency at all."),
    ("lib-locomotive-scroll", "Locomotive Scroll", "Анимация и 3D", "https://scroll.locomotive.ca/docs/", "openSource", "smooth-scroll,parallax,detection,creative", "npm i locomotive-scroll",
     "Smooth scrolling with parallax and scroll-position detection.",
     "Плавная прокрутка с параллаксом и определением позиции скролла.",
     "Hijacking native scroll harms accessibility — verify keyboard and screen reader behaviour."),
    ("lib-splitting-js", "Splitting.js", "Анимация и 3D", "https://splitting.js.org/", "openSource", "text,characters,css-variables,animation", "npm i splitting",
     "Splits text into characters and words for per-element animation.",
     "Разбивает текст на символы и слова для поэлементной анимации.",
     "Splitting text breaks screen reader pronunciation — add an aria-label with the original string."),
    ("lib-splittype", "SplitType", "Анимация и 3D", "https://github.com/lukePeavey/SplitType", "openSource", "text,splitting,lightweight,gsap", "npm i split-type",
     "Lightweight text splitting utility often paired with GSAP.",
     "Лёгкая утилита разбиения текста, часто используемая вместе с GSAP.",
     "A free alternative to GSAP's own SplitText, which sits behind its paid tier."),
    ("lib-typed-js", "Typed.js", "Анимация и 3D", "https://github.com/mattboldt/typed.js/", "openSource", "typewriter,text,effect,simple", "npm i typed.js",
     "Typewriter text effect with configurable speed and looping.",
     "Эффект печатной машинки с настраиваемой скоростью и зацикливанием.",
     "Respect prefers-reduced-motion — a looping typewriter is exactly what that setting exists for."),
    ("lib-vanilla-tilt", "Vanilla Tilt", "Анимация и 3D", "https://micku7zu.github.io/vanilla-tilt.js/", "openSource", "tilt,3d,hover,dependency-free", "npm i vanilla-tilt",
     "Smooth 3D tilt effect on hover, with no dependencies.",
     "Плавный 3D-эффект наклона при наведении, без зависимостей.",
     "Hover-only by nature, so make sure the interaction it decorates works on touch devices too."),
    ("lib-atropos", "Atropos", "Анимация и 3D", "https://atroposjs.com/docs", "openSource", "parallax,3d,touch,lightweight", "npm i atropos",
     "3D parallax hover effect supporting both mouse and touch.",
     "3D-эффект параллакса при наведении с поддержкой мыши и касаний.",
     "Its touch support is what separates it from the many mouse-only tilt libraries."),

    # ---------- Карусели и галереи ----------
    ("lib-keen-slider", "Keen Slider", "UI и frontend", "https://keen-slider.io/docs", "openSource", "carousel,touch,lightweight,framework-agnostic", "npm i keen-slider",
     "Lightweight touch slider with no dependencies.",
     "Лёгкий тач-слайдер без зависимостей.",
     "Under five kilobytes, which matters when a carousel is a small part of the page."),
    ("lib-splide", "Splide", "UI и frontend", "https://splidejs.com/guides/getting-started/", "openSource", "carousel,accessible,lightweight,extensions", "npm i @splidejs/splide",
     "Accessible carousel with full keyboard and screen reader support.",
     "Доступная карусель с полной поддержкой клавиатуры и программ чтения с экрана.",
     "Accessibility is built in rather than an afterthought, which most carousel libraries get wrong."),
    ("lib-flickity", "Flickity", "UI и frontend", "https://flickity.metafizzy.co/", "mixed", "carousel,physics,touch,polished", "npm i flickity",
     "Touch carousel with physics-based momentum scrolling.",
     "Тач-карусель с инерционной прокруткой на основе физики.",
     "Free under GPL; commercial use in a closed-source product needs a paid licence."),
    ("lib-glide-js", "Glide.js", "UI и frontend", "https://glidejs.com/docs/", "openSource", "carousel,dependency-free,modular,es6", "npm i @glidejs/glide",
     "Dependency-free modular slider with a small footprint.",
     "Модульный слайдер без зависимостей с малым размером.",
     "Its modular build lets you include only the components your carousel actually uses."),
    ("lib-photoswipe", "PhotoSwipe", "Изображения и дизайн", "https://photoswipe.com/getting-started/", "openSource", "lightbox,gallery,touch,zoom", "npm i photoswipe",
     "Touch-friendly image gallery and lightbox with pinch zoom.",
     "Галерея изображений и лайтбокс с поддержкой касаний и масштабирования щипком.",
     "Its gesture handling on mobile is noticeably better than most lightbox libraries."),
    ("lib-lightgallery", "lightGallery", "Изображения и дизайн", "https://www.lightgalleryjs.com/docs/", "mixed", "lightbox,gallery,plugins,video", "npm i lightgallery",
     "Feature-rich lightbox supporting images, video and iframes.",
     "Функциональный лайтбокс с поддержкой изображений, видео и iframe.",
     "Free under GPL; a commercial licence is required for closed-source products."),
    ("lib-fancybox", "Fancybox", "Изображения и дизайн", "https://fancyapps.com/fancybox/", "mixed", "lightbox,modal,gallery,polished", "npm i @fancyapps/ui",
     "Polished lightbox and modal library.",
     "Отточенная библиотека лайтбоксов и модальных окон.",
     "Free for non-commercial use only — check the licence before shipping it in a product."),

    # ---------- Работа с изображениями ----------
    ("lib-cropperjs", "Cropper.js", "Изображения и дизайн", "https://fengyuanchen.github.io/cropperjs/", "openSource", "cropping,images,canvas,touch", "npm i cropperjs",
     "JavaScript image cropping with rotation, scaling and touch support.",
     "Обрезка изображений на JavaScript с поворотом, масштабированием и поддержкой касаний.",
     "Crop on the client before upload — it cuts both bandwidth and server-side processing."),
    ("lib-react-image-crop", "react-image-crop", "Изображения и дизайн", "https://github.com/DominicTobias/react-image-crop", "openSource", "react,cropping,responsive,accessible", "npm i react-image-crop",
     "Responsive React image cropping component with keyboard support.",
     "Адаптивный React-компонент обрезки изображений с поддержкой клавиатуры.",
     "It produces crop coordinates rather than an image, leaving the actual cropping to you."),
    ("lib-compressorjs", "Compressor.js", "Изображения и дизайн", "https://fengyuanchen.github.io/compressorjs/", "openSource", "compression,client-side,canvas,quality", "npm i compressorjs",
     "Client-side image compression before upload.",
     "Сжатие изображений на стороне клиента перед загрузкой.",
     "Compressing a phone photo before upload turns a multi-megabyte transfer into a few hundred kilobytes."),
    ("lib-browser-image-compression", "browser-image-compression", "Изображения и дизайн", "https://github.com/Donaldcwl/browser-image-compression", "openSource", "compression,web-worker,client-side,exif", "npm i browser-image-compression",
     "Compresses images in a Web Worker without blocking the main thread.",
     "Сжимает изображения в Web Worker, не блокируя основной поток.",
     "Running in a worker keeps the interface responsive while a large photo is processed."),

    # ---------- Творческий canvas ----------
    ("lib-paper-js", "Paper.js", "Графики и визуализация", "https://github.com/paperjs/paper.js", "openSource", "vector,canvas,scene-graph,bezier", "npm i paper",
     "Vector graphics scripting framework with a full scene graph.",
     "Фреймворк скриптования векторной графики с полноценным графом сцены.",
     "Its boolean path operations handle vector geometry that canvas drawing alone cannot express."),
    ("lib-rough-js", "Rough.js", "Графики и визуализация", "https://roughjs.com/", "openSource", "hand-drawn,sketchy,canvas,svg", "npm i roughjs",
     "Draws graphics in a hand-drawn, sketchy style.",
     "Рисует графику в стиле от руки, как эскиз.",
     "The library behind Excalidraw's look — a sketchy diagram reads as a draft, which changes feedback."),
    ("lib-two-js", "Two.js", "Графики и визуализация", "https://two.js.org/", "openSource", "2d,renderer-agnostic,svg,canvas", "npm i two.js",
     "Two-dimensional drawing API that renders to SVG, canvas or WebGL.",
     "API двумерного рисования с выводом в SVG, canvas или WebGL.",
     "One drawing API across renderers lets you switch output without rewriting the scene."),
    ("lib-zdog", "Zdog", "Анимация и 3D", "https://zzz.dog/", "openSource", "pseudo-3d,canvas,flat,designer-friendly", "npm i zdog",
     "Round, flat, designer-friendly pseudo-3D engine for canvas and SVG.",
     "Округлый плоский псевдо-3D движок для canvas и SVG, дружелюбный к дизайнерам.",
     "Under three kilobytes, which makes 3D-looking decoration affordable on a landing page."),
    ("lib-sketch-js", "Sketch.js", "Графики и визуализация", "https://soulwire.github.io/sketch.js/", "openSource", "canvas,boilerplate,creative-coding,minimal", "",
     "Minimal boilerplate for creative canvas experiments.",
     "Минималистичная заготовка для творческих экспериментов с canvas.",
     "It sets up the render loop and input handling so a sketch starts at the interesting part."),
]
