# -*- coding: utf-8 -*-
"""Stage 5 library pack AF: forecasting, interpretability, fairness, graphs, optimization, numerics."""

LIBS_5AF = [
    # ---------- Прогнозирование временных рядов ----------
    ("lib-neuralprophet", "NeuralProphet", "Данные и ML", "https://neuralprophet.com/", "openSource", "forecasting,neural,time-series,pytorch", "pip install neuralprophet",
     "Neural network forecasting successor to Prophet, built on PyTorch.",
     "Нейросетевой преемник Prophet для прогнозирования, построенный на PyTorch.",
     "Handles autoregression that Prophet cannot, at the cost of longer training and more tuning."),
    ("lib-sktime", "sktime", "Данные и ML", "https://www.sktime.net/en/stable/", "openSource", "time-series,scikit-learn,unified,forecasting", "pip install sktime",
     "Unified scikit-learn-style interface for time series tasks.",
     "Единый интерфейс в стиле scikit-learn для задач с временными рядами.",
     "Its familiar fit/predict API lets you compare very different forecasters with one code path."),
    ("lib-pyod", "PyOD", "Данные и ML", "https://pyod.readthedocs.io/", "openSource", "anomaly-detection,outliers,unified,benchmarks", "pip install pyod",
     "Comprehensive toolkit of outlier and anomaly detection algorithms.",
     "Полный набор алгоритмов обнаружения выбросов и аномалий.",
     "Its unified API makes benchmarking a dozen detectors on your data a short script."),
    ("lib-imbalanced-learn", "imbalanced-learn", "Данные и ML", "https://imbalanced-learn.org/stable/", "openSource", "resampling,class-imbalance,scikit-learn,smote", "pip install imbalanced-learn",
     "Resampling techniques for imbalanced classification, integrated with scikit-learn.",
     "Техники ресемплинга для несбалансированной классификации, интегрированные со scikit-learn.",
     "Resample inside the cross-validation pipeline, not before it — otherwise your scores are inflated."),

    # ---------- Подбор гиперпараметров ----------
    ("lib-hyperopt", "Hyperopt", "MLOps и эксперименты", "https://hyperopt.github.io/hyperopt/", "openSource", "hyperparameters,bayesian,tpe,search", "pip install hyperopt",
     "Bayesian hyperparameter optimization using tree-structured Parzen estimators.",
     "Байесовская оптимизация гиперпараметров через tree-structured Parzen estimators.",
     "Optuna is the more actively developed option now, with a considerably nicer API."),
    ("lib-ray-tune", "Ray Tune", "MLOps и эксперименты", "https://docs.ray.io/en/latest/tune/index.html", "openSource", "hyperparameters,distributed,schedulers,scaling", "pip install 'ray[tune]'",
     "Distributed hyperparameter tuning with early-stopping schedulers.",
     "Распределённый подбор гиперпараметров с планировщиками ранней остановки.",
     "ASHA scheduling kills unpromising trials early, which is where most of the compute saving comes from."),

    # ---------- Интерпретируемость и справедливость ----------
    ("lib-lime", "LIME", "AI-оценка и safety", "https://github.com/marcotcr/lime", "openSource", "interpretability,local,explanations,model-agnostic", "pip install lime",
     "Explains individual predictions by fitting a simple local surrogate model.",
     "Объясняет отдельные предсказания, обучая простую локальную суррогатную модель.",
     "Explanations vary between runs — check stability before showing one to a stakeholder."),
    ("lib-interpretml", "InterpretML", "AI-оценка и safety", "https://interpret.ml/docs/getting-started.html", "openSource", "glassbox,explainable,microsoft,ebm", "pip install interpret",
     "Microsoft toolkit for glassbox models and blackbox explanations.",
     "Набор инструментов Microsoft для прозрачных моделей и объяснений чёрных ящиков.",
     "Its Explainable Boosting Machine is often as accurate as gradient boosting while remaining readable."),
    ("lib-alibi", "Alibi", "AI-оценка и safety", "https://docs.seldon.ai/projects/alibi", "openSource", "explanations,counterfactuals,seldon,inspection", "pip install alibi",
     "Model inspection library with counterfactual and anchor explanations.",
     "Библиотека инспекции моделей с контрфактическими и anchor-объяснениями.",
     "Counterfactuals answer 'what would have to change' — often more actionable than feature importance."),
    ("lib-fairlearn", "Fairlearn", "AI-оценка и safety", "https://fairlearn.org/main/user_guide/index.html", "openSource", "fairness,bias,metrics,mitigation", "pip install fairlearn",
     "Assesses and mitigates fairness-related harms in classification models.",
     "Оценивает и снижает вред, связанный со справедливостью, в моделях классификации.",
     "Fairness metrics conflict mathematically — you must choose which definition your context requires."),
    ("lib-aif360", "AI Fairness 360", "AI-оценка и safety", "https://aif360.readthedocs.io/", "openSource", "fairness,bias,ibm,metrics", "pip install aif360",
     "IBM's extensive library of bias metrics and mitigation algorithms.",
     "Обширная библиотека IBM с метриками смещения и алгоритмами их снижения.",
     "Broader metric coverage than Fairlearn, with a correspondingly steeper learning curve."),

    # ---------- Графы ----------
    ("lib-igraph", "igraph", "Данные и ML", "https://python.igraph.org/en/stable/", "openSource", "graphs,c-core,fast,analysis", "pip install igraph",
     "Fast graph analysis library with a C core and Python, R and Mathematica bindings.",
     "Быстрая библиотека анализа графов с ядром на C и биндингами для Python, R и Mathematica.",
     "Considerably faster than NetworkX on large graphs, with a less Pythonic interface."),
    ("lib-graph-tool", "graph-tool", "Данные и ML", "https://graph-tool.skewed.de/static/doc/index.html", "openSource", "graphs,performance,c-plus-plus,statistics", "",
     "High-performance graph library with statistical inference for network structure.",
     "Высокопроизводительная библиотека графов со статистическим выводом структуры сети.",
     "Its stochastic block model inference finds community structure that modularity methods miss."),
    ("lib-pyg", "PyTorch Geometric", "Данные и ML", "https://pytorch-geometric.readthedocs.io/", "openSource", "gnn,pytorch,graphs,deep-learning", "pip install torch_geometric",
     "Graph neural network library for PyTorch with many published architectures.",
     "Библиотека графовых нейросетей для PyTorch со множеством опубликованных архитектур.",
     "Its sparse message-passing implementation is what makes large graphs fit in GPU memory."),
    ("lib-dgl", "DGL", "Данные и ML", "https://www.dgl.ai/", "openSource", "gnn,framework-agnostic,scalable,graphs", "pip install dgl",
     "Graph neural network library working across PyTorch, TensorFlow and MXNet.",
     "Библиотека графовых нейросетей, работающая с PyTorch, TensorFlow и MXNet.",
     "Its distributed training support handles graphs too large for a single machine."),

    # ---------- Оптимизация ----------
    ("lib-cvxpy", "CVXPY", "Наука и исследования", "https://www.cvxpy.org/", "openSource", "convex-optimization,modelling,python,solvers", "pip install cvxpy",
     "Models convex optimization problems in natural mathematical notation.",
     "Моделирует задачи выпуклой оптимизации в естественной математической нотации.",
     "It verifies convexity as you build the problem, catching a formulation error before any solve."),
    ("lib-pulp", "PuLP", "Наука и исследования", "https://coin-or.github.io/pulp/", "openSource", "linear-programming,milp,python,solvers", "pip install pulp",
     "Linear and mixed-integer programming modeller for Python.",
     "Моделировщик линейного и смешанно-целочисленного программирования для Python.",
     "Ships with a free solver and switches to a commercial one without changing the model code."),
    ("lib-or-tools", "OR-Tools", "Наука и исследования", "https://developers.google.com/optimization", "openSource", "constraint-programming,routing,scheduling,google", "pip install ortools",
     "Google's operations research suite for routing, scheduling and constraint problems.",
     "Набор инструментов исследования операций от Google для маршрутизации, планирования и задач с ограничениями.",
     "Its CP-SAT solver is remarkably strong on scheduling problems that defeat generic MILP approaches."),
    ("lib-pyomo", "Pyomo", "Наука и исследования", "https://pyomo.readthedocs.io/", "openSource", "optimization,modelling,algebraic,solvers", "pip install pyomo",
     "Algebraic modelling language for a wide range of optimization problem classes.",
     "Алгебраический язык моделирования для широкого класса задач оптимизации.",
     "Covers nonlinear and stochastic programming that simpler linear-only modellers cannot express."),
    ("lib-gurobi", "Gurobi", "Наука и исследования", "https://docs.gurobi.com/", "paid", "solver,milp,commercial,performance", "pip install gurobipy",
     "Commercial optimization solver, among the fastest available for large MILP problems.",
     "Коммерческий решатель оптимизации, один из самых быстрых для больших MILP-задач.",
     "Free for academic use, and often an order of magnitude faster than open-source solvers."),

    # ---------- Численные вычисления ----------
    ("lib-scipy", "SciPy", "Наука и исследования", "https://docs.scipy.org/doc/scipy/", "openSource", "scientific,algorithms,optimization,signal", "pip install scipy",
     "Foundational scientific computing library: optimization, signals, statistics and linear algebra.",
     "Фундаментальная библиотека научных вычислений: оптимизация, сигналы, статистика и линейная алгебра.",
     "Check here before writing a numerical routine — the well-tested version usually already exists."),
    ("lib-flax", "Flax", "Данные и ML", "https://flax.readthedocs.io/", "openSource", "jax,neural-networks,google,functional", "pip install flax",
     "Neural network library for JAX, used widely in Google research code.",
     "Библиотека нейросетей для JAX, широко используемая в исследовательском коде Google.",
     "Explicit parameter passing is unusual coming from PyTorch, but it is what makes JAX transforms work."),
    ("lib-equinox", "Equinox", "Данные и ML", "https://docs.kidger.site/equinox/", "openSource", "jax,neural-networks,pytrees,minimal", "pip install equinox",
     "Minimal JAX neural network library where models are ordinary PyTrees.",
     "Минималистичная библиотека нейросетей для JAX, где модели — обычные PyTree.",
     "Models are plain dataclasses, so JAX transformations apply to them with no special handling."),
    ("lib-optax", "Optax", "Данные и ML", "https://optax.readthedocs.io/", "openSource", "jax,optimizers,gradient,composable", "pip install optax",
     "Composable gradient transformation and optimizer library for JAX.",
     "Композируемая библиотека преобразований градиента и оптимизаторов для JAX.",
     "Chaining transformations lets you build clipping, scheduling and weight decay as separate pieces."),
    ("lib-numba", "Numba", "Языки и рантаймы", "https://numba.readthedocs.io/", "openSource", "jit,python,llvm,performance", "pip install numba",
     "JIT compiler turning numerical Python loops into fast machine code.",
     "JIT-компилятор, превращающий числовые циклы Python в быстрый машинный код.",
     "Only helps on numeric array code — decorating general Python often makes things slower."),
    ("lib-cupy", "CuPy", "Данные и ML", "https://docs.cupy.dev/", "openSource", "gpu,numpy-compatible,cuda,arrays", "pip install cupy",
     "GPU array library with a NumPy-compatible API.",
     "Библиотека GPU-массивов с NumPy-совместимым API.",
     "Swapping the numpy import for cupy is often the whole port, for array-heavy code."),
    ("lib-taichi", "Taichi", "Языки и рантаймы", "https://docs.taichi-lang.org/", "openSource", "gpu,parallel,simulation,python-embedded", "pip install taichi",
     "Python-embedded language for high-performance parallel computing and simulation.",
     "Встроенный в Python язык для высокопроизводительных параллельных вычислений и симуляций.",
     "Writes once and runs on CPU or GPU, which suits physics simulation and graphics prototyping."),
]
