# -*- coding: utf-8 -*-
"""Stage 5 library pack AX: web servers and proxies, tunnels and overlay networks, DNS, certificates, access."""

LIBS_5AX = [
    # ---------- Веб-серверы и прокси ----------
    ("lib-haproxy", "HAProxy", "Облако и деплой", "https://docs.haproxy.org/", "openSource", "load-balancer,tcp,http,high-performance", "",
     "High-performance TCP and HTTP load balancer.",
     "Высокопроизводительный балансировщик нагрузки TCP и HTTP.",
     "Its layer 4 mode balances any TCP protocol, which HTTP-only proxies cannot handle."),
    ("lib-apache-httpd", "Apache HTTP Server", "Облако и деплой", "https://httpd.apache.org/docs/", "openSource", "web-server,modules,htaccess,mature", "",
     "The long-established modular web server.",
     "Давно устоявшийся модульный веб-сервер.",
     "Its per-directory .htaccess configuration is why shared hosting still runs on it."),
    ("lib-openlitespeed", "OpenLiteSpeed", "Облако и деплой", "https://openlitespeed.org/kb/", "openSource", "web-server,performance,apache-compatible,caching", "",
     "High-performance web server compatible with Apache configuration.",
     "Высокопроизводительный веб-сервер, совместимый с конфигурацией Apache.",
     "Its built-in page cache is why it dominates managed WordPress hosting."),
    ("lib-squid", "Squid", "Облако и деплой", "https://www.squid-cache.org/Doc/", "openSource", "forward-proxy,caching,filtering,mature", "",
     "Caching forward proxy for outbound web traffic.",
     "Кэширующий forward-прокси для исходящего веб-трафика.",
     "Its access control lists are how many corporate networks filter outbound traffic."),
    ("lib-pingora", "Pingora", "Облако и деплой", "https://github.com/cloudflare/pingora", "openSource", "rust,proxy,cloudflare,framework", "",
     "Rust framework for building fast proxies, from Cloudflare.",
     "Rust-фреймворк для построения быстрых прокси от Cloudflare.",
     "It is a library for writing your own proxy, not a drop-in server like nginx."),

    # ---------- Туннели и оверлейные сети ----------
    ("lib-ngrok", "ngrok", "Разработка и DevOps", "https://ngrok.com/docs", "freeTier", "tunnel,webhooks,local,https", "",
     "Exposes a local server to the public internet over a secure tunnel.",
     "Открывает локальный сервер в интернет через защищённый туннель.",
     "The standard way to test webhooks against a service running on your laptop."),
    ("lib-cloudflare-tunnel", "Cloudflare Tunnel", "Облако и деплой", "https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/", "free", "tunnel,zero-trust,no-open-ports,free", "",
     "Connects a local service to Cloudflare without opening any inbound ports.",
     "Подключает локальный сервис к Cloudflare без открытия входящих портов.",
     "No inbound ports means no exposed attack surface, which port forwarding always creates."),
    ("lib-localtunnel", "localtunnel", "Разработка и DevOps", "https://theboroer.github.io/localtunnel-www/", "openSource", "tunnel,simple,free,self-host", "npm i -g localtunnel",
     "Simple open-source tunnel for exposing a local port.",
     "Простой открытый туннель для проброса локального порта.",
     "Self-hostable, which avoids the session limits free hosted tunnels impose."),
    ("lib-tailscale", "Tailscale", "Безопасность и секреты", "https://tailscale.com/kb", "freeTier", "wireguard,mesh-vpn,zero-config,acl", "",
     "Zero-configuration mesh VPN built on WireGuard.",
     "Mesh-VPN без настройки на базе WireGuard.",
     "It traverses network address translation automatically, which is what makes it feel effortless."),
    ("lib-wireguard", "WireGuard", "Безопасность и секреты", "https://www.wireguard.com/quickstart/", "openSource", "vpn,kernel,fast,simple", "",
     "Modern VPN protocol with a very small, auditable codebase.",
     "Современный VPN-протокол с очень небольшой проверяемой кодовой базой.",
     "A few thousand lines of code, against OpenVPN's hundreds of thousands — that is the security argument."),
    ("lib-headscale", "Headscale", "Безопасность и секреты", "https://headscale.net/stable/", "openSource", "tailscale,self-host,coordination,open-source", "",
     "Open-source self-hosted coordination server for Tailscale clients.",
     "Открытый self-hosted координационный сервер для клиентов Tailscale.",
     "It removes the dependency on Tailscale's control plane while keeping their clients."),
    ("lib-netbird", "NetBird", "Безопасность и секреты", "https://docs.netbird.io/", "openSource", "wireguard,zero-trust,self-host,mesh", "",
     "Open-source zero-trust overlay network built on WireGuard.",
     "Открытая zero-trust оверлейная сеть на базе WireGuard.",
     "Fully self-hostable including the control plane, unlike Tailscale's hosted coordination."),
    ("lib-zerotier", "ZeroTier", "Безопасность и секреты", "https://docs.zerotier.com/", "freeTier", "sdn,layer-2,virtual-network,cross-platform", "",
     "Virtual network creating a layer 2 network across the internet.",
     "Виртуальная сеть, создающая сеть второго уровня поверх интернета.",
     "Layer 2 emulation carries broadcast protocols that layer 3 overlays like WireGuard drop."),
    ("lib-openvpn", "OpenVPN", "Безопасность и секреты", "https://openvpn.net/community-resources/", "openSource", "vpn,mature,tls,cross-platform", "",
     "Long-established TLS-based VPN with very broad platform support.",
     "Давно устоявшийся VPN на основе TLS с очень широкой поддержкой платформ.",
     "Slower than WireGuard, and it traverses restrictive firewalls that block UDP more reliably."),
    ("lib-nebula", "Nebula", "Безопасность и секреты", "https://nebula.defined.net/docs/", "openSource", "overlay,slack,certificates,mesh", "",
     "Scalable overlay networking tool created at Slack.",
     "Масштабируемый инструмент оверлейных сетей, созданный в Slack.",
     "Its certificate-based identity model scales to very large fleets without a coordination server."),

    # ---------- Координация сервисов ----------
    ("lib-consul", "Consul", "Service mesh и Kubernetes", "https://developer.hashicorp.com/consul/docs", "openSource", "service-discovery,mesh,kv,health-checks", "",
     "Service discovery, health checking and service mesh from HashiCorp.",
     "Обнаружение сервисов, проверки состояния и service mesh от HashiCorp.",
     "Its DNS interface means existing applications discover services without any code change."),
    ("lib-etcd", "etcd", "Service mesh и Kubernetes", "https://etcd.io/docs/", "openSource", "key-value,raft,consistent,kubernetes", "",
     "Distributed key-value store providing strong consistency via Raft.",
     "Распределённое хранилище ключ-значение со строгой согласованностью через Raft.",
     "Kubernetes stores all its state here, which makes etcd backups your cluster backups."),
    ("lib-zookeeper", "Apache ZooKeeper", "Service mesh и Kubernetes", "https://zookeeper.apache.org/documentation.html", "openSource", "coordination,consensus,locks,mature", "",
     "Distributed coordination service for configuration and locking.",
     "Служба распределённой координации для конфигурации и блокировок.",
     "Kafka and HBase have historically depended on it, though both are moving away."),

    # ---------- DNS ----------
    ("lib-coredns", "CoreDNS", "Service mesh и Kubernetes", "https://coredns.io/manual/toc/", "openSource", "dns,plugins,kubernetes,go", "",
     "Plugin-based DNS server, the default resolver inside Kubernetes.",
     "DNS-сервер на плагинах, стандартный резолвер внутри Kubernetes.",
     "Its plugin chain lets you add caching or rewriting without a separate DNS layer."),
    ("lib-pi-hole", "Pi-hole", "Безопасность и секреты", "https://docs.pi-hole.net/", "openSource", "dns,ad-blocking,network-wide,self-host", "",
     "Network-wide ad and tracker blocking at the DNS level.",
     "Блокировка рекламы и трекеров на уровне DNS для всей сети.",
     "Blocking at DNS covers every device on the network, including ones that run no extensions."),
    ("lib-adguard-home", "AdGuard Home", "Безопасность и секреты", "https://adguard-dns.io/kb/adguard-home/", "openSource", "dns,filtering,doh,self-host", "",
     "Network-wide DNS filtering with encrypted DNS support.",
     "Сетевая DNS-фильтрация с поддержкой зашифрованного DNS.",
     "It serves DNS-over-HTTPS itself, which Pi-hole needs a separate component for."),
    ("lib-unbound", "Unbound", "Безопасность и секреты", "https://unbound.docs.nlnetlabs.nl/", "openSource", "dns,recursive,validating,dnssec", "",
     "Validating recursive DNS resolver with DNSSEC support.",
     "Проверяющий рекурсивный DNS-резолвер с поддержкой DNSSEC.",
     "Running your own recursive resolver means no upstream provider sees your query history."),
    ("lib-powerdns", "PowerDNS", "Облако и деплой", "https://doc.powerdns.com/", "openSource", "dns,authoritative,api,database-backed", "",
     "Authoritative DNS server with a REST API and database backends.",
     "Авторитативный DNS-сервер с REST API и бэкендами на базах данных.",
     "Its API makes DNS records manageable as code rather than through zone file edits."),
    ("lib-bind", "BIND 9", "Облако и деплой", "https://bind9.readthedocs.io/", "openSource", "dns,reference,authoritative,mature", "",
     "The reference DNS server implementation.",
     "Эталонная реализация DNS-сервера.",
     "Feature-complete and correspondingly complex — lighter servers cover most modern use cases."),
    ("lib-knot-dns", "Knot DNS", "Облако и деплой", "https://www.knot-dns.cz/documentation/", "openSource", "dns,authoritative,performance,dnssec", "",
     "High-performance authoritative DNS server with automated DNSSEC.",
     "Высокопроизводительный авторитативный DNS-сервер с автоматизированным DNSSEC.",
     "Its automatic DNSSEC key management removes the manual rollover that breaks zones."),
    ("lib-dnsmasq", "dnsmasq", "Облако и деплой", "https://thekelleys.org.uk/dnsmasq/doc.html", "openSource", "dns,dhcp,lightweight,embedded", "",
     "Lightweight DNS forwarder and DHCP server for small networks.",
     "Лёгкий DNS-форвардер и DHCP-сервер для небольших сетей.",
     "One small binary covering DNS and DHCP is why it ships on most home routers."),
    ("lib-nextdns", "NextDNS", "Безопасность и секреты", "https://nextdns.io/", "freeTier", "dns,filtering,privacy,hosted", "",
     "Hosted DNS filtering with privacy controls and per-device profiles.",
     "Размещённая DNS-фильтрация с контролем приватности и профилями по устройствам.",
     "Hosted means it protects devices outside your home network too, which Pi-hole cannot."),

    # ---------- Сертификаты и доступ ----------
    ("lib-letsencrypt", "Let's Encrypt", "Безопасность и секреты", "https://letsencrypt.org/docs/", "free", "tls,certificates,free,automated", "",
     "Free automated certificate authority.",
     "Бесплатный автоматизированный удостоверяющий центр.",
     "It made universal HTTPS practical by removing both the cost and the manual renewal."),
    ("lib-certbot", "Certbot", "Безопасность и секреты", "https://eff-certbot.readthedocs.io/", "openSource", "acme,certificates,automation,eff", "",
     "The reference ACME client for obtaining and renewing certificates.",
     "Эталонный ACME-клиент для получения и обновления сертификатов.",
     "Test renewal with a dry run — a renewal that fails silently expires without warning."),
    ("lib-acme-sh", "acme.sh", "Безопасность и секреты", "https://github.com/acmesh-official/acme.sh", "openSource", "acme,shell,lightweight,dns-api", "",
     "Pure shell ACME client with no dependencies.",
     "ACME-клиент на чистом shell без зависимостей.",
     "It runs where Python is unavailable, and its DNS API support covers dozens of providers."),
    ("lib-step-ca", "step-ca", "Безопасность и секреты", "https://smallstep.com/docs/step-ca/", "openSource", "private-ca,acme,certificates,internal", "",
     "Private certificate authority with ACME support for internal services.",
     "Приватный удостоверяющий центр с поддержкой ACME для внутренних сервисов.",
     "It brings automated certificates to internal names that public CAs cannot issue for."),
    ("lib-boundary", "HashiCorp Boundary", "Безопасность и секреты", "https://developer.hashicorp.com/boundary/docs", "openSource", "access,identity-based,sessions,zero-trust", "",
     "Identity-based access to infrastructure without distributing credentials.",
     "Доступ к инфраструктуре на основе идентификации без раздачи учётных данных.",
     "Sessions are brokered per request, so there are no long-lived SSH keys to rotate or leak."),
    ("lib-teleport", "Teleport", "Безопасность и секреты", "https://goteleport.com/docs/", "openSource", "access,ssh,kubernetes,audit", "",
     "Access platform for SSH, Kubernetes, databases and web apps with session recording.",
     "Платформа доступа к SSH, Kubernetes, базам данных и веб-приложениям с записью сессий.",
     "Session recording and audit logs are what make production access reviewable after the fact."),
]
