# -*- coding: utf-8 -*-
"""Stage 5 API pack AA: billing and metering, feature flags, experimentation, remote configuration."""

APIS_5AA = [
    # ---------- Биллинг и подписки ----------
    ("api-stripe-billing", "Stripe Billing", "Платежи и commerce", "https://docs.stripe.com/billing", "paid", "subscriptions,invoicing,usage-based,proration", "",
     "Subscription and invoicing layer on top of Stripe payments.",
     "Слой подписок и выставления счетов поверх платежей Stripe.",
     "Its proration handling covers mid-cycle plan changes, which is where hand-built billing breaks."),
    ("api-chargebee", "Chargebee", "Платежи и commerce", "https://apidocs.chargebee.com/docs/api", "paid", "subscriptions,revenue,dunning,enterprise", "",
     "Subscription management with revenue recognition and dunning workflows.",
     "Управление подписками с признанием выручки и процессами взыскания задолженности.",
     "Its dunning recovers failed payments automatically, which is usually a few percent of revenue."),
    ("api-recurly", "Recurly", "Платежи и commerce", "https://recurly.com/developers/", "paid", "subscriptions,retention,billing,analytics", "",
     "Subscription billing platform with churn and retention tooling.",
     "Платформа биллинга подписок с инструментами удержания и работы с оттоком.",
     "Its revenue recovery features target involuntary churn from expired cards specifically."),
    ("api-orb-billing", "Orb", "Платежи и commerce", "https://docs.withorb.com/", "paid", "usage-based,metering,pricing,developer-first", "",
     "Usage-based billing engine built for complex consumption pricing.",
     "Движок биллинга по потреблению для сложных моделей ценообразования.",
     "Metering and invoicing in one system avoids the reconciliation gap between usage and billing."),
    ("api-metronome", "Metronome", "Платежи и commerce", "https://docs.metronome.com/", "paid", "usage-based,realtime,metering,enterprise", "",
     "Real-time usage-based billing platform for consumption products.",
     "Платформа биллинга по потреблению в реальном времени для consumption-продуктов.",
     "Real-time balances let you show customers current spend rather than a monthly surprise."),
    ("api-lago", "Lago", "Платежи и commerce", "https://getlago.com/docs", "openSource", "usage-based,open-source,self-host,metering", "",
     "Open-source usage-based billing and metering platform.",
     "Открытая платформа биллинга и учёта потребления.",
     "Self-hosting keeps billing data in your own infrastructure, which regulated products often require."),
    ("api-stigg", "Stigg", "Платежи и commerce", "https://docs.stigg.io/", "freeTier", "pricing,entitlements,packaging,monetization", "",
     "Pricing and entitlement management decoupled from billing code.",
     "Управление ценообразованием и правами доступа, отделённое от кода биллинга.",
     "Changing a plan's limits becomes configuration rather than a deploy, which speeds pricing experiments."),
    ("api-schematic", "Schematic", "Платежи и commerce", "https://docs.schematichq.com/", "freeTier", "entitlements,feature-gating,pricing,stripe", "",
     "Feature entitlement and packaging layer that syncs with Stripe.",
     "Слой прав доступа и упаковки функций с синхронизацией со Stripe.",
     "It keeps plan definitions and feature gates in one place rather than scattered across the code."),

    # ---------- Фича-флаги ----------
    ("api-configcat", "ConfigCat", "Feature flags и эксперименты", "https://configcat.com/docs/", "freeTier", "feature-flags,simple,sdk,affordable", "",
     "Straightforward feature flag service with generous free limits.",
     "Простой сервис фича-флагов со щедрыми бесплатными лимитами.",
     "Its free tier covers a real small product, which most flag services reserve for trials."),
    ("api-hypertune", "Hypertune", "Feature flags и эксперименты", "https://docs.hypertune.com/", "freeTier", "type-safe,flags,experiments,codegen", "",
     "Type-safe feature flags with generated client code.",
     "Типобезопасные фича-флаги с генерируемым клиентским кодом.",
     "Generated types mean a deleted flag becomes a compile error rather than a silent default."),
    ("api-bucket-co", "Bucket", "Feature flags и эксперименты", "https://docs.bucket.co/", "freeTier", "feature-flags,b2b,adoption,feedback", "",
     "Feature flags for B2B products, tied to per-company adoption tracking.",
     "Фича-флаги для B2B-продуктов с отслеживанием внедрения по компаниям.",
     "Company-level targeting matches how B2B rollouts actually work, unlike per-user flags."),
    ("api-posthog-flags", "PostHog Feature Flags", "Feature flags и эксперименты", "https://posthog.com/docs/feature-flags", "freeTier", "flags,analytics,experiments,integrated", "",
     "Feature flags integrated with PostHog's product analytics.",
     "Фича-флаги, интегрированные с продуктовой аналитикой PostHog.",
     "Flags and analytics in one system means every rollout is measurable without extra instrumentation."),
    ("api-split-io", "Split", "Feature flags и эксперименты", "https://help.split.io/hc/en-us/categories/360001480091", "freeTier", "flags,experimentation,metrics,enterprise", "",
     "Feature delivery platform combining flags with automatic metric monitoring.",
     "Платформа доставки функций, сочетающая флаги с автоматическим мониторингом метрик.",
     "It alerts when a flag degrades a guardrail metric, which turns a rollout into a safety net."),

    # ---------- Эксперименты ----------
    ("api-eppo", "Eppo", "A/B-тестирование", "https://docs.geteppo.com/", "paid", "experimentation,warehouse-native,statistics,metrics", "",
     "Warehouse-native experimentation platform computing results in your own data warehouse.",
     "Платформа экспериментов, вычисляющая результаты прямо в вашем хранилище данных.",
     "Running analysis on your warehouse means experiment metrics match your existing business metrics."),
    ("api-amplitude-experiment", "Amplitude Experiment", "A/B-тестирование", "https://amplitude.com/docs/experiment", "paid", "experimentation,analytics,flags,integrated", "",
     "Experimentation built on Amplitude's behavioural analytics data.",
     "Эксперименты на основе данных поведенческой аналитики Amplitude.",
     "Reusing existing Amplitude events avoids instrumenting metrics twice for the same question."),
    ("api-ab-tasty", "AB Tasty", "A/B-тестирование", "https://developers.abtasty.com/", "paid", "experimentation,personalization,web,enterprise", "",
     "Experimentation and personalization platform for web and app experiences.",
     "Платформа экспериментов и персонализации для веба и приложений.",
     "Its visual editor lets marketers build variants without engineering involvement."),
    ("api-convert-com", "Convert.com", "A/B-тестирование", "https://api.convert.com/", "paid", "ab-testing,privacy,personalization,web", "",
     "A/B testing platform with a strong privacy and consent posture.",
     "Платформа A/B-тестирования с сильной позицией по приватности и согласию.",
     "Its data handling is built around GDPR, which matters for European traffic specifically."),
    ("api-kameleoon", "Kameleoon", "A/B-тестирование", "https://developers.kameleoon.com/", "paid", "experimentation,personalization,ai,feature-flags", "",
     "Experimentation and personalization with AI-driven targeting.",
     "Эксперименты и персонализация с таргетингом на основе AI.",
     "It combines flags and experiments in one platform, which avoids running two separate systems."),

    # ---------- Удалённая конфигурация ----------
    ("api-firebase-remote-config", "Firebase Remote Config", "Feature flags и эксперименты", "https://firebase.google.com/docs/remote-config", "free", "mobile,configuration,rollouts,free", "",
     "Free remote configuration and staged rollouts for mobile apps.",
     "Бесплатная удалённая конфигурация и поэтапные раскатки для мобильных приложений.",
     "Free at any scale, which makes it the default for mobile config even alongside paid flag services."),
    ("api-vercel-edge-config", "Vercel Edge Config", "Feature flags и эксперименты", "https://vercel.com/docs/edge-config", "freeTier", "edge,configuration,low-latency,vercel", "",
     "Ultra-low-latency configuration store readable from edge functions.",
     "Хранилище конфигурации со сверхнизкой задержкой, читаемое из edge-функций.",
     "Reads take under a millisecond, so config lookups can sit in the request path safely."),
    ("api-aws-appconfig", "AWS AppConfig", "Feature flags и эксперименты", "https://docs.aws.amazon.com/appconfig/", "paid", "aws,configuration,validation,rollouts", "",
     "Managed configuration deployment with validation and automatic rollback.",
     "Управляемое развёртывание конфигурации с валидацией и автоматическим откатом.",
     "Validating configuration before deployment prevents the bad-config outage that flags otherwise invite."),
]
