# -*- coding: utf-8 -*-
"""Stage 5 library pack K: Kubernetes/IaC tooling, observability agents, misc CLI."""

LIBS_5K = [
    # ---------- Service mesh и Kubernetes (deepen) ----------
    ("lib-k9s", "k9s", "Service mesh и Kubernetes", "https://k9scli.io/", "openSource", "kubernetes,tui,cli,operations", "brew install k9s",
     "Terminal UI for navigating and managing Kubernetes clusters interactively.",
     "Терминальный интерфейс для интерактивной навигации и управления кластерами Kubernetes.",
     "Far faster than repeated kubectl commands for exploring what is actually running in a cluster."),
    ("lib-kubectx", "kubectx / kubens", "Service mesh и Kubernetes", "https://github.com/ahmetb/kubectx", "openSource", "kubernetes,context,namespace,cli", "brew install kubectx",
     "Fast switching between Kubernetes contexts and namespaces.",
     "Быстрое переключение между контекстами и пространствами имён Kubernetes.",
     "Pair with a shell prompt showing the current context — most production incidents start with the wrong context."),
    ("lib-kind", "kind", "Service mesh и Kubernetes", "https://kind.sigs.k8s.io/", "openSource", "kubernetes,local,testing,docker", "brew install kind",
     "Runs local Kubernetes clusters inside Docker containers, built for testing.",
     "Запускает локальные кластеры Kubernetes внутри Docker-контейнеров, создан для тестирования.",
     "Its speed of cluster creation and teardown is what makes it the standard for CI-based k8s testing."),
    ("lib-k3s", "K3s", "Service mesh и Kubernetes", "https://docs.k3s.io/", "openSource", "kubernetes,lightweight,edge,iot", "curl -sfL https://get.k3s.io | sh -",
     "Lightweight certified Kubernetes distribution in a single binary, good for edge and small servers.",
     "Лёгкий сертифицированный дистрибутив Kubernetes в одном бинарнике для edge и небольших серверов.",
     "Runs comfortably on a Raspberry Pi, unlike full Kubernetes — the whole point of the distribution."),
    ("lib-flux-cd", "Flux", "Service mesh и Kubernetes", "https://fluxcd.io/flux/", "openSource", "gitops,kubernetes,cd,cncf", "brew install fluxcd/tap/flux",
     "GitOps continuous delivery for Kubernetes, the CNCF alternative to Argo CD.",
     "GitOps непрерывная доставка для Kubernetes, альтернатива Argo CD в CNCF.",
     "More composable and controller-driven than Argo CD; Argo has the stronger UI if that matters to your team."),
    ("lib-cert-manager", "cert-manager", "Service mesh и Kubernetes", "https://cert-manager.io/docs/", "openSource", "tls,certificates,kubernetes,letsencrypt", "",
     "Automates TLS certificate issuance and renewal inside Kubernetes.",
     "Автоматизирует выпуск и обновление TLS-сертификатов внутри Kubernetes.",
     "Set up a staging ClusterIssuer first — Let's Encrypt production rate limits are easy to hit while debugging."),
    ("lib-crossplane", "Crossplane", "Инфраструктура как код", "https://docs.crossplane.io/", "openSource", "iac,kubernetes,control-plane,cncf", "",
     "Manages cloud infrastructure through Kubernetes APIs instead of a separate IaC tool.",
     "Управляет облачной инфраструктурой через API Kubernetes вместо отдельного IaC-инструмента.",
     "Infrastructure becomes Kubernetes resources, so the same RBAC and GitOps flow covers apps and infra alike."),

    # ---------- Мониторинг и аналитика: agents/exporters ----------
    ("lib-vector-dev", "Vector", "Мониторинг и аналитика", "https://vector.dev/docs/", "openSource", "logs,pipeline,rust,observability", "",
     "High-performance observability data pipeline for collecting, transforming and routing logs.",
     "Высокопроизводительный пайплайн данных observability для сбора, трансформации и маршрутизации логов.",
     "Transforming and filtering at the agent cuts ingest cost before data reaches a paid backend."),
    ("lib-fluent-bit", "Fluent Bit", "Мониторинг и аналитика", "https://docs.fluentbit.io/manual", "openSource", "logs,forwarding,lightweight,cncf", "",
     "Lightweight log processor and forwarder, the standard sidecar in Kubernetes logging setups.",
     "Лёгкий обработчик и пересыльщик логов, стандартный sidecar в Kubernetes-логировании.",
     "Its memory footprint is small enough to run as a DaemonSet on every node without noticeable overhead."),
    ("lib-grafana-loki", "Grafana Loki", "Мониторинг и аналитика", "https://grafana.com/docs/loki/latest/", "openSource", "logs,grafana,labels,cheap", "",
     "Log aggregation that indexes only labels, not full text, making it far cheaper to run.",
     "Агрегация логов, индексирующая только метки, а не полный текст — заметно дешевле в эксплуатации.",
     "Keep label cardinality low — high-cardinality labels are the one thing that makes Loki expensive and slow."),
    ("lib-prometheus-client", "Prometheus client libraries", "Мониторинг и аналитика", "https://prometheus.io/docs/instrumenting/clientlibs/", "openSource", "metrics,instrumentation,prometheus,exporters", "pip install prometheus-client",
     "Official instrumentation libraries for exposing Prometheus metrics from your code.",
     "Официальные библиотеки инструментации для экспорта метрик Prometheus из вашего кода.",
     "Stick to the four standard metric types — inventing custom aggregation in-app defeats Prometheus's model."),

    # ---------- Разработка и DevOps (deepen) ----------
    ("lib-act", "act", "Разработка и DevOps", "https://nektosact.com/", "openSource", "github-actions,local,docker,testing", "brew install act",
     "Runs GitHub Actions workflows locally in Docker, without pushing to test a change.",
     "Запускает workflow GitHub Actions локально в Docker, без пуша для проверки изменения.",
     "Saves the push-wait-fail-fix cycle entirely when debugging a workflow file."),
    ("lib-dagger-io", "Dagger", "Разработка и DevOps", "https://docs.dagger.io/", "openSource", "ci,pipelines,containers,portable", "",
     "Defines CI/CD pipelines as code that runs identically locally and on any CI provider.",
     "Описывает CI/CD-пайплайны как код, одинаково работающий локально и на любом CI-провайдере.",
     "Pipelines run in containers, which is why 'works locally but fails in CI' largely disappears."),
    ("lib-earthly", "Earthly", "Разработка и DevOps", "https://docs.earthly.dev/", "openSource", "build,ci,reproducible,containers", "",
     "Build automation combining Dockerfile and Makefile concepts, reproducible across environments.",
     "Автоматизация сборки, объединяющая идеи Dockerfile и Makefile, воспроизводима между окружениями.",
     "Its syntax is familiar if you know Dockerfiles, which shortens adoption compared to a new DSL."),
    ("lib-lefthook", "Lefthook", "Git и совместная работа", "https://lefthook.dev/", "openSource", "git-hooks,fast,parallel,polyglot", "npm i -D lefthook",
     "Fast, parallel git hooks manager that works across language ecosystems.",
     "Быстрый параллельный менеджер git-хуков, работающий в разных языковых экосистемах.",
     "Runs hooks in parallel unlike husky, which matters once you have several checks on pre-commit."),
    ("lib-commitlint", "commitlint", "Git и совместная работа", "https://commitlint.js.org/", "openSource", "commits,conventional,lint,git", "npm i -D @commitlint/cli",
     "Enforces conventional commit message format via a git hook.",
     "Обеспечивает соблюдение формата conventional commits через git-хук.",
     "Conventional commits are what let changelog and version-bump tooling work automatically downstream."),

    # ---------- Утилиты (deepen) ----------
    ("lib-zx", "zx", "CLI и терминал", "https://google.github.io/zx/", "openSource", "shell,javascript,scripting,google", "npm i -g zx",
     "Write shell scripts in JavaScript with clean subprocess syntax, from Google.",
     "Написание shell-скриптов на JavaScript с удобным синтаксисом подпроцессов, от Google.",
     "A good middle ground when a bash script outgrows bash but a full Node CLI is overkill."),
    ("lib-execa", "execa", "CLI и терминал", "https://github.com/sindresorhus/execa", "openSource", "subprocess,node,promises,cli", "npm i execa",
     "Better subprocess execution for Node with promises and sane defaults.",
     "Улучшенный запуск подпроцессов в Node с промисами и разумными настройками по умолчанию.",
     "Its default of not using a shell avoids a whole class of command-injection issues child_process invites."),
    ("lib-chalk", "Chalk", "CLI и терминал", "https://github.com/chalk/chalk", "openSource", "terminal,colors,styling,node", "npm i chalk",
     "Terminal string styling for Node CLIs: colors, bold, underline.",
     "Стилизация строк терминала для Node-CLI: цвета, жирный, подчёркивание.",
     "It auto-detects color support, so piped output stays clean without you checking TTY manually."),
    ("lib-ora", "Ora", "CLI и терминал", "https://github.com/sindresorhus/ora", "openSource", "spinner,terminal,cli,node", "npm i ora",
     "Elegant terminal spinners for long-running CLI operations.",
     "Аккуратные терминальные спиннеры для долгих операций в CLI.",
     "Always stop the spinner in a finally block, or an error leaves a spinning cursor stuck in the terminal."),
]
