# -*- coding: utf-8 -*-
"""Stage 5 pricing pack D: messaging providers, support desks, engagement platforms."""

PAID_5D = [
("paid-twilio-verify","Twilio Verify (pricing)","Коммуникации","https://www.twilio.com/en-us/verify/pricing","paid","otp,pricing,per-verification,usage",
 "One-time-passcode verification billed per successful verification.",
 "Проверка одноразовыми кодами с оплатой за успешную верификацию.",
 "Paying per success rather than per SMS attempt absorbs the cost of retries and failed deliveries.",
 "usage","from ~$0.05 per verification","free trial credit","https://www.twilio.com/en-us/verify/pricing"),
("paid-bandwidth","Bandwidth (pricing)","Коммуникации","https://www.bandwidth.com/pricing/","paid","voice,pricing,per-minute,carrier",
 "Carrier-level voice and messaging billed per minute and per message.",
 "Голос и сообщения операторского уровня с оплатой за минуту и за сообщение.",
 "Direct carrier rates undercut aggregators at volume, which is the reason to take on the added setup.",
 "usage","from ~$0.007 per minute","free trial credit","https://www.bandwidth.com/pricing/"),
("paid-infobip","Infobip (pricing)","Коммуникации","https://www.infobip.com/pricing","paid","omnichannel,pricing,per-message,global",
 "Omnichannel messaging priced per message, varying widely by destination country.",
 "Омниканальные сообщения с оплатой за сообщение, ставка сильно зависит от страны назначения.",
 "Destination pricing varies by an order of magnitude — model your actual country mix, not an average.",
 "usage","custom quote (per message by country)","free trial credit","https://www.infobip.com/pricing"),
("paid-zendesk","Zendesk (pricing)","CRM и продажи","https://www.zendesk.com/pricing/","paid","support,pricing,per-agent,subscription",
 "Support platform billed per agent per month across several tiers.",
 "Платформа поддержки с оплатой за агента в месяц по нескольким тарифам.",
 "API access and automation sit on the higher tiers, so integration plans affect which plan you need.",
 "subscription","from ~$19 per agent per month","free trial","https://www.zendesk.com/pricing/"),
("paid-help-scout","Help Scout (pricing)","CRM и продажи","https://www.helpscout.com/pricing/","paid","support,pricing,per-user,contacts",
 "Shared inbox and knowledge base billed per user with contact-volume tiers.",
 "Общий ящик и база знаний с оплатой за пользователя и тарифами по объёму контактов.",
 "Contact volume, not just seat count, drives the bill — check both before comparing to rivals.",
 "subscription","from ~$50 per month","free trial","https://www.helpscout.com/pricing/"),
("paid-gorgias","Gorgias (pricing)","CRM и продажи","https://www.gorgias.com/pricing","paid","ecommerce,pricing,per-ticket,subscription",
 "E-commerce helpdesk billed by monthly ticket volume rather than agent seats.",
 "Служба поддержки для e-commerce с оплатой по месячному объёму тикетов, а не по местам агентов.",
 "Billing on tickets rather than seats suits a small team handling high volume, and penalizes the reverse.",
 "subscription","from ~$10 per month","free trial","https://www.gorgias.com/pricing"),
("paid-pylon-support","Pylon (pricing)","CRM и продажи","https://usepylon.com/pricing","paid","b2b,pricing,per-seat,subscription",
 "B2B support platform billed per seat on annual contracts.",
 "Платформа B2B-поддержки с оплатой за место по годовым контрактам.",
 "Aimed at teams already running shared Slack channels with enterprise customers.",
 "subscription","custom quote (per seat)","free trial","https://usepylon.com/pricing"),
("paid-missive","Missive (pricing)","Коммуникации","https://missiveapp.com/pricing","paid","shared-inbox,pricing,per-user,subscription",
 "Collaborative shared inbox billed per user per month.",
 "Совместный общий почтовый ящик с оплатой за пользователя в месяц.",
 "API access requires a higher tier — verify that before designing an integration around it.",
 "subscription","from ~$18 per user per month","free trial","https://missiveapp.com/pricing"),
("paid-customer-io","Customer.io (pricing)","Email-маркетинг","https://customer.io/pricing","paid","lifecycle,pricing,profiles,subscription",
 "Behavioural messaging billed by number of tracked customer profiles.",
 "Поведенческие сообщения с оплатой по числу отслеживаемых профилей клиентов.",
 "Profile count includes inactive users, so pruning stale profiles directly cuts the bill.",
 "subscription","from ~$100 per month","free trial","https://customer.io/pricing"),
("paid-braze","Braze (pricing)","CDP и маркетинг-данные","https://www.braze.com/pricing","paid","engagement,pricing,enterprise,custom",
 "Enterprise engagement platform sold on annual contracts scaled to audience size.",
 "Корпоративная платформа вовлечения по годовым контрактам, масштабируемым под размер аудитории.",
 "Expect a real implementation project alongside the licence — this is not a self-serve product.",
 "custom","custom quote","product demo","https://www.braze.com/pricing"),
("paid-iterable","Iterable (pricing)","CDP и маркетинг-данные","https://iterable.com/pricing/","paid","marketing,pricing,contacts,enterprise",
 "Cross-channel marketing automation priced by contact volume on annual contracts.",
 "Кроссканальная маркетинговая автоматизация с ценой по объёму контактов на годовых контрактах.",
 "Priced for mid-market and enterprise senders rather than early-stage products.",
 "custom","custom quote (by contact volume)","product demo","https://iterable.com/pricing/"),
("paid-moengage","MoEngage (pricing)","CDP и маркетинг-данные","https://www.moengage.com/pricing/","paid","engagement,pricing,mau,custom",
 "Engagement platform priced by monthly active users reached.",
 "Платформа вовлечения с ценой по числу охваченных активных пользователей в месяц.",
 "MAU-based pricing suits consumer apps where reach, not contact list size, is the real scale metric.",
 "custom","custom quote (by monthly active users)","product demo","https://www.moengage.com/pricing/"),
("paid-humanloop","Humanloop (pricing)","AI-оценка и safety","https://humanloop.com/pricing","paid","llm-ops,pricing,seats,enterprise",
 "LLM development platform sold per seat on annual enterprise plans.",
 "Платформа разработки LLM с оплатой за место по годовым корпоративным планам.",
 "Priced around domain experts reviewing outputs, so seat count grows with reviewers, not engineers.",
 "subscription","custom quote (per seat)","free trial","https://humanloop.com/pricing"),
("paid-vellum","Vellum (pricing)","AI-оценка и safety","https://www.vellum.ai/pricing","paid","llm-ops,pricing,seats,workflows",
 "Visual LLM workflow and evaluation platform billed per seat with usage tiers.",
 "Визуальная платформа LLM-workflow и оценки с оплатой за место и тарифами по объёму.",
 "Worth it mainly when non-engineers own the LLM logic — otherwise open-source tooling covers the same ground.",
 "subscription","from ~$500 per month","free trial","https://www.vellum.ai/pricing"),
("paid-reducto","Reducto (pricing)","Документы и PDF","https://reducto.ai/pricing","paid","document-parsing,pricing,per-page,accuracy",
 "High-accuracy document parsing billed per processed page.",
 "Высокоточный разбор документов с оплатой за обработанную страницу.",
 "Costs more per page than general parsers, which pays off only where a parsing error is expensive.",
 "usage","from ~$0.02 per page","free trial pages","https://reducto.ai/pricing"),
]
