# -*- coding: utf-8 -*-
"""Stage 5 pricing pack K: document AI, identity and fraud, physical mail, travel connectivity."""

PAID_5K = [
("paid-sphere-engine","Sphere Engine (pricing)","Тестирование и качество","https://sphere-engine.com/pricing","paid","code-execution,pricing,subscription,executions",
 "Code execution infrastructure billed monthly by execution volume.",
 "Инфраструктура выполнения кода с месячной оплатой по объёму запусков.",
 "Judge0 self-hosted covers the same job for free — pay here for the reliability guarantee.",
 "subscription","from ~$50 per month","free trial","https://sphere-engine.com/pricing"),
("paid-klippa","Klippa (pricing)","OCR и распознавание документов","https://www.klippa.com/en/pricing/","paid","ocr,pricing,per-document,subscription",
 "Document parsing billed per processed document.",
 "Разбор документов с оплатой за обработанный документ.",
 "Per-document pricing makes receipt processing costs directly predictable from transaction volume.",
 "usage","custom quote (per document)","free trial credits","https://www.klippa.com/en/pricing/"),
("paid-rossum","Rossum (pricing)","OCR и распознавание документов","https://rossum.ai/pricing/","paid","invoices,pricing,per-document,enterprise",
 "Invoice processing billed per document on annual contracts.",
 "Обработка счетов с оплатой за документ по годовым контрактам.",
 "Priced against the cost of manual data entry, which is the comparison it is sold on.",
 "custom","custom quote (per document)","free trial","https://rossum.ai/pricing/"),
("paid-extend-ai","Extend (pricing)","OCR и распознавание документов","https://www.extend.ai/pricing","paid","document-ai,pricing,per-page,custom",
 "LLM document processing billed per processed page.",
 "Обработка документов на LLM с оплатой за обработанную страницу.",
 "Its evaluation tooling is bundled, which is what separates it from a raw model API call.",
 "usage","custom quote (per page)","free trial","https://www.extend.ai/pricing"),
("paid-sumsub","Sumsub (pricing)","Идентификация и KYC","https://sumsub.com/pricing/","paid","kyc,pricing,per-verification,subscription",
 "Identity verification billed per completed verification.",
 "Проверка личности с оплатой за завершённую верификацию.",
 "Rates vary by country and document type, so a blended average understates high-risk markets.",
 "usage","from ~$1.35 per verification","free trial verifications","https://sumsub.com/pricing/"),
("paid-trulioo","Trulioo (pricing)","Идентификация и KYC","https://www.trulioo.com/pricing","paid","identity,pricing,per-query,global",
 "Global identity verification billed per data source query.",
 "Глобальная проверка личности с оплатой за запрос к источнику данных.",
 "Each additional data source is billed separately, so cascading checks multiply the cost.",
 "usage","custom quote (per verification)","product demo","https://www.trulioo.com/pricing"),
("paid-complyadvantage","ComplyAdvantage (pricing)","Идентификация и KYC","https://complyadvantage.com/pricing/","paid","aml,pricing,per-search,subscription",
 "Sanctions and adverse media screening on annual subscriptions.",
 "Скрининг по санкциям и негативным упоминаниям по годовым подпискам.",
 "Ongoing monitoring costs more than one-off screening, and regulators generally expect monitoring.",
 "custom","custom quote","product demo","https://complyadvantage.com/pricing/"),
("paid-alloy","Alloy (pricing)","Идентификация и KYC","https://www.alloy.com/pricing","paid","identity,pricing,per-application,orchestration",
 "Identity decisioning billed per application processed.",
 "Принятие решений по идентификации с оплатой за обработанную заявку.",
 "You still pay the underlying vendors it orchestrates — this fee sits on top of theirs.",
 "custom","custom quote (per application)","product demo","https://www.alloy.com/pricing"),
("paid-sardine","Sardine (pricing)","Безопасность и секреты","https://www.sardine.ai/pricing","paid","fraud,pricing,per-session,custom",
 "Fraud prevention billed per assessed session or transaction.",
 "Предотвращение мошенничества с оплатой за оценённую сессию или транзакцию.",
 "Compare against your actual fraud losses — that ratio is the only meaningful justification.",
 "custom","custom quote (per session)","product demo","https://www.sardine.ai/pricing"),
("paid-sift","Sift (pricing)","Безопасность и секреты","https://sift.com/pricing","paid","fraud,pricing,per-event,enterprise",
 "Fraud detection billed by scored event volume.",
 "Обнаружение мошенничества с оплатой по объёму оценённых событий.",
 "Sending more event types improves its model, and also raises the bill — tune what you send.",
 "custom","custom quote (per event)","product demo","https://sift.com/pricing"),
("paid-arkose-labs","Arkose Labs (pricing)","Безопасность и секреты","https://www.arkoselabs.com/pricing/","paid","bot-detection,pricing,enterprise,traffic",
 "Bot mitigation sold on enterprise contracts scaled to traffic.",
 "Противодействие ботам по корпоративным контрактам, масштабируемым под трафик.",
 "Enterprise-only; Turnstile and ALTCHA cover ordinary bot filtering at no cost.",
 "custom","custom quote","product demo","https://www.arkoselabs.com/pricing/"),
("paid-lob","Lob (pricing)","Логистика и доставка","https://www.lob.com/pricing","paid","direct-mail,pricing,per-piece,postage",
 "Physical mail billed per piece, including printing and postage.",
 "Физическая почта с оплатой за отправление, включая печать и пересылку.",
 "Volume tiers cut the per-piece rate substantially, which matters for recurring statement mail.",
 "usage","from ~$0.50 per postcard","free test mode","https://www.lob.com/pricing"),
("paid-sendcloud","Sendcloud (pricing)","Логистика и доставка","https://www.sendcloud.com/pricing/","paid","shipping,pricing,subscription,labels",
 "Shipping platform billed monthly by label volume and features.",
 "Платформа доставки с месячной оплатой по объёму этикеток и функциям.",
 "Its negotiated carrier rates often offset the subscription entirely at moderate volume.",
 "subscription","from ~€25 per month","free tier for low volume","https://www.sendcloud.com/pricing/"),
("paid-impala","Impala (pricing)","Транспорт и город","https://impala.travel/","paid","hotels,pricing,per-booking,connectivity",
 "Hotel connectivity billed per booking made through the API.",
 "Подключение к отелям с оплатой за бронирование через API.",
 "Paying per booking rather than per search aligns cost with revenue, which suits a marketplace.",
 "usage","custom quote (per booking)","product demo","https://impala.travel/"),
]
