# -*- coding: utf-8 -*-
"""Stage 5 library pack AR: mobile frameworks, state and navigation, on-device storage, networking and images."""

LIBS_5AR = [
    # ---------- Кроссплатформенные каркасы ----------
    ("lib-ionic", "Ionic Framework", "Мобильная и desktop разработка", "https://ionicframework.com/docs", "openSource", "hybrid,web,components,cross-platform", "npm i @ionic/core",
     "UI component library for building mobile apps with web technologies.",
     "Библиотека UI-компонентов для создания мобильных приложений на веб-технологиях.",
     "Its components adapt their look to iOS or Android automatically, which hybrid apps usually get wrong."),
    ("lib-nitro-modules", "Nitro Modules", "Мобильная и desktop разработка", "https://nitro.margelo.com/", "openSource", "react-native,native-modules,fast,codegen", "npm i react-native-nitro-modules",
     "Fast native module framework for React Native with generated bindings.",
     "Быстрый фреймворк нативных модулей для React Native с генерируемыми биндингами.",
     "Type-safe generated bridges remove the hand-written glue that native modules usually require."),
    ("lib-react-native-skia", "React Native Skia", "Мобильная и desktop разработка", "https://shopify.github.io/react-native-skia/", "openSource", "graphics,skia,2d,high-performance", "npm i @shopify/react-native-skia",
     "Exposes the Skia graphics engine to React Native for custom rendering.",
     "Открывает графический движок Skia для React Native для произвольной отрисовки.",
     "The same engine Chrome and Flutter render with, which makes complex visuals genuinely fast."),
    ("lib-react-navigation", "React Navigation", "Мобильная и desktop разработка", "https://reactnavigation.org/docs/getting-started", "openSource", "react-native,routing,stacks,tabs", "npm i @react-navigation/native",
     "The standard navigation library for React Native applications.",
     "Стандартная библиотека навигации для приложений React Native.",
     "Its native stack uses the platform navigators, so transitions feel native rather than simulated."),

    # ---------- Состояние Flutter ----------
    ("lib-flutter-provider", "Provider", "Мобильная и desktop разработка", "https://pub.dev/packages/provider", "openSource", "flutter,state,inherited-widget,simple", "flutter pub add provider",
     "Simple dependency injection and state management for Flutter.",
     "Простой dependency injection и управление состоянием для Flutter.",
     "Riverpod is by the same author and fixes its main limitations — prefer it for new projects."),
    ("lib-getx", "GetX", "Мобильная и desktop разработка", "https://pub.dev/packages/get", "openSource", "flutter,state,routing,di", "flutter pub add get",
     "All-in-one Flutter package covering state, routing and dependency injection.",
     "Универсальный пакет Flutter для состояния, маршрутизации и внедрения зависимостей.",
     "Its convenience comes with heavy global state, which tends to complicate larger applications."),
    ("lib-freezed", "Freezed", "Мобильная и desktop разработка", "https://pub.dev/packages/freezed", "openSource", "dart,codegen,immutable,unions", "flutter pub add freezed",
     "Code generation for immutable Dart classes and union types.",
     "Кодогенерация неизменяемых классов Dart и union-типов.",
     "Its sealed unions make exhaustive state handling checkable by the compiler."),

    # ---------- Хранилище на устройстве ----------
    ("lib-isar", "Isar", "Мобильная и desktop разработка", "https://isar.dev/", "openSource", "flutter,database,fast,nosql", "flutter pub add isar",
     "Fast cross-platform NoSQL database for Flutter and Dart.",
     "Быстрая кроссплатформенная NoSQL база данных для Flutter и Dart.",
     "Its query inspector shows live database contents during development, which speeds debugging."),
    ("lib-objectbox", "ObjectBox", "Мобильная и desktop разработка", "https://docs.objectbox.io/", "mixed", "database,mobile,fast,sync", "",
     "High-performance object database for mobile and embedded devices.",
     "Высокопроизводительная объектная база данных для мобильных и встраиваемых устройств.",
     "Its optional sync handles offline-first data replication without a separate sync layer."),
    ("lib-realm", "Realm", "Мобильная и desktop разработка", "https://www.mongodb.com/docs/atlas/device-sdks/", "openSource", "mobile,database,objects,sync", "",
     "Object database for mobile with live objects that update automatically.",
     "Объектная база данных для мобильных с живыми объектами, обновляющимися автоматически.",
     "MongoDB retired the hosted sync service — the local database remains, the cloud sync does not."),
    ("lib-watermelondb", "WatermelonDB", "Мобильная и desktop разработка", "https://watermelondb.dev/docs", "openSource", "react-native,sqlite,lazy,sync", "npm i @nozbe/watermelondb",
     "Reactive database for React Native, optimized for very large datasets.",
     "Реактивная база данных для React Native, оптимизированная под очень большие наборы данных.",
     "Lazy loading means it stays fast with tens of thousands of records where AsyncStorage collapses."),
    ("lib-mmkv", "MMKV", "Мобильная и desktop разработка", "https://github.com/Tencent/MMKV", "openSource", "key-value,fast,tencent,mmap", "",
     "Efficient key-value storage using memory mapping, from Tencent.",
     "Эффективное хранилище ключ-значение на отображении в память от Tencent.",
     "Orders of magnitude faster than SharedPreferences or UserDefaults for frequent writes."),
    ("lib-react-native-mmkv", "React Native MMKV", "Мобильная и desktop разработка", "https://github.com/mrousavy/react-native-mmkv", "openSource", "react-native,storage,synchronous,fast", "npm i react-native-mmkv",
     "MMKV bindings for React Native with synchronous access.",
     "Биндинги MMKV для React Native с синхронным доступом.",
     "Synchronous reads let you hydrate state before first render, which AsyncStorage cannot."),
    ("lib-async-storage", "AsyncStorage", "Мобильная и desktop разработка", "https://react-native-async-storage.github.io/async-storage/", "openSource", "react-native,storage,simple,asynchronous", "npm i @react-native-async-storage/async-storage",
     "Simple asynchronous key-value storage for React Native.",
     "Простое асинхронное хранилище ключ-значение для React Native.",
     "Fine for small settings; anything larger belongs in SQLite or MMKV."),
    ("lib-room", "Room", "Мобильная и desktop разработка", "https://developer.android.com/training/data-storage/room", "free", "android,sqlite,orm,compile-time", "",
     "Android's SQLite abstraction with compile-time query verification.",
     "Абстракция SQLite для Android с проверкой запросов на этапе компиляции.",
     "Queries are validated at build time, so a typo in SQL fails the build rather than the app."),
    ("lib-sqldelight", "SQLDelight", "Мобильная и desktop разработка", "https://sqldelight.github.io/sqldelight/", "openSource", "kotlin,sql,multiplatform,typesafe", "",
     "Generates typesafe Kotlin APIs from SQL statements, across platforms.",
     "Генерирует типобезопасные Kotlin-API из SQL-выражений для разных платформ.",
     "You write real SQL and it generates the code, which is the inverse of an ORM's approach."),
    ("lib-core-data", "Core Data", "Мобильная и desktop разработка", "https://developer.apple.com/documentation/coredata", "free", "apple,persistence,object-graph,mature", "",
     "Apple's object graph and persistence framework.",
     "Фреймворк графа объектов и персистентности от Apple.",
     "Powerful and notoriously intricate — SwiftData wraps it in a much simpler modern API."),
    ("lib-swiftdata", "SwiftData", "Мобильная и desktop разработка", "https://developer.apple.com/documentation/swiftdata", "free", "apple,swift,macros,modern", "",
     "Apple's modern persistence framework, declared with Swift macros.",
     "Современный фреймворк персистентности Apple, описываемый макросами Swift.",
     "Requires recent OS versions, so check your deployment target before adopting it."),
    ("lib-grdb", "GRDB", "Мобильная и desktop разработка", "https://swiftpackageindex.com/groue/GRDB.swift/documentation", "openSource", "swift,sqlite,observation,toolkit", "",
     "SQLite toolkit for Swift with database observation.",
     "Набор инструментов SQLite для Swift с наблюдением за изменениями в базе.",
     "Its value observation drives SwiftUI updates directly from database changes."),

    # ---------- Сеть и сериализация ----------
    ("lib-ktor-client", "Ktor Client", "JVM экосистема", "https://ktor.io/docs/client-create-new-application.html", "openSource", "kotlin,http,multiplatform,coroutines", "",
     "Multiplatform HTTP client for Kotlin, built on coroutines.",
     "Мультиплатформенный HTTP-клиент для Kotlin на корутинах.",
     "The same client code runs on Android, iOS and the JVM, which is the point of Kotlin Multiplatform."),
    ("lib-retrofit", "Retrofit", "JVM экосистема", "https://square.github.io/retrofit/", "openSource", "android,http,annotations,square", "",
     "Type-safe HTTP client for Android and Java, defined with annotations.",
     "Типобезопасный HTTP-клиент для Android и Java, описываемый аннотациями.",
     "An annotated interface replaces the request-building code entirely."),
    ("lib-okhttp", "OkHttp", "JVM экосистема", "https://square.github.io/okhttp/", "openSource", "http,android,connection-pooling,interceptors", "",
     "Efficient HTTP client underlying Retrofit and much of the Android ecosystem.",
     "Эффективный HTTP-клиент, лежащий в основе Retrofit и большей части экосистемы Android.",
     "Its interceptors are where logging, auth and retry logic belong, rather than in each call site."),
    ("lib-moshi", "Moshi", "JVM экосистема", "https://github.com/square/moshi", "openSource", "json,kotlin,codegen,square", "",
     "Modern JSON library for Kotlin and Java with code generation.",
     "Современная JSON-библиотека для Kotlin и Java с кодогенерацией.",
     "It understands Kotlin nullability, which Gson silently violates at runtime."),
    ("lib-kotlinx-serialization", "kotlinx.serialization", "JVM экосистема", "https://kotlinlang.org/docs/serialization.html", "openSource", "kotlin,official,multiplatform,compiler-plugin", "",
     "Kotlin's official multiplatform serialization library.",
     "Официальная мультиплатформенная библиотека сериализации Kotlin.",
     "Compiler-plugin based, so it needs no reflection and works on Kotlin/Native too."),

    # ---------- Загрузка изображений ----------
    ("lib-coil", "Coil", "Мобильная и desktop разработка", "https://coil-kt.github.io/coil/", "openSource", "android,kotlin,images,coroutines", "",
     "Kotlin-first image loading library for Android, built on coroutines.",
     "Библиотека загрузки изображений для Android с приоритетом Kotlin, на корутинах.",
     "Lifecycle-aware, so requests cancel automatically when the view goes away."),
    ("lib-glide", "Glide", "Мобильная и desktop разработка", "https://bumptech.github.io/glide/", "openSource", "android,images,caching,mature", "",
     "Mature Android image loading and caching library.",
     "Зрелая библиотека загрузки и кэширования изображений для Android.",
     "Its memory and disk caching defaults are well tuned for scrolling lists of images."),
    ("lib-sdwebimage", "SDWebImage", "Мобильная и desktop разработка", "https://github.com/SDWebImage/SDWebImage", "openSource", "ios,images,caching,async", "",
     "Asynchronous image downloading and caching for iOS.",
     "Асинхронная загрузка и кэширование изображений для iOS.",
     "Long-established with wide format support, including animated images and vectors."),
    ("lib-kingfisher", "Kingfisher", "Мобильная и desktop разработка", "https://github.com/onevcat/Kingfisher", "openSource", "swift,images,caching,swiftui", "",
     "Pure Swift image downloading and caching library.",
     "Библиотека загрузки и кэширования изображений на чистом Swift.",
     "Its SwiftUI view integrates directly, unlike Objective-C libraries that need a wrapper."),
    ("lib-nuke", "Nuke", "Мобильная и desktop разработка", "https://kean-docs.github.io/nuke/documentation/nuke/", "openSource", "swift,images,performance,pipeline", "",
     "High-performance Swift image loading with a configurable pipeline.",
     "Высокопроизводительная загрузка изображений на Swift с настраиваемым пайплайном.",
     "Its prefetching keeps large image grids scrolling smoothly."),

    # ---------- Desktop и гибрид ----------
    ("lib-tauri-mobile", "Tauri Mobile", "Мобильная и desktop разработка", "https://v2.tauri.app/start/", "openSource", "rust,mobile,webview,cross-platform", "",
     "Tauri 2 extending its Rust and webview model to iOS and Android.",
     "Tauri 2, расширяющий модель Rust и webview на iOS и Android.",
     "One Rust core across desktop and mobile, with far smaller binaries than Electron equivalents."),
]
