# -*- coding: utf-8 -*-
"""Stage 5 API pack AD: diffusion interfaces, GPU compute platforms, inference providers, image generation."""

APIS_5AD = [
    # ---------- Интерфейсы диффузионных моделей ----------
    ("api-comfyui", "ComfyUI", "Изображения и дизайн", "https://docs.comfy.org/", "openSource", "node-based,diffusion,workflows,local", "",
     "Node-based interface for building image generation workflows locally.",
     "Интерфейс на узлах для построения локальных workflow генерации изображений.",
     "Workflows export as JSON, so a reproducible generation pipeline is a shareable file."),
    ("api-automatic1111", "AUTOMATIC1111 WebUI", "Изображения и дизайн", "https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki", "openSource", "stable-diffusion,webui,extensions,local", "",
     "The long-standing Stable Diffusion web interface with a large extension ecosystem.",
     "Давно устоявшийся веб-интерфейс Stable Diffusion с большой экосистемой расширений.",
     "Its extension catalogue remains the broadest, though development has slowed considerably."),
    ("api-invokeai", "InvokeAI", "Изображения и дизайн", "https://invoke-ai.github.io/InvokeAI/", "openSource", "diffusion,professional,canvas,workflows", "",
     "Professional-oriented generative image studio with a unified canvas.",
     "Профессиональная студия генеративных изображений с единым холстом.",
     "Its canvas handles inpainting and outpainting as one continuous surface rather than separate modes."),
    ("api-fooocus", "Fooocus", "Изображения и дизайн", "https://github.com/lllyasviel/Fooocus", "openSource", "simple,diffusion,defaults,local", "",
     "Simplified Stable Diffusion interface with strong built-in defaults.",
     "Упрощённый интерфейс Stable Diffusion с хорошими настройками по умолчанию.",
     "It hides the sampler and scheduler knobs, which is exactly right for anyone not tuning them."),
    ("api-sd-webui-forge", "Stable Diffusion WebUI Forge", "Изображения и дизайн", "https://github.com/lllyasviel/stable-diffusion-webui-forge", "openSource", "performance,fork,low-vram,diffusion", "",
     "Performance-focused fork of the AUTOMATIC1111 interface.",
     "Форк интерфейса AUTOMATIC1111 с упором на производительность.",
     "Its memory optimizations make larger models usable on consumer graphics cards."),
    ("api-diffusers", "Diffusers", "Изображения и дизайн", "https://huggingface.co/docs/diffusers", "openSource", "huggingface,library,pipelines,python", "pip install diffusers",
     "Hugging Face library for running and training diffusion models.",
     "Библиотека Hugging Face для запуска и обучения диффузионных моделей.",
     "Its pipeline abstraction makes swapping between model architectures a one-line change."),

    # ---------- GPU-вычисления ----------
    ("api-vast-ai", "Vast.ai", "Локальные модели", "https://docs.vast.ai/", "paid", "gpu,marketplace,cheap,spot", "",
     "Marketplace renting GPU capacity from independent providers.",
     "Маркетплейс аренды GPU-мощностей у независимых поставщиков.",
     "Far cheaper than managed clouds, with reliability that varies by individual host."),
    ("api-paperspace", "Paperspace", "Локальные модели", "https://docs.digitalocean.com/products/paperspace/", "freeTier", "gpu,notebooks,deployments,digitalocean", "",
     "GPU cloud with notebooks and deployments, now part of DigitalOcean.",
     "GPU-облако с ноутбуками и развёртываниями, теперь часть DigitalOcean.",
     "Its free GPU notebook tier is enough to work through a training tutorial end to end."),
    ("api-beam-cloud", "Beam", "Локальные модели", "https://docs.beam.cloud/", "freeTier", "serverless,gpu,python,fast-cold-start", "pip install beam-client",
     "Serverless GPU platform for Python workloads.",
     "Serverless GPU-платформа для Python-нагрузок.",
     "Its fast cold starts make per-request GPU inference viable, which most serverless GPU offerings do not."),
    ("api-cerebrium", "Cerebrium", "Локальные модели", "https://docs.cerebrium.ai/", "freeTier", "serverless,gpu,deployment,inference", "",
     "Serverless GPU infrastructure for deploying machine learning models.",
     "Serverless GPU-инфраструктура для развёртывания моделей машинного обучения.",
     "Deployment is a Python file plus a config, which removes the container build step."),
    ("api-inferless", "Inferless", "Локальные модели", "https://docs.inferless.com/", "freeTier", "serverless,gpu,inference,autoscaling", "",
     "Serverless GPU inference with automatic scaling to zero.",
     "Serverless GPU-инференс с автоматическим масштабированием до нуля.",
     "Scale to zero means an occasionally used model costs nothing while idle."),
    ("api-novita-ai", "Novita AI", "Локальные модели", "https://novita.ai/docs", "freeTier", "gpu,inference,apis,affordable", "",
     "Affordable GPU cloud with ready-made model APIs.",
     "Доступное GPU-облако с готовыми API моделей.",
     "Its prebuilt endpoints cover common models without any deployment work at all."),
    ("api-hyperbolic", "Hyperbolic", "Локальные модели", "https://docs.hyperbolic.xyz/", "freeTier", "gpu,inference,open-models,cheap", "",
     "Low-cost inference and GPU rental for open models.",
     "Недорогой инференс и аренда GPU для открытых моделей.",
     "Its pricing for open-weight models undercuts the major inference providers noticeably."),

    # ---------- Генерация изображений ----------
    ("api-midjourney", "Midjourney", "Изображения и дизайн", "https://docs.midjourney.com/", "paid", "image-generation,quality,discord,aesthetic", "",
     "Image generation service known for its strong aesthetic defaults.",
     "Сервис генерации изображений, известный сильной эстетикой по умолчанию.",
     "It has no official public API, which rules it out for programmatic pipelines."),
    ("api-leonardo-ai", "Leonardo.Ai", "Изображения и дизайн", "https://docs.leonardo.ai/", "freeTier", "image-generation,api,models,game-assets", "",
     "Image generation platform with an API and fine-tuned model library.",
     "Платформа генерации изображений с API и библиотекой дообученных моделей.",
     "Its game asset models produce consistent sprite and texture sets, which general models struggle with."),
    ("api-krea", "Krea", "Изображения и дизайн", "https://docs.krea.ai/", "freeTier", "realtime,generation,enhancement,creative", "",
     "Real-time image generation and enhancement with a creative interface.",
     "Генерация и улучшение изображений в реальном времени с творческим интерфейсом.",
     "Real-time canvas generation turns prompting into a continuous rather than iterative process."),
    ("api-magnific", "Magnific AI", "Изображения и дизайн", "https://magnific.ai/", "paid", "upscaling,detail,enhancement,creative", "",
     "AI upscaler that adds plausible detail rather than only enlarging.",
     "AI-апскейлер, добавляющий правдоподобные детали, а не просто увеличивающий изображение.",
     "It invents detail rather than recovering it, which rules it out for evidential imagery."),
    ("api-freepik-api", "Freepik API", "Изображения и дизайн", "https://docs.freepik.com/", "paid", "stock,generation,icons,licensed", "",
     "Stock assets and image generation with commercial licensing included.",
     "Стоковые ресурсы и генерация изображений с включённой коммерческой лицензией.",
     "Licensing clarity is the real product — generated images alone rarely come with usage rights."),
    ("api-remove-bg", "remove.bg", "Изображения и дизайн", "https://www.remove.bg/api", "freeTier", "background-removal,api,simple,batch", "",
     "Background removal API with consistent results on people and products.",
     "API удаления фона со стабильным результатом на людях и товарах.",
     "Its free tier returns low-resolution results, so evaluate quality at full size before committing."),
]
