# -*- coding: utf-8 -*-
"""Stage 5 library pack AA: observability backends, telemetry pipelines, Kubernetes ops."""

LIBS_5AA = [
    # ---------- Наблюдаемость: бэкенды хранения ----------
    ("lib-grafana-mimir", "Grafana Mimir", "Мониторинг и аналитика", "https://grafana.com/docs/mimir/latest/", "openSource", "prometheus,metrics,long-term,horizontal-scale", "",
     "Horizontally scalable long-term storage for Prometheus metrics.",
     "Горизонтально масштабируемое долговременное хранилище метрик Prometheus.",
     "Prometheus alone keeps weeks of data — this is what you add when you need years of it."),
    ("lib-victoriametrics", "VictoriaMetrics", "Мониторинг и аналитика", "https://docs.victoriametrics.com/", "openSource", "metrics,prometheus-compatible,efficient,tsdb", "",
     "Fast time-series database compatible with Prometheus, using far less storage.",
     "Быстрая база временных рядов, совместимая с Prometheus, с существенно меньшим расходом хранилища.",
     "Its compression typically cuts storage several-fold versus Prometheus for the same retention."),
    ("lib-thanos", "Thanos", "Мониторинг и аналитика", "https://thanos.io/tip/thanos/getting-started.md/", "openSource", "prometheus,global-view,object-storage,ha", "",
     "Adds global query view and unlimited retention across many Prometheus instances.",
     "Добавляет глобальное представление запросов и неограниченное хранение для множества инстансов Prometheus.",
     "Querying across clusters from one endpoint is the feature — retention is almost a side effect."),
    ("lib-pyroscope", "Grafana Pyroscope", "Мониторинг и аналитика", "https://grafana.com/docs/pyroscope/latest/", "openSource", "profiling,continuous,flamegraphs,performance", "",
     "Continuous profiling storing CPU and memory flame graphs over time.",
     "Непрерывное профилирование, сохраняющее flame-графы CPU и памяти во времени.",
     "Profiling in production catches the slow path that never reproduces on a developer machine."),
    ("lib-parca", "Parca", "Мониторинг и аналитика", "https://www.parca.dev/docs/overview/", "openSource", "profiling,ebpf,continuous,low-overhead", "",
     "eBPF-based continuous profiling with very low runtime overhead.",
     "Непрерывное профилирование на eBPF с очень низкими накладными расходами.",
     "Requires no code changes or agent library, since eBPF samples the process from the kernel."),
    ("lib-uptrace", "Uptrace", "Наблюдаемость трасс", "https://uptrace.dev/get/", "openSource", "opentelemetry,traces,metrics,clickhouse", "",
     "OpenTelemetry-native tracing and metrics backend built on ClickHouse.",
     "Нативный для OpenTelemetry бэкенд трасс и метрик на ClickHouse.",
     "ClickHouse storage keeps high-cardinality trace data queryable at a cost column stores make bearable."),
    ("lib-hyperdx", "HyperDX", "Наблюдаемость трасс", "https://www.hyperdx.io/docs", "openSource", "logs,traces,session-replay,clickhouse", "",
     "Open-source observability correlating logs, traces and session replays in one view.",
     "Открытая observability-платформа, связывающая логи, трассы и записи сессий в одном представлении.",
     "Jumping from a user session replay straight to the backend trace is what shortens debugging most."),
    ("lib-netdata", "Netdata", "Мониторинг и аналитика", "https://learn.netdata.cloud/", "openSource", "metrics,real-time,per-second,auto-discovery", "",
     "Real-time per-second infrastructure monitoring with zero-configuration auto-discovery.",
     "Мониторинг инфраструктуры в реальном времени с посекундным разрешением и автообнаружением без настройки.",
     "Per-second granularity catches short spikes that a 15-second scrape interval averages away entirely."),

    # ---------- Телеметрия: сбор и конвейеры ----------
    ("lib-otel-collector", "OpenTelemetry Collector", "Наблюдаемость трасс", "https://opentelemetry.io/docs/collector/", "openSource", "telemetry,pipeline,vendor-neutral,processors", "",
     "Vendor-neutral agent receiving, processing and exporting traces, metrics and logs.",
     "Вендоронезависимый агент приёма, обработки и экспорта трасс, метрик и логов.",
     "Point applications at the collector, not at a vendor — switching backends becomes a config change."),
    ("lib-fluentd", "Fluentd", "Наблюдаемость трасс", "https://docs.fluentd.org/", "openSource", "logs,plugins,cncf,unified-logging", "",
     "Unified logging layer with a very large plugin ecosystem.",
     "Единый слой логирования с очень большой экосистемой плагинов.",
     "Heavier than Fluent Bit — the usual pattern is Fluent Bit on nodes forwarding to Fluentd aggregators."),
    ("lib-telegraf", "Telegraf", "Мониторинг и аналитика", "https://docs.influxdata.com/telegraf/", "openSource", "metrics,plugins,influxdb,agent", "",
     "Plugin-driven agent collecting metrics from systems, services and APIs.",
     "Агент на плагинах, собирающий метрики с систем, сервисов и API.",
     "Its several hundred input plugins usually cover a system you would otherwise write an exporter for."),
    ("lib-alertmanager", "Prometheus Alertmanager", "Мониторинг и аналитика", "https://prometheus.io/docs/alerting/latest/alertmanager/", "openSource", "alerting,routing,deduplication,silencing", "",
     "Handles deduplication, grouping and routing of alerts fired by Prometheus.",
     "Обрабатывает дедупликацию, группировку и маршрутизацию оповещений, порождённых Prometheus.",
     "Alert grouping is what stops one failing node from paging you two hundred times."),
    ("lib-robusta", "Robusta", "Мониторинг и аналитика", "https://docs.robusta.dev/master/", "openSource", "kubernetes,alerting,enrichment,automation", "",
     "Enriches Kubernetes alerts with context and can run automated remediation.",
     "Обогащает оповещения Kubernetes контекстом и может запускать автоматическое устранение.",
     "Attaching pod logs and recent changes to the alert removes the first ten minutes of every incident."),

    # ---------- Kubernetes: доставка и GitOps ----------
    ("lib-argo-workflows", "Argo Workflows", "Service mesh и Kubernetes", "https://argo-workflows.readthedocs.io/", "openSource", "kubernetes,workflows,dag,containers", "",
     "Container-native workflow engine running DAGs of steps on Kubernetes.",
     "Нативный для контейнеров движок workflow, выполняющий DAG шагов в Kubernetes.",
     "Every step is a container, which makes polyglot pipelines trivial compared to a single-language runner."),
    ("lib-argo-rollouts", "Argo Rollouts", "Service mesh и Kubernetes", "https://argo-rollouts.readthedocs.io/", "openSource", "canary,blue-green,progressive-delivery,kubernetes", "",
     "Progressive delivery controller for canary and blue-green Kubernetes deployments.",
     "Контроллер прогрессивной доставки для canary и blue-green развёртываний в Kubernetes.",
     "Automated rollback on metric regression is the part that makes canaries safe to run unattended."),
    ("lib-helmfile", "Helmfile", "Service mesh и Kubernetes", "https://helmfile.readthedocs.io/", "openSource", "helm,declarative,multi-chart,environments", "",
     "Declarative spec for deploying and templating many Helm releases together.",
     "Декларативная спецификация для совместного развёртывания и шаблонизации множества Helm-релизов.",
     "One file describes a whole environment, which plain helm install scripts never manage cleanly."),
    ("lib-tilt", "Tilt", "Service mesh и Kubernetes", "https://docs.tilt.dev/", "openSource", "development,live-update,kubernetes,inner-loop", "",
     "Live-updating local development loop for multi-service Kubernetes applications.",
     "Локальный цикл разработки с живым обновлением для многосервисных Kubernetes-приложений.",
     "Live update syncs files into a running container instead of rebuilding the image on every save."),
    ("lib-skaffold", "Skaffold", "Service mesh и Kubernetes", "https://skaffold.dev/docs/", "openSource", "build,deploy,kubernetes,google", "",
     "Automates the build, push and deploy loop for Kubernetes development.",
     "Автоматизирует цикл сборки, публикации и развёртывания при разработке под Kubernetes.",
     "The same config drives both local dev and CI, which keeps the two from drifting apart."),
    ("lib-devspace", "DevSpace", "Service mesh и Kubernetes", "https://www.devspace.sh/docs/getting-started/introduction", "openSource", "development,kubernetes,hot-reload,profiles", "",
     "Developer tooling for building and debugging applications directly inside a cluster.",
     "Инструменты разработчика для сборки и отладки приложений прямо внутри кластера.",
     "Running the dev loop in-cluster removes the 'works locally, breaks in Kubernetes' class of bug."),
    ("lib-garden-io", "Garden", "Service mesh и Kubernetes", "https://docs.garden.io/", "openSource", "development,testing,caching,kubernetes", "",
     "Builds, tests and deploys multi-service stacks with aggressive result caching.",
     "Собирает, тестирует и развёртывает многосервисные стеки с агрессивным кэшированием результатов.",
     "Caching test results per service means a monorepo CI run only redoes what actually changed."),

    # ---------- Kubernetes: эксплуатация ----------
    ("lib-keda", "KEDA", "Service mesh и Kubernetes", "https://keda.sh/docs/latest/", "openSource", "autoscaling,event-driven,queues,scale-to-zero", "",
     "Event-driven autoscaling that scales workloads on queue depth and other external metrics.",
     "Событийное автомасштабирование по глубине очереди и другим внешним метрикам.",
     "Scaling on queue depth rather than CPU is what makes worker autoscaling actually responsive."),
    ("lib-cluster-autoscaler", "Cluster Autoscaler", "Service mesh и Kubernetes", "https://kubernetes.io/docs/concepts/cluster-administration/cluster-autoscaling/", "openSource", "nodes,autoscaling,kubernetes,capacity", "",
     "Adds and removes cluster nodes based on pending pods.",
     "Добавляет и удаляет узлы кластера в зависимости от ожидающих подов.",
     "Works on node groups, where Karpenter provisions individual right-sized nodes — a real design difference."),
    ("lib-kyverno", "Kyverno", "Service mesh и Kubernetes", "https://kyverno.io/docs/", "openSource", "policy,kubernetes,yaml,admission", "",
     "Kubernetes policy engine with rules written as ordinary Kubernetes resources.",
     "Движок политик Kubernetes с правилами в виде обычных ресурсов Kubernetes.",
     "Policies in YAML rather than Rego is why teams pick it over Gatekeeper for the same job."),
    ("lib-gatekeeper", "OPA Gatekeeper", "Service mesh и Kubernetes", "https://open-policy-agent.github.io/gatekeeper/website/docs/", "openSource", "policy,admission,rego,opa", "",
     "Admission controller enforcing OPA policies against Kubernetes resources.",
     "Admission-контроллер, применяющий политики OPA к ресурсам Kubernetes.",
     "Run new policies in dry-run mode first — a strict admission policy can block every deploy at once."),
    ("lib-velero", "Velero", "Service mesh и Kubernetes", "https://velero.io/docs/", "openSource", "backup,restore,migration,disaster-recovery", "",
     "Backup, restore and migration for Kubernetes cluster resources and volumes.",
     "Резервное копирование, восстановление и миграция ресурсов и томов кластера Kubernetes.",
     "Test a restore, not just the backup — an untested backup is a guess about your recovery time."),
    ("lib-longhorn", "Longhorn", "Service mesh и Kubernetes", "https://longhorn.io/docs/", "openSource", "storage,block,replicated,cncf", "",
     "Distributed block storage for Kubernetes with replication and snapshots.",
     "Распределённое блочное хранилище для Kubernetes с репликацией и снапшотами.",
     "Simpler to operate than Ceph for small clusters that still need replicated persistent volumes."),
    ("lib-rook", "Rook", "Service mesh и Kubernetes", "https://rook.io/docs/rook/latest-release/Getting-Started/intro/", "openSource", "storage,ceph,operator,kubernetes", "",
     "Kubernetes operator running Ceph storage clusters.",
     "Kubernetes-оператор, управляющий кластерами хранилища Ceph.",
     "You still need to understand Ceph — the operator automates operations, not the underlying model."),
    ("lib-cilium", "Cilium", "Service mesh и Kubernetes", "https://docs.cilium.io/", "openSource", "ebpf,networking,network-policy,observability", "",
     "eBPF-based Kubernetes networking, security policy and observability.",
     "Сетевой стек Kubernetes на eBPF с политиками безопасности и наблюдаемостью.",
     "Its Hubble component gives network flow visibility that traditional CNIs simply cannot provide."),
    ("lib-calico", "Calico", "Service mesh и Kubernetes", "https://docs.tigera.io/calico/latest/about/", "openSource", "cni,network-policy,bgp,kubernetes", "",
     "Widely deployed Kubernetes CNI with mature network policy enforcement.",
     "Широко распространённый CNI для Kubernetes со зрелым применением сетевых политик.",
     "The conservative default when you want proven policy enforcement rather than eBPF's newer capabilities."),
    ("lib-kuma", "Kuma", "Service mesh и Kubernetes", "https://kuma.io/docs/", "openSource", "service-mesh,envoy,multi-zone,universal", "",
     "Envoy-based service mesh working on both Kubernetes and plain virtual machines.",
     "Service mesh на Envoy, работающий и в Kubernetes, и на обычных виртуальных машинах.",
     "Its universal mode covers VM workloads, which most Kubernetes-only meshes cannot reach."),
    ("lib-lens-k8s", "Lens", "Service mesh и Kubernetes", "https://docs.k8slens.dev/", "mixed", "kubernetes,ide,gui,cluster-management", "",
     "Desktop IDE for viewing and managing Kubernetes clusters.",
     "Desktop-IDE для просмотра и управления кластерами Kubernetes.",
     "Now requires a subscription for commercial use — Headlamp is the fully open alternative."),
    ("lib-headlamp", "Headlamp", "Service mesh и Kubernetes", "https://headlamp.dev/docs/latest/", "openSource", "kubernetes,ui,extensible,cncf", "",
     "Extensible open-source Kubernetes UI, usable in-cluster or as a desktop app.",
     "Расширяемый открытый интерфейс Kubernetes, работает в кластере или как desktop-приложение.",
     "Its plugin system lets you surface your own CRDs as first-class UI, which generic dashboards cannot."),
    ("lib-stern", "stern", "Service mesh и Kubernetes", "https://github.com/stern/stern", "openSource", "logs,tailing,multi-pod,colors", "brew install stern",
     "Tails logs from multiple pods and containers simultaneously with colour coding.",
     "Одновременно читает логи нескольких подов и контейнеров с цветовой маркировкой.",
     "Follows pods matched by a pattern, so it keeps working across restarts and rollouts."),
    ("lib-popeye", "Popeye", "Service mesh и Kubernetes", "https://popeyecli.io/", "openSource", "linting,cluster-scan,misconfiguration,report", "",
     "Scans live clusters for misconfigurations and unused resources.",
     "Сканирует работающие кластеры на ошибки конфигурации и неиспользуемые ресурсы.",
     "Catches the missing resource limits and dangling config maps that accumulate silently over time."),
    ("lib-kube-bench", "kube-bench", "Безопасность и секреты", "https://github.com/aquasecurity/kube-bench", "openSource", "cis-benchmark,kubernetes,audit,hardening", "",
     "Checks a Kubernetes cluster against the CIS security benchmark.",
     "Проверяет кластер Kubernetes на соответствие CIS-бенчмарку безопасности.",
     "Managed control planes fail checks you cannot fix — use the managed-provider profile for real results."),
]
