# -*- coding: utf-8 -*-
"""Stage 5 API pack W: SMS/voice providers, team chat, support desks, engagement platforms."""

APIS_5W = [
    # ---------- Коммуникации: SMS и голос ----------
    ("api-twilio-verify", "Twilio Verify", "Коммуникации", "https://www.twilio.com/docs/verify", "paid", "otp,2fa,multi-channel,verification", "",
     "Managed one-time-passcode verification across SMS, voice, email and WhatsApp.",
     "Управляемая проверка одноразовыми кодами по SMS, голосу, email и WhatsApp.",
     "Priced per successful verification, which is usually cheaper than paying per SMS attempt."),
    ("api-telnyx", "Telnyx", "Коммуникации", "https://developers.telnyx.com/", "freeTier", "sms,voice,sip,private-network", "",
     "Communications platform running its own IP network for voice and messaging.",
     "Коммуникационная платформа с собственной IP-сетью для голоса и сообщений.",
     "Owning the network rather than reselling is what keeps its per-minute voice rates low."),
    ("api-bandwidth", "Bandwidth", "Коммуникации", "https://dev.bandwidth.com/docs/", "paid", "voice,messaging,911,carrier", "",
     "Carrier-level voice and messaging APIs with emergency calling support.",
     "API голоса и сообщений операторского уровня с поддержкой экстренных вызовов.",
     "Direct carrier status matters for regulated use cases like E911 that aggregators cannot offer."),
    ("api-infobip", "Infobip", "Коммуникации", "https://www.infobip.com/docs/api", "paid", "omnichannel,global,sms,enterprise", "",
     "Global omnichannel communications platform with wide carrier coverage.",
     "Глобальная омниканальная коммуникационная платформа с широким покрытием операторов.",
     "Its coverage in emerging markets is the usual reason to pick it over US-centric providers."),
    ("api-africas-talking", "Africa's Talking", "Коммуникации", "https://developers.africastalking.com/", "freeTier", "sms,ussd,airtime,africa", "",
     "SMS, USSD, voice and airtime APIs built for African markets.",
     "API SMS, USSD, голоса и пополнения счёта, созданные для африканских рынков.",
     "USSD support matters where feature phones dominate and app-based flows simply do not reach users."),
    ("api-termii", "Termii", "Коммуникации", "https://developer.termii.com/", "freeTier", "sms,otp,africa,verification", "",
     "Messaging and verification APIs focused on African markets.",
     "API сообщений и верификации с фокусом на африканские рынки.",
     "Local sender-ID registration is required in several countries — plan for that lead time."),
    ("api-46elks", "46elks", "Коммуникации", "https://46elks.com/docs", "freeTier", "sms,voice,europe,simple", "",
     "Simple SMS and voice API popular in the Nordics and wider Europe.",
     "Простой API SMS и голоса, популярный в Северной Европе и Европе в целом.",
     "Its API is small enough to learn in an afternoon, which suits straightforward notification needs."),
    ("api-clicksend", "ClickSend", "Коммуникации", "https://developers.clicksend.com/", "freeTier", "sms,email,post,fax", "",
     "Multi-channel messaging including SMS, email and physical post.",
     "Многоканальная отправка сообщений: SMS, email и обычная почта.",
     "Physical letter delivery via API is unusual and genuinely useful for regulated notifications."),

    # ---------- Коммуникации: командные чаты ----------
    ("api-matrix", "Matrix", "Коммуникации", "https://spec.matrix.org/latest/", "openSource", "federated,protocol,chat,e2ee", "",
     "Open federated protocol for real-time communication with end-to-end encryption.",
     "Открытый федеративный протокол коммуникации в реальном времени со сквозным шифрованием.",
     "Federation means no single vendor owns your chat history, which is why governments adopt it."),
    ("api-mattermost", "Mattermost", "Коммуникации", "https://developers.mattermost.com/", "openSource", "self-host,chat,slack-alternative,teams", "",
     "Self-hosted team messaging platform with a full REST API and plugin system.",
     "Self-hosted платформа командных сообщений с полным REST API и системой плагинов.",
     "The obvious pick when chat data must stay inside your own infrastructure."),
    ("api-rocket-chat", "Rocket.Chat", "Коммуникации", "https://developer.rocket.chat/", "openSource", "self-host,chat,omnichannel,apps", "",
     "Open-source communications platform with team chat and customer omnichannel support.",
     "Открытая коммуникационная платформа с командным чатом и омниканальной поддержкой клиентов.",
     "Combines internal chat and customer support in one deployment, unlike most alternatives."),
    ("api-zulip", "Zulip", "Коммуникации", "https://zulip.com/api/", "openSource", "threading,topics,async,open-source", "",
     "Team chat organized by topic threads rather than a single channel stream.",
     "Командный чат, организованный по темам-тредам вместо единого потока канала.",
     "Topic-based threading makes catching up after time away genuinely feasible, unlike flat channels."),

    # ---------- Поддержка клиентов ----------
    ("api-zendesk", "Zendesk API", "CRM и продажи", "https://developer.zendesk.com/api-reference/", "paid", "support,tickets,helpdesk,enterprise", "",
     "Customer support ticketing APIs for the widely used Zendesk platform.",
     "API тикетов клиентской поддержки для широко используемой платформы Zendesk.",
     "Rate limits are per account and fairly tight — batch operations rather than looping single calls."),
    ("api-freshdesk", "Freshdesk", "CRM и продажи", "https://developers.freshdesk.com/api/", "freeTier", "support,tickets,helpdesk,affordable", "",
     "Helpdesk and ticketing APIs with a free tier for small teams.",
     "API службы поддержки и тикетов с бесплатным тарифом для небольших команд.",
     "Its free plan covers a real small-team helpdesk, which is rare in this category."),
    ("api-help-scout", "Help Scout", "CRM и продажи", "https://developer.helpscout.com/", "paid", "support,shared-inbox,conversations,docs", "",
     "Shared inbox and knowledge base APIs oriented around conversations, not tickets.",
     "API общего почтового ящика и базы знаний, построенные вокруг диалогов, а не тикетов.",
     "The conversation model keeps customer-facing replies feeling like email rather than a ticket system."),
    ("api-gorgias", "Gorgias", "CRM и продажи", "https://developers.gorgias.com/", "paid", "ecommerce,support,shopify,helpdesk", "",
     "Helpdesk built for e-commerce, with deep Shopify order context in each ticket.",
     "Служба поддержки для e-commerce с глубоким контекстом заказов Shopify в каждом тикете.",
     "Seeing and refunding the order inside the ticket is what makes it worth more than a generic desk."),
    ("api-plain-support", "Plain", "CRM и продажи", "https://www.plain.com/docs", "freeTier", "support,api-first,developer,customer-cards", "",
     "API-first customer support tool designed for engineering-led teams.",
     "Инструмент клиентской поддержки с приоритетом API для команд, ведомых инженерами.",
     "Customer cards pull live data from your own systems into the support view via your API."),
    ("api-pylon-support", "Pylon", "CRM и продажи", "https://docs.usepylon.com/", "paid", "b2b,support,slack,shared-channels", "",
     "B2B support platform operating inside shared Slack and Teams channels.",
     "Платформа B2B-поддержки, работающая внутри общих каналов Slack и Teams.",
     "Meets enterprise customers where they already are instead of forcing them into a portal."),
    ("api-missive", "Missive", "Коммуникации", "https://missiveapp.com/help/api-documentation", "paid", "shared-inbox,collaboration,email,teams", "",
     "Collaborative shared inbox with internal discussion attached to each thread.",
     "Совместный общий почтовый ящик с внутренним обсуждением, привязанным к каждой переписке.",
     "Internal comments live beside the customer thread, so context is not scattered across chat."),

    # ---------- Вовлечение и жизненный цикл ----------
    ("api-customer-io", "Customer.io", "Email-маркетинг", "https://docs.customer.io/api/", "paid", "lifecycle,messaging,segmentation,workflows", "",
     "Behavioural messaging platform triggering campaigns from product events.",
     "Платформа поведенческих сообщений, запускающая кампании по продуктовым событиям.",
     "Its visual workflow builder is genuinely usable by marketers without engineering involvement."),
    ("api-loops-so", "Loops", "Email-маркетинг", "https://loops.so/docs/api-reference/intro", "freeTier", "email,saas,transactional,simple", "",
     "Modern email platform built for SaaS lifecycle and transactional messages.",
     "Современная email-платформа для жизненного цикла SaaS и транзакционных писем.",
     "Much simpler than enterprise marketing suites, which suits a small product team well."),
    ("api-braze", "Braze", "CDP и маркетинг-данные", "https://www.braze.com/docs/api/basics/", "paid", "engagement,cross-channel,enterprise,personalization", "",
     "Enterprise customer engagement platform spanning push, email, in-app and SMS.",
     "Корпоративная платформа вовлечения клиентов: push, email, in-app и SMS.",
     "Enterprise pricing and a real implementation project — not something adopted in an afternoon."),
    ("api-iterable", "Iterable", "CDP и маркетинг-данные", "https://api.iterable.com/api/docs", "paid", "cross-channel,campaigns,workflows,personalization", "",
     "Cross-channel marketing automation with workflow-based campaign orchestration.",
     "Кроссканальная маркетинговая автоматизация с оркестрацией кампаний на основе workflow.",
     "Its data feeds pull live content into messages at send time rather than at campaign build time."),
    ("api-moengage", "MoEngage", "CDP и маркетинг-данные", "https://developers.moengage.com/", "paid", "engagement,mobile,analytics,personalization", "",
     "Customer engagement platform with a strong mobile and emerging-markets focus.",
     "Платформа вовлечения клиентов с сильным фокусом на мобильные и развивающиеся рынки.",
     "Well established in Asian markets where the US-centric platforms have weaker local support."),
    ("api-clevertap", "CleverTap", "CDP и маркетинг-данные", "https://developer.clevertap.com/docs", "freeTier", "retention,mobile,segmentation,analytics", "",
     "Mobile-first retention and engagement platform combining analytics with messaging.",
     "Mobile-first платформа удержания и вовлечения, сочетающая аналитику с рассылками.",
     "Analytics and messaging in one system removes the export step between measuring and acting."),
    ("api-pusher-beams", "Pusher Beams", "Почта и уведомления", "https://pusher.com/docs/beams/", "freeTier", "push,mobile,web,transactional", "",
     "Push notification delivery for iOS, Android and web from a single API.",
     "Доставка push-уведомлений на iOS, Android и web через единый API.",
     "Its per-user publishing handles device token management, which is the tedious part of push."),
    ("api-fcm", "Firebase Cloud Messaging", "Почта и уведомления", "https://firebase.google.com/docs/cloud-messaging", "free", "push,mobile,google,free", "",
     "Google's free push notification service for Android, iOS and web.",
     "Бесплатный сервис push-уведомлений Google для Android, iOS и web.",
     "Free at any volume, which is why most push vendors ultimately deliver through it anyway."),
    ("api-expo-push", "Expo Push Notifications", "Почта и уведомления", "https://docs.expo.dev/push-notifications/overview/", "free", "react-native,expo,push,cross-platform", "",
     "Push notifications for React Native apps without configuring APNs and FCM separately.",
     "Push-уведомления для React Native без отдельной настройки APNs и FCM.",
     "Handles both platform credentials for you, which removes the most error-prone part of mobile push."),
]
