# -*- coding: utf-8 -*-
"""Stage 5 API pack Z: voice agents, speech recognition and synthesis, meeting capture."""

APIS_5Z = [
    # ---------- Голосовые агенты ----------
    ("api-deepgram-voice-agent", "Deepgram Voice Agent", "Голосовые агенты", "https://developers.deepgram.com/docs/voice-agent", "freeTier", "voice-agent,realtime,websocket,unified", "",
     "Single API combining speech recognition, a language model and synthesis for voice agents.",
     "Единый API, объединяющий распознавание речи, языковую модель и синтез для голосовых агентов.",
     "One WebSocket instead of three services removes most of the latency stacking in voice pipelines."),
    ("api-daily-bots", "Daily Bots", "Голосовые агенты", "https://docs.daily.co/products/bots", "freeTier", "voice-agent,webrtc,open-source,low-latency", "",
     "Hosted voice agent infrastructure built on WebRTC and Pipecat.",
     "Размещённая инфраструктура голосовых агентов на WebRTC и Pipecat.",
     "WebRTC transport handles packet loss far better than raw WebSocket audio on mobile networks."),
    ("api-ultravox", "Ultravox", "Голосовые агенты", "https://docs.ultravox.ai/", "freeTier", "speech-native,llm,low-latency,open-weights", "",
     "Speech-native model that understands audio directly without a transcription step.",
     "Речевая модель, понимающая аудио напрямую, без этапа транскрипции.",
     "Skipping transcription removes both latency and the errors a recognizer would introduce."),

    # ---------- Синтез речи ----------
    ("api-rime-ai", "Rime AI", "Аудио и голос", "https://docs.rime.ai/", "freeTier", "tts,conversational,realistic,low-latency", "",
     "Text-to-speech tuned for natural conversational delivery.",
     "Синтез речи, настроенный на естественную разговорную подачу.",
     "Its voices include the disfluencies real speech has, which matters for phone conversations."),
    ("api-neuphonic", "Neuphonic", "Аудио и голос", "https://docs.neuphonic.com/", "freeTier", "tts,efficient,on-device,low-latency", "",
     "Efficient text-to-speech designed to run at low latency, including on-device.",
     "Эффективный синтез речи с низкой задержкой, в том числе на устройстве.",
     "On-device synthesis removes network round trips entirely from the response path."),
    ("api-wellsaid", "WellSaid Labs", "Аудио и голос", "https://docs.wellsaidlabs.com/", "paid", "tts,studio,corporate,narration", "",
     "Studio-quality synthetic voices aimed at corporate narration and training content.",
     "Синтетические голоса студийного качества для корпоративной озвучки и обучающего контента.",
     "Its voices are licensed from paid voice actors, which resolves the consent question cleanly."),
    ("api-respeecher", "Respeecher", "Аудио и голос", "https://docs.respeecher.com/", "paid", "voice-conversion,film,ethical,cloning", "",
     "Speech-to-speech voice conversion used in film and game production.",
     "Конверсия речи в речь, используемая в кино- и игровом производстве.",
     "It preserves the source performance's timing and emotion, which text-to-speech cannot reproduce."),

    # ---------- Распознавание речи ----------
    ("api-speechmatics", "Speechmatics", "Аудио и голос", "https://docs.speechmatics.com/", "freeTier", "stt,accents,realtime,multilingual", "",
     "Speech recognition with unusually strong accent and dialect coverage.",
     "Распознавание речи с необычно широким покрытием акцентов и диалектов.",
     "Its accent robustness is the main reason to choose it over the larger general providers."),
    ("api-rev-ai", "Rev AI", "Аудио и голос", "https://docs.rev.ai/", "freeTier", "stt,transcription,human-option,accurate", "",
     "Speech-to-text API backed by a company that also sells human transcription.",
     "API распознавания речи от компании, которая также продаёт транскрипцию людьми.",
     "You can escalate a difficult file to human transcription through the same account."),
    ("api-gladia", "Gladia", "Аудио и голос", "https://docs.gladia.io/", "freeTier", "stt,whisper,diarization,translation", "",
     "Speech recognition API with built-in diarization and translation.",
     "API распознавания речи со встроенной диаризацией и переводом.",
     "Diarization and transcription in one call avoids running and aligning two separate pipelines."),
    ("api-voicegain", "Voicegain", "Аудио и голос", "https://www.voicegain.ai/api", "freeTier", "stt,telephony,self-host,contact-center", "",
     "Speech recognition for telephony and contact centres, self-hostable.",
     "Распознавание речи для телефонии и контакт-центров с возможностью self-hosting.",
     "It handles narrowband telephone audio, which models trained on wideband speech transcribe poorly."),
    ("api-picovoice", "Picovoice", "Аудио и голос", "https://picovoice.ai/docs/", "freeTier", "on-device,wake-word,offline,edge", "",
     "On-device voice AI with wake word detection and offline speech recognition.",
     "Голосовой AI на устройстве с детекцией ключевого слова и офлайн-распознаванием речи.",
     "Everything runs locally, so no audio leaves the device — often the deciding privacy factor."),
    ("api-vosk", "Vosk", "Аудио и голос", "https://alphacephei.com/vosk/", "openSource", "offline,stt,lightweight,multilingual", "pip install vosk",
     "Offline speech recognition toolkit with small models for many languages.",
     "Офлайновый набор инструментов распознавания речи с компактными моделями для многих языков.",
     "Its models run on a Raspberry Pi, which Whisper-class models generally cannot."),
    ("api-kaldi", "Kaldi", "Аудио и голос", "https://kaldi-asr.org/doc/", "openSource", "research,asr,toolkit,classical", "",
     "Long-established speech recognition research toolkit.",
     "Давно устоявшийся исследовательский набор инструментов распознавания речи.",
     "Largely superseded by end-to-end neural models, but still the reference for classical ASR pipelines."),
    ("api-nvidia-riva", "NVIDIA Riva", "Аудио и голос", "https://docs.nvidia.com/deeplearning/riva/", "free", "gpu,speech,self-host,nvidia", "",
     "GPU-accelerated speech recognition and synthesis you deploy yourself.",
     "Распознавание и синтез речи с GPU-ускорением для самостоятельного развёртывания.",
     "Self-hosted on your own GPUs, which keeps audio inside your infrastructure at high volume."),
    ("api-speechbrain", "SpeechBrain", "Аудио и голос", "https://speechbrain.readthedocs.io/", "openSource", "pytorch,toolkit,research,all-in-one", "pip install speechbrain",
     "PyTorch speech toolkit covering recognition, enhancement and speaker tasks.",
     "PyTorch-набор для речи: распознавание, улучшение и задачи идентификации говорящего.",
     "One framework across speech tasks makes it a good starting point for research work."),
    ("api-nvidia-nemo", "NVIDIA NeMo", "Аудио и голос", "https://docs.nvidia.com/nemo-framework/", "openSource", "nvidia,speech,llm,training", "pip install nemo_toolkit",
     "NVIDIA's framework for training speech and language models.",
     "Фреймворк NVIDIA для обучения речевых и языковых моделей.",
     "Its pretrained ASR checkpoints are competitive and freely usable without training anything."),

    # ---------- Встречи и транскрипция ----------
    ("api-recall-ai", "Recall.ai", "Видеоконференции", "https://docs.recall.ai/", "paid", "meeting-bots,recording,transcription,unified", "",
     "Single API for meeting bots joining Zoom, Meet and Teams calls.",
     "Единый API для ботов, подключающихся к звонкам Zoom, Meet и Teams.",
     "One integration instead of three separate platform-specific bot implementations."),
    ("api-otter-ai", "Otter.ai", "Видеоконференции", "https://otter.ai/api", "paid", "transcription,meetings,notes,collaboration", "",
     "Meeting transcription with searchable notes and summaries.",
     "Транскрипция встреч с поиском по заметкам и резюме.",
     "Its API surface is narrow — it is a product with an API, not an API-first service."),
    ("api-fireflies-ai", "Fireflies.ai", "Видеоконференции", "https://docs.fireflies.ai/", "freeTier", "meetings,transcription,graphql,crm", "",
     "Meeting recorder and transcription with a GraphQL API and CRM integrations.",
     "Запись и транскрипция встреч с GraphQL API и интеграциями CRM.",
     "Its GraphQL API makes pulling structured meeting data considerably easier than scraping exports."),
    ("api-tactiq", "Tactiq", "Видеоконференции", "https://tactiq.io/", "freeTier", "live-transcription,browser,meetings,summaries", "",
     "Live meeting transcription running as a browser extension, with no bot joining.",
     "Живая транскрипция встреч как расширение браузера, без подключения бота.",
     "No visible bot in the call, which avoids the consent awkwardness a joining participant creates."),
    ("api-grain", "Grain", "Видеоконференции", "https://grainhq.notion.site/Grain-Public-API-Documentation-d0a7e3e0e3d94e7a9e3f4b0e8e0e0e0e", "paid", "meetings,highlights,sales,coaching", "",
     "Meeting recording with highlight clips aimed at sales coaching.",
     "Запись встреч с выделением фрагментов для обучения отделов продаж.",
     "Sharing a thirty-second clip beats sending a colleague an hour-long recording."),
    ("api-vexa", "Vexa", "Видеоконференции", "https://github.com/Vexa-ai/vexa", "openSource", "meeting-bots,self-host,transcription,open-source", "",
     "Open-source meeting bot API for real-time transcription, self-hostable.",
     "Открытый API ботов для встреч с транскрипцией в реальном времени и self-hosting.",
     "Self-hosting keeps meeting audio inside your infrastructure, unlike hosted bot services."),
    ("api-krisp", "Krisp", "Аудио и голос", "https://sdk.krisp.ai/docs", "paid", "noise-cancellation,sdk,voice-clarity,realtime", "",
     "Real-time background noise and voice cancellation SDK.",
     "SDK подавления фонового шума и посторонних голосов в реальном времени.",
     "Cleaning audio before recognition measurably improves transcription accuracy in noisy environments."),
    ("api-sonix", "Sonix", "Аудио и голос", "https://sonix.ai/docs/api", "paid", "transcription,translation,subtitles,editing", "",
     "Automated transcription and translation with a browser-based editor.",
     "Автоматическая транскрипция и перевод с редактором в браузере.",
     "Its editor keeps the transcript synced to audio, which makes correcting errors quick."),
    ("api-attend", "Attend.com", "Видеоконференции", "https://docs.attend.com/", "paid", "meetings,ai-notes,crm,automation", "",
     "AI meeting assistant producing notes and CRM updates automatically.",
     "AI-ассистент встреч, автоматически формирующий заметки и обновления CRM.",
     "Writing meeting outcomes straight into the CRM is what removes the post-call admin work."),
]
