# -*- coding: utf-8 -*-
"""Stage 5 library pack C: frontend depth, a11y/visual-testing libs, secrets clients."""

LIBS_5C = [
    # ---------- UI и frontend (deepen) ----------
    ("lib-solid-start", "SolidStart", "UI и frontend", "https://start.solidjs.com/getting-started/what-is-solidstart", "openSource", "solidjs,meta-framework,ssr,fullstack", "npm create solid@latest",
     "Full-stack meta-framework for SolidJS with SSR, routing and server functions.",
     "Full-stack мета-фреймворк для SolidJS с SSR, роутингом и серверными функциями.",
     "File-based routing mirrors Next.js conventions closely, which shortens the learning curve moving over."),
    ("lib-remix", "Remix", "UI и frontend", "https://remix.run/docs", "openSource", "react,ssr,web-standards,forms", "npx create-remix@latest",
     "React framework built on web standards, with nested routing and progressive enhancement.",
     "React-фреймворк на веб-стандартах с вложенным роутингом и прогрессивным улучшением.",
     "Now merged into React Router v7 — new projects should start from React Router's docs directly."),
    ("lib-fresh-deno", "Fresh", "UI и frontend", "https://fresh.deno.dev/docs/introduction", "openSource", "deno,islands,ssr,zero-build", "deno run -A -r https://fresh.deno.dev",
     "Deno's islands-architecture web framework with no build step.",
     "Веб-фреймворк Deno на архитектуре islands без этапа сборки.",
     "No build step means the dev-to-prod code path is identical, which removes a whole class of deploy surprises."),
    ("lib-alpine-ajax", "Alpine AJAX", "UI и frontend", "https://alpine-ajax.js.org/", "openSource", "alpinejs,ajax,minimal,htmx-alternative", "",
     "htmx-like AJAX behavior for teams already using Alpine.js.",
     "Поведение AJAX в духе htmx для команд, уже использующих Alpine.js.",
     "Reach for this over htmx specifically when Alpine is already your interactivity layer."),
    ("lib-svelte-5-runes", "Svelte 5 Runes", "UI и frontend", "https://svelte.dev/docs/svelte/what-are-runes", "openSource", "svelte,reactivity,signals,runes", "",
     "Svelte's explicit reactivity primitives ($state, $derived, $effect) replacing implicit reactivity.",
     "Явные примитивы реактивности Svelte ($state, $derived, $effect) вместо неявной реактивности.",
     "Runes work the same inside and outside components now, which fixes the old share-logic pain points."),
    ("lib-preact-signals", "Preact Signals", "UI и frontend", "https://preactjs.com/guide/v10/signals/", "openSource", "signals,reactivity,preact,performance", "npm i @preact/signals",
     "Fine-grained reactive state that updates the DOM directly, skipping component re-renders.",
     "Тонкозернистое реактивное состояние, обновляющее DOM напрямую, минуя перерисовку компонентов.",
     "Works in plain React too via @preact/signals-react — you don't have to adopt Preact to use it."),
    ("lib-million-js", "Million.js", "UI и frontend", "https://million.dev/docs", "openSource", "react,performance,virtual-dom,compiler", "npx million@latest",
     "Drop-in compiler optimization that speeds up React's virtual DOM diffing.",
     "Компиляторная оптимизация, ускоряющая diffing виртуального DOM React без изменения кода.",
     "The automatic mode requires no code changes at all — try it before hand-optimizing hot components."),

    # ---------- Состояние и данные (deepen) ----------
    ("lib-xstate", "XState", "Состояние и данные", "https://stately.ai/docs", "openSource", "state-machines,statecharts,framework-agnostic", "npm i xstate",
     "State machines and statecharts for JavaScript, framework-agnostic.",
     "Конечные автоматы и statecharts для JavaScript, независимо от фреймворка.",
     "Model complex multi-step flows (checkout, onboarding) as a machine — impossible transitions become impossible."),
    ("lib-valtio", "Valtio", "Состояние и данные", "https://valtio.dev/docs/introduction/getting-started", "openSource", "state,proxy,react,minimal", "npm i valtio",
     "Proxy-based state management: mutate a plain object, components re-render automatically.",
     "Управление состоянием на прокси: мутируешь обычный объект, компоненты перерисовываются сами.",
     "Write mutations as plain JavaScript assignments — the proxy handles the reactivity, no reducers needed."),
    ("lib-legend-state", "Legend-State", "Состояние и данные", "https://legendapp.com/open-source/state/", "openSource", "state,performance,react,fine-grained", "npm i @legendapp/state",
     "Fine-grained observable state claiming some of the fastest React state benchmarks.",
     "Тонкозернистое наблюдаемое состояние с одними из самых быстрых бенчмарков среди React-решений.",
     "Fine-grained subscriptions mean a state change re-renders only the exact component reading that value."),

    # ---------- Графики и визуализация (deepen) ----------
    ("lib-recharts", "Recharts", "Графики и визуализация", "https://recharts.org/", "openSource", "charts,react,composable,svg", "npm i recharts",
     "Composable React chart library built directly on SVG and D3 primitives.",
     "Композируемая библиотека графиков React, построена прямо на SVG и примитивах D3.",
     "Charts compose from JSX components, so conditional series and custom tooltips stay declarative."),
    ("lib-nivo", "Nivo", "Графики и визуализация", "https://nivo.rocks/", "openSource", "charts,react,d3,motion", "npm i @nivo/core",
     "Rich, animated React chart library with server-side rendering support.",
     "Богатая анимированная библиотека графиков React с поддержкой серверного рендеринга.",
     "SSR-safe rendering matters if your dashboard needs a shareable static image, not just an interactive one."),
    ("lib-echarts-2", "Apache ECharts (JS)", "Графики и визуализация", "https://echarts.apache.org/handbook/en/get-started/", "openSource", "charts,canvas,performance,large-datasets", "npm i echarts",
     "Canvas-based chart library that handles very large datasets smoothly.",
     "Библиотека графиков на canvas, плавно справляется с очень большими наборами данных.",
     "Reach for this over SVG chart libraries specifically once a series crosses tens of thousands of points."),

    # ---------- Доступность (a11y) ----------
    ("lib-axe-core", "axe-core", "Доступность (a11y)", "https://github.com/dequelabs/axe-core", "openSource", "accessibility,testing,wcag,library", "npm i axe-core",
     "The open-source engine that powers most automated accessibility testing tools.",
     "Открытый движок, лежащий в основе большинства инструментов автоматического тестирования доступности.",
     "Run it in CI against every page — catching a11y regressions in review is far cheaper than after launch."),
    ("lib-eslint-plugin-jsx-a11y", "eslint-plugin-jsx-a11y", "Доступность (a11y)", "https://github.com/jsx-eslint/eslint-plugin-jsx-a11y", "openSource", "accessibility,eslint,react,lint", "npm i -D eslint-plugin-jsx-a11y",
     "Lint rules catching common accessibility mistakes directly in JSX as you write it.",
     "Правила линтера, ловящие типичные ошибки доступности прямо в JSX в момент написания.",
     "Catches missing alt text and invalid ARIA roles before code review, not after a scan."),
    ("lib-react-aria", "React Aria", "Доступность (a11y)", "https://react-spectrum.adobe.com/react-aria/", "openSource", "accessibility,headless,adobe,hooks", "npm i react-aria",
     "Adobe's accessible interaction hooks: full keyboard, screen-reader and focus behavior, unstyled.",
     "Доступные хуки взаимодействия от Adobe: полная поддержка клавиатуры, скринридеров и фокуса, без стилей.",
     "The accessibility behavior here is more thoroughly tested than most teams could build in-house."),
    ("lib-pa11y", "Pa11y", "Доступность (a11y)", "https://pa11y.org/", "openSource", "accessibility,cli,ci,automated", "npm i -g pa11y",
     "Command-line accessibility testing that fits naturally into a CI pipeline.",
     "Тестирование доступности из командной строки, естественно вписывается в CI-пайплайн.",
     "pa11y-ci runs a whole sitemap of URLs in one CI step — set it up once and forget about it."),

    # ---------- Визуальное тестирование ----------
    ("lib-playwright-visual", "Playwright Visual Comparisons", "Визуальное тестирование", "https://playwright.dev/docs/test-snapshots", "openSource", "visual-regression,playwright,screenshots,built-in", "",
     "Built-in screenshot comparison in Playwright — no separate visual-testing service required.",
     "Встроенное сравнение скриншотов в Playwright — отдельный сервис визуального тестирования не нужен.",
     "Commit baseline screenshots to the repo and update them deliberately with --update-snapshots."),
    ("lib-loki-visual", "Loki", "Визуальное тестирование", "https://loki.js.org/", "openSource", "visual-regression,storybook,docker,free", "npm i -D loki",
     "Free, self-hosted visual regression testing for Storybook using Docker-based browsers.",
     "Бесплатное self-hosted визуальное регрессионное тестирование для Storybook на Docker-браузерах.",
     "Docker-based rendering keeps screenshots pixel-identical across every machine that runs the suite."),

    # ---------- Секреты и конфигурация ----------
    ("lib-dotenv", "dotenv", "Секреты и конфигурация", "https://github.com/motdotla/dotenv", "openSource", "env-vars,config,node,simple", "npm i dotenv",
     "Loads environment variables from a .env file into process.env.",
     "Загружает переменные окружения из файла .env в process.env.",
     "Never commit the actual .env file — commit a .env.example with the keys but no real values."),
    ("lib-python-dotenv", "python-dotenv", "Секреты и конфигурация", "https://github.com/theskumar/python-dotenv", "openSource", "env-vars,config,python,simple", "pip install python-dotenv",
     "The Python equivalent of dotenv for loading .env files into the environment.",
     "Python-аналог dotenv для загрузки .env-файлов в окружение.",
     "load_dotenv() has to run before you read any config — call it at the very top of your entry point."),
    ("lib-sops", "SOPS", "Секреты и конфигурация", "https://github.com/getsops/sops", "openSource", "secrets,encryption,git,yaml", "brew install sops",
     "Encrypts values inside YAML/JSON files so secrets can live safely in Git.",
     "Шифрует значения внутри YAML/JSON-файлов, чтобы секреты могли безопасно жить в Git.",
     "Only the values are encrypted, not the keys — diffs stay readable even for encrypted config."),

    # ---------- Утилиты (deepen) ----------
    ("lib-lodash-es", "Lodash", "Утилиты", "https://lodash.com/docs/", "openSource", "utilities,javascript,functions,classic", "npm i lodash",
     "The classic JavaScript utility library: deep clone, debounce, grouping and dozens more.",
     "Классическая библиотека утилит JavaScript: глубокое клонирование, debounce, группировка и десятки других.",
     "Import individual functions (lodash/debounce) rather than the whole library to keep bundles small."),
    ("lib-ramda", "Ramda", "Утилиты", "https://ramdajs.com/docs/", "openSource", "functional,javascript,immutable,composition", "npm i ramda",
     "Functional programming utility library built around currying and immutability by default.",
     "Библиотека функциональных утилит на каррировании и неизменяемости по умолчанию.",
     "Every function is auto-curried, which is what makes point-free composition read naturally here."),
    ("lib-day-js", "Day.js", "Утилиты", "https://day.js.org/docs/en/installation/installation", "openSource", "dates,lightweight,moment-compatible,2kb", "npm i dayjs",
     "2KB date library with a Moment.js-compatible API, the lightweight successor most projects migrate to.",
     "2КБ библиотека дат с API, совместимым с Moment.js — лёгкий преемник, на который переезжает большинство проектов.",
     "The API mirrors Moment.js closely enough that migrating an old codebase is often a mechanical import swap."),
    ("lib-nanoid", "nanoid", "Утилиты", "https://github.com/ai/nanoid", "openSource", "id-generation,unique,tiny,secure", "npm i nanoid",
     "Tiny, secure, URL-friendly unique ID generator — a smaller alternative to UUID.",
     "Крошечный безопасный URL-дружественный генератор уникальных ID — компактная альтернатива UUID.",
     "IDs are shorter than UUIDs by default while keeping comparable collision resistance for most use cases."),
]
