# -*- coding: utf-8 -*-
"""Stage 5 pricing pack C: fintech rails and blockchain infrastructure."""

PAID_5C = [
("paid-nium","Nium (pricing)","Финансы","https://www.nium.com/pricing","paid","payouts,pricing,per-transaction,corridors",
 "Global payouts priced per transaction, varying by destination corridor.",
 "Глобальные выплаты с оплатой за транзакцию, ставка зависит от коридора назначения.",
 "Corridor-specific rates mean a blended estimate misleads — price your actual country mix.",
 "usage","custom quote (per payout)","sandbox access","https://www.nium.com/pricing"),
("paid-rapyd","Rapyd (pricing)","Финансы","https://www.rapyd.net/pricing/","paid","payments,pricing,local-methods,per-transaction",
 "Payment acceptance priced per transaction, differing by local payment method.",
 "Приём платежей с оплатой за транзакцию, ставка отличается по локальным способам оплаты.",
 "Local methods often cost less than cards in the same market — worth routing deliberately.",
 "usage","from ~2.9% + fixed fee per transaction","sandbox access","https://www.rapyd.net/pricing/"),
("paid-modern-treasury","Modern Treasury (pricing)","Финансы","https://www.moderntreasury.com/pricing","paid","payment-ops,pricing,platform-fee,volume",
 "Payment operations platform billed as a platform fee plus per-payment volume.",
 "Платформа платёжных операций с абонентской платой плюс оплатой по объёму платежей.",
 "Priced for companies already moving real volume — not a self-serve starting point.",
 "subscription","custom quote (platform fee + volume)","sandbox access","https://www.moderntreasury.com/pricing"),
("paid-increase","Increase (pricing)","Финансы","https://increase.com/pricing","paid","banking,pricing,per-transaction,transparent",
 "Bank infrastructure with published per-transaction pricing by payment rail.",
 "Банковская инфраструктура с публичными тарифами за транзакцию по каждому платёжному рельсу.",
 "Publishing per-rail prices openly is rare in banking infrastructure and makes cost modelling easy.",
 "usage","from ~$0.10 per ACH transfer","sandbox access","https://increase.com/pricing"),
("paid-unit-banking","Unit (pricing)","Финансы","https://www.unit.co/pricing","paid","baas,pricing,platform-fee,accounts",
 "Banking-as-a-service billed as a monthly platform fee plus per-account and per-transaction charges.",
 "Banking-as-a-service с месячной платой за платформу плюс оплатой за счёт и за транзакцию.",
 "Interchange revenue from issued cards can offset much of the platform fee at scale.",
 "subscription","custom quote (platform fee + per account)","sandbox access","https://www.unit.co/pricing"),
("paid-column-bank","Column (pricing)","Финансы","https://column.com/pricing","paid","bank,pricing,per-transaction,direct",
 "Direct bank APIs priced per transaction with no intermediary platform fee.",
 "Прямые банковские API с оплатой за транзакцию без комиссии посредника.",
 "Cutting out the BaaS middle layer is exactly where the cost saving comes from.",
 "usage","from ~$0.05 per ACH transfer","sandbox access","https://column.com/pricing"),
("paid-dwolla","Dwolla (pricing)","Финансы","https://www.dwolla.com/pricing/","paid","ach,pricing,subscription,volume",
 "ACH transfer platform billed as a monthly subscription plus per-transfer fees.",
 "Платформа ACH-переводов с месячной подпиской плюс оплатой за перевод.",
 "The monthly minimum makes it expensive at low volume — compare against per-transaction-only rivals.",
 "subscription","from ~$250 per month","sandbox access","https://www.dwolla.com/pricing/"),
("paid-intrinio","Intrinio (pricing)","Финансы","https://intrinio.com/financial-market-data-pricing","paid","market-data,pricing,per-feed,subscription",
 "Financial data sold as separate per-feed subscriptions rather than one bundle.",
 "Финансовые данные продаются отдельными подписками на каждый фид, а не одним пакетом.",
 "Buying only the feeds you use keeps cost far below a full-market-data bundle.",
 "subscription","from ~$100 per month per feed","limited free sandbox","https://intrinio.com/financial-market-data-pricing"),
("paid-blockdaemon","Blockdaemon (pricing)","Web3 и блокчейн","https://www.blockdaemon.com/pricing","paid","nodes,pricing,institutional,sla",
 "Institutional node and staking infrastructure sold on enterprise contracts.",
 "Институциональная инфраструктура узлов и стейкинга по корпоративным контрактам.",
 "Priced for SLA-backed institutional use — free-tier RPC providers cover everything smaller.",
 "custom","custom quote","free tier for basic RPC","https://www.blockdaemon.com/pricing"),
]
