# -*- coding: utf-8 -*-
MCPS = [
("mcp-everything","Everything MCP Server","Инфраструктура MCP","https://github.com/modelcontextprotocol/servers/tree/main/src/everything","openSource","reference,testing,tools,prompts","npx -y @modelcontextprotocol/server-everything",
 "Reference server exercising every MCP feature: tools, prompts, resources and sampling.",
 "Эталонный сервер, задействующий все возможности MCP: tools, prompts, resources и sampling.",
 "The fastest way to confirm your client wiring works before debugging a real server."),
("mcp-inspector","MCP Inspector","Инфраструктура MCP","https://github.com/modelcontextprotocol/inspector","openSource","debug,devtools,protocol,testing","npx @modelcontextprotocol/inspector",
 "Visual debugger for MCP servers with live tool calls and logs.",
 "Визуальный отладчик MCP-серверов с живыми вызовами инструментов и логами.",
 "Run it against your server before connecting an agent: most bugs are visible here first."),

# ==================== Stage 4 additions ====================

("mcp-kubernetes","Kubernetes MCP Server","Инфраструктура MCP","https://github.com/containers/kubernetes-mcp-server","openSource","kubernetes,cluster,pods,operations","npx -y kubernetes-mcp-server@latest",
 "Cluster inspection and resource operations over the Kubernetes API.",
 "Инспекция кластера и операции с ресурсами через Kubernetes API.",
 "Point it at a read-only kubeconfig context first; a wrong scale command is instant and real."),
("mcp-jetbrains","JetBrains MCP Server","Локальные инструменты","https://github.com/JetBrains/mcp-jetbrains","openSource","ide,jetbrains,refactoring,editor","npx -y @jetbrains/mcp-proxy",
 "Exposes an open JetBrains IDE to an agent: files, refactorings and run configurations.",
 "Открывает агенту доступ к запущенной IDE JetBrains: файлы, рефакторинги и конфигурации запуска.",
 "The IDE must be running with the plugin enabled; the agent then reuses its project index."),
("mcp-pulumi","Pulumi MCP Server","Инфраструктура MCP","https://github.com/pulumi/mcp-server","openSource","iac,pulumi,preview,registry","npx -y @pulumi/mcp-server@latest stdio",
 "Runs Pulumi preview and deploy operations and queries the resource registry.",
 "Запускает preview и деплой Pulumi и обращается к реестру ресурсов.",
 "Keep it to preview until you trust the plan output; deploy is not a reversible tool call."),
("mcp-sonarqube","SonarQube MCP Server","Тестирование и качество","https://github.com/SonarSource/sonarqube-mcp-server","openSource","code-quality,static-analysis,issues,security","",
 "Brings SonarQube issues, hotspots and quality gates into the agent’s context.",
 "Приносит issues, hotspots и quality gate SonarQube в контекст агента.",
 "Useful for making the agent fix the findings it caused rather than reporting them to you."),
("mcp-neo4j","Neo4j MCP Servers","Память и знания","https://github.com/neo4j-contrib/mcp-neo4j","openSource","graph,cypher,memory,knowledge","pip install mcp-neo4j-cypher",
 "Cypher queries, schema introspection and graph-backed agent memory.",
 "Cypher-запросы, инспекция схемы и графовая память агента.",
 "A graph handles relationship questions that vector search answers badly, or not at all."),
("mcp-chroma","Chroma MCP Server","Векторные базы","https://github.com/chroma-core/chroma-mcp","openSource","vectors,embeddings,retrieval,memory","pip install chroma-mcp",
 "Vector collections an agent can write to and query as working memory.",
 "Векторные коллекции, в которые агент может писать и делать запросы как в рабочую память.",
 "Namespace collections per project or an agent will happily retrieve someone else’s notes."),
("mcp-mem0","Mem0 MCP Server","Память и знания","https://github.com/mem0ai/mem0-mcp","openSource","memory,preferences,recall,personalization","",
 "Persistent memory for user preferences and facts across sessions.",
 "Постоянная память пользовательских предпочтений и фактов между сессиями.",
 "Store decisions and preferences, not transcripts: recall quality falls as the store grows."),
("mcp-e2b","E2B MCP Server","Браузер и автоматизация","https://github.com/e2b-dev/mcp-server","openSource","sandbox,code-execution,isolation,cloud","npx -y @e2b/mcp-server",
 "Runs agent-generated code in an isolated cloud sandbox.",
 "Запускает сгенерированный агентом код в изолированной облачной песочнице.",
 "The right place for untrusted generated code: your laptop is not a sandbox."),
("mcp-heroku","Heroku MCP Server","Облако и деплой","https://github.com/heroku/heroku-mcp-server","openSource","deploy,apps,dynos,logs","npm i -g @heroku/mcp-server",
 "Manage Heroku apps, dynos, config vars and logs through MCP.",
 "Управление приложениями, dyno, config vars и логами Heroku через MCP.",
 "Reading logs and restarting a dyno covers most incident work without opening a dashboard."),
("mcp-shopify-dev","Shopify Dev MCP","Документация и контекст","https://github.com/Shopify/dev-mcp","openSource","shopify,graphql,schema,commerce","npx -y @shopify/dev-mcp@latest",
 "Shopify API schemas and documentation search for building storefronts and apps.",
 "Схемы API и поиск по документации Shopify для магазинов и приложений.",
 "Schema introspection stops the model inventing GraphQL fields that never existed."),
("mcp-paypal","PayPal MCP Server","Платежи и commerce","https://www.paypal.ai/docs/tools/mcp-quickstart","freeTier","payments,invoices,orders,commerce","",
 "Invoices, orders, subscriptions and transaction lookups over MCP.",
 "Счета, заказы, подписки и поиск транзакций через MCP.",
 "Use sandbox credentials while building: this server moves real money in production mode."),
("mcp-python-sdk","MCP Python SDK","Инфраструктура MCP","https://github.com/modelcontextprotocol/python-sdk","openSource","sdk,python,server,client","pip install mcp",
 "Official Python SDK for building MCP servers and clients.",
 "Официальный Python SDK для создания MCP-серверов и клиентов.",
 "Start from the stdio transport: it needs no networking and debugs in a plain terminal."),
("mcp-ts-sdk","MCP TypeScript SDK","Инфраструктура MCP","https://github.com/modelcontextprotocol/typescript-sdk","openSource","sdk,typescript,server,client","npm i @modelcontextprotocol/sdk",
 "Official TypeScript SDK for MCP servers and clients.",
 "Официальный TypeScript SDK для MCP-серверов и клиентов.",
 "Describe tool inputs with a schema: a vague description is the top cause of wrong tool calls."),
("mcp-fastmcp","FastMCP","Инфраструктура MCP","https://gofastmcp.com/","openSource","python,decorators,server,fast","pip install fastmcp",
 "Ergonomic Python framework that turns functions into MCP tools with decorators.",
 "Удобный Python-фреймворк, превращающий функции в MCP-инструменты декораторами.",
 "Docstrings become tool descriptions, so write them for the model, not only for humans."),
("mcp-registry","MCP Registry","Инфраструктура MCP","https://github.com/modelcontextprotocol/registry","openSource","registry,discovery,catalog,official","",
 "Official open registry of published MCP servers with a public API.",
 "Официальный открытый реестр опубликованных MCP-серверов с публичным API.",
 "This is the same source this app syncs from, so anything published here shows up in your catalog."),
("mcp-brave-search","Brave Search MCP","Поиск и retrieval","https://github.com/brave/brave-search-mcp-server","openSource","search,web,privacy,agent","npx -y @brave/brave-search-mcp-server",
 "Gives an agent independent web and local search through Brave.",
 "Даёт агенту независимый веб- и локальный поиск через Brave.",
 "Needs an API key with a free monthly quota: watch the per-second limit in agent loops."),
("mcp-exa","Exa MCP Server","Поиск и retrieval","https://github.com/exa-labs/exa-mcp-server","openSource","search,research,contents,agent","npx -y exa-mcp-server",
 "Neural search plus page contents exposed as MCP tools.",
 "Нейропоиск и содержимое страниц в виде MCP-инструментов.",
 "Ask for contents in the search tool call so the agent does not need a second fetch step."),
("mcp-tavily","Tavily MCP Server","Поиск и retrieval","https://github.com/tavily-ai/tavily-mcp","openSource","search,extract,research,agent","npx -y tavily-mcp",
 "Search and page extraction tuned for agent research loops.",
 "Поиск и извлечение страниц, заточенные под исследовательские циклы агентов.",
 "Extraction returns cleaned text, which keeps far more context budget than raw HTML."),
("mcp-huggingface","Hugging Face MCP","AI и агенты","https://huggingface.co/mcp","freeTier","models,datasets,spaces,search","",
 "Search models, datasets and Spaces directly from an agent session.",
 "Поиск моделей, датасетов и Spaces прямо из сессии агента.",
 "Useful for picking a model by benchmark and licence without leaving the editor."),
("mcp-vercel","Vercel MCP","Облако и деплой","https://vercel.com/docs/mcp/vercel-mcp","freeTier","deploy,logs,projects,hosting","",
 "Inspect projects, deployments and build logs from an agent.",
 "Просмотр проектов, деплоев и логов сборки прямо из агента.",
 "Reading a failed build log through the agent is much faster than clicking through the dashboard."),
("mcp-netlify","Netlify MCP Server","Облако и деплой","https://docs.netlify.com/build/build-with-ai/netlify-mcp-server/","freeTier","deploy,sites,functions,hosting","",
 "Create sites, trigger deploys and read build output through MCP.",
 "Создание сайтов, запуск деплоев и чтение вывода сборки через MCP.",
 "Give it a scoped token: deploy access is enough, account-wide access is not needed."),
("mcp-mongodb","MongoDB MCP Server","Базы данных и backend","https://github.com/mongodb-js/mongodb-mcp-server","openSource","mongodb,database,query,atlas","npx -y mongodb-mcp-server",
 "Query and manage MongoDB and Atlas clusters from an agent.",
 "Запросы и управление MongoDB и кластерами Atlas из агента.",
 "Connect with a read-only user first and only widen permissions when you actually need writes."),
("mcp-redis","Redis MCP Server","Базы данных и backend","https://github.com/redis/mcp-redis","openSource","redis,cache,keys,memory","",
 "Inspect keys, TTLs and cached values through MCP tools.",
 "Просмотр ключей, TTL и закэшированных значений через MCP-инструменты.",
 "Never point it at production without read-only mode: KEYS on a large database blocks the server."),
("mcp-clickhouse","ClickHouse MCP Server","Базы данных и backend","https://github.com/ClickHouse/mcp-clickhouse","openSource","analytics,sql,olap,query","",
 "Run analytical SQL against ClickHouse from an agent session.",
 "Выполнение аналитического SQL в ClickHouse из сессии агента.",
 "Always add a LIMIT: an agent-written analytical query can scan billions of rows."),
("mcp-elasticsearch","Elasticsearch MCP Server","Поиск и retrieval","https://github.com/elastic/mcp-server-elasticsearch","openSource","search,logs,index,query","",
 "Search indices and logs in Elasticsearch through MCP.",
 "Поиск по индексам и логам Elasticsearch через MCP.",
 "Excellent for incident triage: the agent can grep logs without a dashboard round trip."),
("mcp-grafana","Grafana MCP Server","Мониторинг и аналитика","https://github.com/grafana/mcp-grafana","openSource","dashboards,metrics,alerts,observability","",
 "Read dashboards, metrics and alerts from Grafana.",
 "Чтение дашбордов, метрик и алертов из Grafana.",
 "Pair it with an incident checklist skill so the agent knows which panels matter."),
("mcp-aws","AWS MCP Servers","Облако и деплой","https://github.com/awslabs/mcp","openSource","aws,cloud,infrastructure,official","",
 "Official collection of AWS MCP servers for documentation, cost and services.",
 "Официальная коллекция AWS MCP-серверов для документации, стоимости и сервисов.",
 "Install only the specific servers you need: the collection is large and permissions add up."),
("mcp-azure","Microsoft MCP Servers","Облако и деплой","https://github.com/microsoft/mcp","openSource","azure,microsoft,cloud,official","",
 "Microsoft's official MCP servers for Azure and developer services.",
 "Официальные MCP-серверы Microsoft для Azure и сервисов разработчика.",
 "Authentication reuses your existing Azure CLI login, which keeps secrets out of config files."),
("mcp-apify","Apify MCP Server","Браузер и автоматизация","https://docs.apify.com/platform/integrations/mcp","freeTier","scraping,actors,automation,web","",
 "Thousands of ready scrapers and automation actors exposed as MCP tools.",
 "Тысячи готовых скраперов и актор-автоматизаций в виде MCP-инструментов.",
 "Check the per-actor pricing before letting an agent call one in a loop."),
("mcp-zapier","Zapier MCP","Разработка и DevOps","https://zapier.com/mcp","freeTier","automation,integrations,actions,saas","",
 "Bridges an agent to thousands of SaaS actions through Zapier.",
 "Мост между агентом и тысячами SaaS-действий через Zapier.",
 "Expose only the specific actions you need: a broad action set confuses tool selection."),
("mcp-asana","Asana MCP Server","Разработка и DevOps","https://developers.asana.com/docs/mcp-server","freeTier","tasks,projects,work-management","",
 "Read and update Asana tasks and projects from an agent.",
 "Чтение и обновление задач и проектов Asana из агента.",
 "Start read-only: an agent that can close tasks needs a much more careful prompt."),
("mcp-serena","Serena","Разработка и DevOps","https://github.com/oraios/serena","openSource","code,symbols,lsp,refactor","",
 "Semantic code toolkit that gives agents symbol-level navigation and edits.",
 "Семантический тулкит кода: навигация и правки на уровне символов для агентов.",
 "Symbol-level edits use far fewer tokens than rewriting whole files."),
("mcp-semgrep","Semgrep MCP Server","Тестирование и качество","https://github.com/semgrep/mcp","openSource","security,static-analysis,scan,rules","",
 "Static analysis and security scanning available as agent tools.",
 "Статический анализ и security-сканирование как инструменты агента.",
 "Run it before every PR: an agent that writes code should also be made to scan it."),
("mcp-deepwiki","DeepWiki MCP","Документация и контекст","https://docs.devin.ai/work-with-devin/deepwiki-mcp","free","docs,repos,context,understanding","",
 "Generated documentation and Q&A for public GitHub repositories.",
 "Сгенерированная документация и вопросы-ответы по публичным репозиториям GitHub.",
 "Handy for onboarding into an unfamiliar dependency without reading its whole source."),
("mcp-blender","Blender MCP","Изображения и дизайн","https://github.com/ahujasid/blender-mcp","openSource","3d,blender,modeling,scene","",
 "Drives Blender scenes and objects from an agent conversation.",
 "Управляет сценами и объектами Blender из диалога с агентом.",
 "Save the .blend file before each agent run: generated operations are not always reversible."),
("mcp-obsidian","Obsidian MCP","Память и знания","https://github.com/MarkusPfundstein/mcp-obsidian","openSource","notes,markdown,vault,knowledge","",
 "Reads and writes an Obsidian markdown vault as agent memory.",
 "Читает и пишет markdown-хранилище Obsidian как память агента.",
 "Keep agent-written notes in a separate folder so you can always tell them from your own."),
("mcp-homeassistant","Home Assistant MCP","Локальные инструменты","https://www.home-assistant.io/integrations/mcp_server/","openSource","smart-home,automation,local,devices","",
 "Exposes a local smart home instance to MCP clients.",
 "Открывает локальный умный дом для MCP-клиентов.",
 "Runs entirely on your own network, which is the whole point compared to cloud assistants."),
]

SKILLS = [
("skill-agent-skills-docs","Agent Skills Overview","Гайды и практики","https://docs.claude.com/en/docs/agents-and-tools/agent-skills/overview","free","skills,concepts,claude,official","",
 "Official explanation of what Agent Skills are and how they load.",
 "Официальное объяснение, что такое Agent Skills и как они подгружаются.",
 "Read this before writing your first SKILL.md: the loading model explains most naming rules."),
("skill-authoring-best-practices","Skill Authoring Best Practices","Создание skills","https://docs.claude.com/en/docs/agents-and-tools/agent-skills/best-practices","free","skills,writing,description,structure","",
 "Anthropic's guidance on writing skill descriptions and structuring instructions.",
 "Рекомендации Anthropic по написанию описаний skill и структуре инструкций.",
 "The description field decides whether a skill ever triggers: write it about the task, not the tool."),
("skill-claude-code-plugins","Claude Code Plugins","Гайды и практики","https://docs.claude.com/en/docs/claude-code/plugins","free","plugins,commands,distribution,claude-code","",
 "How to bundle commands, skills and MCP servers into installable plugins.",
 "Как упаковать команды, skills и MCP-серверы в устанавливаемые плагины.",
 "Bundle a team workflow once and everyone installs it with a single command."),
("skill-subagents","Claude Code Subagents","Гайды и практики","https://docs.claude.com/en/docs/claude-code/sub-agents","free","subagents,delegation,context,claude-code","",
 "Delegating focused tasks to separate agents with their own context.",
 "Делегирование узких задач отдельным агентам с собственным контекстом.",
 "Use a subagent for long searches so the main conversation keeps its context budget."),
("skill-hooks","Claude Code Hooks","Гайды и практики","https://docs.claude.com/en/docs/claude-code/hooks","free","hooks,automation,lint,guardrails","",
 "Run your own commands automatically at defined points of an agent session.",
 "Автоматический запуск своих команд в определённых точках сессии агента.",
 "A format-and-test hook after every edit catches broken code before you ever see it."),
("skill-claude-md","CLAUDE.md Project Memory","Гайды и практики","https://docs.claude.com/en/docs/claude-code/memory","free","memory,context,conventions,project","",
 "Project-level instructions that load automatically in every session.",
 "Инструкции уровня проекта, которые подгружаются в каждой сессии.",
 "Put architecture rules here, not in chat: it is what keeps an agent consistent across sessions."),
("skill-mcp-in-claude-code","MCP in Claude Code","Гайды и практики","https://docs.claude.com/en/docs/claude-code/mcp","free","mcp,setup,scope,servers","",
 "Connecting, scoping and troubleshooting MCP servers in Claude Code.",
 "Подключение, области видимости и отладка MCP-серверов в Claude Code.",
 "Project scope keeps a server config in the repo so your teammates get it for free."),
("skill-agents-md","AGENTS.md","Гайды и практики","https://agents.md/","free","codex,conventions,instructions,standard","",
 "Open convention for a repository file that tells coding agents how to work.",
 "Открытое соглашение о файле в репозитории, объясняющем агентам правила работы.",
 "One file works across several agent tools, which avoids maintaining parallel instruction sets."),
("skill-codex-cli","Codex CLI","Гайды и практики","https://developers.openai.com/codex/cli/","mixed","codex,cli,terminal,agent","npm i -g @openai/codex",
 "Running the OpenAI coding agent from your terminal.",
 "Запуск кодового агента OpenAI из терминала.",
 "Sandbox and approval modes are the safety dial: learn them before granting write access."),
("skill-awesome-claude-code","Awesome Claude Code","Каталоги skills","https://github.com/hesreallyhim/awesome-claude-code","openSource","list,community,commands,workflows","",
 "Community collection of commands, hooks and workflows for Claude Code.",
 "Сообщественная подборка команд, хуков и workflow для Claude Code.",
 "Good place to copy a proven command before writing your own from scratch."),
("skill-awesome-mcp","Awesome MCP Servers","Каталоги skills","https://github.com/punkpeye/awesome-mcp-servers","openSource","list,mcp,community,discovery","",
 "Large community index of MCP servers grouped by purpose.",
 "Большой сообществвенный индекс MCP-серверов, сгруппированных по назначению.",
 "Cross-check anything you find here against the official registry before installing it."),
("skill-openai-agents-guide","OpenAI Agents Guide","Гайды и практики","https://platform.openai.com/docs/guides/agents","mixed","agents,tools,handoff,design","",
 "Official guidance on designing agent loops, tools and handoffs.",
 "Официальные рекомендации по проектированию циклов агентов, инструментов и передач.",
 "The handoff pattern is what keeps multi-step agents debuggable instead of magical."),
("skill-prompt-engineering","Prompt Engineering Overview","Гайды и практики","https://docs.claude.com/en/docs/build-with-claude/prompt-engineering/overview","free","prompting,examples,structure,quality","",
 "Practical prompting techniques with concrete before-and-after examples.",
 "Практические техники промптинга с конкретными примерами до и после.",
 "Examples beat adjectives: two good examples usually outperform a paragraph of instructions."),
("skill-tool-use","Tool Use Guide","Гайды и практики","https://docs.claude.com/en/docs/agents-and-tools/tool-use/overview","free","tools,schema,function-calling,agents","",
 "How to define tools and schemas that models call reliably.",
 "Как описывать инструменты и схемы, чтобы модель вызывала их надёжно.",
 "Name parameters the way a human would say them: the model reads names as documentation."),
("skill-context-engineering","Effective Context Engineering","Гайды и практики","https://www.anthropic.com/engineering/effective-context-engineering-for-ai-agents","free","context,agents,memory,tokens","",
 "Engineering guidance on what to keep in an agent's context and what to drop.",
 "Инженерные рекомендации: что держать в контексте агента, а что убирать.",
 "Treat context as a budget: everything you add competes with the instructions that matter."),
("skill-building-agents","Building Effective Agents","Гайды и практики","https://www.anthropic.com/engineering/building-effective-agents","free","agents,patterns,workflows,architecture","",
 "Patterns for agent workflows and when a simple chain beats an autonomous loop.",
 "Паттерны agent workflow и случаи, когда простая цепочка лучше автономного цикла.",
 "Start with the simplest pattern that solves the task: most problems are not agent-shaped."),

# ==================== Stage 4 additions ====================

("skill-writing-tools","Writing Effective Tools for Agents","Гайды и практики","https://www.anthropic.com/engineering/writing-tools-for-agents","free","tools,schemas,naming,design","",
 "How to design tool names, descriptions and schemas an agent can actually use.",
 "Как проектировать имена, описания и схемы инструментов, которыми агент реально может пользоваться.",
 "Tool descriptions are prompts: vague ones cause wrong calls far more often than bad models do."),
("skill-code-execution-mcp","Code Execution with MCP","Гайды и практики","https://www.anthropic.com/engineering/code-execution-with-mcp","free","mcp,tokens,efficiency,architecture","",
 "Calling MCP tools from generated code instead of loading every definition into context.",
 "Вызов MCP-инструментов из сгенерированного кода вместо загрузки всех определений в контекст.",
 "Worth reading once your server count grows: tool definitions quietly dominate the context budget."),
("skill-multi-agent-system","Multi-Agent Research System","Гайды и практики","https://www.anthropic.com/engineering/multi-agent-research-system","free","orchestration,subagents,evaluation,architecture","",
 "An engineering account of an orchestrator-with-subagents system and its trade-offs.",
 "Инженерный разбор системы «оркестратор и субагенты» и её компромиссов.",
 "Note the token cost honestly reported here before choosing a multi-agent design."),
("skill-claude-agent-sdk","Claude Agent SDK","Создание skills","https://docs.claude.com/en/api/agent-sdk/overview","free","sdk,agents,tools,permissions","",
 "The harness behind Claude Code, available as a library for your own agents.",
 "Тот же harness, что у Claude Code, доступный библиотекой для своих агентов.",
 "You inherit the tool loop, permission model and subagents instead of rebuilding them."),
("skill-slash-commands","Claude Code Slash Commands","Workflow skills","https://docs.claude.com/en/docs/claude-code/slash-commands","free","commands,prompts,workflow,reuse","",
 "Reusable prompt files invoked by name, with arguments and file references.",
 "Переиспользуемые файлы промптов, вызываемые по имени, с аргументами и ссылками на файлы.",
 "Any prompt you have typed twice should become a command in .claude/commands."),
("skill-plugin-marketplaces","Claude Code Plugin Marketplaces","Каталоги skills","https://docs.claude.com/en/docs/claude-code/plugin-marketplaces","free","plugins,distribution,marketplace,teams","",
 "Publishing and installing plugin bundles from a git-hosted marketplace.",
 "Публикация и установка наборов плагинов из marketplace на базе git.",
 "A repository plus a manifest is the whole distribution mechanism for a team’s tooling."),
("skill-claude-code-github","Claude Code GitHub Actions","Workflow skills","https://docs.claude.com/en/docs/claude-code/github-actions","free","ci,github,automation,review","",
 "Running Claude Code inside CI to review pull requests and act on issues.",
 "Запуск Claude Code в CI для ревью pull request и работы с issues.",
 "Scope the token tightly: an agent in CI has whatever access you granted the workflow."),
("skill-claude-code-headless","Claude Code Headless Mode","Workflow skills","https://docs.claude.com/en/docs/claude-code/headless","free","automation,scripting,pipelines,json","",
 "Non-interactive invocation for scripts and pipelines, with structured output.",
 "Неинтерактивный запуск для скриптов и пайплайнов со структурированным выводом.",
 "Stream JSON output and parse it rather than scraping the human-readable transcript."),
("skill-claude-code-devcontainer","Claude Code Devcontainer","Установка и миграция","https://docs.claude.com/en/docs/claude-code/devcontainer","free","devcontainer,docker,sandbox,isolation","",
 "A reference container for running the agent with network and filesystem limits.",
 "Эталонный контейнер для запуска агента с ограничениями сети и файловой системы.",
 "The sensible answer to broad permissions: isolate the environment instead of trusting the loop."),
("skill-claude-code-settings","Claude Code Settings","Установка и миграция","https://docs.claude.com/en/docs/claude-code/settings","free","configuration,permissions,hooks,env","",
 "Every configuration surface: permissions, hooks, environment and precedence order.",
 "Все точки конфигурации: разрешения, хуки, окружение и порядок приоритета.",
 "Project settings belong in git; keep machine-specific overrides in the local file."),
("skill-claude-code-security","Claude Code Security","Гайды и практики","https://docs.claude.com/en/docs/claude-code/security","free","security,permissions,injection,trust","",
 "The threat model: prompt injection, permission scope and what the agent can reach.",
 "Модель угроз: prompt injection, область разрешений и то, до чего агент может дотянуться.",
 "Treat fetched web pages and issue comments as untrusted input, because that is what they are."),
("skill-claude-code-costs","Claude Code Cost Management","Гайды и практики","https://docs.claude.com/en/docs/claude-code/costs","free","cost,tokens,context,limits","",
 "Where tokens actually go in an agent session and how to keep the bill predictable.",
 "Куда на самом деле уходят токены в сессии агента и как сделать расходы предсказуемыми.",
 "Long sessions cost more than long files: clear context between unrelated tasks."),
("skill-mcp-specification","MCP Specification","Инфраструктура MCP","https://modelcontextprotocol.io/specification/latest","free","protocol,spec,transports,authorization","",
 "The protocol itself: message shapes, transports, lifecycle and authorization.",
 "Сам протокол: формы сообщений, транспорты, жизненный цикл и авторизация.",
 "Read the transport and authorization sections before exposing a server beyond localhost."),
("skill-spec-kit","GitHub Spec Kit","Workflow skills","https://github.com/github/spec-kit","openSource","spec-driven,workflow,planning,templates","",
 "A spec-driven development workflow with templates for plan, tasks and implementation.",
 "Workflow разработки от спецификации с шаблонами плана, задач и реализации.",
 "Writing the spec first is what makes an agent’s output reviewable instead of surprising."),
("skill-openai-evals","OpenAI Evals","Тестирование и качество","https://platform.openai.com/docs/guides/evals","free","eval,graders,datasets,regression","",
 "Building graded evaluation runs for model and prompt changes.",
 "Построение оценочных прогонов с оценщиками для изменений модели и промпта.",
 "A twenty-case eval you actually run beats a hundred-case suite you never look at."),
]
