# -*- coding: utf-8 -*-
"""Stage 5 API pack AB: error tracking, APM, uptime monitoring, incident response, status pages."""

APIS_5AB = [
    # ---------- Ошибки и APM ----------
    ("api-lightstep-cloud", "ServiceNow Cloud Observability", "Наблюдаемость трасс", "https://docs.lightstep.com/", "paid", "tracing,opentelemetry,distributed,enterprise", "",
     "Distributed tracing platform built on OpenTelemetry, formerly Lightstep.",
     "Платформа распределённой трассировки на OpenTelemetry, ранее Lightstep.",
     "Its change intelligence correlates a latency regression with the deploy that caused it."),
    ("api-splunk", "Splunk", "Мониторинг и аналитика", "https://dev.splunk.com/", "paid", "logs,siem,enterprise,search", "",
     "Enterprise log analysis and security information platform.",
     "Корпоративная платформа анализа логов и информации о безопасности.",
     "Its ingest-based pricing is why log volume management becomes a project of its own."),
    ("api-sumologic", "Sumo Logic", "Мониторинг и аналитика", "https://help.sumologic.com/docs/api/", "paid", "logs,cloud-native,siem,analytics", "",
     "Cloud-native log management and security analytics.",
     "Облачное управление логами и аналитика безопасности.",
     "Its log reduction features cut ingest cost before the data is billed, which matters at volume."),
    ("api-betterstack", "Better Stack", "Мониторинг и аналитика", "https://betterstack.com/docs", "freeTier", "logs,uptime,incidents,unified", "",
     "Combined logs, uptime monitoring, incident management and status pages.",
     "Совмещённые логи, мониторинг доступности, управление инцидентами и страницы статуса.",
     "One product covering four categories is unusual, and it removes several integrations."),
    ("api-baselime", "Baselime", "Наблюдаемость трасс", "https://docs.cloudflare.com/workers-observability/", "freeTier", "serverless,opentelemetry,cloudflare,tracing", "",
     "Serverless-focused observability, now part of Cloudflare's Workers platform.",
     "Observability с фокусом на serverless, теперь часть платформы Cloudflare Workers.",
     "It was built for the short-lived function traces that traditional APM tools handle badly."),
    ("api-highlight-io", "Highlight.io", "Мониторинг и аналитика", "https://www.highlight.io/docs", "openSource", "session-replay,errors,logs,open-source", "",
     "Open-source observability combining session replay, errors and logs.",
     "Открытая observability, объединяющая запись сессий, ошибки и логи.",
     "Self-hostable in full, which is rare for session replay and matters for sensitive interfaces."),
    ("api-glitchtip", "GlitchTip", "Мониторинг и аналитика", "https://glitchtip.com/documentation", "openSource", "errors,sentry-compatible,self-host,lightweight", "",
     "Lightweight open-source error tracking compatible with Sentry SDKs.",
     "Лёгкое открытое отслеживание ошибок, совместимое с SDK Sentry.",
     "Existing Sentry clients point at it unchanged, so migrating is a DSN change."),
    ("api-rollbar", "Rollbar", "Мониторинг и аналитика", "https://docs.rollbar.com/", "freeTier", "errors,grouping,deploys,telemetry", "",
     "Error monitoring with deployment tracking and automatic grouping.",
     "Мониторинг ошибок с отслеживанием развёртываний и автоматической группировкой.",
     "Linking errors to deploys makes 'which release broke this' answerable immediately."),
    ("api-airbrake", "Airbrake", "Мониторинг и аналитика", "https://docs.airbrake.io/", "freeTier", "errors,performance,lightweight,mature", "",
     "Long-established error and performance monitoring service.",
     "Давно работающий сервис мониторинга ошибок и производительности.",
     "Simpler and cheaper than the large APM platforms if you only need error tracking."),
    ("api-raygun", "Raygun", "Мониторинг и аналитика", "https://raygun.com/documentation/", "paid", "errors,real-user-monitoring,performance,traces", "",
     "Error tracking with real user monitoring and code-level performance traces.",
     "Отслеживание ошибок с мониторингом реальных пользователей и трассами производительности на уровне кода.",
     "Its traces point at the specific method responsible, which shortens performance work considerably."),
    ("api-trackjs", "TrackJS", "Мониторинг и аналитика", "https://docs.trackjs.com/", "paid", "javascript,frontend,errors,telemetry", "",
     "Frontend JavaScript error tracking with user action telemetry.",
     "Отслеживание ошибок JavaScript на фронтенде с телеметрией действий пользователя.",
     "Its telemetry timeline shows what the user did before the error, which stack traces omit."),
    ("api-instana", "IBM Instana", "Мониторинг и аналитика", "https://www.ibm.com/docs/en/instana-observability", "paid", "apm,automatic,dependencies,enterprise", "",
     "Automatic application performance monitoring with dependency discovery.",
     "Автоматический мониторинг производительности приложений с обнаружением зависимостей.",
     "Its automatic instrumentation maps service dependencies without manual configuration."),
    ("api-appdynamics", "AppDynamics", "Мониторинг и аналитика", "https://docs.appdynamics.com/", "paid", "apm,business-transactions,enterprise,cisco", "",
     "Enterprise APM organized around business transactions rather than services.",
     "Корпоративный APM, построенный вокруг бизнес-транзакций, а не сервисов.",
     "Framing performance as business transactions makes impact legible to non-engineers."),
    ("api-site24x7", "Site24x7", "Мониторинг и аналитика", "https://www.site24x7.com/help/api/", "freeTier", "monitoring,uptime,apm,affordable", "",
     "All-in-one monitoring covering uptime, servers and applications.",
     "Универсальный мониторинг доступности, серверов и приложений.",
     "Considerably cheaper than the major APM vendors for comparable basic coverage."),

    # ---------- Мониторинг доступности ----------
    ("api-pingdom", "Pingdom", "Мониторинг и аналитика", "https://docs.pingdom.com/api/", "paid", "uptime,synthetic,global,alerts", "",
     "Uptime and synthetic monitoring from many global locations.",
     "Мониторинг доступности и синтетический мониторинг из множества локаций по миру.",
     "Multi-location checks distinguish a real outage from a single regional network problem."),
    ("api-cronitor", "Cronitor", "Мониторинг и аналитика", "https://cronitor.io/docs", "freeTier", "cron,heartbeat,uptime,jobs", "",
     "Monitors scheduled jobs and cron tasks via heartbeat pings.",
     "Мониторит запланированные задачи и cron через heartbeat-пинги.",
     "A job that silently stops running is invisible to uptime checks — this is what catches it."),
    ("api-healthchecks-io", "Healthchecks.io", "Мониторинг и аналитика", "https://healthchecks.io/docs/", "openSource", "cron,heartbeat,self-host,simple", "",
     "Cron job monitoring service, self-hostable and open source.",
     "Сервис мониторинга cron-задач, открытый и с возможностью self-hosting.",
     "Adding a curl at the end of a cron line is the entire integration."),
    ("api-uptime-kuma", "Uptime Kuma", "Мониторинг и аналитика", "https://github.com/louislam/uptime-kuma/wiki", "openSource", "self-host,uptime,status-page,free", "",
     "Self-hosted uptime monitoring with a built-in status page.",
     "Self-hosted мониторинг доступности со встроенной страницей статуса.",
     "One container replaces a paid uptime subscription for a personal or small-team setup."),
    ("api-gatus", "Gatus", "Мониторинг и аналитика", "https://gatus.io/docs", "openSource", "health-checks,yaml,self-host,go", "",
     "Health check dashboard configured entirely in YAML.",
     "Дашборд health-check, настраиваемый полностью в YAML.",
     "Configuration as code means the monitoring setup is reviewed and versioned like the service."),
    ("api-blackbox-exporter", "Blackbox Exporter", "Мониторинг и аналитика", "https://github.com/prometheus/blackbox_exporter", "openSource", "prometheus,probing,http,tls", "",
     "Probes endpoints over HTTP, TCP and ICMP for Prometheus.",
     "Проверяет эндпоинты по HTTP, TCP и ICMP для Prometheus.",
     "Its TLS certificate expiry metric prevents the outage nobody schedules but everyone eventually has."),

    # ---------- Управление инцидентами ----------
    ("api-incident-io", "incident.io", "Мониторинг и аналитика", "https://api-docs.incident.io/", "paid", "incidents,slack,workflows,postmortems", "",
     "Incident management run inside Slack, with automated workflows.",
     "Управление инцидентами прямо в Slack с автоматизированными процессами.",
     "Running the incident where the team already talks removes the tool-switching during an outage."),
    ("api-firehydrant", "FireHydrant", "Мониторинг и аналитика", "https://docs.firehydrant.com/", "paid", "incidents,runbooks,retrospectives,reliability", "",
     "Incident response with runbooks and structured retrospectives.",
     "Реагирование на инциденты с runbook и структурированными разборами.",
     "Its retrospective templates make postmortems consistent rather than dependent on who writes them."),
    ("api-rootly", "Rootly", "Мониторинг и аналитика", "https://docs.rootly.com/", "paid", "incidents,slack,automation,terraform", "",
     "Incident management with Slack workflows and Terraform-managed configuration.",
     "Управление инцидентами с процессами в Slack и конфигурацией через Terraform.",
     "Managing on-call configuration as code makes rotations reviewable in a pull request."),
    ("api-blameless", "Blameless", "Мониторинг и аналитика", "https://www.blameless.com/", "paid", "slo,incidents,reliability,retrospectives", "",
     "Reliability platform combining SLO tracking with incident retrospectives.",
     "Платформа надёжности, объединяющая отслеживание SLO и разборы инцидентов.",
     "Tying incidents to error budgets makes reliability tradeoffs a data question rather than an argument."),
    ("api-squadcast", "Squadcast", "Мониторинг и аналитика", "https://support.squadcast.com/docs", "freeTier", "on-call,incidents,slo,affordable", "",
     "On-call and incident response with a usable free tier.",
     "Дежурства и реагирование на инциденты с рабочим бесплатным тарифом.",
     "Its free tier covers a small team's on-call, which PagerDuty reserves for paid plans."),
    ("api-grafana-oncall", "Grafana OnCall", "Мониторинг и аналитика", "https://grafana.com/docs/oncall/latest/", "openSource", "on-call,grafana,open-source,escalation", "",
     "Open-source on-call management integrated with Grafana alerting.",
     "Открытое управление дежурствами, интегрированное с алертингом Grafana.",
     "Alerts and on-call in one system removes an integration that frequently breaks silently."),

    # ---------- Страницы статуса ----------
    ("api-instatus", "Instatus", "Мониторинг и аналитика", "https://instatus.com/help/api", "freeTier", "status-page,fast,affordable,subscribers", "",
     "Fast status pages with a free tier and subscriber notifications.",
     "Быстрые страницы статуса с бесплатным тарифом и уведомлениями подписчиков.",
     "Substantially cheaper than Statuspage for the same core function."),
    ("api-cachet", "Cachet", "Мониторинг и аналитика", "https://docs.cachethq.io/", "openSource", "status-page,self-host,php,free", "",
     "Open-source self-hosted status page system.",
     "Открытая self-hosted система страниц статуса.",
     "Host it outside your main infrastructure — a status page inside the outage is useless."),
]
