# -*- coding: utf-8 -*-
# (iid, name, category, url, access, tags, summary_en, summary_ru, tip_en,
#  model, from_price, free_quota, pricing_url)
PAID_5B = [
("paid-drugbank","DrugBank (pricing)","Здоровье и медицина","https://go.drugbank.com/pricing","paid","drugs,pricing,pharmacology,license",
 "Licensed pharmacology database, quote-based pricing for commercial use.",
 "Лицензированная фармакологическая база данных, цена по запросу для коммерческого использования.",
 "Academic and non-commercial use has separate, much cheaper licensing — check eligibility before the commercial quote.",
 "subscription","custom license quote","free academic license available","https://go.drugbank.com/pricing"),
("paid-project44","project44 (pricing)","Логистика и доставка","https://www.project44.com/","paid","freight,visibility,pricing,enterprise",
 "Enterprise supply-chain visibility platform, quote-based pricing by shipment volume.",
 "Корпоративная платформа видимости цепочки поставок, цена по запросу за объём отгрузок.",
 "This is an enterprise sales process from the start — there is no self-serve trial to test against your lanes.",
 "subscription","custom quote by shipment volume","no public trial","https://www.project44.com/"),
("paid-middesk","Middesk (pricing)","Идентификация и KYC","https://www.middesk.com/","paid","kyb,pricing,business-verification,custom",
 "Business verification (KYB) checks priced per verification, volume-tiered.",
 "Проверки бизнеса (KYB) с оплатой за проверку, тарифы по объёму.",
 "Ask for sandbox access to test against known-good and known-bad business records before any commercial commitment.",
 "usage","custom per-verification pricing","sandbox available on request","https://www.middesk.com/"),
("paid-postmark-templates","Postmark (pricing)","Коммуникации","https://postmarkapp.com/pricing","paid","email,pricing,transactional,volume",
 "Transactional email priced per monthly email volume.",
 "Транзакционная почта с оплатой по месячному объёму писем.",
 "The 100-email free trial is enough to validate templates and deliverability setup before paying.",
 "subscription","from ~$15 per month (10k emails)","100 free emails to start","https://postmarkapp.com/pricing"),
("paid-kagi-search","Kagi Search (pricing)","Инфраструктура MCP","https://kagi.com/pricing","paid","search,pricing,privacy,subscription",
 "Ad-free search billed as a personal subscription, with an API extension for the same account.",
 "Поиск без рекламы по личной подписке с расширением API для того же аккаунта.",
 "The free trial searches are enough to judge result quality before committing to a monthly plan.",
 "subscription","from ~$10 per month","free trial searches","https://kagi.com/pricing"),
("paid-rippling","Rippling (pricing)","HR и рекрутинг","https://www.rippling.com/pricing","paid","hr,payroll,pricing,per-employee",
 "Unified HR/IT/payroll platform priced per employee per month, modules billed separately.",
 "Единая платформа HR/IT/зарплат с оплатой за сотрудника в месяц, модули оплачиваются отдельно.",
 "Module-based pricing adds up fast — price the exact modules you need, not the platform headline rate.",
 "subscription","from ~$8 per employee per month","demo via sales","https://www.rippling.com/pricing"),
("paid-planetscale-vitess","PlanetScale (pricing)","Базы данных и backend","https://planetscale.com/pricing","paid","mysql,pricing,vitess,scaling",
 "Managed MySQL priced by cluster size and storage, no free tier since 2024.",
 "Управляемый MySQL с оплатой по размеру кластера и хранилищу, бесплатного тарифа нет с 2024 года.",
 "The free tier was removed — budget from the entry paid plan, unlike Neon or Supabase which still have one.",
 "subscription","from ~$39 per month","no free tier","https://planetscale.com/pricing"),
("paid-dynatrace","Dynatrace (pricing)","Мониторинг и аналитика","https://www.dynatrace.com/pricing/","paid","apm,pricing,observability,per-host",
 "Enterprise observability billed per host-hour plus data ingest volume.",
 "Корпоративная observability с оплатой за час работы хоста плюс объём принятых данных.",
 "Host-hour billing means idle non-production hosts still cost money — scope monitoring to what matters.",
 "usage","from ~$0.04 per host-hour","15-day free trial","https://www.dynatrace.com/pricing/"),
("paid-bunny-net","Bunny.net (pricing)","Изображения и дизайн","https://bunny.net/pricing/","paid","cdn,pricing,bandwidth,storage",
 "CDN and storage billed per GB transferred, priced by region.",
 "CDN и хранилище с оплатой за переданный ГБ, цена зависит от региона.",
 "Per-GB rates vary several-fold by region — check your actual traffic geography before estimating cost.",
 "usage","from ~$0.01 per GB","$1 minimum monthly spend","https://bunny.net/pricing/"),
("paid-intercom","Intercom (pricing)","Коммуникации","https://www.intercom.com/pricing","paid","support,pricing,seats,resolutions",
 "Customer support platform priced per seat plus per AI-resolved conversation.",
 "Платформа поддержки клиентов с оплатой за место плюс за разговор, решённый ИИ.",
 "The per-resolution AI charge is separate from seats — model both when estimating monthly cost.",
 "subscription","from ~$29 per seat per month","14-day free trial","https://www.intercom.com/pricing"),
("paid-front-app","Front (pricing)","Коммуникации","https://front.com/pricing","paid","shared-inbox,pricing,seats,collaboration",
 "Shared inbox and team collaboration priced per seat per month.",
 "Общий почтовый ящик и командная работа с оплатой за место в месяц.",
 "API access is gated to higher plans — verify your tier includes it before designing an integration.",
 "subscription","from ~$19 per seat per month","7-day free trial","https://front.com/pricing"),
("paid-hive-moderation","Hive Moderation (pricing)","AI-оценка и safety","https://thehive.ai/pricing","paid","moderation,pricing,images,usage",
 "Content moderation billed per item classified, with volume tiers.",
 "Модерация контента с оплатой за классифицированный объект, тарифы по объёму.",
 "Free trial credits are enough to benchmark accuracy on your own content before committing.",
 "usage","custom per-item pricing","free trial credits","https://thehive.ai/pricing"),
("paid-openai-embeddings","OpenAI Embeddings (pricing)","Поиск и retrieval","https://platform.openai.com/docs/pricing","paid","embeddings,pricing,tokens,openai",
 "Text embeddings billed per input token, far cheaper than generation.",
 "Текстовые эмбеддинги с оплатой за входной токен, заметно дешевле генерации.",
 "Embedding a large corpus is a one-time cost — batch it and store the vectors rather than re-embedding per query.",
 "usage","from ~$0.02 / 1M tokens (small model)","no free tier","https://platform.openai.com/docs/pricing"),
("paid-isbndb","ISBNdb (pricing)","Книги и знания","https://isbndb.com/apidocs/v2","paid","books,pricing,isbn,subscription",
 "ISBN book database access billed as a monthly subscription by request volume.",
 "Доступ к базе книг по ISBN по месячной подписке с тарифом по объёму запросов.",
 "Check coverage for your specific catalog niche during the trial — completeness varies by publisher and era.",
 "subscription","from ~$15 per month","limited trial requests","https://isbndb.com/isbn-database"),
("paid-tecton","Tecton (pricing)","Data engineering","https://www.tecton.ai/","paid","feature-store,pricing,ml,enterprise",
 "Managed feature platform, quote-based enterprise pricing.",
 "Управляемая платформа признаков, корпоративная цена по запросу.",
 "Self-hosting Feast is the free alternative — price Tecton against the ops cost of running Feast yourself.",
 "subscription","custom enterprise quote","demo via sales","https://www.tecton.ai/"),
("paid-browserstack","BrowserStack (pricing)","Тестирование и качество","https://www.browserstack.com/pricing","paid","testing,pricing,parallel,devices",
 "Cross-browser testing priced per parallel test session.",
 "Кроссбраузерное тестирование с оплатой за параллельную тестовую сессию.",
 "Parallel session count is the real cost lever — one session is cheap but makes a large suite slow.",
 "subscription","from ~$29 per month","free trial minutes","https://www.browserstack.com/pricing"),
("paid-saucelabs","Sauce Labs (pricing)","Тестирование и качество","https://saucelabs.com/pricing","paid","testing,pricing,parallel,cloud",
 "Cloud testing priced by concurrency and minutes.",
 "Облачное тестирование с оплатой по параллелизму и минутам.",
 "Open-source projects can request free access — worth asking before paying for a public repository's CI.",
 "subscription","custom quote by concurrency","free trial available","https://saucelabs.com/pricing"),
("paid-shodan","Shodan (pricing)","Безопасность и секреты","https://www.shodan.io/store/member","paid","security,pricing,scanning,lifetime",
 "Internet device search, sold as a one-time membership plus optional API credit packs.",
 "Поиск устройств в интернете: разовое членство плюс опциональные пакеты API-кредитов.",
 "The lifetime membership is frequently discounted around Black Friday, which is when most people buy it.",
 "credits","from ~$49 one-time membership","limited free account queries","https://www.shodan.io/store/member"),
("paid-x-twitter","X API (pricing)","Новости и сообщества","https://developer.x.com/en/portal/products","paid","twitter,pricing,tiers,api",
 "Tiered API access, with meaningful read access only on paid plans.",
 "Многоуровневый доступ к API, реальное чтение данных только на платных тарифах.",
 "The jump from free to Basic to Pro is steep — model your actual read volume before choosing a tier.",
 "subscription","from ~$100 per month (Basic)","free tier is write-only, capped","https://developer.x.com/en/portal/products"),
("paid-adyen","Adyen (pricing)","Платежи и commerce","https://www.adyen.com/pricing","paid","payments,pricing,interchange-plus,enterprise",
 "Interchange-plus payment pricing: a fixed processing fee plus the underlying card scheme costs.",
 "Ценообразование interchange-plus: фиксированная комиссия обработки плюс базовые расходы карточных схем.",
 "Interchange-plus is more transparent than blended pricing but harder to forecast without transaction mix data.",
 "commission","fixed fee plus interchange per transaction","test account for integration","https://www.adyen.com/pricing"),
("paid-github-copilot","GitHub Copilot (pricing)","AI и агенты","https://github.com/features/copilot/plans","paid","coding,pricing,subscription,seats",
 "AI coding assistant sold as a per-user monthly subscription, with a limited free tier.",
 "ИИ-ассистент программирования по месячной подписке на пользователя, с ограниченным бесплатным тарифом.",
 "Verified students and popular open-source maintainers get it free — check eligibility before paying.",
 "subscription","from ~$10 per user per month","free tier with monthly completion cap","https://github.com/features/copilot/plans"),
("paid-clearbit","Clearbit (pricing)","CRM и продажи","https://clearbit.com/pricing","paid","enrichment,pricing,credits,b2b",
 "Data enrichment sold in credit packs, now bundled into HubSpot plans.",
 "Обогащение данных пакетами кредитов, теперь входит в тарифы HubSpot.",
 "Packaging changed after the HubSpot acquisition — confirm current terms rather than trusting older guides.",
 "credits","credit-pack pricing via HubSpot","limited free credits","https://clearbit.com/pricing"),
("paid-urlbox","Urlbox (pricing)","Изображения и дизайн","https://urlbox.com/pricing","paid","screenshots,pricing,rendering,volume",
 "Screenshot rendering billed per monthly render volume.",
 "Рендеринг скриншотов с оплатой по месячному объёму.",
 "Caching rendered images is the single biggest lever on cost here, since renders are what you pay for.",
 "subscription","from ~$19 per month","free trial renders","https://urlbox.com/pricing"),
("paid-8thwall","8th Wall (pricing)","Анимация и 3D","https://www.8thwall.com/pricing","paid","webar,pricing,views,subscription",
 "WebAR platform billed by monthly project views on a subscription.",
 "WebAR-платформа с оплатой по месячным просмотрам проекта в рамках подписки.",
 "Development and testing are free — you only pay once a project goes live to real viewers.",
 "subscription","from ~$99 per month per project","free development and testing","https://www.8thwall.com/pricing"),
("paid-vectorizer-ai","Vectorizer.AI (pricing)","Изображения и дизайн","https://vectorizer.ai/pricing","paid","vectorization,pricing,credits,svg",
 "Raster-to-vector conversion sold in credit packs or a subscription.",
 "Конвертация растра в вектор пакетами кредитов или по подписке.",
 "Preview results are free and watermarked — validate quality on your images before buying credits.",
 "credits","from ~$9.99 per credit pack","free watermarked previews","https://vectorizer.ai/pricing"),
("paid-lalal-ai","LALAL.AI (pricing)","Аудио и голос","https://www.lalal.ai/pricing/","paid","stem-separation,pricing,minutes,audio",
 "Stem separation sold as prepaid processing minutes.",
 "Разделение на стемы с оплатой предоплаченными минутами обработки.",
 "Minutes never expire on most packs, which suits occasional rather than continuous use.",
 "credits","from ~$18 per minute pack","free trial minutes","https://www.lalal.ai/pricing/"),
("paid-deel","Deel (pricing)","HR и рекрутинг","https://www.deel.com/pricing/","paid","payroll,pricing,eor,per-employee",
 "Global hiring billed per contractor or per employee under employer-of-record.",
 "Глобальный найм с оплатой за подрядчика или сотрудника по модели employer-of-record.",
 "Contractor management is far cheaper than EOR — use EOR only where you need legal employment.",
 "subscription","from ~$49 per contractor per month","free HR platform tier","https://www.deel.com/pricing/"),
("paid-remote-com","Remote (pricing)","HR и рекрутинг","https://remote.com/pricing","paid","eor,pricing,payroll,per-employee",
 "Employer-of-record and contractor management billed per person per month.",
 "Employer-of-record и управление подрядчиками с оплатой за человека в месяц.",
 "EOR pricing is flat per employee regardless of country, unlike vendors that vary by jurisdiction.",
 "subscription","from ~$29 per contractor per month","free contractor management tier","https://remote.com/pricing"),
("paid-weglot","Weglot (pricing)","Локализация и i18n","https://www.weglot.com/pricing","paid","translation,pricing,words,subscription",
 "Website translation billed by translated word count and number of languages.",
 "Перевод сайта с оплатой по числу переведённых слов и количеству языков.",
 "Word count is cumulative across the site, so a large content site outgrows the lower tiers quickly.",
 "subscription","from ~€15 per month","free trial","https://www.weglot.com/pricing"),
]
