# -*- coding: utf-8 -*-
"""Stage 5 API pack P: no-code databases, docs collaboration, scheduling, misc SaaS."""

APIS_5P = [
    # ---------- Таблицы и no-code (deepen) ----------
    ("api-grist", "Grist", "Таблицы и no-code", "https://support.getgrist.com/api/", "openSource", "spreadsheet,database,formulas,self-host", "",
     "Spreadsheet-database hybrid with Python formulas and full self-hosting.",
     "Гибрид таблицы и базы данных с формулами на Python и полным self-hosting.",
     "Python formulas in cells are considerably more capable than spreadsheet formula languages."),
    ("api-teable", "Teable", "Таблицы и no-code", "https://help.teable.io/en/developer/api", "openSource", "database,no-code,postgres,airtable-alternative", "",
     "Postgres-backed no-code database with an Airtable-like interface.",
     "No-code база данных на Postgres с интерфейсом в духе Airtable.",
     "Data lives in real Postgres, so SQL access remains available alongside the spreadsheet UI."),
    ("api-rowy", "Rowy", "Таблицы и no-code", "https://docs.rowy.io/", "openSource", "firestore,spreadsheet,ui,low-code", "",
     "Spreadsheet UI on top of Firestore with cloud functions attached to columns.",
     "Табличный интерфейс поверх Firestore с облачными функциями, привязанными к колонкам.",
     "Useful specifically for teams already on Firebase who need a non-developer admin surface."),
    ("api-seatable", "SeaTable", "Таблицы и no-code", "https://api.seatable.io/", "freeTier", "database,no-code,self-host,collaboration", "",
     "Collaborative no-code database with self-hosting and a full REST API.",
     "Совместная no-code база данных с self-hosting и полноценным REST API.",
     "European hosting option matters for teams with data-residency requirements Airtable cannot meet."),

    # ---------- CMS и контент: collaboration ----------
    ("api-slite", "Slite API", "Документация и контекст", "https://developers.slite.com/", "freeTier", "docs,knowledge-base,team,notes", "",
     "Team knowledge base and documentation API.",
     "API базы знаний и документации для команд.",
     "Simpler and more opinionated than Notion, which suits teams that want fewer structural choices."),
    ("api-coda", "Coda API", "Таблицы и no-code", "https://coda.io/developers/apis/v1", "freeTier", "docs,tables,automation,no-code", "",
     "Documents that combine text, tables and automation, accessible programmatically.",
     "Документы, объединяющие текст, таблицы и автоматизацию, доступные программно.",
     "Its table rows behave like a database, which makes Coda a viable lightweight backend for small tools."),
    ("api-clickup-2", "ClickUp API", "Планирование и календари", "https://developer.clickup.com/docs", "freeTier", "tasks,project-management,docs,goals", "",
     "Task, doc and goal management API for the ClickUp workspace platform.",
     "API управления задачами, документами и целями платформы ClickUp.",
     "Webhooks are per-workspace — subscribe once rather than polling task lists for changes."),
    ("api-basecamp", "Basecamp API", "Планирование и календари", "https://github.com/basecamp/bc3-api", "mixed", "project-management,todos,messages,campfire", "",
     "Project management API covering todos, messages, schedules and campfires.",
     "API управления проектами: задачи, сообщения, расписания и чаты.",
     "Its API requires a descriptive User-Agent with contact info, and requests without one are rejected."),
    ("api-height-app", "Height API", "Планирование и календари", "https://height.notion.site/API-documentation-643aea5bf01742de9232e5971cb4afda", "freeTier", "tasks,project-management,api,automation", "",
     "Task management API with a strong automation and webhook story.",
     "API управления задачами с сильной поддержкой автоматизации и webhooks.",
     "Its activity feed model makes it straightforward to mirror task changes into another system."),

    # ---------- Платежи и commerce (deepen) ----------
    ("api-mollie", "Mollie", "Платежи и commerce", "https://docs.mollie.com/", "mixed", "payments,europe,sepa,ideal", "",
     "European payment provider with strong local method support (iDEAL, Bancontact, SEPA).",
     "Европейский платёжный провайдер с сильной поддержкой локальных методов (iDEAL, Bancontact, SEPA).",
     "Local payment methods matter enormously for European conversion — cards alone underperform there."),
    ("api-adyen", "Adyen", "Платежи и commerce", "https://docs.adyen.com/", "paid", "payments,enterprise,global,unified", "",
     "Enterprise payment platform covering online, in-store and mobile in one integration.",
     "Корпоративная платёжная платформа, покрывающая онлайн, офлайн и мобильные платежи в одной интеграции.",
     "Its unified commerce model is the draw for businesses with both physical and online sales channels."),
    ("api-square", "Square API", "Платежи и commerce", "https://developer.squareup.com/docs", "mixed", "payments,pos,inventory,commerce", "",
     "Payments, point of sale, inventory and catalog APIs for physical and online commerce.",
     "API платежей, POS, склада и каталога для офлайн- и онлайн-торговли.",
     "The sandbox provides test card numbers that trigger specific decline reasons — use them for error paths."),
    ("api-razorpay", "Razorpay", "Платежи и commerce", "https://razorpay.com/docs/api/", "mixed", "payments,india,upi,subscriptions", "",
     "Indian payment gateway with UPI, cards, netbanking and subscription support.",
     "Индийский платёжный шлюз с поддержкой UPI, карт, интернет-банкинга и подписок.",
     "UPI is the dominant payment method in India — card-only integrations lose most of the market."),

    # ---------- Коммуникации (deepen) ----------
    ("api-knock", "Knock", "Почта и уведомления", "https://docs.knock.app/", "freeTier", "notifications,workflows,multi-channel,in-app", "",
     "Notification infrastructure with cross-channel workflows and an in-app inbox component.",
     "Инфраструктура уведомлений с кросс-канальными workflow и компонентом входящих в приложении.",
     "Its prebuilt in-app inbox component saves building notification UI from scratch."),
    ("api-courier", "Courier", "Почта и уведомления", "https://www.courier.com/docs/", "freeTier", "notifications,routing,templates,multi-channel", "",
     "Notification API routing one message across email, SMS, push and chat with fallbacks.",
     "API уведомлений, маршрутизирующий одно сообщение по email, SMS, push и чату с резервными каналами.",
     "Channel fallback (try push, then email) is configured centrally rather than coded per notification."),
    ("api-pusher", "Pusher Channels", "Коммуникации", "https://pusher.com/docs/channels/", "freeTier", "realtime,websockets,pubsub,hosted", "",
     "Hosted realtime messaging over WebSockets with presence and private channels.",
     "Размещённая передача сообщений в реальном времени по WebSockets с присутствием и приватными каналами.",
     "Presence channels give you online-user lists without building your own connection tracking."),
    ("api-ably", "Ably", "Коммуникации", "https://ably.com/docs", "freeTier", "realtime,pubsub,websockets,guaranteed-delivery", "",
     "Realtime messaging platform with message ordering and delivery guarantees.",
     "Платформа обмена сообщениями в реальном времени с гарантиями порядка и доставки.",
     "Its connection recovery replays missed messages, which plain WebSockets leave you to implement."),
]
