# -*- coding: utf-8 -*-
"""Stage 5 library pack AV: file uploads, object storage, image processing and delivery, package CDNs."""

LIBS_5AV = [
    # ---------- Загрузка файлов ----------
    ("lib-uppy", "Uppy", "Изображения и дизайн", "https://uppy.io/docs/", "openSource", "uploads,resumable,ui,plugins", "npm i @uppy/core",
     "Modular file uploader with resumable uploads and a polished interface.",
     "Модульный загрузчик файлов с возобновляемой загрузкой и отточенным интерфейсом.",
     "Its tus support resumes a large upload after a dropped connection, which plain form posts cannot."),
    ("lib-filepond", "FilePond", "Изображения и дизайн", "https://pqina.nl/filepond/docs/", "openSource", "uploads,animated,plugins,lightweight", "npm i filepond",
     "Smooth file upload component with image preview and editing plugins.",
     "Плавный компонент загрузки файлов с превью изображений и плагинами редактирования.",
     "Its client-side image resizing plugin cuts upload size before the request even starts."),
    ("lib-filestack", "Filestack", "Изображения и дизайн", "https://www.filestack.com/docs/", "freeTier", "uploads,transformation,cdn,picker", "",
     "File upload and transformation API with a prebuilt file picker.",
     "API загрузки и преобразования файлов с готовым выбором файлов.",
     "Its picker pulls from Google Drive and Dropbox, which a plain file input cannot reach."),
    ("lib-bytescale", "Bytescale", "Изображения и дизайн", "https://www.bytescale.com/docs/", "freeTier", "uploads,cdn,transformation,storage", "",
     "File upload, storage and image transformation behind one API.",
     "Загрузка файлов, хранение и преобразование изображений через один API.",
     "Combining upload and delivery removes the storage-plus-CDN wiring most projects assemble by hand."),

    # ---------- Объектное хранилище ----------
    ("lib-minio", "MinIO", "Облако и деплой", "https://docs.min.io/", "mixed", "s3-compatible,self-host,object-storage,kubernetes", "",
     "S3-compatible object storage you run yourself.",
     "S3-совместимое объектное хранилище для самостоятельного развёртывания.",
     "Wire compatibility means every S3 SDK works unchanged, which makes local testing straightforward."),
    ("lib-seaweedfs", "SeaweedFS", "Облако и деплой", "https://github.com/seaweedfs/seaweedfs/wiki", "openSource", "distributed,files,s3,fast", "",
     "Distributed file system optimized for storing very large numbers of small files.",
     "Распределённая файловая система, оптимизированная под хранение огромного числа мелких файлов.",
     "Small-file performance is where it beats general object stores, which struggle with billions of objects."),
    ("lib-garage-s3", "Garage", "Облако и деплой", "https://garagehq.deuxfleurs.fr/documentation/", "openSource", "s3,lightweight,self-host,geo-distributed", "",
     "Lightweight S3-compatible store designed for geo-distributed self-hosting.",
     "Лёгкое S3-совместимое хранилище для геораспределённого self-hosting.",
     "It tolerates high-latency links between nodes, which MinIO's clustering does not."),
    ("lib-backblaze-b2", "Backblaze B2", "Облако и деплой", "https://www.backblaze.com/docs/cloud-storage", "paid", "object-storage,cheap,s3-compatible,egress", "",
     "Low-cost cloud object storage with an S3-compatible API.",
     "Дешёвое облачное объектное хранилище с S3-совместимым API.",
     "Free egress to Cloudflare partners is what makes it far cheaper than S3 for media delivery."),
    ("lib-wasabi", "Wasabi", "Облако и деплой", "https://docs.wasabi.com/", "paid", "object-storage,flat-pricing,no-egress-fees,s3", "",
     "Object storage with flat pricing and no egress or request fees.",
     "Объектное хранилище с фиксированной ценой без платы за исходящий трафик и запросы.",
     "Its minimum retention period penalizes short-lived data, which the flat rate can obscure."),
    ("lib-filebase", "Filebase", "Облако и деплой", "https://docs.filebase.com/", "paid", "s3,ipfs,decentralized,gateway", "",
     "S3-compatible gateway to decentralized storage networks.",
     "S3-совместимый шлюз к децентрализованным сетям хранения.",
     "It puts an S3 interface in front of IPFS, so decentralized storage needs no new client code."),
    ("lib-cloudflare-r2", "Cloudflare R2", "Облако и деплой", "https://developers.cloudflare.com/r2/", "freeTier", "object-storage,zero-egress,s3-compatible,workers", "",
     "S3-compatible object storage with no egress fees.",
     "S3-совместимое объектное хранилище без платы за исходящий трафик.",
     "Zero egress is the entire pitch, and it changes the economics of serving media substantially."),
    ("lib-cloudflare-images", "Cloudflare Images", "Изображения и дизайн", "https://developers.cloudflare.com/images/", "paid", "storage,transformation,delivery,variants", "",
     "Image storage, resizing and delivery in one service.",
     "Хранение, изменение размера и доставка изображений в одном сервисе.",
     "Its variants let one stored original serve every layout without storing each size."),

    # ---------- Обработка изображений ----------
    ("lib-imgproxy", "imgproxy", "Изображения и дизайн", "https://docs.imgproxy.net/", "mixed", "on-the-fly,resizing,secure,go", "",
     "Fast on-the-fly image processing server with signed URLs.",
     "Быстрый сервер обработки изображений на лету с подписанными URL.",
     "URL signing prevents strangers from using your server as a free image processor."),
    ("lib-thumbor", "Thumbor", "Изображения и дизайн", "https://thumbor.readthedocs.io/", "openSource", "on-demand,cropping,smart-detection,python", "",
     "On-demand image cropping and resizing with smart focal point detection.",
     "Обрезка и изменение размера изображений по запросу с определением фокусной точки.",
     "Its face and feature detection keeps the subject in frame when aspect ratios change."),
    ("lib-sharp", "Sharp", "Изображения и дизайн", "https://sharp.pixelplumbing.com/", "openSource", "node,libvips,fast,resizing", "npm i sharp",
     "High-performance Node image processing built on libvips.",
     "Высокопроизводительная обработка изображений в Node на базе libvips.",
     "Several times faster than ImageMagick and uses far less memory on large images."),
    ("lib-libvips", "libvips", "Изображения и дизайн", "https://www.libvips.org/API/current/", "openSource", "c,streaming,low-memory,fast", "",
     "Demand-driven image processing library with very low memory use.",
     "Библиотека обработки изображений по требованию с очень низким потреблением памяти.",
     "It streams rather than loading whole images, which is why memory stays flat on huge files."),
    ("lib-jimp", "Jimp", "Изображения и дизайн", "https://jimp-dev.github.io/jimp/", "openSource", "javascript,pure-js,no-native,simple", "npm i jimp",
     "Pure JavaScript image processing with no native dependencies.",
     "Обработка изображений на чистом JavaScript без нативных зависимостей.",
     "Slower than Sharp, but it installs anywhere, including environments that block native builds."),
    ("lib-pillow", "Pillow", "Изображения и дизайн", "https://pillow.readthedocs.io/", "openSource", "python,imaging,formats,standard", "pip install pillow",
     "The standard Python imaging library.",
     "Стандартная библиотека обработки изображений для Python.",
     "Its format support is broad enough that most Python image work starts and ends here."),
    ("lib-squoosh", "Squoosh", "Изображения и дизайн", "https://github.com/GoogleChromeLabs/squoosh", "openSource", "compression,wasm,codecs,browser", "",
     "Image compression tool and WASM codec libraries from Google.",
     "Инструмент сжатия изображений и WASM-кодеки от Google.",
     "Its codecs run in the browser, so compression can happen entirely client-side before upload."),

    # ---------- Форматы и плейсхолдеры ----------
    ("lib-avif", "AVIF", "Изображения и дизайн", "https://developer.mozilla.org/en-US/docs/Web/Media/Guides/Formats/Image_types", "free", "format,compression,modern,av1", "",
     "Modern image format with substantially better compression than JPEG.",
     "Современный формат изображений с существенно лучшим сжатием, чем JPEG.",
     "Encoding is slow — precompute AVIF variants rather than generating them per request."),
    ("lib-webp", "WebP", "Изображения и дизайн", "https://developers.google.com/speed/webp", "free", "format,google,compression,universal-support", "",
     "Google's image format with wide browser support and good compression.",
     "Формат изображений Google с широкой поддержкой браузеров и хорошим сжатием.",
     "Universally supported now, which makes it the safe default where AVIF is still risky."),
    ("lib-blurhash", "BlurHash", "Изображения и дизайн", "https://blurha.sh/", "openSource", "placeholder,compact,string,loading", "npm i blurhash",
     "Encodes a blurred image placeholder into a very short string.",
     "Кодирует размытый плейсхолдер изображения в очень короткую строку.",
     "Around thirty characters fits in a database row, so placeholders need no extra requests."),
    ("lib-thumbhash", "ThumbHash", "Изображения и дизайн", "https://evanw.github.io/thumbhash/", "openSource", "placeholder,compact,better-quality,alpha", "npm i thumbhash",
     "Compact image placeholder encoding with better fidelity than BlurHash.",
     "Компактное кодирование плейсхолдеров изображений с большей точностью, чем BlurHash.",
     "It preserves aspect ratio and transparency, which BlurHash discards."),
    ("lib-plaiceholder", "Plaiceholder", "Изображения и дизайн", "https://plaiceholder.co/docs", "openSource", "placeholders,build-time,css,base64", "npm i plaiceholder",
     "Generates image placeholders at build time in several formats.",
     "Генерирует плейсхолдеры изображений на этапе сборки в нескольких форматах.",
     "Build-time generation means no runtime cost for the placeholder at all."),
    ("lib-unpic", "unpic", "Изображения и дизайн", "https://unpic.pics/", "openSource", "responsive-images,cdn-agnostic,components,multi-framework", "npm i @unpic/react",
     "Responsive image components that work with any image CDN.",
     "Компоненты адаптивных изображений, работающие с любым image CDN.",
     "Switching image CDNs becomes a configuration change rather than rewriting every image tag."),
    ("lib-next-cloudinary", "next-cloudinary", "Изображения и дизайн", "https://next.cloudinary.dev/", "openSource", "nextjs,cloudinary,components,transformations", "npm i next-cloudinary",
     "Cloudinary components and transformations for Next.js.",
     "Компоненты и преобразования Cloudinary для Next.js.",
     "Transformations are expressed as component props, which keeps URLs out of the markup."),

    # ---------- Доставка контента ----------
    ("lib-fastly-io", "Fastly Image Optimizer", "Изображения и дизайн", "https://www.fastly.com/documentation/reference/io/", "paid", "cdn,transformation,edge,realtime", "",
     "Image transformation at the edge within Fastly's CDN.",
     "Преобразование изображений на edge внутри CDN Fastly.",
     "Transforming at the edge means the origin stores one original and serves every variant."),
    ("lib-akamai-image-manager", "Akamai Image & Video Manager", "Изображения и дизайн", "https://techdocs.akamai.com/ivm/docs", "paid", "cdn,optimization,automatic,enterprise", "",
     "Automatic image and video optimization within Akamai's CDN.",
     "Автоматическая оптимизация изображений и видео в CDN Akamai.",
     "Its automatic format and quality selection needs no per-image configuration."),
    ("lib-keycdn", "KeyCDN", "Облако и деплой", "https://www.keycdn.com/support", "paid", "cdn,affordable,pay-as-you-go,image-processing", "",
     "Affordable pay-as-you-go content delivery network.",
     "Доступная сеть доставки контента с оплатой по факту использования.",
     "No monthly minimum, which suits a project with irregular or unpredictable traffic."),
    ("lib-jsdelivr", "jsDelivr", "Сборка и bundlers", "https://www.jsdelivr.com/documentation", "free", "cdn,npm,github,free", "",
     "Free CDN serving npm packages, GitHub releases and WordPress assets.",
     "Бесплатный CDN, отдающий npm-пакеты, релизы GitHub и ресурсы WordPress.",
     "Pin an exact version in the URL — a floating version can change your site without a deploy."),
    ("lib-unpkg", "unpkg", "Сборка и bundlers", "https://unpkg.com/", "free", "cdn,npm,simple,free", "",
     "CDN serving any file from any npm package.",
     "CDN, отдающий любой файл из любого npm-пакета.",
     "Handy for prototypes and demos, and not something to depend on in production."),
    ("lib-skypack", "Skypack", "Сборка и bundlers", "https://www.skypack.dev/", "free", "esm,cdn,npm,browser", "",
     "CDN converting npm packages into browser-ready ES modules.",
     "CDN, преобразующий npm-пакеты в готовые для браузера ES-модули.",
     "Largely superseded by esm.sh, which is more actively maintained."),
    ("lib-esm-sh", "esm.sh", "Сборка и bundlers", "https://esm.sh/", "openSource", "esm,cdn,npm,deno", "",
     "Modern ES module CDN for npm packages, popular with Deno.",
     "Современный CDN ES-модулей для npm-пакетов, популярный в Deno.",
     "It handles dependency resolution and bundling, so a single import works without a build step."),
]
