# -*- coding: utf-8 -*-
"""Stage 5 pricing pack J: object storage, image delivery and CDN services."""

PAID_5J = [
("paid-backblaze-b2","Backblaze B2 (pricing)","Облако и деплой","https://www.backblaze.com/cloud-storage/pricing","paid","storage,pricing,per-gb,egress",
 "Object storage billed per gigabyte stored, with free egress to partner networks.",
 "Объектное хранилище с оплатой за гигабайт хранения и бесплатным трафиком к партнёрским сетям.",
 "Free egress through Cloudflare is where the real saving over S3 comes from, not the storage rate.",
 "usage","from ~$6 per TB per month","10GB free storage","https://www.backblaze.com/cloud-storage/pricing"),
("paid-wasabi","Wasabi (pricing)","Облако и деплой","https://wasabi.com/cloud-object-storage/pricing","paid","storage,pricing,flat,no-egress",
 "Flat per-terabyte storage pricing with no egress or request charges.",
 "Фиксированная цена за терабайт хранения без платы за трафик и запросы.",
 "Its 90-day minimum retention means short-lived data is billed as if it stayed for months.",
 "usage","from ~$6.99 per TB per month","free trial","https://wasabi.com/cloud-object-storage/pricing"),
("paid-filebase","Filebase (pricing)","Облако и деплой","https://filebase.com/pricing/","paid","storage,pricing,per-gb,ipfs",
 "Decentralized storage gateway billed per gigabyte stored and transferred.",
 "Шлюз децентрализованного хранения с оплатой за гигабайт хранения и передачи.",
 "You pay for the S3 interface and pinning, which raw IPFS would leave you to operate yourself.",
 "usage","from ~$5.99 per TB per month","free tier of 5GB","https://filebase.com/pricing/"),
("paid-cloudflare-images","Cloudflare Images (pricing)","Изображения и дизайн","https://developers.cloudflare.com/images/pricing/","paid","images,pricing,per-image,delivery",
 "Image storage and delivery billed per stored image and per images delivered.",
 "Хранение и доставка изображений с оплатой за хранимое изображение и за доставленные изображения.",
 "Variants cost nothing extra, so serving many sizes from one original is the efficient pattern.",
 "usage","from ~$5 per 100k stored images","free tier via transformations","https://developers.cloudflare.com/images/pricing/"),
("paid-fastly-io","Fastly Image Optimizer (pricing)","Изображения и дизайн","https://www.fastly.com/pricing","paid","cdn,pricing,per-request,add-on",
 "Edge image transformation billed as an add-on to Fastly CDN usage.",
 "Преобразование изображений на edge как дополнение к использованию CDN Fastly.",
 "Only makes sense if Fastly is already your CDN — as a standalone image service it is expensive.",
 "usage","custom quote (add-on to CDN usage)","free trial credit","https://www.fastly.com/pricing"),
("paid-akamai-image-manager","Akamai Image & Video Manager (pricing)","Изображения и дизайн","https://www.akamai.com/products/image-and-video-manager","paid","cdn,pricing,enterprise,add-on",
 "Image and video optimization sold as an add-on to Akamai delivery contracts.",
 "Оптимизация изображений и видео как дополнение к контрактам доставки Akamai.",
 "Enterprise CDN contract territory — not something bought independently for a single site.",
 "custom","custom quote","product demo","https://www.akamai.com/products/image-and-video-manager"),
("paid-keycdn","KeyCDN (pricing)","Облако и деплой","https://www.keycdn.com/pricing","paid","cdn,pricing,per-gb,pay-as-you-go",
 "Content delivery billed per gigabyte transferred, varying by region.",
 "Доставка контента с оплатой за переданный гигабайт, ставка зависит от региона.",
 "No monthly minimum, which makes it viable for a low-traffic site that a CDN contract would not.",
 "usage","from ~$0.04 per GB","free trial credit","https://www.keycdn.com/pricing"),
("paid-devin","Devin (pricing)","Разработка и DevOps","https://devin.ai/pricing","paid","agent,pricing,acu,subscription",
 "Autonomous coding agent billed in agent compute units on a monthly plan.",
 "Автономный агент кодирования с оплатой в единицах агентных вычислений по месячному плану.",
 "Cost per completed task varies enormously with task clarity — pilot on well-scoped work first.",
 "subscription","from ~$20 per month plus usage","free trial credit","https://devin.ai/pricing"),
("paid-amp-code","Amp (pricing)","Разработка и DevOps","https://ampcode.com/manual#pricing","paid","agent,pricing,usage,tokens",
 "Agentic coding tool billed by token usage rather than a seat licence.",
 "Агентный инструмент кодирования с оплатой по расходу токенов, а не за место.",
 "Usage billing suits occasional heavy sessions better than a flat per-seat subscription.",
 "usage","pay-as-you-go by token usage","free trial credit","https://ampcode.com/manual#pricing"),
("paid-augment-code","Augment Code (pricing)","Разработка и DevOps","https://www.augmentcode.com/pricing","paid","assistant,pricing,per-user,subscription",
 "Codebase-aware assistant billed per developer per month.",
 "Ассистент с пониманием кодовой базы и оплатой за разработчика в месяц.",
 "Its retrieval over huge repositories is what justifies the premium over generic completion tools.",
 "subscription","from ~$50 per user per month","free trial","https://www.augmentcode.com/pricing"),
("paid-greptile","Greptile (pricing)","Тестирование и качество","https://www.greptile.com/pricing","paid","code-review,pricing,per-developer,subscription",
 "AI code review billed per active developer per month.",
 "AI-ревью кода с оплатой за активного разработчика в месяц.",
 "Billing on active developers rather than repository count suits a monorepo team well.",
 "subscription","from ~$30 per developer per month","free trial","https://www.greptile.com/pricing"),
("paid-ellipsis","Ellipsis (pricing)","Тестирование и качество","https://www.ellipsis.dev/pricing","paid","code-review,pricing,per-seat,subscription",
 "AI pull request reviewer billed per seat.",
 "AI-ревьюер pull request с оплатой за место.",
 "Free for open-source repositories, which makes evaluating it on real code straightforward.",
 "subscription","from ~$20 per seat per month","free for open source","https://www.ellipsis.dev/pricing"),
("paid-vast-ai","Vast.ai (pricing)","Локальные модели","https://vast.ai/pricing","paid","gpu,pricing,per-hour,marketplace",
 "GPU rental billed per hour at rates set by individual hosts.",
 "Аренда GPU с почасовой оплатой по ставкам, устанавливаемым отдельными хостами.",
 "Interruptible instances cost a fraction of on-demand, which suits checkpointed training runs.",
 "usage","from ~$0.20 per hour","free trial credit","https://vast.ai/pricing"),
("paid-midjourney","Midjourney (pricing)","Изображения и дизайн","https://docs.midjourney.com/hc/en-us/articles/29273914197901","paid","image-generation,pricing,subscription,gpu-minutes",
 "Image generation sold as monthly plans with fast GPU time allowances.",
 "Генерация изображений по месячным планам с квотой быстрого GPU-времени.",
 "The lower tiers exhaust fast hours quickly, after which generation queues behind other users.",
 "subscription","from ~$10 per month","no free tier","https://docs.midjourney.com/hc/en-us/articles/29273914197901"),
("paid-magnific","Magnific AI (pricing)","Изображения и дизайн","https://magnific.ai/pricing","paid","upscaling,pricing,credits,subscription",
 "AI upscaling sold as monthly credit allowances.",
 "AI-апскейлинг с месячной квотой кредитов.",
 "Each upscale consumes credits by output size, so large images drain a plan fast.",
 "subscription","from ~$39 per month","no free tier","https://magnific.ai/pricing"),
("paid-freepik-api","Freepik API (pricing)","Изображения и дизайн","https://www.freepik.com/api/pricing","paid","stock,pricing,credits,licensing",
 "Stock assets and generation sold as API credits with commercial licensing.",
 "Стоковые ресурсы и генерация в виде API-кредитов с коммерческой лицензией.",
 "The licence covering commercial use is a substantial part of what the credits buy.",
 "credits","from ~$0.004 per credit","free trial credits","https://www.freepik.com/api/pricing"),
]
