# -*- coding: utf-8 -*-
"""Stage 5 library pack P: data science depth, notebooks, geospatial, scientific."""

LIBS_5P = [
    # ---------- Данные и ML: notebooks/tools ----------
    ("lib-jupyter", "JupyterLab", "Данные и ML", "https://jupyterlab.readthedocs.io/", "openSource", "notebooks,python,interactive,data-science", "pip install jupyterlab",
     "The standard interactive notebook environment for data science and exploration.",
     "Стандартная среда интерактивных ноутбуков для data science и исследования данных.",
     "Restart-and-run-all before sharing a notebook — hidden state from out-of-order cells is the classic trap."),
    ("lib-marimo", "marimo", "Данные и ML", "https://docs.marimo.io/", "openSource", "notebooks,reactive,python,reproducible", "pip install marimo",
     "Reactive Python notebook stored as a plain .py file, with no hidden execution state.",
     "Реактивный Python-ноутбук в виде обычного .py файла без скрытого состояния выполнения.",
     "Being plain Python means notebooks diff and merge in git properly, unlike .ipynb JSON."),
    ("lib-quarto", "Quarto", "Документация и контекст", "https://quarto.org/docs/guide/", "openSource", "publishing,notebooks,reports,multi-language", "",
     "Scientific publishing system rendering notebooks and markdown to sites, PDFs and slides.",
     "Система научной публикации, превращающая ноутбуки и markdown в сайты, PDF и слайды.",
     "One source document renders to every output format, which suits reproducible research reports."),
    ("lib-panel-holoviz", "Panel", "Данные и ML", "https://panel.holoviz.org/", "openSource", "dashboards,python,interactive,holoviz", "pip install panel",
     "Python dashboarding library working with most plotting libraries and notebooks.",
     "Python-библиотека дашбордов, работающая с большинством библиотек графиков и ноутбуками.",
     "More flexible than Streamlit for complex layouts, at the cost of a steeper learning curve."),
    ("lib-shiny-python", "Shiny for Python", "Данные и ML", "https://shiny.posit.co/py/", "openSource", "dashboards,python,reactive,posit", "pip install shiny",
     "Reactive web application framework for Python, ported from R's Shiny.",
     "Реактивный фреймворк веб-приложений для Python, портированный из R Shiny.",
     "Its reactive model recomputes only what changed, which scales better than Streamlit's full rerun."),

    # ---------- Данные и ML: scientific ----------
    ("lib-sympy", "SymPy", "Наука и исследования", "https://docs.sympy.org/", "openSource", "symbolic,math,python,algebra", "pip install sympy",
     "Symbolic mathematics in pure Python: algebra, calculus, equation solving.",
     "Символьная математика на чистом Python: алгебра, анализ, решение уравнений.",
     "Use it to derive an exact formula, then lambdify it into a fast numeric function for actual computation."),
    ("lib-networkx", "NetworkX", "Данные и ML", "https://networkx.org/documentation/stable/", "openSource", "graphs,networks,algorithms,python", "pip install networkx",
     "Graph and network analysis in Python: algorithms, metrics and visualization.",
     "Анализ графов и сетей в Python: алгоритмы, метрики и визуализация.",
     "Pure Python, so it slows past roughly a million edges — switch to igraph or graph-tool at that scale."),
    ("lib-scikit-image", "scikit-image", "Компьютерное зрение", "https://scikit-image.org/docs/stable/", "openSource", "image-processing,python,scientific,algorithms", "pip install scikit-image",
     "Scientific image processing algorithms in Python, complementing OpenCV.",
     "Научные алгоритмы обработки изображений в Python, дополняют OpenCV.",
     "Its API is more NumPy-native than OpenCV's, which fits better inside a scientific Python pipeline."),
    ("lib-astropy", "Astropy", "Космос и наука", "https://docs.astropy.org/", "openSource", "astronomy,science,python,fits", "pip install astropy",
     "Core astronomy library for Python: coordinates, time systems, FITS files, units.",
     "Основная астрономическая библиотека Python: координаты, системы времени, FITS-файлы, единицы.",
     "Its units system catches dimensional errors at runtime, which is invaluable in scientific code."),
    ("lib-biopython", "Biopython", "Наука и исследования", "https://biopython.org/wiki/Documentation", "openSource", "bioinformatics,sequences,python,genomics", "pip install biopython",
     "Bioinformatics toolkit for sequence analysis, file parsing and database access.",
     "Тулкит биоинформатики для анализа последовательностей, парсинга файлов и доступа к базам.",
     "Its parsers cover the many awkward bioinformatics file formats you would otherwise hand-parse."),

    # ---------- Погода и геоданные: geospatial libs ----------
    ("lib-geopandas", "GeoPandas", "Погода и геоданные", "https://geopandas.org/en/stable/docs.html", "openSource", "geospatial,pandas,shapefiles,python", "pip install geopandas",
     "Pandas dataframes extended with geometry columns and spatial operations.",
     "Датафреймы Pandas, расширенные геометрическими колонками и пространственными операциями.",
     "Spatial joins that would be painful in raw SQL become one method call here."),
    ("lib-shapely", "Shapely", "Погода и геоданные", "https://shapely.readthedocs.io/", "openSource", "geometry,spatial,python,gis", "pip install shapely",
     "Planar geometry operations in Python: intersections, buffers, unions.",
     "Операции планарной геометрии в Python: пересечения, буферы, объединения.",
     "It ignores the Earth's curvature — reproject to a suitable CRS before measuring real-world distances."),
    ("lib-rasterio", "Rasterio", "Погода и геоданные", "https://rasterio.readthedocs.io/", "openSource", "raster,geotiff,satellite,python", "pip install rasterio",
     "Reads and writes geospatial raster data like satellite imagery and elevation models.",
     "Чтение и запись геопространственных растровых данных: спутниковые снимки и модели рельефа.",
     "Read windows rather than whole files — satellite scenes are far too large to load into memory entirely."),
    ("lib-postgis", "PostGIS", "Погода и геоданные", "https://postgis.net/documentation/", "openSource", "postgres,spatial,gis,sql", "",
     "Spatial database extension adding geographic objects and queries to PostgreSQL.",
     "Расширение пространственной базы, добавляющее географические объекты и запросы в PostgreSQL.",
     "Create a spatial index (GIST) on geometry columns, or spatial queries scan the whole table."),
    ("lib-turf-js", "Turf.js", "Погода и геоданные", "https://turfjs.org/docs/", "openSource", "geospatial,javascript,geojson,analysis", "npm i @turf/turf",
     "Geospatial analysis for JavaScript operating on GeoJSON in the browser or Node.",
     "Геопространственный анализ на JavaScript поверх GeoJSON в браузере или Node.",
     "Doing spatial calculations client-side avoids a server round-trip for interactive map tools."),
    ("lib-h3", "H3", "Погода и геоданные", "https://h3geo.org/docs/", "openSource", "spatial-index,hexagons,uber,geospatial", "pip install h3",
     "Hexagonal hierarchical geospatial indexing system from Uber.",
     "Иерархическая гексагональная система геопространственной индексации от Uber.",
     "Hexagons have uniform neighbour distance, unlike square grids — that is why it suits proximity analysis."),
]
