# -*- coding: utf-8 -*-
"""Stage 5 library pack AW: NLP toolkits, topic modelling, PII redaction, data labelling platforms."""

LIBS_5AW = [
    # ---------- NLP инструментарий ----------
    ("lib-stanza", "Stanza", "NLP и обработка текста", "https://stanfordnlp.github.io/stanza/", "openSource", "stanford,multilingual,neural,linguistics", "pip install stanza",
     "Stanford's neural NLP pipeline covering many languages.",
     "Нейросетевой NLP-конвейер Stanford для множества языков.",
     "Its linguistic annotations are more accurate than spaCy's on lower-resource languages."),
    ("lib-flair", "Flair", "NLP и обработка текста", "https://flairnlp.github.io/docs/intro", "openSource", "embeddings,ner,sequence-labeling,pytorch", "pip install flair",
     "NLP framework with strong named entity recognition and sequence labelling.",
     "NLP-фреймворк с сильным распознаванием именованных сущностей и разметкой последовательностей.",
     "Its stacked embeddings often beat a single transformer on entity recognition tasks."),
    ("lib-polyglot", "Polyglot", "NLP и обработка текста", "https://polyglot.readthedocs.io/", "openSource", "multilingual,detection,transliteration,ner", "pip install polyglot",
     "Multilingual NLP toolkit covering more than a hundred languages.",
     "Многоязычный NLP-инструментарий, покрывающий более сотни языков.",
     "Its language coverage exceeds most modern toolkits, though maintenance has largely stopped."),
    ("lib-setfit", "SetFit", "NLP и обработка текста", "https://huggingface.co/docs/setfit", "openSource", "few-shot,classification,efficient,sentence-transformers", "pip install setfit",
     "Few-shot text classification that trains well on very small datasets.",
     "Few-shot классификация текста, обучающаяся на очень малых наборах данных.",
     "A few dozen labelled examples often match a fine-tuned model trained on thousands."),

    # ---------- Тематическое моделирование и ключевые слова ----------
    ("lib-bertopic", "BERTopic", "NLP и обработка текста", "https://maartengr.github.io/BERTopic/", "openSource", "topic-modeling,embeddings,clustering,interpretable", "pip install bertopic",
     "Topic modelling using transformer embeddings and clustering.",
     "Тематическое моделирование на эмбеддингах трансформеров и кластеризации.",
     "Its topics are far more coherent than classic LDA on short texts like reviews or tickets."),
    ("lib-top2vec", "Top2Vec", "NLP и обработка текста", "https://top2vec.readthedocs.io/", "openSource", "topic-modeling,embeddings,automatic,no-preprocessing", "pip install top2vec",
     "Topic modelling that discovers the number of topics automatically.",
     "Тематическое моделирование с автоматическим определением числа тем.",
     "Not having to guess the topic count in advance is its main practical advantage over LDA."),
    ("lib-keybert", "KeyBERT", "NLP и обработка текста", "https://maartengr.github.io/KeyBERT/", "openSource", "keywords,embeddings,extraction,simple", "pip install keybert",
     "Keyword extraction using BERT embeddings.",
     "Извлечение ключевых слов с использованием эмбеддингов BERT.",
     "Its keywords are semantically relevant rather than merely frequent, which statistical methods miss."),
    ("lib-yake", "YAKE", "NLP и обработка текста", "https://github.com/LIAAD/yake", "openSource", "keywords,unsupervised,statistical,lightweight", "pip install yake",
     "Unsupervised statistical keyword extraction with no training required.",
     "Неконтролируемое статистическое извлечение ключевых слов без обучения.",
     "It needs no model at all, which makes it viable where a transformer would be too heavy."),
    ("lib-rake-nltk", "RAKE", "NLP и обработка текста", "https://github.com/csurfer/rake-nltk", "openSource", "keywords,rapid,unsupervised,phrases", "pip install rake-nltk",
     "Rapid automatic keyword extraction using word co-occurrence.",
     "Быстрое автоматическое извлечение ключевых слов по совместной встречаемости слов.",
     "Very fast and language-independent, at noticeably lower quality than embedding methods."),
    ("lib-sumy", "sumy", "NLP и обработка текста", "https://github.com/miso-belica/sumy", "openSource", "summarization,extractive,classic,multilingual", "pip install sumy",
     "Extractive text summarization with several classic algorithms.",
     "Экстрактивная суммаризация текста несколькими классическими алгоритмами.",
     "Extractive summaries quote the source verbatim, which avoids the fabrication risk of generation."),
    ("lib-lexrank", "LexRank", "NLP и обработка текста", "https://github.com/crabcamp/lexrank", "openSource", "summarization,graph-based,extractive,unsupervised", "pip install lexrank",
     "Graph-based extractive summarization ranking sentences by centrality.",
     "Графовая экстрактивная суммаризация, ранжирующая предложения по центральности.",
     "Requires no training data, which suits domains where no summarization corpus exists."),

    # ---------- Конфиденциальность и качество данных ----------
    ("lib-presidio", "Presidio", "Безопасность и секреты", "https://microsoft.github.io/presidio/", "openSource", "pii,redaction,microsoft,anonymization", "pip install presidio-analyzer",
     "Microsoft's toolkit for detecting and anonymizing personal data in text and images.",
     "Набор инструментов Microsoft для обнаружения и анонимизации персональных данных в тексте и изображениях.",
     "Redacting personal data before it reaches an LLM is often what makes the use case legal at all."),
    ("lib-scrubadub", "scrubadub", "Безопасность и секреты", "https://scrubadub.readthedocs.io/", "openSource", "pii,cleaning,python,simple", "pip install scrubadub",
     "Removes personally identifiable information from free text.",
     "Удаляет персональные данные из свободного текста.",
     "Simpler than Presidio and correspondingly less thorough — verify recall on your own data."),
    ("lib-cleanlab", "Cleanlab", "AI-оценка и safety", "https://docs.cleanlab.ai/", "openSource", "label-errors,data-quality,confident-learning,detection", "pip install cleanlab",
     "Finds label errors and data quality problems in training sets.",
     "Находит ошибки разметки и проблемы качества данных в обучающих выборках.",
     "Mislabelled training data caps model accuracy in a way more training never fixes."),
    ("lib-snorkel", "Snorkel", "Данные и ML", "https://www.snorkel.org/get-started/", "openSource", "weak-supervision,labeling-functions,programmatic,stanford", "pip install snorkel",
     "Programmatic labelling through weak supervision rules.",
     "Программная разметка через правила слабого контроля.",
     "Writing labelling functions scales to datasets that manual annotation never could."),

    # ---------- Платформы разметки ----------
    ("lib-label-studio", "Label Studio", "Данные и ML", "https://labelstud.io/guide/", "openSource", "annotation,multi-modal,open-source,self-host", "pip install label-studio",
     "Open-source annotation tool covering text, image, audio and video.",
     "Открытый инструмент разметки для текста, изображений, аудио и видео.",
     "Its configurable label interface handles unusual annotation schemas that fixed tools cannot."),
    ("lib-prodigy", "Prodigy", "Данные и ML", "https://prodi.gy/docs", "paid", "annotation,active-learning,scriptable,explosion", "",
     "Scriptable annotation tool with active learning, from the spaCy team.",
     "Скриптуемый инструмент разметки с активным обучением от команды spaCy.",
     "Active learning surfaces the examples the model is least sure about, which cuts labelling volume."),
    ("lib-argilla", "Argilla", "Данные и ML", "https://docs.argilla.io/", "openSource", "llm-data,feedback,annotation,huggingface", "pip install argilla",
     "Collaboration platform for building and curating LLM datasets.",
     "Платформа совместной работы для построения и курирования датасетов LLM.",
     "It is built around human feedback collection, which generic annotation tools handle awkwardly."),
    ("lib-doccano", "doccano", "Данные и ML", "https://doccano.github.io/doccano/", "openSource", "text-annotation,self-host,simple,collaborative", "pip install doccano",
     "Open-source text annotation tool for classification and sequence labelling.",
     "Открытый инструмент разметки текста для классификации и разметки последовательностей.",
     "Lightweight enough to stand up for a one-off labelling project without much setup."),
    ("lib-cvat", "CVAT", "Компьютерное зрение", "https://docs.cvat.ai/", "openSource", "video,image,annotation,computer-vision", "",
     "Computer vision annotation tool with strong video labelling support.",
     "Инструмент разметки для компьютерного зрения с сильной поддержкой видео.",
     "Its interpolation between keyframes makes video annotation far faster than frame-by-frame work."),
    ("lib-fiftyone", "FiftyOne", "Компьютерное зрение", "https://docs.voxel51.com/", "openSource", "datasets,visualization,curation,evaluation", "pip install fiftyone",
     "Tool for visualizing, curating and evaluating computer vision datasets.",
     "Инструмент визуализации, курирования и оценки датасетов компьютерного зрения.",
     "Looking at your data properly finds more model problems than another round of hyperparameter tuning."),
    ("lib-supervisely", "Supervisely", "Компьютерное зрение", "https://docs.supervisely.com/", "freeTier", "annotation,platform,apps,computer-vision", "",
     "Computer vision platform combining annotation, training and deployment.",
     "Платформа компьютерного зрения, объединяющая разметку, обучение и развёртывание.",
     "Its app ecosystem covers the whole pipeline, which suits teams without ML infrastructure."),
    ("lib-encord", "Encord", "Компьютерное зрение", "https://docs.encord.com/", "paid", "annotation,active-learning,enterprise,multimodal", "",
     "Enterprise data platform for annotating and curating training data.",
     "Корпоративная платформа данных для разметки и курирования обучающих выборок.",
     "Its quality control workflows matter when annotation is outsourced to a large team."),
    ("lib-labelbox", "Labelbox", "Данные и ML", "https://docs.labelbox.com/", "freeTier", "annotation,enterprise,workforce,quality", "",
     "Data labelling platform with workforce management and quality review.",
     "Платформа разметки данных с управлением исполнителями и контролем качества.",
     "Its review workflows catch the annotator drift that silently degrades a large dataset."),
    ("lib-v7-darwin", "V7", "Компьютерное зрение", "https://docs.v7labs.com/", "paid", "annotation,automation,medical,video", "",
     "Annotation platform with automated labelling, strong in medical imaging.",
     "Платформа разметки с автоматизацией, сильна в медицинской визуализации.",
     "Its medical imaging support handles DICOM natively, which general tools do not."),
    ("lib-kili-technology", "Kili Technology", "Данные и ML", "https://docs.kili-technology.com/", "paid", "annotation,quality,llm,enterprise", "",
     "Data labelling platform focused on quality metrics and LLM datasets.",
     "Платформа разметки данных с фокусом на метрики качества и датасеты LLM.",
     "Its inter-annotator agreement metrics quantify label reliability rather than assuming it."),
    ("lib-superannotate", "SuperAnnotate", "Данные и ML", "https://doc.superannotate.com/", "paid", "annotation,multimodal,marketplace,automation", "",
     "Annotation platform with an integrated marketplace of annotation teams.",
     "Платформа разметки со встроенным маркетплейсом команд разметчиков.",
     "Sourcing annotators through the same platform removes a separate vendor relationship."),
    ("lib-scale-ai", "Scale AI", "Данные и ML", "https://docs.scale.com/", "paid", "labeling,rlhf,enterprise,managed", "",
     "Managed data labelling service, including human feedback for model training.",
     "Управляемая служба разметки данных, включая обратную связь людей для обучения моделей.",
     "It is a service rather than a tool — you send data and receive labels, with no platform to run."),
    ("lib-surge-ai", "Surge AI", "Данные и ML", "https://app.surgehq.ai/docs", "paid", "rlhf,human-data,quality,api", "",
     "Human data platform for high-quality annotation and model feedback.",
     "Платформа данных от людей для качественной разметки и обратной связи для моделей.",
     "It pays annotators well, which shows in the quality on nuanced judgement tasks."),
    ("lib-toloka", "Toloka", "Данные и ML", "https://toloka.ai/docs/", "paid", "crowdsourcing,annotation,global,api", "",
     "Crowdsourcing platform for data labelling at scale.",
     "Краудсорсинговая платформа разметки данных в больших объёмах.",
     "Crowdsourced labels need aggregation across annotators — a single response is rarely reliable."),
    ("lib-mturk", "Amazon Mechanical Turk", "Данные и ML", "https://docs.aws.amazon.com/mturk/", "paid", "crowdsourcing,aws,microtasks,api", "",
     "The original crowdsourcing marketplace for human microtasks.",
     "Первый краудсорсинговый маркетплейс микрозадач для людей.",
     "Quality depends entirely on how carefully you design qualification and review steps."),
]
