# -*- coding: utf-8 -*-
"""Stage 5 API pack B: finance/fintech, robotics-adjacent APIs, health, more geodata,
data engineering services, message queues, communication, more dev-services."""

APIS_5B = [
    # ---------- Финансы (deepen existing category) ----------
    ("api-plaid", "Plaid", "Финансы", "https://plaid.com/docs/", "mixed", "banking,fintech,accounts,transactions", "",
     "Bank account linking, balances and transaction history for fintech apps.",
     "Подключение банковских счетов, балансы и история транзакций для fintech-приложений.",
     "Sandbox mode simulates real banks with test credentials — build the whole flow before any live key."),
    ("api-stripe-treasury", "Stripe Treasury", "Финансы", "https://docs.stripe.com/treasury", "paid", "banking,fintech,accounts,embedded", "",
     "Embedded banking: financial accounts, money movement, cards, built on Stripe.",
     "Встроенный банкинг: финансовые счета, движение денег, карты — на базе Stripe.",
     "This requires a partnership approval from Stripe before production access, unlike most Stripe products."),
    ("api-wise-platform", "Wise Platform", "Финансы", "https://docs.wise.com/", "mixed", "payments,international,fx,transfers", "",
     "International money transfer and multi-currency account API.",
     "API международных переводов и мультивалютных счетов.",
     "Quote the FX rate right before executing a transfer — rates are only guaranteed briefly."),
    ("api-mono-africa", "Mono", "Финансы", "https://docs.mono.co/", "mixed", "banking,africa,fintech,accounts", "",
     "Bank account linking and transaction data for African fintech products.",
     "Подключение банковских счетов и транзакционные данные для африканских fintech-продуктов.",
     "Coverage is strongest in Nigeria and Kenya — check bank support before assuming pan-African reach."),
    ("api-truelayer", "TrueLayer", "Финансы", "https://docs.truelayer.com/", "mixed", "open-banking,europe,payments,accounts", "",
     "Open Banking API for account data and payments across UK and European banks.",
     "API Open Banking для доступа к счетам и платежам в банках Великобритании и Европы.",
     "Payments initiation and data access are separate products with separate approval processes."),
    ("api-yodlee", "Yodlee", "Финансы", "https://developer.yodlee.com/", "paid", "banking,aggregation,fintech,enterprise", "",
     "Long-standing financial data aggregation platform, an alternative to Plaid at enterprise scale.",
     "Давно существующая платформа агрегации финансовых данных, альтернатива Plaid для крупного масштаба.",
     "Onboarding is heavier than Plaid's — budget real integration time, not a weekend prototype."),
    ("api-marqeta", "Marqeta", "Финансы", "https://www.marqeta.com/docs", "paid", "cards,issuing,fintech,payments", "",
     "Card issuing platform: create, control and process virtual and physical cards.",
     "Платформа выпуска карт: создание, контроль и обработка виртуальных и физических карт.",
     "Just-in-time funding lets you approve each transaction in real time instead of pre-funding balances."),

    # ---------- Данные и ML (deepen) / Data engineering ----------
    ("api-fivetran", "Fivetran", "Data engineering", "https://fivetran.com/docs", "mixed", "etl,connectors,data-pipeline,managed", "",
     "Managed ELT connectors that sync data from hundreds of sources into a warehouse.",
     "Управляемые ELT-коннекторы, синхронизирующие данные из сотен источников в хранилище.",
     "Row-based pricing means a poorly filtered sync can get expensive fast — scope tables deliberately."),
    ("api-airbyte", "Airbyte", "Data engineering", "https://docs.airbyte.com/", "openSource", "etl,connectors,open-source,self-host", "",
     "Open-source data integration with hundreds of community connectors, self-hostable.",
     "Открытая интеграция данных с сотнями коннекторов сообщества, можно разместить самостоятельно.",
     "Self-host to avoid per-row pricing entirely — the OSS version has no artificial connector limits."),
    ("api-hightouch", "Hightouch", "Data engineering", "https://hightouch.com/docs", "mixed", "reverse-etl,data-pipeline,warehouse,sync", "",
     "Reverse ETL: syncs warehouse tables out to SaaS tools like Salesforce or HubSpot.",
     "Reverse ETL: синхронизирует таблицы хранилища в SaaS-инструменты вроде Salesforce или HubSpot.",
     "Model the sync as a SQL view first — Hightouch just keeps that view in sync with the destination."),
    ("api-census", "Census", "Data engineering", "https://docs.getcensus.com/", "mixed", "reverse-etl,warehouse,sync,operational", "",
     "Reverse ETL platform syncing warehouse data into operational business tools.",
     "Платформа reverse ETL, синхронизирующая данные хранилища в операционные бизнес-инструменты.",
     "Sync keys matter: pick a stable warehouse column as the match key, not something that can change."),
    # ---------- Message queues и брокеры ----------
    ("api-kafka", "Apache Kafka", "Message queues и брокеры", "https://kafka.apache.org/documentation/", "openSource", "streaming,events,broker,distributed", "",
     "Distributed event streaming platform, the de facto standard for high-throughput pipelines.",
     "Распределённая платформа событийного стриминга, фактический стандарт для высоконагруженных пайплайнов.",
     "Partition count is a one-way door in most setups — plan for your eventual scale, not just today's."),
    ("api-confluent-cloud", "Confluent Cloud", "Message queues и брокеры", "https://docs.confluent.io/cloud/current/overview.html", "freeTier", "kafka,managed,streaming,cloud", "",
     "Fully managed Kafka with a free tier, from Kafka's original creators.",
     "Полностью управляемый Kafka с бесплатным тарифом от создателей Kafka.",
     "The free tier's monthly credit is enough to run a real small pipeline, not just a toy topic."),
    ("api-rabbitmq", "RabbitMQ", "Message queues и брокеры", "https://www.rabbitmq.com/docs", "openSource", "queue,amqp,broker,self-host", "",
     "General-purpose message broker supporting AMQP, MQTT and STOMP.",
     "Универсальный брокер сообщений с поддержкой AMQP, MQTT и STOMP.",
     "Use quorum queues over classic mirrored queues in new deployments — they handle failover more reliably."),
    ("api-nats", "NATS", "Message queues и брокеры", "https://docs.nats.io/", "openSource", "messaging,lightweight,go,pubsub", "",
     "Lightweight, high-performance messaging system with optional persistence via JetStream.",
     "Лёгкая высокопроизводительная система обмена сообщениями с опциональной персистентностью через JetStream.",
     "Start with core NATS pub/sub; add JetStream only once you actually need message replay or durability."),
    ("api-aws-sqs", "Amazon SQS", "Message queues и брокеры", "https://docs.aws.amazon.com/sqs/", "mixed", "queue,aws,managed,serverless", "",
     "Fully managed message queue, the default choice inside AWS-based architectures.",
     "Полностью управляемая очередь сообщений, стандартный выбор в AWS-архитектурах.",
     "FIFO queues cost more and throughput less — use standard queues unless strict ordering is required."),
    ("api-pulsar", "Apache Pulsar", "Message queues и брокеры", "https://pulsar.apache.org/docs/", "openSource", "streaming,multi-tenant,broker,distributed", "",
     "Distributed pub-sub messaging with built-in multi-tenancy and tiered storage.",
     "Распределённый pub-sub с встроенной multi-tenancy и многоуровневым хранением.",
     "Consider it over Kafka when you need real multi-tenant isolation between teams on one cluster."),

    # ---------- Здоровье и медицина (deepen) ----------
    ("api-fhir", "FHIR (HL7)", "Здоровье и медицина", "https://www.hl7.org/fhir/", "free", "healthcare,standard,interop,ehr", "",
     "The open standard for exchanging healthcare data between systems.",
     "Открытый стандарт обмена медицинскими данными между системами.",
     "Test against a public FHIR sandbox server before touching a real EHR integration."),
    ("api-epic-fhir", "Epic on FHIR", "Здоровье и медицина", "https://fhir.epic.com/", "mixed", "healthcare,ehr,fhir,epic", "",
     "FHIR-based API access to Epic electronic health record systems.",
     "FHIR-доступ к системам электронных медицинских карт Epic.",
     "The open sandbox with synthetic patients is the right place to build before any real hospital contract."),
    ("api-redox", "Redox", "Здоровье и медицина", "https://developer.redoxengine.com/", "paid", "healthcare,interop,ehr,integration", "",
     "Healthcare integration engine normalizing data across many EHR systems into one API.",
     "Движок интеграции здравоохранения, нормализующий данные разных EHR в один API.",
     "One integration replaces separate work per hospital EHR vendor — the whole value is that abstraction."),
    ("api-infermedica", "Infermedica", "Здоровье и медицина", "https://developer.infermedica.com/", "freeTier", "symptom-checker,triage,medical,ai", "",
     "Symptom-checking and triage API built on a clinically validated medical knowledge base.",
     "API проверки симптомов и триажа на клинически проверенной медицинской базе знаний.",
     "This assists triage, it does not diagnose — the API's own terms require that framing in your UI."),

    # ---------- Погода и геоданные (deepen) ----------
    ("api-tomorrow-io", "Tomorrow.io", "Погода и геоданные", "https://docs.tomorrow.io/", "freeTier", "weather,forecast,climate,api", "",
     "Hyperlocal weather forecasting API with a real free tier for developers.",
     "API гиперлокального прогноза погоды с реальным бесплатным тарифом для разработчиков.",
     "The free tier's 500 calls/day is enough for a weather widget without a backend cache."),
    ("api-visual-crossing", "Visual Crossing Weather", "Погода и геоданные", "https://www.visualcrossing.com/weather-api", "freeTier", "weather,historical,forecast,api", "",
     "Historical and forecast weather data with a simple CSV/JSON API.",
     "Исторические данные и прогноз погоды с простым CSV/JSON API.",
     "Historical data goes back decades in one request — useful for climate-correlation analysis."),
    ("api-here-geocoding", "HERE Geocoding & Search", "Погода и геоданные", "https://www.here.com/docs/bundle/geocoding-and-search-api-developer-guide/", "freeTier", "geocoding,maps,search,here", "",
     "Geocoding, reverse geocoding and place search from HERE's mapping platform.",
     "Геокодирование, обратное геокодирование и поиск мест от картографической платформы HERE.",
     "The free tier's 250k transactions/month is generous enough for most non-enterprise apps."),
    ("api-geocodio", "Geocodio", "Погода и геоданные", "https://www.geocod.io/docs/", "freeTier", "geocoding,us-focused,batch,address", "",
     "US and Canada-focused geocoding with strong batch-processing support.",
     "Геокодирование с фокусом на США и Канаду с сильной поддержкой пакетной обработки.",
     "Batch geocoding via CSV upload is dramatically cheaper per-address than the single-lookup endpoint."),

    # ---------- Космос и наука (deepen) ----------
    ("api-n2yo", "N2YO", "Космос и наука", "https://www.n2yo.com/api/", "freeTier", "satellites,tracking,space,tle", "",
     "Real-time satellite tracking and pass predictions from orbital element data.",
     "Отслеживание спутников в реальном времени и прогноз пролётов по орбитальным элементам.",
     "Free tier rate limits are strict — cache TLE data locally rather than refetching per request."),
    ("api-launch-library", "Launch Library 2", "Космос и наука", "https://thespacedevs.com/llapi", "free", "space,launches,rockets,schedule", "",
     "Upcoming and historical rocket launch schedules across every space agency and company.",
     "Расписание предстоящих и прошедших запусков ракет всех космических агентств и компаний.",
     "Cache aggressively — the free tier's rate limit is tight relative to how often launch data actually changes."),

    # ---------- Логистика и доставка (deepen) ----------
    ("api-aftership", "AfterShip", "Логистика и доставка", "https://developers.aftership.com/", "freeTier", "tracking,shipping,notifications,ecommerce", "",
     "Shipment tracking across 1,100+ carriers with branded tracking pages.",
     "Трекинг посылок у 1100+ перевозчиков с брендированными страницами отслеживания.",
     "The free tier's 100 shipments/month is a fast way to validate the integration before paying."),
    ("api-fedex-web-services", "FedEx Web Services", "Логистика и доставка", "https://developer.fedex.com/", "mixed", "shipping,fedex,rates,tracking", "",
     "Direct FedEx integration for rating, shipping and tracking, without a middleman aggregator.",
     "Прямая интеграция с FedEx для тарификации, отправки и трекинга без посредника-агрегатора.",
     "Direct carrier integration only pays off at real volume — an aggregator like EasyPost is faster to ship for most apps."),
    ("api-ups-developer", "UPS Developer Kit", "Логистика и доставка", "https://developer.ups.com/", "mixed", "shipping,ups,rates,tracking", "",
     "Direct UPS API access for rating, label generation and package tracking.",
     "Прямой доступ к API UPS для тарификации, генерации этикеток и трекинга посылок.",
     "OAuth2 replaced the older access-key auth — use the current guide, older tutorials are stale."),

    # ---------- Коммуникации (deepen) ----------
    ("api-vonage", "Vonage Communications APIs", "Коммуникации", "https://developer.vonage.com/en/documentation", "mixed", "sms,voice,video,messaging", "",
     "SMS, voice, video and verification APIs, a Twilio alternative with broader carrier reach in some regions.",
     "API SMS, голоса, видео и верификации — альтернатива Twilio с более широким покрытием операторов в некоторых регионах.",
     "Compare per-country SMS pricing against Twilio directly — the cheaper option varies a lot by destination."),
    ("api-messagebird", "MessageBird (Bird)", "Коммуникации", "https://docs.bird.com/", "mixed", "sms,whatsapp,omnichannel,messaging", "",
     "Omnichannel messaging API covering SMS, WhatsApp, email and voice from one platform.",
     "Омниканальный API сообщений: SMS, WhatsApp, email и голос с одной платформы.",
     "The WhatsApp Business integration needs Meta template approval — budget days, not hours, for that step."),
    ("api-sinch", "Sinch", "Коммуникации", "https://developers.sinch.com/docs/", "mixed", "sms,voice,verification,messaging", "",
     "Global SMS, voice and verification APIs with strong carrier-direct coverage.",
     "Глобальные API SMS, голоса и верификации с сильным прямым покрытием операторов.",
     "Verification API handles the retry/fallback logic for OTP delivery so you don't have to build it."),
    ("api-signalwire", "SignalWire", "Коммуникации", "https://developer.signalwire.com/", "mixed", "voice,sms,webrtc,twilio-compatible", "",
     "Twilio-API-compatible voice, SMS and video, often priced lower for the same call patterns.",
     "Голос, SMS и видео с API, совместимым с Twilio, зачастую дешевле при тех же паттернах вызовов.",
     "The Twilio-compatible SDK means migrating existing Twilio code is often a base-URL and key swap."),

    # ---------- Рекомендательные системы ----------
    ("api-recombee", "Recombee", "Рекомендательные системы", "https://docs.recombee.com/", "freeTier", "recommendations,api,personalization,managed", "",
     "Managed recommendation engine API: send interactions, get personalized results back.",
     "Управляемый API рекомендательной системы: отправляешь взаимодействия, получаешь персонализированные результаты.",
     "Send interaction events as they happen — recommendation quality depends directly on event freshness."),

    # ---------- Финансы: рынки и данные (deepen) ----------
    ("api-polygon-io", "Polygon.io", "Финансы", "https://polygon.io/docs", "freeTier", "stocks,market-data,realtime,options", "",
     "Real-time and historical market data for stocks, options, forex and crypto.",
     "Рыночные данные в реальном времени и исторические по акциям, опционам, форекс и крипто.",
     "The free tier is delayed by 15 minutes — check that against your use case before assuming real-time."),
    ("api-iex-cloud", "IEX Cloud", "Финансы", "https://iexcloud.io/docs/", "freeTier", "stocks,market-data,api,finance", "",
     "Financial market data API with a credit-based free tier for stocks and fundamentals.",
     "API финансовых рыночных данных с кредитным бесплатным тарифом для акций и фундаментальных данных.",
     "Credits deplete per field requested — request only the fields you actually use to stretch the free tier."),
    ("api-twelvedata", "Twelve Data", "Финансы", "https://twelvedata.com/docs", "freeTier", "stocks,forex,crypto,market-data", "",
     "Stocks, forex, crypto and ETF data with a WebSocket feed for real-time prices.",
     "Данные по акциям, форекс, крипто и ETF с WebSocket-потоком цен в реальном времени.",
     "The WebSocket plan is a separate tier from the REST API — check both before committing to one."),
]
