# -*- coding: utf-8 -*-
"""Stage 5 API pack S: audio/music generation, 3D/AR, creative tools, misc media."""

APIS_5S = [
    # ---------- Аудио и голос: generation ----------
    ("api-suno", "Suno", "Аудио и голос", "https://suno.com/", "mixed", "music-generation,ai,audio,songs", "",
     "AI music generation producing full songs with vocals from a text prompt.",
     "Генерация музыки ИИ: полноценные песни с вокалом по текстовому промпту.",
     "Check the commercial-use terms for your plan tier before using generated music in a product."),
    ("api-udio", "Udio", "Аудио и голос", "https://www.udio.com/", "mixed", "music-generation,ai,audio,creative", "",
     "AI music creation platform with extension and remixing of generated tracks.",
     "Платформа создания музыки ИИ с расширением и ремиксом сгенерированных треков.",
     "Licensing for generated audio is still an evolving area — verify terms before commercial release."),
    ("api-stability-audio", "Stability AI Audio", "Аудио и голос", "https://platform.stability.ai/docs/api-reference", "mixed", "audio-generation,sound-effects,music,stability", "",
     "Sound effect and music generation from Stability AI's audio models.",
     "Генерация звуковых эффектов и музыки моделями аудио от Stability AI.",
     "Better suited to sound effects and loops than full songs — different tool from Suno or Udio."),
    ("api-playht", "PlayAI (Play.ht)", "Аудио и голос", "https://docs.play.ai/", "freeTier", "tts,voice-cloning,audio,realtime", "",
     "Text-to-speech and voice cloning with low-latency streaming.",
     "Синтез речи и клонирование голоса с потоковой передачей и низкой задержкой.",
     "Voice cloning requires consent from the voice owner — most providers require you to attest to this."),
    ("api-speechify", "Speechify API", "Аудио и голос", "https://docs.sws.speechify.com/", "freeTier", "tts,accessibility,reading,voices", "",
     "Text-to-speech aimed at reading long-form content aloud.",
     "Синтез речи для озвучивания длинных текстов.",
     "Its voices are tuned for sustained listening rather than short prompts, which suits article narration."),
    ("api-lalal-ai", "LALAL.AI", "Аудио и голос", "https://www.lalal.ai/api/help/", "paid", "stem-separation,audio,vocals,music", "",
     "Audio stem separation splitting tracks into vocals, drums, bass and other parts.",
     "Разделение аудио на стемы: вокал, барабаны, бас и другие части.",
     "Quality varies by source material — dense mixes separate noticeably worse than sparse ones."),

    # ---------- Анимация и 3D: services ----------
    ("api-meshy", "Meshy", "Анимация и 3D", "https://docs.meshy.ai/", "freeTier", "3d-generation,ai,models,texturing", "",
     "AI 3D model generation from text prompts or reference images.",
     "Генерация 3D-моделей ИИ по текстовым промптам или референсным изображениям.",
     "Generated topology is rarely production-ready for animation — plan for retopology if you need to rig it."),
    ("api-luma-genie", "Luma Genie", "Анимация и 3D", "https://lumalabs.ai/genie", "freeTier", "3d-generation,ai,text-to-3d,models", "",
     "Text-to-3D model generation from Luma Labs.",
     "Генерация 3D-моделей из текста от Luma Labs.",
     "Useful for rapid concept iteration; hand-modelling still wins for final production assets."),
    ("api-sketchfab", "Sketchfab API", "Анимация и 3D", "https://sketchfab.com/developers", "freeTier", "3d,models,marketplace,viewer", "",
     "3D model hosting, search and an embeddable web viewer.",
     "Хостинг 3D-моделей, поиск и встраиваемый веб-просмотрщик.",
     "Its embed viewer handles format conversion and LOD automatically, saving a lot of WebGL work."),
    ("api-polyhaven", "Poly Haven", "Анимация и 3D", "https://redocly.github.io/redoc/?url=https://api.polyhaven.com/api-docs.json", "noKey", "3d,textures,hdri,cc0", "",
     "Free CC0 HDRIs, textures and 3D models with a public API, no key required.",
     "Бесплатные CC0 HDRI, текстуры и 3D-модели с публичным API, без ключа.",
     "Everything is CC0, so there are no attribution requirements even in commercial work."),
    ("api-8thwall", "8th Wall", "Анимация и 3D", "https://www.8thwall.com/docs", "paid", "webar,ar,browser,niantic", "",
     "WebAR platform delivering augmented reality through a browser, no app install.",
     "WebAR-платформа, доставляющая дополненную реальность через браузер без установки приложения.",
     "No app install is the entire value proposition — compare against native ARKit/ARCore on that basis."),

    # ---------- Изображения и дизайн: creative ----------
    ("api-photoroom", "PhotoRoom", "Изображения и дизайн", "https://www.photoroom.com/api", "freeTier", "background-removal,ecommerce,images,editing", "",
     "Background removal and product photo editing tuned for ecommerce catalogs.",
     "Удаление фона и редактирование фото товаров, заточено под ecommerce-каталоги.",
     "Its product-photo templates handle shadows and reflections better than generic background removal."),
    ("api-clipdrop", "ClipDrop", "Изображения и дизайн", "https://clipdrop.co/apis/docs", "freeTier", "image-editing,upscale,cleanup,stability", "",
     "Image editing APIs: background removal, cleanup, upscaling and relighting.",
     "API редактирования изображений: удаление фона, очистка, апскейл и перерасчёт освещения.",
     "The cleanup endpoint removes unwanted objects, which is often more useful than full regeneration."),
    ("api-vectorizer-ai", "Vectorizer.AI", "Изображения и дизайн", "https://vectorizer.ai/api", "paid", "vectorization,svg,raster-to-vector,tracing", "",
     "Converts raster images into clean vector SVG artwork.",
     "Преобразует растровые изображения в чистую векторную SVG-графику.",
     "Results are far better on flat graphics and logos than on photographs, which vectorize poorly by nature."),
    ("api-pixelcut", "Pixelcut API", "Изображения и дизайн", "https://www.pixelcut.ai/api", "freeTier", "background-removal,upscale,images,ecommerce", "",
     "Background removal, upscaling and product photo generation.",
     "Удаление фона, апскейл и генерация фото товаров.",
     "Compare output against PhotoRoom on your own product images — quality differs noticeably by category."),

    # ---------- Видео и медиа (deepen) ----------
    ("api-shotstack", "Shotstack", "Видео и медиа", "https://shotstack.io/docs/", "freeTier", "video-editing,api,rendering,automation", "",
     "Programmatic video editing and rendering from a JSON timeline description.",
     "Программное редактирование и рендеринг видео из JSON-описания таймлайна.",
     "Describing edits as JSON makes automated, templated video generation genuinely practical."),
    ("api-creatomate", "Creatomate", "Видео и медиа", "https://creatomate.com/docs", "freeTier", "video,automation,templates,rendering", "",
     "Template-based video and image generation for automated content production.",
     "Генерация видео и изображений по шаблонам для автоматизированного производства контента.",
     "Design the template once in their editor, then vary it per-render with data — much like Bannerbear for video."),
    ("api-assemblyai-lemur", "AssemblyAI LeMUR", "Аудио и голос", "https://www.assemblyai.com/docs/lemur", "freeTier", "audio,llm,summarization,qa", "",
     "Applies an LLM directly to audio transcripts for summarization and question answering.",
     "Применяет LLM прямо к транскриптам аудио для суммаризации и ответов на вопросы.",
     "Avoids wiring transcription and an LLM together yourself when the task is purely transcript analysis."),
]
