# -*- coding: utf-8 -*-
"""Stage 5 MCP + skills pack B."""

MCPS_5B = [
    ("mcp-figma-community", "Figma Context MCP (community)", "Инфраструктура MCP", "https://github.com/GLips/Figma-Context-MCP", "openSource", "figma,design,community,layout", "npx figma-developer-mcp",
     "Community server that extracts layout and styling data from Figma files for code generation.",
     "Сервер сообщества, извлекающий данные о layout и стилях из файлов Figma для генерации кода.",
     "Works with any Figma file via a personal access token, unlike the official server's Dev Mode requirement."),
    ("mcp-postgres-community", "Postgres MCP Pro", "Инфраструктура MCP", "https://github.com/crystaldba/postgres-mcp", "openSource", "postgres,database,query-planning,community", "pipx install postgres-mcp",
     "Query execution plus index tuning and query-plan analysis for Postgres.",
     "Выполнение запросов плюс подбор индексов и анализ планов выполнения для Postgres.",
     "The index-advisor tool catches missing indexes an agent would otherwise never think to suggest."),
    ("mcp-firecrawl-2", "Firecrawl MCP", "Инфраструктура MCP", "https://github.com/mendableai/firecrawl-mcp-server", "freeTier", "scraping,crawl,markdown,official", "npx -y firecrawl-mcp",
     "Official Firecrawl server: crawl a site and get clean markdown back as agent tool results.",
     "Официальный сервер Firecrawl: обход сайта с возвратом чистого markdown как результата инструмента.",
     "The scrape tool for a single page is much cheaper than crawl for the whole site — pick per task."),
    ("mcp-webflow-official", "Webflow MCP (official)", "Инфраструктура MCP", "https://developers.webflow.com/data/docs/ai-tools", "freeTier", "webflow,cms,official,pages", "",
     "Official server for managing Webflow CMS collections and site content.",
     "Официальный сервер для управления CMS-коллекциями и контентом сайта Webflow.",
     "Publish changes explicitly — edits to CMS items stay in draft until you call the publish tool."),
    ("mcp-asana-official", "Asana MCP (official)", "Инфраструктура MCP", "https://developers.asana.com/docs/using-the-asana-mcp-server", "freeTier", "asana,tasks,official,project-management", "",
     "Official server for Asana tasks, projects and workspaces.",
     "Официальный сервер для задач, проектов и рабочих пространств Asana.",
     "Scope the personal access token to one workspace if the agent should not see every project you're in."),
    ("mcp-monday-official", "monday.com MCP (official)", "Инфраструктура MCP", "https://developer.monday.com/apps/docs/mcp", "freeTier", "monday,project-management,official,boards", "",
     "Official server exposing monday.com boards, items and updates as agent tools.",
     "Официальный сервер, отдающий доски, элементы и обновления monday.com как инструменты агента.",
     "Board column types vary per board — fetch the board schema before writing values to a new board."),
    ("mcp-elevenlabs-official", "ElevenLabs MCP (official)", "Инфраструктура MCP", "https://elevenlabs.io/docs/product-guides/administration/mcp", "freeTier", "elevenlabs,tts,voice,official", "uvx elevenlabs-mcp",
     "Official server for text-to-speech and voice cloning from an agent.",
     "Официальный сервер для синтеза речи и клонирования голоса из агента.",
     "Generated audio is saved locally by the server, so the agent can reference the file path afterward."),
    ("mcp-paypal-official", "PayPal MCP (official)", "Платежи и commerce", "https://developer.paypal.com/tools/mcp-server/", "freeTier", "paypal,payments,official,invoices", "",
     "Official server for PayPal invoices, orders and transaction lookups.",
     "Официальный сервер для счетов, заказов и поиска транзакций PayPal.",
     "Use sandbox credentials while building — this server moves real money once switched to live mode."),
    ("mcp-square-official", "Square MCP (official)", "Платежи и commerce", "https://developer.squareup.com/docs/mcp", "freeTier", "square,payments,official,pos", "",
     "Official server for Square payments, catalog and order management.",
     "Официальный сервер для платежей, каталога и заказов Square.",
     "The sandbox environment mirrors production closely enough to fully test a checkout flow safely."),
    ("mcp-close-official", "Close MCP (official)", "CRM и продажи", "https://developer.close.com/topics/mcp/", "freeTier", "close,crm,official,sales", "",
     "Official server for Close CRM leads, contacts and activities.",
     "Официальный сервер для лидов, контактов и активностей Close CRM.",
     "Let the agent log a call summary as an activity directly instead of pasting notes manually."),
    ("mcp-intercom-official", "Intercom MCP (official)", "Коммуникации", "https://developers.intercom.com/docs/guides/mcp", "freeTier", "intercom,support,official,conversations", "",
     "Official server for Intercom conversations, contacts and help center content.",
     "Официальный сервер для разговоров, контактов и базы знаний Intercom.",
     "Search the help center content through the agent before drafting a new answer — it may already exist."),
    ("mcp-zendesk-community", "Zendesk MCP (community)", "Коммуникации", "https://github.com/reminia/zendesk-mcp-server", "openSource", "zendesk,support,tickets,community", "",
     "Community server for reading and updating Zendesk support tickets.",
     "Сервер сообщества для чтения и обновления тикетов поддержки Zendesk.",
     "Start read-only while evaluating — write access lets an agent close or reassign real customer tickets."),
    ("mcp-posthog-official", "PostHog MCP (official)", "Мониторинг и аналитика", "https://posthog.com/docs/model-context-protocol", "freeTier", "posthog,analytics,official,feature-flags", "",
     "Official server for PostHog analytics queries, feature flags and insights.",
     "Официальный сервер для аналитических запросов, feature-флагов и инсайтов PostHog.",
     "Ask the agent to create a feature flag directly instead of clicking through the dashboard for a quick toggle."),
    ("mcp-sentry-official-2", "Sentry MCP (official, hosted)", "Мониторинг и аналитика", "https://docs.sentry.io/product/sentry-mcp/", "freeTier", "sentry,errors,official,remote", "",
     "Official hosted remote server for Sentry issues, releases and performance data.",
     "Официальный размещённый удалённый сервер для issues, релизов и данных производительности Sentry.",
     "The hosted remote server needs no local install — connect via OAuth directly from a compatible client."),
    ("mcp-railway-community", "Railway MCP (community)", "Облако и деплой", "https://github.com/jasontanswe/railway-mcp", "openSource", "railway,deploy,community,services", "",
     "Community server for managing Railway projects, services and deployments.",
     "Сервер сообщества для управления проектами, сервисами и деплоями Railway.",
     "Check the token's project scope before granting an agent deploy access to anything beyond a sandbox."),
]

SKILLS_5B = [
    ("skill-claude-code-output-styles", "Claude Code Output Styles", "Установка и миграция", "https://docs.claude.com/en/docs/claude-code/output-styles", "free", "claude-code,customization,prompts,tone", "",
     "Customize Claude Code's default system prompt and response style for a project.",
     "Настройка системного промпта по умолчанию и стиля ответов Claude Code для проекта.",
     "Use this instead of repeating tone instructions in every prompt — set it once per project."),
    ("skill-claude-code-checkpoints", "Claude Code Checkpoints", "Гайды и практики", "https://docs.claude.com/en/docs/claude-code/checkpointing", "free", "claude-code,undo,safety,snapshots", "",
     "Automatic snapshots of file state that let you rewind an agent session that went wrong.",
     "Автоматические снимки состояния файлов, позволяющие откатить сессию агента, пошедшую не так.",
     "Rely on this instead of manual git stashing mid-session — it is built for exactly that recovery case."),
    ("skill-claude-code-hooks-reference", "Claude Code Hooks Reference", "Гайды и практики", "https://docs.claude.com/en/docs/claude-code/hooks-guide", "free", "claude-code,hooks,automation,events", "",
     "Practical patterns for PreToolUse, PostToolUse and other hook events.",
     "Практические паттерны для событий PreToolUse, PostToolUse и других хуков.",
     "A PreToolUse hook that blocks a dangerous command is more reliable than hoping the model refuses on its own."),
    ("skill-claude-code-ide-integrations", "Claude Code IDE Integrations", "Установка и миграция", "https://docs.claude.com/en/docs/claude-code/ide-integrations", "free", "claude-code,vscode,jetbrains,ide", "",
     "Official VS Code and JetBrains extensions for running Claude Code inside the editor.",
     "Официальные расширения VS Code и JetBrains для запуска Claude Code прямо в редакторе.",
     "Diagnostics and selected code flow into context automatically here, unlike the plain terminal CLI."),
    ("skill-claude-code-memory", "Claude Code Memory (CLAUDE.md)", "Гайды и практики", "https://docs.claude.com/en/docs/claude-code/memory", "free", "claude-code,claude-md,context,conventions", "",
     "How CLAUDE.md files are discovered, merged and scoped across a project.",
     "Как файлы CLAUDE.md находятся, объединяются и применяются в разных частях проекта.",
     "A nested CLAUDE.md in a subdirectory overrides the root one only for work inside that subtree."),
    ("skill-claude-code-network-sandboxing", "Claude Code Network Sandboxing", "Гайды и практики", "https://docs.claude.com/en/docs/claude-code/network-sandboxing", "free", "claude-code,security,sandbox,network", "",
     "Restricting an agent's outbound network access to an explicit allowlist of hosts.",
     "Ограничение исходящего сетевого доступа агента явным списком разрешённых хостов.",
     "Pair this with filesystem permission limits — network and file access are separate attack surfaces."),
    ("skill-model-cards", "Anthropic Model Cards", "Гайды и практики", "https://docs.claude.com/en/docs/about-claude/models", "free", "models,claude,capabilities,comparison", "",
     "Capability, context-window and pricing comparison across the current Claude model family.",
     "Сравнение возможностей, размера контекста и цены среди текущего семейства моделей Claude.",
     "Check the exact model here before hardcoding a model string — aliases and versions both exist and differ."),
    ("skill-prompt-caching-guide", "Prompt Caching Guide", "Гайды и практики", "https://docs.claude.com/en/docs/build-with-claude/prompt-caching", "free", "caching,cost,performance,claude", "",
     "How to structure prompts so repeated system instructions and context get cached, cutting cost and latency.",
     "Как строить промпты, чтобы повторяющиеся системные инструкции и контекст кэшировались, снижая стоимость и задержку.",
     "Put the stable, reused content (system prompt, long documents) first, and the changing part last."),
    ("skill-anthropic-transparency-hub", "Anthropic Transparency Hub", "Гайды и практики", "https://www.anthropic.com/transparency", "free", "safety,policy,transparency,anthropic", "",
     "Published usage policies, safety framework and transparency reporting for Claude.",
     "Опубликованные политики использования, safety-framework и отчётность по прозрачности для Claude.",
     "Check the current usage policy here before designing a feature in a regulated or high-stakes domain."),
    ("skill-mcp-roots", "MCP Roots", "Инфраструктура MCP", "https://modelcontextprotocol.io/specification/latest/client/roots", "free", "mcp,filesystem,scope,spec", "",
     "How MCP clients communicate filesystem boundaries a server should respect.",
     "Как MCP-клиенты сообщают серверу границы файловой системы, которые нужно соблюдать.",
     "A well-behaved filesystem server checks roots before touching any path outside the declared boundary."),
]
