# -*- coding: utf-8 -*-
# (id, name, category, url, access, tags, install, summary_en, summary_ru, tip_en)
APIS = [
("api-openai-platform","OpenAI Platform API","AI и агенты","https://platform.openai.com/docs/api-reference","mixed","openai,llm,api,agents","",
 "Official OpenAI REST API for chat, responses, embeddings, images and audio.",
 "Официальный REST API OpenAI: чат, responses, эмбеддинги, изображения и аудио.",
 "Use the Responses API for new work and keep the key on a server proxy, never in client code."),
("api-anthropic","Anthropic API","AI и агенты","https://docs.claude.com/en/api/overview","mixed","anthropic,claude,llm,tools","",
 "Claude models with tool use, streaming, batches and prompt caching.",
 "Модели Claude с tool use, стримингом, batch-режимом и prompt caching.",
 "Enable prompt caching for long system prompts: it cuts both latency and cost on repeat calls."),
("api-deepseek","DeepSeek API","AI и агенты","https://api-docs.deepseek.com/","mixed","deepseek,llm,cheap,openai-compatible","",
 "OpenAI-compatible endpoint for DeepSeek chat and reasoning models.",
 "OpenAI-совместимый эндпоинт для чат- и reasoning-моделей DeepSeek.",
 "It is OpenAI-compatible, so you can reuse an existing SDK by swapping base_url and key."),
("api-together","Together AI","Локальные модели","https://docs.together.ai/docs/introduction","freeTier","llm,inference,open-models","",
 "Hosted inference for hundreds of open-weight models behind one API.",
 "Хостинг-инференс сотен open-weight моделей через единый API.",
 "Compare price per million tokens before you pick a model: the spread between similar models is large."),
("api-fireworks","Fireworks AI","Локальные модели","https://docs.fireworks.ai/","freeTier","llm,inference,fast","",
 "Fast serverless inference for open models with an OpenAI-compatible layer.",
 "Быстрый serverless-инференс open-моделей с OpenAI-совместимым слоем.",
 "Start on the serverless tier and only move to dedicated deployments when latency actually hurts."),
("api-perplexity","Perplexity API","Поиск и retrieval","https://docs.perplexity.ai/","mixed","search,llm,citations,research","",
 "Search-grounded answers with citations from a live web index.",
 "Ответы с опорой на живой веб-индекс и ссылками на источники.",
 "Ask for citations explicitly and store them: grounded answers are only useful if you can verify them."),
("api-brave-search","Brave Search API","Поиск и retrieval","https://brave.com/search/api/","freeTier","search,web,index,privacy","",
 "Independent web index with a free monthly query quota.",
 "Независимый веб-индекс с бесплатной месячной квотой запросов.",
 "The free tier is rate limited per second, so queue agent searches instead of firing them in parallel."),
("api-exa","Exa","Поиск и retrieval","https://docs.exa.ai/","freeTier","search,embeddings,agents,research","",
 "Neural search built for agents, with full page contents in the response.",
 "Нейропоиск для агентов: сразу отдаёт содержимое найденных страниц.",
 "Request contents in the same call: one round trip beats search plus a separate scrape."),
("api-jina-reader","Jina AI Reader","Поиск и retrieval","https://jina.ai/reader/","freeTier","scrape,markdown,llm,context","",
 "Turns any URL into clean LLM-ready markdown by prefixing it with r.jina.ai.",
 "Превращает любой URL в чистый markdown для LLM через префикс r.jina.ai.",
 "Great as a fallback when a site blocks your own fetcher, but cache results: you pay per request."),
("api-deepl","DeepL API Free","Переводы и языки","https://developers.deepl.com/docs","freeTier","translation,de,en,quality","",
 "High quality machine translation with 500k free characters per month.",
 "Качественный машинный перевод, 500 тыс. бесплатных символов в месяц.",
 "The Free plan uses a separate api-free host: hardcoding the Pro host is the usual first bug."),
("api-libretranslate","LibreTranslate","Переводы и языки","https://libretranslate.com/docs/","mixed","translation,open-source,self-host","",
 "Open source translation engine you can self-host or use as a hosted API.",
 "Открытый движок перевода: можно self-host или использовать как облачный API.",
 "Self-hosting removes the rate limit entirely and keeps user text off third-party servers."),
("api-mymemory","MyMemory Translation","Переводы и языки","https://mymemory.translated.net/doc/spec.php","noKey","translation,free,fallback","",
 "Free translation memory API with a generous anonymous daily quota.",
 "Бесплатный API памяти переводов с щедрой анонимной дневной квотой.",
 "Perfect as the last link in a translation fallback chain when the primary provider is down."),
("api-dictionary-dev","Free Dictionary API","Словари и лексика","https://dictionaryapi.dev/","noKey","dictionary,english,definitions,learning","",
 "English definitions, phonetics and audio pronunciation without any key.",
 "Английские определения, транскрипция и аудио-произношение без ключа.",
 "The phonetics array is often partly empty: always guard the audio field before playing it."),
("api-datamuse","Datamuse API","Словари и лексика","https://www.datamuse.com/api/","noKey","words,rhymes,synonyms,vocabulary","",
 "Word finding engine for synonyms, rhymes, collocations and spelling hints.",
 "Поисковик слов: синонимы, рифмы, коллокации и подсказки написания.",
 "Combine ml, rel_trg and sp parameters to build vocabulary exercises without any ML of your own."),
("api-wordnik","Wordnik API","Словари и лексика","https://developer.wordnik.com/","freeTier","dictionary,english,examples","",
 "Definitions, examples and word-of-the-day from many dictionary sources.",
 "Определения, примеры и слово дня из множества словарных источников.",
 "Ask for several source dictionaries at once: coverage per single source is uneven."),
("api-lrclib","LRCLIB","Музыка и медиа","https://lrclib.net/docs","noKey","lyrics,synced,music,free","",
 "Open lyrics database with plain and time-synced lyrics, no key required.",
 "Открытая база текстов песен с обычными и синхронизированными lyrics, без ключа.",
 "Search by track plus artist plus duration: exact matching cuts the wrong-song rate a lot."),
("api-theaudiodb","TheAudioDB","Музыка и медиа","https://www.theaudiodb.com/api_guide.php","freeTier","music,artists,artwork,metadata","",
 "Artist biographies, album art and band metadata for music sites.",
 "Биографии артистов, обложки и метаданные групп для музыкальных сайтов.",
 "Cache artwork URLs locally: the test key is heavily throttled and images rarely change."),
("api-deezer","Deezer API","Музыка и медиа","https://developers.deezer.com/api","freeTier","music,search,preview,charts","",
 "Track search, 30-second previews, charts and artist data.",
 "Поиск треков, 30-секундные превью, чарты и данные артистов.",
 "Preview URLs expire, so resolve them at play time instead of storing them in your database."),
("api-lastfm","Last.fm API","Музыка и медиа","https://www.last.fm/api","freeTier","music,scrobbles,similar,tags","",
 "Listening data, similar artists and community tags.",
 "Данные прослушиваний, похожие артисты и теги сообщества.",
 "The similar-artists endpoint is the cheapest way to build a recommendation section."),
("api-setlistfm","setlist.fm API","Музыка и медиа","https://api.setlist.fm/docs/1.0/index.html","freeTier","concerts,setlists,tours","",
 "Crowdsourced concert setlists and tour history.",
 "Сет-листы концертов и история туров, собранные сообществом.",
 "Setlists are user submitted, so show the submission date next to any tour statistic."),
("api-jamendo","Jamendo API","Музыка и медиа","https://developer.jamendo.com/v3.0","freeTier","music,creative-commons,streaming","",
 "Creative Commons music catalog you may legally stream in demos.",
 "Каталог музыки под Creative Commons, которую можно легально играть в демо.",
 "Check the exact CC licence per track: some forbid commercial use even with attribution."),
("api-openverse","Openverse API","Изображения и дизайн","https://api.openverse.org/v1/","noKey","images,audio,creative-commons,search","",
 "Search hundreds of millions of openly licensed images and audio files.",
 "Поиск по сотням миллионов изображений и аудио с открытыми лицензиями.",
 "Store the attribution string with the file: openly licensed still means credit is required."),
("api-picsum","Lorem Picsum","Изображения и дизайн","https://picsum.photos/","noKey","placeholder,images,prototyping","",
 "Placeholder photos by size, seed, blur or grayscale straight from a URL.",
 "Плейсхолдер-фото по размеру, seed, blur и grayscale прямо из URL.",
 "Pass a stable seed so your screenshots and tests do not change image on every reload."),
("api-cloudinary","Cloudinary","Изображения и дизайн","https://cloudinary.com/documentation","freeTier","images,cdn,transform,upload","",
 "Image and video CDN with URL-based transforms and a free tier.",
 "CDN для изображений и видео с трансформациями через URL и free tier.",
 "Do resizing in the URL, not in your code: the CDN caches every generated variant."),
("api-removebg","remove.bg API","Изображения и дизайн","https://www.remove.bg/api","freeTier","images,background,cutout","",
 "Automatic background removal for product and portrait images.",
 "Автоматическое удаление фона с товарных и портретных изображений.",
 "Free credits are small, so cache the cutout result by the source image hash."),
("api-elevenlabs","ElevenLabs API","Аудио и голос","https://elevenlabs.io/docs/api-reference/introduction","freeTier","tts,voice,audio,speech","",
 "Natural text to speech and voice cloning with a free monthly quota.",
 "Естественный синтез речи и клонирование голоса с бесплатной квотой.",
 "Stream the audio instead of waiting for the whole file: perceived latency drops dramatically."),
("api-deepgram","Deepgram","Аудио и голос","https://developers.deepgram.com/docs","freeTier","stt,transcription,realtime","",
 "Fast speech to text with streaming and word-level timestamps.",
 "Быстрый speech-to-text со стримингом и таймкодами на уровне слов.",
 "Word timestamps are what let you build karaoke-style subtitles without extra alignment work."),
("api-assemblyai","AssemblyAI","Аудио и голос","https://www.assemblyai.com/docs","freeTier","stt,transcription,summary,diarization","",
 "Transcription plus speaker diarization, chapters and summaries.",
 "Транскрипция плюс разделение спикеров, главы и краткие пересказы.",
 "Diarization needs decent audio: normalize loudness before upload or speakers get merged."),
("api-telegram-bot","Telegram Bot API","Коммуникации","https://core.telegram.org/bots/api","free","bot,telegram,messaging,webhook","",
 "Full featured bot platform with webhooks, keyboards and file transfer.",
 "Полноценная платформа ботов с вебхуками, клавиатурами и передачей файлов.",
 "Prefer webhooks over long polling in production: it survives restarts far better."),
("api-discord","Discord API","Коммуникации","https://discord.com/developers/docs/reference","free","bot,discord,community,gateway","",
 "REST plus gateway API for bots, slash commands and community tools.",
 "REST и gateway API для ботов, slash-команд и инструментов сообщества.",
 "Register slash commands per guild while developing: global commands take up to an hour to propagate."),
("api-slack-web","Slack Web API","Коммуникации","https://api.slack.com/web","freeTier","slack,bot,workflow,notifications","",
 "Post messages, build workflows and read channels from your own app.",
 "Отправка сообщений, workflow и чтение каналов из собственного приложения.",
 "Scope tokens narrowly: a bot token with chat:write only is much easier to get approved."),
("api-mastodon","Mastodon API","Новости и сообщества","https://docs.joinmastodon.org/api/","free","fediverse,social,open,timeline","",
 "Open social API for timelines, posting and following across instances.",
 "Открытый социальный API: ленты, публикации и подписки между инстансами.",
 "Public timelines need no token at all, which makes it ideal for read-only demo widgets."),
("api-reddit","Reddit API","Новости и сообщества","https://www.reddit.com/dev/api/","freeTier","reddit,social,feeds,oauth","",
 "Subreddit listings, comments and search behind OAuth.",
 "Листинги сабреддитов, комментарии и поиск через OAuth.",
 "Set a descriptive User-Agent with contact info or you will be blocked within minutes."),
("api-stackexchange","Stack Exchange API","Новости и сообщества","https://api.stackexchange.com/docs","freeTier","stackoverflow,questions,search","",
 "Questions, answers and tags across all Stack Exchange sites.",
 "Вопросы, ответы и теги по всем сайтам Stack Exchange.",
 "Use the filter parameter to strip fields you do not need: payloads shrink by an order of magnitude."),
("api-youtube-data","YouTube Data API","Видео и медиа","https://developers.google.com/youtube/v3","freeTier","video,search,playlists,google","",
 "Search videos, read playlists and channel metadata.",
 "Поиск видео, чтение плейлистов и метаданных каналов.",
 "Search costs a hundred quota units per call, so cache results and paginate carefully."),
("api-vimeo","Vimeo API","Видео и медиа","https://developer.vimeo.com/api/guides/start","freeTier","video,hosting,embed","",
 "Upload, manage and embed video with granular privacy controls.",
 "Загрузка, управление и встраивание видео с гибкими настройками приватности."
 ,"Domain-level privacy lets you embed on your own site while blocking hotlinking elsewhere."),
("api-spotify","Spotify Web API","Музыка и медиа","https://developer.spotify.com/documentation/web-api","freeTier","music,search,playlists,oauth","",
 "Catalog search, playlists and playback data via OAuth.",
 "Поиск по каталогу, плейлисты и данные воспроизведения через OAuth.",
 "Client credentials flow is enough for catalog search: only user data needs the full login dance."),
("api-db-transport","DB transport.rest","Транспорт и город","https://v6.db.transport.rest/","noKey","germany,trains,departures,travel","",
 "Free REST wrapper over Deutsche Bahn timetables and departures.",
 "Бесплатная REST-обёртка над расписаниями и отправлениями Deutsche Bahn.",
 "Resolve station ids once and cache them: name lookups are the slowest part of the API."),
("api-openholidays","OpenHolidays API","Транспорт и город","https://www.openholidaysapi.org/en/","noKey","holidays,school,germany,europe","",
 "Public and school holidays for many European countries and German states.",
 "Государственные и школьные каникулы стран Европы и земель Германии.",
 "German holidays differ per Bundesland: always pass the subdivision code."),
("api-zippopotam","Zippopotam.us","Транспорт и город","https://api.zippopotam.us/","noKey","postal-code,geo,address","",
 "Postal code to place and coordinates lookup for dozens of countries.",
 "Поиск города и координат по почтовому индексу для десятков стран.",
 "Handy for address form autofill without pulling in a paid geocoding provider."),
("api-nominatim","Nominatim","Карты и навигация","https://nominatim.org/release-docs/latest/api/Overview/","noKey","geocoding,osm,search,reverse","",
 "OpenStreetMap geocoding and reverse geocoding.",
 "Геокодирование и обратное геокодирование на данных OpenStreetMap.",
 "The public instance allows one request per second: batch and cache or self-host."),
("api-overpass","Overpass API","Карты и навигация","https://wiki.openstreetmap.org/wiki/Overpass_API","noKey","osm,query,poi,map-data","",
 "Query engine for raw OpenStreetMap objects like cafes, benches or trails.",
 "Движок запросов к сырым объектам OpenStreetMap: кафе, скамейки, тропы.",
 "Always bound the query with a bbox and a timeout, or the server will simply drop it."),
("api-brightsky","Bright Sky","Погода и геоданные","https://brightsky.dev/","noKey","weather,germany,dwd,forecast","",
 "JSON access to official German DWD weather observations and forecasts.",
 "JSON-доступ к официальным наблюдениям и прогнозам немецкой службы DWD.",
 "Data is station based, so pick the nearest station explicitly for stable historical series."),
("api-openaq","OpenAQ","Погода и геоданные","https://docs.openaq.org/","freeTier","air-quality,environment,sensors","",
 "Worldwide open air quality measurements from public sensors.",
 "Открытые мировые измерения качества воздуха с публичных датчиков.",
 "Sensor coverage is uneven: check the last update timestamp before showing a value as current."),
("api-usgs-quake","USGS Earthquake API","Наука и исследования","https://earthquake.usgs.gov/fdsnws/event/1/","noKey","earthquake,geojson,realtime,science","",
 "Real time and historical earthquake feeds in GeoJSON.",
 "Актуальные и исторические данные о землетрясениях в формате GeoJSON.",
 "The ready-made GeoJSON summary feeds drop straight into Leaflet with zero transformation."),
("api-inaturalist","iNaturalist API","Наука и исследования","https://api.inaturalist.org/v1/docs/","noKey","biodiversity,species,photos,citizen-science","",
 "Species observations with photos from a global citizen science network.",
 "Наблюдения видов с фотографиями из глобальной сети гражданской науки.",
 "Filter by quality_grade=research if you need identifications you can actually trust."),
("api-openfoodfacts","Open Food Facts","Еда и быт","https://openfoodfacts.github.io/openfoodfacts-server/api/","noKey","food,barcode,nutrition,open-data","",
 "Open product database searchable by barcode with nutrition facts.",
 "Открытая база продуктов с поиском по штрихкоду и данными о питании.",
 "Fields are crowd-filled and often missing: code defensively around every nutrient key."),
("api-themealdb","TheMealDB","Еда и быт","https://www.themealdb.com/api.php","freeTier","recipes,food,images","",
 "Recipes with images, ingredients and categories.",
 "Рецепты с изображениями, ингредиентами и категориями.",
 "The ingredient fields are numbered up to twenty: loop instead of writing them out."),
("api-alphavantage","Alpha Vantage","Финансы","https://www.alphavantage.co/documentation/","freeTier","stocks,forex,crypto,timeseries","",
 "Stock, forex and crypto time series with a free key.",
 "Временные ряды акций, валют и крипты с бесплатным ключом.",
 "The free key allows only a handful of calls per minute: build a queue before you build the chart."),
("api-finnhub","Finnhub","Финансы","https://finnhub.io/docs/api","freeTier","stocks,news,fundamentals,websocket","",
 "Market data, company news and a realtime websocket feed.",
 "Рыночные данные, новости компаний и realtime-поток по websocket.",
 "Websocket quotes are free but delayed on the base plan: label the delay in your UI."),
("api-stripe","Stripe API","Платежи и commerce","https://docs.stripe.com/api","freeTier","payments,checkout,billing,webhooks","",
 "Payments, subscriptions and invoicing with a full test mode.",
 "Платежи, подписки и счета с полноценным тестовым режимом.",
 "Verify webhook signatures from day one: it is the security bug reviewers look for first."),
("api-vercel-rest","Vercel REST API","Облако и деплой","https://vercel.com/docs/rest-api","freeTier","deploy,hosting,ci,projects","",
 "Manage projects, deployments, domains and env vars programmatically.",
 "Программное управление проектами, деплоями, доменами и переменными окружения.",
 "Scope tokens to one project: a full-account token in CI is an avoidable blast radius."),
("api-netlify","Netlify API","Облако и деплой","https://docs.netlify.com/api/get-started/","freeTier","deploy,hosting,forms,functions","",
 "Deploy sites, read build logs and manage forms from code.",
 "Деплой сайтов, чтение логов сборки и управление формами из кода.",
 "The digest deploy endpoint uploads only changed files, which makes CI deploys much faster."),
("api-cloudflare","Cloudflare API","Облако и деплой","https://developers.cloudflare.com/api/","freeTier","dns,workers,r2,cdn","",
 "DNS, Workers, R2 and CDN configuration over one REST surface.",
 "DNS, Workers, R2 и настройки CDN через единый REST-интерфейс.",
 "Use scoped API tokens rather than the global key: the global key can do literally everything."),
("api-notion","Notion API","Документация и контекст","https://developers.notion.com/","freeTier","notes,database,cms,workspace","",
 "Read and write Notion pages and databases as a lightweight CMS.",
 "Чтение и запись страниц и баз Notion как лёгкой CMS.",
 "Pages must be explicitly shared with your integration, which is the usual cause of empty results."),
("api-airtable","Airtable API","Базы данных и backend","https://airtable.com/developers/web/api/introduction","freeTier","database,spreadsheet,cms,records","",
 "Spreadsheet-style database with a clean REST API for prototypes.",
 "База в стиле таблицы с чистым REST API для прототипов.",
 "Five requests per second per base is the hard ceiling: batch writes in groups of ten records."),
("api-turso","Turso","Базы данных и backend","https://docs.turso.tech/","freeTier","sqlite,edge,libsql,database","",
 "Edge-hosted SQLite (libSQL) with generous free storage.",
 "SQLite (libSQL) на краю сети со щедрым бесплатным хранилищем.",
 "Embedded replicas give local read speed with remote writes: ideal for offline-first apps."),
("api-dummyjson","DummyJSON","Тестовые и mock API","https://dummyjson.com/docs","noKey","mock,fake-data,rest,prototyping","",
 "Realistic fake REST data for products, users, carts and posts.",
 "Реалистичные фейковые REST-данные: товары, пользователи, корзины, посты.",
 "It supports delay and limit parameters, so you can rehearse loading and pagination states."),
("api-httpbin","httpbin","Тестовые и mock API","https://httpbin.org/","noKey","http,debug,testing,requests","",
 "Request and response inspection service for debugging HTTP clients.",
 "Сервис проверки запросов и ответов для отладки HTTP-клиентов.",
 "The /status/:code and /delay/:n routes are the fastest way to test retry and timeout logic."),
("api-qrserver","QR Code API","Утилиты","https://goqr.me/api/","noKey","qr,barcode,image,generate","",
 "Generate QR codes as images straight from a URL.",
 "Генерация QR-кодов в виде картинок прямо из URL.",
 "Since output is a plain image URL, you can embed it in emails and PDFs with no SDK at all."),
("api-shields","Shields.io","Разработка и DevOps","https://shields.io/","free","badges,readme,ci,status","",
 "Dynamic SVG badges for READMEs, versions and build status.",
 "Динамические SVG-бейджи для README, версий и статуса сборки.",
 "The endpoint badge type renders from your own JSON, so you can publish any metric you like."),
("api-lichess","Lichess API","Игры и развлечения","https://lichess.org/api","noKey","chess,games,pgn,open-source","",
 "Open chess platform API for games, puzzles and PGN export.",
 "Открытый шахматный API: партии, задачи и экспорт PGN.",
 "Streaming endpoints send newline-delimited JSON, so parse per line rather than per body."),
("api-jikan","Jikan (MyAnimeList)","Игры и развлечения","https://jikan.moe/","noKey","anime,manga,search,unofficial","",
 "Unofficial MyAnimeList REST API for anime and manga metadata.",
 "Неофициальный REST API MyAnimeList с метаданными аниме и манги.",
 "Rate limits are strict and enforced per second and per minute: add backoff before you ship."),
("api-rickandmorty","Rick and Morty API","Игры и развлечения","https://rickandmortyapi.com/documentation","noKey","rest,graphql,demo,learning","",
 "Small, well documented REST and GraphQL API perfect for teaching demos.",
 "Небольшой отлично документированный REST и GraphQL API для учебных демо.",
 "The GraphQL endpoint makes it a painless first project for practising queries and fragments."),
("api-thesportsdb","TheSportsDB","Игры и развлечения","https://www.thesportsdb.com/free_sports_api","freeTier","sports,teams,scores,logos","",
 "Team, league and event metadata with logos across many sports.",
 "Метаданные команд, лиг и матчей с логотипами по многим видам спорта.",
 "Logo and badge URLs are stable, which makes it a decent free image source for sports UIs."),

# ==================== Stage 4 additions ====================

# ---------- Аутентификация ----------
("api-turnstile","Cloudflare Turnstile","Аутентификация","https://developers.cloudflare.com/turnstile/","free","captcha,bots,forms,privacy","",
 "Invisible CAPTCHA replacement with no puzzles and no per-site limit.",
 "Невидимая замена CAPTCHA без головоломок и без лимита на число сайтов.",
 "Verify the token server side: the client widget alone stops nobody who reads your bundle."),
("api-hcaptcha","hCaptcha","Аутентификация","https://docs.hcaptcha.com/","freeTier","captcha,bots,forms,accessibility","",
 "Bot protection for forms with an accessibility mode and no user tracking.",
 "Защита форм от ботов с режимом доступности и без трекинга пользователей.",
 "Keep the sitekey public and the secret on the server; they are not interchangeable."),
("api-workos","WorkOS","Аутентификация","https://workos.com/docs","freeTier","sso,saml,scim,enterprise","",
 "Enterprise SSO, SCIM directory sync and audit logs behind one API.",
 "Корпоративный SSO, SCIM-синхронизация каталогов и audit logs через один API.",
 "Add SSO only when a customer asks and pays for it: the integration outlives the deal."),
("api-ory","Ory Network","Аутентификация","https://www.ory.sh/docs/","freeTier","auth,oauth,permissions,open-source","",
 "Composable identity, OAuth2 and permission services with an open-source core.",
 "Композируемые сервисы identity, OAuth2 и разрешений с открытым ядром.",
 "The same APIs run self-hosted, so a migration off the cloud stays a config change."),

# ---------- Безопасность и секреты ----------
("api-hibp","Have I Been Pwned","Безопасность и секреты","https://haveibeenpwned.com/API/v3","mixed","breach,passwords,security,privacy","",
 "Breach lookups for accounts, plus a k-anonymity range API for passwords.",
 "Проверка утечек по аккаунтам и k-anonymity Range API для паролей.",
 "The password range endpoint takes five SHA-1 characters, so the secret never leaves your server."),
("api-osv","OSV.dev","Безопасность и секреты","https://google.github.io/osv.dev/api/","free","vulnerabilities,dependencies,cve,scanning","",
 "Open vulnerability database queryable by package, version or commit.",
 "Открытая база уязвимостей с запросами по пакету, версии или коммиту.",
 "Query by exact version in CI and fail the build only on fixed-available advisories."),
("api-virustotal","VirusTotal","Безопасность и секреты","https://docs.virustotal.com/reference/overview","freeTier","malware,urls,files,threat-intel","",
 "Reputation checks for files, URLs, domains and IPs across many engines.",
 "Проверка репутации файлов, ссылок, доменов и IP по множеству движков.",
 "Public keys allow only a few requests per minute: queue lookups instead of scanning in a loop."),
("api-abuseipdb","AbuseIPDB","Безопасность и секреты","https://docs.abuseipdb.com/","freeTier","ip,abuse,blocklist,security","",
 "Community-reported abuse scores for IP addresses.",
 "Оценки злоупотреблений по IP-адресам на основе сообщений сообщества.",
 "Cache the verdict per IP for a day: scores move slowly and the free quota does not."),
("api-ssl-labs","SSL Labs API","Безопасность и секреты","https://github.com/ssllabs/ssllabs-scan/blob/master/ssllabs-api-docs-v4.md","free","tls,https,scanning,certificates","",
 "Deep TLS configuration analysis for a hostname, the same engine as the web grader.",
 "Глубокий анализ конфигурации TLS для хоста — тот же движок, что у веб-сканера.",
 "A full scan takes minutes: poll with startNew=off or you will keep restarting it."),

# ---------- Почта и уведомления ----------
("api-brevo","Brevo","Почта и уведомления","https://developers.brevo.com/","freeTier","email,sms,transactional,marketing","",
 "Transactional and marketing email plus SMS behind one API.",
 "Транзакционная и маркетинговая почта плюс SMS через один API.",
 "Set up SPF and DKIM before the first send: domain reputation is hard to repair later."),
("api-mailgun","Mailgun","Почта и уведомления","https://documentation.mailgun.com/","mixed","email,smtp,routing,webhooks","",
 "Email sending, inbound routing and delivery webhooks for applications.",
 "Отправка почты, входящая маршрутизация и webhooks доставки для приложений.",
 "Inbound routes turn a mailbox into a webhook, which beats polling IMAP from your app."),
("api-ntfy","ntfy","Почта и уведомления","https://docs.ntfy.sh/","free","push,notifications,self-host,no-key","",
 "Push notifications to your phone from a plain HTTP POST, no account needed.",
 "Push-уведомления на телефон обычным HTTP POST, без регистрации.",
 "One curl line turns any script into an alerting system; self-host it for private topics."),
("api-onesignal","OneSignal","Почта и уведомления","https://documentation.onesignal.com/","freeTier","push,web-push,mobile,segments","",
 "Push notifications for web, Android and iOS with segmentation.",
 "Push-уведомления для web, Android и iOS с сегментацией аудитории.",
 "Web push needs HTTPS and a service worker, so plan for a tunnel during local development."),
("api-novu","Novu","Почта и уведомления","https://docs.novu.co/","openSource","notifications,workflows,in-app,self-host","",
 "Notification infrastructure: one workflow fans out to email, push, SMS and in-app.",
 "Инфраструктура уведомлений: один workflow разводит письма, push, SMS и in-app.",
 "Model the workflow once and switch providers per channel without touching product code."),

# ---------- Платежи и commerce ----------
("api-polar","Polar","Платежи и commerce","https://docs.polar.sh/","mixed","payments,merchant-of-record,saas,digital-goods","",
 "Merchant-of-record billing for developer products, including usage-based AI billing.",
 "Merchant of record для продуктов разработчиков, включая оплату ИИ по потреблению.",
 "As merchant of record they file the sales tax, which removes the hardest part of selling globally."),
("api-revenuecat","RevenueCat","Платежи и commerce","https://www.revenuecat.com/docs/","freeTier","subscriptions,mobile,iap,paywalls","",
 "Cross-platform in-app subscription infrastructure for iOS, Android and web.",
 "Инфраструктура подписок в приложениях для iOS, Android и web.",
 "Never trust a client receipt: let their server verify entitlements and read the result."),
("api-btcpay","BTCPay Server","Платежи и commerce","https://docs.btcpayserver.org/","openSource","crypto,bitcoin,self-host,invoices","",
 "Self-hosted crypto payment processor with no fees and no third party.",
 "Self-hosted процессор крипто-платежей без комиссий и посредников.",
 "You hold the keys, which also means you own the backups: test recovery before going live."),

# ---------- Финансы ----------
("api-binance-public","Binance Public API","Финансы","https://developers.binance.com/docs/binance-spot-api-docs","free","crypto,prices,market-data,websocket","",
 "Public market data for crypto pairs over REST and websocket streams.",
 "Публичные рыночные данные по крипто-парам через REST и websocket-стримы.",
 "Market data needs no key; use the websocket stream instead of polling the REST endpoint."),
("api-fmp","Financial Modeling Prep","Финансы","https://site.financialmodelingprep.com/developer/docs","freeTier","stocks,fundamentals,statements,finance","",
 "Company fundamentals, statements and quotes for equities.",
 "Фундаментальные данные компаний, отчётности и котировки по акциям.",
 "Fundamentals change quarterly: cache them and only refresh quotes frequently."),

# ---------- Карты и навигация ----------
("api-maptiler","MapTiler Cloud","Карты и навигация","https://docs.maptiler.com/cloud/api/","freeTier","maps,tiles,geocoding,vector","",
 "Vector tiles, map styles and geocoding as a drop-in alternative to Google Maps.",
 "Векторные тайлы, стили карт и геокодирование как замена Google Maps.",
 "Restrict the key to your domains in the dashboard: a frontend key is public by definition."),
("api-stadia-maps","Stadia Maps","Карты и навигация","https://docs.stadiamaps.com/","freeTier","maps,tiles,routing,geocoding","",
 "Map tiles, routing and geocoding built on open data.",
 "Тайлы карт, маршрутизация и геокодирование на открытых данных.",
 "Their styles work directly with MapLibre, so switching providers is a URL change."),
("api-photon","Photon Geocoder","Карты и навигация","https://photon.komoot.io/","free","geocoding,osm,search,no-key","",
 "Typeahead-friendly geocoder built on OpenStreetMap data.",
 "Геокодер на данных OpenStreetMap, удобный для подсказок при вводе.",
 "Built for as-you-type search, but self-host it before you point production traffic at the demo."),

# ---------- Транспорт и город ----------
("api-transitland","Transitland","Транспорт и город","https://www.transit.land/documentation/","freeTier","transit,gtfs,routes,open-data","",
 "Aggregated public transit feeds: operators, routes, stops and schedules.",
 "Агрегированные фиды общественного транспорта: операторы, маршруты, остановки, расписания.",
 "GTFS feeds are huge; filter by feed_onestop_id rather than downloading everything."),
("api-open-charge-map","Open Charge Map","Транспорт и город","https://openchargemap.org/site/develop/api","freeTier","ev,charging,poi,open-data","",
 "Community database of electric-vehicle charging locations worldwide.",
 "Открытая база точек зарядки электромобилей по всему миру.",
 "Bound every query by bounding box and distance or the response runs to megabytes."),

# ---------- Открытые данные ----------
("api-worldbank","World Bank Open Data","Открытые данные","https://datahelpdesk.worldbank.org/knowledgebase/topics/125589","free","economics,indicators,countries,no-key","",
 "Decades of economic and social indicators for every country.",
 "Экономические и социальные показатели стран за десятилетия.",
 "Pass format=json explicitly: the default response is XML and will surprise your parser."),
("api-eurostat","Eurostat API","Открытые данные","https://ec.europa.eu/eurostat/web/main/data/web-services","free","europe,statistics,open-data,no-key","",
 "Official European statistics as JSON-stat datasets.",
 "Официальная статистика Европы в формате JSON-stat.",
 "JSON-stat is dimension-indexed, not row-based: flatten it once into records before charting."),
("api-destatis","Destatis GENESIS","Открытые данные","https://www-genesis.destatis.de/datenbank/online","freeTier","germany,statistics,government,data","",
 "Official German federal statistics through the GENESIS-Online API.",
 "Официальная статистика Германии через API GENESIS-Online.",
 "Registration is free, and the CSV responses are far easier to parse than their JSON."),
("api-wikidata","Wikidata Query Service","Открытые данные","https://query.wikidata.org/","free","sparql,linked-data,facts,no-key","",
 "SPARQL endpoint over structured facts about people, places and things.",
 "SPARQL-эндпоинт по структурированным фактам о людях, местах и объектах.",
 "Always set LIMIT and a descriptive User-Agent; the public endpoint drops heavy queries."),

# ---------- Наука и исследования ----------
("api-datacite","DataCite REST API","Наука и исследования","https://support.datacite.org/docs/api","free","doi,datasets,metadata,no-key","",
 "Metadata for research datasets, software and preprints registered with DOIs.",
 "Метаданные исследовательских датасетов, ПО и препринтов с DOI.",
 "Complements Crossref: DataCite covers datasets and software, Crossref covers journal articles."),

# ---------- Здоровье и медицина ----------
("api-pubmed","PubMed E-utilities","Здоровье и медицина","https://www.ncbi.nlm.nih.gov/books/NBK25501/","free","medical,papers,ncbi,no-key","",
 "Search and fetch biomedical literature records from NCBI.",
 "Поиск и выгрузка записей биомедицинской литературы из NCBI.",
 "Chain esearch then efetch, and keep to three requests per second without an API key."),
("api-rxnorm","RxNorm API","Здоровье и медицина","https://lhncbc.nlm.nih.gov/RxNav/APIs/","free","drugs,medical,normalization,no-key","",
 "Normalised drug names and identifiers linking clinical drug vocabularies.",
 "Нормализованные названия и идентификаторы лекарств, связывающие клинические словари.",
 "This is reference data, not medical advice: show a disclaimer wherever you surface it."),

# ---------- Еда и быт ----------
("api-usda-fdc","USDA FoodData Central","Еда и быт","https://fdc.nal.usda.gov/api-guide","freeTier","food,nutrition,open-data,health","",
 "Authoritative nutrient data for tens of thousands of foods.",
 "Авторитетные данные о нутриентах для десятков тысяч продуктов.",
 "DEMO_KEY works for a first test but is rate-limited hard; a personal key is instant and free."),
("api-open-brewery-db","Open Brewery DB","Еда и быт","https://www.openbrewerydb.org/documentation","noKey","breweries,geo,no-key,directory","",
 "Directory of breweries with addresses and coordinates, no key required.",
 "Каталог пивоварен с адресами и координатами, без ключа.",
 "Most records carry latitude and longitude, which makes it a ready dataset for map practice."),
("api-thecocktaildb","TheCocktailDB","Еда и быт","https://www.thecocktaildb.com/api.php","freeTier","cocktails,recipes,images,food","",
 "Cocktail recipes with ingredients, measures and images.",
 "Рецепты коктейлей с ингредиентами, пропорциями и изображениями.",
 "The public test key is fine for a prototype but is shared and throttled; get your own to ship."),

# ---------- Игры и развлечения ----------
("api-deck-of-cards","Deck of Cards API","Игры и развлечения","https://deckofcardsapi.com/","noKey","cards,games,no-key,fun","",
 "A virtual deck of cards with shuffling, drawing and piles.",
 "Виртуальная колода карт с тасовкой, раздачей и стопками.",
 "The server keeps deck state, so a card game needs no backend of your own."),

# ---------- Космос и наука ----------
("api-spacex","SpaceX API","Космос и наука","https://github.com/r-spacex/SpaceX-API","noKey","space,launches,rockets,no-key","",
 "Launches, rockets, capsules and landing history, key-free.",
 "Запуски, ракеты, капсулы и история посадок, без ключа.",
 "A clean dataset for practising timelines and charts: rich, small and never rate-limited."),
("api-sunrise-sunset","Sunrise Sunset API","Космос и наука","https://sunrise-sunset.org/api","noKey","sun,astronomy,geo,no-key","",
 "Sunrise, sunset and twilight times for any coordinates.",
 "Время восхода, заката и сумерек для любых координат.",
 "Results come back in UTC; convert on the client or your evening will be someone else’s morning."),

# ---------- Музыка и медиа ----------
("api-podcast-index","Podcast Index","Музыка и медиа","https://podcastindex-org.github.io/docs-api/","free","podcasts,rss,search,open","",
 "Open index of podcasts and episodes with full-text search.",
 "Открытый индекс подкастов и эпизодов с полнотекстовым поиском.",
 "Auth is a SHA-1 of key, secret and timestamp, so it has to be computed server side."),

# ---------- Изображения и дизайн ----------
("api-imagekit","ImageKit","Изображения и дизайн","https://imagekit.io/docs","freeTier","images,cdn,resize,webp","",
 "Media CDN with on-the-fly resizing and automatic WebP or AVIF delivery.",
 "Медиа-CDN с ресайзом на лету и автоматической отдачей WebP или AVIF.",
 "Transformations live in the URL, so responsive images need no build-time asset pipeline."),
("api-tinypng","TinyPNG","Изображения и дизайн","https://tinypng.com/developers","freeTier","images,compression,png,optimize","",
 "Lossy PNG and JPEG compression that keeps quality visually intact.",
 "Сжатие PNG и JPEG с потерями, визуально сохраняющее качество.",
 "Compress once at build time and commit the result; do not spend quota on every deploy."),
("api-dicebear","DiceBear Avatars","Изображения и дизайн","https://www.dicebear.com/how-to-use/http-api/","noKey","avatars,svg,placeholder,no-key","",
 "Deterministic SVG avatars generated from a seed string, many styles.",
 "Детерминированные SVG-аватары по строке-сиду, множество стилей.",
 "The same seed always yields the same avatar, which keeps demo users stable across rebuilds."),
("api-uploadthing","UploadThing","Изображения и дизайн","https://docs.uploadthing.com/","freeTier","upload,files,typescript,nextjs","",
 "File uploads for TypeScript apps with a typed router and signed URLs.",
 "Загрузка файлов для TypeScript-приложений с типизированным роутером и signed URL.",
 "Enforce size and MIME limits in the server router: client-side checks are advisory only."),
("api-bfl-flux","Black Forest Labs FLUX","Изображения и дизайн","https://docs.bfl.ai/","mixed","image-generation,flux,editing,diffusion","",
 "FLUX image generation and editing endpoints, including structural conditioning.",
 "Генерация и редактирование изображений FLUX, включая структурное кондиционирование.",
 "Record the seed and the exact model id: without both, a good result is not reproducible."),

# ---------- Документы и PDF ----------
("api-cloudconvert","CloudConvert","Документы и PDF","https://cloudconvert.com/api/v2","mixed","conversion,pdf,documents,files","",
 "File conversion between hundreds of document, image and media formats.",
 "Конвертация файлов между сотнями форматов документов, изображений и медиа.",
 "Build a job with tasks rather than one-shot calls: it gives you retries and webhooks for free."),
("api-gotenberg","Gotenberg","Документы и PDF","https://gotenberg.dev/docs/getting-started/introduction","openSource","pdf,html-to-pdf,docker,self-host","",
 "A Docker service that turns HTML, Markdown and Office files into PDF.",
 "Docker-сервис, превращающий HTML, Markdown и Office-файлы в PDF.",
 "It wraps headless Chromium, so your invoice template is just a styled web page."),

# ---------- Таблицы и no-code ----------
("api-google-sheets","Google Sheets API","Таблицы и no-code","https://developers.google.com/workspace/sheets/api/guides/concepts","free","spreadsheets,google,rows,backend","",
 "Read and write spreadsheet cells, ranges and formatting programmatically.",
 "Чтение и запись ячеек, диапазонов и форматирования таблиц программно.",
 "A service account plus one shared sheet is the fastest editable backend a non-developer can own."),
("api-nocodb","NocoDB","Таблицы и no-code","https://docs.nocodb.com/","openSource","database,no-code,rest,self-host","",
 "Turns any Postgres or MySQL database into a spreadsheet UI with a REST API.",
 "Превращает любую базу Postgres или MySQL в таблицу с REST API.",
 "It sits on your existing database, so nothing is trapped in a vendor’s storage."),
("api-baserow","Baserow","Таблицы и no-code","https://baserow.io/api-docs","freeTier","database,no-code,rest,self-host","",
 "Open-source Airtable alternative with a REST API and self-hosting.",
 "Открытая альтернатива Airtable с REST API и self-hosting.",
 "Grid views map to filtered API queries, so the UI and the API stay in sync by construction."),

# ---------- Разработка и DevOps ----------
("api-npm-registry","npm Registry API","Разработка и DevOps","https://github.com/npm/registry/blob/main/docs/REGISTRY-API.md","free","npm,packages,versions,no-key","",
 "Package metadata, versions, dependencies and download counts.",
 "Метаданные пакетов, версии, зависимости и статистика загрузок.",
 "Requesting /{package}/latest is the cheapest possible version check for a dependency bot."),
("api-pypi-json","PyPI JSON API","Разработка и DevOps","https://docs.pypi.org/api/json/","free","python,packages,versions,no-key","",
 "Release history and metadata for Python packages.",
 "История релизов и метаданные пакетов Python.",
 "One request returns every release, so diff locally instead of paging the index."),
("api-crates-io","crates.io API","Разработка и DevOps","https://crates.io/data-access","free","rust,packages,versions,no-key","",
 "Versions, owners and download metadata for Rust crates.",
 "Версии, владельцы и статистика загрузок для Rust-крейтов.",
 "A descriptive User-Agent is mandatory here: anonymous clients get a 403, not a rate limit."),
("api-pub-dev","pub.dev API","Мобильная и desktop разработка","https://pub.dev/help/api","free","dart,flutter,packages,no-key","",
 "Version and publisher metadata for Dart and Flutter packages.",
 "Метаданные версий и издателей для пакетов Dart и Flutter.",
 "Useful for checking your own Flutter dependencies from a script instead of by hand."),

# ---------- Мониторинг и аналитика ----------
("api-uptimerobot","UptimeRobot","Мониторинг и аналитика","https://uptimerobot.com/api/","freeTier","uptime,monitoring,alerts,status-page","",
 "Availability monitoring with alerting and public status pages.",
 "Мониторинг доступности с алертами и публичными статус-страницами.",
 "Monitor the health endpoint, not the homepage: a cached page stays up while the API is down."),
("api-axiom","Axiom","Мониторинг и аналитика","https://axiom.co/docs","freeTier","logs,events,query,observability","",
 "High-volume log and event storage with a query language on top.",
 "Хранение логов и событий большого объёма с языком запросов поверх.",
 "Send structured JSON events rather than text lines; the query language pays you back for it."),
("api-langfuse","Langfuse","AI и агенты","https://langfuse.com/docs","freeTier","llm-ops,tracing,evals,prompts","",
 "Tracing, prompt versioning, evaluation and cost tracking for LLM apps.",
 "Трассировка, версии промптов, оценки и учёт стоимости для LLM-приложений.",
 "Instrument before you optimise: most cost surprises are one unbounded retry loop."),
("api-helicone","Helicone","AI и агенты","https://docs.helicone.ai/","freeTier","llm-ops,proxy,caching,cost","",
 "A one-line proxy that logs every model call, with caching and rate limits.",
 "Прокси в одну строку, логирующий каждый вызов модели, с кэшем и лимитами.",
 "Changing a base URL is the whole integration, which makes it easy to trial and easy to remove."),

# ---------- AI и агенты ----------
("api-cerebras","Cerebras Inference","AI и агенты","https://inference-docs.cerebras.ai/","freeTier","llm,inference,fast,openai-compatible","",
 "Wafer-scale inference for open-weight models when tokens per second is the metric.",
 "Инференс открытых моделей на wafer-scale чипах, когда важны токены в секунду.",
 "The endpoint is OpenAI-compatible, so it is a two-line swap in an existing client."),
("api-deepinfra","DeepInfra","AI и агенты","https://deepinfra.com/docs","mixed","llm,inference,open-models,embeddings","",
 "Per-token hosting for a broad set of open-weight text, image and audio models.",
 "Потокенный хостинг широкого набора открытых моделей текста, изображений и аудио.",
 "Prices differ sharply between similar models: check the per-model rate, not the provider."),
("api-voyage","Voyage AI","Поиск и retrieval","https://docs.voyageai.com/","freeTier","embeddings,rerank,rag,search","",
 "Embedding and reranking models tuned for retrieval quality.",
 "Модели эмбеддингов и реранка, настроенные на качество поиска.",
 "Adding a reranker usually beats upgrading the generator when RAG answers are off-topic."),
("api-jina-embeddings","Jina Embeddings","Поиск и retrieval","https://jina.ai/embeddings/","freeTier","embeddings,multilingual,rag,long-context","",
 "Multilingual embedding models with long input windows.",
 "Мультиязычные модели эмбеддингов с длинным входным окном.",
 "Long context lets you embed a whole section, which keeps chunk boundaries out of your answers."),

# ---------- Аудио и голос ----------
("api-cartesia","Cartesia","Аудио и голос","https://docs.cartesia.ai/","freeTier","tts,voice,streaming,latency","",
 "Low-latency streaming text-to-speech aimed at real-time voice agents.",
 "Стриминговый синтез речи с низкой задержкой для голосовых агентов в реальном времени.",
 "Stream the first sentence while the rest generates: perceived latency is what users judge."),

# ---------- Переводы и языки ----------
("api-lingva","Lingva Translate","Переводы и языки","https://github.com/thedaviddelta/lingva-translate","openSource","translate,proxy,self-host,no-key","",
 "A key-free translation API that proxies Google Translate, self-hostable.",
 "Переводческий API без ключа, проксирующий Google Translate, с self-hosting.",
 "Public instances come and go: pin your own deployment before shipping anything that matters."),
("api-tatoeba","Tatoeba API","Словари и лексика","https://en.wiki.tatoeba.org/articles/show/api","free","sentences,examples,languages,no-key","",
 "Millions of example sentences with translations, contributed and reviewed.",
 "Миллионы примеров предложений с переводами, собранных и проверенных сообществом.",
 "Example sentences beat dictionary definitions for language drills; filter by owner for quality."),

# ---------- Утилиты ----------
("api-worldtime","WorldTimeAPI","Утилиты","https://worldtimeapi.org/","noKey","time,timezone,dst,no-key","",
 "Current time, timezone and DST details by zone or client IP.",
 "Текущее время, таймзона и параметры DST по зоне или IP клиента.",
 "For display formatting, Intl.DateTimeFormat in the browser is simpler; use this on the server."),
("api-ipapi-co","ipapi.co","Погода и геоданные","https://ipapi.co/api/","freeTier","ip,geolocation,timezone,no-key","",
 "IP geolocation with country, city, timezone and currency.",
 "Геолокация по IP: страна, город, часовой пояс и валюта.",
 "Good enough to pick a default language, never good enough to enforce access rules."),
]
