# -*- coding: utf-8 -*-
"""Stage 5 API pack I: enterprise SaaS integrations, docs/knowledge, ecommerce."""

APIS_5I = [
    # ---------- CMS и контент (deepen) ----------
    ("api-directus-2", "Directus Cloud", "CMS и контент", "https://docs.directus.io/", "openSource", "cms,headless,sql,self-host", "",
     "Wraps any existing SQL database in a headless CMS and REST/GraphQL API.",
     "Оборачивает любую существующую SQL-базу в headless CMS и REST/GraphQL API.",
     "Point it at a database you already have — it introspects the schema instead of forcing its own."),
    ("api-storyblok", "Storyblok", "CMS и контент", "https://www.storyblok.com/docs/api/content-delivery/v2", "freeTier", "cms,headless,visual-editor,components", "",
     "Headless CMS with a visual editor that previews your real components live.",
     "Headless CMS с визуальным редактором, показывающим реальные компоненты в живом превью.",
     "The visual editor needs a bridge script on your frontend — set it up early or editors get a blank preview."),
    ("api-prismic", "Prismic", "CMS и контент", "https://prismic.io/docs", "freeTier", "cms,headless,slices,page-builder", "",
     "Headless CMS built around reusable content slices that map to frontend components.",
     "Headless CMS вокруг переиспользуемых слайсов контента, отображаемых в компоненты фронтенда.",
     "Model slices to match your component library one-to-one, or the page builder gets confusing for editors."),
    ("api-ghost-api", "Ghost Content API", "CMS и контент", "https://ghost.org/docs/content-api/", "openSource", "cms,blog,publishing,headless", "",
     "Read-only content API for the Ghost publishing platform, usable headlessly.",
     "API контента только для чтения для платформы публикаций Ghost, можно использовать headless.",
     "The Content API key is safe to expose client-side; the Admin API key is not — do not mix them up."),
    ("api-notion-api-2", "Notion API (databases)", "CMS и контент", "https://developers.notion.com/reference/post-database-query", "freeTier", "notion,database,query,filters", "",
     "Query Notion databases with filters and sorts, using Notion as a lightweight CMS.",
     "Запросы к базам данных Notion с фильтрами и сортировкой — Notion как лёгкая CMS.",
     "Query results are paginated at 100 items — always follow next_cursor rather than assuming one page."),

    # ---------- Платежи и commerce (deepen) ----------
    ("api-shopify-admin", "Shopify Admin API", "Платежи и commerce", "https://shopify.dev/docs/api/admin", "mixed", "ecommerce,shopify,graphql,orders", "",
     "Products, orders, customers and inventory for Shopify stores via GraphQL.",
     "Товары, заказы, клиенты и склад для магазинов Shopify через GraphQL.",
     "REST is being deprecated in favor of GraphQL — start new integrations on GraphQL directly."),
    ("api-shopify-storefront", "Shopify Storefront API", "Платежи и commerce", "https://shopify.dev/docs/api/storefront", "mixed", "ecommerce,headless,shopify,graphql", "",
     "Public, customer-facing GraphQL API for building headless Shopify storefronts.",
     "Публичный клиентский GraphQL API для headless-витрин Shopify.",
     "This token is safe in client code, unlike the Admin API token — that's the whole point of the split."),
    ("api-woocommerce", "WooCommerce REST API", "Платежи и commerce", "https://woocommerce.github.io/woocommerce-rest-api-docs/", "openSource", "ecommerce,wordpress,rest,orders", "",
     "REST API for WooCommerce stores running on WordPress.",
     "REST API для магазинов WooCommerce на WordPress.",
     "Requires HTTPS for key-based auth — over plain HTTP it silently falls back to a weaker OAuth1 flow."),
    ("api-medusa-js", "Medusa", "Платежи и commerce", "https://docs.medusajs.com/", "openSource", "ecommerce,headless,nodejs,self-host", "npx create-medusa-app@latest",
     "Open-source headless commerce engine in Node, a self-hostable Shopify alternative.",
     "Открытый headless-движок коммерции на Node, self-hosted альтернатива Shopify.",
     "Its plugin system covers payments and fulfillment — check for an existing plugin before writing an integration."),
    ("api-snipcart", "Snipcart", "Платежи и commerce", "https://docs.snipcart.com/v3/", "mixed", "ecommerce,cart,static-sites,javascript", "",
     "Drop-in shopping cart for static sites, added with a script tag and HTML attributes.",
     "Готовая корзина для статических сайтов, добавляется скриптом и HTML-атрибутами.",
     "Products are defined in your HTML markup, which means no separate product database to maintain."),

    # ---------- Документация и контекст (deepen) ----------
    ("api-readme-io", "ReadMe", "Документация и контекст", "https://docs.readme.com/main/reference/intro-to-the-readme-api", "mixed", "docs,api-reference,openapi,hosted", "",
     "Hosted API documentation generated from OpenAPI, with an interactive playground.",
     "Размещённая документация API из OpenAPI с интерактивной песочницей.",
     "Sync your OpenAPI spec from CI so docs never drift behind the actual API surface."),
    ("api-mintlify", "Mintlify", "Документация и контекст", "https://mintlify.com/docs", "freeTier", "docs,mdx,hosted,ai-search", "npm i -g mint",
     "Documentation platform with MDX authoring, AI search and a polished default theme.",
     "Платформа документации с авторингом в MDX, ИИ-поиском и качественной темой по умолчанию.",
     "Docs live as MDX files in your repo, so documentation reviews happen in the same PR as the code change."),
    ("api-gitbook", "GitBook API", "Документация и контекст", "https://gitbook.com/docs/developers/gitbook-api", "freeTier", "docs,knowledge-base,api,publishing", "",
     "Programmatic access to GitBook spaces, pages and content for docs automation.",
     "Программный доступ к пространствам, страницам и контенту GitBook для автоматизации документации.",
     "Git Sync keeps a GitBook space mirrored with a repo branch — often simpler than driving the API directly."),

    # ---------- Браузер и автоматизация (deepen) ----------
    ("api-scrapfly", "Scrapfly", "Браузер и автоматизация", "https://scrapfly.io/docs", "freeTier", "scraping,anti-bot,proxy,rendering", "",
     "Web scraping API with anti-bot bypass, JS rendering and proxy rotation built in.",
     "API веб-скрапинга с обходом анти-бот защиты, JS-рендерингом и ротацией прокси.",
     "Enable ASP (anti-scraping protection) bypass only when needed — it costs more credits per request."),
    ("api-zenrows", "ZenRows", "Браузер и автоматизация", "https://docs.zenrows.com/", "freeTier", "scraping,proxy,anti-bot,api", "",
     "Scraping API handling proxies, headless browsers and CAPTCHA avoidance behind one call.",
     "API скрапинга, берущий на себя прокси, headless-браузеры и обход CAPTCHA в одном вызове.",
     "Start without premium proxies — many sites work fine on the cheaper datacenter pool."),
    ("api-browserless", "Browserless", "Браузер и автоматизация", "https://docs.browserless.io/", "freeTier", "headless,chrome,puppeteer,hosted", "",
     "Hosted headless Chrome that Puppeteer and Playwright connect to over WebSocket.",
     "Размещённый headless Chrome, к которому Puppeteer и Playwright подключаются по WebSocket.",
     "Change one connect() line in existing Puppeteer code — no rewrite needed to move off local Chrome."),
    ("api-apify-2", "Apify Actors", "Браузер и автоматизация", "https://docs.apify.com/platform/actors", "freeTier", "scraping,actors,marketplace,cloud", "",
     "Prebuilt scrapers ('actors') for common sites, plus a platform to run your own.",
     "Готовые скраперы («акторы») для популярных сайтов плюс платформа для запуска своих.",
     "Search the Actor Store before writing a scraper — a maintained one likely exists for your target site."),

    # ---------- Мониторинг и аналитика (deepen) ----------
    ("api-newrelic", "New Relic", "Мониторинг и аналитика", "https://docs.newrelic.com/docs/apis/intro-apis/introduction-new-relic-apis/", "freeTier", "apm,observability,nrql,monitoring", "",
     "Full-stack observability with its own NRQL query language and a real free tier.",
     "Full-stack observability с собственным языком запросов NRQL и реальным бесплатным тарифом.",
     "The free tier includes 100GB/month ingest — generous enough for a small production service."),
    ("api-dynatrace", "Dynatrace", "Мониторинг и аналитика", "https://docs.dynatrace.com/docs/dynatrace-api", "paid", "apm,observability,ai,enterprise", "",
     "Enterprise observability with automated dependency mapping and root-cause analysis.",
     "Корпоративная observability с автоматическим построением зависимостей и анализом первопричин.",
     "Its OneAgent auto-discovers services without manual instrumentation, which is the main draw over DIY OTel."),
    ("api-elastic-apm", "Elastic APM", "Мониторинг и аналитика", "https://www.elastic.co/guide/en/apm/guide/current/index.html", "openSource", "apm,elastic,tracing,self-host", "",
     "Application performance monitoring built on the Elastic Stack, self-hostable.",
     "Мониторинг производительности приложений на Elastic Stack, можно разместить самостоятельно.",
     "If you already run Elasticsearch for logs, APM data lands in the same cluster — one system, not two."),

    # ---------- HR и рекрутинг (deepen) ----------
    ("api-ashby", "Ashby API", "HR и рекрутинг", "https://developers.ashbyhq.com/", "mixed", "ats,recruiting,analytics,hiring", "",
     "Modern ATS API with strong built-in hiring analytics.",
     "Современный API ATS с сильной встроенной аналитикой найма.",
     "Its analytics endpoints expose funnel metrics directly — no need to recompute them from raw application data."),
    ("api-rippling", "Rippling API", "HR и рекрутинг", "https://developer.rippling.com/", "paid", "hr,payroll,it,employee-data", "",
     "Unified HR, IT and payroll platform API for employee lifecycle automation.",
     "Единый API HR, IT и зарплат для автоматизации жизненного цикла сотрудника.",
     "Its IT provisioning hooks let onboarding create accounts across tools automatically from one HR event."),
    ("api-gusto", "Gusto API", "HR и рекрутинг", "https://docs.gusto.com/", "mixed", "payroll,hr,benefits,small-business", "",
     "Payroll and benefits API aimed at small and mid-sized US businesses.",
     "API зарплат и льгот для малого и среднего бизнеса в США.",
     "The demo environment has synthetic companies to build against before touching real payroll data."),
]
