# -*- coding: utf-8 -*-
"""Stage 5 pricing pack G: voice synthesis, meeting capture and transcription services."""

PAID_5G = [
("paid-wellsaid","WellSaid Labs (pricing)","Аудио и голос","https://wellsaidlabs.com/pricing/","paid","tts,pricing,subscription,seats",
 "Studio-quality synthetic voices sold as a monthly subscription per seat.",
 "Синтетические голоса студийного качества по месячной подписке за место.",
 "Voices are licensed from paid actors, which is what the premium over open TTS models buys.",
 "subscription","from ~$44 per month","free trial","https://wellsaidlabs.com/pricing/"),
("paid-respeecher","Respeecher (pricing)","Аудио и голос","https://www.respeecher.com/pricing","paid","voice-conversion,pricing,minutes,production",
 "Speech-to-speech voice conversion billed by processed audio minutes.",
 "Конверсия речи в речь с оплатой по минутам обработанного аудио.",
 "Priced for film and game production, where a single scene justifies the per-minute rate.",
 "usage","custom quote (per minute)","free trial","https://www.respeecher.com/pricing"),
("paid-krisp","Krisp (pricing)","Аудио и голос","https://krisp.ai/pricing/","paid","noise-cancellation,pricing,sdk,per-user",
 "Noise cancellation sold per user, with separate SDK licensing for embedding.",
 "Подавление шума с оплатой за пользователя и отдельным лицензированием SDK для встраивания.",
 "The desktop app and the embeddable SDK are priced separately — confirm which you actually need.",
 "subscription","from ~$8 per user per month","free tier with limited minutes","https://krisp.ai/pricing/"),
("paid-sonix","Sonix (pricing)","Аудио и голос","https://sonix.ai/pricing","paid","transcription,pricing,per-hour,subscription",
 "Transcription and translation billed per hour of audio.",
 "Транскрипция и перевод с оплатой за час аудио.",
 "Per-hour pricing beats a subscription for occasional use; the reverse holds at steady volume.",
 "usage","from ~$10 per hour of audio","free trial minutes","https://sonix.ai/pricing"),
("paid-recall-ai","Recall.ai (pricing)","Видеоконференции","https://www.recall.ai/pricing","paid","meeting-bots,pricing,per-hour,usage",
 "Meeting bot infrastructure billed per hour of recorded meeting.",
 "Инфраструктура ботов для встреч с оплатой за час записанной встречи.",
 "Cheaper than maintaining three platform-specific bot integrations, which is the real comparison.",
 "usage","from ~$0.70 per hour","free trial credit","https://www.recall.ai/pricing"),
("paid-otter-ai","Otter.ai (pricing)","Видеоконференции","https://otter.ai/pricing","paid","transcription,pricing,subscription,minutes",
 "Meeting transcription billed monthly with per-plan minute allowances.",
 "Транскрипция встреч с месячной оплатой и лимитом минут по каждому тарифу.",
 "Its free plan covers occasional personal use, with monthly minute caps rather than a trial period.",
 "subscription","from ~$16.99 per user per month","free tier with monthly minutes","https://otter.ai/pricing"),
("paid-grain","Grain (pricing)","Видеоконференции","https://grain.com/pricing","paid","meetings,pricing,per-seat,subscription",
 "Meeting recording and highlight clips billed per seat.",
 "Запись встреч и выделение фрагментов с оплатой за место.",
 "Aimed at sales teams, so seat count tracks the revenue org rather than engineering.",
 "subscription","from ~$19 per seat per month","free tier","https://grain.com/pricing"),
("paid-attend","Attend.com (pricing)","Видеоконференции","https://www.attend.com/pricing","paid","meetings,pricing,per-seat,crm",
 "AI meeting assistant billed per seat, with CRM sync on higher tiers.",
 "AI-ассистент встреч с оплатой за место; синхронизация с CRM — на старших тарифах.",
 "The CRM write-back is the feature that justifies the cost, and it is not on the entry plan.",
 "subscription","from ~$29 per seat per month","free trial","https://www.attend.com/pricing"),
("paid-escape-tech","Escape (pricing)","Безопасность и секреты","https://escape.tech/pricing","paid","api-security,pricing,per-api,subscription",
 "API security testing billed by the number of APIs under scan.",
 "Тестирование безопасности API с оплатой по числу сканируемых API.",
 "Per-API pricing suits a focused surface; a sprawling microservice estate gets expensive fast.",
 "subscription","custom quote (per API)","free trial","https://escape.tech/pricing"),
("paid-salt-security","Salt Security (pricing)","Безопасность и секреты","https://salt.security/pricing","paid","api-security,pricing,enterprise,traffic",
 "Runtime API security sold on enterprise contracts scaled to API traffic.",
 "Безопасность API во время выполнения по корпоративным контрактам, масштабируемым под трафик API.",
 "Enterprise-only, and its value depends on having enough traffic for behavioural baselining to work.",
 "custom","custom quote","product demo","https://salt.security/pricing"),
("paid-traceable","Traceable (pricing)","Безопасность и секреты","https://www.traceable.ai/pricing","paid","api-security,pricing,enterprise,custom",
 "Trace-based API security sold on enterprise contracts.",
 "Безопасность API на основе трассировки по корпоративным контрактам.",
 "It assumes distributed tracing is already deployed — factor that instrumentation work into the cost.",
 "custom","custom quote","product demo","https://www.traceable.ai/pricing"),
("paid-noname-security","Akamai API Security (pricing)","Безопасность и секреты","https://www.akamai.com/products/api-security","paid","api-security,pricing,enterprise,discovery",
 "Enterprise API discovery and posture management sold through Akamai contracts.",
 "Корпоративное обнаружение API и управление защищённостью по контрактам Akamai.",
 "Usually bought alongside other Akamai edge products rather than as a standalone tool.",
 "custom","custom quote","product demo","https://www.akamai.com/products/api-security"),
("paid-impart-security","Impart Security (pricing)","Безопасность и секреты","https://impart.security/pricing","paid","api-security,pricing,traffic,subscription",
 "Runtime API protection priced by protected request volume.",
 "Защита API во время выполнения с ценой по объёму защищённых запросов.",
 "Traffic-based pricing means cost tracks real exposure rather than the number of services.",
 "custom","custom quote (by request volume)","free trial","https://impart.security/pricing"),
]
