# -*- coding: utf-8 -*-
"""Stage 5 library pack E: more testing/build tools, animation, PDF, robotics libs."""

LIBS_5E = [
    # ---------- Сборка и bundlers (deepen) ----------
    ("lib-rolldown", "Rolldown", "Сборка и bundlers", "https://rolldown.rs/", "openSource", "bundler,rust,rollup-compatible,vite", "",
     "Rust-based bundler aiming for Rollup compatibility, built to eventually power Vite.",
     "Бандлер на Rust, совместимый с Rollup, создаётся как будущий движок Vite.",
     "Watch this replace Rollup under the hood in Vite over time — the API is designed to stay compatible."),
    ("lib-turbopack", "Turbopack", "Сборка и bundlers", "https://turbo.build/pack/docs", "openSource", "bundler,rust,vercel,incremental", "",
     "Rust-based incremental bundler from Vercel, built as a faster successor to Webpack.",
     "Инкрементальный бандлер на Rust от Vercel, создан как более быстрый преемник Webpack.",
     "Currently powers Next.js dev mode — check current production-readiness before using it standalone."),
    ("lib-parcel", "Parcel", "Сборка и bundlers", "https://parceljs.org/docs/", "openSource", "bundler,zero-config,fast,javascript", "npm i -D parcel",
     "Zero-configuration bundler that just works for most common project setups.",
     "Бандлер без конфигурации, который просто работает для большинства типовых проектов.",
     "Point it at an HTML entry file and it resolves the rest — no config file needed for a first build."),

    # ---------- Анимация и 3D (deepen) ----------
    ("lib-gsap-scrolltrigger", "GSAP ScrollTrigger", "Анимация и 3D", "https://gsap.com/docs/v3/Plugins/ScrollTrigger/", "openSource", "gsap,scroll,animation,plugin", "",
     "GSAP's scroll-driven animation plugin, now free including what used to be paid plugins.",
     "Плагин GSAP для анимации по скроллу, теперь бесплатен вместе с бывшими платными плагинами.",
     "Use scrub for animation tied directly to scroll position instead of a one-shot trigger."),
    ("lib-theatre-js", "Theatre.js", "Анимация и 3D", "https://www.theatrejs.com/docs/latest", "openSource", "animation,timeline,visual-editor,webgl", "npm i @theatre/core",
     "Motion design library with a visual timeline editor, aimed at complex WebGL/Three.js scenes.",
     "Библиотека для motion-дизайна с визуальным редактором таймлайна для сложных WebGL/Three.js сцен.",
     "The Studio editor lets a designer tweak keyframes visually without touching the animation code."),
    ("lib-drei", "Drei", "Анимация и 3D", "https://github.com/pmndrs/drei", "openSource", "react-three-fiber,helpers,3d,components", "npm i @react-three/drei",
     "Ready-made helper components for React Three Fiber: cameras, controls, loaders, effects.",
     "Готовые вспомогательные компоненты для React Three Fiber: камеры, контролы, загрузчики, эффекты.",
     "Check here before hand-rolling a camera control or loader — most common R3F needs already exist as a Drei component."),
    ("lib-motion-canvas", "Motion Canvas", "Анимация и 3D", "https://motioncanvas.io/docs/", "openSource", "animation,typescript,programmatic,video", "npm init @motion-canvas@latest",
     "Programmatic animation for creating precise vector-based explainer videos in TypeScript.",
     "Программируемая анимация для точных векторных обучающих видео на TypeScript.",
     "Animations are code and fully reproducible/diffable in git, unlike a keyframe-based video editor project."),

    # ---------- Документы и PDF (deepen) ----------
    ("lib-pdf-lib", "pdf-lib", "Документы и PDF", "https://pdf-lib.js.org/", "openSource", "pdf,javascript,forms,create", "npm i pdf-lib",
     "Create and modify PDFs in JavaScript, in the browser or Node, including form fields.",
     "Создание и изменение PDF на JavaScript в браузере или Node, включая поля форм.",
     "It runs in the browser with no server round-trip — generate a PDF entirely client-side when privacy matters."),
    ("lib-pdfmake", "pdfmake", "Документы и PDF", "https://pdfmake.github.io/docs/", "openSource", "pdf,javascript,declarative,reports", "npm i pdfmake",
     "Declarative PDF generation from a JSON document definition, good for reports and invoices.",
     "Декларативная генерация PDF из JSON-описания документа, удобно для отчётов и счетов.",
     "The document definition is plain JSON, which makes generating a PDF from server data a direct mapping."),
    ("lib-jspdf", "jsPDF", "Документы и PDF", "https://github.com/parallax/jsPDF", "openSource", "pdf,javascript,client-side,simple", "npm i jspdf",
     "Client-side PDF generation directly in the browser with a simple imperative API.",
     "Генерация PDF прямо в браузере на клиенте с простым императивным API.",
     "Pair it with html2canvas to turn an existing DOM element into a PDF page directly."),
    ("lib-pymupdf", "PyMuPDF", "Документы и PDF", "https://pymupdf.readthedocs.io/", "openSource", "pdf,python,fast,rendering", "pip install pymupdf",
     "Fast PDF parsing and rendering in Python, faster than most pure-Python alternatives.",
     "Быстрый парсинг и рендеринг PDF на Python, быстрее большинства чисто-питоновских альтернатив.",
     "Its C-based rendering is why it stays fast on large PDFs where pypdf slows down noticeably."),

    # ---------- Робототехника ----------
    ("lib-rospy", "rclpy (ROS 2 Python)", "Робототехника", "https://docs.ros.org/en/rolling/p/rclpy/", "openSource", "ros,python,robotics,nodes", "",
     "Python client library for writing ROS 2 nodes.",
     "Python-клиентская библиотека для написания узлов ROS 2.",
     "Prototype logic in Python nodes first; port to C++ only for the specific nodes that need real-time performance."),
    ("lib-pybullet", "PyBullet", "Робототехника", "https://pybullet.org/wordpress/index.php/forum-2/", "openSource", "physics,simulation,robotics,reinforcement-learning", "pip install pybullet",
     "Physics simulation for robotics and reinforcement learning, lighter-weight than Gazebo.",
     "Физическая симуляция для робототехники и обучения с подкреплением, легче Gazebo.",
     "It is the common choice for RL research specifically because episodes reset and run faster than Gazebo."),
    ("lib-opencv-robotics", "OpenCV (robotics use)", "Робототехника", "https://docs.opencv.org/", "openSource", "vision,robotics,perception,cpp", "pip install opencv-python",
     "The same computer-vision toolkit, referenced here for robot perception pipelines specifically.",
     "Тот же тулкит компьютерного зрения, здесь — применительно к пайплайнам восприятия робота.",
     "ArUco marker detection built into OpenCV is a fast way to add fiducial-based localization to a robot."),

    # ---------- Backend и API (deepen) ----------
    ("lib-graphql-yoga", "GraphQL Yoga", "Backend и API", "https://the-guild.dev/graphql/yoga-server/docs", "openSource", "graphql,server,node,spec-compliant", "npm i graphql-yoga",
     "Fully spec-compliant, batteries-included GraphQL server for Node.",
     "Полностью соответствующий спецификации GraphQL-сервер для Node со всем необходимым из коробки.",
     "Subscriptions over SSE work out of the box, unlike many servers that need a separate WebSocket setup."),
    ("lib-apollo-server", "Apollo Server", "Backend и API", "https://www.apollographql.com/docs/apollo-server", "openSource", "graphql,server,node,federation", "npm i @apollo/server",
     "Widely used GraphQL server with strong support for schema federation across services.",
     "Широко используемый GraphQL-сервер с сильной поддержкой федерации схем между сервисами.",
     "Federation is the specific reason to pick this over a simpler server when multiple teams own separate schemas."),
    ("lib-pothos", "Pothos", "Backend и API", "https://pothos-graphql.dev/", "openSource", "graphql,typescript,code-first,schema", "npm i @pothos/core",
     "Code-first GraphQL schema builder with full TypeScript inference, no separate schema file.",
     "Code-first построитель GraphQL-схем с полным выводом типов TypeScript, без отдельного файла схемы.",
     "Types flow from your resolvers to the schema automatically — no risk of the two drifting apart."),
    ("lib-trpc-2", "tRPC (server plugins)", "Backend и API", "https://trpc.io/docs/server/introduction", "openSource", "typescript,rpc,type-safe,server", "npm i @trpc/server",
     "The server-side package for tRPC's end-to-end typed API pattern.",
     "Серверный пакет для паттерна end-to-end типизированного API tRPC.",
     "Middleware composes cleanly for auth checks — attach it once at the router level, not per-procedure."),
]
