# -*- coding: utf-8 -*-
# (iid, name, category, url, access, tags, summary_en, summary_ru, tip_en,
#  model, from_price, free_quota, pricing_url)
PAID_5B = [
("paid-drugbank","DrugBank (pricing)","Здоровье и медицина","https://go.drugbank.com/pricing","paid","drugs,pricing,pharmacology,license",
 "Licensed pharmacology database, quote-based pricing for commercial use.",
 "Лицензированная фармакологическая база данных, цена по запросу для коммерческого использования.",
 "Academic and non-commercial use has separate, much cheaper licensing — check eligibility before the commercial quote.",
 "subscription","custom license quote","free academic license available","https://go.drugbank.com/pricing"),
("paid-project44","project44 (pricing)","Логистика и доставка","https://www.project44.com/","paid","freight,visibility,pricing,enterprise",
 "Enterprise supply-chain visibility platform, quote-based pricing by shipment volume.",
 "Корпоративная платформа видимости цепочки поставок, цена по запросу за объём отгрузок.",
 "This is an enterprise sales process from the start — there is no self-serve trial to test against your lanes.",
 "subscription","custom quote by shipment volume","no public trial","https://www.project44.com/"),
("paid-middesk","Middesk (pricing)","Идентификация и KYC","https://www.middesk.com/","paid","kyb,pricing,business-verification,custom",
 "Business verification (KYB) checks priced per verification, volume-tiered.",
 "Проверки бизнеса (KYB) с оплатой за проверку, тарифы по объёму.",
 "Ask for sandbox access to test against known-good and known-bad business records before any commercial commitment.",
 "usage","custom per-verification pricing","sandbox available on request","https://www.middesk.com/"),
("paid-postmark-templates","Postmark (pricing)","Коммуникации","https://postmarkapp.com/pricing","paid","email,pricing,transactional,volume",
 "Transactional email priced per monthly email volume.",
 "Транзакционная почта с оплатой по месячному объёму писем.",
 "The 100-email free trial is enough to validate templates and deliverability setup before paying.",
 "subscription","from ~$15 per month (10k emails)","100 free emails to start","https://postmarkapp.com/pricing"),
("paid-kagi-search","Kagi Search (pricing)","Инфраструктура MCP","https://kagi.com/pricing","paid","search,pricing,privacy,subscription",
 "Ad-free search billed as a personal subscription, with an API extension for the same account.",
 "Поиск без рекламы по личной подписке с расширением API для того же аккаунта.",
 "The free trial searches are enough to judge result quality before committing to a monthly plan.",
 "subscription","from ~$10 per month","free trial searches","https://kagi.com/pricing"),
("paid-rippling","Rippling (pricing)","HR и рекрутинг","https://www.rippling.com/pricing","paid","hr,payroll,pricing,per-employee",
 "Unified HR/IT/payroll platform priced per employee per month, modules billed separately.",
 "Единая платформа HR/IT/зарплат с оплатой за сотрудника в месяц, модули оплачиваются отдельно.",
 "Module-based pricing adds up fast — price the exact modules you need, not the platform headline rate.",
 "subscription","from ~$8 per employee per month","demo via sales","https://www.rippling.com/pricing"),
("paid-planetscale-vitess","PlanetScale (pricing)","Базы данных и backend","https://planetscale.com/pricing","paid","mysql,pricing,vitess,scaling",
 "Managed MySQL priced by cluster size and storage, no free tier since 2024.",
 "Управляемый MySQL с оплатой по размеру кластера и хранилищу, бесплатного тарифа нет с 2024 года.",
 "The free tier was removed — budget from the entry paid plan, unlike Neon or Supabase which still have one.",
 "subscription","from ~$39 per month","no free tier","https://planetscale.com/pricing"),
("paid-dynatrace","Dynatrace (pricing)","Мониторинг и аналитика","https://www.dynatrace.com/pricing/","paid","apm,pricing,observability,per-host",
 "Enterprise observability billed per host-hour plus data ingest volume.",
 "Корпоративная observability с оплатой за час работы хоста плюс объём принятых данных.",
 "Host-hour billing means idle non-production hosts still cost money — scope monitoring to what matters.",
 "usage","from ~$0.04 per host-hour","15-day free trial","https://www.dynatrace.com/pricing/"),
("paid-bunny-net","Bunny.net (pricing)","Изображения и дизайн","https://bunny.net/pricing/","paid","cdn,pricing,bandwidth,storage",
 "CDN and storage billed per GB transferred, priced by region.",
 "CDN и хранилище с оплатой за переданный ГБ, цена зависит от региона.",
 "Per-GB rates vary several-fold by region — check your actual traffic geography before estimating cost.",
 "usage","from ~$0.01 per GB","$1 minimum monthly spend","https://bunny.net/pricing/"),
("paid-intercom","Intercom (pricing)","Коммуникации","https://www.intercom.com/pricing","paid","support,pricing,seats,resolutions",
 "Customer support platform priced per seat plus per AI-resolved conversation.",
 "Платформа поддержки клиентов с оплатой за место плюс за разговор, решённый ИИ.",
 "The per-resolution AI charge is separate from seats — model both when estimating monthly cost.",
 "subscription","from ~$29 per seat per month","14-day free trial","https://www.intercom.com/pricing"),
("paid-front-app","Front (pricing)","Коммуникации","https://front.com/pricing","paid","shared-inbox,pricing,seats,collaboration",
 "Shared inbox and team collaboration priced per seat per month.",
 "Общий почтовый ящик и командная работа с оплатой за место в месяц.",
 "API access is gated to higher plans — verify your tier includes it before designing an integration.",
 "subscription","from ~$19 per seat per month","7-day free trial","https://front.com/pricing"),
]
