# -*- coding: utf-8 -*-
"""Stage 5 API pack M: government/civic data, environment/energy, sports, misc reference."""

APIS_5M = [
    # ---------- Открытые данные (deepen further) ----------
    ("api-uk-gov", "GOV.UK Content API", "Открытые данные", "https://content-api.publishing.service.gov.uk/", "free", "government,uk,content,no-key", "",
     "Structured access to all GOV.UK published content, no key required.",
     "Структурированный доступ ко всему опубликованному контенту GOV.UK, без ключа.",
     "A good example of well-designed government API documentation, worth reading even outside UK projects."),
    ("api-companies-house", "Companies House API", "Юридические и налоговые API", "https://developer.company-information.service.gov.uk/", "free", "companies,uk,registry,legal", "",
     "UK company registry data: filings, officers, ownership, all free.",
     "Данные реестра компаний Великобритании: отчётность, руководители, владельцы — бесплатно.",
     "Free and comprehensive for UK entities — a rare case where official registry data needs no commercial vendor."),
    ("api-opencorporates", "OpenCorporates", "Юридические и налоговые API", "https://api.opencorporates.com/documentation/API-Reference", "mixed", "companies,registry,global,legal", "",
     "Company registry data aggregated across many national jurisdictions.",
     "Данные реестров компаний, агрегированные по множеству национальных юрисдикций.",
     "Coverage and freshness vary a lot by jurisdiction — check your target country before relying on it."),
    ("api-openstates", "Open States", "Открытые данные", "https://docs.openstates.org/api-v3/", "freeTier", "government,legislation,us-states,civic", "",
     "US state legislature data: bills, legislators, votes and committees.",
     "Данные законодательных органов штатов США: законопроекты, законодатели, голосования, комитеты.",
     "GraphQL and REST both available — GraphQL avoids over-fetching on bill records with many nested fields."),
    ("api-congress-gov", "Congress.gov API", "Открытые данные", "https://api.congress.gov/", "free", "government,us,legislation,congress", "",
     "Official US Congress legislative data: bills, amendments, members, votes.",
     "Официальные законодательные данные Конгресса США: законопроекты, поправки, члены, голосования.",
     "Uses the same api.data.gov key infrastructure as other federal APIs — one key covers several agencies."),
    ("api-fec", "OpenFEC", "Открытые данные", "https://api.open.fec.gov/developers/", "free", "campaign-finance,us,elections,transparency", "",
     "US campaign finance data: contributions, expenditures and committee filings.",
     "Данные о финансировании избирательных кампаний США: взносы, расходы, отчёты комитетов.",
     "Filing data lags real activity by weeks — do not treat it as real-time during an active campaign."),

    # ---------- Наука и исследования: environment/energy ----------
    ("api-electricity-maps", "Electricity Maps", "Наука и исследования", "https://portal.electricitymaps.com/docs/api", "freeTier", "energy,carbon,grid,climate", "",
     "Real-time carbon intensity and electricity mix data by geographic zone.",
     "Данные об углеродоёмкости и структуре электрогенерации по географическим зонам в реальном времени.",
     "Useful for carbon-aware scheduling — shift batch jobs to hours when the grid is cleanest."),
    ("api-carbon-interface", "Carbon Interface", "Наука и исследования", "https://docs.carboninterface.com/", "freeTier", "carbon,emissions,calculator,sustainability", "",
     "Carbon emission estimates for electricity, flights, shipping and vehicles.",
     "Оценка выбросов углерода для электроэнергии, авиаперелётов, доставки и транспорта.",
     "Estimates use published emission factors, so document the methodology if you display figures to users."),
    ("api-eia", "EIA Open Data", "Наука и исследования", "https://www.eia.gov/opendata/documentation.php", "free", "energy,us,statistics,government", "",
     "US Energy Information Administration data on production, consumption and prices.",
     "Данные Управления энергетической информации США о добыче, потреблении и ценах.",
     "Series IDs are the primary lookup key — browse the catalog first rather than guessing identifiers."),
    ("api-gbif", "GBIF", "Наука и исследования", "https://techdocs.gbif.org/en/openapi/", "free", "biodiversity,species,occurrences,open-data", "",
     "Global biodiversity data: species occurrence records from museums and surveys worldwide.",
     "Глобальные данные о биоразнообразии: записи о встречах видов из музеев и исследований по всему миру.",
     "Occurrence downloads are asynchronous for large queries — request, then poll for the prepared archive."),

    # ---------- Игры и развлечения: sports ----------
    ("api-api-football", "API-Football", "Игры и развлечения", "https://www.api-football.com/documentation-v3", "freeTier", "football,soccer,fixtures,live-scores", "",
     "Football (soccer) fixtures, live scores, standings and statistics across leagues.",
     "Расписание, живые счета, турнирные таблицы и статистика футбола по лигам.",
     "The free tier's 100 requests/day suits a personal dashboard, not a public live-score site."),
    ("api-balldontlie", "balldontlie", "Игры и развлечения", "https://docs.balldontlie.io/", "freeTier", "nba,basketball,stats,simple", "",
     "NBA statistics API: players, teams, games and box scores.",
     "API статистики NBA: игроки, команды, игры и протоколы матчей.",
     "Simple enough to be a good first API for teaching pagination and query parameters."),
    ("api-football-data-org", "football-data.org", "Игры и развлечения", "https://www.football-data.org/documentation/quickstart", "freeTier", "football,fixtures,competitions,free-tier", "",
     "European football competition data with a free tier covering major leagues.",
     "Данные европейских футбольных соревнований с бесплатным тарифом по основным лигам.",
     "The free tier covers a fixed set of competitions — verify your league is included before building."),

    # ---------- Погода и геоданные (deepen) ----------
    ("api-meteostat", "Meteostat", "Погода и геоданные", "https://dev.meteostat.net/", "freeTier", "weather,historical,climate,stations", "",
     "Historical weather and climate data from thousands of ground stations.",
     "Исторические данные о погоде и климате с тысяч наземных метеостанций.",
     "Its Python library reads the same data locally without API limits, which suits bulk historical analysis."),
    ("api-weatherkit", "Apple WeatherKit", "Погода и геоданные", "https://developer.apple.com/weatherkit/", "mixed", "weather,apple,forecast,rest", "",
     "Apple's weather data service, available via REST beyond Apple platforms.",
     "Сервис погодных данных Apple, доступен через REST и вне платформ Apple.",
     "Requires an Apple Developer account even for REST use — that is the main barrier versus alternatives."),

    # ---------- Транспорт и город (deepen) ----------
    ("api-opensky", "OpenSky Network", "Транспорт и город", "https://openskynetwork.github.io/opensky-api/", "free", "flights,adsb,tracking,open-data", "",
     "Free live and historical flight tracking data from a community ADS-B receiver network.",
     "Бесплатные живые и исторические данные отслеживания рейсов из общественной сети ADS-B приёмников.",
     "Anonymous access is heavily rate-limited; registering (still free) raises limits substantially."),
    ("api-navitia", "Navitia", "Транспорт и город", "https://doc.navitia.io/", "freeTier", "transit,routing,gtfs,journey-planner", "",
     "Public transit journey planning API built on open GTFS data.",
     "API планирования поездок на общественном транспорте на открытых данных GTFS.",
     "Coverage depends on which regions have published GTFS feeds — check your city's data availability first."),

    # ---------- Книги и знания (deepen) ----------
    ("api-google-books", "Google Books API", "Книги и знания", "https://developers.google.com/books/docs/v1/using", "free", "books,search,metadata,google", "",
     "Book search, metadata, covers and preview availability from Google Books.",
     "Поиск книг, метаданные, обложки и доступность предпросмотра из Google Books.",
     "Works without a key for basic search, though adding one raises the quota considerably."),
    ("api-isbndb", "ISBNdb", "Книги и знания", "https://isbndb.com/apidocs/v2", "paid", "books,isbn,metadata,catalog", "",
     "Comprehensive ISBN-indexed book database with pricing and edition data.",
     "Полная база книг по ISBN с данными о ценах и изданиях.",
     "More complete for obscure and out-of-print editions than free alternatives, which is what you pay for."),
    ("api-gutendex", "Gutendex (Project Gutenberg)", "Книги и знания", "https://gutendex.com/", "noKey", "books,public-domain,gutenberg,no-key", "",
     "JSON API over Project Gutenberg's public domain book catalog, no key required.",
     "JSON API поверх каталога общественного достояния Project Gutenberg, без ключа.",
     "Full book texts are downloadable directly, which makes it a good corpus source for NLP experiments."),
]
