# -*- coding: utf-8 -*-
"""Stage 5 library pack S: performance, caching, workers, misc web platform."""

LIBS_5S = [
    # ---------- UI и frontend: performance ----------
    ("lib-partytown", "Partytown", "UI и frontend", "https://partytown.builder.io/", "openSource", "performance,web-workers,third-party,scripts", "npm i @builder.io/partytown",
     "Moves third-party scripts off the main thread into a web worker.",
     "Переносит сторонние скрипты с главного потока в web worker.",
     "Analytics and tag-manager scripts are the usual culprits blocking the main thread — start with those."),
    ("lib-comlink", "Comlink", "UI и frontend", "https://github.com/GoogleChromeLabs/comlink", "openSource", "web-workers,rpc,google,ergonomics", "npm i comlink",
     "Makes web workers feel like local async function calls instead of message passing.",
     "Превращает web workers в обычные асинхронные вызовы функций вместо обмена сообщениями.",
     "Removes nearly all postMessage boilerplate, which is why workers stop feeling painful to use."),
    ("lib-workbox", "Workbox", "UI и frontend", "https://developer.chrome.com/docs/workbox", "openSource", "service-worker,pwa,caching,offline", "npm i workbox-build",
     "Service worker toolkit for caching strategies and offline-capable PWAs.",
     "Тулкит service worker для стратегий кэширования и офлайн-совместимых PWA.",
     "Pick the caching strategy per route deliberately — a wrong strategy serves stale content indefinitely."),
    ("lib-vite-pwa", "Vite PWA Plugin", "UI и frontend", "https://vite-pwa-org.netlify.app/", "openSource", "pwa,vite,service-worker,manifest", "npm i -D vite-plugin-pwa",
     "Zero-config PWA support for Vite projects, generating manifest and service worker.",
     "PWA-поддержка без конфигурации для Vite-проектов, генерирует манифест и service worker.",
     "Test the update flow explicitly — stale service workers serving old assets is the classic PWA bug."),
    ("lib-web-vitals", "web-vitals", "Мониторинг и аналитика", "https://github.com/GoogleChrome/web-vitals", "openSource", "performance,metrics,core-web-vitals,google", "npm i web-vitals",
     "Measures Core Web Vitals (LCP, INP, CLS) from real user sessions.",
     "Измеряет Core Web Vitals (LCP, INP, CLS) в реальных пользовательских сессиях.",
     "Field data from real users differs a lot from lab scores — this is what search ranking actually uses."),
    ("lib-lighthouse", "Lighthouse", "Тестирование и качество", "https://developer.chrome.com/docs/lighthouse", "openSource", "performance,audit,accessibility,seo", "npm i -g lighthouse",
     "Automated auditing for performance, accessibility, SEO and best practices.",
     "Автоматический аудит производительности, доступности, SEO и лучших практик.",
     "Run it in CI with a performance budget so a regression fails the build rather than shipping quietly."),
    ("lib-bundle-analyzer", "Rollup Plugin Visualizer", "Сборка и bundlers", "https://github.com/btd/rollup-plugin-visualizer", "openSource", "bundle-size,analysis,visualization,rollup", "npm i -D rollup-plugin-visualizer",
     "Visualizes bundle composition to find what is actually making your build large.",
     "Визуализирует состав бандла, чтобы найти, что реально раздувает сборку.",
     "Almost always reveals one unexpectedly large dependency — check before optimizing your own code."),
    ("lib-size-limit", "Size Limit", "Сборка и bundlers", "https://github.com/ai/size-limit", "openSource", "bundle-size,ci,budget,performance", "npm i -D size-limit",
     "Enforces a bundle size budget in CI, failing the build when it grows past a threshold.",
     "Обеспечивает бюджет размера бандла в CI, роняя сборку при превышении порога.",
     "Set the budget slightly above current size — a budget you constantly override stops meaning anything."),

    # ---------- Состояние и данные: client caching ----------
    ("lib-swr", "SWR", "Состояние и данные", "https://swr.vercel.app/docs/getting-started", "openSource", "data-fetching,react,cache,vercel", "npm i swr",
     "React data fetching with stale-while-revalidate caching, from Vercel.",
     "Загрузка данных в React с кэшированием stale-while-revalidate от Vercel.",
     "Lighter than TanStack Query; pick TanStack when you need mutations and complex cache invalidation."),
    ("lib-apollo-client", "Apollo Client", "Состояние и данные", "https://www.apollographql.com/docs/react", "openSource", "graphql,cache,react,normalized", "npm i @apollo/client",
     "GraphQL client with a normalized cache that updates related queries automatically.",
     "GraphQL-клиент с нормализованным кэшем, автоматически обновляющим связанные запросы.",
     "The normalized cache is powerful but subtle — read its identity rules before debugging stale UI."),
    ("lib-urql", "urql", "Состояние и данные", "https://commerce.nearform.com/open-source/urql/docs/", "openSource", "graphql,client,lightweight,exchanges", "npm i urql",
     "Lightweight, extensible GraphQL client, a simpler alternative to Apollo.",
     "Лёгкий расширяемый GraphQL-клиент, более простая альтернатива Apollo.",
     "Its document cache is easier to reason about than normalized caching for many applications."),
    ("lib-idb", "idb", "Состояние и данные", "https://github.com/jakearchibald/idb", "openSource", "indexeddb,promises,browser,storage", "npm i idb",
     "Tiny promise-based wrapper over IndexedDB.",
     "Крошечная обёртка над IndexedDB на промисах.",
     "Thinner than Dexie — pick it when you want IndexedDB with promises and nothing more."),
    ("lib-localforage", "localForage", "Состояние и данные", "https://localforage.github.io/localForage/", "openSource", "storage,offline,indexeddb,fallback", "npm i localforage",
     "Offline storage with a localStorage-like API backed by IndexedDB or WebSQL.",
     "Офлайн-хранилище с API в духе localStorage поверх IndexedDB или WebSQL.",
     "Unlike localStorage it stores structured data and is asynchronous, so it never blocks the main thread."),

    # ---------- Backend: performance/caching ----------
    ("lib-varnish", "Varnish Cache", "Облако и деплой", "https://varnish-cache.org/docs/", "openSource", "http-cache,reverse-proxy,performance,vcl", "",
     "HTTP accelerator caching responses in front of your application servers.",
     "HTTP-акселератор, кэширующий ответы перед серверами приложений.",
     "Its VCL configuration language is powerful but idiosyncratic — budget real time to learn it."),
    ("lib-memcached", "Memcached", "Состояние и данные", "https://memcached.org/", "openSource", "cache,memory,simple,distributed", "",
     "Simple distributed memory caching system for reducing database load.",
     "Простая распределённая система кэширования в памяти для снижения нагрузки на базу.",
     "Simpler than Redis, but with no persistence or data structures — pick Redis unless you specifically want minimal."),
    ("lib-granian", "Granian", "Backend и API", "https://github.com/emmett-framework/granian", "openSource", "python,asgi,rust,server", "pip install granian",
     "Rust-based HTTP server for Python ASGI and WSGI applications.",
     "HTTP-сервер на Rust для Python-приложений ASGI и WSGI.",
     "Worth benchmarking against Uvicorn on your own workload — the gap varies by application shape."),
    ("lib-gunicorn", "Gunicorn", "Backend и API", "https://docs.gunicorn.org/", "openSource", "python,wsgi,server,process-manager", "pip install gunicorn",
     "Python WSGI server and process manager, commonly fronting Uvicorn workers.",
     "WSGI-сервер и менеджер процессов Python, часто управляет воркерами Uvicorn.",
     "Set worker count from CPU cores, not arbitrarily — too many workers thrash memory without adding throughput."),
]
