# -*- coding: utf-8 -*-
"""Stage 5 MCP + skills pack D."""

MCPS_5D = [
    ("mcp-obsidian-community-2", "Obsidian REST MCP", "Память и знания", "https://github.com/MarkusPfundstein/mcp-obsidian", "openSource", "obsidian,notes,community,local", "uvx mcp-obsidian",
     "Reads and writes an Obsidian vault via the Local REST API community plugin.",
     "Чтение и запись хранилища Obsidian через community-плагин Local REST API.",
     "Requires the Local REST API plugin installed and enabled in Obsidian first — it is not a standalone server."),
    ("mcp-apple-notes", "Apple Notes MCP", "Память и знания", "https://github.com/sirmalloc/mcp-apple-notes", "openSource", "apple,notes,macos,community", "",
     "Reads and searches Apple Notes on macOS from an agent.",
     "Чтение и поиск заметок Apple Notes на macOS из агента.",
     "macOS-only, since it works through AppleScript automation against the local Notes app."),
    ("mcp-git-official", "Git MCP (official)", "Git и совместная работа", "https://github.com/modelcontextprotocol/servers/tree/main/src/git", "openSource", "git,local,official,reference", "uvx mcp-server-git",
     "Official reference server for local git operations: log, diff, status, commit.",
     "Официальный эталонный сервер для локальных git-операций: log, diff, status, commit.",
     "Read-only exploration (log, diff, show) is safe by default; think twice before enabling commit/push tools."),
    ("mcp-time-official", "Time MCP (official)", "Инфраструктура MCP", "https://github.com/modelcontextprotocol/servers/tree/main/src/time", "openSource", "time,timezone,official,reference", "uvx mcp-server-time",
     "Official reference server for current time and timezone conversion.",
     "Официальный эталонный сервер текущего времени и конвертации часовых поясов.",
     "Small and simple by design — useful mainly as a reference implementation for writing your own server."),
    ("mcp-everart", "EverArt MCP", "Изображения и дизайн", "https://github.com/modelcontextprotocol/servers-archived/tree/main/src/everart", "openSource", "image-generation,community,archived", "",
     "Community server for generating images through the EverArt API.",
     "Сервер сообщества для генерации изображений через API EverArt.",
     "Check the server is still maintained before depending on it — some early community servers are archived."),
    ("mcp-kagi-search", "Kagi Search MCP", "Инфраструктура MCP", "https://github.com/kagisearch/kagimcp", "paid", "search,kagi,privacy,official", "",
     "Official server for Kagi's privacy-respecting, ad-free search results.",
     "Официальный сервер для приватного поиска Kagi без рекламы.",
     "Requires an active paid Kagi subscription — there is no free tier for the search API itself."),
    ("mcp-wolfram-alpha", "Wolfram Alpha MCP", "Инфраструктура MCP", "https://github.com/wolfram-alpha/wolfram-mcp", "freeTier", "math,computation,wolfram,knowledge", "",
     "Computational knowledge engine for math, science and factual queries as an agent tool.",
     "Вычислительная система знаний для математики, науки и фактических запросов как инструмент агента.",
     "Reach for this specifically for symbolic math and unit conversions an LLM alone gets wrong."),
]

SKILLS_5D = [
    ("skill-claude-code-remote-execution", "Claude Code Remote Sessions", "Установка и миграция", "https://docs.claude.com/en/docs/claude-code/claude-code-on-the-web", "free", "claude-code,remote,cloud,web", "",
     "Running Claude Code sessions in the cloud from a browser instead of a local terminal.",
     "Запуск сессий Claude Code в облаке из браузера вместо локального терминала.",
     "Useful for kicking off a long task from a phone and checking back later — the session keeps running."),
    ("skill-claude-code-enterprise", "Claude Code for Enterprise", "Гайды и практики", "https://docs.claude.com/en/docs/claude-code/administration", "free", "claude-code,enterprise,admin,governance", "",
     "Managed deployment, spend controls and policy settings for organization-wide Claude Code use.",
     "Управляемое развёртывание, контроль расходов и настройки политик для Claude Code в организации.",
     "Set spend limits per team before a wide rollout — usage scales fast once many engineers adopt it."),
    ("skill-agent-sdk-typescript", "Claude Agent SDK (TypeScript)", "Создание skills", "https://docs.claude.com/en/api/agent-sdk/typescript", "free", "sdk,agents,typescript,claude", "npm i @anthropic-ai/claude-agent-sdk",
     "TypeScript bindings for the Claude Agent SDK, the same harness behind Claude Code.",
     "TypeScript-биндинги для Claude Agent SDK — того же harness, что и у Claude Code.",
     "Reuse Claude Code's own tool and permission model rather than reimplementing an agent loop from scratch."),
    ("skill-agent-sdk-python", "Claude Agent SDK (Python)", "Создание skills", "https://docs.claude.com/en/api/agent-sdk/python", "free", "sdk,agents,python,claude", "pip install claude-agent-sdk",
     "Python bindings for the Claude Agent SDK.",
     "Python-биндинги для Claude Agent SDK.",
     "Start from one of the SDK's example agents rather than an empty loop — most of the plumbing is already solved."),
]
