# -*- coding: utf-8 -*-
"""Stage 5 library pack BA: knowledge bases, note taking, team wikis, read-later and reference managers."""

LIBS_5BA = [
    # ---------- Личные базы знаний ----------
    ("lib-obsidian", "Obsidian", "Память и знания", "https://help.obsidian.md/", "freeTier", "markdown,local-first,plugins,linking", "",
     "Local-first knowledge base storing notes as plain Markdown files.",
     "Local-first база знаний, хранящая заметки обычными файлами Markdown.",
     "Your notes stay as files on disk, so no vendor shutdown can strand them."),
    ("lib-logseq", "Logseq", "Память и знания", "https://docs.logseq.com/", "openSource", "outliner,blocks,local-first,open-source", "",
     "Open-source outliner where every block is independently linkable.",
     "Открытый аутлайнер, где каждый блок можно связать отдельно.",
     "Block-level linking suits daily journaling far better than page-level tools."),
    ("lib-anytype", "Anytype", "Память и знания", "https://doc.anytype.io/", "openSource", "local-first,encrypted,objects,peer-to-peer", "",
     "Encrypted local-first workspace with peer-to-peer synchronization.",
     "Зашифрованное local-first рабочее пространство с одноранговой синхронизацией.",
     "End-to-end encryption means the sync server never sees your content at all."),
    ("lib-appflowy", "AppFlowy", "Память и знания", "https://docs.appflowy.io/", "openSource", "notion-alternative,rust,flutter,self-host", "",
     "Open-source Notion alternative built with Rust and Flutter.",
     "Открытая альтернатива Notion на Rust и Flutter.",
     "Self-hosting keeps team documents inside your own infrastructure."),
    ("lib-affine", "AFFiNE", "Память и знания", "https://docs.affine.pro/", "openSource", "docs,whiteboard,local-first,unified", "",
     "Workspace combining documents and an infinite whiteboard in one canvas.",
     "Рабочее пространство, объединяющее документы и бесконечную доску на одном холсте.",
     "Editing the same content as a document or as a diagram is genuinely unusual."),
    ("lib-trilium", "Trilium Notes", "Память и знания", "https://triliumnext.github.io/Docs/", "openSource", "hierarchical,self-host,scripting,notes", "",
     "Hierarchical note-taking application with scripting support.",
     "Иерархическое приложение для заметок с поддержкой скриптов.",
     "Its scripting turns a note collection into a small personal application."),
    ("lib-joplin", "Joplin", "Память и знания", "https://joplinapp.org/help/", "openSource", "markdown,encryption,sync,cross-platform", "",
     "Open-source note taking with end-to-end encrypted synchronization.",
     "Открытые заметки со сквозным шифрованием при синхронизации.",
     "It syncs through storage you already own, such as Dropbox or WebDAV."),
    ("lib-silverbullet", "SilverBullet", "Память и знания", "https://silverbullet.md/", "openSource", "markdown,self-host,queries,extensible", "",
     "Self-hosted Markdown notebook with an embedded query language.",
     "Self-hosted блокнот на Markdown со встроенным языком запросов.",
     "Querying across notes turns a note collection into a small structured database."),
    ("lib-dendron", "Dendron", "Память и знания", "https://wiki.dendron.so/", "openSource", "vscode,hierarchical,markdown,developer", "",
     "Hierarchical note taking built into VS Code.",
     "Иерархические заметки, встроенные в VS Code.",
     "Notes live beside code in the same editor, which suits developer documentation habits."),
    ("lib-foam", "Foam", "Память и знания", "https://foambubble.github.io/foam/", "openSource", "vscode,markdown,linking,free", "",
     "Personal knowledge management in VS Code using linked Markdown.",
     "Управление личными знаниями в VS Code через связанный Markdown.",
     "It is a set of extensions and conventions rather than an application, which keeps it portable."),

    # ---------- Командные вики ----------
    ("lib-outline", "Outline", "Документация и контекст", "https://docs.getoutline.com/", "openSource", "team-wiki,markdown,search,self-host", "",
     "Team knowledge base with fast search and a clean editor.",
     "Командная база знаний с быстрым поиском и понятным редактором.",
     "Its search is fast enough that people actually look things up rather than asking again."),
    ("lib-wikijs", "Wiki.js", "Документация и контекст", "https://docs.requarks.io/", "openSource", "wiki,self-host,markdown,git-sync", "",
     "Modern self-hosted wiki with optional Git synchronization.",
     "Современная self-hosted вики с опциональной синхронизацией через Git.",
     "Git sync means the wiki content is versioned and reviewable like any other repository."),
    ("lib-bookstack", "BookStack", "Документация и контекст", "https://www.bookstackapp.com/docs/", "openSource", "wiki,php,structured,simple", "",
     "Self-hosted documentation platform organized into books and chapters.",
     "Self-hosted платформа документации, организованная в книги и главы.",
     "Its fixed hierarchy is a feature — free-form wikis sprawl without one."),
    ("lib-docmost", "Docmost", "Документация и контекст", "https://docmost.com/docs", "openSource", "wiki,collaborative,real-time,self-host", "",
     "Open-source collaborative wiki with real-time editing.",
     "Открытая совместная вики с редактированием в реальном времени.",
     "Real-time collaboration is rare in self-hosted wikis, which usually lock pages instead."),

    # ---------- Чтение и справочные материалы ----------
    ("lib-zotero", "Zotero", "Книги и знания", "https://www.zotero.org/support/", "openSource", "references,citations,research,academic", "",
     "Reference manager for collecting and citing research sources.",
     "Менеджер источников для сбора и цитирования научных материалов.",
     "Its browser connector captures full citation metadata from a page in one click."),
    ("lib-readwise", "Readwise", "Книги и знания", "https://readwise.io/api_deets", "paid", "highlights,spaced-repetition,sync,reading", "",
     "Collects highlights from books and articles and resurfaces them over time.",
     "Собирает выделения из книг и статей и периодически возвращает их вам.",
     "Spaced resurfacing is what turns highlights into something you actually retain."),
    ("lib-raindrop-io", "Raindrop.io", "Книги и знания", "https://developer.raindrop.io/", "freeTier", "bookmarks,collections,search,cross-platform", "",
     "Bookmark manager with collections, tagging and full-text search.",
     "Менеджер закладок с коллекциями, тегами и полнотекстовым поиском.",
     "Its permanent copies keep the content readable after the original page disappears."),
    ("lib-wallabag", "wallabag", "Книги и знания", "https://doc.wallabag.org/", "openSource", "read-later,self-host,articles,php", "",
     "Self-hosted read-later service that saves article content.",
     "Self-hosted сервис отложенного чтения, сохраняющий содержимое статей.",
     "Self-hosting means your reading list is not a business model that can be discontinued."),
    ("lib-linkding", "linkding", "Книги и знания", "https://linkding.link/", "openSource", "bookmarks,self-host,minimal,fast", "",
     "Minimal self-hosted bookmark manager.",
     "Минималистичный self-hosted менеджер закладок.",
     "Small enough to run on a Raspberry Pi and fast enough to use constantly."),
    ("lib-karakeep", "Karakeep", "Книги и знания", "https://docs.karakeep.app/", "openSource", "bookmarks,ai-tagging,self-host,search", "",
     "Self-hosted bookmark manager with automatic AI tagging, formerly Hoarder.",
     "Self-hosted менеджер закладок с автоматической AI-разметкой, ранее Hoarder.",
     "Automatic tagging keeps a large collection navigable without manual filing."),
    ("lib-omnivore", "Omnivore", "Книги и знания", "https://github.com/omnivore-app/omnivore", "openSource", "read-later,archived,self-host,highlights", "",
     "Read-later application, now archived but self-hostable from source.",
     "Приложение отложенного чтения, теперь архивное, но разворачиваемое из исходников.",
     "The hosted service shut down — a useful reminder to prefer self-hostable reading tools."),
]
