# -*- coding: utf-8 -*-
# (iid, name, category, url, access, tags, summary_en, summary_ru, tip_en,
#  model, from_price, free_quota, pricing_url)
PAID_5B = [
("paid-drugbank","DrugBank (pricing)","Здоровье и медицина","https://go.drugbank.com/pricing","paid","drugs,pricing,pharmacology,license",
 "Licensed pharmacology database, quote-based pricing for commercial use.",
 "Лицензированная фармакологическая база данных, цена по запросу для коммерческого использования.",
 "Academic and non-commercial use has separate, much cheaper licensing — check eligibility before the commercial quote.",
 "subscription","custom license quote","free academic license available","https://go.drugbank.com/pricing"),
("paid-project44","project44 (pricing)","Логистика и доставка","https://www.project44.com/","paid","freight,visibility,pricing,enterprise",
 "Enterprise supply-chain visibility platform, quote-based pricing by shipment volume.",
 "Корпоративная платформа видимости цепочки поставок, цена по запросу за объём отгрузок.",
 "This is an enterprise sales process from the start — there is no self-serve trial to test against your lanes.",
 "subscription","custom quote by shipment volume","no public trial","https://www.project44.com/"),
("paid-middesk","Middesk (pricing)","Идентификация и KYC","https://www.middesk.com/","paid","kyb,pricing,business-verification,custom",
 "Business verification (KYB) checks priced per verification, volume-tiered.",
 "Проверки бизнеса (KYB) с оплатой за проверку, тарифы по объёму.",
 "Ask for sandbox access to test against known-good and known-bad business records before any commercial commitment.",
 "usage","custom per-verification pricing","sandbox available on request","https://www.middesk.com/"),
("paid-postmark-templates","Postmark (pricing)","Коммуникации","https://postmarkapp.com/pricing","paid","email,pricing,transactional,volume",
 "Transactional email priced per monthly email volume.",
 "Транзакционная почта с оплатой по месячному объёму писем.",
 "The 100-email free trial is enough to validate templates and deliverability setup before paying.",
 "subscription","from ~$15 per month (10k emails)","100 free emails to start","https://postmarkapp.com/pricing"),
("paid-kagi-search","Kagi Search (pricing)","Инфраструктура MCP","https://kagi.com/pricing","paid","search,pricing,privacy,subscription",
 "Ad-free search billed as a personal subscription, with an API extension for the same account.",
 "Поиск без рекламы по личной подписке с расширением API для того же аккаунта.",
 "The free trial searches are enough to judge result quality before committing to a monthly plan.",
 "subscription","from ~$10 per month","free trial searches","https://kagi.com/pricing"),
]
