# -*- coding: utf-8 -*-
"""Stage 5 library pack AC: LLM programming, evaluation, agent frameworks, memory, parsing."""

LIBS_5AC = [
    # ---------- Программирование LLM ----------
    ("lib-baml", "BAML", "AI-фреймворки", "https://docs.boundaryml.com/", "openSource", "structured-output,schema,typed,codegen", "",
     "Schema language for LLM functions that generates typed clients in several languages.",
     "Язык схем для LLM-функций, генерирующий типизированные клиенты на нескольких языках.",
     "Its parser recovers usable data from slightly malformed model output instead of failing outright."),
    ("lib-marvin", "Marvin", "AI-фреймворки", "https://askmarvin.ai/", "openSource", "python,structured,functions,pydantic", "pip install marvin",
     "Turns ordinary Python functions into LLM-backed ones with typed results.",
     "Превращает обычные Python-функции в функции на основе LLM с типизированными результатами.",
     "Decorating a function with a type signature is often all the prompt engineering a simple task needs."),
    ("lib-mirascope", "Mirascope", "AI-фреймворки", "https://mirascope.com/docs/mirascope", "openSource", "python,provider-agnostic,typed,prompts", "pip install mirascope",
     "Provider-agnostic LLM library keeping prompts as ordinary typed Python code.",
     "Библиотека LLM вне привязки к провайдеру, хранящая промпты как обычный типизированный Python-код.",
     "Prompts stay normal functions, so your existing editor tooling and tests apply unchanged."),
    ("lib-magentic", "Magentic", "AI-фреймворки", "https://magentic.dev/", "openSource", "python,decorators,structured,streaming", "pip install magentic",
     "Integrates LLM calls into Python code through simple function decorators.",
     "Встраивает вызовы LLM в Python-код через простые декораторы функций.",
     "Streaming structured output arrives as a typed iterator rather than a string you parse later."),
    ("lib-portkey", "Portkey", "AI-фреймворки", "https://portkey.ai/docs", "freeTier", "gateway,routing,fallbacks,observability", "",
     "AI gateway adding routing, retries, caching and observability across providers.",
     "AI-шлюз с маршрутизацией, повторами, кэшированием и наблюдаемостью между провайдерами.",
     "Automatic fallback to a second provider turns an outage into added latency rather than downtime."),

    # ---------- Оценка и наблюдаемость LLM ----------
    ("lib-trulens", "TruLens", "AI-оценка и safety", "https://www.trulens.org/", "openSource", "evaluation,rag,feedback-functions,tracking", "pip install trulens",
     "Evaluates LLM applications using programmable feedback functions.",
     "Оценивает LLM-приложения с помощью программируемых функций обратной связи.",
     "Its RAG triad (context relevance, groundedness, answer relevance) is a solid default starting metric set."),
    ("lib-deepeval", "DeepEval", "AI-оценка и safety", "https://deepeval.com/docs/getting-started", "openSource", "evaluation,pytest,metrics,unit-tests", "pip install deepeval",
     "LLM evaluation framework shaped like a unit testing library.",
     "Фреймворк оценки LLM, оформленный как библиотека модульного тестирования.",
     "Running evals as pytest cases puts them in CI, where they actually get run on every change."),
    ("lib-arize-phoenix", "Phoenix", "AI-оценка и safety", "https://arize.com/docs/phoenix", "openSource", "tracing,evaluation,opentelemetry,notebooks", "pip install arize-phoenix",
     "Open-source LLM tracing and evaluation that runs locally in a notebook or container.",
     "Открытая трассировка и оценка LLM, работающая локально в ноутбуке или контейнере.",
     "Built on OpenTelemetry, so traces flow to your existing observability backend as well."),
    ("lib-langwatch", "LangWatch", "AI-оценка и safety", "https://docs.langwatch.ai/", "freeTier", "monitoring,evaluation,quality,pipelines", "",
     "Monitoring and evaluation platform for LLM applications in production.",
     "Платформа мониторинга и оценки LLM-приложений в продакшне.",
     "Its optimization studio runs DSPy-style prompt tuning against your own collected traces."),
    ("lib-opik", "Opik", "AI-оценка и safety", "https://www.comet.com/docs/opik/", "openSource", "tracing,evaluation,self-host,comet", "pip install opik",
     "Open-source LLM tracing and evaluation from the Comet team.",
     "Открытая трассировка и оценка LLM от команды Comet.",
     "Self-hostable in full, which matters when prompts and outputs contain regulated data."),
    ("lib-agenta", "Agenta", "AI-оценка и safety", "https://docs.agenta.ai/", "openSource", "prompt-management,evaluation,playground,versioning", "",
     "Open-source platform for prompt versioning, evaluation and collaborative playgrounds.",
     "Открытая платформа для версионирования промптов, оценки и совместных playground.",
     "Lets non-engineers iterate on prompts without a deploy, while keeping versions under control."),
    ("lib-promptlayer", "PromptLayer", "AI-оценка и safety", "https://docs.promptlayer.com/introduction", "freeTier", "prompt-management,logging,versioning,registry", "",
     "Prompt registry and request logging with visual prompt editing.",
     "Реестр промптов и логирование запросов с визуальным редактированием промптов.",
     "Decoupling prompts from code lets you fix a bad prompt without shipping a release."),
    ("lib-humanloop", "Humanloop", "AI-оценка и safety", "https://humanloop.com/docs", "paid", "evaluation,prompt-management,collaboration,enterprise", "",
     "Enterprise LLM development platform for prompt management and evaluation workflows.",
     "Корпоративная платформа разработки LLM для управления промптами и процессов оценки.",
     "Built around domain experts reviewing outputs, not just engineers reading eval scores."),
    ("lib-vellum", "Vellum", "AI-оценка и safety", "https://docs.vellum.ai/", "paid", "workflows,evaluation,prompt-management,visual", "",
     "Visual workflow builder and evaluation platform for production LLM features.",
     "Визуальный конструктор workflow и платформа оценки для продакшн-функций на LLM.",
     "Its visual builder suits teams where product managers own the LLM logic alongside engineers."),

    # ---------- Агентные фреймворки ----------
    ("lib-atomic-agents", "Atomic Agents", "AI и агенты", "https://brainblend-ai.github.io/atomic-agents/", "openSource", "modular,schema-driven,lightweight,composable", "pip install atomic-agents",
     "Modular agent framework built from small schema-defined, individually testable components.",
     "Модульный агентный фреймворк из небольших компонентов со схемами, тестируемых по отдельности.",
     "Deliberately avoids hidden orchestration, which makes agent behaviour debuggable step by step."),
    ("lib-strands-agents", "Strands Agents", "AI и агенты", "https://strandsagents.com/latest/documentation/docs/", "openSource", "aws,model-driven,tools,lightweight", "pip install strands-agents",
     "AWS's model-driven agent SDK where the model plans and calls tools directly.",
     "Model-driven SDK агентов от AWS, где модель сама планирует и вызывает инструменты.",
     "Relies on the model's own reasoning rather than a hardcoded graph, which keeps the code very small."),
    ("lib-google-adk", "Google Agent Development Kit", "AI и агенты", "https://google.github.io/adk-docs/", "openSource", "google,agents,multi-agent,evaluation", "pip install google-adk",
     "Google's toolkit for building, evaluating and deploying multi-agent systems.",
     "Набор инструментов Google для создания, оценки и развёртывания мультиагентных систем.",
     "Ships with an evaluation harness, which most agent frameworks leave entirely to you."),
    ("lib-letta", "Letta", "Память и знания", "https://docs.letta.com/", "openSource", "memory,stateful,agents,memgpt", "pip install letta",
     "Stateful agents with self-editing long-term memory, formerly MemGPT.",
     "Агенты с состоянием и самостоятельно редактируемой долговременной памятью, ранее MemGPT.",
     "The agent decides what to keep in memory itself, rather than you tuning a retrieval pipeline."),
    ("lib-cognee", "Cognee", "Память и знания", "https://docs.cognee.ai/", "openSource", "memory,knowledge-graph,rag,pipelines", "pip install cognee",
     "Builds a knowledge graph memory layer for agents from unstructured input.",
     "Строит слой памяти в виде графа знаний для агентов из неструктурированных данных.",
     "Graph memory answers relational questions that flat vector retrieval consistently gets wrong."),
    ("lib-graphiti", "Graphiti", "Память и знания", "https://help.getzep.com/graphiti/", "openSource", "temporal,knowledge-graph,memory,agents", "pip install graphiti-core",
     "Temporal knowledge graph tracking how facts about entities change over time.",
     "Временной граф знаний, отслеживающий изменение фактов о сущностях во времени.",
     "Recording when a fact stopped being true is what keeps an agent from repeating stale information."),

    # ---------- Подготовка документов ----------
    ("lib-unstructured", "Unstructured", "Поиск и retrieval", "https://docs.unstructured.io/", "mixed", "parsing,documents,ingestion,rag", "pip install unstructured",
     "Extracts and chunks text from PDFs, Office files, HTML and images for RAG pipelines.",
     "Извлекает и разбивает на чанки текст из PDF, файлов Office, HTML и изображений для RAG-пайплайнов.",
     "Its element types (title, table, narrative) let you chunk by structure rather than character count."),
    ("lib-chonkie", "Chonkie", "Поиск и retrieval", "https://docs.chonkie.ai/", "openSource", "chunking,rag,lightweight,strategies", "pip install chonkie",
     "Lightweight library implementing many text chunking strategies for RAG.",
     "Лёгкая библиотека, реализующая множество стратегий разбиения текста для RAG.",
     "Chunking strategy affects retrieval quality more than embedding model choice in most pipelines."),
    ("lib-markitdown", "MarkItDown", "Документы и PDF", "https://github.com/microsoft/markitdown", "openSource", "conversion,markdown,microsoft,llm-ready", "pip install markitdown",
     "Microsoft's converter turning Office documents, PDFs and more into Markdown for LLMs.",
     "Конвертер Microsoft, превращающий документы Office, PDF и другие форматы в Markdown для LLM.",
     "Markdown preserves headings and tables, which plain text extraction destroys and retrieval needs."),
    ("lib-llamaparse", "LlamaParse", "Документы и PDF", "https://docs.cloud.llamaindex.ai/llamaparse/getting_started", "freeTier", "pdf,parsing,tables,rag", "",
     "Document parsing service tuned for complex PDFs with tables and multi-column layouts.",
     "Сервис разбора документов, настроенный на сложные PDF с таблицами и многоколоночной вёрсткой.",
     "Its free daily page allowance is enough to evaluate it properly against your own difficult documents."),
    ("lib-reducto", "Reducto", "Документы и PDF", "https://docs.reducto.ai/", "paid", "document-parsing,tables,accuracy,enterprise", "",
     "High-accuracy document parsing aimed at complex financial and scientific documents.",
     "Высокоточный разбор документов для сложных финансовых и научных материалов.",
     "Priced per page and aimed at cases where a parsing error carries real financial consequence."),
]
