# -*- coding: utf-8 -*-
"""Stage 5 API pack F: insurance, agriculture, energy, more web3, more documents."""

APIS_5F = [
    # ---------- Web3 и блокчейн (deepen) ----------
    ("api-quicknode", "QuickNode", "Web3 и блокчейн", "https://www.quicknode.com/docs/welcome", "freeTier", "web3,rpc,nodes,multi-chain", "",
     "Managed blockchain node infrastructure across many chains, an Alchemy alternative.",
     "Управляемая инфраструктура блокчейн-нод для многих сетей — альтернатива Alchemy.",
     "Compare chain coverage directly against Alchemy — support varies for less mainstream chains."),
    ("api-the-graph", "The Graph", "Web3 и блокчейн", "https://thegraph.com/docs/", "freeTier", "web3,indexing,graphql,subgraphs", "",
     "Decentralized indexing protocol for querying blockchain data via GraphQL subgraphs.",
     "Децентрализованный протокол индексации для запросов к блокчейн-данным через GraphQL-сабграфы.",
     "Check the Subgraph Studio for an existing subgraph before writing and deploying your own."),
    ("api-moralis", "Moralis", "Web3 и блокчейн", "https://docs.moralis.com/", "freeTier", "web3,api,nft,multi-chain", "",
     "Web3 data API: wallet balances, NFTs and transaction history across chains, no node required.",
     "Web3 data API: балансы кошельков, NFT и история транзакций по сетям без своей ноды.",
     "It abstracts away raw RPC calls entirely — reach for it before standing up your own indexer."),
    ("api-walletconnect", "WalletConnect", "Web3 и блокчейн", "https://docs.walletconnect.com/", "openSource", "web3,wallet,connection,protocol", "npm i @walletconnect/web3wallet",
     "Open protocol connecting wallets to dapps via QR code or deep link, chain-agnostic.",
     "Открытый протокол подключения кошельков к dapp через QR-код или deep link, не зависит от сети.",
     "It is the de facto standard for wallet connection — support it even if you also support browser-injected wallets."),
    ("api-covalent", "Covalent (GoldRush)", "Web3 и блокчейн", "https://goldrush.dev/docs/", "freeTier", "web3,data,multi-chain,unified-api", "",
     "Unified API for blockchain data across 200+ chains: balances, transactions, NFTs.",
     "Единый API блокчейн-данных для 200+ сетей: балансы, транзакции, NFT.",
     "One consistent schema across every supported chain removes the need to write per-chain parsers."),

    # ---------- Инфраструктура MCP (bonus hosted directory tools) ----------
    ("api-smithery-registry", "Smithery", "Инфраструктура MCP", "https://smithery.ai/docs", "free", "mcp,registry,discovery,directory", "",
     "Registry and hosting for discovering and deploying MCP servers.",
     "Реестр и хостинг для поиска и деплоя MCP-серверов.",
     "Hosted deployment removes the need to run a server process yourself for simple stdio servers."),

    # ---------- Здоровье и медицина (deepen further) ----------
    ("api-nutritionvalue", "USDA FoodData Central (SR Legacy)", "Здоровье и медицина", "https://fdc.nal.usda.gov/", "free", "nutrition,food,usda,reference", "",
     "The reference USDA nutrient database, an alternative dataset within FoodData Central.",
     "Эталонная база нутриентов USDA — альтернативный датасет внутри FoodData Central.",
     "SR Legacy has cleaner per-100g values than the Branded Foods dataset for whole-food nutrition lookups."),
    ("api-drugbank", "DrugBank", "Здоровье и медицина", "https://docs.drugbank.com/", "paid", "drugs,pharmacology,interactions,medical", "",
     "Detailed drug data: interactions, mechanisms, targets and pharmacology.",
     "Подробные данные о лекарствах: взаимодействия, механизмы, мишени, фармакология.",
     "This is reference data for building tools, not a substitute for pharmacist or physician guidance."),
    ("api-fitbit-api", "Fitbit Web API", "Здоровье и медицина", "https://dev.fitbit.com/build/reference/web-api/", "free", "fitness,wearables,health,activity", "",
     "Activity, sleep and heart-rate data from Fitbit devices via OAuth.",
     "Данные активности, сна и пульса с устройств Fitbit через OAuth.",
     "Intraday data (minute-by-minute) needs a separate application-level approval beyond basic OAuth."),
    ("api-apple-healthkit", "Apple HealthKit", "Здоровье и медицина", "https://developer.apple.com/documentation/healthkit", "free", "health,ios,wearables,apple", "",
     "On-device health and fitness data store for iOS, not a network API.",
     "Локальное хранилище данных здоровья и активности для iOS, не сетевой API.",
     "Data never leaves the device unless your app explicitly exports it — plan the permission UX carefully."),

    # ---------- Финансы: страхование (Юридические/страхование под data-group) ----------
    ("api-shipwell", "Shipwell", "Логистика и доставка", "https://developer.shipwell.com/", "mixed", "freight,logistics,tms,shipping", "",
     "Freight transportation management: quoting, booking and tracking for shippers.",
     "Управление грузоперевозками: расчёт стоимости, бронирование и трекинг для грузоотправителей.",
     "Rate quoting across multiple carriers in one call is the main efficiency win over calling carriers directly."),
    ("api-project44", "project44", "Логистика и доставка", "https://developer.project44.com/", "paid", "freight,visibility,supply-chain,tracking", "",
     "Real-time supply chain visibility across ocean, air, rail and truck freight.",
     "Видимость цепочки поставок в реальном времени: море, воздух, ж/д и автоперевозки.",
     "Coverage depth varies heavily by carrier and mode — validate your specific lanes before committing."),

    # ---------- Data engineering (deepen further) ----------
    ("api-snowflake", "Snowflake", "Data engineering", "https://docs.snowflake.com/en/developer-guide/sql-api/index", "mixed", "warehouse,sql,cloud,scaling", "",
     "Cloud data warehouse with separate storage/compute scaling and a SQL REST API.",
     "Облачное хранилище данных с раздельным масштабированием хранения и вычислений и SQL REST API.",
     "Suspend warehouses when idle — compute is billed by the second and adds up fast if left running."),
    ("api-bigquery", "Google BigQuery", "Data engineering", "https://cloud.google.com/bigquery/docs/reference/rest", "mixed", "warehouse,sql,google,serverless", "",
     "Serverless data warehouse billed per query, with a REST and client-library API.",
     "Serverless хранилище данных с оплатой за запрос, REST и клиентские библиотеки.",
     "Query cost is billed by data scanned — select only needed columns instead of SELECT * on large tables."),
    ("api-databricks", "Databricks", "Data engineering", "https://docs.databricks.com/en/dev-tools/index.html", "mixed", "spark,lakehouse,ml,notebooks", "",
     "Unified data and AI platform combining Spark processing, a lakehouse and ML tooling.",
     "Единая платформа данных и ИИ, объединяющая Spark, lakehouse и ML-инструменты.",
     "The free Community Edition is enough to learn Spark and notebooks before touching a paid workspace."),
    ("api-clickhouse-cloud-2", "ClickHouse Cloud", "Data engineering", "https://clickhouse.com/docs/en/cloud/overview", "freeTier", "analytics,olap,columnar,managed", "",
     "Managed columnar analytics database that stays fast at billions of rows.",
     "Управляемая колоночная аналитическая база данных, остаётся быстрой при миллиардах строк.",
     "Its free trial credit is enough to benchmark real query patterns before committing to a plan."),

    # ---------- IoT и встраиваемые системы (deepen) ----------
    ("api-particle-io", "Particle", "IoT и встраиваемые системы", "https://docs.particle.io/", "freeTier", "iot,hardware,cellular,cloud", "",
     "IoT hardware plus a cloud platform for device management and firmware OTA updates.",
     "IoT-железо плюс облачная платформа для управления устройствами и OTA-обновлений прошивки.",
     "The free tier covers a handful of devices — enough to prototype before committing to fleet pricing."),
    ("api-aws-iot-core", "AWS IoT Core", "IoT и встраиваемые системы", "https://docs.aws.amazon.com/iot/", "mixed", "iot,aws,mqtt,device-management", "",
     "Managed MQTT broker and device management for connecting IoT fleets to AWS.",
     "Управляемый MQTT-брокер и управление устройствами для подключения IoT-парков к AWS.",
     "Device Shadows let you read/write desired device state even while the device itself is offline."),
    ("api-balena", "balena", "IoT и встраиваемые системы", "https://docs.balena.io/", "freeTier", "iot,fleet,docker,deployment", "",
     "Fleet management for IoT devices running containerized applications.",
     "Управление парком IoT-устройств, работающих на контейнеризованных приложениях.",
     "Push a Docker image once and it rolls out to the whole device fleet — no manual per-device flashing."),

    # ---------- Игровые движки (deepen) ----------
    ("api-playcanvas", "PlayCanvas", "Игровые движки", "https://developer.playcanvas.com/", "freeTier", "webgl,game-engine,browser,collaborative", "",
     "WebGL game engine with a real-time collaborative browser editor.",
     "WebGL-движок для игр с совместным браузерным редактором в реальном времени.",
     "Games run directly in a browser tab with no install step, which is the whole point of picking it."),
    ("api-construct-3", "Construct 3", "Игровые движки", "https://www.construct.net/en/make-games/manuals/construct-3", "freeTier", "no-code,game-engine,2d,browser", "",
     "No-code 2D game engine with a visual event system, runs entirely in the browser.",
     "No-code 2D игровой движок с визуальной системой событий, работает прямо в браузере.",
     "The event sheet system covers surprisingly complex game logic without writing a line of code."),

    # ---------- Планирование и календари (deepen) ----------
    ("api-outlook-calendar", "Microsoft Graph Calendar API", "Планирование и календари", "https://learn.microsoft.com/graph/api/resources/calendar", "free", "calendar,outlook,microsoft,events", "",
     "Read and write Outlook/Microsoft 365 calendar events via Microsoft Graph.",
     "Чтение и запись событий календаря Outlook/Microsoft 365 через Microsoft Graph.",
     "Delta queries let you sync only what changed since the last check, instead of refetching everything."),
    ("api-savvycal", "SavvyCal", "Планирование и календари", "https://developer.savvycal.com/", "freeTier", "scheduling,calendar,booking,api", "",
     "Scheduling links API with an emphasis on a more considerate booking experience than typical tools.",
     "API ссылок для планирования с акцентом на более деликатный опыт бронирования, чем у типичных инструментов.",
     "Overlay links let an invitee see your link on top of their own calendar during scheduling."),
]
