# -*- coding: utf-8 -*-
"""Stage 5 pricing pack H: subscription billing, usage metering, experimentation platforms."""

PAID_5H = [
("paid-stripe-billing","Stripe Billing (pricing)","Платежи и commerce","https://stripe.com/billing/pricing","paid","subscriptions,pricing,percentage,volume",
 "Subscription billing charged as a percentage of recurring revenue, on top of payment fees.",
 "Биллинг подписок с оплатой в процентах от регулярной выручки поверх комиссий за платежи.",
 "The billing percentage stacks on the processing fee — model both when comparing to a flat-fee platform.",
 "usage","from ~0.5% of billing volume","free on the starter tier","https://stripe.com/billing/pricing"),
("paid-chargebee","Chargebee (pricing)","Платежи и commerce","https://www.chargebee.com/pricing/","paid","subscriptions,pricing,revenue-share,subscription",
 "Subscription management billed as a monthly fee plus a share of billing volume above a threshold.",
 "Управление подписками с месячной платой плюс долей от объёма биллинга сверх порога.",
 "Free below a revenue threshold, which covers early products entirely.",
 "subscription","free under ~$250k annual revenue, then from ~$599 per month","free starter tier","https://www.chargebee.com/pricing/"),
("paid-recurly","Recurly (pricing)","Платежи и commerce","https://recurly.com/pricing/","paid","subscriptions,pricing,revenue-share,platform-fee",
 "Subscription billing with a monthly platform fee plus a percentage of revenue.",
 "Биллинг подписок с месячной платой за платформу плюс процентом от выручки.",
 "Its revenue percentage makes it expensive at scale relative to fixed-fee alternatives.",
 "subscription","from ~$249 per month","free trial","https://recurly.com/pricing/"),
("paid-orb-billing","Orb (pricing)","Платежи и commerce","https://www.withorb.com/pricing","paid","usage-based,pricing,platform-fee,custom",
 "Usage-based billing engine sold as a platform fee scaled to billed volume.",
 "Движок биллинга по потреблению с платой за платформу, масштабируемой под объём выставленных счетов.",
 "Aimed at consumption products where pricing logic is too complex for Stripe Billing alone.",
 "custom","custom quote","product demo","https://www.withorb.com/pricing"),
("paid-metronome","Metronome (pricing)","Платежи и commerce","https://metronome.com/pricing","paid","usage-based,pricing,enterprise,volume",
 "Real-time usage billing sold on enterprise contracts scaled to billed volume.",
 "Биллинг потребления в реальном времени по корпоративным контрактам, масштабируемым под объём.",
 "Its real-time balances suit products where customers need to watch spend as it accrues.",
 "custom","custom quote","product demo","https://metronome.com/pricing"),
("paid-eppo","Eppo (pricing)","A/B-тестирование","https://www.geteppo.com/pricing","paid","experimentation,pricing,warehouse,custom",
 "Warehouse-native experimentation sold on annual contracts.",
 "Эксперименты на базе хранилища данных по годовым контрактам.",
 "Compute runs in your own warehouse, so factor that query cost in alongside the licence.",
 "custom","custom quote","product demo","https://www.geteppo.com/pricing"),
("paid-amplitude-experiment","Amplitude Experiment (pricing)","A/B-тестирование","https://amplitude.com/pricing","paid","experimentation,pricing,mtu,add-on",
 "Experimentation sold as an add-on to Amplitude, priced by tracked users.",
 "Эксперименты как дополнение к Amplitude с ценой по числу отслеживаемых пользователей.",
 "Only worth it if you already run Amplitude analytics — standalone it is poor value.",
 "custom","custom quote (by monthly tracked users)","free analytics tier","https://amplitude.com/pricing"),
("paid-ab-tasty","AB Tasty (pricing)","A/B-тестирование","https://www.abtasty.com/pricing/","paid","experimentation,pricing,traffic,annual",
 "Experimentation and personalization priced by monthly tested traffic.",
 "Эксперименты и персонализация с ценой по объёму тестируемого трафика в месяц.",
 "Traffic-based pricing means a high-volume site pays substantially more for the same feature set.",
 "custom","custom quote (by monthly traffic)","product demo","https://www.abtasty.com/pricing/"),
("paid-convert-com","Convert.com (pricing)","A/B-тестирование","https://www.convert.com/pricing/","paid","ab-testing,pricing,tested-users,subscription",
 "A/B testing billed monthly by the number of tested visitors.",
 "A/B-тестирование с месячной оплатой по числу протестированных посетителей.",
 "Published transparent pricing, unlike most enterprise experimentation vendors.",
 "subscription","from ~$99 per month","free trial","https://www.convert.com/pricing/"),
("paid-kameleoon","Kameleoon (pricing)","A/B-тестирование","https://www.kameleoon.com/pricing","paid","experimentation,pricing,traffic,custom",
 "Experimentation and personalization sold on contracts scaled to traffic.",
 "Эксперименты и персонализация по контрактам, масштабируемым под трафик.",
 "Bundling flags and experiments can replace two separate subscriptions, which changes the comparison.",
 "custom","custom quote","free trial","https://www.kameleoon.com/pricing"),
("paid-aws-appconfig","AWS AppConfig (pricing)","Feature flags и эксперименты","https://aws.amazon.com/systems-manager/pricing/","paid","aws,pricing,per-request,configuration",
 "Configuration delivery billed per configuration request and per deployment.",
 "Доставка конфигурации с оплатой за запрос конфигурации и за развёртывание.",
 "Cache configuration in the application — polling it per request makes the bill grow quickly.",
 "usage","from ~$0.0000002 per configuration request","free tier of requests","https://aws.amazon.com/systems-manager/pricing/"),
("paid-turbopuffer","turbopuffer (pricing)","Векторные базы","https://turbopuffer.com/pricing","paid","vector,pricing,storage,queries",
 "Vector search billed by stored data volume plus queries, on object-storage economics.",
 "Векторный поиск с оплатой по объёму хранимых данных и запросам на экономике объектного хранилища.",
 "Far cheaper per stored vector than memory-resident databases, with higher latency on cold namespaces.",
 "usage","from ~$0.33 per GB-month stored","free trial credit","https://turbopuffer.com/pricing"),
]
