# -*- coding: utf-8 -*-
"""Stage 5 API pack K: no-code/automation, chat/support, social, misc consumer APIs."""

APIS_5K = [
    # ---------- Разработка и DevOps: automation platforms ----------
    ("api-make-com", "Make (Integromat)", "Разработка и DevOps", "https://developers.make.com/api-documentation", "freeTier", "automation,no-code,workflows,integrations", "",
     "Visual workflow automation connecting hundreds of apps, with its own REST API.",
     "Визуальная автоматизация workflow, соединяющая сотни приложений, со своим REST API.",
     "Its visual scenario builder handles branching and error paths better than most no-code competitors."),
    ("api-pipedream", "Pipedream", "Разработка и DevOps", "https://pipedream.com/docs/", "freeTier", "automation,serverless,code,integrations", "",
     "Workflow automation where each step can be arbitrary Node/Python code, not just presets.",
     "Автоматизация workflow, где каждый шаг может быть произвольным кодом Node/Python, а не только пресетом.",
     "The code-step escape hatch is why it fits developers better than purely visual automation tools."),
    ("api-windmill", "Windmill", "Разработка и DevOps", "https://www.windmill.dev/docs/intro", "openSource", "automation,scripts,self-host,workflows", "",
     "Open-source developer platform turning scripts into workflows, UIs and cron jobs.",
     "Открытая платформа для разработчиков, превращающая скрипты в workflow, интерфейсы и cron-задачи.",
     "Self-hostable alternative to Retool plus Airflow in one, if you want both internal tools and job scheduling."),
    ("api-trigger-dev", "Trigger.dev", "Очереди и события", "https://trigger.dev/docs", "openSource", "background-jobs,typescript,workflows,durable", "npx trigger.dev@latest init",
     "Durable background jobs for TypeScript with no timeouts and built-in retries.",
     "Устойчивые фоновые задачи для TypeScript без таймаутов и со встроенными повторами.",
     "Long-running tasks survive deploys, which is the main advantage over plain serverless functions."),
    ("api-retool", "Retool", "Разработка и DevOps", "https://docs.retool.com/", "freeTier", "internal-tools,low-code,admin,dashboards", "",
     "Build internal admin tools and dashboards by dragging components onto queries.",
     "Сборка внутренних админ-инструментов и дашбордов перетаскиванием компонентов на запросы.",
     "Its value is skipping a CRUD admin UI entirely — do not use it for customer-facing product surfaces."),
    ("api-appsmith", "Appsmith", "Разработка и DevOps", "https://docs.appsmith.com/", "openSource", "internal-tools,low-code,self-host,admin", "",
     "Open-source, self-hostable internal tool builder, a Retool alternative.",
     "Открытый self-hosted конструктор внутренних инструментов, альтернатива Retool.",
     "Self-hosting matters here specifically because internal tools usually touch production databases directly."),
    ("api-budibase", "Budibase", "Разработка и DevOps", "https://docs.budibase.com/", "openSource", "low-code,internal-tools,self-host,forms", "",
     "Open-source low-code platform for internal apps, with a built-in database option.",
     "Открытая low-code платформа для внутренних приложений со встроенной опцией базы данных.",
     "It can host its own data, unlike tools that require you to bring an existing database."),

    # ---------- Коммуникации: support/chat ----------
    ("api-intercom", "Intercom API", "Коммуникации", "https://developers.intercom.com/docs/references/introduction/", "paid", "support,chat,messaging,crm", "",
     "Customer messaging and support platform API: conversations, contacts, help center.",
     "API платформы клиентских сообщений и поддержки: разговоры, контакты, база знаний.",
     "Webhooks on conversation events replace polling for new customer messages entirely."),
    ("api-crisp-chat", "Crisp", "Коммуникации", "https://docs.crisp.chat/", "freeTier", "chat,support,livechat,widget", "",
     "Live chat and customer support platform with a genuinely free starting tier.",
     "Платформа живого чата и поддержки клиентов с реально бесплатным стартовым тарифом.",
     "The free tier includes the chat widget and two seats — enough for a solo product's support channel."),
    ("api-chatwoot", "Chatwoot", "Коммуникации", "https://www.chatwoot.com/docs/product/", "openSource", "support,chat,omnichannel,self-host", "",
     "Open-source customer engagement suite, a self-hostable Intercom alternative.",
     "Открытый набор инструментов взаимодействия с клиентами, self-hosted альтернатива Intercom.",
     "Self-hosting removes per-seat pricing, which is the main cost driver for support tools as teams grow."),
    ("api-front-app", "Front API", "Коммуникации", "https://dev.frontapp.com/", "paid", "email,shared-inbox,collaboration,support", "",
     "Shared inbox and team collaboration API for customer-facing email.",
     "API общего почтового ящика и командной работы для клиентской переписки.",
     "Its API models conversations rather than individual emails, which fits team-based support workflows better."),

    # ---------- Новости и сообщества (deepen) ----------
    ("api-devto", "DEV.to API", "Новости и сообщества", "https://developers.forem.com/api", "free", "blogging,articles,devto,forem", "",
     "Publish and read articles on DEV.to and other Forem-powered communities.",
     "Публикация и чтение статей на DEV.to и других сообществах на Forem.",
     "Cross-post from your own blog with a canonical_url so search engines credit your site, not DEV.to."),
    ("api-hashnode", "Hashnode API", "Новости и сообщества", "https://apidocs.hashnode.com/", "free", "blogging,graphql,developers,publishing", "",
     "GraphQL API for the Hashnode developer blogging platform.",
     "GraphQL API для платформы блогов для разработчиков Hashnode.",
     "Its GraphQL schema makes fetching exactly the post fields you need straightforward, unlike REST blog APIs."),
    ("api-lemmy", "Lemmy API", "Новости и сообщества", "https://join-lemmy.org/docs/contributors/04-api.html", "openSource", "fediverse,forum,reddit-alternative,federated", "",
     "API for Lemmy, the federated link-aggregator and Reddit alternative.",
     "API Lemmy — федеративного агрегатора ссылок и альтернативы Reddit.",
     "Each instance federates independently — pick a home instance before building against the API."),

    # ---------- Переводы и языки (deepen) ----------
    ("api-deepl-2", "DeepL API", "Переводы и языки", "https://developers.deepl.com/docs", "freeTier", "translation,quality,formality,glossary", "",
     "Machine translation widely regarded as higher quality than alternatives for European languages.",
     "Машинный перевод, широко признанный более качественным для европейских языков.",
     "Glossaries let you pin product names and domain terms so they stay untranslated consistently."),
    ("api-google-translate-2", "Google Cloud Translation v3", "Переводы и языки", "https://cloud.google.com/translate/docs/reference/rest", "mixed", "translation,google,batch,glossary", "",
     "Google's translation API with batch translation and custom glossary support.",
     "API перевода Google с пакетным переводом и поддержкой пользовательских глоссариев.",
     "Batch translation of documents in Cloud Storage is far cheaper per word than per-request calls."),
    ("api-modernmt", "ModernMT", "Переводы и языки", "https://www.modernmt.com/api/", "mixed", "translation,adaptive,context,mt", "",
     "Adaptive machine translation that learns from corrections in real time.",
     "Адаптивный машинный перевод, обучающийся на исправлениях в реальном времени.",
     "Feeding back post-edited translations improves subsequent output within the same session."),

    # ---------- Словари и лексика (deepen) ----------
    ("api-wordsapi", "WordsAPI", "Словари и лексика", "https://www.wordsapi.com/docs/", "freeTier", "dictionary,synonyms,rhymes,english", "",
     "English word data: definitions, synonyms, rhymes, syllables and frequency.",
     "Данные об английских словах: определения, синонимы, рифмы, слоги и частотность.",
     "Frequency data is useful for filtering obscure words out of word games and vocabulary tools."),
    ("api-merriam-webster", "Merriam-Webster APIs", "Словари и лексика", "https://dictionaryapi.com/", "freeTier", "dictionary,thesaurus,english,authoritative", "",
     "Authoritative English dictionary and thesaurus data from Merriam-Webster.",
     "Авторитетные данные английского словаря и тезауруса от Merriam-Webster.",
     "Free non-commercial keys allow 1000 queries/day — commercial use requires a separate licence."),

    # ---------- Еда и быт (deepen) ----------
    ("api-tasty", "Tasty API", "Еда и быт", "https://rapidapi.com/apidojo/api/tasty", "freeTier", "recipes,food,video,buzzfeed", "",
     "Recipes with video instructions from BuzzFeed's Tasty, via RapidAPI.",
     "Рецепты с видеоинструкциями от Tasty (BuzzFeed) через RapidAPI.",
     "Access is through RapidAPI rather than a direct endpoint — the key and billing live there."),
    ("api-fruityvice", "Fruityvice", "Еда и быт", "https://www.fruityvice.com/doc/index.html", "noKey", "fruit,nutrition,no-key,simple", "",
     "Nutrition data about fruit, no key required, useful for teaching and demos.",
     "Данные о питательной ценности фруктов без ключа, удобно для обучения и демо.",
     "Its tiny, stable dataset makes it a good target for teaching API consumption without rate-limit worries."),

    # ---------- Игры и развлечения (deepen) ----------
    ("api-boardgamegeek", "BoardGameGeek XML API", "Игры и развлечения", "https://boardgamegeek.com/wiki/page/BGG_XML_API2", "noKey", "board-games,ratings,collection,no-key", "",
     "Board game data, ratings and user collections from BoardGameGeek.",
     "Данные о настольных играх, рейтинги и коллекции пользователей с BoardGameGeek.",
     "Returns XML, not JSON, and may reply 202 while it prepares data — retry after a short delay."),
    ("api-dnd5e", "D&D 5e API", "Игры и развлечения", "https://www.dnd5eapi.co/docs/", "noKey", "dnd,rpg,spells,no-key", "",
     "Dungeons & Dragons 5th edition rules data: spells, monsters, classes, no key required.",
     "Данные правил D&D 5-й редакции: заклинания, монстры, классы, без ключа.",
     "The dataset is static and small enough to cache entirely on first load for an offline-capable app."),
]
