# -*- coding: utf-8 -*-
"""Stage 5 pricing pack I: APM and log platforms, uptime monitoring, incident management."""

PAID_5I = [
("paid-splunk","Splunk (pricing)","Мониторинг и аналитика","https://www.splunk.com/en_us/products/pricing.html","paid","logs,pricing,ingest,workload",
 "Log platform priced by daily ingest volume or by compute workload.",
 "Платформа логов с ценой по суточному объёму приёма данных или по вычислительной нагрузке.",
 "Ingest-based pricing is why log volume reduction becomes a standing engineering project.",
 "custom","custom quote (by daily ingest)","free tier up to 500MB/day","https://www.splunk.com/en_us/products/pricing.html"),
("paid-sumologic","Sumo Logic (pricing)","Мониторинг и аналитика","https://www.sumologic.com/pricing/","paid","logs,pricing,ingest,credits",
 "Log analytics sold as credits consumed by ingest and query volume.",
 "Аналитика логов в виде кредитов, расходуемых на приём и запросы данных.",
 "Its tiered storage moves old logs to cheaper classes, which materially changes long-retention cost.",
 "credits","from ~$3.00 per GB ingested","free tier","https://www.sumologic.com/pricing/"),
("paid-lightstep-cloud","ServiceNow Cloud Observability (pricing)","Наблюдаемость трасс","https://www.servicenow.com/products/observability.html","paid","tracing,pricing,enterprise,spans",
 "Distributed tracing sold on enterprise contracts scaled to span volume.",
 "Распределённая трассировка по корпоративным контрактам, масштабируемым под объём спанов.",
 "Sampling strategy drives the bill more than traffic does — decide it before signing.",
 "custom","custom quote","free developer tier","https://www.servicenow.com/products/observability.html"),
("paid-instana","IBM Instana (pricing)","Мониторинг и аналитика","https://www.ibm.com/products/instana/pricing","paid","apm,pricing,per-host,subscription",
 "Application performance monitoring billed per monitored host.",
 "Мониторинг производительности приложений с оплатой за отслеживаемый хост.",
 "Per-host pricing penalizes many small containers, so check how it counts your workloads.",
 "subscription","from ~$75 per host per month","free trial","https://www.ibm.com/products/instana/pricing"),
("paid-appdynamics","AppDynamics (pricing)","Мониторинг и аналитика","https://www.appdynamics.com/pricing","paid","apm,pricing,per-agent,enterprise",
 "Enterprise APM billed per monitored agent on annual contracts.",
 "Корпоративный APM с оплатой за отслеживаемый агент по годовым контрактам.",
 "Priced for large estates; smaller teams get comparable coverage far cheaper elsewhere.",
 "subscription","from ~$60 per agent per month","free trial","https://www.appdynamics.com/pricing"),
("paid-raygun","Raygun (pricing)","Мониторинг и аналитика","https://raygun.com/pricing","paid","errors,pricing,per-event,subscription",
 "Error and performance monitoring billed by event and session volume.",
 "Мониторинг ошибок и производительности с оплатой по объёму событий и сессий.",
 "Its code-level traces are the feature that justifies the premium over plain error trackers.",
 "usage","from ~$4 per 10000 errors","free trial","https://raygun.com/pricing"),
("paid-trackjs","TrackJS (pricing)","Мониторинг и аналитика","https://trackjs.com/pricing/","paid","frontend,pricing,per-error,subscription",
 "Frontend error tracking billed monthly by captured error volume.",
 "Отслеживание ошибок фронтенда с месячной оплатой по объёму захваченных ошибок.",
 "Focused purely on browser errors, which keeps it cheaper than full-stack platforms.",
 "subscription","from ~$49 per month","free trial","https://trackjs.com/pricing/"),
("paid-pingdom","Pingdom (pricing)","Мониторинг и аналитика","https://www.pingdom.com/pricing/","paid","uptime,pricing,per-check,subscription",
 "Uptime and synthetic monitoring billed by number of checks and locations.",
 "Мониторинг доступности и синтетический мониторинг с оплатой по числу проверок и локаций.",
 "Self-hosted Uptime Kuma covers basic uptime for free — pay here for the global probe network.",
 "subscription","from ~$10 per month","free trial","https://www.pingdom.com/pricing/"),
("paid-incident-io","incident.io (pricing)","Мониторинг и аналитика","https://incident.io/pricing","paid","incidents,pricing,per-responder,subscription",
 "Incident management billed per responder on the on-call rotation.",
 "Управление инцидентами с оплатой за участника дежурной ротации.",
 "Billing per responder rather than per employee keeps cost tied to who is actually on call.",
 "subscription","from ~$20 per responder per month","free trial","https://incident.io/pricing"),
("paid-firehydrant","FireHydrant (pricing)","Мониторинг и аналитика","https://firehydrant.com/pricing/","paid","incidents,pricing,per-user,subscription",
 "Incident response platform billed per user with a free starter tier.",
 "Платформа реагирования на инциденты с оплатой за пользователя и бесплатным стартовым тарифом.",
 "Its free tier covers a small team's incident process, including retrospectives.",
 "subscription","from ~$25 per user per month","free tier for small teams","https://firehydrant.com/pricing/"),
("paid-rootly","Rootly (pricing)","Мониторинг и аналитика","https://rootly.com/pricing","paid","incidents,pricing,per-user,subscription",
 "Incident management billed per user, with on-call as a separate module.",
 "Управление инцидентами с оплатой за пользователя; дежурства — отдельный модуль.",
 "Confirm whether on-call is included in the quote — it is often priced separately.",
 "subscription","custom quote (per user)","free trial","https://rootly.com/pricing"),
("paid-blameless","Blameless (pricing)","Мониторинг и аналитика","https://www.blameless.com/pricing","paid","reliability,pricing,enterprise,custom",
 "Reliability and SLO platform sold on enterprise contracts.",
 "Платформа надёжности и SLO по корпоративным контрактам.",
 "Its value depends on already having SLOs defined — the tool does not create that discipline.",
 "custom","custom quote","product demo","https://www.blameless.com/pricing"),
]
