# -*- coding: utf-8 -*-
"""Stage 5 library pack AG: monorepo build systems, release automation, package and toolchain managers."""

LIBS_5AG = [
    # ---------- Монорепозитории и сборка ----------
    ("lib-lerna", "Lerna", "Сборка и bundlers", "https://lerna.js.org/docs/introduction", "openSource", "monorepo,javascript,versioning,publishing", "npm i -D lerna",
     "Long-standing JavaScript monorepo tool for versioning and publishing packages.",
     "Давний инструмент JavaScript-монорепозиториев для версионирования и публикации пакетов.",
     "Now maintained by the Nx team and largely a thin layer over it for new projects."),
    ("lib-rush", "Rush", "Сборка и bundlers", "https://rushjs.io/pages/intro/welcome/", "openSource", "monorepo,microsoft,scalable,strict", "npm i -g @microsoft/rush",
     "Microsoft's monorepo manager built for very large repositories with strict policies.",
     "Менеджер монорепозиториев от Microsoft для очень больших репозиториев со строгими политиками.",
     "Its strict dependency policies prevent the phantom-dependency problems that grow with repo size."),
    ("lib-buck2", "Buck2", "Сборка и bundlers", "https://buck2.build/docs/", "openSource", "build-system,meta,rust,remote-execution", "",
     "Meta's Rust-based build system, a faster successor to Buck.",
     "Система сборки Meta на Rust, более быстрый преемник Buck.",
     "Its incremental engine is fast, but expect a real investment in writing build definitions."),

    # ---------- Релизы и зависимости ----------
    ("lib-semantic-release", "semantic-release", "Git и совместная работа", "https://semantic-release.gitbook.io/semantic-release/", "openSource", "versioning,changelog,automation,commits", "npm i -D semantic-release",
     "Fully automated versioning and publishing driven by commit messages.",
     "Полностью автоматизированное версионирование и публикация на основе сообщений коммитов.",
     "Requires disciplined conventional commits — the whole version number derives from them."),
    ("lib-release-please", "release-please", "Git и совместная работа", "https://github.com/googleapis/release-please", "openSource", "google,changelog,release-pr,conventional-commits", "",
     "Generates release pull requests with changelogs from conventional commits.",
     "Формирует релизные pull request с changelog на основе conventional commits.",
     "The release PR gives a human review step that fully automated publishing skips."),
    ("lib-syncpack", "Syncpack", "Сборка и bundlers", "https://jamiemason.github.io/syncpack/", "openSource", "monorepo,dependencies,versions,consistency", "npm i -D syncpack",
     "Finds and fixes mismatched dependency versions across a monorepo.",
     "Находит и исправляет расхождения версий зависимостей в монорепозитории.",
     "Two packages on different versions of the same library is a classic source of subtle monorepo bugs."),
    ("lib-npm-check-updates", "npm-check-updates", "Сборка и bundlers", "https://github.com/raineorshine/npm-check-updates", "openSource", "dependencies,upgrades,cli,semver", "npm i -g npm-check-updates",
     "Upgrades package.json dependencies past their declared semver ranges.",
     "Обновляет зависимости package.json за пределы объявленных диапазонов semver.",
     "Upgrade in batches by risk level — one command bumping everything makes failures impossible to bisect."),
    ("lib-verdaccio", "Verdaccio", "Сборка и bundlers", "https://verdaccio.org/docs/what-is-verdaccio", "openSource", "registry,private,npm,proxy", "npm i -g verdaccio",
     "Lightweight private npm registry that proxies and caches the public one.",
     "Лёгкий приватный npm-реестр, проксирующий и кэширующий публичный.",
     "Excellent for end-to-end testing a publish flow without pushing anything to the real registry."),

    # ---------- Менеджеры пакетов JavaScript ----------
    ("lib-yarn-berry", "Yarn (Berry)", "Сборка и bundlers", "https://yarnpkg.com/getting-started", "openSource", "package-manager,pnp,zero-installs,workspaces", "",
     "Modern Yarn with Plug'n'Play resolution and optional zero-install workflows.",
     "Современный Yarn с разрешением Plug'n'Play и опциональным подходом zero-install.",
     "Plug'n'Play removes node_modules entirely, which some tooling still does not expect."),
    ("lib-bun-install", "Bun install", "Сборка и bundlers", "https://bun.com/docs/cli/install", "openSource", "package-manager,fast,node-compatible,lockfile", "",
     "Very fast npm-compatible package installer built into the Bun runtime.",
     "Очень быстрый npm-совместимый установщик пакетов, встроенный в рантайм Bun.",
     "Usable purely as an installer in an otherwise Node project, without adopting the Bun runtime."),
    ("lib-corepack", "Corepack", "Сборка и bundlers", "https://nodejs.org/api/corepack.html", "free", "node,package-manager,versions,built-in", "",
     "Node's built-in shim pinning which package manager version a project uses.",
     "Встроенный в Node механизм, фиксирующий версию используемого проектом менеджера пакетов.",
     "The packageManager field guarantees every contributor resolves dependencies identically."),
    ("lib-volta", "Volta", "Разработка и DevOps", "https://docs.volta.sh/guide/", "openSource", "node,toolchain,per-project,rust", "curl https://get.volta.sh | bash",
     "Pins Node and package manager versions per project and switches automatically.",
     "Фиксирует версии Node и менеджера пакетов для каждого проекта и переключает их автоматически.",
     "Switching happens on directory entry with no shell hook, unlike nvm's manual model."),
    ("lib-fnm", "fnm", "Разработка и DevOps", "https://github.com/Schniz/fnm", "openSource", "node,version-manager,fast,rust", "",
     "Fast Node version manager written in Rust, compatible with .nvmrc.",
     "Быстрый менеджер версий Node на Rust, совместимый с .nvmrc.",
     "Noticeably faster shell startup than nvm, which matters if you open many terminals."),
    ("lib-nvm", "nvm", "Разработка и DevOps", "https://github.com/nvm-sh/nvm", "openSource", "node,version-manager,shell,ubiquitous", "",
     "The original Node version manager, implemented as shell functions.",
     "Оригинальный менеджер версий Node, реализованный как shell-функции.",
     "Ubiquitous and reliable, though its shell implementation slows down every new terminal."),

    # ---------- Менеджеры пакетов Python ----------
    ("lib-poetry", "Poetry", "Разработка и DevOps", "https://python-poetry.org/docs/", "openSource", "python,dependencies,packaging,lockfile", "pipx install poetry",
     "Python dependency management and packaging with a proper lock file.",
     "Управление зависимостями и упаковка Python с полноценным lock-файлом.",
     "Its resolver is thorough but slow — uv is dramatically faster for the same dependency graph."),
    ("lib-pdm", "PDM", "Разработка и DevOps", "https://pdm-project.org/", "openSource", "python,pep-582,standards,packaging", "pipx install pdm",
     "Standards-based Python package manager following modern packaging PEPs.",
     "Менеджер пакетов Python на основе стандартов, следующий современным PEP по упаковке.",
     "Sticks closely to the official standards, which keeps projects portable between tools."),
    ("lib-hatch", "Hatch", "Разработка и DevOps", "https://hatch.pypa.io/", "openSource", "python,packaging,environments,pypa", "pipx install hatch",
     "PyPA's project manager covering environments, builds and publishing.",
     "Менеджер проектов от PyPA, охватывающий окружения, сборку и публикацию.",
     "Its build backend, Hatchling, is widely used even by projects that do not use the rest of Hatch."),
    ("lib-rye", "Rye", "Разработка и DevOps", "https://rye.astral.sh/", "openSource", "python,toolchain,astral,experimental", "",
     "Experimental Python project manager from Astral, now largely folded into uv.",
     "Экспериментальный менеджер Python-проектов от Astral, во многом влившийся в uv.",
     "Start new projects on uv — Rye exists mainly for repositories that already adopted it."),
    ("lib-pipx", "pipx", "Разработка и DevOps", "https://pipx.pypa.io/", "openSource", "python,cli-tools,isolation,global", "pip install pipx",
     "Installs Python CLI applications into isolated environments.",
     "Устанавливает Python-приложения командной строки в изолированные окружения.",
     "Keeps tool dependencies out of your project environments, which prevents a common class of conflict."),
    ("lib-pip-tools", "pip-tools", "Разработка и DevOps", "https://pip-tools.readthedocs.io/", "openSource", "python,pinning,requirements,compile", "pip install pip-tools",
     "Compiles loose requirements into fully pinned, reproducible lock files.",
     "Компилирует свободные требования в полностью зафиксированные воспроизводимые lock-файлы.",
     "A minimal way to add real pinning to an existing requirements.txt project with no restructuring."),
    ("lib-conda", "Conda", "Разработка и DevOps", "https://docs.conda.io/", "openSource", "python,scientific,binaries,environments", "",
     "Cross-language package manager handling binary scientific dependencies.",
     "Кроссязыковой менеджер пакетов, работающий с бинарными научными зависимостями.",
     "It installs non-Python binaries like CUDA and MKL, which is why scientific stacks still rely on it."),
    ("lib-pixi-pkg", "Pixi", "Разработка и DevOps", "https://pixi.sh/latest/", "openSource", "conda,fast,rust,lockfile", "",
     "Fast Rust-based package manager for the conda ecosystem with proper lock files.",
     "Быстрый менеджер пакетов на Rust для экосистемы conda с полноценными lock-файлами.",
     "Brings reproducible lock files to conda packages, which conda itself never handled well."),

    # ---------- JVM и другие экосистемы ----------
    ("lib-maven", "Apache Maven", "JVM экосистема", "https://maven.apache.org/guides/", "openSource", "java,build,dependencies,convention", "",
     "Convention-based Java build tool with a very large plugin and repository ecosystem.",
     "Java-инструмент сборки на соглашениях с очень большой экосистемой плагинов и репозиториев.",
     "Its XML verbosity is the usual complaint, but its predictability is why enterprises keep it."),
    ("lib-gradle", "Gradle", "JVM экосистема", "https://docs.gradle.org/current/userguide/userguide.html", "openSource", "java,kotlin,android,incremental", "",
     "Flexible JVM build tool with incremental builds and a build cache.",
     "Гибкий инструмент сборки для JVM с инкрементальными сборками и кэшем сборки.",
     "Use the Kotlin DSL for new builds — the type safety catches script errors the Groovy DSL hides."),
    ("lib-sbt", "sbt", "JVM экосистема", "https://www.scala-sbt.org/documentation.html", "openSource", "scala,build,incremental,interactive", "",
     "The standard Scala build tool, with incremental compilation and an interactive shell.",
     "Стандартный инструмент сборки Scala с инкрементальной компиляцией и интерактивной оболочкой.",
     "Keeping its shell open avoids repeated JVM startup, which dominates short Scala build times."),
    ("lib-mill", "Mill", "JVM экосистема", "https://mill-build.org/mill/Intro_to_Mill.html", "openSource", "scala,java,build,simple", "",
     "JVM build tool aiming for simpler, more predictable builds than sbt.",
     "Инструмент сборки для JVM, стремящийся к более простым и предсказуемым сборкам, чем sbt.",
     "Its build files are plain Scala objects, which makes build logic far easier to follow than sbt's DSL."),
    ("lib-cargo", "Cargo", "Rust экосистема", "https://doc.rust-lang.org/cargo/", "openSource", "rust,build,dependencies,official", "",
     "Rust's official build tool and package manager.",
     "Официальный инструмент сборки и менеджер пакетов Rust.",
     "Widely treated as the reference design for what a language's package manager should be."),

    # ---------- Воспроизводимые окружения ----------
    ("lib-nix", "Nix", "Разработка и DevOps", "https://nix.dev/", "openSource", "reproducible,declarative,packages,environments", "",
     "Purely functional package manager producing fully reproducible environments.",
     "Чисто функциональный менеджер пакетов, создающий полностью воспроизводимые окружения.",
     "The reproducibility is real, and so is the learning curve — budget time before committing a team."),
    ("lib-devenv", "devenv", "Разработка и DevOps", "https://devenv.sh/", "openSource", "nix,dev-environments,declarative,services", "",
     "Declarative development environments built on Nix, including background services.",
     "Декларативные среды разработки на базе Nix, включая фоновые сервисы.",
     "It makes Nix approachable by hiding most of the language behind a simple configuration file."),
    ("lib-flox", "Flox", "Разработка и DevOps", "https://flox.dev/docs/", "openSource", "nix,environments,cross-platform,simple", "",
     "Nix-backed environments with a conventional command-line interface.",
     "Окружения на основе Nix с привычным интерфейсом командной строки.",
     "Gives most of Nix's reproducibility without requiring anyone to write Nix expressions."),

    # ---------- Контейнерные образы ----------
    ("lib-buildkit", "BuildKit", "Разработка и DevOps", "https://docs.docker.com/build/buildkit/", "openSource", "docker,builds,cache,parallel", "",
     "Docker's modern build engine with parallel stages and advanced caching.",
     "Современный движок сборки Docker с параллельными стадиями и продвинутым кэшированием.",
     "Cache mounts keep package downloads between builds, which is usually the biggest single speedup."),
    ("lib-docker-bake", "Docker Bake", "Разработка и DevOps", "https://docs.docker.com/build/bake/", "openSource", "docker,build,declarative,multi-target", "",
     "Declarative multi-target Docker builds defined in a single file.",
     "Декларативные многоцелевые сборки Docker, описанные в одном файле.",
     "Building several images with shared configuration becomes one command instead of a shell loop."),
    ("lib-ko-build", "ko", "Разработка и DevOps", "https://ko.build/", "openSource", "go,containers,no-dockerfile,fast", "go install github.com/google/ko@latest",
     "Builds container images for Go applications without a Dockerfile.",
     "Собирает образы контейнеров для Go-приложений без Dockerfile.",
     "Produces small reproducible images in seconds, since it skips the Docker build machinery entirely."),
    ("lib-jib", "Jib", "Разработка и DevOps", "https://github.com/GoogleContainerTools/jib", "openSource", "java,containers,no-docker-daemon,layers", "",
     "Builds optimized Java container images from Maven or Gradle without Docker.",
     "Собирает оптимизированные Java-образы контейнеров из Maven или Gradle без Docker.",
     "Its layering separates dependencies from your code, so a code change rebuilds only a tiny layer."),
    ("lib-apko", "apko", "Разработка и DevOps", "https://github.com/chainguard-dev/apko", "openSource", "images,declarative,apk,reproducible", "",
     "Builds minimal container images declaratively from APK packages.",
     "Декларативно собирает минимальные образы контейнеров из APK-пакетов.",
     "Images are bit-for-bit reproducible, which makes supply-chain attestation meaningful."),
    ("lib-chainguard-images", "Chainguard Images", "Безопасность и секреты", "https://images.chainguard.dev/", "mixed", "containers,minimal,cve-free,hardened", "",
     "Minimal hardened container base images maintained with near-zero known CVEs.",
     "Минимальные усиленные базовые образы контейнеров с почти нулевым числом известных CVE.",
     "Fewer packages means fewer CVEs to triage — most of the security benefit is simply less software."),
    ("lib-distroless", "Distroless", "Безопасность и секреты", "https://github.com/GoogleContainerTools/distroless", "openSource", "containers,minimal,google,no-shell", "",
     "Google's base images containing only your application and its runtime dependencies.",
     "Базовые образы Google, содержащие только ваше приложение и его рантайм-зависимости.",
     "No shell in the image means debugging needs an ephemeral sidecar — plan for that before adopting."),
]
