# -*- coding: utf-8 -*-
"""Stage 5 library pack L: AI/RAG libs depth, local models, audio, misc frontend."""

LIBS_5L = [
    # ---------- AI-фреймворки (deepen) ----------
    ("lib-langchain-js", "LangChain.js", "AI-фреймворки", "https://js.langchain.com/docs/introduction/", "openSource", "javascript,agents,rag,integrations", "npm i langchain",
     "The JavaScript/TypeScript port of LangChain for Node and browser agents.",
     "JavaScript/TypeScript-порт LangChain для агентов в Node и браузере.",
     "Its integration surface lags the Python version — verify your specific integration exists before committing."),
    ("lib-llamaindex-ts", "LlamaIndex.TS", "AI-фреймворки", "https://ts.llamaindex.ai/", "openSource", "typescript,rag,indexing,retrieval", "npm i llamaindex",
     "TypeScript implementation of LlamaIndex for RAG pipelines in Node.",
     "TypeScript-реализация LlamaIndex для RAG-пайплайнов в Node.",
     "Useful when the whole stack is TypeScript and you would rather not run a separate Python service for RAG."),
    ("lib-mastra", "Mastra", "AI-фреймворки", "https://mastra.ai/docs", "openSource", "typescript,agents,workflows,rag", "npm create mastra@latest",
     "TypeScript agent framework with workflows, RAG and evals built in.",
     "TypeScript-фреймворк агентов со встроенными workflow, RAG и оценками.",
     "Its workflow primitives are durable, which covers the long-running-agent case plain function calls do not."),
    ("lib-agno", "Agno", "AI-фреймворки", "https://docs.agno.com/", "openSource", "python,agents,multi-agent,memory", "pip install agno",
     "Lightweight Python framework for building agents with memory, tools and reasoning.",
     "Лёгкий Python-фреймворк для агентов с памятью, инструментами и рассуждением.",
     "Deliberately minimal compared to LangChain — the whole framework is small enough to read in an afternoon."),
    ("lib-pydantic-graph", "Pydantic Graph", "Планирование и reasoning", "https://ai.pydantic.dev/graph/", "openSource", "python,graphs,state-machines,typed", "pip install pydantic-graph",
     "Typed graph-based state machines for orchestrating multi-step agent logic.",
     "Типизированные графовые конечные автоматы для оркестрации многошаговой логики агента.",
     "Type-checked node transitions catch invalid agent state paths at development time, not in production."),
    ("lib-burr", "Burr", "Планирование и reasoning", "https://burr.dagworks.io/", "openSource", "python,state-machines,agents,observability", "pip install burr",
     "State machine framework for AI applications with built-in tracking and a debug UI.",
     "Фреймворк конечных автоматов для ИИ-приложений со встроенным трекингом и UI отладки.",
     "Its UI replays an agent run step by step, which makes debugging non-deterministic flows far easier."),

    # ---------- Локальные модели (deepen) ----------
    ("lib-lm-studio", "LM Studio", "Локальные модели", "https://lmstudio.ai/docs", "freeTier", "local,gui,models,openai-compatible", "",
     "Desktop app for downloading and running local models, with an OpenAI-compatible server.",
     "Настольное приложение для скачивания и запуска локальных моделей с OpenAI-совместимым сервером.",
     "Its local server mode means existing OpenAI client code points at localhost with no other changes."),
    ("lib-text-generation-webui", "Text Generation WebUI", "Локальные модели", "https://github.com/oobabooga/text-generation-webui", "openSource", "local,gradio,models,ui", "",
     "Gradio web UI for running local text models with many backend loaders.",
     "Веб-интерфейс Gradio для запуска локальных текстовых моделей с разными загрузчиками бэкендов.",
     "Supports more quantization formats than most runners — useful when a model only ships in an unusual format."),
    ("lib-exllamav2", "ExLlamaV2", "Локальные модели", "https://github.com/turboderp-org/exllamav2", "openSource", "quantization,inference,gpu,fast", "pip install exllamav2",
     "Fast quantized inference library for running large models on consumer GPUs.",
     "Быстрая библиотека квантованного инференса для запуска больших моделей на потребительских GPU.",
     "Its EXL2 format allows fractional bit-rates, letting you fit a model exactly into available VRAM."),
    ("lib-llamafile", "llamafile", "Локальные модели", "https://github.com/Mozilla-Ocho/llamafile", "openSource", "local,single-file,portable,mozilla", "",
     "Packages an LLM and its runtime into one executable file that runs on multiple OSes.",
     "Упаковывает LLM и рантайм в один исполняемый файл, работающий на разных ОС.",
     "One file with no install step at all — the simplest way to hand someone a working local model."),
    ("lib-gpt4all", "GPT4All", "Локальные модели", "https://docs.gpt4all.io/", "openSource", "local,desktop,privacy,cpu", "pip install gpt4all",
     "Local model runner focused on CPU inference and privacy, with a desktop app.",
     "Локальный запуск моделей с фокусом на CPU-инференс и приватность, с настольным приложением.",
     "Runs acceptably without a GPU, which matters for deploying to ordinary office hardware."),

    # ---------- Аудио и голос (deepen) ----------
    ("lib-whisperx", "WhisperX", "Аудио и голос", "https://github.com/m-bain/whisperX", "openSource", "transcription,alignment,diarization,whisper", "pip install whisperx",
     "Whisper transcription with word-level timestamps and speaker diarization.",
     "Транскрипция Whisper с таймкодами на уровне слов и разделением говорящих.",
     "Word-level alignment is what makes subtitle generation and clip-searching actually usable."),
    ("lib-pyannote", "pyannote.audio", "Аудио и голос", "https://github.com/pyannote/pyannote-audio", "openSource", "diarization,speakers,audio,pytorch", "pip install pyannote.audio",
     "Speaker diarization toolkit: who spoke when, in a multi-speaker recording.",
     "Тулкит разделения говорящих: кто и когда говорил в многоголосой записи.",
     "Requires accepting model terms on Hugging Face before the pretrained pipeline will download."),
    ("lib-librosa", "librosa", "Аудио и голос", "https://librosa.org/doc/latest/index.html", "openSource", "audio,analysis,python,features", "pip install librosa",
     "Python library for audio analysis: spectrograms, beat tracking, feature extraction.",
     "Python-библиотека анализа аудио: спектрограммы, отслеживание ритма, извлечение признаков.",
     "The standard starting point for classical audio feature engineering before reaching for a neural model."),
    ("lib-pydub", "Pydub", "Аудио и голос", "https://github.com/jiaaro/pydub", "openSource", "audio,manipulation,python,simple", "pip install pydub",
     "Simple audio manipulation in Python: slice, concatenate, adjust volume, convert formats.",
     "Простая работа с аудио в Python: нарезка, склейка, громкость, конвертация форматов.",
     "It shells out to FFmpeg, so FFmpeg must be installed separately or format conversion silently fails."),
    ("lib-web-audio-api", "Web Audio API", "Аудио и голос", "https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API", "free", "audio,browser,synthesis,standard", "",
     "The browser's native audio processing and synthesis API.",
     "Нативный API браузера для обработки и синтеза аудио.",
     "Audio context must start from a user gesture — browsers block autoplay audio without one."),

    # ---------- UI и frontend (deepen further) ----------
    ("lib-embla-carousel", "Embla Carousel", "UI и frontend", "https://www.embla-carousel.com/", "openSource", "carousel,slider,lightweight,accessible", "npm i embla-carousel",
     "Lightweight, dependency-free carousel with precise scroll physics.",
     "Лёгкая карусель без зависимостей с точной физикой прокрутки.",
     "Its physics feel native on touch devices, which is where most carousel libraries fall apart."),
    ("lib-floating-ui", "Floating UI", "UI и frontend", "https://floating-ui.com/docs/getting-started", "openSource", "tooltips,popovers,positioning,anchoring", "npm i @floating-ui/dom",
     "Positioning engine for tooltips, popovers and dropdowns, the successor to Popper.js.",
     "Движок позиционирования для тултипов, поповеров и дропдаунов, преемник Popper.js.",
     "It handles viewport collision and flipping, which is the part everyone gets wrong hand-rolling a tooltip."),
    ("lib-tanstack-virtual", "TanStack Virtual", "UI и frontend", "https://tanstack.com/virtual/latest", "openSource", "virtualization,performance,lists,headless", "npm i @tanstack/virtual-core",
     "Headless list and grid virtualization for rendering huge datasets smoothly.",
     "Headless виртуализация списков и сеток для плавного рендеринга огромных наборов данных.",
     "Only becomes necessary past roughly a thousand DOM nodes — below that it adds complexity for no gain."),
    ("lib-dnd-kit", "dnd kit", "UI и frontend", "https://docs.dndkit.com/", "openSource", "drag-and-drop,react,accessible,modular", "npm i @dnd-kit/core",
     "Modern, accessible drag-and-drop toolkit for React with keyboard support.",
     "Современный доступный тулкит drag-and-drop для React с поддержкой клавиатуры.",
     "Keyboard-accessible dragging out of the box is the main reason to pick it over react-beautiful-dnd."),
    ("lib-cmdk", "cmdk", "UI и frontend", "https://cmdk.paco.me/", "openSource", "command-palette,react,search,keyboard", "npm i cmdk",
     "Composable command palette component for React, the pattern behind Cmd+K menus.",
     "Композируемый компонент командной палитры для React — паттерн меню по Cmd+K.",
     "Ships unstyled, so it adapts to any design system rather than fighting one."),
]
