# -*- coding: utf-8 -*-
"""Stage 5 library pack AY: CI/CD platforms, artifact registries, faster runners, git forges."""

LIBS_5AY = [
    # ---------- CI/CD платформы ----------
    ("lib-woodpecker-ci", "Woodpecker CI", "Разработка и DevOps", "https://woodpecker-ci.org/docs/intro", "openSource", "self-host,containers,lightweight,drone-fork", "",
     "Lightweight self-hosted CI engine running each step in a container.",
     "Лёгкий self-hosted движок CI, выполняющий каждый шаг в контейнере.",
     "A community fork of Drone that stayed fully open source after Drone's licence changed."),
    ("lib-drone-ci", "Drone", "Разработка и DevOps", "https://docs.drone.io/", "mixed", "containers,pipelines,self-host,harness", "",
     "Container-native CI platform, now part of Harness.",
     "CI-платформа на контейнерах, теперь часть Harness.",
     "Its licence changed after the acquisition — Woodpecker is the open continuation."),
    ("lib-concourse", "Concourse CI", "Разработка и DevOps", "https://concourse-ci.org/docs.html", "openSource", "pipelines,resources,stateless,declarative", "",
     "Pipeline-centric CI built around stateless jobs and versioned resources.",
     "CI, построенный вокруг stateless-задач и версионированных ресурсов.",
     "Its strict statelessness makes builds reproducible and its learning curve unusually steep."),
    ("lib-buildkite", "Buildkite", "Разработка и DevOps", "https://buildkite.com/docs", "paid", "hybrid,self-hosted-agents,scalable,pipelines", "",
     "Hosted CI control plane with build agents running on your own infrastructure.",
     "Размещённый управляющий слой CI с агентами сборки на вашей инфраструктуре.",
     "Your code never leaves your infrastructure while the orchestration stays managed."),
    ("lib-teamcity", "TeamCity", "Разработка и DevOps", "https://www.jetbrains.com/help/teamcity/", "mixed", "jetbrains,build-chains,jvm,on-premise", "",
     "JetBrains CI server with strong build chain and JVM support.",
     "CI-сервер JetBrains с сильной поддержкой цепочек сборки и JVM.",
     "Its free tier covers a real small team on-premise, which most commercial CI servers do not."),
    ("lib-bamboo", "Bamboo", "Разработка и DevOps", "https://confluence.atlassian.com/bamboo/", "paid", "atlassian,jira-integration,on-premise,deployments", "",
     "Atlassian CI server with deep Jira and Bitbucket integration.",
     "CI-сервер Atlassian с глубокой интеграцией Jira и Bitbucket.",
     "Its value is almost entirely the Atlassian integration — standalone it lags modern alternatives."),
    ("lib-semaphore-ci", "Semaphore", "Разработка и DevOps", "https://docs.semaphoreci.com/", "freeTier", "fast,pipelines,hosted,monorepo", "",
     "Hosted CI focused on fast builds with monorepo change detection.",
     "Размещённый CI с фокусом на быстрые сборки и определение изменений в монорепозитории.",
     "Its change detection skips jobs for untouched parts of a monorepo, which cuts build time sharply."),
    ("lib-circleci", "CircleCI", "Разработка и DevOps", "https://circleci.com/docs/", "freeTier", "hosted,orbs,caching,parallelism", "",
     "Hosted CI with reusable configuration packages called orbs.",
     "Размещённый CI с переиспользуемыми конфигурационными пакетами orbs.",
     "Orbs turn common setup steps into one line, at the cost of another supply chain to trust."),
    ("lib-travis-ci", "Travis CI", "Разработка и DevOps", "https://docs.travis-ci.com/", "paid", "hosted,legacy,open-source-history,simple", "",
     "Hosted CI service, historically the default for open-source projects.",
     "Размещённый сервис CI, исторически стандарт для open-source проектов.",
     "Most open-source projects moved to GitHub Actions after its free tier was withdrawn."),
    ("lib-appveyor", "AppVeyor", "Разработка и DevOps", "https://www.appveyor.com/docs/", "freeTier", "windows,dotnet,ci,cross-platform", "",
     "CI service with unusually strong Windows and .NET support.",
     "Сервис CI с необычно сильной поддержкой Windows и .NET.",
     "Its Windows build environments are more complete than most cross-platform CI providers offer."),
    ("lib-harness", "Harness", "Разработка и DevOps", "https://developer.harness.io/", "freeTier", "cd,verification,feature-flags,platform", "",
     "Delivery platform with automated deployment verification.",
     "Платформа доставки с автоматической проверкой развёртываний.",
     "It watches metrics after a deploy and rolls back automatically when they degrade."),
    ("lib-codefresh", "Codefresh", "Разработка и DevOps", "https://codefresh.io/docs/", "freeTier", "gitops,argo,kubernetes,pipelines", "",
     "GitOps-focused CI/CD built on Argo.",
     "CI/CD с фокусом на GitOps, построенный на Argo.",
     "Its Argo foundation means the delivery model matches what Kubernetes teams already run."),
    ("lib-octopus-deploy", "Octopus Deploy", "Разработка и DevOps", "https://octopus.com/docs", "paid", "deployment,releases,environments,dotnet", "",
     "Deployment automation with strong release and environment management.",
     "Автоматизация развёртывания с сильным управлением релизами и окружениями.",
     "It separates build from deploy explicitly, which suits regulated release processes."),
    ("lib-spinnaker", "Spinnaker", "Облако и деплой", "https://spinnaker.io/docs/", "openSource", "multi-cloud,canary,netflix,deployment", "",
     "Multi-cloud continuous delivery platform originating at Netflix.",
     "Мультиоблачная платформа непрерывной доставки, созданная в Netflix.",
     "Powerful canary analysis and heavy to operate — Argo Rollouts covers most of it more simply."),

    # ---------- Реестры артефактов ----------
    ("lib-artifactory", "JFrog Artifactory", "Разработка и DevOps", "https://jfrog.com/help/r/jfrog-artifactory-documentation", "mixed", "registry,universal,binaries,enterprise", "",
     "Universal artifact repository supporting most package formats.",
     "Универсальный репозиторий артефактов с поддержкой большинства форматов пакетов.",
     "One registry across every language removes a per-ecosystem registry to run and secure."),
    ("lib-nexus-repository", "Nexus Repository", "Разработка и DevOps", "https://help.sonatype.com/en/sonatype-nexus-repository.html", "mixed", "registry,proxy,maven,sonatype", "",
     "Artifact repository manager with proxying and caching of public registries.",
     "Менеджер репозиториев артефактов с проксированием и кэшированием публичных реестров.",
     "Proxying public registries keeps builds working when an upstream package is yanked."),
    ("lib-cloudsmith", "Cloudsmith", "Разработка и DevOps", "https://help.cloudsmith.io/docs", "freeTier", "registry,hosted,multi-format,security", "",
     "Hosted package registry supporting many formats with security scanning.",
     "Размещённый реестр пакетов с поддержкой множества форматов и сканированием безопасности.",
     "Hosted means no registry to operate, which is most of the cost of running Artifactory."),
    ("lib-github-packages", "GitHub Packages", "Разработка и DevOps", "https://docs.github.com/en/packages", "freeTier", "registry,github,integrated,multi-format", "",
     "Package registry integrated with GitHub repositories and permissions.",
     "Реестр пакетов, интегрированный с репозиториями и правами GitHub.",
     "Repository permissions carry over to packages, so there is no second access model to manage."),

    # ---------- Ускорение сборки ----------
    ("lib-depot", "Depot", "Разработка и DevOps", "https://depot.dev/docs", "freeTier", "docker-builds,cache,fast,remote", "",
     "Remote container build service with persistent layer caching.",
     "Удалённый сервис сборки контейнеров с постоянным кэшем слоёв.",
     "Persistent cache across CI runs is what GitHub Actions runners cannot provide natively."),
    ("lib-buildjet", "BuildJet", "Разработка и DevOps", "https://buildjet.com/for-github-actions/docs", "paid", "github-actions,runners,fast,arm", "",
     "Faster GitHub Actions runners, including Arm machines.",
     "Более быстрые раннеры GitHub Actions, включая машины Arm.",
     "Swapping the runs-on label is the entire migration, which makes it easy to trial."),
    ("lib-namespace-so", "Namespace", "Разработка и DevOps", "https://namespace.so/docs", "freeTier", "runners,caching,builds,fast", "",
     "Fast CI runners with built-in caching and container builds.",
     "Быстрые CI-раннеры со встроенным кэшированием и сборкой контейнеров.",
     "Its cache volumes persist between runs, which removes most dependency install time."),
    ("lib-blacksmith", "Blacksmith", "Разработка и DevOps", "https://docs.blacksmith.sh/", "freeTier", "github-actions,gaming-cpus,fast,drop-in", "",
     "Drop-in GitHub Actions runners on high-frequency processors.",
     "Раннеры GitHub Actions на высокочастотных процессорах с простой заменой.",
     "Single-threaded build steps benefit most, since clock speed is what it optimizes for."),
    ("lib-warpbuild", "WarpBuild", "Разработка и DevOps", "https://docs.warpbuild.com/", "freeTier", "runners,byoc,fast,github-actions", "",
     "Faster CI runners, optionally running in your own cloud account.",
     "Более быстрые CI-раннеры, опционально в вашем собственном облачном аккаунте.",
     "Running in your own account keeps build machines inside your network boundary."),
    ("lib-actuated", "Actuated", "Разработка и DevOps", "https://docs.actuated.com/", "paid", "firecracker,self-hosted,secure,github-actions", "",
     "Self-hosted CI runners isolated in Firecracker microVMs.",
     "Self-hosted CI-раннеры, изолированные в microVM Firecracker.",
     "VM isolation per job is what makes self-hosted runners safe for public repositories."),

    # ---------- Git-форжи ----------
    ("lib-gitea", "Gitea", "Git и совместная работа", "https://docs.gitea.com/", "openSource", "self-host,lightweight,git,actions", "",
     "Lightweight self-hosted Git service with built-in CI.",
     "Лёгкий self-hosted Git-сервис со встроенным CI.",
     "It runs comfortably on a very small server, which GitLab never has."),
    ("lib-forgejo", "Forgejo", "Git и совместная работа", "https://forgejo.org/docs/latest/", "openSource", "gitea-fork,community,federation,self-host", "",
     "Community-governed fork of Gitea, working toward federation.",
     "Форк Gitea под управлением сообщества, движущийся к федерации.",
     "Forked over governance concerns, and it remains largely drop-in compatible with Gitea."),
    ("lib-gitlab-ce", "GitLab Community Edition", "Git и совместная работа", "https://docs.gitlab.com/", "openSource", "self-host,devops-platform,ci,complete", "",
     "Self-hosted GitLab covering repositories, CI, registry and issues.",
     "Self-hosted GitLab с репозиториями, CI, реестром и задачами.",
     "One platform replaces several services, at a substantial memory and operational cost."),
    ("lib-onedev", "OneDev", "Git и совместная работа", "https://docs.onedev.io/", "openSource", "self-host,ci,code-search,lightweight", "",
     "Self-hosted Git server with built-in CI and symbol-level code search.",
     "Self-hosted Git-сервер со встроенным CI и поиском по символам кода.",
     "Its code search understands symbols rather than text, which few self-hosted forges offer."),
    ("lib-sourcehut", "SourceHut", "Git и совместная работа", "https://man.sr.ht/", "mixed", "minimal,email-workflow,no-javascript,fast", "",
     "Minimal software forge built around an email-based patch workflow.",
     "Минималистичная площадка для разработки с рабочим процессом патчей по электронной почте.",
     "Its pages work without JavaScript entirely, which is a deliberate accessibility position."),
    ("lib-codeberg", "Codeberg", "Git и совместная работа", "https://docs.codeberg.org/", "free", "non-profit,forgejo,free,open-source-only", "",
     "Non-profit Git hosting for free and open-source projects.",
     "Некоммерческий хостинг Git для свободных и открытых проектов.",
     "Free with no commercial tier, funded by donations rather than by monetizing your code."),
    ("lib-radicle", "Radicle", "Git и совместная работа", "https://radicle.xyz/guides", "openSource", "peer-to-peer,decentralized,local-first,git", "",
     "Peer-to-peer code collaboration with no central server.",
     "Одноранговая совместная работа над кодом без центрального сервера.",
     "Repositories replicate between peers, so the project survives any single host disappearing."),
]
