# -*- coding: utf-8 -*-
"""Stage 5 library pack AD: media codecs, streaming players, programmatic video, audio/speech."""

LIBS_5AD = [
    # ---------- Медиа: обработка и кодеки ----------
    ("lib-ffmpeg", "FFmpeg", "Видео и медиа", "https://ffmpeg.org/documentation.html", "openSource", "transcoding,codecs,cli,universal", "",
     "The universal multimedia toolkit for decoding, encoding and transforming audio and video.",
     "Универсальный мультимедийный инструментарий для декодирования, кодирования и преобразования аудио и видео.",
     "Almost every video product wraps it — learning its filter graph syntax pays off across all of them."),
    ("lib-gstreamer", "GStreamer", "Видео и медиа", "https://gstreamer.freedesktop.org/documentation/", "openSource", "pipeline,streaming,plugins,realtime", "",
     "Pipeline-based multimedia framework for building streaming and processing applications.",
     "Мультимедийный фреймворк на пайплайнах для построения потоковых и обрабатывающих приложений.",
     "Better suited than FFmpeg for live pipelines where elements are reconfigured while running."),
    ("lib-libvpx", "libvpx", "Видео и медиа", "https://www.webmproject.org/code/", "openSource", "vp8,vp9,webm,codec", "",
     "Reference encoder and decoder for the VP8 and VP9 video codecs.",
     "Эталонный кодировщик и декодировщик видеокодеков VP8 и VP9.",
     "VP9 is royalty-free with broad browser support, which is why WebM builds on it."),
    ("lib-svt-av1", "SVT-AV1", "Видео и медиа", "https://gitlab.com/AOMediaCodec/SVT-AV1", "openSource", "av1,encoder,performance,royalty-free", "",
     "Fast, scalable AV1 encoder suited to production transcoding workloads.",
     "Быстрый масштабируемый AV1-кодировщик, пригодный для продакшн-транскодирования.",
     "AV1 cuts bitrate substantially versus H.264, at a real cost in encoding time — measure both."),
    ("lib-x264", "x264", "Видео и медиа", "https://www.videolan.org/developers/x264.html", "openSource", "h264,encoder,quality,standard", "",
     "The reference free H.264 encoder, still the compatibility baseline for video delivery.",
     "Эталонный свободный кодировщик H.264, до сих пор базовый уровень совместимости для доставки видео.",
     "Still the safest fallback rendition — every device made in the last fifteen years decodes it."),
    ("lib-mediamtx", "MediaMTX", "Стриминг видео", "https://github.com/bluenviron/mediamtx", "openSource", "rtsp,webrtc,srt,server", "",
     "Zero-dependency media server bridging RTSP, RTMP, WebRTC, HLS and SRT.",
     "Медиасервер без зависимостей, связывающий RTSP, RTMP, WebRTC, HLS и SRT.",
     "Converting between protocols in one binary replaces a surprising amount of streaming infrastructure."),
    ("lib-obs-websocket", "OBS WebSocket", "Стриминг видео", "https://github.com/obsproject/obs-websocket", "openSource", "obs,remote-control,automation,streaming", "",
     "Remote control API for OBS Studio scenes, sources and recording.",
     "API удалённого управления сценами, источниками и записью в OBS Studio.",
     "Makes automated scene switching and recording possible without touching the OBS interface."),

    # ---------- Плееры и воспроизведение ----------
    ("lib-shaka-player", "Shaka Player", "Стриминг видео", "https://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html", "openSource", "dash,hls,drm,google", "npm i shaka-player",
     "Google's adaptive streaming player with built-in DRM support.",
     "Плеер адаптивного стриминга от Google со встроенной поддержкой DRM.",
     "Its EME integration is the reason to pick it when protected content is a requirement."),
    ("lib-vidstack", "Vidstack", "Стриминг видео", "https://vidstack.io/docs/player", "openSource", "player,web-components,customizable,accessible", "npm i @vidstack/react",
     "Modern customizable media player built from web components.",
     "Современный настраиваемый медиаплеер на веб-компонентах.",
     "Its headless mode gives you the player logic while you own every pixel of the interface."),

    # ---------- Программное видео и графика ----------
    ("lib-remotion", "Remotion", "Видео и медиа", "https://www.remotion.dev/docs/", "mixed", "react,video,programmatic,rendering", "npx create-video@latest",
     "Creates videos programmatically using React components and rendering them frame by frame.",
     "Создаёт видео программно из React-компонентов, рендеря их покадрово.",
     "Data-driven videos (personalized reports, generated clips) are where it beats a video editor entirely."),
    ("lib-manim", "Manim", "Анимация и 3D", "https://docs.manim.community/", "openSource", "math,animation,python,educational", "pip install manim",
     "Animation engine for mathematical and explanatory visualizations.",
     "Движок анимации для математических и объясняющих визуализаций.",
     "Rendering is slow — build scenes at low quality and raise it only for the final export."),
    ("lib-editly", "Editly", "Видео и медиа", "https://github.com/mifi/editly", "openSource", "video-editing,declarative,ffmpeg,node", "npm i editly",
     "Declarative video editing from a JSON specification, built on FFmpeg.",
     "Декларативный видеомонтаж по JSON-спецификации на базе FFmpeg.",
     "Describing the edit as data makes batch-generating many similar videos straightforward."),

    # ---------- Аудио: обработка ----------
    ("lib-essentia", "Essentia", "Аудио и голос", "https://essentia.upf.edu/documentation.html", "openSource", "audio-analysis,mir,features,research", "",
     "Audio analysis library for music information retrieval and feature extraction.",
     "Библиотека аудиоанализа для music information retrieval и извлечения признаков.",
     "Covers rhythm, key and mood descriptors that general audio libraries do not attempt."),
    ("lib-soundfile", "SoundFile", "Аудио и голос", "https://python-soundfile.readthedocs.io/", "openSource", "python,audio-io,formats,numpy", "pip install soundfile",
     "Reads and writes audio files into NumPy arrays across many formats.",
     "Читает и записывает аудиофайлы в массивы NumPy во множестве форматов.",
     "Faster and more reliable than librosa for plain file I/O, which librosa itself delegates to it for."),
    ("lib-demucs", "Demucs", "Аудио и голос", "https://github.com/adefossez/demucs", "openSource", "stem-separation,music,pytorch,research", "pip install demucs",
     "State-of-the-art music source separation splitting tracks into stems.",
     "Передовое разделение музыкальных источников на отдельные стемы.",
     "Runs locally, so a large back catalogue costs GPU time rather than per-minute service fees."),
    ("lib-spleeter", "Spleeter", "Аудио и голос", "https://github.com/deezer/spleeter", "openSource", "stem-separation,deezer,tensorflow,fast", "pip install spleeter",
     "Deezer's fast source separation tool for splitting vocals and instruments.",
     "Быстрый инструмент разделения источников от Deezer для отделения вокала и инструментов.",
     "Faster than Demucs but noticeably lower quality — pick by whether throughput or fidelity matters."),

    # ---------- Речь: распознавание и синтез ----------
    ("lib-whisper-cpp", "whisper.cpp", "Аудио и голос", "https://github.com/ggml-org/whisper.cpp", "openSource", "speech-to-text,local,cpu,ggml", "",
     "Whisper speech recognition in plain C++, running on CPU with no Python.",
     "Распознавание речи Whisper на чистом C++, работает на CPU без Python.",
     "Runs on a phone or laptop with no GPU, which is what makes on-device transcription practical."),
    ("lib-silero-vad", "Silero VAD", "Аудио и голос", "https://github.com/snakers4/silero-vad", "openSource", "vad,speech-detection,lightweight,realtime", "pip install silero-vad",
     "Fast, tiny voice activity detector for finding speech segments in audio.",
     "Быстрый крошечный детектор голосовой активности для поиска речевых сегментов в аудио.",
     "Trimming silence before transcription cuts both cost and hallucinated text on empty audio."),
    ("lib-piper-tts", "Piper TTS", "Аудио и голос", "https://github.com/OHF-Voice/piper1-gpl", "openSource", "tts,local,fast,raspberry-pi", "pip install piper-tts",
     "Fast local neural text-to-speech that runs well even on a Raspberry Pi.",
     "Быстрый локальный нейросетевой синтез речи, работающий даже на Raspberry Pi.",
     "The default choice for offline voice assistants where cloud TTS latency is unacceptable."),
    ("lib-coqui-tts", "Coqui TTS", "Аудио и голос", "https://github.com/coqui-ai/TTS", "openSource", "tts,voice-cloning,multilingual,research", "pip install TTS",
     "Text-to-speech toolkit with multilingual models and voice cloning.",
     "Набор инструментов синтеза речи с многоязычными моделями и клонированием голоса.",
     "The company shut down but the models remain widely used — expect no new upstream releases."),
    ("lib-kokoro-tts", "Kokoro TTS", "Аудио и голос", "https://github.com/hexgrad/kokoro", "openSource", "tts,lightweight,quality,apache", "pip install kokoro",
     "Small open-weight text-to-speech model with quality well above its parameter count.",
     "Небольшая модель синтеза речи с открытыми весами и качеством выше её размера.",
     "Under a hundred million parameters, so it runs in real time on a CPU."),
    ("lib-bark-tts", "Bark", "Аудио и голос", "https://github.com/suno-ai/bark", "openSource", "tts,generative,expressive,suno", "pip install git+https://github.com/suno-ai/bark.git",
     "Generative audio model producing expressive speech, sound effects and music cues.",
     "Генеративная аудиомодель, создающая выразительную речь, звуковые эффекты и музыкальные фрагменты.",
     "Nondeterministic by design — regenerate for a different take rather than expecting exact repeats."),
    ("lib-rvc", "RVC (Retrieval-based Voice Conversion)", "Аудио и голос", "https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI", "openSource", "voice-conversion,cloning,realtime,training", "",
     "Voice conversion framework transforming one speaker's voice into another.",
     "Фреймворк конверсии голоса, преобразующий голос одного говорящего в другой.",
     "Cloning a real person's voice needs their consent — many jurisdictions now regulate this explicitly."),
]
