# -*- coding: utf-8 -*-
"""Stage 5 API pack T: databases-as-a-service depth, search, queues, misc backend."""

APIS_5T = [
    # ---------- Базы данных и backend (deepen) ----------
    ("api-supabase-realtime", "Supabase Realtime", "Базы данных и backend", "https://supabase.com/docs/guides/realtime", "freeTier", "realtime,postgres,websockets,broadcast", "",
     "Realtime Postgres change subscriptions, presence and broadcast channels.",
     "Подписки на изменения Postgres в реальном времени, присутствие и broadcast-каналы.",
     "Row Level Security applies to realtime subscriptions too — a missing policy leaks rows over the socket."),
    ("api-firebase-firestore", "Cloud Firestore", "Базы данных и backend", "https://firebase.google.com/docs/firestore", "freeTier", "nosql,realtime,offline,google", "",
     "Realtime document database with offline persistence built into the client SDKs.",
     "Документная база реального времени со встроенной офлайн-персистентностью в клиентских SDK.",
     "Design around its query limitations early — no joins and limited compound queries shape the data model."),
    ("api-mongodb-atlas-2", "MongoDB Atlas Search", "Поиск и retrieval", "https://www.mongodb.com/docs/atlas/atlas-search/", "freeTier", "search,mongodb,lucene,full-text", "",
     "Full-text and vector search built into MongoDB Atlas, no separate search cluster.",
     "Полнотекстовый и векторный поиск внутри MongoDB Atlas, без отдельного поискового кластера.",
     "Avoids running Elasticsearch alongside Mongo, which removes a whole sync pipeline and its failure modes."),
    ("api-fauna", "Fauna", "Базы данных и backend", "https://docs.fauna.com/", "freeTier", "serverless,distributed,fql,transactions", "",
     "Distributed serverless document-relational database with strong consistency.",
     "Распределённая serverless документно-реляционная база данных со строгой согласованностью.",
     "Global strong consistency without manual replica management is its main differentiator."),
    ("api-tigrisdata", "Tigris", "Базы данных и backend", "https://www.tigrisdata.com/docs/", "freeTier", "object-storage,s3,globally-distributed,edge", "",
     "S3-compatible object storage distributed globally with no egress fees.",
     "S3-совместимое объектное хранилище с глобальным распределением и без платы за исходящий трафик.",
     "No egress fees changes the economics for media-heavy applications compared to AWS S3."),
    ("api-clickhouse-2", "ClickHouse", "Data engineering", "https://clickhouse.com/docs", "openSource", "olap,columnar,analytics,fast", "",
     "Columnar OLAP database designed for very fast analytical queries at scale.",
     "Колоночная OLAP-база данных для очень быстрых аналитических запросов на масштабе.",
     "Its performance depends heavily on choosing the right ORDER BY key — that decision is hard to change later."),
    ("api-questdb", "QuestDB", "Data engineering", "https://questdb.com/docs/", "openSource", "timeseries,sql,fast,ingestion", "",
     "High-performance time-series database with SQL and fast ingestion.",
     "Высокопроизводительная база временных рядов с SQL и быстрым приёмом данных.",
     "Its SQL extensions for time-series (SAMPLE BY, LATEST ON) remove a lot of window-function boilerplate."),
    ("api-timescaledb", "TimescaleDB", "Data engineering", "https://docs.timescale.com/", "openSource", "timeseries,postgres,extension,hypertables", "",
     "Time-series extension for PostgreSQL, keeping full SQL and the Postgres ecosystem.",
     "Расширение временных рядов для PostgreSQL с сохранением полного SQL и экосистемы Postgres.",
     "Choosing this over a dedicated TSDB means keeping joins with your relational data, which often matters more."),
    ("api-influxdb", "InfluxDB", "Data engineering", "https://docs.influxdata.com/", "freeTier", "timeseries,metrics,iot,monitoring", "",
     "Purpose-built time-series database for metrics, events and IoT sensor data.",
     "Специализированная база временных рядов для метрик, событий и данных IoT-датчиков.",
     "Retention policies and downsampling are essential — raw high-frequency data grows unmanageably fast."),
    ("api-neo4j-aura", "Neo4j AuraDB", "Базы данных и backend", "https://neo4j.com/docs/aura/", "freeTier", "graph,cypher,managed,relationships", "",
     "Managed graph database service with the Cypher query language.",
     "Управляемый сервис графовой базы данных с языком запросов Cypher.",
     "Graph databases win specifically on multi-hop relationship queries that become expensive joins in SQL."),
    ("api-dgraph", "Dgraph", "Базы данных и backend", "https://dgraph.io/docs/", "openSource", "graph,graphql,distributed,native", "",
     "Distributed graph database with native GraphQL support.",
     "Распределённая графовая база данных с нативной поддержкой GraphQL.",
     "Its GraphQL-native model removes the resolver layer most graph databases still require."),
    ("api-surrealdb", "SurrealDB", "Базы данных и backend", "https://surrealdb.com/docs", "openSource", "multi-model,rust,realtime,graph", "",
     "Multi-model database combining document, graph and relational in one engine.",
     "Мультимодельная база данных, объединяющая документную, графовую и реляционную модели в одном движке.",
     "Its embedded mode runs in-process, which suits local-first apps as well as server deployments."),

    # ---------- Поиск и retrieval (deepen) ----------
    ("api-orama", "Orama", "Поиск и retrieval", "https://docs.orama.com/", "openSource", "search,javascript,in-memory,edge", "npm i @orama/orama",
     "Full-text, vector and hybrid search engine running in JavaScript, including in the browser.",
     "Полнотекстовый, векторный и гибридный поисковый движок на JavaScript, работает и в браузере.",
     "Running search entirely client-side removes both server cost and query latency for modest datasets."),
    ("api-pagefind", "Pagefind", "Поиск и retrieval", "https://pagefind.app/docs/", "openSource", "static-search,indexing,low-bandwidth,ssg", "",
     "Static site search that indexes at build time and loads index fragments on demand.",
     "Поиск по статическим сайтам с индексацией на этапе сборки и загрузкой фрагментов индекса по требованию.",
     "It downloads only the index chunks a query needs, so large sites stay searchable without a server."),
    ("api-lunr", "Lunr.js", "Поиск и retrieval", "https://lunrjs.com/docs/index.html", "openSource", "search,client-side,javascript,small", "npm i lunr",
     "Small client-side full-text search library, a JavaScript take on Solr's ideas.",
     "Небольшая клиентская библиотека полнотекстового поиска, JavaScript-интерпретация идей Solr.",
     "Index size grows quickly — beyond a few thousand documents, prefer Pagefind's chunked approach."),
    ("api-zincsearch", "ZincSearch", "Поиск и retrieval", "https://zincsearch-docs.zinc.dev/", "openSource", "search,lightweight,elasticsearch-alternative,go", "",
     "Lightweight search engine in Go, a simpler alternative to Elasticsearch.",
     "Лёгкий поисковый движок на Go, более простая альтернатива Elasticsearch.",
     "Single binary with far lower resource use, which suits small deployments Elasticsearch would dominate."),
]
