# -*- coding: utf-8 -*-
"""Stage 5 API pack J: auth depth, storage/CDN, edge compute, misc infra."""

APIS_5J = [
    # ---------- Аутентификация (deepen) ----------
    ("api-stytch", "Stytch", "Аутентификация", "https://stytch.com/docs", "freeTier", "auth,passwordless,magic-links,b2b", "",
     "Passwordless-first auth: magic links, OTP, passkeys and B2B organization support.",
     "Аутентификация без паролей: magic links, OTP, passkeys и поддержка B2B-организаций.",
     "Its B2B product models organizations and SSO natively, unlike bolting orgs onto a consumer auth product."),
    ("api-supertokens", "SuperTokens", "Аутентификация", "https://supertokens.com/docs", "openSource", "auth,open-source,self-host,sessions", "",
     "Open-source auth with self-hosting, session management and social login.",
     "Открытая аутентификация с self-hosting, управлением сессиями и социальным входом.",
     "Self-hosting the core removes per-MAU pricing entirely, which matters once user counts grow."),
    ("api-kinde", "Kinde", "Аутентификация", "https://docs.kinde.com/", "freeTier", "auth,b2b,saas,feature-flags", "",
     "Auth built for SaaS: organizations, roles, permissions and feature flags together.",
     "Аутентификация для SaaS: организации, роли, разрешения и feature-флаги в одном месте.",
     "Combining auth and feature flags in one service removes a common two-vendor integration for early SaaS."),
    ("api-descope", "Descope", "Аутентификация", "https://docs.descope.com/", "freeTier", "auth,flows,drag-drop,passwordless", "",
     "Auth platform with a visual flow builder for designing login and signup journeys.",
     "Платформа аутентификации с визуальным конструктором потоков входа и регистрации.",
     "Change an auth flow (add MFA, change ordering) in the visual editor without redeploying your app."),
    ("api-fusionauth", "FusionAuth", "Аутентификация", "https://fusionauth.io/docs/", "freeTier", "auth,self-host,oauth,enterprise", "",
     "Full-featured auth server, free when self-hosted with no user-count limit.",
     "Полнофункциональный сервер аутентификации, бесплатен при self-hosting без лимита пользователей.",
     "The self-hosted community edition has no MAU cap at all — unusual among auth vendors."),

    # ---------- Облако и деплой (deepen) ----------
    ("api-cloudflare-workers-2", "Cloudflare Durable Objects", "Облако и деплой", "https://developers.cloudflare.com/durable-objects/", "mixed", "edge,stateful,coordination,cloudflare", "",
     "Strongly consistent stateful objects at the edge, for coordination and real-time state.",
     "Строго согласованные объекты с состоянием на edge для координации и состояния в реальном времени.",
     "Each object is single-threaded and globally unique — ideal for per-room or per-document coordination."),
    ("api-deno-deploy", "Deno Deploy", "Облако и деплой", "https://docs.deno.com/deploy/manual/", "freeTier", "edge,deno,serverless,typescript", "",
     "Globally distributed serverless runtime for TypeScript and JavaScript, no build step.",
     "Глобально распределённый serverless-рантайм для TypeScript и JavaScript без этапа сборки.",
     "Deploys straight from a GitHub repo with no bundler config — TypeScript runs as-is."),
    ("api-koyeb", "Koyeb", "Облако и деплой", "https://www.koyeb.com/docs", "freeTier", "serverless,containers,global,deploy", "",
     "Serverless platform for containers and functions with global edge deployment.",
     "Serverless-платформа для контейнеров и функций с глобальным edge-деплоем.",
     "It runs plain Docker images, so migrating off it later is just moving the same container elsewhere."),
    ("api-porter-run", "Porter", "Облако и деплой", "https://docs.porter.run/", "mixed", "kubernetes,paas,aws,deploy", "",
     "PaaS layer that deploys into your own AWS/GCP account, combining Heroku UX with cloud ownership.",
     "PaaS-слой, разворачивающий в твой собственный аккаунт AWS/GCP — UX Heroku с владением облаком.",
     "Infrastructure stays in your cloud account, so leaving Porter does not mean migrating the workloads."),
    ("api-northflank", "Northflank", "Облако и деплой", "https://northflank.com/docs", "freeTier", "paas,containers,databases,ci", "",
     "Platform combining container deployment, managed databases and build pipelines.",
     "Платформа, объединяющая деплой контейнеров, управляемые базы данных и пайплайны сборки.",
     "Its free tier includes a managed database, which is rare — most free PaaS tiers exclude persistence."),

    # ---------- Базы данных и backend (deepen) ----------
    ("api-planetscale-2", "PlanetScale (Vitess)", "Базы данных и backend", "https://planetscale.com/docs", "paid", "mysql,vitess,scaling,branching", "",
     "Managed MySQL on Vitess with database branching and non-blocking schema changes.",
     "Управляемый MySQL на Vitess с ветвлением базы и неблокирующими изменениями схемы.",
     "Schema changes deploy without locking tables, which is the main reason to pick it over plain RDS MySQL."),
    ("api-cockroachdb", "CockroachDB", "Базы данных и backend", "https://www.cockroachlabs.com/docs/", "freeTier", "distributed,sql,postgres-compatible,resilient", "",
     "Distributed SQL database that survives node and region failures, Postgres wire-compatible.",
     "Распределённая SQL-база, переживающая отказ узлов и регионов, совместима с протоколом Postgres.",
     "Postgres wire compatibility means most Postgres drivers and ORMs work without modification."),
    ("api-xata", "Xata", "Базы данных и backend", "https://xata.io/docs", "freeTier", "postgres,serverless,search,branching", "",
     "Serverless Postgres with built-in full-text search and database branching.",
     "Serverless Postgres со встроенным полнотекстовым поиском и ветвлением базы данных.",
     "Search is built in rather than needing a separate Elasticsearch cluster alongside the database."),
    ("api-convex-dev", "Convex", "Базы данных и backend", "https://docs.convex.dev/", "freeTier", "backend,realtime,typescript,reactive", "npm create convex@latest",
     "Reactive backend where queries auto-update in the UI when underlying data changes.",
     "Реактивный бэкенд, где запросы автоматически обновляются в UI при изменении данных.",
     "Queries are reactive by default — no manual websocket or polling code to keep the UI in sync."),
    ("api-instantdb", "InstantDB", "Базы данных и backend", "https://www.instantdb.com/docs", "freeTier", "realtime,graph,offline-first,sync", "npm i @instantdb/react",
     "Realtime, offline-first database with optimistic updates and automatic sync.",
     "Realtime offline-first база данных с оптимистичными обновлениями и автоматической синхронизацией.",
     "Optimistic local writes make the UI feel instant while sync happens in the background."),
    ("api-electric-sql", "ElectricSQL", "Базы данных и backend", "https://electric-sql.com/docs", "openSource", "sync,postgres,local-first,offline", "",
     "Postgres sync engine for local-first apps: query a local copy, sync changes automatically.",
     "Движок синхронизации Postgres для local-first приложений: запросы к локальной копии, автосинхронизация.",
     "Local-first means reads never hit the network — the tradeoff is designing for eventual consistency."),

    # ---------- Изображения и дизайн: storage/CDN ----------
    ("api-uploadcare", "Uploadcare", "Изображения и дизайн", "https://uploadcare.com/docs/", "freeTier", "upload,cdn,transform,widget", "",
     "File uploading, storage, transformation and CDN delivery with a drop-in upload widget.",
     "Загрузка, хранение, трансформация и CDN-доставка файлов с готовым виджетом загрузки.",
     "The upload widget handles resumable uploads and camera/social sources without custom UI work."),
    ("api-bunny-net", "Bunny.net", "Изображения и дизайн", "https://docs.bunny.net/", "paid", "cdn,storage,video,cheap", "",
     "Low-cost CDN, object storage and video delivery, priced well below the big providers.",
     "Недорогой CDN, объектное хранилище и доставка видео, заметно дешевле крупных провайдеров.",
     "Its per-GB pricing is often several times cheaper than Cloudflare or Fastly for straightforward CDN needs."),
    ("api-transloadit", "Transloadit", "Изображения и дизайн", "https://transloadit.com/docs/", "mixed", "encoding,files,pipelines,media", "",
     "File processing pipelines: resize, transcode, watermark, virus-scan in one assembly.",
     "Пайплайны обработки файлов: ресайз, транскодирование, водяные знаки, антивирус в одной сборке.",
     "Templates define the pipeline server-side, so the client only uploads and never sends processing params."),
]
