# -*- coding: utf-8 -*-
"""Stage 5 API pack N: analytics/BI, feature stores, testing services, misc dev infra."""

APIS_5N = [
    # ---------- Мониторинг и аналитика: BI ----------
    ("api-metabase", "Metabase", "Мониторинг и аналитика", "https://www.metabase.com/docs/latest/", "openSource", "bi,dashboards,sql,self-host", "",
     "Open-source business intelligence: dashboards and questions over your database.",
     "Открытая BI-система: дашборды и вопросы к вашей базе данных.",
     "Non-technical users can build questions without SQL, which is why it beats a hand-built admin dashboard."),
    ("api-superset", "Apache Superset", "Мониторинг и аналитика", "https://superset.apache.org/docs/intro", "openSource", "bi,dashboards,visualization,apache", "",
     "Enterprise-grade open-source data exploration and visualization platform.",
     "Открытая платформа исследования и визуализации данных корпоративного уровня.",
     "Heavier to operate than Metabase but handles far larger datasets and more chart types."),
    ("api-lightdash", "Lightdash", "Мониторинг и аналитика", "https://docs.lightdash.com/", "openSource", "bi,dbt,metrics,self-host", "",
     "BI layer built directly on top of your dbt project's metric definitions.",
     "BI-слой прямо поверх определений метрик вашего dbt-проекта.",
     "Metrics stay defined in dbt, so BI and pipelines never disagree about what a number means."),
    ("api-cube-dev", "Cube", "Мониторинг и аналитика", "https://cube.dev/docs", "openSource", "semantic-layer,metrics,api,caching", "",
     "Semantic layer exposing consistent metrics over your warehouse via REST, GraphQL and SQL.",
     "Семантический слой, отдающий согласованные метрики поверх хранилища через REST, GraphQL и SQL.",
     "One metric definition serves every consumer, which stops each dashboard reinventing 'active user'."),
    ("api-amplitude", "Amplitude", "CDP и маркетинг-данные", "https://amplitude.com/docs/apis", "freeTier", "product-analytics,events,cohorts,funnels", "",
     "Product analytics with cohort analysis, funnels and behavioral segmentation.",
     "Продуктовая аналитика с когортным анализом, воронками и поведенческой сегментацией.",
     "Design your event taxonomy before instrumenting — renaming events later loses historical continuity."),
    ("api-mixpanel", "Mixpanel", "CDP и маркетинг-данные", "https://developer.mixpanel.com/reference/overview", "freeTier", "product-analytics,events,funnels,retention", "",
     "Event-based product analytics focused on funnels and retention.",
     "Событийная продуктовая аналитика с фокусом на воронки и удержание.",
     "Send events server-side where accuracy matters — client-side events are lost to ad blockers."),

    # ---------- Data engineering (deepen) ----------
    ("api-feast", "Feast", "Data engineering", "https://docs.feast.dev/", "openSource", "feature-store,ml,serving,training", "pip install feast",
     "Open-source feature store keeping training and serving features consistent.",
     "Открытый feature store, поддерживающий согласованность признаков между обучением и инференсом.",
     "Training/serving skew is the bug it exists to prevent — the same feature definition serves both paths."),
    ("api-tecton", "Tecton", "Data engineering", "https://docs.tecton.ai/", "paid", "feature-store,ml,streaming,enterprise", "",
     "Managed feature platform for real-time ML with streaming feature pipelines.",
     "Управляемая платформа признаков для real-time ML с потоковыми пайплайнами.",
     "Its streaming feature support is the main reason to pay over self-hosting Feast."),
    ("api-estuary", "Estuary Flow", "Data engineering", "https://docs.estuary.dev/", "freeTier", "cdc,streaming,etl,real-time", "",
     "Real-time data integration with change data capture from databases to warehouses.",
     "Интеграция данных в реальном времени с CDC из баз данных в хранилища.",
     "CDC captures every change rather than periodic snapshots, which matters for audit and real-time use cases."),
    ("api-materialize", "Materialize", "Data engineering", "https://materialize.com/docs/", "freeTier", "streaming,sql,incremental,views", "",
     "Streaming database maintaining incrementally updated materialized views in SQL.",
     "Потоковая база данных, поддерживающая инкрементально обновляемые материализованные представления в SQL.",
     "Write a normal SQL view and it stays continuously up to date — no manual refresh scheduling."),
    ("api-risingwave", "RisingWave", "Data engineering", "https://docs.risingwave.com/", "openSource", "streaming,sql,postgres-compatible,incremental", "",
     "Postgres-compatible streaming database, an open-source Materialize alternative.",
     "Потоковая база данных, совместимая с Postgres, открытая альтернатива Materialize.",
     "Postgres wire compatibility means existing SQL clients and BI tools connect without changes."),

    # ---------- Тестирование и качество: services ----------
    ("api-browserstack", "BrowserStack", "Тестирование и качество", "https://www.browserstack.com/docs", "paid", "cross-browser,devices,testing,cloud", "",
     "Cloud testing across thousands of real browser and device combinations.",
     "Облачное тестирование на тысячах реальных комбинаций браузеров и устройств.",
     "Real devices, not emulators, is the differentiator — mobile rendering bugs often only appear on real hardware."),
    ("api-saucelabs", "Sauce Labs", "Тестирование и качество", "https://docs.saucelabs.com/", "paid", "cross-browser,selenium,testing,cloud", "",
     "Cloud-based cross-browser and mobile testing with Selenium and Appium support.",
     "Облачное кроссбраузерное и мобильное тестирование с поддержкой Selenium и Appium.",
     "Parallel test execution is what makes a large suite finish in minutes rather than an hour."),
    ("api-lambdatest", "LambdaTest", "Тестирование и качество", "https://www.lambdatest.com/support/docs/", "freeTier", "cross-browser,testing,cloud,free-tier", "",
     "Cross-browser testing platform with a free tier for manual testing.",
     "Платформа кроссбраузерного тестирования с бесплатным тарифом для ручного тестирования.",
     "The free tier's manual live-testing minutes are enough for occasional browser-specific bug reproduction."),
    ("api-codecov", "Codecov", "Тестирование и качество", "https://docs.codecov.com/", "freeTier", "coverage,ci,reports,github", "",
     "Test coverage reporting and PR-level coverage diffs.",
     "Отчёты о покрытии тестами и диффы покрытия на уровне pull request.",
     "Coverage on the diff matters far more than total project coverage — configure the PR check accordingly."),
    ("api-sonarcloud", "SonarCloud", "Тестирование и качество", "https://docs.sonarsource.com/sonarqube-cloud/", "freeTier", "static-analysis,quality-gate,ci,security", "",
     "Hosted code quality and security analysis with quality gates in CI.",
     "Размещённый анализ качества и безопасности кода с quality gates в CI.",
     "Free for public repositories, which makes it easy to add to an open-source project's CI."),

    # ---------- Облако и деплой (deepen) ----------
    ("api-pulumi-cloud", "Pulumi Cloud", "Инфраструктура как код", "https://www.pulumi.com/docs/pulumi-cloud/", "freeTier", "iac,state,secrets,collaboration", "",
     "Managed state backend, secrets and collaboration for Pulumi deployments.",
     "Управляемый бэкенд состояния, секреты и совместная работа для деплоев Pulumi.",
     "Free for individuals — a much safer default than storing IaC state in a shared bucket you manage yourself."),
    ("api-terraform-cloud", "HCP Terraform", "Инфраструктура как код", "https://developer.hashicorp.com/terraform/cloud-docs", "freeTier", "iac,state,runs,collaboration", "",
     "Hosted Terraform state, remote runs and policy enforcement.",
     "Размещённое состояние Terraform, удалённые запуски и применение политик.",
     "Remote state with locking prevents the concurrent-apply corruption that plain S3 backends allow."),
    ("api-spacelift", "Spacelift", "Инфраструктура как код", "https://docs.spacelift.io/", "freeTier", "iac,terraform,policy,automation", "",
     "CI/CD purpose-built for infrastructure as code, with policy-as-code controls.",
     "CI/CD, созданный специально для infrastructure as code, с policy-as-code контролем.",
     "Its OPA policy layer gates risky plans automatically instead of relying on human review to catch them."),
]
