# -*- coding: utf-8 -*-
"""Stage 5 MCP + skills pack F."""

MCPS_5F = [
    ("mcp-openai-agents", "OpenAI Agents SDK MCP", "Инфраструктура MCP", "https://openai.github.io/openai-agents-python/mcp/", "openSource", "openai,agents,mcp,python", "pip install openai-agents",
     "MCP client support inside OpenAI's Agents SDK, connecting the same servers.",
     "Поддержка MCP-клиента в OpenAI Agents SDK, подключает те же серверы.",
     "One MCP server works across Claude, OpenAI agents and other hosts — that portability is the point."),
    ("mcp-langchain-adapter", "LangChain MCP Adapters", "Инфраструктура MCP", "https://github.com/langchain-ai/langchain-mcp-adapters", "openSource", "langchain,mcp,tools,adapter", "pip install langchain-mcp-adapters",
     "Converts MCP server tools into LangChain tools usable in existing chains and agents.",
     "Превращает инструменты MCP-серверов в инструменты LangChain для существующих цепочек и агентов.",
     "Lets you reuse the MCP ecosystem without rewriting an existing LangChain application."),
    ("mcp-fastapi-mcp", "FastAPI-MCP", "Инфраструктура MCP", "https://github.com/tadata-org/fastapi_mcp", "openSource", "fastapi,mcp,python,auto-generation", "pip install fastapi-mcp",
     "Exposes an existing FastAPI application's endpoints as MCP tools automatically.",
     "Автоматически отдаёт эндпоинты существующего FastAPI-приложения как MCP-инструменты.",
     "Your OpenAPI descriptions become the tool descriptions, so write them well before exposing them."),
    ("mcp-openapi-server", "OpenAPI MCP Server", "Инфраструктура MCP", "https://github.com/janwilmake/openapi-mcp-server", "openSource", "openapi,mcp,generation,rest", "",
     "Turns any OpenAPI specification into an MCP server without writing server code.",
     "Превращает любую OpenAPI-спецификацию в MCP-сервер без написания кода сервера.",
     "The fastest path to giving an agent access to an internal REST API you already document."),
    ("mcp-mcp-use", "mcp-use", "Инфраструктура MCP", "https://docs.mcp-use.com/", "openSource", "mcp,client,python,agents", "pip install mcp-use",
     "Open-source Python client for connecting any LLM to MCP servers.",
     "Открытый Python-клиент для подключения любой LLM к MCP-серверам.",
     "Useful for building a custom agent host without adopting a full agent framework."),
    ("mcp-glama-directory", "Glama MCP Directory", "Каталоги skills", "https://glama.ai/mcp/servers", "free", "mcp,directory,discovery,index", "",
     "Searchable directory of MCP servers with security and quality signals.",
     "Поисковый каталог MCP-серверов с сигналами безопасности и качества.",
     "Check a community server's activity and inspection results here before installing it."),
    ("mcp-pulse-directory", "PulseMCP", "Каталоги skills", "https://www.pulsemcp.com/servers", "free", "mcp,directory,news,discovery", "",
     "MCP server directory with news and weekly updates on ecosystem changes.",
     "Каталог MCP-серверов с новостями и еженедельными обновлениями об изменениях в экосистеме.",
     "Useful for tracking what is new — the MCP ecosystem moves fast enough that directories go stale."),
]

SKILLS_5F = [
    ("skill-skill-authoring-guide", "Skill Authoring Guide", "Создание skills", "https://docs.claude.com/en/docs/agents-and-tools/agent-skills/best-practices", "free", "skills,authoring,description,triggering", "",
     "How to write a skill's description so it triggers at the right time and not otherwise.",
     "Как написать описание skill, чтобы он срабатывал вовремя и не срабатывал лишний раз.",
     "The description is the entire triggering mechanism — vague descriptions produce skills that never fire."),
    ("skill-progressive-disclosure", "Progressive Disclosure in Skills", "Создание skills", "https://docs.claude.com/en/docs/agents-and-tools/agent-skills/overview", "free", "skills,context,structure,efficiency", "",
     "Structuring a skill so only the needed parts load into context, not everything at once.",
     "Структурирование skill так, чтобы в контекст загружалось только нужное, а не всё сразу.",
     "Keep SKILL.md short and push detail into referenced files the model reads only when relevant."),
    ("skill-claude-in-slack", "Claude in Slack", "Workflow skills", "https://docs.claude.com/en/docs/claude-code/slack", "free", "slack,integration,claude,team", "",
     "Running Claude from Slack channels and threads for team workflows.",
     "Запуск Claude из каналов и тредов Slack для командных процессов.",
     "Thread context carries over, so a discussion can turn into a task without restating the background."),
    ("skill-claude-desktop-extensions", "Claude Desktop Extensions", "Установка и миграция", "https://www.anthropic.com/engineering/desktop-extensions", "free", "desktop,extensions,mcp,packaging", "",
     "Packaging MCP servers as one-click installable desktop extensions.",
     "Упаковка MCP-серверов в устанавливаемые в один клик desktop-расширения.",
     "Removes the manual JSON config step that stops non-technical users adopting MCP servers at all."),
    ("skill-effective-agents-tools", "Tool Design for Agents", "Гайды и практики", "https://www.anthropic.com/engineering/writing-tools-for-agents", "free", "tools,schemas,design,agents", "",
     "Designing tool interfaces an agent can use correctly without trial and error.",
     "Проектирование интерфейсов инструментов, которыми агент пользуется правильно без проб и ошибок.",
     "Consolidate many narrow tools into fewer well-described ones — agents pick wrong among near-identical options."),
    ("skill-agent-evaluation", "Evaluating Agent Systems", "AI-оценка и safety", "https://docs.claude.com/en/docs/test-and-evaluate/eval-tool", "free", "evaluation,agents,testing,metrics", "",
     "Building evaluation sets for agent behavior rather than single-turn output.",
     "Построение оценочных наборов для поведения агента, а не для одиночного ответа.",
     "Evaluate the trajectory, not just the final answer — a right answer via a dangerous path is still a failure."),
]
