# -*- coding: utf-8 -*-
"""Stage 5 API pack A: computer vision, OCR, voice agents, video, sales/marketing ops."""

APIS_5A = [
    # ---------- Компьютерное зрение ----------
    ("api-google-vision", "Google Cloud Vision API", "Компьютерное зрение", "https://cloud.google.com/vision/docs", "mixed", "vision,ocr,labels,faces", "",
     "Image labeling, OCR, face and landmark detection as a managed API.",
     "Разметка изображений, OCR, распознавание лиц и достопримечательностей как управляемый API.",
     "Batch requests: a single call can annotate up to 16 images, which cuts overhead sharply."),
    ("api-aws-rekognition", "Amazon Rekognition", "Компьютерное зрение", "https://docs.aws.amazon.com/rekognition/", "mixed", "vision,faces,moderation,video", "",
     "Image and video analysis: object detection, face comparison, content moderation.",
     "Анализ изображений и видео: детекция объектов, сравнение лиц, модерация контента.",
     "Video analysis is asynchronous via SNS notification — do not poll, subscribe instead."),
    ("api-azure-vision", "Azure AI Vision", "Компьютерное зрение", "https://learn.microsoft.com/azure/ai-services/computer-vision/", "mixed", "vision,ocr,captioning,azure", "",
     "Image analysis, OCR and automatic captioning from Microsoft's vision stack.",
     "Анализ изображений, OCR и автоматическое описание из vision-стека Microsoft.",
     "The Read API handles dense documents far better than the older OCR endpoint — use it by default."),
    ("api-clarifai", "Clarifai", "Компьютерное зрение", "https://docs.clarifai.com/", "freeTier", "vision,models,custom-training,moderation", "",
     "Pretrained and custom-trainable vision models behind one API.",
     "Готовые и дообучаемые модели компьютерного зрения за одним API.",
     "Workflows chain multiple models server-side, so detection plus classification is one call."),
    ("api-roboflow", "Roboflow", "Компьютерное зрение", "https://docs.roboflow.com/", "freeTier", "vision,dataset,training,deploy", "pip install roboflow",
     "Dataset management, annotation and training for custom object-detection models.",
     "Управление датасетами, разметка и обучение своих моделей детекции объектов.",
     "Universe has thousands of public datasets — check there before labeling from scratch."),
    ("api-facepp", "Face++", "Компьютерное зрение", "https://console.faceplusplus.com/documents/", "freeTier", "faces,detection,comparison,attributes", "",
     "Face detection, comparison and attribute analysis with a generous free tier.",
     "Детекция лиц, сравнение и анализ атрибутов с щедрым бесплатным тарифом.",
     "Attribute detection (age, emotion) is a separate paid call from plain detection — check pricing per feature."),

    # ---------- OCR и распознавание документов ----------
    ("api-mindee", "Mindee", "OCR и распознавание документов", "https://developers.mindee.com/", "freeTier", "ocr,receipts,invoices,extraction", "",
     "Pretrained document extraction for receipts, invoices, IDs and passports.",
     "Готовое извлечение данных из чеков, счетов, документов и паспортов.",
     "Try the pretrained endpoints before building a custom model — most document types are covered."),
    ("api-veryfi", "Veryfi", "OCR и распознавание документов", "https://docs.veryfi.com/", "freeTier", "ocr,receipts,invoices,expense", "",
     "Real-time receipt and invoice OCR built for expense-report pipelines.",
     "OCR чеков и счетов в реальном времени, заточенный под пайплайны расходов.",
     "Line-item extraction is the differentiator here versus a generic OCR API."),
    ("api-docparser", "Docparser", "OCR и распознавание документов", "https://docparser.com/api/", "freeTier", "ocr,parsing,templates,pdf", "",
     "Template-based document parsing: draw zones once, extract from every matching document after.",
     "Парсинг документов по шаблонам: один раз размечаешь зоны, дальше извлекается автоматически.",
     "Works best on documents with a stable layout — invoices from the same vendor, not free-form text."),
    ("api-docsumo", "Docsumo", "OCR и распознавание документов", "https://docs.docsumo.com/", "paid", "ocr,documents,automation,extraction", "",
     "Document AI for structured extraction from bank statements, invoices and forms.",
     "Document AI для структурного извлечения из банковских выписок, счетов и форм.",
     "Review-and-correct UI feeds back into the model, so accuracy improves as you use it."),

    # ---------- Голосовые агенты ----------
    ("api-vapi", "Vapi", "Голосовые агенты", "https://docs.vapi.ai/", "freeTier", "voice,agents,realtime,telephony", "",
     "Build and deploy voice agents with sub-second latency over phone or web.",
     "Сборка и деплой голосовых агентов с задержкой менее секунды по телефону или в браузере.",
     "Test in the web playground before connecting a phone number — iteration is much faster."),
    ("api-retell-ai", "Retell AI", "Голосовые агенты", "https://docs.retellai.com/", "freeTier", "voice,agents,telephony,llm", "",
     "Voice agent infrastructure with interruption handling and call analytics.",
     "Инфраструктура голосовых агентов с обработкой перебиваний и аналитикой звонков.",
     "Turn on backchannel words (\"mm-hm\") — it measurably reduces users talking over the agent."),
    ("api-bland-ai", "Bland AI", "Голосовые агенты", "https://docs.bland.ai/", "mixed", "voice,agents,telephony,outbound", "",
     "Programmable phone calls with a conversational AI agent, inbound and outbound.",
     "Программируемые телефонные звонки с разговорным ИИ-агентом, входящие и исходящие.",
     "Pathways let you script deterministic branches for compliance-sensitive call flows."),
    ("api-livekit-agents", "LiveKit Agents", "Голосовые агенты", "https://docs.livekit.io/agents/", "openSource", "voice,realtime,webrtc,self-host", "pip install livekit-agents",
     "Open-source framework for real-time voice agents on top of LiveKit's WebRTC infrastructure.",
     "Открытый фреймворк голосовых агентов реального времени поверх WebRTC-инфраструктуры LiveKit.",
     "Self-hostable end to end, which matters if a compliance rule blocks a third-party voice vendor."),
    ("lib-pipecat", "Pipecat", "Голосовые агенты", "https://docs.pipecat.ai/", "openSource", "voice,pipeline,realtime,python", "pip install pipecat-ai",
     "Python framework for composing real-time voice and multimodal agent pipelines.",
     "Python-фреймворк для сборки пайплайнов голосовых и мультимодальных агентов в реальном времени.",
     "Swap the STT/LLM/TTS stage independently — the pipeline model is the whole point."),
    ("api-openai-realtime", "OpenAI Realtime API", "Голосовые агенты", "https://platform.openai.com/docs/guides/realtime", "paid", "voice,realtime,websocket,openai", "",
     "Low-latency speech-to-speech over a persistent WebSocket connection.",
     "Speech-to-speech с низкой задержкой через постоянное WebSocket-соединение.",
     "Server-side VAD (voice activity detection) removes the need to manage turn-taking yourself."),

    # ---------- Видеоконференции ----------
    ("api-daily-co", "Daily", "Видеоконференции", "https://docs.daily.co/", "freeTier", "video,webrtc,sdk,realtime", "",
     "Embeddable WebRTC video calls with a prebuilt UI or a full custom SDK.",
     "Встраиваемые видеозвонки на WebRTC с готовым UI или полным кастомным SDK.",
     "The prebuilt call UI ships a working room in one line — start there before the custom SDK."),
    ("api-livekit", "LiveKit", "Видеоконференции", "https://docs.livekit.io/", "openSource", "webrtc,video,sfu,self-host", "",
     "Open-source WebRTC infrastructure (SFU) for scalable real-time video and audio.",
     "Открытая WebRTC-инфраструктура (SFU) для масштабируемого видео и аудио в реальном времени.",
     "Self-host the SFU or use LiveKit Cloud — the client SDK code is identical either way."),
    ("api-agora", "Agora", "Видеоконференции", "https://docs.agora.io/", "freeTier", "video,voice,rtc,streaming", "",
     "Real-time engagement APIs for video, voice and interactive live streaming.",
     "API реального времени для видео, голоса и интерактивных live-трансляций.",
     "10,000 free minutes per month covers most prototypes without a card on file."),
    ("api-twilio-video", "Twilio Video", "Видеоконференции", "https://www.twilio.com/docs/video", "mixed", "video,webrtc,rooms,twilio", "",
     "Programmable video rooms from the team behind Twilio's messaging and voice APIs.",
     "Программируемые видеокомнаты от команды Twilio, известной по messaging и voice API.",
     "Group Rooms scale automatically to an SFU — no separate setup needed as participants grow."),
    ("api-zoom-sdk", "Zoom Video SDK", "Видеоконференции", "https://developers.zoom.us/docs/video-sdk/", "mixed", "video,sdk,embed,zoom", "",
     "Embed Zoom's video infrastructure directly into your own app UI.",
     "Встраивание видео-инфраструктуры Zoom прямо в интерфейс своего приложения.",
     "This is the SDK, not the Meeting API — use it when you want your own UI, not a Zoom-branded window."),
    ("api-100ms", "100ms", "Видеоконференции", "https://www.100ms.live/docs", "freeTier", "video,live,sdk,interactive", "",
     "Live video SDK for interactive streaming: audio rooms, watch parties, virtual events.",
     "SDK живого видео для интерактивных трансляций: аудиокомнаты, совместный просмотр, виртуальные события.",
     "Prebuilt UI kits cover the common layouts (grid, spotlight) without custom CSS work."),

    # ---------- Стриминг видео ----------
    ("api-mux-video", "Mux Video", "Стриминг видео", "https://docs.mux.com/", "mixed", "video,streaming,encoding,analytics", "",
     "Upload, encode and stream video with built-in analytics, no infrastructure to run.",
     "Загрузка, кодирование и стриминг видео со встроенной аналитикой, без своей инфраструктуры.",
     "Direct uploads from the browser skip your server entirely — check the direct-upload guide first."),
    ("api-cloudflare-stream", "Cloudflare Stream", "Стриминг видео", "https://developers.cloudflare.com/stream/", "mixed", "video,streaming,cdn,cloudflare", "",
     "Video hosting and adaptive streaming on Cloudflare's global network.",
     "Хостинг и адаптивный стриминг видео на глобальной сети Cloudflare.",
     "Pricing is per-minute-stored plus per-minute-delivered — predictable compared to per-GB egress."),
    ("api-api-video", "api.video", "Стриминг видео", "https://docs.api.video/", "freeTier", "video,streaming,upload,player", "",
     "Video hosting API aimed squarely at developers, with a generous free tier.",
     "API хостинга видео, ориентированный на разработчиков, с щедрым бесплатным тарифом.",
     "Live streaming and VOD share the same player embed code, which simplifies the frontend."),
    # ---------- CRM и продажи ----------
    ("api-hubspot", "HubSpot API", "CRM и продажи", "https://developers.hubspot.com/docs/api/overview", "freeTier", "crm,marketing,contacts,deals", "",
     "CRM, marketing and sales objects (contacts, deals, tickets) behind one REST/GraphQL API.",
     "Объекты CRM, маркетинга и продаж (контакты, сделки, тикеты) за одним REST/GraphQL API.",
     "Use the free developer test account before touching a production HubSpot portal."),
    ("api-salesforce", "Salesforce REST API", "CRM и продажи", "https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/", "paid", "crm,enterprise,soql,salesforce", "",
     "Enterprise CRM data and automation via REST, backed by the SOQL query language.",
     "Данные и автоматизация корпоративного CRM через REST, с языком запросов SOQL.",
     "A free Developer Edition org gives full API access for building and testing integrations."),
    ("api-pipedrive", "Pipedrive API", "CRM и продажи", "https://developers.pipedrive.com/docs/api/v1", "freeTier", "crm,pipeline,deals,sales", "",
     "Pipeline-centric CRM API built around deals moving through stages.",
     "CRM API, построенный вокруг воронки — сделок, движущихся по стадиям.",
     "Webhooks fire on every stage change, which is usually more useful than polling deals."),
    ("api-close-crm", "Close CRM API", "CRM и продажи", "https://developer.close.com/", "paid", "crm,sales,calling,email", "",
     "Sales CRM API with built-in calling and email tracking as first-class objects.",
     "API продажного CRM со встроенными звонками и трекингом почты как объектами первого класса.",
     "Activities (calls, emails, SMS) are unified in one timeline endpoint per lead."),
    ("api-attio", "Attio API", "CRM и продажи", "https://docs.attio.com/", "freeTier", "crm,flexible,records,workspace", "",
     "Fully customizable CRM data model exposed as a flexible records API.",
     "Полностью настраиваемая модель данных CRM в виде гибкого API записей.",
     "Attributes are defined per workspace, so fetch the schema before hardcoding field names."),

    # ---------- Email-маркетинг ----------
    ("api-mailchimp", "Mailchimp API", "Email-маркетинг", "https://mailchimp.com/developer/marketing/api/", "freeTier", "email,campaigns,audience,automation", "",
     "Campaign, audience and automation management for the long-standing email platform.",
     "Управление кампаниями, аудиторией и автоматизацией на давно известной email-платформе.",
     "Batch operations exist for bulk subscriber updates — avoid one request per contact."),
    ("api-klaviyo", "Klaviyo API", "Email-маркетинг", "https://developers.klaviyo.com/", "freeTier", "email,sms,ecommerce,segments", "",
     "Email and SMS marketing API built for ecommerce event tracking and segmentation.",
     "API email- и SMS-маркетинга, заточенный под ecommerce-события и сегментацию.",
     "Track ecommerce events (viewed product, placed order) — segments are built almost entirely from these."),
    ("api-customerio", "Customer.io API", "Email-маркетинг", "https://customer.io/docs/api/", "freeTier", "email,messaging,workflows,triggers", "",
     "Event-triggered messaging across email, push and SMS with visual workflows.",
     "Событийные рассылки по email, push и SMS с визуальными workflow.",
     "Send events server-side rather than client-side — ad blockers routinely drop client-side tracking."),
    ("api-mailerlite", "MailerLite API", "Email-маркетинг", "https://developers.mailerlite.com/", "freeTier", "email,campaigns,automation,simple", "",
     "A simpler email marketing API with a genuinely usable free tier for small lists.",
     "Более простой API email-маркетинга с реально полезным бесплатным тарифом для небольших списков.",
     "Free tier covers up to 1,000 subscribers with full API access — no feature gating."),

    # ---------- Формы и опросы ----------
    ("api-typeform", "Typeform API", "Формы и опросы", "https://www.typeform.com/developers/", "freeTier", "forms,surveys,responses,webhooks", "",
     "Conversational forms with an API for creating forms and reading responses.",
     "Разговорные формы с API для создания форм и чтения ответов.",
     "Webhooks push responses in real time — polling the responses endpoint is rarely necessary."),
    ("api-google-forms", "Google Forms API", "Формы и опросы", "https://developers.google.com/workspace/forms/api/guides/overview", "free", "forms,google,responses,quiz", "",
     "Programmatic creation and response-reading for Google Forms.",
     "Программное создание форм Google Forms и чтение ответов.",
     "Watches (push notifications) need a Cloud Pub/Sub topic — polling is simpler for low-volume forms."),
    ("api-jotform", "Jotform API", "Формы и опросы", "https://api.jotform.com/docs/", "freeTier", "forms,builder,submissions,payments", "",
     "Drag-and-drop form builder with an API for submissions, files and payment forms.",
     "Конструктор форм с перетаскиванием и API для отправок, файлов и платёжных форм.",
     "File uploads attached to a submission are fetched via a separate endpoint, not inline in the JSON."),
    ("api-surveymonkey", "SurveyMonkey API", "Формы и опросы", "https://developer.surveymonkey.com/api/v3/", "mixed", "surveys,responses,analysis,nps", "",
     "Survey creation and response analytics from the long-standing survey platform.",
     "Создание опросов и аналитика ответов на давно известной платформе опросов.",
     "The free tier API access is read-mostly; creating surveys programmatically needs a paid plan."),
    # ---------- Идентификация и KYC ----------
    ("api-persona", "Persona", "Идентификация и KYC", "https://docs.withpersona.com/", "mixed", "identity,kyc,verification,compliance", "",
     "Identity verification flows: document checks, selfie match, database verification.",
     "Проверка личности: проверка документов, сравнение с селфи, проверка по базам.",
     "Sandbox mode returns deterministic test results per document type — script tests against it."),
    ("api-stripe-identity", "Stripe Identity", "Идентификация и KYC", "https://docs.stripe.com/identity", "paid", "identity,kyc,verification,stripe", "",
     "Government ID verification from the same platform already handling your payments.",
     "Проверка государственных ID от той же платформы, что уже обрабатывает платежи.",
     "One integration if you already use Stripe for billing — the verification session API mirrors Checkout."),
    ("api-onfido", "Onfido", "Идентификация и KYC", "https://documentation.onfido.com/", "paid", "identity,kyc,biometrics,compliance", "",
     "Document and biometric identity verification for regulated industries.",
     "Проверка личности по документам и биометрии для регулируемых индустрий.",
     "Webhook-driven check results — do not build a synchronous wait, checks can take minutes."),
    ("api-veriff", "Veriff", "Идентификация и KYC", "https://developers.veriff.com/", "paid", "identity,kyc,video,liveness", "",
     "Automated identity verification with liveness detection to catch spoofed photos.",
     "Автоматическая проверка личности с liveness-детекцией против поддельных фото.",
     "The verification session URL can be opened in-app via WebView or redirected to in a browser."),

    # ---------- Логистика и доставка ----------
    ("api-easypost", "EasyPost", "Логистика и доставка", "https://docs.easypost.com/", "freeTier", "shipping,labels,tracking,carriers", "",
     "One API for shipping labels, rates and tracking across dozens of carriers.",
     "Один API для этикеток доставки, тарифов и трекинга у десятков перевозчиков.",
     "Rate shopping across carriers in one call is the real value — do not integrate carriers individually."),
    ("api-shippo", "Shippo", "Логистика и доставка", "https://docs.goshippo.com/", "freeTier", "shipping,labels,rates,ecommerce", "",
     "Shipping label generation and rate comparison built for ecommerce checkout flows.",
     "Генерация этикеток доставки и сравнение тарифов, заточено под ecommerce-checkout.",
     "Test mode generates real-looking labels with no carrier charge — use it through the whole integration."),
    ("api-shipengine", "ShipEngine", "Логистика и доставка", "https://www.shipengine.com/docs/", "freeTier", "shipping,tracking,labels,rates", "",
     "Shipping API from the team behind ShipStation, covering labels, tracking and address validation.",
     "API доставки от команды ShipStation: этикетки, трекинг, валидация адресов.",
     "Address validation before label purchase avoids the most common cause of failed deliveries."),
    ("api-ship24", "Ship24", "Логистика и доставка", "https://docs.ship24.com/", "freeTier", "tracking,shipping,carriers,webhooks", "",
     "Universal shipment tracking across 1,200+ carriers with webhook status updates.",
     "Универсальный трекинг посылок у 1200+ перевозчиков с webhook-обновлениями статуса.",
     "One tracking number format works across carriers — no need to detect the carrier yourself first."),

    # ---------- Недвижимость ----------
    ("api-zillow-bridge", "Bridge Interactive (Zillow)", "Недвижимость", "https://www.bridgeinteractive.com/developers/", "mixed", "real-estate,mls,listings,zillow", "",
     "MLS listing data feed used by many real-estate platforms, including Zillow syndication.",
     "Фид данных листингов MLS, используемый многими платформами недвижимости, включая синдикацию в Zillow.",
     "Access requires MLS/broker approval, not just an API key — plan for a manual onboarding step."),
    ("api-rentcast", "RentCast", "Недвижимость", "https://developers.rentcast.io/", "freeTier", "real-estate,rent,valuation,listings", "",
     "Property records, rent estimates and market data via a straightforward REST API.",
     "Записи о недвижимости, оценка аренды и рыночные данные через простой REST API.",
     "The free tier's 50 requests/month is enough to prototype a valuation feature before paying."),
    ("api-attom-data", "ATTOM Data", "Недвижимость", "https://api.developer.attomdata.com/docs", "paid", "real-estate,property,data,valuation", "",
     "Deep US property data: tax assessments, sales history, foreclosure status.",
     "Глубокие данные по недвижимости США: налоговые оценки, история продаж, статус выкупа.",
     "Coverage and depth vary by county — check a target market's data availability before committing."),

    # ---------- Юридические и налоговые API ----------
    ("api-avalara", "Avalara AvaTax", "Юридические и налоговые API", "https://developer.avalara.com/", "paid", "tax,sales-tax,compliance,ecommerce", "",
     "Real-time sales tax calculation and filing across US and international jurisdictions.",
     "Расчёт и подача налога с продаж в реальном времени по юрисдикциям США и мира.",
     "Sandbox environment mirrors production tax rules exactly — test the full checkout flow there first."),
    ("api-taxjar", "TaxJar", "Юридические и налоговые API", "https://developer.taxjar.com/", "freeTier", "tax,sales-tax,ecommerce,filing", "",
     "Sales tax calculation and automated filing aimed at smaller ecommerce sellers.",
     "Расчёт налога с продаж и автоматическая подача, ориентировано на небольших ecommerce-продавцов.",
     "The free plan's 25 calls/month is enough to validate integration before enabling billing."),
    ("api-docusign", "DocuSign eSignature API", "Юридические и налоговые API", "https://developers.docusign.com/docs/esign-rest-api/", "freeTier", "esignature,contracts,legal,workflow", "",
     "Programmatic e-signature workflows: send, track and retrieve signed documents.",
     "Программные workflow электронной подписи: отправка, отслеживание, получение подписанных документов.",
     "Embedded signing keeps the signer inside your app instead of redirecting to DocuSign's site."),

    # ---------- Образование ----------
    ("api-canvas-lms", "Canvas LMS API", "Образование", "https://canvas.instructure.com/doc/api/", "openSource", "lms,education,courses,grades", "",
     "REST API for the widely used open-source learning management system.",
     "REST API для широко используемой open-source системы управления обучением.",
     "A free developer instance is available for testing without touching a real institution's data."),
    ("api-google-classroom", "Google Classroom API", "Образование", "https://developers.google.com/classroom", "free", "lms,education,google,assignments", "",
     "Manage courses, rosters and assignments in Google Classroom programmatically.",
     "Программное управление курсами, списками учеников и заданиями в Google Classroom.",
     "Domain-wide delegation is required for admin-level access across a whole school's classrooms."),
    ("api-quizlet", "Quizlet API", "Образование", "https://quizlet.com/api-docs", "freeTier", "flashcards,learning,education,study", "",
     "Access flashcard sets and study data from the popular learning platform.",
     "Доступ к наборам карточек и данным обучения с популярной образовательной платформы.",
     "Public set search works without auth — full user data needs OAuth."),

    # ---------- HR и рекрутинг ----------
    ("api-greenhouse", "Greenhouse API", "HR и рекрутинг", "https://developers.greenhouse.io/", "mixed", "ats,recruiting,hiring,harvest", "",
     "Applicant tracking system API: candidates, jobs, applications and interviews.",
     "API системы отслеживания кандидатов: кандидаты, вакансии, отклики, интервью.",
     "The Harvest API (read/write) and Job Board API (public postings) are separate keys — pick the right one."),
    ("api-workday", "Workday API", "HR и рекрутинг", "https://developer.workday.com/", "paid", "hr,enterprise,payroll,workforce", "",
     "Enterprise HR, payroll and workforce data via SOAP and REST endpoints.",
     "Корпоративные данные HR, зарплат и персонала через SOAP и REST эндпоинты.",
     "Workday's API surface is enormous — start from the specific report/service your tenant already exposes."),
    ("api-bamboohr", "BambooHR API", "HR и рекрутинг", "https://documentation.bamboohr.com/", "mixed", "hr,employees,pto,onboarding", "",
     "Employee data, time-off and onboarding workflows for a widely used HR platform.",
     "Данные сотрудников, отпуска и онбординг для широко используемой HR-платформы.",
     "Custom fields differ per company — fetch the meta/fields endpoint before assuming a schema."),
    ("api-lever", "Lever API", "HR и рекрутинг", "https://hire.lever.co/developer/documentation", "mixed", "ats,recruiting,hiring,pipeline", "",
     "Recruiting pipeline API: postings, candidates, stages and interview feedback.",
     "API воронки найма: вакансии, кандидаты, стадии, обратная связь по интервью.",
     "Webhooks cover most integrations better than polling the candidates list."),

    # ---------- Планирование и календари ----------
    ("api-calendly", "Calendly API", "Планирование и календари", "https://developer.calendly.com/", "freeTier", "scheduling,calendar,booking,webhooks", "",
     "Scheduling links and booking data for the widely used meeting scheduler.",
     "Ссылки для планирования и данные бронирований для широко используемого планировщика встреч.",
     "Webhook subscriptions on invitee.created replace polling for new bookings entirely."),
    ("api-cal-com", "Cal.com API", "Планирование и календари", "https://cal.com/docs/api-reference/v2/introduction", "openSource", "scheduling,calendar,self-host,open-source", "",
     "Open-source scheduling infrastructure — self-host it or use the hosted version.",
     "Открытая инфраструктура планирования — self-host или размещённая версия.",
     "Self-hosting removes per-booking fees entirely, at the cost of running the infrastructure yourself."),
    ("api-google-calendar", "Google Calendar API", "Планирование и календари", "https://developers.google.com/workspace/calendar/api/guides/overview", "free", "calendar,events,scheduling,google", "",
     "Read and write calendar events, free/busy data and reminders.",
     "Чтение и запись событий календаря, данных о занятости и напоминаний.",
     "The freebusy.query endpoint is far cheaper than fetching full event lists to check availability."),
    ("api-nylas", "Nylas", "Планирование и календари", "https://developer.nylas.com/docs/", "freeTier", "calendar,email,scheduling,unified", "",
     "Unified email, calendar and contacts API across Google, Outlook and generic IMAP.",
     "Единый API почты, календаря и контактов для Google, Outlook и обычного IMAP.",
     "One integration covers three providers — worth it the moment you need to support both Google and Outlook."),
]
