# -*- coding: utf-8 -*-
"""Stage 5 library pack B: data engineering, MLOps, NLP, recommenders, language ecosystems."""

LIBS_5B = [
    # ---------- Data engineering ----------
    ("lib-dbt", "dbt", "Data engineering", "https://docs.getdbt.com/", "openSource", "sql,transformation,warehouse,testing", "pip install dbt-core",
     "SQL-based data transformation with version control, testing and documentation built in.",
     "SQL-трансформация данных с версионированием, тестами и документацией из коробки.",
     "Write a test on every model's primary key from day one — it catches join fan-out immediately."),
    ("lib-apache-airflow", "Apache Airflow", "Data engineering", "https://airflow.apache.org/docs/", "openSource", "orchestration,workflows,scheduling,python", "pip install apache-airflow",
     "The standard workflow orchestrator for scheduled data pipelines, defined as Python DAGs.",
     "Стандартный оркестратор для запланированных пайплайнов данных, DAG описывается на Python.",
     "Keep DAG files light — heavy imports at parse time slow down the scheduler for every DAG, not just yours."),
    ("lib-dagster", "Dagster", "Data engineering", "https://docs.dagster.io/", "openSource", "orchestration,assets,testing,python", "pip install dagster",
     "Asset-based orchestrator that treats data outputs, not just tasks, as first-class objects.",
     "Asset-ориентированный оркестратор, где данные, а не только задачи — объекты первого класса.",
     "Model pipelines as assets rather than tasks — lineage and backfills become far easier to reason about."),
    ("lib-prefect", "Prefect", "Data engineering", "https://docs.prefect.io/", "openSource", "orchestration,python,workflows,scheduling", "pip install prefect",
     "Python-native workflow orchestration with a lighter learning curve than Airflow.",
     "Оркестрация workflow на чистом Python с более пологой кривой обучения, чем у Airflow.",
     "Plain Python functions become tasks with one decorator — no separate DAG-definition language to learn."),
    ("lib-great-expectations", "Great Expectations", "Data engineering", "https://docs.greatexpectations.io/", "openSource", "data-quality,testing,validation,python", "pip install great_expectations",
     "Data quality validation: define expectations about your data and test them automatically.",
     "Валидация качества данных: описываешь ожидания о данных и проверяешь их автоматически.",
     "Run expectations as a pipeline step, not a one-off notebook check — that's what catches silent drift."),
    ("lib-dlt", "dlt", "Data engineering", "https://dlthub.com/docs/intro", "openSource", "etl,python,pipelines,lightweight", "pip install dlt",
     "Lightweight Python library for building data pipelines without a platform to deploy.",
     "Лёгкая Python-библиотека для построения пайплайнов данных без развёртывания платформы.",
     "It infers schema from your data automatically, which removes most manual mapping work."),

    # ---------- MLOps и эксперименты ----------
    ("lib-mlflow", "MLflow", "MLOps и эксперименты", "https://mlflow.org/docs/latest/index.html", "openSource", "experiments,tracking,models,registry", "pip install mlflow",
     "Experiment tracking, model registry and deployment, all open-source and self-hostable.",
     "Трекинг экспериментов, реестр моделей и деплой — всё открытое и self-hosted.",
     "Log parameters and metrics from the very first training run — retrofitting tracking later loses history."),
    ("lib-wandb-client", "Weights & Biases (client)", "MLOps и эксперименты", "https://docs.wandb.ai/", "freeTier", "experiments,tracking,visualization,collaboration", "pip install wandb",
     "Experiment tracking with rich visualization and team collaboration features.",
     "Трекинг экспериментов с богатой визуализацией и функциями командной работы.",
     "Free tier covers individuals and small teams fully — no feature gating below the org-scale plans."),
    ("lib-dvc", "DVC", "MLOps и эксперименты", "https://dvc.org/doc", "openSource", "versioning,data,models,git", "pip install dvc",
     "Git-like version control for datasets and models, storing large files outside the repo.",
     "Git-подобное версионирование датасетов и моделей с хранением больших файлов вне репозитория.",
     "Point it at S3 or GCS as remote storage — the repo itself stays small no matter the dataset size."),
    ("lib-clearml", "ClearML", "MLOps и эксперименты", "https://clear.ml/docs/latest/docs", "openSource", "experiments,orchestration,mlops,pipelines", "pip install clearml",
     "Experiment tracking plus orchestration and pipeline automation in one open-source suite.",
     "Трекинг экспериментов плюс оркестрация и автоматизация пайплайнов в одном открытом решении.",
     "Two lines of code auto-log an existing training script — no need to rewrite it around the API."),
    ("lib-bentoml", "BentoML", "MLOps и эксперименты", "https://docs.bentoml.com/", "openSource", "serving,deployment,packaging,models", "pip install bentoml",
     "Packages trained models into production-ready API services.",
     "Упаковывает обученные модели в готовые к продакшену API-сервисы.",
     "It generates a Dockerfile automatically, so deployment target choice comes after packaging, not before."),
    ("lib-ray", "Ray", "MLOps и эксперименты", "https://docs.ray.io/", "openSource", "distributed,training,serving,scaling", "pip install ray",
     "Distributed computing framework for scaling Python training and inference workloads.",
     "Фреймворк распределённых вычислений для масштабирования обучения и инференса на Python.",
     "Start with Ray Data or Ray Train specifically rather than the low-level API — they cover most needs directly."),
    ("lib-optuna", "Optuna", "MLOps и эксперименты", "https://optuna.readthedocs.io/", "openSource", "hyperparameter,tuning,optimization,python", "pip install optuna",
     "Hyperparameter optimization framework with pruning to stop bad trials early.",
     "Фреймворк оптимизации гиперпараметров с прунингом, останавливающим неудачные прогоны рано.",
     "Enable pruning from the start — it is the main reason Optuna searches faster than a grid search."),

    # ---------- NLP и обработка текста ----------
    ("lib-spacy", "spaCy", "NLP и обработка текста", "https://spacy.io/usage", "openSource", "nlp,tokenization,ner,production", "pip install spacy",
     "Production-grade NLP: tokenization, NER, dependency parsing, all fast and typed.",
     "NLP промышленного уровня: токенизация, NER, синтаксический разбор — всё быстрое и типизированное.",
     "Use the small pipeline model in development and the large one only when accuracy actually matters."),
    ("lib-nltk", "NLTK", "NLP и обработка текста", "https://www.nltk.org/", "openSource", "nlp,teaching,classical,python", "pip install nltk",
     "The classic teaching-oriented NLP toolkit, still useful for classical text-processing tasks.",
     "Классический учебный тулкит NLP, всё ещё полезен для классических задач обработки текста.",
     "Reach for spaCy in production code; NLTK is better suited to learning and one-off exploration."),
    ("lib-huggingface-tokenizers", "Hugging Face Tokenizers", "NLP и обработка текста", "https://huggingface.co/docs/tokenizers", "openSource", "tokenization,rust,fast,nlp", "pip install tokenizers",
     "Rust-backed tokenizers matching every model on the Hugging Face Hub, extremely fast.",
     "Токенизаторы на Rust, совпадающие с каждой моделью на Hugging Face Hub, очень быстрые.",
     "Always load the tokenizer that shipped with your specific model checkpoint — vocabularies are not interchangeable."),
    ("lib-textblob", "TextBlob", "NLP и обработка текста", "https://textblob.readthedocs.io/", "openSource", "nlp,sentiment,simple,python", "pip install textblob",
     "Simple API for common NLP tasks: sentiment, noun phrases, translation.",
     "Простой API для типовых задач NLP: тональность, именные группы, перевод.",
     "Fine for a quick prototype; swap to spaCy or a proper model before anything production-facing."),
    ("lib-gensim", "Gensim", "NLP и обработка текста", "https://radimrehurek.com/gensim/", "openSource", "topic-modeling,embeddings,nlp,unsupervised", "pip install gensim",
     "Topic modeling and word-embedding library built for large, unsupervised text corpora.",
     "Библиотека тематического моделирования и эмбеддингов для больших неразмеченных текстовых корпусов.",
     "Still the fastest path to a working LDA topic model without training your own from scratch."),

    # ---------- Рекомендательные системы ----------
    ("lib-implicit", "Implicit", "Рекомендательные системы", "https://benfred.github.io/implicit/", "openSource", "recommendations,collaborative-filtering,python", "pip install implicit",
     "Fast collaborative filtering for implicit feedback datasets (clicks, views, purchases).",
     "Быстрая коллаборативная фильтрация для неявной обратной связи (клики, просмотры, покупки).",
     "Implicit feedback needs different algorithms than star ratings — this library assumes that from the start."),
    ("lib-lightfm", "LightFM", "Рекомендательные системы", "https://making.lyst.com/lightfm/docs/home.html", "openSource", "recommendations,hybrid,cold-start,python", "pip install lightfm",
     "Hybrid recommendation model combining collaborative and content-based signals.",
     "Гибридная модель рекомендаций, объединяющая коллаборативные и контентные сигналы.",
     "The hybrid approach is specifically what handles cold-start users and items reasonably well."),
    # ---------- Rust экосистема ----------
    ("lib-tokio", "Tokio", "Rust экосистема", "https://tokio.rs/tokio/tutorial", "openSource", "rust,async,runtime,networking", "cargo add tokio",
     "The async runtime nearly all networked Rust applications are built on.",
     "Асинхронный рантайм, на котором построены почти все сетевые приложения на Rust.",
     "Enable only the feature flags you need — the full feature set adds real compile-time cost."),
    ("lib-actix-web", "Actix Web", "Rust экосистема", "https://actix.rs/docs/", "openSource", "rust,web,framework,async", "cargo add actix-web",
     "High-performance async web framework for Rust.",
     "Высокопроизводительный асинхронный веб-фреймворк для Rust.",
     "Consistently near the top of web framework benchmarks, but check ecosystem maturity for your specific need."),
    ("lib-axum", "Axum", "Rust экосистема", "https://docs.rs/axum/latest/axum/", "openSource", "rust,web,tokio,ergonomic", "cargo add axum",
     "Ergonomic Rust web framework built by the Tokio team on top of Tower.",
     "Эргономичный веб-фреймворк Rust от команды Tokio, построен поверх Tower.",
     "Tower middleware works unmodified here, so the ecosystem is bigger than it first appears."),
    ("lib-serde", "Serde", "Rust экосистема", "https://serde.rs/", "openSource", "rust,serialization,json,derive", "cargo add serde",
     "The standard Rust serialization framework, powering nearly every JSON/YAML/etc. use case.",
     "Стандартный фреймворк сериализации Rust, лежит в основе почти любой работы с JSON/YAML.",
     "The derive macro generates (de)serialization code at compile time — no runtime reflection cost."),
    ("lib-sqlx", "SQLx", "Rust экосистема", "https://docs.rs/sqlx/latest/sqlx/", "openSource", "rust,database,async,compile-time", "cargo add sqlx",
     "Async SQL toolkit that checks your queries against the real database schema at compile time.",
     "Асинхронный SQL-тулкит, проверяющий запросы по реальной схеме базы данных на этапе компиляции.",
     "Run cargo sqlx prepare before CI without a live database connection — it caches query metadata for that."),

    # ---------- Go экосистема ----------
    ("lib-gin", "Gin", "Go экосистема", "https://gin-gonic.com/docs/", "openSource", "go,web,framework,fast", "go get github.com/gin-gonic/gin",
     "Fast, minimal HTTP web framework for Go with an Express-like API.",
     "Быстрый минималистичный HTTP-веб-фреймворк для Go с API в духе Express.",
     "Its router is a radix tree, which is why route matching stays fast even with hundreds of routes."),
    ("lib-echo-go", "Echo", "Go экосистема", "https://echo.labstack.com/docs", "openSource", "go,web,framework,middleware", "go get github.com/labstack/echo/v4",
     "Minimalist, extensible Go web framework with a clean middleware system.",
     "Минималистичный расширяемый веб-фреймворк Go с чистой системой middleware.",
     "Built-in binding and validation cover most request-parsing boilerplate without extra packages."),
    ("lib-cobra", "Cobra", "Go экосистема", "https://cobra.dev/", "openSource", "go,cli,commands,framework", "go get github.com/spf13/cobra",
     "The standard framework for building CLI applications in Go, used by kubectl and Hugo.",
     "Стандартный фреймворк для CLI-приложений на Go, используется в kubectl и Hugo.",
     "Pair it with Viper for config file and flag handling — they're built by the same author to work together."),
    ("lib-gorm", "GORM", "Go экосистема", "https://gorm.io/docs/", "openSource", "go,orm,database,sql", "go get gorm.io/gorm",
     "Feature-rich ORM for Go with associations, migrations and hooks.",
     "ORM для Go с ассоциациями, миграциями и хуками.",
     "Auto-migrate is convenient in development but write real migrations before production."),
    ("lib-testify", "testify", "Go экосистема", "https://github.com/stretchr/testify", "openSource", "go,testing,assertions,mocks", "go get github.com/stretchr/testify",
     "Assertion and mocking library that makes Go's standard testing package far more pleasant.",
     "Библиотека утверждений и моков, делающая стандартный testing-пакет Go гораздо приятнее.",
     "The require sub-package stops the test immediately on failure — use it over assert for setup checks."),

    # ---------- JVM экосистема ----------
    ("lib-spring-boot", "Spring Boot", "JVM экосистема", "https://docs.spring.io/spring-boot/", "openSource", "java,framework,enterprise,convention", "",
     "Convention-over-configuration framework that makes Spring's Java ecosystem approachable.",
     "Фреймворк convention-over-configuration, делающий экосистему Spring для Java доступной.",
     "Spring Initializr generates a working starter project in seconds — start there, not from a blank repo."),
    ("lib-quarkus", "Quarkus", "JVM экосистема", "https://quarkus.io/guides/", "openSource", "java,kubernetes,fast-boot,graalvm", "",
     "Kubernetes-native Java framework optimized for fast startup and low memory via GraalVM.",
     "Java-фреймворк, нативный для Kubernetes, оптимизирован под быстрый старт и низкую память через GraalVM.",
     "Native compilation via GraalVM cuts startup to milliseconds — worth it specifically for serverless Java."),
    ("lib-micronaut", "Micronaut", "JVM экосистема", "https://docs.micronaut.io/", "openSource", "java,kotlin,fast-boot,microservices", "",
     "JVM framework using compile-time dependency injection for fast startup, no reflection at runtime.",
     "JVM-фреймворк с DI на этапе компиляции для быстрого старта без рефлексии в рантайме.",
     "Compile-time DI is why startup and memory footprint beat traditional Spring in serverless contexts."),

    # ---------- .NET экосистема ----------
    ("lib-aspnet-core", "ASP.NET Core", ".NET экосистема", "https://learn.microsoft.com/aspnet/core/", "openSource", "dotnet,web,csharp,cross-platform", "",
     "Cross-platform web framework for building APIs and web apps in C#.",
     "Кроссплатформенный веб-фреймворк для API и веб-приложений на C#.",
     "Minimal APIs cut the boilerplate dramatically for small services compared to full MVC controllers."),
    ("lib-entity-framework", "Entity Framework Core", ".NET экосистема", "https://learn.microsoft.com/ef/core/", "openSource", "dotnet,orm,database,migrations", "",
     "The standard .NET ORM with LINQ-based queries and code-first migrations.",
     "Стандартный ORM для .NET с LINQ-запросами и code-first миграциями.",
     "Turn on query logging in development — generated SQL for a complex LINQ query is often surprising."),
    ("lib-blazor", "Blazor", ".NET экосистема", "https://learn.microsoft.com/aspnet/core/blazor/", "openSource", "dotnet,web,wasm,csharp", "",
     "Build interactive web UIs in C# instead of JavaScript, running via WebAssembly or the server.",
     "Интерактивные веб-интерфейсы на C# вместо JavaScript, через WebAssembly или сервер.",
     "Server-side render mode has near-zero download but needs a live connection — pick per your latency tolerance."),

    # ---------- Elixir экосистема ----------
    ("lib-phoenix-framework", "Phoenix Framework", "Elixir экосистема", "https://hexdocs.pm/phoenix/overview.html", "openSource", "elixir,web,realtime,liveview", "mix archive.install hex phx_new",
     "Elixir's productive, fault-tolerant web framework built on the Erlang VM.",
     "Продуктивный отказоустойчивый веб-фреймворк Elixir, построен на Erlang VM.",
     "LiveView gives you real-time interactivity without writing client-side JavaScript at all."),
    ("lib-ecto", "Ecto", "Elixir экосистема", "https://hexdocs.pm/ecto/Ecto.html", "openSource", "elixir,database,query,changeset", "",
     "Elixir's database wrapper and query builder, built around explicit changesets for validation.",
     "Обёртка базы данных и построитель запросов Elixir, построен на явных changeset для валидации.",
     "Changesets validate data before it ever reaches the database — put business rules there, not in controllers."),
    ("lib-oban", "Oban", "Elixir экосистема", "https://hexdocs.pm/oban/Oban.html", "openSource", "elixir,jobs,queue,postgres", "",
     "Reliable background job processing for Elixir, backed by Postgres instead of a separate broker.",
     "Надёжная фоновая обработка задач для Elixir на базе Postgres вместо отдельного брокера.",
     "No Redis or separate queue service needed — the database you already have is the whole job store."),
]
