# -*- coding: utf-8 -*-
"""Stage 5 API pack G: search, image/video AI generation depth, more MLOps hosted, agriculture/energy."""

APIS_5G = [
    # ---------- Поиск и retrieval (deepen) ----------
    ("api-algolia-2", "Algolia InstantSearch", "Поиск и retrieval", "https://www.algolia.com/doc/guides/building-search-ui/what-is-instantsearch/js/", "freeTier", "search,ui,instant,algolia", "npm i instantsearch.js",
     "Prebuilt search UI widgets that plug directly into Algolia's search API.",
     "Готовые UI-виджеты поиска, подключаются напрямую к поисковому API Algolia.",
     "Widgets cover facets, pagination and highlighting — most search UIs need no custom component at all."),
    ("api-vespa-ai", "Vespa", "Поиск и retrieval", "https://docs.vespa.ai/", "openSource", "search,vector,ranking,self-host", "",
     "Open-source engine for combined vector and keyword search with custom ranking at scale.",
     "Открытый движок для комбинированного векторного и ключевого поиска с кастомным ранжированием на масштабе.",
     "Its ranking expressions let you combine BM25 and vector similarity in one scoring formula, not two separate passes."),
    ("api-marqo", "Marqo", "Поиск и retrieval", "https://docs.marqo.ai/", "openSource", "search,vector,embeddings,self-host", "",
     "Vector search engine that handles embedding generation internally, not just storage.",
     "Векторный поисковый движок, сам генерирует эмбеддинги, а не только хранит их.",
     "You send raw text or images, not vectors — it embeds internally, which removes a whole pipeline step."),
    ("api-elastic-cloud", "Elastic Cloud", "Поиск и retrieval", "https://www.elastic.co/guide/en/cloud/current/index.html", "freeTier", "search,elasticsearch,managed,hosted", "",
     "Managed Elasticsearch and Kibana, avoiding the operational overhead of running your own cluster.",
     "Управляемый Elasticsearch и Kibana, снимает операционную нагрузку по своему кластеру.",
     "The 14-day trial is enough to validate query performance against your real data volume before committing."),

    # ---------- Изображения и дизайн: генерация (deepen) ----------
    ("api-ideogram", "Ideogram", "Изображения и дизайн", "https://developer.ideogram.ai/", "mixed", "image-generation,typography,ai,design", "",
     "Image generation model particularly strong at rendering legible text inside images.",
     "Модель генерации изображений, особенно сильна в отрисовке читаемого текста внутри картинок.",
     "Reach for this specifically when a generated image needs actual readable text, not decorative shapes."),
    ("api-recraft", "Recraft", "Изображения и дизайн", "https://www.recraft.ai/docs", "mixed", "image-generation,vector,design,brand", "",
     "Image generation with vector (SVG) output and brand style consistency across generations.",
     "Генерация изображений с векторным (SVG) выводом и единообразием бренд-стиля между генерациями.",
     "SVG output is the differentiator — most generators only produce raster images, not editable vectors."),
    ("api-luma-ai", "Luma AI (Dream Machine)", "Видео и медиа", "https://docs.lumalabs.ai/", "mixed", "video-generation,ai,text-to-video", "",
     "Text-to-video and image-to-video generation API.",
     "Генерация видео из текста и изображений через API.",
     "Image-to-video generally gives more controllable, coherent results than pure text-to-video prompts."),
    ("api-runway-ml", "Runway", "Видео и медиа", "https://docs.dev.runwayml.com/", "mixed", "video-generation,editing,ai,creative", "",
     "AI video generation and editing tools, from text-to-video to inpainting existing footage.",
     "Инструменты генерации и редактирования видео на ИИ — от текста в видео до инпейнтинга существующих кадров.",
     "Gen-3/Gen-4 model choice matters a lot for cost and quality — check current model pricing before batch jobs."),
    ("api-kling-ai", "Kling AI", "Видео и медиа", "https://app.klingai.com/global/dev/document-api", "mixed", "video-generation,ai,text-to-video", "",
     "Text-to-video and image-to-video generation with strong motion coherence.",
     "Генерация видео из текста и изображений с сильной согласованностью движения.",
     "Longer duration generations cost proportionally more — start with short clips while iterating on a prompt."),

    # ---------- MLOps и эксперименты (deepen hosted) ----------
    ("api-modal-labs", "Modal", "MLOps и эксперименты", "https://modal.com/docs", "freeTier", "serverless,gpu,python,deployment", "",
     "Serverless GPU compute for Python: run training or inference without managing infrastructure.",
     "Serverless GPU-вычисления для Python: обучение или инференс без управления инфраструктурой.",
     "Cold starts are minimized by keeping containers warm — check the keep-warm setting for latency-sensitive apps."),
    ("api-replicate-deployments", "Replicate Deployments", "MLOps и эксперименты", "https://replicate.com/docs/topics/deployments", "mixed", "deployment,models,scaling,replicate",  "",
     "Dedicated, auto-scaling deployments for models you run frequently on Replicate.",
     "Выделенные автомасштабируемые деплойменты для моделей, которые часто запускаются на Replicate.",
     "Switch from public model endpoints to a deployment once traffic is steady — cold starts drop significantly."),
    ("api-baseten", "Baseten", "MLOps и эксперименты", "https://docs.baseten.co/", "mixed", "model-serving,deployment,gpu,production", "",
     "Model serving infrastructure with autoscaling GPUs, aimed at production inference workloads.",
     "Инфраструктура обслуживания моделей с автомасштабируемыми GPU для продакшен-инференса.",
     "Truss, their open packaging format, is portable — you are not locked into their hosting to use it."),
    ("api-anyscale", "Anyscale", "MLOps и эксперименты", "https://docs.anyscale.com/", "mixed", "ray,distributed,training,managed", "",
     "Managed Ray platform for distributed training and serving at scale.",
     "Управляемая платформа Ray для распределённого обучения и обслуживания на масштабе.",
     "Start with open-source Ray locally; move here specifically when cluster operations become the bottleneck."),

    # ---------- Голосовые агенты (deepen) ----------
    ("api-cartesia-sonic", "Cartesia Sonic", "Голосовые агенты", "https://docs.cartesia.ai/", "freeTier", "tts,voice,latency,streaming", "",
     "Sub-100ms streaming text-to-speech aimed at real-time conversational agents.",
     "Стриминговый TTS с задержкой менее 100мс для разговорных агентов в реальном времени.",
     "Streaming the first audio chunk while the rest generates is what gets latency this low, not raw model speed alone."),
    ("api-hume-ai", "Hume AI", "Голосовые агенты", "https://dev.hume.ai/docs", "freeTier", "voice,emotion,empathic,agents", "",
     "Voice AI that reads and responds to emotional tone, not just words.",
     "Голосовой ИИ, считывающий и реагирующий на эмоциональный тон, а не только слова.",
     "The empathic voice interface adjusts response tone based on detected user emotion — check it against your use case's tolerance for that."),

    # ---------- Наблюдаемость трасс (deepen) ----------
    ("api-signoz", "SigNoz", "Наблюдаемость трасс", "https://signoz.io/docs/", "openSource", "tracing,open-source,self-host,otel", "",
     "Open-source observability platform combining traces, metrics and logs, self-hostable.",
     "Открытая платформа observability, объединяющая трейсы, метрики и логи, можно разместить самостоятельно.",
     "It is a genuine open-source alternative to Datadog/New Relic, not a crippled trial of a paid product."),
    ("api-grafana-tempo", "Grafana Tempo", "Наблюдаемость трасс", "https://grafana.com/docs/tempo/latest/", "openSource", "tracing,grafana,object-storage,cheap", "",
     "Distributed tracing backend storing traces cheaply in object storage instead of a database.",
     "Бэкенд распределённой трассировки, хранит трейсы дёшево в объектном хранилище вместо базы данных.",
     "Object storage backing is why retention can be much longer here than in traditional trace databases."),

    # ---------- Секреты и конфигурация (deepen) ----------
    ("api-onepassword-connect", "1Password Connect / SDK", "Секреты и конфигурация", "https://developer.1password.com/docs/connect/", "freeTier", "secrets,1password,api,team", "",
     "Programmatic access to 1Password vaults for CI/CD and application secrets.",
     "Программный доступ к хранилищам 1Password для CI/CD и секретов приложений.",
     "Reuse the vault your team already trusts for personal passwords, instead of standing up a separate secrets tool."),

    # ---------- Игровые движки (deepen) ----------
    ("api-photon-engine", "Photon Engine", "Игровые движки", "https://doc.photonengine.com/", "freeTier", "multiplayer,netcode,realtime,unity", "",
     "Real-time multiplayer networking backend, widely used with Unity and Unreal.",
     "Бэкенд для реального времени мультиплеера, широко используется с Unity и Unreal.",
     "The free tier's concurrent-user cap is generous enough to validate a multiplayer prototype fully."),
    ("api-playfab", "PlayFab", "Игровые движки", "https://learn.microsoft.com/gaming/playfab/", "freeTier", "backend,game-services,leaderboards,microsoft", "",
     "Backend-as-a-service for games: leaderboards, matchmaking, economy, player data.",
     "Backend-as-a-service для игр: таблицы лидеров, матчмейкинг, экономика, данные игроков.",
     "It covers the boring-but-essential game backend so a solo dev can skip building one from scratch."),
]
