# -*- coding: utf-8 -*-
LIBS = [
("lib-typescript","TypeScript","Языки и рантаймы","https://www.typescriptlang.org/docs/","openSource","types,javascript,tooling,dx","npm i -D typescript",
 "Typed superset of JavaScript that catches whole classes of bugs before runtime.",
 "Типизированное надмножество JavaScript, ловит целые классы багов до запуска.",
 "Turn on strict mode in a new project: retrofitting it into an old codebase is far more painful."),
("lib-nodejs","Node.js","Языки и рантаймы","https://nodejs.org/docs/latest/api/","openSource","runtime,javascript,server,cli","",
 "The default JavaScript runtime for servers, tooling and scripts.",
 "Стандартный JavaScript-рантайм для серверов, тулинга и скриптов.",
 "Pin the version with an .nvmrc file so CI and your machine never drift apart."),
("lib-bun","Bun","Языки и рантаймы","https://bun.sh/docs","openSource","runtime,bundler,test,fast","curl -fsSL https://bun.sh/install | bash",
 "All-in-one runtime with a bundler, test runner and package manager built in.",
 "Всё-в-одном рантайм со встроенными bundler, тест-раннером и пакетным менеджером.",
 "Try it first on scripts and tests: that is where the speed difference is most obvious."),
("lib-deno","Deno","Языки и рантаймы","https://docs.deno.com/","openSource","runtime,typescript,secure,permissions","",
 "Secure-by-default runtime with native TypeScript and explicit permissions.",
 "Безопасный по умолчанию рантайм с нативным TypeScript и явными разрешениями.",
 "The permission flags are the point: run untrusted code without network access and it simply cannot phone home."),
("lib-pnpm","pnpm","Разработка и DevOps","https://pnpm.io/","openSource","package-manager,monorepo,disk,fast","npm i -g pnpm",
 "Fast package manager with a content-addressable store and strict linking.",
 "Быстрый пакетный менеджер с общим хранилищем и строгими зависимостями.",
 "Strict linking exposes phantom dependencies early, which is exactly what you want before deploying."),
("lib-turborepo","Turborepo","Разработка и DevOps","https://turborepo.com/docs","openSource","monorepo,cache,build,tasks","",
 "Task runner with remote caching for JavaScript monorepos.",
 "Таск-раннер с удалённым кэшем для JavaScript-монорепозиториев.",
 "Declare task inputs and outputs precisely, otherwise the cache silently stops helping."),
("lib-nx","Nx","Разработка и DevOps","https://nx.dev/getting-started/intro","openSource","monorepo,generators,graph,cache","",
 "Monorepo toolkit with project graph, generators and affected-only builds.",
 "Инструментарий монорепо: граф проектов, генераторы и сборка только затронутого.",
 "The affected command is the real win in CI: it turns a full build into a partial one."),
("lib-esbuild","esbuild","Сборка и bundlers","https://esbuild.github.io/","openSource","bundler,fast,go,transform","npm i -D esbuild",
 "Extremely fast bundler and minifier written in Go.",
 "Очень быстрый бандлер и минификатор, написанный на Go.",
 "Great for library builds and scripts even when your app bundler is something else."),
("lib-rollup","Rollup","Сборка и bundlers","https://rollupjs.org/","openSource","bundler,esm,library,treeshaking","npm i -D rollup",
 "ES module bundler focused on clean library output and tree shaking.",
 "Бандлер ES-модулей с упором на чистый вывод библиотек и tree shaking.",
 "Mark peer dependencies as external or you will ship two copies of React to your users."),
("lib-webpack","Webpack","Сборка и bundlers","https://webpack.js.org/concepts/","openSource","bundler,loaders,legacy,config","npm i -D webpack",
 "Mature, highly configurable bundler still common in large codebases.",
 "Зрелый и очень настраиваемый бандлер, всё ещё частый в больших кодовых базах.",
 "Worth learning for maintenance work even if new projects start on Vite."),
("lib-rspack","Rspack","Сборка и bundlers","https://rspack.dev/","openSource","bundler,rust,webpack-compatible,fast","",
 "Rust-based bundler that is largely API compatible with Webpack.",
 "Бандлер на Rust, во многом совместимый по API с Webpack.",
 "The migration path is the selling point: keep the config, gain the speed."),
("lib-htmx","htmx","UI и frontend","https://htmx.org/docs/","openSource","html,hypermedia,no-build,server","",
 "Adds AJAX, transitions and websockets to plain HTML attributes.",
 "Добавляет AJAX, переходы и websockets прямо в атрибуты HTML.",
 "Ideal when a server already renders HTML and you only need islands of interactivity."),
("lib-alpine","Alpine.js","UI и frontend","https://alpinejs.dev/","openSource","reactive,no-build,lightweight,vanilla","",
 "Tiny reactive framework you drop in with one script tag.",
 "Крошечный реактивный фреймворк, подключается одним script-тегом.",
 "Perfect middle ground for vanilla projects that outgrew manual DOM updates but do not need a build step."),
("lib-lit","Lit","UI и frontend","https://lit.dev/docs/","openSource","web-components,standards,shadow-dom","npm i lit",
 "Small library for building standards-based web components.",
 "Небольшая библиотека для веб-компонентов на стандартах платформы.",
 "Components work in any framework, which makes it a safe choice for shared design systems."),
("lib-solid","SolidJS","UI и frontend","https://www.solidjs.com/docs/latest","openSource","reactive,fine-grained,fast,jsx","npm i solid-js",
 "Fine-grained reactive UI library with JSX and no virtual DOM.",
 "Реактивная UI-библиотека с тонкой реактивностью, JSX и без virtual DOM.",
 "Props are getters, not values: destructuring them is the classic beginner mistake."),
("lib-preact","Preact","UI и frontend","https://preactjs.com/guide/v10/getting-started/","openSource","react-compatible,small,performance","npm i preact",
 "Three kilobyte alternative to React with a compatibility layer.",
 "Трёхкилобайтная альтернатива React со слоем совместимости.",
 "The compat alias lets you swap it into an existing React app and measure the bundle win."),
("lib-angular","Angular","UI и frontend","https://angular.dev/","openSource","framework,typescript,enterprise,signals","",
 "Full featured framework with DI, routing and signals out of the box.",
 "Полноценный фреймворк с DI, роутингом и сигналами из коробки.",
 "Very common in German enterprise job listings: worth a portfolio project if you apply there."),
("lib-react-router","React Router","UI и frontend","https://reactrouter.com/","openSource","routing,react,ssr,data","npm i react-router",
 "Routing and data loading for React, including full framework mode.",
 "Роутинг и загрузка данных для React, включая полноценный framework-режим.",
 "Loaders and actions remove most manual fetching code once you commit to them."),
("lib-eleventy","Eleventy","UI и frontend","https://www.11ty.dev/docs/","openSource","static-site,html,markdown,no-js","npm i -D @11ty/eleventy",
 "Static site generator that ships zero JavaScript by default.",
 "Генератор статики, который по умолчанию не отдаёт ни байта JavaScript.",
 "A natural upgrade from hand-written HTML: keep your markup, gain layouts and collections."),
("lib-hugo","Hugo","UI и frontend","https://gohugo.io/documentation/","openSource","static-site,go,fast,markdown","",
 "Very fast static site generator with a single binary and no Node dependency.",
 "Очень быстрый генератор статики: один бинарник, без зависимости от Node.",
 "Builds of thousands of pages finish in seconds, which makes local preview genuinely instant."),
("lib-docusaurus","Docusaurus","Документация и контекст","https://docusaurus.io/docs","openSource","docs,react,versioning,search","npx create-docusaurus@latest docs classic",
 "Documentation site framework with versioning, i18n and search.",
 "Фреймворк для документации с версионированием, i18n и поиском.",
 "Versioned docs are the feature you will miss most if you roll your own."),
("lib-vitepress","VitePress","Документация и контекст","https://vitepress.dev/","openSource","docs,vue,markdown,fast","npm i -D vitepress",
 "Vite-powered static docs generator with markdown-first authoring.",
 "Генератор документации на Vite с упором на markdown.",
 "Excellent for a project wiki you want to publish from the same repo as the code."),
("lib-gsap","GSAP","Анимация и 3D","https://gsap.com/docs/v3/","free","animation,timeline,scroll,web","npm i gsap",
 "Professional animation engine with timelines and scroll triggers.",
 "Профессиональный движок анимации с таймлайнами и scroll-триггерами.",
 "Build one timeline and control it, instead of chaining dozens of independent tweens."),
("lib-animejs","Anime.js","Анимация и 3D","https://animejs.com/documentation/","openSource","animation,svg,css,lightweight","npm i animejs",
 "Lightweight animation library for CSS, SVG and DOM attributes.",
 "Лёгкая библиотека анимации для CSS, SVG и атрибутов DOM.",
 "The stagger helper turns a boring list reveal into something that looks designed."),
("lib-lenis","Lenis","Анимация и 3D","https://lenis.darkroom.engineering/","openSource","scroll,smooth,animation,ux","npm i lenis",
 "Smooth scroll library used across award-winning agency sites.",
 "Библиотека плавного скролла, популярная на сайтах-победителях конкурсов.",
 "Always respect prefers-reduced-motion: smooth scrolling makes some users physically unwell."),
("lib-swiper","Swiper","UI и frontend","https://swiperjs.com/","openSource","slider,carousel,touch,mobile","npm i swiper",
 "Touch-first slider and carousel with no framework dependency.",
 "Слайдер и карусель с упором на тач-жесты, без зависимости от фреймворка.",
 "Lazy-load slide images: a ten-slide gallery otherwise blocks your largest paint."),
("lib-leaflet","Leaflet","Карты и навигация","https://leafletjs.com/reference.html","openSource","maps,osm,markers,lightweight","npm i leaflet",
 "Small, dependable map library for OpenStreetMap tiles.",
 "Небольшая надёжная библиотека карт для тайлов OpenStreetMap.",
 "Cluster markers past a few hundred points or panning becomes visibly janky."),
("lib-maplibre","MapLibre GL JS","Карты и навигация","https://maplibre.org/maplibre-gl-js/docs/","openSource","maps,vector,webgl,styles","npm i maplibre-gl",
 "Open source vector map renderer with full style control.",
 "Открытый рендерер векторных карт с полным контролем над стилями.",
 "Vector tiles let you restyle a map at runtime without re-downloading anything."),
("lib-apexcharts","ApexCharts","Графики и визуализация","https://apexcharts.com/docs/installation/","openSource","charts,svg,interactive,dashboard","npm i apexcharts",
 "Interactive SVG charts with good defaults and framework wrappers.",
 "Интерактивные SVG-графики с хорошими дефолтами и обёртками для фреймворков.",
 "The defaults already look presentable, which saves hours on internal dashboards."),
("lib-plotly","Plotly.js","Графики и визуализация","https://plotly.com/javascript/","openSource","charts,scientific,3d,interactive","npm i plotly.js-dist",
 "Scientific charting library covering 3D, maps and statistical plots.",
 "Научная библиотека графиков: 3D, карты и статистические визуализации.",
 "Import the partial bundle you need: the full distribution is several megabytes."),
("lib-p5","p5.js","Анимация и 3D","https://p5js.org/reference/","openSource","creative-coding,canvas,art,education","npm i p5",
 "Creative coding library for canvas sketches, art and teaching.",
 "Библиотека креативного кодинга для canvas-скетчей, арта и обучения.",
 "The fastest way to turn a maths idea into something visual you can put in a portfolio."),
("lib-pixi","PixiJS","Анимация и 3D","https://pixijs.com/8.x/guides","openSource","webgl,2d,rendering,games","npm i pixi.js",
 "High performance 2D WebGL renderer for games and rich visuals.",
 "Высокопроизводительный 2D WebGL-рендерер для игр и насыщенной графики.",
 "Batch sprites from a single texture atlas: draw calls are what actually cost you frames."),
("lib-phaser","Phaser","Игры и развлечения","https://docs.phaser.io/","openSource","games,2d,physics,arcade","npm i phaser",
 "Complete 2D game framework with physics, input and scene management.",
 "Полноценный 2D игровой фреймворк с физикой, вводом и сценами.",
 "Scenes are the unit of structure: one scene per screen keeps a game project readable."),
("lib-tone","Tone.js","Музыка и медиа","https://tonejs.github.io/","openSource","audio,synth,web-audio,music","npm i tone",
 "Web Audio framework for synths, effects and musical timing.",
 "Web Audio фреймворк для синтезаторов, эффектов и музыкального тайминга.",
 "Audio can only start after a user gesture: wire start-up to an explicit play button."),
("lib-howler","Howler.js","Музыка и медиа","https://howlerjs.com/","openSource","audio,sprites,cross-browser,playback","npm i howler",
 "Simple cross-browser audio playback with sprite support.",
 "Простое кроссбраузерное воспроизведение аудио с поддержкой спрайтов.",
 "Audio sprites cut dozens of small requests down to one file for UI sounds."),
("lib-wavesurfer","WaveSurfer.js","Музыка и медиа","https://wavesurfer.xyz/","openSource","waveform,audio,visualization,player","npm i wavesurfer.js",
 "Waveform visualisation and audio player built on Web Audio.",
 "Визуализация волновой формы и аудиоплеер на базе Web Audio.",
 "Pre-compute peaks on the server for long files, otherwise decoding freezes the first paint."),
("lib-plyr","Plyr","Видео и медиа","https://plyr.io/","openSource","player,video,accessible,embed","npm i plyr",
 "Accessible, themeable media player for video, audio and embeds.",
 "Доступный настраиваемый медиаплеер для видео, аудио и встраиваний.",
 "It keeps native keyboard behaviour, which most custom players quietly break."),
("lib-dexie","Dexie.js","Состояние и данные","https://dexie.org/","openSource","indexeddb,offline,storage,browser","npm i dexie",
 "Friendly wrapper over IndexedDB with queries and live updates.",
 "Удобная обёртка над IndexedDB с запросами и живыми обновлениями.",
 "The right tool once localStorage limits bite: same offline idea, proper indexes and transactions."),
("lib-fusejs","Fuse.js","Поиск и retrieval","https://www.fusejs.io/","openSource","fuzzy,search,client,typo-tolerant","npm i fuse.js",
 "Client-side fuzzy search with typo tolerance and field weighting.",
 "Клиентский нечёткий поиск с терпимостью к опечаткам и весами полей.",
 "Tune the threshold with real queries: the default is either too loose or too strict for most data."),
("lib-minisearch","MiniSearch","Поиск и retrieval","https://lucaong.github.io/minisearch/","openSource","full-text,search,offline,index","npm i minisearch",
 "Tiny in-memory full text search engine that works fully offline.",
 "Крошечный полнотекстовый поисковый движок в памяти, полностью офлайн.",
 "Serialise the index and ship it with your build so first search needs no indexing pass."),
("lib-datefns","date-fns","Утилиты","https://date-fns.org/docs/Getting-Started","openSource","dates,immutable,tree-shakable,i18n","npm i date-fns",
 "Modular date utility library with per-function imports.",
 "Модульная библиотека для дат с импортом отдельных функций.",
 "Import only what you use: whole-library imports undo the tree-shaking advantage."),
("lib-axios","Axios","Backend и API","https://axios-http.com/docs/intro","openSource","http,client,interceptors,requests","npm i axios",
 "HTTP client with interceptors, cancellation and wide browser support.",
 "HTTP-клиент с интерсепторами, отменой запросов и широкой поддержкой браузеров.",
 "Interceptors are the clean place to attach auth headers and unified error handling."),
("lib-socketio","Socket.IO","Backend и API","https://socket.io/docs/v4/","openSource","websocket,realtime,rooms,fallback","npm i socket.io",
 "Realtime bidirectional messaging with rooms and automatic reconnect.",
 "Realtime-обмен сообщениями с комнатами и автоматическим переподключением.",
 "Rooms give you per-user and per-document channels without inventing your own routing."),
("lib-fastify","Fastify","Backend и API","https://fastify.dev/docs/latest/","openSource","node,server,schema,performance","npm i fastify",
 "Fast Node web framework with schema-based validation and serialisation.",
 "Быстрый Node-фреймворк со схемной валидацией и сериализацией.",
 "JSON schemas both validate input and speed up responses: define them per route from the start."),
("lib-elysia","Elysia","Backend и API","https://elysiajs.com/","openSource","bun,typescript,server,end-to-end-types","bun add elysia",
 "Bun-first web framework with end-to-end type safety.",
 "Веб-фреймворк для Bun со сквозной типобезопасностью.",
 "Types flow to the client via Eden, which removes a whole class of API contract drift."),
("lib-strapi","Strapi","CMS и контент","https://docs.strapi.io/","openSource","cms,headless,admin,rest","npx create-strapi-app@latest my-app",
 "Self-hosted headless CMS with an admin panel and REST or GraphQL output.",
 "Self-hosted headless CMS с админкой и выдачей через REST или GraphQL.",
 "Design content types before importing data: renaming fields later means migrations."),
("lib-directus","Directus","CMS и контент","https://docs.directus.io/","openSource","cms,database-first,api,admin","",
 "Headless CMS that wraps an existing SQL database without owning the schema.",
 "Headless CMS поверх существующей SQL-базы, не навязывающий свою схему.",
 "Ideal when the database already exists and you just need editors to have a UI."),
("lib-payload","Payload CMS","CMS и контент","https://payloadcms.com/docs","openSource","cms,typescript,nextjs,config-as-code","",
 "TypeScript-native CMS configured in code and embeddable in Next.js.",
 "CMS на TypeScript, настраиваемая кодом и встраиваемая в Next.js.",
 "Config as code means content models live in git and review like any other change."),
("lib-authjs","Auth.js","Аутентификация","https://authjs.dev/","openSource","auth,oauth,sessions,nextjs","npm i next-auth",
 "Authentication for web frameworks with dozens of OAuth providers.",
 "Аутентификация для веб-фреймворков с десятками OAuth-провайдеров.",
 "Start with one provider and a database session: adding providers later is trivial."),
("lib-better-auth","Better Auth","Аутентификация","https://www.better-auth.com/docs","openSource","auth,typescript,plugins,2fa","npm i better-auth",
 "Framework-agnostic TypeScript auth with plugins for 2FA and organisations.",
 "Framework-agnostic аутентификация на TypeScript с плагинами 2FA и организаций.",
 "Own your user table from day one: migrating off a hosted auth provider later is painful."),
("lib-kysely","Kysely","Базы данных и ORM","https://kysely.dev/","openSource","sql,typescript,query-builder,types","npm i kysely",
 "Type-safe SQL query builder with autocomplete over your real schema.",
 "Типобезопасный SQL query builder с автодополнением по вашей реальной схеме.",
 "Closer to SQL than an ORM, which makes generated queries easy to review and explain."),
("lib-duckdb","DuckDB","Данные и ML","https://duckdb.org/docs/","openSource","analytics,sql,olap,embedded","",
 "In-process analytical database that queries CSV and Parquet directly.",
 "Встраиваемая аналитическая база, читающая CSV и Parquet напрямую.",
 "Run SQL over a folder of CSV files without any import step: perfect for one-off analysis."),
("lib-redis","Redis","Базы данных и backend","https://redis.io/docs/latest/","mixed","cache,queue,pubsub,memory","",
 "In-memory data store for caching, queues and pub/sub.",
 "In-memory хранилище для кэша, очередей и pub/sub.",
 "Always set a TTL on cache keys: unbounded cache growth is the classic production incident."),
("lib-meilisearch","Meilisearch","Поиск и retrieval","https://www.meilisearch.com/docs","openSource","search,typo-tolerant,instant,self-host","",
 "Instant search engine with typo tolerance and simple self-hosting.",
 "Мгновенный поисковый движок с терпимостью к опечаткам и простым self-host.",
 "Configure searchable and filterable attributes explicitly: defaults index more than you want."),
("lib-typesense","Typesense","Поиск и retrieval","https://typesense.org/docs/","openSource","search,fast,vector,open-source","",
 "Open source search engine with keyword and vector search in one API.",
 "Открытый поисковый движок с ключевым и векторным поиском в одном API.",
 "Hybrid search often beats pure vector search for short queries such as product names."),
("lib-polars","Polars","Данные и ML","https://docs.pola.rs/","openSource","dataframe,rust,fast,analytics","pip install polars",
 "Fast dataframe library with lazy evaluation and a Rust core.",
 "Быстрая dataframe-библиотека с ленивыми вычислениями и ядром на Rust.",
 "Use the lazy API for pipelines: the optimiser can skip columns you never read."),
("lib-pandas","pandas","Данные и ML","https://pandas.pydata.org/docs/","openSource","dataframe,python,analysis,csv","pip install pandas",
 "The standard Python dataframe library for tabular analysis.",
 "Стандартная Python-библиотека dataframe для табличного анализа.",
 "Set dtypes on read for large CSVs: inference costs both memory and time."),
("lib-streamlit","Streamlit","Данные и ML","https://docs.streamlit.io/","openSource","dashboard,python,demo,fast-ui","pip install streamlit",
 "Turns a Python script into a shareable data app with no frontend code.",
 "Превращает Python-скрипт в шареное дата-приложение без фронтенд-кода.",
 "The whole script reruns on every interaction: cache expensive calls or it crawls."),
("lib-gradio","Gradio","Данные и ML","https://www.gradio.app/docs","openSource","demo,ml,ui,huggingface","pip install gradio",
 "Quick web UIs for machine learning demos, deployable to Spaces.",
 "Быстрые веб-интерфейсы для ML-демо с деплоем в Spaces.",
 "The fastest path from a model to a link you can paste into an application."),
("lib-rich","Rich","CLI и терминал","https://rich.readthedocs.io/en/stable/","openSource","terminal,formatting,tables,progress","pip install rich",
 "Beautiful terminal output with tables, progress bars and syntax highlighting.",
 "Красивый вывод в терминал: таблицы, прогресс-бары и подсветка синтаксиса.",
 "Rich logging handlers make CLI tool output readable enough to keep in production."),
("lib-typer","Typer","CLI и терминал","https://typer.tiangolo.com/","openSource","cli,python,types,args","pip install typer",
 "Builds Python CLIs from type hints with automatic help output.",
 "Строит Python CLI из аннотаций типов с автоматической справкой.",
 "Type hints become both validation and documentation, so the help text never goes stale."),
("lib-httpx","HTTPX","Backend и API","https://www.python-httpx.org/","openSource","http,async,python,client","pip install httpx",
 "Modern Python HTTP client with sync and async APIs.",
 "Современный Python HTTP-клиент с синхронным и асинхронным API.",
 "Reuse one client instance: creating a client per request throws away connection pooling."),
("lib-pydantic","Pydantic","Состояние и данные","https://docs.pydantic.dev/latest/","openSource","validation,types,python,schema","pip install pydantic",
 "Data validation and settings management from Python type hints.",
 "Валидация данных и управление настройками через аннотации типов Python.",
 "Validate LLM output against a model: it converts a vague string into a contract you can test."),
("lib-uv","uv","Разработка и DevOps","https://docs.astral.sh/uv/","openSource","python,packaging,fast,venv","",
 "Extremely fast Python package and project manager from the Ruff authors.",
 "Очень быстрый менеджер пакетов и проектов Python от авторов Ruff.",
 "It replaces pip, venv and pip-tools in one binary, which simplifies CI images a lot."),
("lib-scrapy","Scrapy","Браузер и автоматизация","https://docs.scrapy.org/en/latest/","openSource","scraping,crawler,python,pipeline","pip install scrapy",
 "Mature crawling framework with pipelines, throttling and retries.",
 "Зрелый фреймворк краулинга с пайплайнами, троттлингом и ретраями.",
 "Respect robots.txt and set a download delay: politeness keeps your IP usable."),
("lib-puppeteer","Puppeteer","Браузер и автоматизация","https://pptr.dev/","openSource","chrome,headless,screenshot,pdf","npm i puppeteer",
 "Headless Chrome control for screenshots, PDFs and scraping.",
 "Управление headless Chrome для скриншотов, PDF и скрапинга.",
 "Screenshot and PDF generation is the quickest win: it renders your real CSS."),
("lib-faker","Faker.js","Тестирование и качество","https://fakerjs.dev/","openSource","fake-data,seed,testing,fixtures","npm i -D @faker-js/faker",
 "Generates realistic fake names, addresses and content for tests.",
 "Генерирует реалистичные фейковые имена, адреса и контент для тестов.",
 "Set a fixed seed in tests so failures are reproducible instead of random."),
("lib-testing-library","Testing Library","Тестирование и качество","https://testing-library.com/docs/","openSource","testing,dom,accessibility,queries","npm i -D @testing-library/dom",
 "Test utilities that query the DOM the way a user would.",
 "Тестовые утилиты, которые ищут элементы так же, как это делает пользователь.",
 "Querying by role and label improves accessibility as a side effect of writing tests."),
("lib-llama-cpp","llama.cpp","Локальные модели","https://github.com/ggml-org/llama.cpp","openSource","local,gguf,cpu,inference","",
 "Runs GGUF language models locally on CPU or GPU with minimal dependencies.",
 "Запускает GGUF-модели локально на CPU или GPU с минимумом зависимостей.",
 "Quantised models let a laptop run useful assistants entirely offline."),
("lib-vllm","vLLM","Локальные модели","https://docs.vllm.ai/en/latest/","openSource","serving,throughput,gpu,openai-api","pip install vllm",
 "High throughput model server with an OpenAI-compatible endpoint.",
 "Высокопроизводительный сервер моделей с OpenAI-совместимым эндпоинтом.",
 "The OpenAI-compatible layer means your existing client code needs no rewrite."),
("lib-openwebui","Open WebUI","Локальные модели","https://docs.openwebui.com/","openSource","ui,chat,ollama,self-host","",
 "Self-hosted chat interface for local and remote models.",
 "Self-hosted чат-интерфейс для локальных и удалённых моделей.",
 "Pairs naturally with Ollama when you want a shared team UI over local models."),
("lib-faster-whisper","faster-whisper","Аудио и голос","https://github.com/SYSTRAN/faster-whisper","openSource","stt,whisper,ctranslate2,offline","pip install faster-whisper",
 "Reimplementation of Whisper that transcribes several times faster offline.",
 "Реализация Whisper, которая транскрибирует офлайн в несколько раз быстрее.",
 "Fully offline transcription: nothing about the audio ever leaves the machine."),
("lib-n8n","n8n","Разработка и DevOps","https://docs.n8n.io/","mixed","automation,workflow,self-host,integrations","",
 "Self-hostable workflow automation with hundreds of integrations.",
 "Self-hosted автоматизация workflow с сотнями интеграций.",
 "Good glue for scheduled jobs you do not want to write and host yourself."),
("lib-kmp","Kotlin Multiplatform","Мобильная и desktop разработка","https://kotlinlang.org/docs/multiplatform.html","openSource","kotlin,android,desktop,shared-code","",
 "Share business logic across Android, desktop, iOS and web from one Kotlin codebase.",
 "Общая бизнес-логика для Android, desktop, iOS и web из одной Kotlin-кодовой базы.",
 "Share logic first and keep UI native per platform: that split ages best."),
("lib-compose","Jetpack Compose","Мобильная и desktop разработка","https://developer.android.com/develop/ui/compose/documentation","openSource","android,ui,declarative,kotlin","",
 "Declarative UI toolkit for Android and Compose Multiplatform desktop.",
 "Декларативный UI-тулкит для Android и desktop через Compose Multiplatform.",
 "Hoist state out of composables: it is the difference between testable and tangled UI."),
("lib-ktor","Ktor","Мобильная и desktop разработка","https://ktor.io/docs/welcome.html","openSource","kotlin,http,client,server","",
 "Kotlin HTTP client and server framework that works on every KMP target.",
 "Kotlin-фреймворк HTTP-клиента и сервера, работающий на всех целях KMP.",
 "One client API across Android, desktop and iOS removes a lot of platform-specific glue."),
("lib-riverpod","Riverpod","Состояние и данные","https://riverpod.dev/","openSource","flutter,state,dependency-injection,testable","flutter pub add flutter_riverpod",
 "Compile-safe state management and dependency injection for Flutter.",
 "Управление состоянием и внедрение зависимостей для Flutter с проверкой на компиляции.",
 "Providers are trivially overridable in tests, which is where the design pays off."),
("lib-bloc","Bloc","Состояние и данные","https://bloclibrary.dev/","openSource","flutter,state,events,testable","flutter pub add flutter_bloc",
 "Event-driven state management with strong testing and tooling support.",
 "Событийное управление состоянием с сильной поддержкой тестов и инструментов.",
 "Explicit events make state transitions easy to log, replay and explain in an interview."),
("lib-drift","Drift","Базы данных и ORM","https://drift.simonbinder.eu/","openSource","flutter,sqlite,typed,reactive","flutter pub add drift",
 "Reactive, type-safe SQLite persistence for Dart and Flutter.",
 "Реактивная типобезопасная работа с SQLite для Dart и Flutter.",
 "Streamed queries update the UI automatically when the underlying rows change."),
("lib-expo","Expo","Мобильная и desktop разработка","https://docs.expo.dev/","openSource","react-native,mobile,build,ota","npx create-expo-app@latest",
 "React Native toolchain with managed builds and over-the-air updates.",
 "Тулчейн React Native с управляемыми сборками и OTA-обновлениями.",
 "EAS Build removes the need for a local Xcode or Android Studio setup for release builds."),
("lib-capacitor","Capacitor","Мобильная и desktop разработка","https://capacitorjs.com/docs","openSource","web-to-native,mobile,plugins,hybrid","npm i @capacitor/core",
 "Wraps an existing web app into native iOS and Android shells.",
 "Оборачивает существующее веб-приложение в нативные оболочки iOS и Android.",
 "The realistic path to a store listing when your product is already a working website."),
("lib-wails","Wails","Мобильная и desktop разработка","https://wails.io/docs/introduction","openSource","desktop,go,webview,native","",
 "Builds desktop apps from a Go backend and a web frontend.",
 "Собирает desktop-приложения из Go-бэкенда и веб-фронтенда.",
 "Similar idea to Tauri but with Go instead of Rust: compare binary size before choosing."),

# ==================== Stage 4 additions ====================

# ---------- UI и frontend ----------
("lib-qwik","Qwik","UI и frontend","https://qwik.dev/docs/","openSource","resumability,ssr,islands,performance","npm create qwik@latest",
 "Resumable framework that ships almost no JavaScript until an interaction needs it.",
 "Resumable-фреймворк, почти не отправляющий JavaScript до первого взаимодействия.",
 "Resumability replaces hydration, so measure interaction latency rather than bundle size."),
("lib-mantine","Mantine","UI и frontend","https://mantine.dev/getting-started/","openSource","components,react,hooks,forms","npm i @mantine/core @mantine/hooks",
 "Large React component set with a matching hooks library and dark mode built in.",
 "Большой набор React-компонентов с библиотекой хуков и встроенной тёмной темой.",
 "The hooks package is worth installing on its own, even without the components."),
("lib-base-ui","Base UI","UI и frontend","https://base-ui.com/react/overview/quick-start","openSource","headless,a11y,react,unstyled","npm i @base-ui-components/react",
 "Unstyled, accessible React primitives from the MUI team.",
 "Неоформленные доступные React-примитивы от команды MUI.",
 "Choose one headless primitive library per project: mixing them doubles your focus-trap bugs."),
("lib-headless-ui","Headless UI","UI и frontend","https://headlessui.com/","openSource","headless,tailwind,a11y,react","npm i @headlessui/react",
 "Accessible unstyled components designed to pair with Tailwind.",
 "Доступные неоформленные компоненты, рассчитанные на работу с Tailwind.",
 "Smaller surface than Radix; enough for menus, dialogs and comboboxes in most apps."),
("lib-unocss","UnoCSS","UI и frontend","https://unocss.dev/guide/","openSource","css,atomic,presets,vite","npm i -D unocss",
 "On-demand atomic CSS engine with presets, including a Tailwind-compatible one.",
 "Движок атомарного CSS по требованию с пресетами, включая Tailwind-совместимый.",
 "The inspector shows exactly which rules were generated, which makes debugging classes trivial."),
("lib-panda-css","Panda CSS","UI и frontend","https://panda-css.com/docs","openSource","css-in-js,tokens,build-time,typescript","npm i -D @pandacss/dev",
 "Build-time CSS-in-JS with design tokens and zero runtime cost.",
 "CSS-in-JS на этапе сборки с дизайн-токенами и без рантайм-затрат.",
 "Type-safe tokens catch a renamed colour at compile time instead of in a screenshot review."),
("lib-vanilla-extract","vanilla-extract","UI и frontend","https://vanilla-extract.style/documentation/","openSource","css,typescript,themes,zero-runtime","npm i -D @vanilla-extract/css",
 "Write CSS in TypeScript files that compile away to static stylesheets.",
 "CSS в TypeScript-файлах, компилируемый в статические стили.",
 "Themes become typed objects, so a missing token is a build error, not a broken page."),
("lib-codemirror","CodeMirror 6","UI и frontend","https://codemirror.net/docs/","openSource","editor,code,extensions,a11y","npm i codemirror",
 "Modular, accessible code editor that stays usable on mobile.",
 "Модульный доступный редактор кода, работающий и на мобильных.",
 "Everything is an extension: add only the language and keymap you need to keep it light."),
("lib-lexical","Lexical","UI и frontend","https://lexical.dev/docs/intro","openSource","editor,rich-text,react,extensible","npm i lexical @lexical/react",
 "Extensible text-editor framework from Meta with a strict, testable state model.",
 "Расширяемый фреймворк текстового редактора от Meta со строгой тестируемой моделью состояния.",
 "Editor state is serialisable JSON, which makes collaborative and undo features tractable."),
("lib-tanstack-router","TanStack Router","UI и frontend","https://tanstack.com/router/latest","openSource","routing,typescript,type-safe,react","npm i @tanstack/react-router",
 "Fully type-safe routing with typed search params and built-in data loading.",
 "Полностью типизированный роутинг с типизированными search-параметрами и загрузкой данных.",
 "Typed search params remove a whole category of runtime bugs around URL state."),
("lib-tanstack-table","TanStack Table","UI и frontend","https://tanstack.com/table/latest","openSource","table,headless,sorting,virtualization","npm i @tanstack/react-table",
 "Headless table logic: sorting, grouping, pagination and column sizing.",
 "Headless-логика таблиц: сортировка, группировка, пагинация и размеры колонок.",
 "It renders nothing, which is why it fits any design system without a fight."),
("lib-vueuse","VueUse","UI и frontend","https://vueuse.org/guide/","openSource","vue,composables,utilities,reactivity","npm i @vueuse/core",
 "Several hundred Vue composables for common reactive patterns.",
 "Несколько сотен Vue-composable для типовых реактивных задач.",
 "Check here before writing a composable: the tricky lifecycle cases are already handled."),

# ---------- Состояние и данные ----------
("lib-pinia","Pinia","Состояние и данные","https://pinia.vuejs.org/","openSource","vue,state,store,devtools","npm i pinia",
 "The official Vue store: typed, modular and devtools-friendly.",
 "Официальное хранилище Vue: типизированное, модульное, с поддержкой devtools.",
 "Stores are plain functions, so testing one needs no component and no mounting."),
("lib-jotai","Jotai","Состояние и данные","https://jotai.org/docs/introduction","openSource","react,atoms,state,minimal","npm i jotai",
 "Atomic state for React: many small independent atoms instead of one store.",
 "Атомарное состояние для React: много мелких независимых атомов вместо одного стора.",
 "Derived atoms recompute only for the components that read them, which keeps renders narrow."),
("lib-nanostores","Nano Stores","Состояние и данные","https://github.com/nanostores/nanostores","openSource","state,framework-agnostic,tiny,islands","npm i nanostores",
 "A tiny framework-agnostic store, useful for sharing state between islands.",
 "Крошечный фреймворк-независимый стор, полезный для обмена состоянием между islands.",
 "The natural choice in Astro, where React and Svelte islands must share one value."),
("lib-immer","Immer","Состояние и данные","https://immerjs.github.io/immer/","openSource","immutability,state,reducers,typescript","npm i immer",
 "Write mutating code against a draft and get an immutable result.",
 "Пишешь мутирующий код по черновику и получаешь иммутабельный результат.",
 "It removes the deep-spread ceremony that makes nested reducers unreadable."),

# ---------- Графики и визуализация ----------
("lib-observable-plot","Observable Plot","Графики и визуализация","https://observablehq.com/plot/","openSource","charts,grammar-of-graphics,d3,svg","npm i @observablehq/plot",
 "Grammar-of-graphics charts in a single call, with D3 available underneath.",
 "Графики по grammar of graphics одним вызовом, с доступным D3 под капотом.",
 "Reach for this before raw D3: most exploratory charts are four lines here."),
("lib-visx","visx","Графики и визуализация","https://airbnb.io/visx/docs","openSource","react,charts,d3,primitives","npm i @visx/shape @visx/scale",
 "Low-level React chart primitives built on D3 scales and shapes.",
 "Низкоуровневые React-примитивы графиков на основе D3 scales и shapes.",
 "You assemble the chart yourself, which is the point when a design spec is exact."),
("lib-uplot","uPlot","Графики и визуализация","https://github.com/leeoniya/uPlot","openSource","charts,timeseries,canvas,performance","npm i uplot",
 "Extremely fast canvas time-series charts for very large datasets.",
 "Очень быстрые canvas-графики временных рядов для больших наборов данных.",
 "The right tool when a line chart has a hundred thousand points and SVG has given up."),
("lib-deck-gl","deck.gl","Графики и визуализация","https://deck.gl/docs","openSource","webgl,maps,layers,geospatial","npm i deck.gl",
 "WebGL layers for large-scale geospatial and scatter visualisation.",
 "WebGL-слои для крупномасштабной геопространственной и точечной визуализации.",
 "Composes with MapLibre, so you keep open tiles under a GPU-rendered data layer."),
("lib-matplotlib","Matplotlib","Графики и визуализация","https://matplotlib.org/stable/users/index.html","openSource","python,plots,figures,publication","pip install matplotlib",
 "The Python plotting foundation, from quick looks to publication figures.",
 "Основа построения графиков в Python — от быстрых проверок до публикационных фигур.",
 "Use the object-oriented API with explicit figures; the global pyplot state bites in notebooks."),
("lib-altair","Vega-Altair","Графики и визуализация","https://altair-viz.github.io/","openSource","python,declarative,vega,charts","pip install altair",
 "Declarative Python charting that compiles to Vega-Lite specs.",
 "Декларативное построение графиков в Python, компилируемое в спецификации Vega-Lite.",
 "The chart is data plus a spec, so it serialises into a report or a web page unchanged."),

# ---------- Анимация и 3D ----------
("lib-react-three-fiber","React Three Fiber","Анимация и 3D","https://r3f.docs.pmnd.rs/getting-started/introduction","openSource","three,react,3d,webgl","npm i three @react-three/fiber",
 "Three.js as declarative React components, with a large helper ecosystem.",
 "Three.js в виде декларативных React-компонентов с большой экосистемой хелперов.",
 "Learn plain Three.js concepts first: the React layer hides the API, not the graphics maths."),
("lib-babylon","Babylon.js","Анимация и 3D","https://doc.babylonjs.com/","openSource","3d,webgl,webgpu,engine","npm i @babylonjs/core",
 "Full 3D engine with physics, XR and a browser-based scene inspector.",
 "Полноценный 3D-движок с физикой, XR и браузерным инспектором сцены.",
 "More batteries-included than Three.js; the playground is the fastest way to evaluate it."),
("lib-rive","Rive","Анимация и 3D","https://rive.app/docs","freeTier","animation,state-machine,vector,runtime","npm i @rive-app/canvas",
 "State-machine-driven vector animation with small runtimes for web and native.",
 "Векторная анимация на конечных автоматах с компактными рантаймами для web и native.",
 "Interactions live in the state machine, so the developer wires inputs rather than keyframes."),
("lib-lottie","Lottie Web","Анимация и 3D","https://airbnb.io/lottie/#/web","openSource","animation,json,after-effects,svg","npm i lottie-web",
 "Plays After Effects animations exported as JSON.",
 "Проигрывает анимации из After Effects, экспортированные в JSON.",
 "Prefer the canvas renderer for busy animations: the SVG renderer stalls on heavy files."),

# ---------- Изображения и дизайн ----------
("lib-lucide","Lucide","Изображения и дизайн","https://lucide.dev/guide/","openSource","icons,svg,stroke,tree-shaking","npm i lucide-react",
 "Consistent stroke icon set with packages for every major framework.",
 "Единый набор штриховых иконок с пакетами под все основные фреймворки.",
 "Import icons individually so the bundler drops the thousand you did not use."),
("lib-iconify","Iconify","Изображения и дизайн","https://iconify.design/docs/","openSource","icons,aggregator,svg,on-demand","npm i @iconify/react",
 "Over two hundred icon sets behind one API with on-demand loading.",
 "Более двухсот наборов иконок через один API с загрузкой по требованию.",
 "Great for prototyping across sets, but pin to one family before you ship a design."),
("lib-phosphor","Phosphor Icons","Изображения и дизайн","https://phosphoricons.com/","openSource","icons,weights,svg,flexible","npm i @phosphor-icons/react",
 "One icon family in six weights, so icon density can match your typography.",
 "Одно семейство иконок в шести весах, чтобы плотность иконок совпадала с типографикой.",
 "Pick a single weight per interface: mixing weights reads as an accident, not a choice."),
("lib-fontsource","Fontsource","Изображения и дизайн","https://fontsource.org/","openSource","fonts,self-host,npm,performance","npm i @fontsource-variable/inter",
 "Self-host open fonts as npm packages instead of linking a font CDN.",
 "Self-hosting открытых шрифтов через npm-пакеты вместо ссылки на шрифтовой CDN.",
 "The fix whenever a strict Content-Security-Policy blocks external font requests."),
("lib-open-props","Open Props","Изображения и дизайн","https://open-props.style/","openSource","css,tokens,variables,design-system","npm i open-props",
 "A ready set of CSS custom properties for colour, space, type and easing.",
 "Готовый набор CSS-переменных для цвета, отступов, типографики и easing.",
 "Useful when you want design tokens without adopting a utility-class framework."),

# ---------- Локальные модели ----------
("lib-transformers-js","Transformers.js","Локальные модели","https://huggingface.co/docs/transformers.js","openSource","onnx,browser,wasm,webgpu","npm i @huggingface/transformers",
 "Run transformer models directly in the browser via ONNX Runtime and WebGPU.",
 "Запуск transformer-моделей прямо в браузере через ONNX Runtime и WebGPU.",
 "Embeddings and classification run entirely client side, which removes the API bill and the privacy question."),
("lib-onnxruntime","ONNX Runtime","Локальные модели","https://onnxruntime.ai/docs/","openSource","inference,onnx,cross-platform,accelerators","pip install onnxruntime",
 "Cross-platform inference engine for models exported to ONNX.",
 "Кроссплатформенный движок инференса для моделей, экспортированных в ONNX.",
 "Export once and the same file runs on server, mobile and browser targets."),
("lib-mlx","MLX","Локальные модели","https://ml-explore.github.io/mlx/","openSource","apple-silicon,training,inference,numpy-like","pip install mlx",
 "Array framework for Apple silicon with unified memory and a NumPy-like API.",
 "Фреймворк массивов для Apple silicon с единой памятью и API в духе NumPy.",
 "On a Mac it makes local fine-tuning practical rather than theoretical."),

# ---------- AI-фреймворки ----------
("lib-outlines","Outlines","AI-фреймворки","https://dottxt-ai.github.io/outlines/","openSource","structured-output,grammar,regex,constrained","pip install outlines",
 "Constrained decoding: force model output to match a regex, grammar or schema.",
 "Ограниченное декодирование: вывод модели принудительно соответствует regex, грамматике или схеме.",
 "With local models this removes retry loops entirely: invalid output becomes impossible."),
("lib-guardrails","Guardrails AI","AI-фреймворки","https://www.guardrailsai.com/docs","openSource","validation,safety,pii,structured","pip install guardrails-ai",
 "Input and output validators for PII, jailbreak attempts and schema drift.",
 "Валидаторы входа и выхода для PII, попыток jailbreak и отклонений схемы.",
 "Validate outputs even from a trusted model: the failure mode you fear is a malformed field."),
("lib-ragas","Ragas","AI-фреймворки","https://docs.ragas.io/","openSource","eval,rag,metrics,faithfulness","pip install ragas",
 "Metrics for retrieval pipelines: faithfulness, answer relevance, context recall.",
 "Метрики для retrieval-пайплайнов: faithfulness, релевантность ответа, полнота контекста.",
 "Build a fifty-question set from real users; a benchmark from your own docs flatters you."),

# ---------- Тестирование и качество ----------
("lib-promptfoo","promptfoo","Тестирование и качество","https://www.promptfoo.dev/docs/intro/","openSource","eval,prompts,assertions,ci","npx promptfoo@latest init",
 "Declarative prompt and model comparison with assertions, runnable in CI.",
 "Декларативное сравнение промптов и моделей с проверками, запускается в CI.",
 "Version the config beside your prompts so a regression shows up as a failing check."),
("lib-inspect-ai","Inspect AI","Тестирование и качество","https://inspect.aisi.org.uk/","openSource","eval,solvers,scorers,safety","pip install inspect-ai",
 "Evaluation framework with solvers, scorers and a proper results viewer.",
 "Фреймворк оценки с solvers, scorers и полноценным просмотром результатов.",
 "Designed for real evaluation work, so logs are inspectable rather than a single score."),
("lib-hypothesis","Hypothesis","Тестирование и качество","https://hypothesis.readthedocs.io/","openSource","property-based,python,fuzzing,shrinking","pip install hypothesis",
 "Property-based testing that generates the input you would never have written.",
 "Property-based тестирование, генерирующее вход, который ты бы сам не придумал.",
 "When it fails it shrinks the case to a minimal example, which is half the debugging done."),
("lib-testcontainers","Testcontainers","Тестирование и качество","https://testcontainers.com/guides/","openSource","integration,docker,databases,fixtures","pip install testcontainers",
 "Real Postgres, Redis or Kafka in tests, started and torn down automatically.",
 "Настоящие Postgres, Redis или Kafka в тестах, поднимаются и гасятся автоматически.",
 "Removes the mock-versus-reality gap in data-access code, at the cost of slower tests."),
("lib-k6","Grafana k6","Тестирование и качество","https://grafana.com/docs/k6/latest/","openSource","load-testing,performance,thresholds,ci","brew install k6",
 "Load tests written in JavaScript with thresholds that can fail a pipeline.",
 "Нагрузочные тесты на JavaScript с порогами, способными завалить пайплайн.",
 "Set thresholds on p95 latency and error rate, then let CI enforce the budget."),
("lib-locust","Locust","Тестирование и качество","https://docs.locust.io/","openSource","load-testing,python,distributed,web-ui","pip install locust",
 "Load testing where user behaviour is ordinary Python code.",
 "Нагрузочное тестирование, в котором поведение пользователя — обычный Python-код.",
 "Model a realistic journey rather than hammering one endpoint; the bottleneck moves."),
("lib-mypy","mypy","Тестирование и качество","https://mypy.readthedocs.io/","openSource","python,types,static-analysis,strict","pip install mypy",
 "The reference static type checker for Python.",
 "Эталонный статический анализатор типов для Python.",
 "Adopt it per module with strict settings; a repo-wide switch produces noise nobody reads."),
("lib-oxlint","oxlint","Тестирование и качество","https://oxc.rs/docs/guide/usage/linter","openSource","javascript,lint,rust,fast","npm i -D oxlint",
 "Very fast JavaScript and TypeScript linter for large repositories.",
 "Очень быстрый линтер JavaScript и TypeScript для больших репозиториев.",
 "Fast enough to run on every save in a monorepo where ESLint takes minutes."),
("lib-pre-commit","pre-commit","Тестирование и качество","https://pre-commit.com/","openSource","git,hooks,lint,reproducible","pip install pre-commit",
 "Pins and runs git hooks identically on every machine and in CI.",
 "Фиксирует и запускает git-хуки одинаково на всех машинах и в CI.",
 "Run the same config in CI too, otherwise the hooks become optional in practice."),

# ---------- Очереди и события ----------
("lib-bullmq","BullMQ","Очереди и события","https://docs.bullmq.io/","openSource","queue,redis,jobs,node","npm i bullmq",
 "Redis-backed job queues for Node with retries, repeatable jobs and flows.",
 "Очереди задач на Redis для Node с повторами, периодическими задачами и flows.",
 "Make handlers idempotent: at-least-once delivery means a job will run twice one day."),
("lib-celery","Celery","Очереди и события","https://docs.celeryq.dev/","openSource","queue,python,workers,scheduling","pip install celery",
 "The long-standing Python task queue for background and scheduled work.",
 "Проверенная временем очередь задач Python для фоновой и периодической работы.",
 "Set explicit time limits and acks_late, or one stuck task quietly holds a worker forever."),
("lib-temporal","Temporal","Очереди и события","https://docs.temporal.io/","freeTier","durable-execution,workflows,retries,orchestration","pip install temporalio",
 "Durable execution: workflows survive crashes, deploys and week-long waits.",
 "Durable execution: workflow выживает после падений, деплоев и недельных ожиданий.",
 "Workflow code must be deterministic; keep every side effect inside an activity."),
("lib-inngest","Inngest","Очереди и события","https://www.inngest.com/docs","freeTier","serverless,workflows,events,steps","npm i inngest",
 "Event-driven durable functions with steps and no queue to operate.",
 "Событийные durable-функции со шагами и без очереди, которую нужно обслуживать.",
 "Each step is checkpointed, so a retry resumes rather than restarting the whole function."),

# ---------- Базы данных и ORM ----------
("lib-litestar","Litestar","Backend и API","https://docs.litestar.dev/","openSource","python,asgi,di,openapi","pip install litestar",
 "Batteries-included ASGI framework with dependency injection and SQLAlchemy support.",
 "ASGI-фреймворк со всем необходимым: dependency injection и поддержка SQLAlchemy.",
 "Its DI container makes layered testing straightforward without patching imports."),
("lib-nitro","Nitro","Backend и API","https://nitro.build/guide","openSource","server,universal,deploy,edge","npm i -D nitropack",
 "Universal server toolkit that builds for Node, edge runtimes and serverless targets.",
 "Универсальный серверный тулкит, собирающий под Node, edge-рантаймы и serverless.",
 "The engine under Nuxt: one codebase, a different deploy preset per host."),
("lib-alembic","Alembic","Базы данных и ORM","https://alembic.sqlalchemy.org/","openSource","migrations,sqlalchemy,python,schema","pip install alembic",
 "Migration tool for SQLAlchemy with autogenerated revisions.",
 "Инструмент миграций для SQLAlchemy с автогенерацией ревизий.",
 "Always read the autogenerated migration: it misses renames and guesses at type changes."),
("lib-sqlmodel","SQLModel","Базы данных и ORM","https://sqlmodel.tiangolo.com/","openSource","python,orm,pydantic,fastapi","pip install sqlmodel",
 "One model class serving as both the Pydantic schema and the SQLAlchemy table.",
 "Один класс модели работает и как Pydantic-схема, и как таблица SQLAlchemy.",
 "Convenient for small services; split the API schema from the table once they diverge."),
("lib-ibis","Ibis","Данные и ML","https://ibis-project.org/","openSource","dataframes,sql,portable,backends","pip install ibis-framework",
 "One dataframe API that compiles to SQL for twenty different engines.",
 "Единый dataframe-API, компилируемый в SQL для двадцати разных движков.",
 "Prototype on DuckDB locally and run the identical code against the warehouse."),
("lib-pyarrow","Apache Arrow","Данные и ML","https://arrow.apache.org/docs/python/","openSource","columnar,parquet,zero-copy,interop","pip install pyarrow",
 "Columnar memory format and the Parquet reader that most data tools share.",
 "Колоночный формат памяти и Parquet-ридер, общий для большинства инструментов данных.",
 "Passing Arrow tables between libraries avoids a copy and a conversion each way."),
("lib-numpy","NumPy","Данные и ML","https://numpy.org/doc/stable/","openSource","arrays,numerics,vectorization,python","pip install numpy",
 "The array foundation the entire Python numeric stack is built on.",
 "Основа массивов, на которой построен весь численный стек Python.",
 "Vectorise before you optimise: a Python loop over an array is the usual bottleneck."),
("lib-scikit-learn","scikit-learn","Данные и ML","https://scikit-learn.org/stable/","openSource","ml,classical,pipelines,metrics","pip install scikit-learn",
 "Classical machine learning with a consistent estimator and pipeline API.",
 "Классический машинный анализ с единым API estimator и pipeline.",
 "Try a linear model or gradient boosting first: on tabular data it often ends the search."),

# ---------- Документы и PDF ----------
("lib-docling","Docling","Документы и PDF","https://docling-project.github.io/docling/","openSource","parsing,pdf,layout,ingestion","pip install docling",
 "Turns PDFs, DOCX and slides into structured, chunk-ready document trees.",
 "Превращает PDF, DOCX и презентации в структурированные деревья, готовые к чанкованию.",
 "Layout-aware parsing preserves tables and headings, which is what RAG quality actually depends on."),
("lib-pypdf","pypdf","Документы и PDF","https://pypdf.readthedocs.io/","openSource","pdf,merge,split,python","pip install pypdf",
 "Pure-Python PDF reading, merging, splitting and metadata editing.",
 "Чтение, слияние, разделение и правка метаданных PDF на чистом Python.",
 "Fine for structure work; for scanned pages you still need OCR in front of it."),
("lib-weasyprint","WeasyPrint","Документы и PDF","https://doc.courtbouillon.org/weasyprint/stable/","openSource","html-to-pdf,css,print,python","pip install weasyprint",
 "Renders HTML and CSS to PDF with real support for print stylesheets.",
 "Рендерит HTML и CSS в PDF с настоящей поддержкой print-стилей.",
 "Paged-media CSS gives you headers, footers and page numbers without a template engine."),
("lib-openpyxl","openpyxl","Таблицы и no-code","https://openpyxl.readthedocs.io/","openSource","excel,xlsx,python,spreadsheets","pip install openpyxl",
 "Read and write real Excel workbooks, including formulas and formatting.",
 "Чтение и запись настоящих Excel-книг, включая формулы и форматирование.",
 "Use read_only and write_only modes for large sheets or memory grows without bound."),

# ---------- Локализация и i18n ----------
("lib-i18next","i18next","Локализация и i18n","https://www.i18next.com/","openSource","i18n,translations,plurals,detection","npm i i18next",
 "Framework-agnostic internationalisation with plurals, context and lazy namespaces.",
 "Фреймворк-независимая интернационализация с плюралами, контекстом и ленивыми namespace.",
 "Split translations into namespaces per route so a locale does not download the whole app."),
("lib-formatjs","FormatJS","Локализация и i18n","https://formatjs.github.io/docs/getting-started/installation","openSource","icu,intl,react,messages","npm i react-intl",
 "ICU message formatting built on the platform Intl APIs.",
 "Форматирование сообщений ICU на основе платформенных Intl API.",
 "ICU syntax handles gender and plural rules that string concatenation gets wrong."),

# ---------- Инфраструктура как код ----------
("lib-opentofu","OpenTofu","Инфраструктура как код","https://opentofu.org/docs/","openSource","iac,declarative,state,plan","brew install opentofu",
 "Declarative infrastructure with a real plan step, forked from Terraform.",
 "Декларативная инфраструктура с настоящим шагом plan, форк Terraform.",
 "Keep state remote and locked from day one: a lost local state file is a manual rebuild."),
("lib-pulumi","Pulumi","Инфраструктура как код","https://www.pulumi.com/docs/","freeTier","iac,typescript,python,cloud","npm i @pulumi/pulumi",
 "Infrastructure as code in general-purpose languages with real types and loops.",
 "Инфраструктура как код на обычных языках с настоящими типами и циклами.",
 "Loops and functions beat HCL copy-paste, but the same discipline about state still applies."),
("lib-ansible","Ansible","Инфраструктура как код","https://docs.ansible.com/","openSource","configuration,ssh,playbooks,idempotent","pip install ansible",
 "Agentless configuration management over SSH with idempotent playbooks.",
 "Управление конфигурацией без агентов по SSH с идемпотентными playbook.",
 "Idempotence is a property of the modules you use, not a guarantee: avoid raw shell tasks."),

# ---------- CLI и терминал ----------
("lib-ripgrep","ripgrep","CLI и терминал","https://github.com/BurntSushi/ripgrep","openSource","search,grep,rust,fast","brew install ripgrep",
 "Recursive regex search that respects gitignore and is fast enough to feel instant.",
 "Рекурсивный regex-поиск, уважающий gitignore и работающий мгновенно.",
 "The default gitignore filtering is why it beats grep on a real repository."),
("lib-fzf","fzf","CLI и терминал","https://junegunn.github.io/fzf/","openSource","fuzzy,finder,shell,interactive","brew install fzf",
 "General-purpose fuzzy finder that turns any list into an interactive picker.",
 "Универсальный fuzzy-поиск, превращающий любой список в интерактивный выбор.",
 "Pipe anything into it: branches, files, processes, history. It composes with everything."),
("lib-jq","jq","CLI и терминал","https://jqlang.org/manual/","openSource","json,cli,filter,transform","brew install jq",
 "JSON filtering and transformation on the command line.",
 "Фильтрация и преобразование JSON в командной строке.",
 "Still the quickest way to understand an unfamiliar API response before writing code."),
("lib-httpie","HTTPie","CLI и терминал","https://httpie.io/docs/cli","openSource","http,cli,debug,sessions","pip install httpie",
 "A human-friendly HTTP client with readable output and sessions.",
 "Удобный для человека HTTP-клиент с читаемым выводом и сессиями.",
 "Sessions persist auth between calls, which makes manual API exploration much less tedious."),
("lib-just","just","CLI и терминал","https://just.systems/man/en/","openSource","tasks,runner,make,recipes","brew install just",
 "A command runner without Make’s tabs, timestamps and implicit rules.",
 "Раннер команд без табов, таймстемпов и неявных правил Make.",
 "One justfile documents every project command, which is onboarding written as code."),
("lib-mise","mise","Установка и миграция","https://mise.jdx.dev/","openSource","versions,runtimes,env,tasks","curl https://mise.run | sh",
 "Per-project runtime versions, environment variables and tasks in one config.",
 "Версии рантаймов, переменные окружения и задачи проекта в одном конфиге.",
 "Replaces nvm, pyenv and rbenv at once, and the versions are committed with the repo."),
("lib-direnv","direnv","Локальные инструменты","https://direnv.net/","openSource","env,shell,per-directory,secrets","brew install direnv",
 "Loads and unloads environment variables as you enter and leave a directory.",
 "Загружает и выгружает переменные окружения при входе в каталог и выходе из него.",
 "Keep .envrc out of git and let it source a local secrets file that is also ignored."),

# ---------- Git и совместная работа ----------
("lib-gh-cli","GitHub CLI","Git и совместная работа","https://cli.github.com/manual/","openSource","github,cli,pr,workflow","brew install gh",
 "Pull requests, issues, releases and Actions from the terminal.",
 "Pull request, issues, релизы и Actions из терминала.",
 "gh pr create and gh run watch remove most of the browser round-trips from a review cycle."),
("lib-lazygit","lazygit","Git и совместная работа","https://github.com/jesseduffield/lazygit","openSource","git,tui,staging,rebase","brew install lazygit",
 "Terminal UI for git that makes partial staging and interactive rebase legible.",
 "Терминальный интерфейс git, делающий частичный staging и интерактивный rebase понятными.",
 "Staging individual lines here is far easier than remembering git add --patch commands."),
("lib-changesets","Changesets","Git и совместная работа","https://github.com/changesets/changesets","openSource","versioning,monorepo,changelog,release","npm i -D @changesets/cli",
 "Versioning and changelogs for monorepos, driven by intent files in the PR.",
 "Версионирование и changelog для монорепозиториев на основе файлов намерений в PR.",
 "The version bump is decided in review, which is where the breaking-change judgement belongs."),

# ---------- Мониторинг и аналитика ----------
("lib-opentelemetry","OpenTelemetry","Мониторинг и аналитика","https://opentelemetry.io/docs/","openSource","tracing,metrics,logs,vendor-neutral","pip install opentelemetry-sdk",
 "Vendor-neutral traces, metrics and logs: instrument once, change backend later.",
 "Вендор-независимые трейсы, метрики и логи: инструментируешь один раз, backend меняешь позже.",
 "Auto-instrumentation gets you spans in an afternoon; add manual spans only where they explain something."),
]
