# -*- coding: utf-8 -*-
"""Stage 5 library pack T: ML/DL frameworks, RL, time series, misc data science."""

LIBS_5T = [
    # ---------- Данные и ML: deep learning ----------
    ("lib-pytorch", "PyTorch", "Данные и ML", "https://pytorch.org/docs/stable/index.html", "openSource", "deep-learning,tensors,research,gpu", "pip install torch",
     "The dominant deep learning framework for research and increasingly for production.",
     "Доминирующий фреймворк глубокого обучения для исследований и всё чаще для продакшена.",
     "torch.compile speeds up training and inference substantially with a one-line change on modern versions."),
    ("lib-tensorflow", "TensorFlow", "Данные и ML", "https://www.tensorflow.org/api_docs", "openSource", "deep-learning,google,production,keras", "pip install tensorflow",
     "Google's deep learning framework with strong production and mobile deployment tooling.",
     "Фреймворк глубокого обучения Google с сильными инструментами продакшена и мобильного развёртывания.",
     "TensorFlow Lite and TF.js remain its edge — on-device deployment is better served here than by PyTorch."),
    ("lib-jax", "JAX", "Данные и ML", "https://docs.jax.dev/", "openSource", "autodiff,xla,research,functional", "pip install jax",
     "Composable function transformations (grad, jit, vmap) over NumPy-like arrays.",
     "Композируемые преобразования функций (grad, jit, vmap) над массивами в духе NumPy.",
     "Its functional purity requirement is strict — side effects inside jit-compiled functions silently misbehave."),
    ("lib-keras", "Keras 3", "Данные и ML", "https://keras.io/api/", "openSource", "deep-learning,high-level,multi-backend,api", "pip install keras",
     "High-level neural network API running on TensorFlow, PyTorch or JAX backends.",
     "Высокоуровневый API нейросетей поверх бэкендов TensorFlow, PyTorch или JAX.",
     "Multi-backend support means the same model code runs on whichever framework your team standardizes on."),
    ("lib-lightning", "PyTorch Lightning", "Данные и ML", "https://lightning.ai/docs/pytorch/stable/", "openSource", "pytorch,training,boilerplate,distributed", "pip install lightning",
     "Structures PyTorch training loops and handles distributed training details.",
     "Структурирует циклы обучения PyTorch и берёт на себя детали распределённого обучения.",
     "Moving to multi-GPU becomes a flag change rather than a rewrite, which is the main reason to adopt it."),
    ("lib-accelerate", "Hugging Face Accelerate", "Данные и ML", "https://huggingface.co/docs/accelerate", "openSource", "distributed,training,pytorch,huggingface", "pip install accelerate",
     "Runs the same PyTorch training code on CPU, single GPU, multi-GPU or TPU unchanged.",
     "Запускает один и тот же код обучения PyTorch на CPU, одной GPU, нескольких GPU или TPU без изменений.",
     "Lighter than Lightning — it adds device handling without imposing a training-loop structure."),
    ("lib-peft", "PEFT", "Данные и ML", "https://huggingface.co/docs/peft", "openSource", "fine-tuning,lora,efficient,huggingface", "pip install peft",
     "Parameter-efficient fine-tuning methods including LoRA and QLoRA.",
     "Методы параметрически эффективного дообучения, включая LoRA и QLoRA.",
     "LoRA fine-tuning fits on a single consumer GPU where full fine-tuning would need a cluster."),
    ("lib-trl", "TRL", "Данные и ML", "https://huggingface.co/docs/trl", "openSource", "rlhf,dpo,fine-tuning,alignment", "pip install trl",
     "Reinforcement learning and preference optimization (DPO, PPO) for language models.",
     "Обучение с подкреплением и оптимизация предпочтений (DPO, PPO) для языковых моделей.",
     "DPO is simpler and more stable than PPO for most preference-tuning tasks — start there."),
    ("lib-unsloth", "Unsloth", "Данные и ML", "https://docs.unsloth.ai/", "openSource", "fine-tuning,fast,memory-efficient,lora", "pip install unsloth",
     "Faster, more memory-efficient LLM fine-tuning through optimized kernels.",
     "Более быстрое и экономное по памяти дообучение LLM за счёт оптимизированных ядер.",
     "Meaningfully reduces VRAM requirements, which often decides whether a fine-tune is possible at all locally."),
    ("lib-axolotl", "Axolotl", "Данные и ML", "https://docs.axolotl.ai/", "openSource", "fine-tuning,config,yaml,llm", "pip install axolotl",
     "Config-driven LLM fine-tuning covering many model architectures and training methods.",
     "Дообучение LLM через конфиг, покрывает множество архитектур моделей и методов обучения.",
     "A YAML file defines the whole run, which makes experiments reproducible and easy to diff."),

    # ---------- Данные и ML: reinforcement learning ----------
    ("lib-gymnasium", "Gymnasium", "Данные и ML", "https://gymnasium.farama.org/", "openSource", "reinforcement-learning,environments,standard,api", "pip install gymnasium",
     "Standard API for reinforcement learning environments, the maintained successor to OpenAI Gym.",
     "Стандартный API сред обучения с подкреплением, поддерживаемый преемник OpenAI Gym.",
     "Use this rather than the archived gym package — the original is no longer maintained."),
    ("lib-stable-baselines3", "Stable-Baselines3", "Данные и ML", "https://stable-baselines3.readthedocs.io/", "openSource", "reinforcement-learning,algorithms,pytorch,baselines", "pip install stable-baselines3",
     "Reliable implementations of standard reinforcement learning algorithms in PyTorch.",
     "Надёжные реализации стандартных алгоритмов обучения с подкреплением на PyTorch.",
     "Its implementations are validated against published results, which matters since RL is notoriously fiddly."),

    # ---------- Данные и ML: time series ----------
    ("lib-prophet", "Prophet", "Данные и ML", "https://facebook.github.io/prophet/docs/quick_start.html", "openSource", "forecasting,timeseries,seasonality,meta", "pip install prophet",
     "Time series forecasting handling seasonality and holidays with minimal tuning.",
     "Прогнозирование временных рядов с учётом сезонности и праздников при минимальной настройке.",
     "Strong on business metrics with clear seasonality; weaker on series driven by external shocks."),
    ("lib-statsforecast", "StatsForecast", "Данные и ML", "https://nixtlaverse.nixtla.io/statsforecast/", "openSource", "forecasting,statistical,fast,timeseries", "pip install statsforecast",
     "Fast statistical forecasting models (ARIMA, ETS) with a scikit-learn-like API.",
     "Быстрые статистические модели прогнозирования (ARIMA, ETS) с API в духе scikit-learn.",
     "Classical statistical models often beat neural forecasters on short, regular series — benchmark before assuming."),
    ("lib-darts", "Darts", "Данные и ML", "https://unit8co.github.io/darts/", "openSource", "forecasting,timeseries,unified-api,python", "pip install darts",
     "Unified time series library covering classical, machine learning and deep forecasting models.",
     "Единая библиотека временных рядов: классические, ML и глубокие модели прогнозирования.",
     "Its consistent API makes comparing a dozen model families a loop rather than a rewrite each time."),
    ("lib-tsfresh", "tsfresh", "Данные и ML", "https://tsfresh.readthedocs.io/", "openSource", "feature-extraction,timeseries,automated,python", "pip install tsfresh",
     "Automated feature extraction from time series for downstream machine learning.",
     "Автоматическое извлечение признаков из временных рядов для последующего машинного обучения.",
     "It generates hundreds of features then filters by statistical relevance, saving manual feature engineering."),
    ("lib-shap", "SHAP", "Данные и ML", "https://shap.readthedocs.io/", "openSource", "explainability,interpretability,ml,features", "pip install shap",
     "Model explainability through Shapley values, showing each feature's contribution.",
     "Объяснимость моделей через значения Шепли, показывает вклад каждого признака.",
     "TreeExplainer is exact and fast for tree models — use it rather than the slower model-agnostic explainer."),
]
