# -*- coding: utf-8 -*-
"""Stage 5 API pack C: AI safety/eval, CDP, robotics, education, remaining hosted services."""

APIS_5C = [
    # ---------- AI-оценка и safety ----------
    ("api-braintrust", "Braintrust", "AI-оценка и safety", "https://www.braintrust.dev/docs", "freeTier", "eval,llm,datasets,regression", "",
     "Eval-driven development platform: datasets, scorers and regression diffs per commit.",
     "Платформа eval-driven разработки: датасеты, скореры и диффы регрессий по каждому коммиту.",
     "Wire evals into CI so a prompt change that regresses quality fails the build, not a demo."),
    ("api-arize-phoenix-cloud", "Arize AX", "AI-оценка и safety", "https://docs.arize.com/arize", "freeTier", "eval,observability,llm,tracing", "",
     "Hosted LLM observability and evaluation, the managed counterpart to open-source Phoenix.",
     "Управляемая observability и оценка LLM — облачный аналог open-source Phoenix.",
     "Start with the open-source Phoenix locally; move to the hosted product once you need team sharing."),
    ("api-patronus-ai", "Patronus AI", "AI-оценка и safety", "https://docs.patronus.ai/", "freeTier", "eval,safety,hallucination,llm", "",
     "Automated evaluation and hallucination detection for LLM outputs.",
     "Автоматическая оценка и детекция галлюцинаций в выводах LLM.",
     "Run detectors on production traffic samples, not just offline test sets — real inputs surface different failures."),
    ("api-lakera-guard", "Lakera Guard", "AI-оценка и safety", "https://platform.lakera.ai/docs", "freeTier", "safety,prompt-injection,security,llm", "",
     "Real-time prompt injection and jailbreak detection for LLM applications.",
     "Детекция prompt injection и jailbreak в реальном времени для LLM-приложений.",
     "Put it in front of any tool-calling agent that reads untrusted text — that's the highest-risk surface."),
    ("api-giskard", "Giskard", "AI-оценка и safety", "https://docs.giskard.ai/", "openSource", "testing,bias,llm,vulnerability-scan", "pip install giskard",
     "Automated vulnerability scanning for ML and LLM models: bias, robustness, hallucination.",
     "Автоматическое сканирование уязвимостей ML- и LLM-моделей: смещения, устойчивость, галлюцинации.",
     "Run the scan before a model ships, not after — most findings are cheap to fix pre-launch."),

    # ---------- Service mesh и Kubernetes ----------
    ("api-istio", "Istio", "Service mesh и Kubernetes", "https://istio.io/latest/docs/", "openSource", "service-mesh,kubernetes,traffic,security", "",
     "The most widely deployed service mesh: traffic management, mTLS, observability for Kubernetes.",
     "Самый распространённый service mesh: управление трафиком, mTLS, observability для Kubernetes.",
     "Start with the ambient mesh mode if available on your version — it avoids the sidecar-per-pod overhead."),
    ("api-linkerd", "Linkerd", "Service mesh и Kubernetes", "https://linkerd.io/2/overview/", "openSource", "service-mesh,kubernetes,lightweight,rust", "",
     "Lightweight Rust-based service mesh, simpler to operate than Istio for most teams.",
     "Лёгкий service mesh на Rust, проще в эксплуатации, чем Istio, для большинства команд.",
     "Its complexity budget is deliberately smaller than Istio's — a good default unless you need Istio-specific features."),
    ("api-argo-cd", "Argo CD", "Service mesh и Kubernetes", "https://argo-cd.readthedocs.io/", "openSource", "gitops,kubernetes,deployment,cd", "",
     "GitOps continuous delivery for Kubernetes: the cluster state always matches a Git repo.",
     "GitOps непрерывная доставка для Kubernetes: состояние кластера всегда соответствует репозиторию Git.",
     "Enable auto-sync only after you trust the pipeline — manual sync is safer while you're still learning it."),
    ("api-helm", "Helm", "Service mesh и Kubernetes", "https://helm.sh/docs/", "openSource", "kubernetes,packaging,templates,charts", "",
     "The package manager for Kubernetes: templated manifests bundled as reusable charts.",
     "Пакетный менеджер для Kubernetes: шаблонизированные манифесты в переиспользуемых чартах.",
     "helm template renders output locally without touching a cluster — use it to debug a chart before install."),
    ("api-kustomize", "Kustomize", "Service mesh и Kubernetes", "https://kubectl.docs.kubernetes.io/references/kustomize/", "openSource", "kubernetes,config,overlays,native", "",
     "Template-free Kubernetes configuration via overlays, built into kubectl itself.",
     "Конфигурация Kubernetes через оверлеи без шаблонов, встроена прямо в kubectl.",
     "Prefer this over Helm for straightforward environment-specific overrides — no templating language to learn."),
    ("api-karpenter", "Karpenter", "Service mesh и Kubernetes", "https://karpenter.sh/docs/", "openSource", "kubernetes,autoscaling,nodes,aws", "",
     "Just-in-time Kubernetes node autoscaling, replacing the older cluster-autoscaler.",
     "Автомасштабирование узлов Kubernetes точно по требованию, замена старому cluster-autoscaler.",
     "It provisions the exact instance type a pending pod needs, which cuts both cost and scheduling latency."),

    # ---------- Feature flags и эксперименты ----------
    ("api-launchdarkly", "LaunchDarkly", "Feature flags и эксперименты", "https://launchdarkly.com/docs/", "freeTier", "feature-flags,experiments,rollout,targeting", "",
     "Feature flag management with targeting rules, gradual rollouts and experimentation.",
     "Управление feature-флагами с правилами таргетинга, постепенным раскаткой и экспериментами.",
     "Kill switches are the highest-value flag type — wrap any risky new code path in one from day one."),
    ("api-flagsmith", "Flagsmith", "Feature flags и эксперименты", "https://docs.flagsmith.com/", "freeTier", "feature-flags,open-source,self-host,segments", "",
     "Open-source feature flag and remote config platform, self-hostable.",
     "Открытая платформа feature-флагов и remote-конфигурации, можно разместить самостоятельно.",
     "Self-hosting removes per-seat pricing entirely once flag volume grows past a small team."),
    ("api-statsig", "Statsig", "Feature flags и эксперименты", "https://docs.statsig.com/", "freeTier", "feature-flags,experiments,analytics,ab-testing", "",
     "Feature flags, experimentation and product analytics in one integrated platform.",
     "Feature-флаги, эксперименты и продуктовая аналитика на одной интегрированной платформе.",
     "Every flag is automatically an experiment — you get statistical results without a separate A/B tool."),
    ("api-growthbook", "GrowthBook", "Feature flags и эксперименты", "https://docs.growthbook.io/", "openSource", "feature-flags,experiments,open-source,warehouse", "",
     "Open-source feature flagging and experimentation that reads results from your own warehouse.",
     "Открытые feature-флаги и эксперименты, результаты читаются прямо из вашего хранилища данных.",
     "Point it at your existing warehouse instead of shipping analytics events to a third party."),
    ("api-unleash", "Unleash", "Feature flags и эксперименты", "https://docs.getunleash.io/", "openSource", "feature-flags,open-source,self-host,gradual-rollout", "",
     "Open-source feature flag platform with a generous free self-hosted tier.",
     "Открытая платформа feature-флагов с щедрым бесплатным self-hosted тарифом.",
     "The open-source edition is genuinely complete, not a crippled trial of the paid product."),

    # ---------- CDP и маркетинг-данные ----------
    ("api-segment", "Segment", "CDP и маркетинг-данные", "https://segment.com/docs/", "freeTier", "cdp,analytics,events,integrations", "",
     "Customer data platform: collect events once, route them to hundreds of destinations.",
     "Customer data platform: собираешь события один раз, маршрутизируешь в сотни назначений.",
     "Track events server-side where possible — client-side tracking loses data to ad blockers."),
    ("api-rudderstack", "RudderStack", "CDP и маркетинг-данные", "https://www.rudderstack.com/docs/", "openSource", "cdp,open-source,warehouse,self-host", "",
     "Open-source, warehouse-native customer data platform, an alternative to Segment.",
     "Открытая CDP, нативная для хранилища данных — альтернатива Segment.",
     "Warehouse-native means your event data lands in your own warehouse first, not a vendor's silo."),
    ("api-mparticle", "mParticle", "CDP и маркетинг-данные", "https://docs.mparticle.com/", "mixed", "cdp,mobile,integrations,identity", "",
     "Customer data platform with particularly strong mobile SDK support.",
     "Customer data platform с особенно сильной поддержкой мобильных SDK.",
     "Identity resolution across devices is the feature that differentiates it for mobile-heavy products."),

    # ---------- A/B-тестирование ----------
    ("api-optimizely", "Optimizely", "A/B-тестирование", "https://docs.developers.optimizely.com/", "paid", "ab-testing,experimentation,feature-flags,enterprise", "",
     "Enterprise experimentation platform for web, feature flags and full-stack A/B tests.",
     "Корпоративная платформа экспериментов для веба, feature-флагов и full-stack A/B-тестов.",
     "Full-stack experiments (server-side) avoid the flash-of-original-content problem client-side tools have."),
    ("api-vwo", "VWO", "A/B-тестирование", "https://developers.vwo.com/", "paid", "ab-testing,conversion,heatmaps,experimentation", "",
     "A/B testing and conversion optimization with visual editor and heatmaps included.",
     "A/B-тестирование и оптимизация конверсии со встроенным визуальным редактором и тепловыми картами.",
     "The visual editor covers most copy/layout tests without touching code — save the SDK for logic-based tests."),

    # ---------- Доступность (a11y) ----------
    ("api-axe-devtools", "axe DevTools", "Доступность (a11y)", "https://docs.deque.com/devtools-html-api/", "freeTier", "accessibility,testing,wcag,automated", "",
     "Automated accessibility testing engine behind most a11y linters and browser extensions.",
     "Движок автоматического тестирования доступности, лежащий в основе большинства a11y-линтеров.",
     "Automated checks catch roughly a third of real WCAG issues — pair this with manual keyboard testing."),
    ("api-wave-webaim", "WAVE", "Доступность (a11y)", "https://wave.webaim.org/api/", "freeTier", "accessibility,wcag,testing,api", "",
     "Accessibility evaluation API and browser extension from WebAIM.",
     "API и расширение браузера для оценки доступности от WebAIM.",
     "The visual overlay in the browser extension is often faster for spot-checking than the raw API report."),

    # ---------- Визуальное тестирование ----------
    ("api-chromatic", "Chromatic", "Визуальное тестирование", "https://www.chromatic.com/docs/", "freeTier", "visual-regression,storybook,ci,snapshots", "",
     "Visual regression testing built specifically around Storybook stories.",
     "Визуальное регрессионное тестирование, построенное специально вокруг Storybook-историй.",
     "Every story becomes a visual test automatically — no separate test file to maintain per component."),
    ("api-percy", "Percy", "Визуальное тестирование", "https://www.browserstack.com/docs/percy", "freeTier", "visual-regression,screenshots,ci,browserstack", "",
     "Visual regression testing that integrates with Cypress, Playwright and Selenium.",
     "Визуальное регрессионное тестирование, интегрируется с Cypress, Playwright и Selenium.",
     "Snapshot only the components that actually changed in a PR — full-page snapshots on every run get noisy."),
    ("api-applitools", "Applitools", "Визуальное тестирование", "https://applitools.com/docs/", "freeTier", "visual-regression,ai,cross-browser,testing", "",
     "AI-powered visual testing that ignores rendering noise across browsers and devices.",
     "Визуальное тестирование на ИИ, игнорирующее шум рендеринга между браузерами и устройствами.",
     "Its Visual AI comparison tolerates anti-aliasing differences that cause false positives in pixel-diff tools."),

    # ---------- Наблюдаемость трасс ----------
    ("api-honeycomb", "Honeycomb", "Наблюдаемость трасс", "https://docs.honeycomb.io/", "freeTier", "tracing,observability,otel,queries", "",
     "High-cardinality distributed tracing built for asking arbitrary questions about production.",
     "Трассировка с высокой кардинальностью для произвольных вопросов о поведении продакшена.",
     "Add wide, high-cardinality fields to spans (user id, request id) — that's what makes queries useful later."),
    ("api-lightstep", "ServiceNow Cloud Observability (Lightstep)", "Наблюдаемость трасс", "https://docs.lightstep.com/", "paid", "tracing,observability,otel,root-cause", "",
     "Distributed tracing with automated root-cause analysis across microservices.",
     "Распределённая трассировка с автоматическим анализом первопричины между микросервисами.",
     "Change Intelligence flags deploys correlated with regressions automatically — check it before manual bisecting."),
    ("api-jaeger", "Jaeger", "Наблюдаемость трасс", "https://www.jaegertracing.io/docs/", "openSource", "tracing,open-source,cncf,self-host", "",
     "CNCF distributed tracing system, the open-source default for OpenTelemetry backends.",
     "Система распределённой трассировки CNCF, открытый бэкенд по умолчанию для OpenTelemetry.",
     "Point your OTel SDK's exporter at it with zero code changes if you're already instrumented."),

    # ---------- Секреты и конфигурация ----------
    ("api-hashicorp-vault", "HashiCorp Vault", "Секреты и конфигурация", "https://developer.hashicorp.com/vault/docs", "openSource", "secrets,encryption,self-host,dynamic", "",
     "Secrets management with dynamic credentials, encryption as a service and audit logging.",
     "Управление секретами с динамическими credentials, шифрованием как сервисом и аудит-логом.",
     "Dynamic database credentials that auto-expire beat static rotated passwords for almost every use case."),
    ("api-doppler", "Doppler", "Секреты и конфигурация", "https://docs.doppler.com/", "freeTier", "secrets,env-vars,sync,managed", "",
     "Managed secrets and environment variable sync across every environment and platform.",
     "Управляемое хранение секретов и переменных окружения, синхронизация по всем окружениям и платформам.",
     "One source of truth removes the classic .env-file-drifted-from-production class of bugs entirely."),
    ("api-infisical", "Infisical", "Секреты и конфигурация", "https://infisical.com/docs/", "openSource", "secrets,open-source,self-host,env-vars", "",
     "Open-source secrets management, a self-hostable alternative to Doppler or Vault.",
     "Открытое управление секретами, self-hosted альтернатива Doppler или Vault.",
     "The CLI wraps your existing run command and injects secrets as env vars with no code changes."),
    ("api-aws-secrets-manager", "AWS Secrets Manager", "Секреты и конфигурация", "https://docs.aws.amazon.com/secretsmanager/", "paid", "secrets,aws,rotation,managed", "",
     "Managed secret storage with automatic rotation for RDS, Redshift and custom secrets.",
     "Управляемое хранение секретов с автоматической ротацией для RDS, Redshift и своих секретов.",
     "Automatic rotation for RDS credentials is the single biggest reason to pick this over a plain parameter store."),

    # ---------- Робототехника ----------
    ("api-ros2", "ROS 2", "Робототехника", "https://docs.ros.org/en/rolling/", "openSource", "robotics,middleware,nodes,realtime", "",
     "The standard middleware for robotics software: nodes, topics, services across languages.",
     "Стандартное middleware для программного обеспечения роботов: узлы, топики, сервисы на разных языках.",
     "Simulate in Gazebo before touching real hardware — most logic bugs are cheaper to find in sim."),
    ("api-gazebo", "Gazebo", "Робототехника", "https://gazebosim.org/docs", "openSource", "robotics,simulation,physics,ros", "",
     "Physics-based robot simulator that pairs directly with ROS.",
     "Физический симулятор роботов, напрямую сочетается с ROS.",
     "Sensor noise models in simulation are what make sim-to-real transfer actually work later."),
    ("api-moveit", "MoveIt", "Робототехника", "https://moveit.ai/documentation/", "openSource", "robotics,motion-planning,manipulation,ros", "",
     "Motion planning framework for robotic arms and manipulators, built on ROS.",
     "Фреймворк планирования движения для роботизированных манипуляторов на базе ROS.",
     "The setup assistant generates a working config from a robot's URDF in minutes, not hand-written XML."),

    # ---------- Образование (deepen) ----------
    ("api-open-trivia-db", "Open Trivia Database", "Образование", "https://opentdb.com/api_config.php", "noKey", "trivia,quiz,questions,no-key", "",
     "Free trivia question database across many categories, no key required.",
     "Бесплатная база вопросов для викторин по многим категориям, ключ не нужен.",
     "Session tokens prevent repeat questions across a quiz session — use them for anything longer than one round."),
    ("api-khan-academy", "Khan Academy API", "Образование", "https://api-explorer.khanacademy.org/", "free", "education,courses,exercises,free", "",
     "Access Khan Academy's course and exercise content programmatically.",
     "Программный доступ к курсам и упражнениям Khan Academy.",
     "Content coverage varies a lot by subject — check your target topic exists before building around it."),
]
