# -*- coding: utf-8 -*-
"""Stage 5 MCP + skills pack E."""

MCPS_5E = [
    ("mcp-clickup", "ClickUp MCP", "Планирование и календари", "https://github.com/taazkareem/clickup-mcp-server", "openSource", "clickup,tasks,project-management,community", "npx -y @taazkareem/clickup-mcp-server",
     "Community server for ClickUp tasks, lists and spaces.",
     "Сервер сообщества для задач, списков и пространств ClickUp.",
     "Scope the API token to one workspace before letting an agent create or move tasks."),
    ("mcp-trello", "Trello MCP", "Планирование и календари", "https://github.com/delorenj/mcp-server-trello", "openSource", "trello,kanban,boards,community", "",
     "Community server for Trello boards, lists and cards.",
     "Сервер сообщества для досок, списков и карточек Trello.",
     "Board IDs are opaque — have the agent list boards first rather than hardcoding an ID."),
    ("mcp-youtube-transcript", "YouTube Transcript MCP", "Видео и медиа", "https://github.com/jkawamoto/mcp-youtube-transcript", "openSource", "youtube,transcripts,video,community", "uvx mcp-youtube-transcript",
     "Fetches YouTube video transcripts for summarization and search.",
     "Получает транскрипты видео YouTube для суммаризации и поиска.",
     "Only works on videos with captions available — auto-generated captions count, but not all videos have them."),
    ("mcp-arxiv", "arXiv MCP Server", "Наука и исследования", "https://github.com/blazickjp/arxiv-mcp-server", "openSource", "arxiv,papers,research,community", "uvx arxiv-mcp-server",
     "Search and retrieve arXiv papers directly into an agent's context.",
     "Поиск и получение статей arXiv прямо в контекст агента.",
     "Downloads full paper text, so a long paper can eat a large share of the context window — summarize per section."),
    ("mcp-pubmed", "PubMed MCP", "Здоровье и медицина", "https://github.com/JackKuo666/PubMed-MCP-Server", "openSource", "pubmed,medical,research,community", "",
     "Search biomedical literature from PubMed as an agent tool.",
     "Поиск биомедицинской литературы PubMed как инструмент агента.",
     "Useful for literature review workflows, but always verify claims against the actual abstract."),
    ("mcp-aws-official", "AWS MCP Servers (official)", "Облако и деплой", "https://awslabs.github.io/mcp/", "openSource", "aws,cloud,official,multi-service", "",
     "AWS Labs' collection of official MCP servers covering many AWS services.",
     "Коллекция официальных MCP-серверов AWS Labs, покрывающая множество сервисов AWS.",
     "Install only the specific service servers you need — the full set is large and mostly irrelevant per project."),
    ("mcp-azure-devops", "Azure DevOps MCP", "Git и совместная работа", "https://github.com/microsoft/azure-devops-mcp", "openSource", "azure-devops,official,microsoft,pipelines", "npx -y @azure-devops/mcp",
     "Official Microsoft server for Azure DevOps work items, repos and pipelines.",
     "Официальный сервер Microsoft для рабочих элементов, репозиториев и пайплайнов Azure DevOps.",
     "Personal access token scope determines what the agent can touch — start with read-only scopes."),
    ("mcp-sqlite-official", "SQLite MCP (official)", "Базы данных и ORM", "https://github.com/modelcontextprotocol/servers-archived/tree/main/src/sqlite", "openSource", "sqlite,database,official,reference", "uvx mcp-server-sqlite",
     "Reference server for querying and modifying SQLite databases.",
     "Эталонный сервер для запросов и изменения баз данных SQLite.",
     "Good template for writing your own database MCP server — the code is short and readable."),
    ("mcp-memory-bank", "Memory Bank MCP", "Память и знания", "https://github.com/alioshr/memory-bank-mcp", "openSource", "memory,project-context,files,community", "npx -y @allpepper/memory-bank-mcp",
     "File-based project memory an agent reads and updates across sessions.",
     "Файловая память проекта, которую агент читает и обновляет между сессиями.",
     "Plain markdown files means the memory is reviewable and version-controllable, unlike an opaque vector store."),
    ("mcp-code-runner", "Code Runner MCP", "Браузер и автоматизация", "https://github.com/formulahendry/mcp-server-code-runner", "openSource", "code-execution,local,multi-language,community", "npx -y mcp-server-code-runner",
     "Runs code snippets locally in many languages from an agent tool call.",
     "Запускает фрагменты кода локально на многих языках по вызову инструмента агента.",
     "Runs on your host with your permissions — prefer a sandboxed alternative for untrusted generated code."),
]

SKILLS_5E = [
    ("skill-anthropic-courses", "Anthropic Courses", "Гайды и практики", "https://github.com/anthropics/courses", "free", "learning,claude,tutorials,prompting", "",
     "Structured courses on prompt engineering, tool use and building with the Claude API.",
     "Структурированные курсы по prompt engineering, tool use и разработке с Claude API.",
     "The prompt engineering course is the most practical starting point if you are new to the API."),
    ("skill-prompt-library", "Anthropic Prompt Library", "Гайды и практики", "https://docs.claude.com/en/resources/prompt-library/library", "free", "prompts,examples,templates,claude", "",
     "Ready-made prompts for dozens of common tasks, usable as starting templates.",
     "Готовые промпты для десятков типовых задач, годятся как стартовые шаблоны.",
     "Adapt rather than copy — these are illustrative starting points, not tuned for your specific data."),
    ("skill-be-clear-direct", "Be Clear and Direct", "Гайды и практики", "https://docs.claude.com/en/docs/build-with-claude/prompt-engineering/be-clear-and-direct", "free", "prompting,clarity,technique,claude", "",
     "The single highest-leverage prompting technique: say exactly what you want.",
     "Самая эффективная техника промптинга: сказать точно, что именно нужно.",
     "Most prompt failures are ambiguity, not model capability — fix the prompt before switching models."),
    ("skill-chain-of-thought", "Chain of Thought Prompting", "Планирование и reasoning", "https://docs.claude.com/en/docs/build-with-claude/prompt-engineering/chain-of-thought", "free", "prompting,reasoning,technique,claude", "",
     "Letting the model reason step by step before answering, and when it actually helps.",
     "Пошаговое рассуждение модели перед ответом и случаи, когда это реально помогает.",
     "It costs latency and tokens — reserve it for genuinely multi-step problems, not simple lookups."),
    ("skill-use-examples", "Multishot Prompting", "Гайды и практики", "https://docs.claude.com/en/docs/build-with-claude/prompt-engineering/multishot-prompting", "free", "prompting,examples,few-shot,claude", "",
     "Using examples to pin down output format and style more reliably than description alone.",
     "Использование примеров для надёжной фиксации формата и стиля вывода лучше, чем одно описание.",
     "Three to five diverse examples usually beat a long prose description of the desired format."),
    ("skill-system-prompts", "System Prompts", "Гайды и практики", "https://docs.claude.com/en/docs/build-with-claude/prompt-engineering/system-prompts", "free", "prompting,role,system,claude", "",
     "Using the system prompt to set persistent role, context and constraints.",
     "Использование системного промпта для постоянной роли, контекста и ограничений.",
     "Put stable instructions here and variable content in user turns — that split also maximizes cache hits."),
    ("skill-long-context-tips", "Long Context Tips", "Гайды и практики", "https://docs.claude.com/en/docs/build-with-claude/prompt-engineering/long-context-tips", "free", "context,long-documents,structure,claude", "",
     "Structuring very long inputs so the model reliably finds what matters.",
     "Структурирование очень длинных входных данных, чтобы модель надёжно находила нужное.",
     "Put the question after the documents, not before — it measurably improves retrieval from long context."),
    ("skill-reduce-hallucinations", "Reduce Hallucinations", "AI-оценка и safety", "https://docs.claude.com/en/docs/test-and-evaluate/strengthen-guardrails/reduce-hallucinations", "free", "hallucinations,grounding,accuracy,claude", "",
     "Techniques for grounding answers and letting the model say it does not know.",
     "Техники привязки ответов к источникам и разрешения модели сказать, что она не знает.",
     "Explicitly permitting \"I don't know\" in the prompt measurably reduces confident fabrication."),
    ("skill-increase-consistency", "Increase Output Consistency", "Гайды и практики", "https://docs.claude.com/en/docs/test-and-evaluate/strengthen-guardrails/increase-consistency", "free", "consistency,formatting,structured,claude", "",
     "Getting reliably formatted output across repeated runs.",
     "Получение стабильно форматированного вывода при повторных запусках.",
     "Prefilling the assistant turn with the opening of your desired format is the simplest reliable trick."),
    ("skill-define-success", "Define Success Criteria", "AI-оценка и safety", "https://docs.claude.com/en/docs/test-and-evaluate/define-success", "free", "evaluation,metrics,criteria,claude", "",
     "Writing measurable success criteria before building an LLM feature.",
     "Формулирование измеримых критериев успеха до разработки LLM-функции.",
     "Without this, evaluation becomes vibes — decide what 'good' means before you start tuning prompts."),
]
