# -*- coding: utf-8 -*-
"""Stage 5 library pack AM: compilers and bundlers, formatters, per-language linters, codemods."""

LIBS_5AM = [
    # ---------- Компиляторы и сборка библиотек ----------
    ("lib-swc", "SWC", "Сборка и bundlers", "https://swc.rs/docs/getting-started", "openSource", "rust,transpiler,fast,babel-alternative", "npm i -D @swc/core",
     "Rust-based TypeScript and JavaScript compiler, a fast Babel replacement.",
     "Компилятор TypeScript и JavaScript на Rust, быстрая замена Babel.",
     "Next.js and Jest both use it under the hood, so many projects already depend on it indirectly."),
    ("lib-bunchee", "Bunchee", "Сборка и bundlers", "https://github.com/huozhi/bunchee", "openSource", "library,zero-config,bundler,exports", "npm i -D bunchee",
     "Zero-configuration bundler for npm packages, driven by package.json exports.",
     "Бандлер без конфигурации для npm-пакетов, работающий по полю exports в package.json.",
     "It reads your exports map, so the build matches what consumers actually import."),
    ("lib-microbundle", "Microbundle", "Сборка и bundlers", "https://github.com/developit/microbundle", "openSource", "library,tiny,rollup,zero-config", "npm i -D microbundle",
     "Zero-configuration bundler for tiny modules, built on Rollup.",
     "Бандлер без конфигурации для маленьких модулей на базе Rollup.",
     "Emits every module format at once, which suits a library supporting old and new consumers."),

    # ---------- Форматирование ----------
    ("lib-dprint", "dprint", "Тестирование и качество", "https://dprint.dev/", "openSource", "formatter,rust,plugins,fast", "",
     "Pluggable code formatter written in Rust, supporting several languages.",
     "Подключаемый форматтер кода на Rust с поддержкой нескольких языков.",
     "Its incremental formatting only touches changed files, which is noticeable on a large repository."),
    ("lib-black", "Black", "Тестирование и качество", "https://black.readthedocs.io/", "openSource", "python,formatter,opinionated,deterministic", "pip install black",
     "Uncompromising Python formatter with almost no configuration.",
     "Бескомпромиссный форматтер Python практически без настроек.",
     "Removing formatting from code review entirely is the point — that is why it refuses options."),
    ("lib-isort", "isort", "Тестирование и качество", "https://pycqa.github.io/isort/", "openSource", "python,imports,sorting,formatter", "pip install isort",
     "Sorts and groups Python imports consistently.",
     "Сортирует и группирует импорты Python единообразно.",
     "Ruff implements the same rules, so a project already using Ruff needs no separate tool."),

    # ---------- Статический анализ Python ----------
    ("lib-pyright", "Pyright", "Тестирование и качество", "https://microsoft.github.io/pyright/", "openSource", "python,type-checker,fast,microsoft", "npm i -g pyright",
     "Fast Python type checker from Microsoft, the engine behind Pylance.",
     "Быстрый проверщик типов Python от Microsoft, движок Pylance.",
     "Considerably faster than mypy and stricter by default, which surfaces more genuine errors."),
    ("lib-ty", "ty", "Тестирование и качество", "https://github.com/astral-sh/ty", "openSource", "python,type-checker,rust,astral", "",
     "Extremely fast Python type checker in Rust, from the Ruff team.",
     "Крайне быстрый проверщик типов Python на Rust от команды Ruff.",
     "Still pre-release — worth tracking, but keep mypy or Pyright as the checker CI depends on."),
    ("lib-pylint", "Pylint", "Тестирование и качество", "https://pylint.readthedocs.io/", "openSource", "python,linter,thorough,configurable", "pip install pylint",
     "Thorough Python linter checking style, errors and code smells.",
     "Тщательный линтер Python, проверяющий стиль, ошибки и запахи кода.",
     "Its design checks (too many arguments, too many branches) catch complexity other linters ignore."),
    ("lib-bandit", "Bandit", "Безопасность и секреты", "https://bandit.readthedocs.io/", "openSource", "python,security,static-analysis,ast", "pip install bandit",
     "Finds common security issues in Python code.",
     "Находит распространённые проблемы безопасности в коде Python.",
     "Its shell-injection and weak-crypto checks catch the mistakes that most often reach production."),

    # ---------- Статический анализ Rust и Go ----------
    ("lib-clippy", "Clippy", "Rust экосистема", "https://doc.rust-lang.org/clippy/", "openSource", "rust,linter,official,idiomatic", "rustup component add clippy",
     "Official Rust linter with hundreds of idiom and correctness lints.",
     "Официальный линтер Rust с сотнями правил идиоматичности и корректности.",
     "It teaches idiomatic Rust as you go, which makes it valuable well beyond catching bugs."),
    ("lib-rustfmt", "rustfmt", "Rust экосистема", "https://rust-lang.github.io/rustfmt/", "openSource", "rust,formatter,official,consistent", "rustup component add rustfmt",
     "The official Rust code formatter.",
     "Официальный форматтер кода Rust.",
     "Near-universal adoption means Rust code looks the same across essentially every project."),
    ("lib-gofmt", "gofmt", "Go экосистема", "https://pkg.go.dev/cmd/gofmt", "free", "go,formatter,official,canonical", "",
     "Go's canonical formatter, shipped with the toolchain.",
     "Канонический форматтер Go, поставляемый вместе с тулчейном.",
     "Go settled formatting debates by shipping one formatter with no options at all."),
    ("lib-golangci-lint", "golangci-lint", "Go экосистема", "https://golangci-lint.run/", "openSource", "go,linters,aggregator,fast", "",
     "Runs dozens of Go linters in parallel from one configuration.",
     "Запускает десятки линтеров Go параллельно из одной конфигурации.",
     "Enable linters gradually on an existing codebase — the full default set buries you in findings."),
    ("lib-staticcheck", "Staticcheck", "Go экосистема", "https://staticcheck.dev/docs/", "openSource", "go,static-analysis,correctness,precise", "",
     "Advanced Go static analysis focused on correctness with very few false positives.",
     "Продвинутый статический анализ Go с упором на корректность и очень малым числом ложных срабатываний.",
     "Its low false-positive rate is why it is worth running even when other linters are noisy."),

    # ---------- Статический анализ JVM ----------
    ("lib-detekt", "Detekt", "JVM экосистема", "https://detekt.dev/docs/intro", "openSource", "kotlin,static-analysis,complexity,rules", "",
     "Static analysis for Kotlin covering code smells and complexity.",
     "Статический анализ Kotlin с проверкой запахов кода и сложности.",
     "Its complexity thresholds give an objective signal for when a function needs splitting."),
    ("lib-ktlint", "ktlint", "JVM экосистема", "https://pinterest.github.io/ktlint/latest/", "openSource", "kotlin,formatter,linter,official-style", "",
     "Kotlin linter and formatter following the official style guide.",
     "Линтер и форматтер Kotlin по официальному руководству по стилю.",
     "Following the official guide avoids a per-team style debate that never actually converges."),
    ("lib-spotbugs", "SpotBugs", "JVM экосистема", "https://spotbugs.readthedocs.io/", "openSource", "java,bytecode,bug-patterns,static-analysis", "",
     "Finds bug patterns in Java bytecode, the successor to FindBugs.",
     "Находит шаблоны ошибок в байткоде Java, преемник FindBugs.",
     "Analyzing bytecode means it also inspects dependencies you have no source for."),
    ("lib-pmd", "PMD", "JVM экосистема", "https://pmd.github.io/", "openSource", "static-analysis,multi-language,rules,copy-paste", "",
     "Source code analyzer for many languages, including copy-paste detection.",
     "Анализатор исходного кода для многих языков, включая обнаружение копипаста.",
     "Its copy-paste detector finds duplication across files that ordinary linters never compare."),
    ("lib-checkstyle", "Checkstyle", "JVM экосистема", "https://checkstyle.org/", "openSource", "java,style,conventions,configurable", "",
     "Enforces Java coding conventions and style rules.",
     "Обеспечивает соблюдение соглашений и правил стиля в Java.",
     "Adopt a published configuration (Google or Sun) rather than writing rules from scratch."),
    ("lib-errorprone", "Error Prone", "JVM экосистема", "https://errorprone.info/", "openSource", "java,compile-time,bug-patterns,google", "",
     "Catches common Java mistakes at compile time, from Google.",
     "Ловит распространённые ошибки Java на этапе компиляции, разработка Google.",
     "Many of its checks ship automatic fixes, so it repairs findings rather than only reporting them."),
    ("lib-infer", "Infer", "Тестирование и качество", "https://fbinfer.com/docs/getting-started/", "openSource", "static-analysis,meta,null-safety,interprocedural", "",
     "Meta's static analyzer finding null dereferences and resource leaks across procedures.",
     "Статический анализатор Meta, находящий разыменования null и утечки ресурсов между процедурами.",
     "Interprocedural analysis catches bugs spanning several functions that per-file linters cannot see."),

    # ---------- Кодмоды и структурный поиск ----------
    ("lib-ast-grep", "ast-grep", "Разработка и DevOps", "https://ast-grep.github.io/", "openSource", "structural-search,codemod,rust,tree-sitter", "npm i -g @ast-grep/cli",
     "Structural code search and rewriting using syntax patterns rather than regex.",
     "Структурный поиск и переписывание кода по синтаксическим шаблонам вместо регулярных выражений.",
     "Patterns match the syntax tree, so formatting and whitespace never break a search."),
    ("lib-comby", "Comby", "Разработка и DevOps", "https://comby.dev/docs/overview", "openSource", "structural-search,rewriting,language-agnostic,patterns", "",
     "Language-agnostic structural search and replace across many syntaxes.",
     "Языконезависимый структурный поиск и замена для множества синтаксисов.",
     "It understands balanced delimiters, which is exactly where regex-based rewrites go wrong."),
    ("lib-jscodeshift", "jscodeshift", "Разработка и DevOps", "https://jscodeshift.com/", "openSource", "codemod,javascript,ast,migration", "npm i -g jscodeshift",
     "JavaScript codemod toolkit for large-scale automated refactoring.",
     "Инструментарий кодмодов JavaScript для масштабного автоматического рефакторинга.",
     "Many libraries ship codemods for their breaking changes — check before migrating by hand."),
    ("lib-openrewrite", "OpenRewrite", "JVM экосистема", "https://docs.openrewrite.org/", "openSource", "refactoring,java,recipes,automated", "",
     "Automated large-scale refactoring for JVM projects, driven by reusable recipes.",
     "Автоматический масштабный рефакторинг JVM-проектов на основе переиспользуемых рецептов.",
     "Its framework migration recipes handle Spring Boot upgrades that would otherwise be manual work."),
    ("lib-sourcery", "Sourcery", "Тестирование и качество", "https://docs.sourcery.ai/", "freeTier", "python,refactoring,suggestions,ide", "pip install sourcery",
     "Suggests and applies Python refactorings as you write code.",
     "Предлагает и применяет рефакторинги Python прямо во время написания кода.",
     "Free for open-source projects, and its suggestions double as a way to learn idiomatic Python."),
]
