# -*- coding: utf-8 -*-
"""Stage 5 library pack J: security/crypto, parsing, dates/i18n, misc utilities."""

LIBS_5J = [
    # ---------- Безопасность и секреты (deepen) ----------
    ("lib-argon2", "Argon2", "Безопасность и секреты", "https://github.com/P-H-C/phc-winner-argon2", "openSource", "password-hashing,crypto,security,kdf", "pip install argon2-cffi",
     "The password-hashing competition winner, the current recommended default for new systems.",
     "Победитель конкурса алгоритмов хеширования паролей, рекомендуемый выбор для новых систем.",
     "Prefer this over bcrypt for new projects; both are far better than any general-purpose hash like SHA-256."),
    ("lib-bcrypt", "bcrypt", "Безопасность и секреты", "https://github.com/pyca/bcrypt", "openSource", "password-hashing,crypto,security,legacy", "pip install bcrypt",
     "Long-established password hashing function, still perfectly acceptable and widely supported.",
     "Давно проверенная функция хеширования паролей, до сих пор приемлема и широко поддерживается.",
     "Its 72-byte input limit silently truncates longer passwords — pre-hash if you allow long passphrases."),
    ("lib-libsodium", "libsodium", "Безопасность и секреты", "https://doc.libsodium.org/", "openSource", "crypto,encryption,nacl,modern", "",
     "Modern cryptography library with safe defaults and hard-to-misuse APIs.",
     "Современная криптографическая библиотека с безопасными настройками и API, который сложно применить неправильно.",
     "Its API deliberately hides algorithm choice — that is the feature, not a limitation."),
    ("lib-jose-jwt", "jose", "Безопасность и секреты", "https://github.com/panva/jose", "openSource", "jwt,jwe,jws,javascript", "npm i jose",
     "JavaScript implementation of JWT, JWS, JWE and JWK with modern crypto primitives.",
     "JavaScript-реализация JWT, JWS, JWE и JWK на современных криптопримитивах.",
     "Always verify the algorithm explicitly when validating a token — accepting 'none' is a classic JWT vulnerability."),
    ("lib-trivy", "Trivy", "Безопасность и секреты", "https://trivy.dev/latest/docs/", "openSource", "scanning,vulnerabilities,containers,iac", "brew install trivy",
     "Scans containers, filesystems and IaC for vulnerabilities and misconfigurations.",
     "Сканирует контейнеры, файловые системы и IaC на уязвимости и ошибки конфигурации.",
     "Add it as a CI step on your Dockerfile build — it catches vulnerable base images before they ship."),
    ("lib-gitleaks", "Gitleaks", "Безопасность и секреты", "https://github.com/gitleaks/gitleaks", "openSource", "secrets,scanning,git,pre-commit", "brew install gitleaks",
     "Detects hardcoded secrets and credentials in git repositories and history.",
     "Находит захардкоженные секреты и учётные данные в git-репозиториях и истории.",
     "Run it as a pre-commit hook — catching a key before it enters history saves a painful rotation later."),
    ("lib-semgrep-2", "Semgrep", "Безопасность и секреты", "https://semgrep.dev/docs/", "openSource", "sast,static-analysis,rules,security", "pip install semgrep",
     "Static analysis with readable, code-pattern-based rules for finding security bugs.",
     "Статический анализ с читаемыми правилами на основе паттернов кода для поиска уязвимостей.",
     "Rules look like the code they match, so writing a custom rule for your codebase takes minutes, not hours."),

    # ---------- Утилиты: parsing (deepen) ----------
    ("lib-valibot", "Valibot", "Утилиты", "https://valibot.dev/guides/introduction/", "openSource", "validation,typescript,tiny,tree-shakeable", "npm i valibot",
     "Schema validation for TypeScript with a much smaller bundle than Zod.",
     "Валидация схем для TypeScript с заметно меньшим размером бандла, чем у Zod.",
     "Its modular API means you only bundle the validators you actually import — the main win over Zod on the client."),
    ("lib-arktype", "ArkType", "Утилиты", "https://arktype.io/docs/intro/setup", "openSource", "validation,typescript,inference,syntax", "npm i arktype",
     "TypeScript validation using type-like syntax with full static inference.",
     "Валидация TypeScript с синтаксисом в духе типов и полным статическим выводом.",
     "Schemas read almost exactly like TypeScript type annotations, which keeps them easy to scan."),
    ("lib-yaml-js", "js-yaml", "Утилиты", "https://github.com/nodeca/js-yaml", "openSource", "yaml,parsing,javascript,config", "npm i js-yaml",
     "YAML parser and serializer for JavaScript.",
     "Парсер и сериализатор YAML для JavaScript.",
     "Use safeLoad semantics (the default in v4) — the unsafe loader can instantiate arbitrary JS types."),
    ("lib-papaparse", "PapaParse", "Утилиты", "https://www.papaparse.com/docs", "openSource", "csv,parsing,javascript,streaming", "npm i papaparse",
     "Fast in-browser CSV parser with streaming support for large files.",
     "Быстрый браузерный парсер CSV с потоковой обработкой больших файлов.",
     "Streaming mode parses multi-hundred-megabyte CSVs in the browser without exhausting memory."),
    ("lib-cheerio", "Cheerio", "Утилиты", "https://cheerio.js.org/docs/intro", "openSource", "html,parsing,jquery-like,scraping", "npm i cheerio",
     "Server-side HTML parsing with a jQuery-like API, no browser required.",
     "Парсинг HTML на сервере с API в духе jQuery, без браузера.",
     "Far faster than a headless browser for static HTML — only reach for Playwright when JS rendering is required."),
    ("lib-beautifulsoup", "Beautiful Soup", "Утилиты", "https://www.crummy.com/software/BeautifulSoup/bs4/doc/", "openSource", "html,parsing,python,scraping", "pip install beautifulsoup4",
     "The standard Python HTML/XML parsing library, tolerant of malformed markup.",
     "Стандартная библиотека парсинга HTML/XML в Python, устойчива к некорректной разметке.",
     "Pair it with the lxml parser backend for a substantial speed improvement over the built-in one."),
    ("lib-lxml", "lxml", "Утилиты", "https://lxml.de/", "openSource", "xml,html,python,xpath", "pip install lxml",
     "Fast XML and HTML processing for Python with full XPath support.",
     "Быстрая обработка XML и HTML в Python с полной поддержкой XPath.",
     "XPath handles deeply nested extraction far more concisely than chained CSS selector calls."),

    # ---------- Локализация и i18n (deepen) ----------
    ("lib-babel-python-i18n", "Babel (Python)", "Локализация и i18n", "https://babel.pocoo.org/", "openSource", "i18n,python,dates,gettext", "pip install babel",
     "Internationalization for Python: locale-aware date, number and currency formatting.",
     "Интернационализация для Python: форматирование дат, чисел и валют с учётом локали.",
     "It ships the CLDR locale database, so formatting matches platform conventions rather than hand-rolled rules."),
    ("lib-luxon", "Luxon", "Локализация и i18n", "https://moment.github.io/luxon/", "openSource", "dates,timezones,i18n,immutable", "npm i luxon",
     "Date and time library with first-class timezone and locale support, from the Moment.js team.",
     "Библиотека дат и времени с полноценной поддержкой часовых поясов и локалей от команды Moment.js.",
     "Its timezone handling is the reason to pick it over Day.js when you genuinely need multi-zone logic."),
    ("lib-temporal-polyfill", "Temporal API polyfill", "Локализация и i18n", "https://github.com/tc39/proposal-temporal", "openSource", "dates,javascript,standard,tc39", "npm i @js-temporal/polyfill",
     "Polyfill for the upcoming standard JavaScript date/time API replacing the flawed Date object.",
     "Полифил будущего стандартного API даты/времени JavaScript, заменяющего проблемный Date.",
     "Worth adopting now for new code — it becomes the platform standard and removes the need for a date library."),

    # ---------- Документация и контекст (deepen) ----------
    ("lib-typedoc", "TypeDoc", "Документация и контекст", "https://typedoc.org/", "openSource", "docs,typescript,api-reference,generation", "npm i -D typedoc",
     "Generates API documentation directly from TypeScript source and TSDoc comments.",
     "Генерирует документацию API прямо из исходников TypeScript и TSDoc-комментариев.",
     "Docs stay accurate because they are derived from the actual type signatures, not written separately."),
    ("lib-sphinx", "Sphinx", "Документация и контекст", "https://www.sphinx-doc.org/", "openSource", "docs,python,rst,generation", "pip install sphinx",
     "The standard Python documentation generator, behind most major Python project docs.",
     "Стандартный генератор документации Python, лежит в основе документации большинства крупных Python-проектов.",
     "autodoc pulls docstrings straight from source, so the API reference maintains itself."),
    ("lib-mkdocs", "MkDocs", "Документация и контекст", "https://www.mkdocs.org/", "openSource", "docs,markdown,static-site,python", "pip install mkdocs",
     "Markdown-based static documentation site generator, simpler than Sphinx.",
     "Генератор статических сайтов документации на Markdown, проще Sphinx.",
     "Material for MkDocs is the theme most projects actually use — install it alongside from the start."),
]
