# -*- coding: utf-8 -*-
# (iid, name, category, url, access, tags, summary_en, summary_ru, tip_en,
#  model, from_price, free_quota, pricing_url)
# These merge onto stage-5 entries carrying access='paid' so every such entry
# has a real price, per the same contract stage 1-4 pricing follows.
PAID_5 = [
("paid-docsumo","Docsumo","OCR и распознавание документов","https://www.docsumo.com/pricing","paid","ocr,documents,pricing,extraction",
 "Document AI extraction priced per page processed.",
 "Извлечение данных Document AI с оплатой за обработанную страницу.",
 "Ask for a trial batch on your actual document type before committing to a page-volume plan.",
 "usage","custom volume-based pricing","free trial on request","https://www.docsumo.com/pricing"),
("paid-openai-realtime","OpenAI Realtime API (pricing)","Голосовые агенты","https://platform.openai.com/docs/pricing","paid","voice,realtime,pricing,openai",
 "Speech-to-speech billed per audio minute plus token usage.",
 "Speech-to-speech с оплатой за минуту аудио плюс расход токенов.",
 "Audio tokens are the real cost driver — cap session length while prototyping.",
 "usage","from ~$0.06 / min audio input","no free tier","https://platform.openai.com/docs/pricing"),
("paid-close-crm","Close CRM (pricing)","CRM и продажи","https://close.com/pricing/","paid","crm,pricing,subscription,sales",
 "Per-seat subscription CRM pricing with calling minutes bundled in.",
 "Помесячная подписка CRM за место с включёнными минутами звонков.",
 "Compare seat price against Pipedrive/Attio before committing — Close targets outbound-heavy teams specifically.",
 "subscription","from ~$49 per seat per month","14-day free trial","https://close.com/pricing/"),
("paid-salesforce","Salesforce (pricing)","CRM и продажи","https://www.salesforce.com/editions-pricing/sales-cloud/","paid","crm,enterprise,pricing,subscription",
 "Enterprise per-seat CRM licensing, priced by edition tier.",
 "Корпоративное лицензирование CRM за место, цена зависит от редакции.",
 "The free Developer Edition org is enough to build and test an integration before any licensing talk.",
 "subscription","from ~$25 per seat per month","free Developer Edition for building","https://www.salesforce.com/editions-pricing/sales-cloud/"),
("paid-workday","Workday (pricing)","HR и рекрутинг","https://www.workday.com/en-us/pricing.html","paid","hr,enterprise,pricing,custom",
 "Enterprise HR/finance suite, quote-based pricing by employee count and modules.",
 "Корпоративный HR/финансовый комплекс, цена по запросу — по числу сотрудников и модулям.",
 "There is no self-serve tier at all — API access assumes an existing tenant contract.",
 "subscription","custom quote only","no self-serve tier","https://www.workday.com/en-us/pricing.html"),
("paid-onfido","Onfido (pricing)","Идентификация и KYC","https://onfido.com/pricing/","paid","identity,kyc,pricing,verification",
 "Per-check identity verification pricing, volume-tiered.",
 "Оплата за проверку личности, тарифы зависят от объёма.",
 "Sandbox checks are free and unlimited — validate the full flow before any billed check.",
 "usage","custom per-check pricing","free unlimited sandbox checks","https://onfido.com/pricing/"),
("paid-stripe-identity","Stripe Identity (pricing)","Идентификация и KYC","https://stripe.com/identity/pricing","paid","identity,kyc,pricing,stripe",
 "Per-verification pricing for government ID checks.",
 "Оплата за проверку по количеству верификаций государственных ID.",
 "Test mode verifications are free and unlimited for building the integration.",
 "usage","from ~$1.50 per verification","free test-mode verifications","https://stripe.com/identity/pricing"),
("paid-veriff","Veriff (pricing)","Идентификация и KYC","https://www.veriff.com/pricing","paid","identity,kyc,pricing,liveness",
 "Per-verification pricing with liveness detection included.",
 "Оплата за верификацию, liveness-детекция включена.",
 "Ask for the sandbox credentials explicitly — they are not self-serve on the pricing page.",
 "usage","custom per-verification pricing","sandbox available on request","https://www.veriff.com/pricing"),
("paid-attom-data","ATTOM Data (pricing)","Недвижимость","https://www.attomdata.com/solutions/property-data-api/","paid","real-estate,data,pricing,property",
 "Licensed property-data access, priced by dataset breadth and call volume.",
 "Лицензированный доступ к данным недвижимости, цена по широте датасета и объёму запросов.",
 "Request the free trial API key to check your target county's data coverage before licensing.",
 "subscription","custom licensing pricing","free trial key available","https://www.attomdata.com/solutions/property-data-api/"),
("paid-avalara","Avalara AvaTax (pricing)","Юридические и налоговые API","https://www.avalara.com/us/en/pricing.html","paid","tax,pricing,compliance,subscription",
 "Sales-tax calculation billed on transaction volume, tiered by plan.",
 "Расчёт налога с продаж с оплатой по объёму транзакций, тарифы по уровню плана.",
 "The developer sandbox mirrors production tax logic exactly, so integration testing costs nothing.",
 "usage","custom transaction-volume pricing","free developer sandbox","https://www.avalara.com/us/en/pricing.html"),
("paid-brightdata-mcp","Bright Data (pricing)","Браузер и автоматизация","https://brightdata.com/pricing","paid","scraping,proxy,pricing,residential",
 "Proxy and scraping infrastructure billed per GB or per successful request.",
 "Инфраструктура прокси и скрапинга с оплатой за ГБ или за успешный запрос.",
 "Start on the pay-as-you-go tier — committed volume plans only pay off once usage is predictable.",
 "usage","from ~$0.001 per request (pay-as-you-go)","free trial credit","https://brightdata.com/pricing"),
("paid-datadog-mcp","Datadog (pricing)","Мониторинг и аналитика","https://www.datadoghq.com/pricing/","paid","monitoring,pricing,observability,per-host",
 "Observability platform priced per host and per million log events.",
 "Платформа observability с оплатой за хост и за миллион событий логов.",
 "The 14-day full-feature trial is the only realistic way to estimate your actual host/log volume cost.",
 "subscription","from ~$15 per host per month","14-day free trial","https://www.datadoghq.com/pricing/"),
("paid-redox","Redox (pricing)","Здоровье и медицина","https://developer.redoxengine.com/","paid","healthcare,pricing,interop,custom",
 "Healthcare integration engine, quote-based pricing per connected data source.",
 "Движок интеграции здравоохранения, цена по запросу за каждый подключённый источник данных.",
 "Engage their team early — pricing depends heavily on which EHR systems you need normalized.",
 "subscription","custom quote per integration","sandbox access on request","https://developer.redoxengine.com/"),
("paid-marqeta","Marqeta (pricing)","Финансы","https://www.marqeta.com/platform/pricing","paid","cards,issuing,pricing,fintech",
 "Card issuing platform billed per active card plus interchange revenue share.",
 "Платформа выпуска карт с оплатой за активную карту плюс доля от interchange.",
 "The sandbox environment is free and full-featured — build the entire issuing flow before any commercial talk.",
 "usage","custom per-card and interchange pricing","free sandbox environment","https://www.marqeta.com/platform/pricing"),
("paid-stripe-treasury","Stripe Treasury (pricing)","Финансы","https://stripe.com/treasury/pricing","paid","banking,embedded,pricing,stripe",
 "Embedded banking priced per financial account plus transaction fees.",
 "Встроенный банкинг с оплатой за финансовый счёт плюс комиссии за транзакции.",
 "Requires a partnership conversation with Stripe before any pricing applies — this is not self-serve.",
 "usage","custom per-account and transaction pricing","partnership approval required","https://stripe.com/treasury/pricing"),
("paid-yodlee","Yodlee (pricing)","Финансы","https://www.yodlee.com/","paid","banking,aggregation,pricing,enterprise",
 "Enterprise financial data aggregation, quote-based pricing by connected accounts.",
 "Корпоративная агрегация финансовых данных, цена по запросу за подключённые счета.",
 "Expect an enterprise sales cycle — there is no public self-serve pricing page at all.",
 "subscription","custom enterprise quote","trial available via sales","https://www.yodlee.com/"),
("paid-optimizely","Optimizely (pricing)","A/B-тестирование","https://www.optimizely.com/pricing/","paid","ab-testing,pricing,enterprise,custom",
 "Enterprise experimentation platform, quote-based pricing by traffic and modules.",
 "Корпоративная платформа экспериментов, цена по запросу — по трафику и модулям.",
 "Ask for a proof-of-concept sandbox before signing — the platform is complex enough to need hands-on evaluation.",
 "subscription","custom quote by traffic volume","proof-of-concept trial via sales","https://www.optimizely.com/pricing/"),
("paid-vwo","VWO (pricing)","A/B-тестирование","https://vwo.com/pricing/","paid","ab-testing,pricing,conversion,subscription",
 "A/B testing and conversion tools priced by monthly tracked users.",
 "Инструменты A/B-тестирования и конверсии, цена по числу отслеживаемых пользователей в месяц.",
 "The free plan's visitor cap is tight — budget for the paid tier the moment you leave prototyping.",
 "subscription","from ~$217 per month","free plan for low traffic","https://vwo.com/pricing/"),
("paid-lightstep","Lightstep (pricing)","Наблюдаемость трасс","https://www.servicenow.com/products/observability/pricing.html","paid","tracing,pricing,observability,enterprise",
 "Distributed tracing and observability priced by ingested data volume.",
 "Распределённая трассировка и observability с оплатой по объёму принятых данных.",
 "Sample traces aggressively in high-volume services — ingestion volume is the direct cost driver.",
 "usage","custom quote by data volume","trial available via sales","https://www.servicenow.com/products/observability/pricing.html"),
("paid-aws-secrets-manager","AWS Secrets Manager (pricing)","Секреты и конфигурация","https://aws.amazon.com/secrets-manager/pricing/","paid","secrets,aws,pricing,per-secret",
 "Managed secrets storage billed per secret per month plus API call volume.",
 "Управляемое хранение секретов с оплатой за секрет в месяц плюс объём API-вызовов.",
 "Cache secret values in your app rather than fetching on every request — API calls are metered.",
 "usage","from ~$0.40 per secret per month","30-day free trial per secret","https://aws.amazon.com/secrets-manager/pricing/"),
("paid-statuspage-io","Statuspage (pricing)","Мониторинг и аналитика","https://www.atlassian.com/software/statuspage/pricing","paid","status-page,pricing,atlassian,subscription",
 "Public status page hosting priced by plan tier and subscriber count.",
 "Хостинг публичной статус-страницы с ценой по уровню плана и числу подписчиков.",
 "The cheapest tier covers a single status page fully — only upgrade once you need private pages or SSO.",
 "subscription","from ~$29 per month","14-day free trial","https://www.atlassian.com/software/statuspage/pricing"),
]
