# -*- coding: utf-8 -*-
"""Stage 5 API pack AC: AI coding agents and editors, code review automation, version control tooling."""

APIS_5AC = [
    # ---------- Редакторы и агенты ----------
    ("api-zed-editor", "Zed", "Разработка и DevOps", "https://zed.dev/docs/", "openSource", "editor,rust,collaborative,fast", "",
     "High-performance collaborative code editor written in Rust.",
     "Высокопроизводительный совместный редактор кода, написанный на Rust.",
     "Its GPU-accelerated rendering keeps typing latency low in files where other editors stutter."),
    ("api-roo-code", "Roo Code", "Разработка и DevOps", "https://docs.roocode.com/", "openSource", "vscode,agent,modes,autonomous", "",
     "Autonomous coding agent for VS Code with configurable operating modes.",
     "Автономный агент кодирования для VS Code с настраиваемыми режимами работы.",
     "Its per-mode permissions let a review mode read without granting it write access."),
    ("api-kilo-code", "Kilo Code", "Разработка и DevOps", "https://kilocode.ai/docs", "openSource", "vscode,agent,open-source,multi-model", "",
     "Open-source VS Code coding agent supporting many model providers.",
     "Открытый агент кодирования для VS Code с поддержкой множества провайдеров моделей.",
     "It merges features from several agent forks, so its capability set moves quickly."),
    ("api-openhands", "OpenHands", "Разработка и DevOps", "https://docs.all-hands.dev/", "openSource", "autonomous,sandbox,agent,research", "",
     "Open-source autonomous software development agent running in a sandbox.",
     "Открытый автономный агент разработки ПО, работающий в песочнице.",
     "Sandboxed execution is what makes letting an agent run arbitrary commands acceptable."),
    ("api-swe-agent", "SWE-agent", "Разработка и DevOps", "https://swe-agent.com/latest/", "openSource", "research,benchmarks,github-issues,princeton", "",
     "Research agent that resolves GitHub issues autonomously.",
     "Исследовательский агент, автономно решающий задачи из GitHub.",
     "Its agent-computer interface design is the interesting contribution, beyond the benchmark scores."),
    ("api-devin", "Devin", "Разработка и DevOps", "https://docs.devin.ai/", "paid", "autonomous,agent,cognition,tasks", "",
     "Autonomous software engineering agent working from task descriptions.",
     "Автономный агент разработки ПО, работающий по описанию задачи.",
     "Best suited to well-scoped repetitive tasks rather than open-ended feature work."),
    ("api-gemini-cli", "Gemini CLI", "Разработка и DevOps", "https://google-gemini.github.io/gemini-cli/", "freeTier", "google,terminal,agent,open-source", "npm i -g @google/gemini-cli",
     "Google's open-source terminal coding agent.",
     "Открытый терминальный агент кодирования от Google.",
     "Its free tier includes a substantial daily request allowance for individual use."),
    ("api-amp-code", "Amp", "Разработка и DevOps", "https://ampcode.com/manual", "paid", "sourcegraph,agent,terminal,codebase-aware", "",
     "Agentic coding tool from Sourcegraph with deep codebase context.",
     "Агентный инструмент кодирования от Sourcegraph с глубоким контекстом кодовой базы.",
     "Sourcegraph's code search underneath it is what gives it context across a large repository."),
    ("api-amazon-q-developer", "Amazon Q Developer", "Разработка и DevOps", "https://docs.aws.amazon.com/amazonq/latest/qdeveloper-ug/", "freeTier", "aws,assistant,transformation,security-scans", "",
     "AWS coding assistant with code transformation and security scanning.",
     "Ассистент кодирования AWS с преобразованием кода и сканированием безопасности.",
     "Its Java version upgrade transformation is the standout feature for legacy AWS estates."),
    ("api-supermaven", "Supermaven", "Разработка и DevOps", "https://supermaven.com/", "freeTier", "completion,fast,long-context,low-latency", "",
     "Very fast code completion with an unusually long context window.",
     "Очень быстрое автодополнение кода с необычно большим контекстным окном.",
     "Its latency is low enough that completions keep pace with fast typing, which most tools do not."),
    ("api-augment-code", "Augment Code", "Разработка и DevOps", "https://docs.augmentcode.com/", "paid", "codebase-context,enterprise,retrieval,agent", "",
     "Coding assistant built around deep retrieval over large codebases.",
     "Ассистент кодирования, построенный на глубоком поиске по большим кодовым базам.",
     "It is aimed at repositories too large for a model's context window to hold directly."),

    # ---------- Автоматизация code review ----------
    ("api-qodo", "Qodo", "Тестирование и качество", "https://docs.qodo.ai/", "freeTier", "code-review,tests,pr-agent,quality", "",
     "AI code review and test generation, formerly Codium.",
     "AI-ревью кода и генерация тестов, ранее Codium.",
     "Its open-source PR agent runs in your own CI, which keeps code inside your infrastructure."),
    ("api-coderabbit", "CodeRabbit", "Тестирование и качество", "https://docs.coderabbit.ai/", "freeTier", "code-review,pull-requests,context,line-comments", "",
     "AI pull request reviewer leaving line-level comments.",
     "AI-ревьюер pull request, оставляющий комментарии на уровне строк.",
     "Free for open-source repositories, which makes it easy to evaluate on real code."),
    ("api-greptile", "Greptile", "Тестирование и качество", "https://docs.greptile.com/", "paid", "code-review,codebase-graph,context,api", "",
     "Code review and search built on a graph of your entire codebase.",
     "Ревью и поиск по коду на основе графа всей вашей кодовой базы.",
     "Whole-repository context lets it flag a change that breaks a distant caller."),
    ("api-ellipsis", "Ellipsis", "Тестирование и качество", "https://docs.ellipsis.dev/", "paid", "code-review,bug-detection,pull-requests,fixes", "",
     "AI reviewer that comments on pull requests and can push fixes.",
     "AI-ревьюер, комментирующий pull request и способный отправлять исправления.",
     "Having it fix its own findings shortens the loop, provided review discipline stays intact."),
    ("api-graphite", "Graphite", "Git и совместная работа", "https://graphite.dev/docs", "freeTier", "stacked-prs,workflow,review,cli", "",
     "Stacked pull request workflow with a CLI and review interface.",
     "Рабочий процесс со стопками pull request, CLI и интерфейсом ревью.",
     "Stacking keeps each PR small and reviewable while still shipping a large change coherently."),
    ("api-reviewable", "Reviewable", "Git и совместная работа", "https://docs.reviewable.io/", "freeTier", "code-review,github,thorough,tracking", "",
     "Detailed code review tool layered on top of GitHub pull requests.",
     "Инструмент детального ревью кода поверх pull request GitHub.",
     "It tracks which revisions each reviewer has seen, which GitHub's own interface loses."),
    ("api-danger-js", "Danger", "Тестирование и качество", "https://danger.systems/js/", "openSource", "ci,conventions,pull-requests,automation", "npm i -D danger",
     "Automates team conventions as pull request checks.",
     "Автоматизирует командные соглашения как проверки pull request.",
     "It codifies the review comments you write repeatedly, so a bot leaves them instead."),

    # ---------- Инструменты контроля версий ----------
    ("api-difftastic", "Difftastic", "Git и совместная работа", "https://difftastic.wilfred.me.uk/", "openSource", "diff,syntax-aware,structural,rust", "",
     "Structural diff tool that compares syntax trees rather than lines.",
     "Инструмент структурного сравнения, сопоставляющий синтаксические деревья, а не строки.",
     "A reformatting-only change shows as no change at all, which line diffs cannot express."),
    ("api-delta-diff", "delta", "Git и совместная работа", "https://dandavison.github.io/delta/", "openSource", "diff,syntax-highlighting,git,pager", "",
     "Syntax-highlighting pager for git diff output.",
     "Пейджер с подсветкой синтаксиса для вывода git diff.",
     "Its side-by-side mode with word-level highlighting makes large diffs far easier to read."),
    ("api-semantic-diff", "SemanticDiff", "Git и совместная работа", "https://semanticdiff.com/", "freeTier", "diff,language-aware,pull-requests,noise-reduction", "",
     "Language-aware diffs that hide refactoring noise in pull requests.",
     "Диффы с учётом языка, скрывающие шум рефакторинга в pull request.",
     "Filtering out renames and moves leaves only the behavioural change to review."),
    ("api-git-absorb", "git-absorb", "Git и совместная работа", "https://github.com/tummychow/git-absorb", "openSource", "git,fixup,rebase,automation", "",
     "Automatically creates fixup commits targeting the right earlier commit.",
     "Автоматически создаёт fixup-коммиты, направленные в нужный более ранний коммит.",
     "It removes the manual work of finding which commit in a stack a change belongs to."),
    ("api-jujutsu", "Jujutsu (jj)", "Git и совместная работа", "https://jj-vcs.github.io/jj/latest/", "openSource", "vcs,git-compatible,rebase,undo", "",
     "Version control system with a simpler model, backed by Git repositories.",
     "Система контроля версий с более простой моделью поверх Git-репозиториев.",
     "It works against an existing Git repo, so you can try it without migrating anything."),
    ("api-sapling", "Sapling", "Git и совместная работа", "https://sapling-scm.com/docs/introduction/", "openSource", "vcs,meta,stacked,scalable", "",
     "Meta's version control system, designed for very large repositories.",
     "Система контроля версий Meta, рассчитанная на очень большие репозитории.",
     "Its stacked commit workflow is the part most worth borrowing, even if you stay on Git."),
    ("api-gerrit", "Gerrit", "Git и совместная работа", "https://gerrit-review.googlesource.com/Documentation/", "openSource", "code-review,change-based,self-host,google", "",
     "Change-based code review system used by Android and Chromium.",
     "Система ревью кода на основе changes, используемая в Android и Chromium.",
     "Reviewing individual commits rather than branches enforces a much tighter commit discipline."),
    ("api-phabricator", "Phorge (Phabricator)", "Git и совместная работа", "https://we.phorge.it/book/phorge/", "openSource", "code-review,self-host,community-fork,tools", "",
     "Community-maintained fork of Phabricator's development platform.",
     "Поддерживаемый сообществом форк платформы разработки Phabricator.",
     "Phabricator itself was discontinued — this fork carries the ongoing maintenance."),
    ("api-copilot-workspace", "GitHub Copilot Workspace", "Разработка и DevOps", "https://githubnext.com/projects/copilot-workspace", "freeTier", "github,issue-to-pr,planning,experimental", "",
     "Experimental GitHub environment taking an issue through to a pull request.",
     "Экспериментальная среда GitHub, проводящая задачу от issue до pull request.",
     "Its editable plan step is the useful part — you correct the approach before any code is written."),
]
