# -*- coding: utf-8 -*-
"""Stage 5 API pack Q: AI coding tools, dev productivity, code intelligence."""

APIS_5Q = [
    # ---------- AI и агенты: coding assistants ----------
    ("api-github-copilot", "GitHub Copilot", "AI и агенты", "https://docs.github.com/copilot", "paid", "coding,completion,github,assistant", "",
     "AI pair programmer with inline completion, chat and agentic coding modes.",
     "ИИ-напарник для программирования с инлайн-дополнением, чатом и агентными режимами.",
     "Free for verified students and maintainers of popular open-source projects — check eligibility first."),
    ("api-cursor", "Cursor", "AI и агенты", "https://docs.cursor.com/", "freeTier", "editor,ai,coding,agent", "",
     "AI-first code editor built as a VS Code fork with agentic editing.",
     "ИИ-ориентированный редактор кода на базе форка VS Code с агентным редактированием.",
     "Its .cursorrules file plays the same role as CLAUDE.md — project conventions the AI reads every time."),
    ("api-windsurf", "Windsurf", "AI и агенты", "https://docs.windsurf.com/", "freeTier", "editor,ai,agent,codeium", "",
     "Agentic AI code editor with a flow-based approach to multi-file changes.",
     "Агентный ИИ-редактор кода с flow-подходом к изменениям в нескольких файлах.",
     "Its Cascade mode keeps broader project context than single-file completion tools."),
    ("api-continue-dev", "Continue", "AI и агенты", "https://docs.continue.dev/", "openSource", "editor,ai,open-source,byo-model", "",
     "Open-source AI code assistant for VS Code and JetBrains, bring your own model.",
     "Открытый ИИ-ассистент кода для VS Code и JetBrains с подключением своей модели.",
     "Point it at a local Ollama model for fully offline completion with no code leaving your machine."),
    ("api-aider", "Aider", "AI и агенты", "https://aider.chat/docs/", "openSource", "cli,ai,coding,git", "pip install aider-install",
     "Terminal-based AI pair programmer that commits its changes to git directly.",
     "ИИ-напарник для программирования в терминале, коммитящий изменения прямо в git.",
     "Every edit becomes a git commit, so reverting a bad AI change is a normal git operation."),
    ("api-cline", "Cline", "AI и агенты", "https://docs.cline.bot/", "openSource", "vscode,agent,autonomous,coding", "",
     "Autonomous coding agent extension for VS Code with terminal and browser access.",
     "Расширение автономного агента-программиста для VS Code с доступом к терминалу и браузеру.",
     "It asks approval per action by default — review that setting before letting it run unattended."),
    ("api-codeium", "Codeium", "AI и агенты", "https://docs.codeium.com/", "freeTier", "completion,free,ide,autocomplete", "",
     "AI code completion with a genuinely free individual tier across many IDEs.",
     "ИИ-дополнение кода с по-настоящему бесплатным индивидуальным тарифом для многих IDE.",
     "The free individual plan is unusually complete, which makes it a low-risk first AI completion tool."),
    ("api-tabnine", "Tabnine", "AI и агенты", "https://docs.tabnine.com/", "freeTier", "completion,privacy,on-premise,enterprise", "",
     "Code completion with on-premise deployment options for privacy-sensitive teams.",
     "Дополнение кода с вариантами локального развёртывания для команд с требованиями к приватности.",
     "Its self-hosted option is the differentiator when code cannot leave your network at all."),
    ("api-sourcegraph", "Sourcegraph", "Документация и контекст", "https://sourcegraph.com/docs", "freeTier", "code-search,navigation,large-codebases,cody", "",
     "Code search and navigation across large multi-repository codebases.",
     "Поиск и навигация по коду в больших многорепозиторных кодовых базах.",
     "Its structural search finds code patterns, not just text, which regex-based search cannot express."),
    ("api-codeql", "CodeQL", "Безопасность и секреты", "https://codeql.github.com/docs/", "freeTier", "sast,security,queries,github", "",
     "Semantic code analysis engine treating code as data you can query for vulnerabilities.",
     "Движок семантического анализа кода, где код — данные, к которым можно писать запросы об уязвимостях.",
     "Free for public repositories via GitHub Advanced Security — enable it in the repo's security settings."),
    ("api-snyk", "Snyk", "Безопасность и секреты", "https://docs.snyk.io/", "freeTier", "dependencies,vulnerabilities,scanning,fix-prs", "",
     "Dependency, container and IaC vulnerability scanning with automated fix pull requests.",
     "Сканирование уязвимостей зависимостей, контейнеров и IaC с автоматическими PR с исправлениями.",
     "Its automated fix PRs are the practical differentiator over scanners that only report findings."),
    ("api-dependabot", "Dependabot", "Разработка и DevOps", "https://docs.github.com/code-security/dependabot", "free", "dependencies,updates,security,github", "",
     "Automated dependency update pull requests, built into GitHub for free.",
     "Автоматические pull request с обновлениями зависимостей, встроены в GitHub бесплатно.",
     "Group related updates in the config, or a large project drowns in one PR per package."),
    ("api-renovate", "Renovate", "Разработка и DevOps", "https://docs.renovatebot.com/", "openSource", "dependencies,updates,configurable,multi-platform", "",
     "Highly configurable dependency update bot, working beyond GitHub too.",
     "Гибко настраиваемый бот обновления зависимостей, работает не только на GitHub.",
     "More configurable than Dependabot — grouping, scheduling and automerge rules are far more expressive."),
    ("api-codacy", "Codacy", "Тестирование и качество", "https://docs.codacy.com/", "freeTier", "code-quality,static-analysis,coverage,ci", "",
     "Automated code review covering quality, coverage and security across many languages.",
     "Автоматическое ревью кода: качество, покрытие и безопасность для многих языков.",
     "Free for open source, which makes it easy to add quality gates to a public project."),
    ("api-deepsource", "DeepSource", "Тестирование и качество", "https://docs.deepsource.com/", "freeTier", "static-analysis,autofix,code-quality,ci", "",
     "Static analysis with autofix suggestions applied as pull requests.",
     "Статический анализ с автоисправлениями, применяемыми через pull request.",
     "Its autofix covers mechanical issues, leaving human review for genuine design questions."),
]
