# -*- coding: utf-8 -*-
"""Stage 5 library pack AH: typed API layers, query builders, Postgres tooling, GraphQL servers."""

LIBS_5AH = [
    # ---------- Backend фреймворки ----------
    ("lib-koa", "Koa", "Backend и API", "https://koajs.com/", "openSource", "node,middleware,minimal,async", "npm i koa",
     "Minimal Node framework from the Express team, built around async middleware.",
     "Минималистичный Node-фреймворк от команды Express, построенный на асинхронных middleware.",
     "Its middleware cascade unwinds after the response, which makes timing and cleanup logic natural."),
    ("lib-adonisjs", "AdonisJS", "Backend и API", "https://docs.adonisjs.com/", "openSource", "node,typescript,fullstack,batteries-included", "npm init adonisjs@latest",
     "Full-featured TypeScript backend framework with ORM, auth and validation included.",
     "Полнофункциональный TypeScript-фреймворк бэкенда с ORM, аутентификацией и валидацией из коробки.",
     "The closest thing Node has to Laravel — conventions instead of assembling a stack yourself."),
    ("lib-encore", "Encore", "Backend и API", "https://encore.dev/docs", "openSource", "typescript,go,infrastructure-from-code,distributed",
     "npm i encore.dev",
     "Backend framework that provisions infrastructure from your application code.",
     "Бэкенд-фреймворк, разворачивающий инфраструктуру на основе кода приложения.",
     "Declaring a queue or database in code generates the real resource, removing a separate IaC layer."),

    # ---------- Типобезопасные API-слои ----------
    ("lib-orpc", "oRPC", "Backend и API", "https://orpc.unnoq.com/docs/getting-started", "openSource", "typescript,rpc,openapi,end-to-end-types", "npm i @orpc/server",
     "End-to-end typed RPC that also emits a standard OpenAPI specification.",
     "Сквозная типизация RPC с генерацией стандартной OpenAPI-спецификации.",
     "Gives tRPC's type safety while staying callable by clients that only speak REST."),
    ("lib-ts-rest", "ts-rest", "Backend и API", "https://ts-rest.com/", "openSource", "typescript,rest,contracts,incremental", "npm i @ts-rest/core",
     "Type-safe REST contracts shared between client and server.",
     "Типобезопасные REST-контракты, общие для клиента и сервера.",
     "Adopts incrementally on an existing REST API, unlike RPC layers that require rewriting endpoints."),
    ("lib-zodios", "Zodios", "Backend и API", "https://www.zodios.org/", "openSource", "typescript,zod,axios,runtime-validation", "npm i @zodios/core",
     "Typed HTTP client and server built on Zod schemas and Axios.",
     "Типизированный HTTP-клиент и сервер на схемах Zod и Axios.",
     "Validates responses at runtime, which catches a backend contract change the type system cannot see."),
    ("lib-fp-ts", "fp-ts", "Языки и рантаймы", "https://gcanti.github.io/fp-ts/", "openSource", "typescript,functional,algebraic,composition", "npm i fp-ts",
     "Functional programming primitives for TypeScript: Option, Either and type classes.",
     "Примитивы функционального программирования для TypeScript: Option, Either и классы типов.",
     "Effect absorbed most of its ideas with a friendlier API — check that first for new projects."),
    ("lib-neverthrow", "neverthrow", "Языки и рантаймы", "https://github.com/supermacro/neverthrow", "openSource", "typescript,result,error-handling,minimal", "npm i neverthrow",
     "Typed Result values making error paths explicit without exceptions.",
     "Типизированные Result-значения, делающие пути ошибок явными без исключений.",
     "A much smaller commitment than a full functional runtime when you only want typed errors."),

    # ---------- Драйверы и построители запросов ----------
    ("lib-objection-js", "Objection.js", "Базы данных и ORM", "https://vincit.github.io/objection.js/", "openSource", "node,orm,knex,relations", "npm i objection knex",
     "SQL-friendly ORM built on Knex with strong relation handling.",
     "SQL-ориентированная ORM на базе Knex с сильной работой со связями.",
     "Its eager loading expressions fetch deep relation graphs in a predictable number of queries."),
    ("lib-slonik", "Slonik", "Базы данных и ORM", "https://github.com/gajus/slonik", "openSource", "postgres,sql,safety,tagged-templates", "npm i slonik",
     "Postgres client enforcing safe SQL through tagged template literals.",
     "Клиент Postgres, обеспечивающий безопасный SQL через тегированные шаблонные литералы.",
     "It refuses plain string queries outright, which structurally eliminates SQL injection."),
    ("lib-postgres-js", "postgres.js", "Базы данных и ORM", "https://github.com/porsager/postgres", "openSource", "postgres,fast,tagged-templates,node", "npm i postgres",
     "Fast, small Postgres client for Node using tagged template queries.",
     "Быстрый компактный клиент Postgres для Node с запросами через тегированные шаблоны.",
     "Its performance and pipelining are why Drizzle and others default to it as a driver."),
    ("lib-node-postgres", "node-postgres (pg)", "Базы данных и ORM", "https://node-postgres.com/", "openSource", "postgres,driver,pooling,mature", "npm i pg",
     "The long-established Postgres driver for Node, with connection pooling.",
     "Давно устоявшийся драйвер Postgres для Node с пулом соединений.",
     "The most battle-tested option — many higher-level libraries ultimately sit on top of it."),

    # ---------- Postgres: расширения и инфраструктура ----------
    ("lib-pgvector", "pgvector", "Векторные базы", "https://github.com/pgvector/pgvector", "openSource", "postgres,embeddings,similarity,extension", "",
     "Postgres extension adding vector storage and similarity search.",
     "Расширение Postgres, добавляющее хранение векторов и поиск по сходству.",
     "Keeping embeddings beside your relational data removes an entire separate vector database."),
    ("lib-pg-cron", "pg_cron", "Базы данных и ORM", "https://github.com/citusdata/pg_cron", "openSource", "postgres,scheduling,jobs,extension", "",
     "Runs scheduled jobs inside Postgres using cron syntax.",
     "Выполняет запланированные задачи внутри Postgres по синтаксису cron.",
     "Good for database maintenance; a job that outlives a connection still belongs in a real queue."),
    ("lib-pg-partman", "pg_partman", "Базы данных и ORM", "https://github.com/pgpartman/pg_partman", "openSource", "postgres,partitioning,time-series,maintenance", "",
     "Automates creation and retention of Postgres table partitions.",
     "Автоматизирует создание и удержание партиций таблиц Postgres.",
     "Automatic partition rotation makes dropping old data instant instead of a long DELETE."),
    ("lib-supavisor", "Supavisor", "Базы данных и ORM", "https://supabase.github.io/supavisor/", "openSource", "postgres,pooling,elixir,multi-tenant", "",
     "Cloud-native Postgres connection pooler built for multi-tenant scale.",
     "Cloud-native пул соединений Postgres, рассчитанный на мультиарендный масштаб.",
     "Handles far more concurrent clients than PgBouncer, which matters for serverless workloads."),
    ("lib-pgpool", "Pgpool-II", "Базы данных и ORM", "https://www.pgpool.net/docs/latest/en/html/", "openSource", "postgres,pooling,load-balancing,replication", "",
     "Postgres middleware providing pooling, load balancing and replication management.",
     "Middleware для Postgres с пулом соединений, балансировкой нагрузки и управлением репликацией.",
     "Does more than pooling, and that extra scope is also its main operational risk."),
    ("lib-timescaledb-toolkit", "TimescaleDB Toolkit", "Data engineering", "https://github.com/timescale/timescaledb-toolkit", "openSource", "postgres,time-series,analytics,hyperfunctions", "",
     "Time-series analysis functions for Postgres and TimescaleDB.",
     "Функции анализа временных рядов для Postgres и TimescaleDB.",
     "Its hyperfunctions express downsampling and gap-filling in SQL that would otherwise need application code."),
    ("lib-prisma-accelerate", "Prisma Accelerate", "Базы данных и ORM", "https://www.prisma.io/docs/accelerate", "freeTier", "prisma,connection-pooling,caching,edge", "",
     "Global connection pooling and query caching for Prisma at the edge.",
     "Глобальный пул соединений и кэширование запросов для Prisma на edge.",
     "Solves the serverless connection-exhaustion problem that plain Prisma hits at scale."),

    # ---------- Автоматические API поверх базы ----------
    ("lib-postgrest", "PostgREST", "Backend и API", "https://docs.postgrest.org/", "openSource", "postgres,rest,auto-generated,rls", "",
     "Serves a full REST API generated directly from a Postgres schema.",
     "Отдаёт полноценный REST API, сгенерированный напрямую из схемы Postgres.",
     "Authorization lives in row-level security policies, so the database enforces access, not middleware."),
    ("lib-hasura", "Hasura", "Backend и API", "https://hasura.io/docs/", "mixed", "graphql,postgres,permissions,realtime", "",
     "Instant GraphQL API over your databases with a declarative permission system.",
     "Мгновенный GraphQL API поверх ваших баз данных с декларативной системой разрешений.",
     "Its subscriptions give realtime updates without writing any WebSocket handling code."),
    ("lib-postgraphile", "PostGraphile", "Backend и API", "https://www.graphile.org/postgraphile/", "openSource", "graphql,postgres,introspection,plugins", "",
     "Generates a GraphQL schema by introspecting a Postgres database.",
     "Генерирует GraphQL-схему через интроспекцию базы данных Postgres.",
     "Database comments become GraphQL descriptions, so documentation lives with the schema itself."),
    ("lib-grafbase", "Grafbase", "Backend и API", "https://grafbase.com/docs", "freeTier", "graphql,federation,edge,gateway", "",
     "GraphQL federation gateway running at the edge.",
     "Шлюз GraphQL-федерации, работающий на edge.",
     "Its Rust gateway adds noticeably less latency than JavaScript federation gateways."),
    ("lib-wundergraph", "WunderGraph", "Backend и API", "https://wundergraph.com/docs", "openSource", "graphql,federation,bff,api-composition", "",
     "Composes REST, GraphQL and databases into one typed API layer.",
     "Объединяет REST, GraphQL и базы данных в один типизированный слой API.",
     "Compiles operations at build time, so clients send a short operation id rather than a full query."),

    # ---------- GraphQL серверы и схемы ----------
    ("lib-apollo-federation", "Apollo Federation", "Backend и API", "https://www.apollographql.com/docs/graphos/schema-design/federated-schemas/federation", "mixed", "graphql,federation,supergraph,microservices", "",
     "Composes many GraphQL services into a single federated supergraph.",
     "Объединяет множество GraphQL-сервисов в единый федеративный supergraph.",
     "Entity resolution across services is powerful and easy to make slow — watch the query plans."),
    ("lib-graphql-nexus", "Nexus", "Backend и API", "https://nexusjs.org/docs/", "openSource", "graphql,code-first,typescript,schema", "npm i nexus",
     "Code-first GraphQL schema construction for TypeScript.",
     "Code-first построение GraphQL-схемы для TypeScript.",
     "Largely superseded by Pothos, which has better type inference for the same approach."),
    ("lib-gqlgen", "gqlgen", "Go экосистема", "https://gqlgen.com/", "openSource", "go,graphql,schema-first,codegen", "go get github.com/99designs/gqlgen",
     "Schema-first GraphQL server generator for Go.",
     "Генератор GraphQL-серверов для Go по схеме.",
     "Generating resolvers from the schema means a schema change becomes a compile error, not a runtime bug."),
    ("lib-strawberry-graphql", "Strawberry GraphQL", "Backend и API", "https://strawberry.rocks/docs", "openSource", "python,graphql,type-hints,dataclasses", "pip install strawberry-graphql",
     "Python GraphQL library defining schemas with ordinary type hints.",
     "Python-библиотека GraphQL, определяющая схемы обычными аннотациями типов.",
     "Its dataclass-style definitions read like normal Python, unlike older schema-string approaches."),
    ("lib-ariadne", "Ariadne", "Backend и API", "https://ariadnegraphql.org/docs/intro", "openSource", "python,graphql,schema-first,sdl", "pip install ariadne",
     "Schema-first Python GraphQL library using standard SDL.",
     "Schema-first Python-библиотека GraphQL на стандартном SDL.",
     "Keeping the schema in SDL lets frontend and backend share one canonical contract file."),
]
