# -*- coding: utf-8 -*-
"""Stage 5 API pack D: gaming/social, more consumer data, dev-services depth."""

APIS_5D = [
    # ---------- Игры и развлечения (deepen) ----------
    ("api-steam-web-api", "Steam Web API", "Игры и развлечения", "https://steamcommunity.com/dev", "free", "steam,gaming,profiles,achievements", "",
     "Player profiles, owned games, achievements and friend lists from Steam.",
     "Профили игроков, купленные игры, достижения и списки друзей из Steam.",
     "Most player data requires the profile to be public — private profiles return near-empty results."),
    ("api-riot-games", "Riot Games API", "Игры и развлечения", "https://developer.riotgames.com/", "freeTier", "gaming,league-of-legends,valorant,esports", "",
     "Match history, ranks and stats for League of Legends, Valorant and other Riot titles.",
     "История матчей, ранги и статистика League of Legends, Valorant и других игр Riot.",
     "Regional routing matters — a player's data lives on their region's specific API endpoint."),
    ("api-igdb", "IGDB", "Игры и развлечения", "https://api-docs.igdb.com/", "free", "games,database,covers,metadata", "",
     "Twitch-owned game database with covers, ratings and release metadata.",
     "База данных игр от Twitch с обложками, рейтингами и метаданными релизов.",
     "Auth goes through Twitch's OAuth, not a separate IGDB key — reuse a Twitch dev app if you have one."),
    ("api-chess-com", "Chess.com API", "Игры и развлечения", "https://www.chess.com/news/view/published-data-api", "noKey", "chess,games,no-key,stats", "",
     "Public player stats, game archives and titled-player data, no key required.",
     "Публичная статистика игроков, архивы партий и данные титулованных игроков, ключ не нужен.",
     "Monthly game archives are the efficient way to pull history — avoid paging single games."),
    ("api-open-trivia-2", "TriviaAPI.dev", "Игры и развлечения", "https://the-trivia-api.com/docs/", "noKey", "trivia,quiz,questions,no-key", "",
     "Trivia questions with difficulty tagging and category filters, no key required.",
     "Вопросы для викторин с тегами сложности и фильтрами категорий, ключ не нужен.",
     "The regions parameter filters culturally specific questions — useful for a non-US audience."),
    ("api-twitch-api", "Twitch API", "Игры и развлечения", "https://dev.twitch.tv/docs/api/", "free", "twitch,streaming,live,chat", "",
     "Streams, channels, clips and chat data from Twitch's live-streaming platform.",
     "Стримы, каналы, клипы и данные чата с платформы живых трансляций Twitch.",
     "EventSub webhooks replace polling for stream-online notifications — set them up instead of a cron loop."),

    # ---------- Новости и сообщества (deepen) ----------
    ("api-newsdata-io", "NewsData.io", "Новости и сообщества", "https://newsdata.io/documentation", "freeTier", "news,articles,search,free-tier", "",
     "News article search and headlines across thousands of sources, with a real free tier.",
     "Поиск новостных статей и заголовков по тысячам источников с реальным бесплатным тарифом.",
     "Filter by category and country server-side — the free tier's daily quota goes further that way."),
    ("api-gnews", "GNews", "Новости и сообщества", "https://gnews.io/docs/", "freeTier", "news,google,search,headlines", "",
     "News search API powered by Google News indexing.",
     "API поиска новостей на основе индексации Google News.",
     "The free tier's 100 requests/day is enough for a daily-digest feature, not a live news app."),
    ("api-bluesky-api", "Bluesky (AT Protocol)", "Новости и сообщества", "https://docs.bsky.app/", "free", "bluesky,social,atproto,federated", "",
     "Post and read data on Bluesky via the open AT Protocol.",
     "Публикация и чтение данных Bluesky через открытый AT Protocol.",
     "The protocol is federated by design — a Bluesky-hosted PDS is the easy starting point before self-hosting."),

    # ---------- Игры и развлечения / Еда (deepen further) ----------
    ("api-nutritionix", "Nutritionix", "Еда и быт", "https://developer.nutritionix.com/docs/v2", "freeTier", "nutrition,food,calories,natural-language", "",
     "Natural-language food logging: \"2 eggs and toast\" returns full nutrition data.",
     "Логирование еды на естественном языке: «2 яйца и тост» возвращает полные данные о питании.",
     "The natural-language endpoint saves you from building your own food-parsing logic entirely."),
    ("api-edamam", "Edamam", "Еда и быт", "https://developer.edamam.com/", "freeTier", "recipes,nutrition,food,diet-labels", "",
     "Recipe search and nutrition analysis with diet and allergen labeling.",
     "Поиск рецептов и анализ питания с маркировкой диет и аллергенов.",
     "Recipe Search and Nutrition Analysis are separate APIs with separate keys — check which one you need."),

    # ---------- Транспорт и город (deepen) ----------
    ("api-here-traffic", "HERE Traffic API", "Транспорт и город", "https://www.here.com/docs/bundle/traffic-api-developer-guide-v7/", "freeTier", "traffic,routing,realtime,here", "",
     "Real-time traffic flow and incident data for routing applications.",
     "Данные о трафике и инцидентах в реальном времени для приложений маршрутизации.",
     "Combine flow and incidents endpoints — flow alone misses road closures that incidents catches."),
    ("api-citymapper", "Citymapper API", "Транспорт и город", "https://citymapper.com/api", "mixed", "transit,routing,multimodal,cities", "",
     "Multimodal city routing combining transit, walking, cycling and rideshare.",
     "Мультимодальная маршрутизация по городу: транспорт, пешком, велосипед, райдшеринг.",
     "Coverage is limited to Citymapper's supported cities — check the list before depending on it."),
    ("api-flightaware", "FlightAware AeroAPI", "Транспорт и город", "https://www.flightaware.com/aeroapi/", "mixed", "flights,tracking,aviation,realtime", "",
     "Real-time and historical flight tracking data.",
     "Данные отслеживания рейсов в реальном времени и исторические.",
     "Historical queries are billed separately and more expensively than live tracking — check pricing per call type."),
    ("api-aviationstack", "Aviationstack", "Транспорт и город", "https://aviationstack.com/documentation", "freeTier", "flights,tracking,aviation,free-tier", "",
     "Flight status and schedule data with a genuinely usable free tier.",
     "Данные о статусе и расписании рейсов с реально полезным бесплатным тарифом.",
     "Free tier is HTTP-only, not HTTPS — check your compliance requirements before relying on it in production."),

    # ---------- Дизайн-системы / изображения (deepen) ----------
    ("api-canva-connect", "Canva Connect API", "Изображения и дизайн", "https://www.canva.dev/docs/connect/", "freeTier", "design,templates,export,canva", "",
     "Programmatically create and export designs from Canva templates.",
     "Программное создание и экспорт дизайнов из шаблонов Canva.",
     "Autofill APIs populate a brand template with your data — faster than building a design generator from scratch."),
    ("api-bannerbear", "Bannerbear", "Изображения и дизайн", "https://developers.bannerbear.com/", "freeTier", "images,automation,templates,social", "",
     "Automated image and video generation from templates, built for social media assets.",
     "Автоматическая генерация изображений и видео из шаблонов для соцсетей.",
     "Design the template once in their editor, then generate hundreds of variants via one API call each."),
    ("api-placid", "Placid", "Изображения и дизайн", "https://placid.app/docs", "freeTier", "images,templates,automation,og-images", "",
     "Template-based image generation, popular specifically for dynamic OG/social preview images.",
     "Генерация изображений по шаблонам, особенно популярна для динамических OG-превью для соцсетей.",
     "Generate Open Graph images per page at build time — it turns generic link previews into branded ones."),

    # ---------- Финансы / Крипто (deepen) ----------
    ("api-etherscan", "Etherscan API", "Финансы", "https://docs.etherscan.io/", "freeTier", "ethereum,blockchain,explorer,transactions", "",
     "Query Ethereum transactions, balances and contract data via the leading block explorer.",
     "Запрос транзакций, балансов и данных контрактов Ethereum через ведущий block explorer.",
     "Rate limits are per-key and strict on the free tier — cache anything that doesn't need to be live."),
    ("api-alchemy", "Alchemy", "Финансы", "https://docs.alchemy.com/", "freeTier", "web3,rpc,ethereum,infrastructure", "",
     "Managed blockchain node infrastructure and enhanced APIs for Ethereum and other chains.",
     "Управляемая инфраструктура блокчейн-нод и расширенные API для Ethereum и других сетей.",
     "Enhanced APIs (NFT, token balances) save you from indexing chain data yourself for common queries."),
    ("api-coinmarketcap", "CoinMarketCap API", "Финансы", "https://coinmarketcap.com/api/documentation/v1/", "freeTier", "crypto,prices,market-cap,rankings", "",
     "Cryptocurrency prices, market caps and rankings from the widely cited data source.",
     "Цены, капитализация и рейтинги криптовалют из широко цитируемого источника данных.",
     "The free tier's monthly credit resets matter for scheduling — batch requests instead of polling per-coin."),

    # ---------- Наблюдаемость / DevOps (deepen) ----------
    ("api-pagerduty", "PagerDuty API", "Мониторинг и аналитика", "https://developer.pagerduty.com/", "freeTier", "incidents,oncall,alerting,api", "",
     "Trigger, acknowledge and resolve incidents programmatically, and manage on-call schedules.",
     "Программное создание, подтверждение и закрытие инцидентов, управление дежурствами.",
     "Use Events API v2 for triggering alerts from monitoring — the REST API is for managing PagerDuty itself."),
    ("api-opsgenie", "Opsgenie API", "Мониторинг и аналитика", "https://docs.opsgenie.com/docs/api-overview", "freeTier", "incidents,oncall,alerting,atlassian", "",
     "Incident alerting and on-call scheduling, Atlassian's alternative to PagerDuty.",
     "Оповещение об инцидентах и дежурства — альтернатива PagerDuty от Atlassian.",
     "Bundled free with some Jira Service Management plans — check if you already have access before paying separately."),
    ("api-statuspage-io", "Statuspage API", "Мониторинг и аналитика", "https://developer.statuspage.io/", "paid", "status-page,incidents,communication,atlassian", "",
     "Manage a public status page and post incident updates programmatically.",
     "Управление публичной статус-страницей и программная публикация обновлений об инцидентах.",
     "Wire it to your alerting pipeline so a triggered incident auto-drafts a status page update."),

    # ---------- Наука (deepen) ----------
    ("api-noaa", "NOAA APIs", "Наука и исследования", "https://www.weather.gov/documentation/services-web-api", "noKey", "weather,climate,noaa,no-key", "",
     "US government weather, climate and ocean data, no key required.",
     "Государственные данные США о погоде, климате и океане, ключ не нужен.",
     "Grid-point forecasts are more precise than city-level ones — resolve coordinates to a grid point first."),
    ("api-usgs-water", "USGS Water Services", "Наука и исследования", "https://waterservices.usgs.gov/", "noKey", "water,rivers,usgs,no-key", "",
     "Real-time river, lake and groundwater monitoring data across the US.",
     "Данные мониторинга рек, озёр и подземных вод в реальном времени по США.",
     "Site numbers are the stable identifier — resolve a location to its nearest gauge site once and cache it."),
    ("api-ncbi-eutils", "NCBI E-utilities", "Наука и исследования", "https://www.ncbi.nlm.nih.gov/books/NBK25497/", "free", "genomics,pubmed,ncbi,bioinformatics", "",
     "Programmatic access to PubMed, GenBank and the rest of NCBI's biomedical databases.",
     "Программный доступ к PubMed, GenBank и остальным биомедицинским базам NCBI.",
     "Register an API key even though it's optional — it triples your rate limit for free."),
]
