# -*- coding: utf-8 -*-
"""Stage 5 library pack AE: mobile testing, mobile CI/CD, crash reporting, monetization SDKs."""

LIBS_5AE = [
    # ---------- Мобильное тестирование ----------
    ("lib-detox", "Detox", "Mobile skills", "https://wix.github.io/Detox/docs/introduction/getting-started", "openSource", "react-native,e2e,grey-box,synchronization", "npm i -D detox",
     "Grey-box end-to-end testing for React Native that waits for the app to settle.",
     "Grey-box E2E тестирование для React Native, ожидающее стабилизации приложения.",
     "Automatic synchronization with the app's event loop removes almost all arbitrary sleep calls."),
    ("lib-maestro", "Maestro", "Mobile skills", "https://docs.maestro.dev/", "openSource", "mobile,e2e,yaml,simple", "",
     "Mobile UI testing driven by simple YAML flows, tolerant of timing and flakiness.",
     "Тестирование мобильного интерфейса простыми YAML-сценариями, устойчивое к таймингам и нестабильности.",
     "Built-in tolerance for slow rendering means far fewer flaky failures than raw Appium scripts."),
    ("lib-appium", "Appium", "Mobile skills", "https://appium.io/docs/en/latest/", "openSource", "mobile,webdriver,cross-platform,automation", "npm i -g appium",
     "WebDriver-based mobile automation across iOS, Android and beyond.",
     "Мобильная автоматизация на основе WebDriver для iOS, Android и других платформ.",
     "One test suite drives both platforms, at the cost of being slower than each platform's native runner."),
    ("lib-xcuitest", "XCUITest", "Mobile skills", "https://developer.apple.com/documentation/xctest/user-interface-tests", "free", "ios,apple,ui-testing,native", "",
     "Apple's native UI testing framework for iOS and macOS apps.",
     "Нативный фреймворк UI-тестирования Apple для приложений iOS и macOS.",
     "Fastest and most reliable on iOS, since it runs inside Apple's own testing infrastructure."),
    ("lib-espresso", "Espresso", "Mobile skills", "https://developer.android.com/training/testing/espresso", "free", "android,ui-testing,google,native", "",
     "Google's native Android UI testing framework with automatic synchronization.",
     "Нативный фреймворк UI-тестирования Android от Google с автоматической синхронизацией.",
     "Its idling resource mechanism handles async work that would otherwise need explicit waits."),
    ("lib-robolectric", "Robolectric", "Mobile skills", "https://robolectric.org/", "openSource", "android,unit-tests,jvm,fast", "",
     "Runs Android unit tests on the JVM without an emulator or device.",
     "Запускает модульные тесты Android на JVM без эмулятора или устройства.",
     "Seconds instead of minutes per run, which is what makes Android TDD practical at all."),
    ("lib-patrol", "Patrol", "Mobile skills", "https://patrol.leancode.co/", "openSource", "flutter,integration-tests,native-interactions,permissions", "",
     "Flutter integration testing that can also drive native permission dialogs.",
     "Интеграционное тестирование Flutter, способное управлять и нативными диалогами разрешений.",
     "Handling the OS permission prompt is exactly where plain Flutter integration tests give up."),

    # ---------- Мобильный CI/CD и доставка ----------
    ("lib-fastlane", "Fastlane", "Mobile skills", "https://docs.fastlane.tools/", "openSource", "ios,android,automation,release", "gem install fastlane",
     "Automates mobile builds, signing, screenshots and store submission.",
     "Автоматизирует сборку, подписание, скриншоты и публикацию мобильных приложений.",
     "Its match tool for shared signing certificates solves the single worst part of iOS releases."),
    ("lib-codemagic", "Codemagic", "Mobile skills", "https://docs.codemagic.io/", "freeTier", "ci-cd,flutter,mobile,macos-runners", "",
     "Mobile-focused CI/CD with first-class Flutter support and macOS build machines.",
     "CI/CD с фокусом на мобильную разработку, полноценной поддержкой Flutter и macOS-раннерами.",
     "Its free tier includes real macOS minutes, which most general CI providers charge heavily for."),
    ("lib-bitrise", "Bitrise", "Mobile skills", "https://devcenter.bitrise.io/", "freeTier", "ci-cd,mobile,workflows,steps", "",
     "Mobile CI/CD platform built from composable workflow steps.",
     "Платформа мобильного CI/CD, собираемая из композируемых шагов workflow.",
     "Its step library covers most mobile release chores without writing shell scripts."),
    ("lib-eas-build", "EAS Build", "Mobile skills", "https://docs.expo.dev/build/introduction/", "freeTier", "expo,react-native,cloud-builds,credentials", "npm i -g eas-cli",
     "Expo's cloud build service for React Native apps, including credential management.",
     "Облачный сервис сборки Expo для приложений React Native, включая управление сертификатами.",
     "Handles iOS signing credentials for you, which removes the usual reason to own a Mac."),
    ("lib-firebase-app-distribution", "Firebase App Distribution", "Mobile skills", "https://firebase.google.com/docs/app-distribution", "free", "beta,testing,distribution,free", "",
     "Free pre-release app distribution to testers on iOS and Android.",
     "Бесплатное распространение предрелизных сборок тестировщикам на iOS и Android.",
     "Free at any scale, and unlike TestFlight it needs no App Store review for each build."),
    ("lib-testflight", "TestFlight", "Mobile skills", "https://developer.apple.com/testflight/", "free", "ios,beta,apple,distribution", "",
     "Apple's official beta distribution for iOS apps, up to ten thousand testers.",
     "Официальное бета-распространение iOS-приложений от Apple, до десяти тысяч тестировщиков.",
     "External testing needs a review pass, so plan a day of lead time before a public beta."),

    # ---------- Крэши и диагностика ----------
    ("lib-firebase-crashlytics", "Firebase Crashlytics", "Mobile skills", "https://firebase.google.com/docs/crashlytics", "free", "crashes,mobile,free,google", "",
     "Free crash reporting for mobile apps with grouped, prioritized issues.",
     "Бесплатные отчёты о падениях мобильных приложений с группировкой и приоритизацией проблем.",
     "Free without volume limits, which is why it remains the default even alongside paid alternatives."),
    ("lib-bugsnag", "Bugsnag", "Мониторинг и аналитика", "https://docs.bugsnag.com/", "freeTier", "errors,stability,releases,cross-platform", "",
     "Error monitoring organized around a stability score per release.",
     "Мониторинг ошибок, построенный вокруг оценки стабильности каждого релиза.",
     "Its stability target turns 'should we roll back' into a threshold rather than a judgement call."),
    ("lib-instabug", "Instabug", "Mobile skills", "https://docs.instabug.com/", "freeTier", "bug-reporting,in-app,feedback,mobile", "",
     "In-app bug reporting capturing screenshots, logs and device state from users.",
     "Внутриприложенческие баг-репорты со скриншотами, логами и состоянием устройства от пользователей.",
     "Shake-to-report gets reproduction details from real users that a store review never contains."),
    ("lib-embrace-io", "Embrace", "Mobile skills", "https://embrace.io/docs/", "paid", "mobile,observability,sessions,performance", "",
     "Mobile observability reconstructing complete user sessions around each problem.",
     "Мобильная observability, восстанавливающая полные пользовательские сессии вокруг каждой проблемы.",
     "Session-level context catches non-crash failures — frozen frames, silent network errors — that crash tools miss."),
    ("lib-sentry-mobile", "Sentry for Mobile", "Mobile skills", "https://docs.sentry.io/platforms/apple/", "freeTier", "crashes,performance,sessions,cross-platform", "",
     "Sentry's mobile SDKs for crash reporting and performance across iOS, Android and Flutter.",
     "Мобильные SDK Sentry для отчётов о падениях и производительности на iOS, Android и Flutter.",
     "Sharing one error platform with your backend makes cross-tier incidents far easier to correlate."),

    # ---------- Подписки и монетизация ----------
    ("lib-revenuecat-sdk", "RevenueCat SDK", "Платежи и commerce", "https://www.revenuecat.com/docs/", "freeTier", "subscriptions,iap,cross-platform,entitlements", "",
     "Cross-platform in-app subscription infrastructure with server-side entitlements.",
     "Кроссплатформенная инфраструктура подписок в приложении с серверными правами доступа.",
     "Its entitlement model means you check one flag rather than reconciling App Store and Play receipts."),
    ("lib-adapty", "Adapty", "Платежи и commerce", "https://adapty.io/docs/", "freeTier", "subscriptions,paywalls,ab-testing,analytics", "",
     "Subscription infrastructure with remotely configurable paywalls and A/B testing.",
     "Инфраструктура подписок с удалённо настраиваемыми paywall и A/B-тестированием.",
     "Changing a paywall without an app release is what makes pricing experiments actually feasible."),
    ("lib-superwall", "Superwall", "Платежи и commerce", "https://superwall.com/docs/home", "freeTier", "paywalls,experiments,remote-config,mobile", "",
     "Remotely built and tested paywalls, decoupled from app releases.",
     "Paywall, создаваемые и тестируемые удалённо, независимо от релизов приложения.",
     "Focused purely on the paywall layer — it pairs with, rather than replaces, subscription backends."),
    ("lib-qonversion", "Qonversion", "Платежи и commerce", "https://documentation.qonversion.io/", "freeTier", "subscriptions,analytics,segmentation,mobile", "",
     "Subscription management with revenue analytics and user segmentation.",
     "Управление подписками с аналитикой выручки и сегментацией пользователей.",
     "Combines the entitlement layer with cohort revenue reporting, avoiding a second analytics tool."),

    # ---------- Атрибуция ----------
    ("lib-appsflyer", "AppsFlyer", "CDP и маркетинг-данные", "https://dev.appsflyer.com/", "paid", "attribution,mobile,campaigns,deep-links", "",
     "Mobile attribution platform measuring which campaigns drive installs and revenue.",
     "Платформа мобильной атрибуции, измеряющая, какие кампании приносят установки и выручку.",
     "Post-ATT attribution is probabilistic on iOS — treat the numbers as directional, not exact."),
    ("lib-adjust", "Adjust", "CDP и маркетинг-данные", "https://dev.adjust.com/", "paid", "attribution,fraud-prevention,mobile,analytics", "",
     "Mobile measurement platform with strong ad-fraud prevention.",
     "Платформа мобильных измерений с сильной защитой от рекламного фрода.",
     "Its fraud filtering typically pays for itself on any meaningful paid acquisition budget."),
    ("lib-branch-io", "Branch", "CDP и маркетинг-данные", "https://help.branch.io/developers-hub/docs", "freeTier", "deep-links,attribution,deferred,mobile", "",
     "Deep linking and attribution, including deferred links that survive app installation.",
     "Диплинки и атрибуция, включая отложенные ссылки, переживающие установку приложения.",
     "Deferred deep linking routes a new user to the right screen after install, which plain links cannot."),
    ("lib-singular", "Singular", "CDP и маркетинг-данные", "https://support.singular.net/hc/en-us/categories/360002441132", "paid", "attribution,marketing-analytics,roi,mobile", "",
     "Marketing analytics unifying attribution with ad spend for ROI reporting.",
     "Маркетинговая аналитика, объединяющая атрибуцию с рекламными расходами для отчётов по ROI.",
     "Joining cost data to attribution is the part that turns installs into an actual ROI figure."),

    # ---------- Поведенческая аналитика и session replay ----------
    ("lib-fullstory", "FullStory", "Мониторинг и аналитика", "https://developer.fullstory.com/", "paid", "session-replay,analytics,frustration-signals,web", "",
     "Session replay and behavioural analytics with automatic frustration detection.",
     "Запись сессий и поведенческая аналитика с автоматическим выявлением признаков раздражения.",
     "Its rage-click and dead-click signals surface broken interactions no error tracker reports."),
    ("lib-logrocket", "LogRocket", "Мониторинг и аналитика", "https://docs.logrocket.com/", "freeTier", "session-replay,console-logs,network,debugging", "",
     "Session replay combined with console logs, network traffic and Redux state.",
     "Запись сессий вместе с логами консоли, сетевым трафиком и состоянием Redux.",
     "Replaying a bug with the network calls and state attached removes most reproduction guesswork."),
    ("lib-smartlook", "Smartlook", "Мониторинг и аналитика", "https://docs.smartlook.com/", "freeTier", "session-replay,mobile,heatmaps,events", "",
     "Session recording and heatmaps covering both web and native mobile apps.",
     "Запись сессий и тепловые карты для веба и нативных мобильных приложений.",
     "Native mobile replay is the differentiator — most replay tools are web-only."),
    ("lib-hotjar", "Hotjar", "Мониторинг и аналитика", "https://help.hotjar.com/hc/en-us", "freeTier", "heatmaps,recordings,surveys,feedback", "",
     "Heatmaps, session recordings and on-site surveys for understanding user behaviour.",
     "Тепловые карты, записи сессий и опросы на сайте для понимания поведения пользователей.",
     "Its on-page surveys collect the 'why' that heatmaps and analytics can only hint at."),
    ("lib-microsoft-clarity", "Microsoft Clarity", "Мониторинг и аналитика", "https://learn.microsoft.com/en-us/clarity/", "free", "heatmaps,session-replay,free,unlimited", "",
     "Free unlimited heatmaps and session recordings from Microsoft.",
     "Бесплатные безлимитные тепловые карты и записи сессий от Microsoft.",
     "Genuinely free at any traffic volume, which makes the paid alternatives a harder sell."),
    ("lib-contentsquare", "Contentsquare", "Мониторинг и аналитика", "https://docs.contentsquare.com/", "paid", "experience-analytics,enterprise,journeys,zoning", "",
     "Enterprise digital experience analytics measuring engagement zone by zone.",
     "Корпоративная аналитика цифрового опыта, измеряющая вовлечённость по зонам страницы.",
     "Its zoning analysis quantifies which page regions earn attention, beyond click counts."),
    ("lib-heap", "Heap", "Мониторинг и аналитика", "https://developers.heap.io/", "freeTier", "autocapture,retroactive,analytics,events", "",
     "Analytics that autocaptures every interaction, allowing retroactive event definition.",
     "Аналитика с автозахватом всех взаимодействий, позволяющая определять события задним числом.",
     "You can answer questions about the past without having instrumented them in advance."),

    # ---------- Онбординг и product adoption ----------
    ("lib-pendo", "Pendo", "Мониторинг и аналитика", "https://support.pendo.io/hc/en-us", "paid", "product-analytics,in-app-guides,feedback,adoption", "",
     "Product analytics combined with in-app guides and user feedback collection.",
     "Продуктовая аналитика вместе с внутриприложенческими подсказками и сбором обратной связи.",
     "Measuring a feature and guiding users to it in one tool shortens the adoption feedback loop."),
    ("lib-appcues", "Appcues", "UI и frontend", "https://docs.appcues.com/", "paid", "onboarding,tours,no-code,adoption", "",
     "No-code in-app onboarding flows and product tours.",
     "No-code онбординг и продуктовые туры внутри приложения.",
     "Product teams ship onboarding changes without engineering, which is the entire value proposition."),
    ("lib-userpilot", "Userpilot", "UI и frontend", "https://docs.userpilot.com/", "paid", "onboarding,engagement,surveys,segmentation", "",
     "In-app onboarding and engagement flows targeted by user segment.",
     "Онбординг и вовлечение внутри приложения с таргетингом по сегментам пользователей.",
     "Segment-targeted flows avoid showing a power user the same tour as a first-time visitor."),
    ("lib-chameleon", "Chameleon", "UI и frontend", "https://help.chameleon.io/", "paid", "product-tours,tooltips,surveys,customization", "",
     "Highly customizable in-product tours, tooltips and microsurveys.",
     "Гибко настраиваемые продуктовые туры, подсказки и микроопросы внутри продукта.",
     "Its styling control is the reason to pick it when tours must look native to your design system."),
    ("lib-intro-js", "Intro.js", "UI и frontend", "https://introjs.com/docs", "mixed", "tours,onboarding,lightweight,vanilla", "npm i intro.js",
     "Lightweight library for step-by-step product tours and hints.",
     "Лёгкая библиотека пошаговых продуктовых туров и подсказок.",
     "Free under AGPL; commercial use in a closed-source product requires a paid licence."),
    ("lib-shepherd-js", "Shepherd.js", "UI и frontend", "https://shepherdjs.dev/docs/", "openSource", "tours,guides,accessible,floating-ui", "npm i shepherd.js",
     "Guided tour library built on Floating UI with solid accessibility.",
     "Библиотека пошаговых туров на Floating UI с хорошей доступностью.",
     "Focus management and keyboard navigation work correctly, which most tour libraries neglect."),
    ("lib-driver-js", "Driver.js", "UI и frontend", "https://driverjs.com/docs/installation", "openSource", "tours,highlight,tiny,vanilla", "npm i driver.js",
     "Tiny dependency-free library for highlighting elements and driving tours.",
     "Крошечная библиотека без зависимостей для подсветки элементов и проведения туров.",
     "A few kilobytes with no dependencies, which suits a simple one-off walkthrough."),
    ("lib-react-joyride", "React Joyride", "UI и frontend", "https://docs.react-joyride.com/", "openSource", "react,tours,steps,callbacks", "npm i react-joyride",
     "Step-by-step product tours as a React component with lifecycle callbacks.",
     "Пошаговые продуктовые туры как React-компонент с колбэками жизненного цикла.",
     "Its callbacks let you record tour progress as analytics events to see where users abandon."),
]
