# -*- coding: utf-8 -*-
"""Stage 5 library pack AT: vector databases, search engines, embedded search, ANN indexes."""

LIBS_5AT = [
    # ---------- Векторные базы ----------
    ("lib-milvus", "Milvus", "Векторные базы", "https://milvus.io/docs", "openSource", "vector,scalable,distributed,cncf", "pip install pymilvus",
     "Distributed vector database built for billion-scale similarity search.",
     "Распределённая векторная база данных для поиска по сходству на миллиардах векторов.",
     "Operationally heavy — its scale only pays off well past what pgvector handles comfortably."),
    ("lib-weaviate", "Weaviate", "Векторные базы", "https://docs.weaviate.io/", "openSource", "vector,graphql,hybrid-search,modules", "pip install weaviate-client",
     "Vector database with GraphQL queries and built-in hybrid search.",
     "Векторная база данных с GraphQL-запросами и встроенным гибридным поиском.",
     "Hybrid search combining keywords and vectors usually beats either alone on real queries."),
    ("lib-lancedb", "LanceDB", "Векторные базы", "https://lancedb.github.io/lancedb/", "openSource", "embedded,columnar,serverless,multimodal", "pip install lancedb",
     "Embedded vector database storing data in a columnar format on disk.",
     "Встраиваемая векторная база данных, хранящая данные в колоночном формате на диске.",
     "It runs in-process like SQLite, which removes a whole service from a small RAG deployment."),
    ("lib-turbopuffer", "turbopuffer", "Векторные базы", "https://turbopuffer.com/docs", "paid", "vector,object-storage,cheap,serverless", "",
     "Vector search built on object storage, priced for very large cold datasets.",
     "Векторный поиск на объектном хранилище с ценой, рассчитанной на очень большие холодные наборы данных.",
     "Object storage makes it far cheaper per vector than memory-resident databases, at higher cold latency."),
    ("lib-zilliz-cloud", "Zilliz Cloud", "Векторные базы", "https://docs.zilliz.com/", "freeTier", "managed,milvus,vector,serverless", "",
     "Managed Milvus service with a serverless tier.",
     "Управляемый сервис Milvus с serverless-тарифом.",
     "Worth it over self-hosted Milvus purely for avoiding its operational complexity."),
    ("lib-pinecone-serverless", "Pinecone Serverless", "Векторные базы", "https://docs.pinecone.io/guides/index-data/indexing-overview", "freeTier", "managed,serverless,vector,usage-based", "pip install pinecone",
     "Serverless vector database billed by usage rather than provisioned capacity.",
     "Serverless векторная база данных с оплатой по использованию, а не по выделенной ёмкости.",
     "Usage-based billing removed the idle-pod cost that made its earlier model expensive to prototype on."),
    ("lib-upstash-vector", "Upstash Vector", "Векторные базы", "https://upstash.com/docs/vector", "freeTier", "serverless,rest,edge,pay-per-request", "",
     "Serverless vector database with a REST API and per-request pricing.",
     "Serverless векторная база данных с REST API и оплатой за запрос.",
     "A REST interface means it works from edge runtimes where TCP database drivers cannot."),
    ("lib-cloudflare-vectorize", "Vectorize", "Векторные базы", "https://developers.cloudflare.com/vectorize/", "freeTier", "cloudflare,workers,edge,integrated", "",
     "Cloudflare's vector database, integrated with Workers and Workers AI.",
     "Векторная база данных Cloudflare, интегрированная с Workers и Workers AI.",
     "Embedding and querying inside one Worker keeps the whole RAG path at the edge."),
    ("lib-sqlite-vec", "sqlite-vec", "Векторные базы", "https://alexgarcia.xyz/sqlite-vec/", "openSource", "sqlite,extension,embedded,portable", "pip install sqlite-vec",
     "Vector search as a SQLite extension, running anywhere SQLite does.",
     "Векторный поиск как расширение SQLite, работающее везде, где работает SQLite.",
     "It runs in a browser via WASM and on a phone, which no server-based vector database can."),

    # ---------- Поисковые движки ----------
    ("lib-opensearch", "OpenSearch", "Поиск и retrieval", "https://docs.opensearch.org/", "openSource", "search,fork,apache-2,analytics", "",
     "Apache-licensed search and analytics engine, forked from Elasticsearch.",
     "Поисковый и аналитический движок под лицензией Apache, форк Elasticsearch.",
     "Its permissive licence is the reason cloud providers and licence-sensitive organizations chose it."),
    ("lib-elasticsearch", "Elasticsearch", "Поиск и retrieval", "https://www.elastic.co/docs", "mixed", "search,aggregations,mature,ecosystem", "",
     "Mature distributed search engine with powerful aggregations.",
     "Зрелый распределённый поисковый движок с мощными агрегациями.",
     "Its aggregation framework does analytical work that lighter search engines cannot approach."),
    ("lib-manticore-search", "Manticore Search", "Поиск и retrieval", "https://manual.manticoresearch.com/", "openSource", "search,fast,sphinx,sql", "",
     "Fast open-source search engine with a SQL interface, successor to Sphinx.",
     "Быстрый открытый поисковый движок с SQL-интерфейсом, преемник Sphinx.",
     "Its SQL interface makes it approachable to anyone who has never learned a search DSL."),
    ("lib-tantivy", "Tantivy", "Поиск и retrieval", "https://docs.rs/tantivy/latest/tantivy/", "openSource", "rust,library,full-text,lucene-like", "cargo add tantivy",
     "Full-text search library for Rust, comparable to Lucene.",
     "Библиотека полнотекстового поиска для Rust, сопоставимая с Lucene.",
     "It is a library, not a server, so search runs in your process with no network hop."),
    ("lib-bleve", "Bleve", "Go экосистема", "https://blevesearch.com/docs/Home/", "openSource", "go,full-text,library,indexing", "go get github.com/blevesearch/bleve/v2",
     "Full-text search and indexing library for Go.",
     "Библиотека полнотекстового поиска и индексации для Go.",
     "Embedding search in a Go binary avoids operating a separate search service entirely."),
    ("lib-sonic-search", "Sonic", "Поиск и retrieval", "https://github.com/valeriansaliou/sonic", "openSource", "lightweight,rust,schema-less,identifiers", "",
     "Very lightweight search index returning identifiers rather than documents.",
     "Очень лёгкий поисковый индекс, возвращающий идентификаторы вместо документов.",
     "It stores no documents, so memory use stays tiny and your database remains the source of truth."),
    ("lib-paradedb", "ParadeDB", "Поиск и retrieval", "https://docs.paradedb.com/", "openSource", "postgres,full-text,bm25,extension", "",
     "Postgres extension bringing Elasticsearch-quality full-text search.",
     "Расширение Postgres, приносящее полнотекстовый поиск качества Elasticsearch.",
     "Proper BM25 ranking inside Postgres removes the need to sync data into a search cluster."),
    ("lib-redisearch", "RediSearch", "Поиск и retrieval", "https://redis.io/docs/latest/develop/interact/search-and-query/", "mixed", "redis,search,vector,secondary-index", "",
     "Search and secondary indexing inside Redis, including vector similarity.",
     "Поиск и вторичная индексация внутри Redis, включая векторное сходство.",
     "If Redis is already in the stack, this often removes the need for a separate search service."),
    ("lib-pg-search", "pg_search", "Поиск и retrieval", "https://github.com/paradedb/paradedb/tree/dev/pg_search", "openSource", "postgres,bm25,tantivy,extension", "",
     "BM25 full-text search for Postgres, built on Tantivy.",
     "Полнотекстовый поиск BM25 для Postgres на базе Tantivy.",
     "Its ranking is substantially better than Postgres's built-in text search for relevance-sensitive queries."),

    # ---------- Клиентский поиск ----------
    ("lib-flexsearch", "FlexSearch", "Поиск и retrieval", "https://github.com/nextapps-de/flexsearch", "openSource", "client-side,fast,memory,zero-dependency", "npm i flexsearch",
     "Very fast in-memory full-text search for the browser and Node.",
     "Очень быстрый полнотекстовый поиск в памяти для браузера и Node.",
     "Fast enough that a documentation site can search thousands of pages entirely client-side."),
    ("lib-ufuzzy", "uFuzzy", "Поиск и retrieval", "https://github.com/leeoniya/uFuzzy", "openSource", "fuzzy,tiny,ranking,regex", "npm i @leeoniya/ufuzzy",
     "Tiny fuzzy search library with careful result ranking.",
     "Крошечная библиотека нечёткого поиска с продуманным ранжированием результатов.",
     "Its ranking is noticeably better than Fuse.js on typo-heavy queries, at a fraction of the size."),

    # ---------- Индексы приближённого поиска ----------
    ("lib-faiss", "Faiss", "Векторные базы", "https://faiss.ai/", "openSource", "ann,meta,gpu,library", "pip install faiss-cpu",
     "Meta's library for efficient similarity search over dense vectors.",
     "Библиотека Meta для эффективного поиска по сходству среди плотных векторов.",
     "Most vector databases use it internally, so understanding its index types explains their tradeoffs."),
    ("lib-hnswlib", "hnswlib", "Векторные базы", "https://github.com/nmslib/hnswlib", "openSource", "ann,hnsw,fast,header-only", "pip install hnswlib",
     "Fast approximate nearest neighbour search using the HNSW graph algorithm.",
     "Быстрый приближённый поиск ближайших соседей по графовому алгоритму HNSW.",
     "HNSW trades memory for speed, which is why in-memory vector stores default to it."),
    ("lib-voyager", "Voyager", "Векторные базы", "https://spotify.github.io/voyager/", "openSource", "ann,spotify,python,java", "pip install voyager",
     "Spotify's approximate nearest neighbour library for Python and Java.",
     "Библиотека приближённого поиска ближайших соседей от Spotify для Python и Java.",
     "Its successor to Annoy, with better recall at comparable query speed."),
]
