# -*- coding: utf-8 -*-
"""Stage 5 API pack R: regional/local APIs, misc reference data, niche services."""

APIS_5R = [
    # ---------- Открытые данные: regional ----------
    ("api-insee", "INSEE API", "Открытые данные", "https://api.insee.fr/catalogue/", "free", "france,statistics,companies,government", "",
     "French national statistics and company registry (SIRENE) data.",
     "Национальная статистика Франции и реестр компаний (SIRENE).",
     "SIRENE is the authoritative source for French company identifiers, free and comprehensive."),
    ("api-bundesbank", "Deutsche Bundesbank API", "Финансы", "https://www.bundesbank.de/en/statistics/time-series-databases", "free", "germany,economics,timeseries,central-bank", "",
     "German central bank time series: interest rates, exchange rates, economic indicators.",
     "Временные ряды центрального банка Германии: ставки, курсы валют, экономические показатели.",
     "Series keys are structured and stable, which makes automated economic dashboards straightforward."),
    ("api-ecb", "ECB Data Portal API", "Финансы", "https://data.ecb.europa.eu/help/api/overview", "free", "europe,central-bank,rates,statistics", "",
     "European Central Bank statistics: rates, monetary aggregates, exchange rates.",
     "Статистика Европейского центрального банка: ставки, денежные агрегаты, курсы валют.",
     "The official source behind most free FX APIs — go direct if you need reference rates specifically."),
    ("api-worldbank-2", "World Bank Indicators API", "Открытые данные", "https://datahelpdesk.worldbank.org/knowledgebase/articles/889392", "free", "development,indicators,countries,timeseries", "",
     "Development indicators for every country across decades.",
     "Показатели развития по каждой стране за десятилетия.",
     "Indicator codes are stable across releases, so a dashboard built on them keeps working long-term."),
    ("api-imf", "IMF Data API", "Финансы", "https://datahelp.imf.org/knowledgebase/articles/667681", "free", "imf,economics,global,statistics", "",
     "International Monetary Fund macroeconomic and financial statistics.",
     "Макроэкономическая и финансовая статистика Международного валютного фонда.",
     "SDMX format is verbose — most people build a thin wrapper to flatten it before use."),
    ("api-nasdaq-data-link", "Nasdaq Data Link", "Финансы", "https://docs.data.nasdaq.com/", "freeTier", "finance,datasets,economics,alternative-data", "",
     "Financial, economic and alternative datasets, formerly Quandl.",
     "Финансовые, экономические и альтернативные датасеты, ранее Quandl.",
     "Many datasets are free while others need per-dataset purchase — check licensing before building on one."),

    # ---------- Погода и геоданные: regional ----------
    ("api-dwd", "DWD Open Data", "Погода и геоданные", "https://www.dwd.de/EN/ourservices/opendata/opendata.html", "free", "germany,weather,official,open-data", "",
     "German Weather Service open data: forecasts, observations, radar and climate records.",
     "Открытые данные немецкой метеослужбы: прогнозы, наблюдения, радар и климатические записи.",
     "Data comes as files on an open FTP/HTTPS server rather than a REST API — plan for file parsing."),
    ("api-met-no", "MET Norway Weather API", "Погода и геоданные", "https://api.met.no/weatherapi/documentation", "free", "weather,norway,global,no-key", "",
     "Norwegian Meteorological Institute forecasts, free and global, no key required.",
     "Прогнозы Норвежского метеорологического института, бесплатно и глобально, без ключа.",
     "Requires a proper identifying User-Agent; anonymous requests are blocked outright."),
    ("api-nws", "US National Weather Service API", "Погода и геоданные", "https://www.weather.gov/documentation/services-web-api", "free", "weather,usa,government,no-key", "",
     "Official US weather forecasts, alerts and observations, free with no key.",
     "Официальные прогнозы погоды США, оповещения и наблюдения, бесплатно и без ключа.",
     "Alert feeds are the most valuable part — official severe weather warnings straight from the source."),

    # ---------- Утилиты (deepen further) ----------
    ("api-abstract-2", "Abstract API suite", "Утилиты", "https://docs.abstractapi.com/", "freeTier", "validation,email,phone,ip", "",
     "Collection of small utility APIs: email validation, phone validation, IP geolocation.",
     "Набор небольших утилитарных API: валидация email, телефонов, геолокация по IP.",
     "Each API has its own key and quota — they are separate products under one brand."),
    ("api-numverify", "numverify", "Утилиты", "https://numverify.com/documentation", "freeTier", "phone,validation,carrier,format", "",
     "Phone number validation with carrier and line-type detection.",
     "Валидация телефонных номеров с определением оператора и типа линии.",
     "Validate format client-side first and only call the API for numbers that pass — it saves quota."),
    ("api-hunter-io", "Hunter", "Утилиты", "https://hunter.io/api-documentation", "freeTier", "email,verification,finder,outreach", "",
     "Email finding and verification for outreach and lead generation.",
     "Поиск и верификация email для аутрича и генерации лидов.",
     "Verify before sending — bounce rates directly damage your sending domain's reputation."),
    ("api-zerobounce", "ZeroBounce", "Утилиты", "https://www.zerobounce.net/docs/", "freeTier", "email,validation,deliverability,bounce", "",
     "Email validation service detecting invalid, disposable and catch-all addresses.",
     "Сервис валидации email, определяющий недействительные, одноразовые и catch-all адреса.",
     "Clean an imported list before the first campaign — a bad first send is hard to recover from."),
    ("api-clearbit", "Clearbit (Breeze Intelligence)", "CRM и продажи", "https://dashboard.clearbit.com/docs", "paid", "enrichment,company-data,b2b,leads", "",
     "Company and contact data enrichment from an email or domain.",
     "Обогащение данных о компаниях и контактах по email или домену.",
     "Now part of HubSpot, so check current availability and packaging before designing around it."),
    ("api-apollo-io", "Apollo.io", "CRM и продажи", "https://docs.apollo.io/", "freeTier", "sales,leads,enrichment,prospecting", "",
     "B2B contact database and sales engagement platform with enrichment APIs.",
     "База B2B-контактов и платформа продаж с API обогащения данных.",
     "Check data-protection obligations before storing enriched personal contact data in your own systems."),

    # ---------- Изображения и дизайн (deepen) ----------
    ("api-screenshotone", "ScreenshotOne", "Изображения и дизайн", "https://screenshotone.com/docs/", "freeTier", "screenshots,rendering,api,og-images", "",
     "Website screenshot API with ad blocking, custom viewports and full-page capture.",
     "API скриншотов сайтов с блокировкой рекламы, настраиваемыми вьюпортами и захватом всей страницы.",
     "Cache rendered screenshots aggressively — rendering is the expensive part, not serving the image."),
    ("api-urlbox", "Urlbox", "Изображения и дизайн", "https://urlbox.com/docs/overview", "paid", "screenshots,rendering,pdf,api", "",
     "Website rendering API producing screenshots, PDFs and full-page captures.",
     "API рендеринга сайтов, создающий скриншоты, PDF и захваты всей страницы.",
     "Its signed-URL mode lets you generate images client-side without exposing the API key."),
    ("api-htmlcsstoimage", "HTML/CSS to Image", "Изображения и дизайн", "https://docs.htmlcsstoimage.com/", "freeTier", "rendering,html,images,templates", "",
     "Renders arbitrary HTML and CSS into an image, useful for dynamic social cards.",
     "Рендерит произвольный HTML и CSS в изображение, удобно для динамических карточек соцсетей.",
     "Templates with variables avoid sending the full HTML on every request, which speeds things up noticeably."),
]
