# -*- coding: utf-8 -*-
"""Stage 5 library pack Y: geospatial stack, tiles, 3D/WebGL engines."""

LIBS_5Y = [
    # ---------- Геоданные: обработка ----------
    ("lib-gdal", "GDAL", "Погода и геоданные", "https://gdal.org/en/stable/", "openSource", "raster,vector,conversion,geospatial", "",
     "The foundational translator library for raster and vector geospatial formats.",
     "Фундаментальная библиотека-транслятор растровых и векторных геопространственных форматов.",
     "Almost every geospatial tool wraps it — learning ogr2ogr and gdal_translate pays off everywhere."),
    ("lib-s2-geometry", "S2 Geometry", "Погода и геоданные", "https://s2geometry.io/", "openSource", "spherical,indexing,google,cells", "",
     "Google's spherical geometry library indexing the globe as hierarchical cells.",
     "Библиотека сферической геометрии Google, индексирующая земной шар иерархическими ячейками.",
     "Spherical rather than planar math avoids the distortion that bites flat projections near the poles."),
    ("lib-pygeos-shapely2", "pygeos", "Погода и геоданные", "https://pygeos.readthedocs.io/", "openSource", "python,vectorized,geometry,numpy", "",
     "Vectorized geometry operations for Python, now merged into Shapely 2.",
     "Векторизованные геометрические операции для Python, теперь объединены в Shapely 2.",
     "Use Shapely 2 directly for new code — this package exists mainly for legacy compatibility."),

    # ---------- Геоданные: карты и тайлы ----------
    ("lib-openlayers", "OpenLayers", "Карты и навигация", "https://openlayers.org/doc/", "openSource", "maps,web,ogc,projections", "npm i ol",
     "Feature-rich web mapping library with strong OGC standards and projection support.",
     "Богатая веб-картографическая библиотека с сильной поддержкой стандартов OGC и проекций.",
     "The right choice when you need WMS, WFS and arbitrary projections that lighter libraries skip."),
    ("lib-mapbox-gl-js", "Mapbox GL JS", "Карты и навигация", "https://docs.mapbox.com/mapbox-gl-js/guides/", "mixed", "maps,vector-tiles,webgl,styling", "npm i mapbox-gl",
     "WebGL vector-tile map renderer with runtime styling and smooth zooming.",
     "WebGL-рендерер векторных тайлов с рантайм-стилизацией и плавным зумом.",
     "Version 2 onward is not open source — MapLibre is the fork to use if the licence matters."),
    ("lib-protomaps", "Protomaps", "Карты и навигация", "https://docs.protomaps.com/", "openSource", "tiles,static,pmtiles,serverless", "",
     "Serves entire vector basemaps from a single static file, with no tile server.",
     "Отдаёт целые векторные базовые карты из одного статического файла без тайл-сервера.",
     "A whole-planet basemap on static hosting removes the map server bill entirely."),
    ("lib-pmtiles", "PMTiles", "Карты и навигация", "https://docs.protomaps.com/pmtiles/", "openSource", "tiles,single-file,range-requests,cloud", "",
     "Single-file tile archive format read directly over HTTP range requests.",
     "Однофайловый формат архива тайлов, читаемый напрямую через HTTP range-запросы.",
     "The browser fetches only the byte ranges it needs, so a huge archive costs no extra bandwidth."),
    ("lib-tippecanoe", "Tippecanoe", "Карты и навигация", "https://github.com/felt/tippecanoe", "openSource", "tiles,generation,geojson,mbtiles", "brew install tippecanoe",
     "Builds vector tilesets from large GeoJSON inputs with automatic zoom-level simplification.",
     "Строит наборы векторных тайлов из больших GeoJSON с автоматическим упрощением по уровням зума.",
     "Its per-zoom feature dropping is what keeps a million-point dataset renderable at low zoom."),
    ("lib-martin-tiles", "Martin", "Карты и навигация", "https://maplibre.org/martin/", "openSource", "tile-server,postgis,rust,mvt", "",
     "Fast Rust tile server publishing vector tiles straight from PostGIS.",
     "Быстрый tile-сервер на Rust, публикующий векторные тайлы прямо из PostGIS.",
     "Serving tiles directly from the database keeps them live without a regeneration pipeline."),
    ("lib-kepler-gl", "Kepler.gl", "Графики и визуализация", "https://docs.kepler.gl/", "openSource", "geospatial,visualization,exploration,uber", "npm i kepler.gl",
     "Geospatial analysis and visualization tool for large location datasets.",
     "Инструмент геопространственного анализа и визуализации для больших наборов геоданных.",
     "Its no-code browser UI lets analysts explore data before anyone writes a visualization."),
    ("lib-cesium", "CesiumJS", "Анимация и 3D", "https://cesium.com/learn/cesiumjs-learn/", "openSource", "3d-globe,terrain,geospatial,webgl", "npm i cesium",
     "3D globe and map engine for geospatial visualization with real terrain data.",
     "Движок 3D-глобуса и карт для геопространственной визуализации с реальными данными рельефа.",
     "The only mainstream option when altitude and true 3D terrain actually matter to the visualization."),
    ("lib-overture-maps", "Overture Maps", "Открытые данные", "https://docs.overturemaps.org/", "openSource", "open-data,basemap,places,buildings", "",
     "Open map dataset of places, buildings, transportation and boundaries.",
     "Открытый набор картографических данных: места, здания, транспорт и границы.",
     "Distributed as GeoParquet, so you query it with DuckDB rather than importing a whole database."),
    ("lib-osrm", "OSRM", "Карты и навигация", "https://project-osrm.org/docs/v5.24.0/api/", "openSource", "routing,osm,c-plus-plus,fast", "",
     "Very fast routing engine for OpenStreetMap data, self-hostable.",
     "Очень быстрый движок маршрутизации по данным OpenStreetMap, разворачивается самостоятельно.",
     "Preprocessing a country's data takes hours and lots of RAM, but queries then run in milliseconds."),
    ("lib-pelias", "Pelias", "Карты и навигация", "https://pelias.io/", "openSource", "geocoding,search,elasticsearch,self-host", "",
     "Open-source geocoder built on Elasticsearch, combining several open data sources.",
     "Открытый геокодер на Elasticsearch, объединяющий несколько открытых источников данных.",
     "Self-hosting removes per-request geocoding costs, which dominate at high address volumes."),

    # ---------- 3D и игровые движки ----------
    ("lib-a-frame", "A-Frame", "Анимация и 3D", "https://aframe.io/docs/", "openSource", "webxr,vr,html,declarative", "npm i aframe",
     "Declarative HTML framework for building WebXR and VR scenes.",
     "Декларативный HTML-фреймворк для создания сцен WebXR и VR.",
     "Writing a VR scene in HTML tags makes it approachable to anyone who knows the DOM."),
    ("lib-blender-python", "Blender Python API", "Анимация и 3D", "https://docs.blender.org/api/current/", "openSource", "3d,scripting,automation,rendering", "",
     "Scripting API for automating modelling, rendering and asset pipelines in Blender.",
     "API скриптования для автоматизации моделирования, рендеринга и пайплайнов ассетов в Blender.",
     "Blender runs headless, so batch rendering and asset generation work fine on a server."),
]
