# -*- coding: utf-8 -*-
"""Stage 5 library pack O: build/monorepo tooling, protocol libs, misc infra libs."""

LIBS_5O = [
    # ---------- Сборка и bundlers (deepen) ----------
    ("lib-moonrepo", "moon", "Разработка и DevOps", "https://moonrepo.dev/docs", "openSource", "monorepo,rust,tasks,caching", "",
     "Rust-based monorepo task runner with smart caching and dependency-aware execution.",
     "Монорепозиторный раннер задач на Rust с умным кэшированием и учётом зависимостей.",
     "Language-agnostic, unlike Turborepo and Nx which are strongest in the JS ecosystem."),
    ("lib-pants-build", "Pants", "Разработка и DevOps", "https://www.pantsbuild.org/docs", "openSource", "monorepo,python,build,caching", "",
     "Build system for monorepos with particularly strong Python support.",
     "Система сборки монорепозиториев с особенно сильной поддержкой Python.",
     "It infers dependencies from imports automatically, which removes most hand-written BUILD file maintenance."),
    ("lib-bazel", "Bazel", "Разработка и DevOps", "https://bazel.build/docs", "openSource", "build,hermetic,monorepo,google", "",
     "Google's hermetic build system for very large polyglot monorepos.",
     "Герметичная система сборки Google для очень больших полиглотных монорепозиториев.",
     "Its correctness guarantees cost real setup complexity — worth it at scale, overkill for a small repo."),
    ("lib-tsup", "tsup", "Сборка и bundlers", "https://tsup.egoist.dev/", "openSource", "bundler,typescript,esbuild,library", "npm i -D tsup",
     "Zero-config TypeScript library bundler built on esbuild.",
     "Бандлер TypeScript-библиотек без конфигурации на базе esbuild.",
     "Purpose-built for publishing libraries — it emits ESM, CJS and type declarations from one command."),
    ("lib-unbuild", "unbuild", "Сборка и bundlers", "https://github.com/unjs/unbuild", "openSource", "bundler,rollup,library,unjs", "npm i -D unbuild",
     "Unified build system for JavaScript libraries, from the UnJS ecosystem.",
     "Единая система сборки JavaScript-библиотек из экосистемы UnJS.",
     "Its stub mode links source directly during development, avoiding a rebuild on every change."),

    # ---------- Backend: protocols ----------
    ("lib-grpc", "gRPC", "Backend и API", "https://grpc.io/docs/", "openSource", "rpc,protobuf,streaming,cross-language", "",
     "High-performance RPC framework using Protocol Buffers over HTTP/2.",
     "Высокопроизводительный RPC-фреймворк на Protocol Buffers поверх HTTP/2.",
     "Browsers cannot speak gRPC natively — you need grpc-web or Connect for frontend clients."),
    ("lib-connectrpc", "Connect", "Backend и API", "https://connectrpc.com/docs/introduction", "openSource", "rpc,protobuf,http,browser-compatible", "npm i @connectrpc/connect",
     "RPC framework speaking both gRPC and a browser-friendly HTTP protocol from one definition.",
     "RPC-фреймворк, говорящий и по gRPC, и по дружественному браузеру HTTP из одного определения.",
     "Solves gRPC's browser problem without a separate proxy layer, which is its main reason to exist."),
    ("lib-protobuf", "Protocol Buffers", "Backend и API", "https://protobuf.dev/", "openSource", "serialization,schema,binary,google", "",
     "Language-neutral binary serialization format with schema evolution rules.",
     "Языконезависимый бинарный формат сериализации с правилами эволюции схемы.",
     "Never reuse a removed field number — that rule is what keeps old and new clients compatible."),
    ("lib-buf", "Buf", "Backend и API", "https://buf.build/docs/", "freeTier", "protobuf,linting,breaking-change,registry", "",
     "Modern Protocol Buffers tooling: linting, breaking-change detection and a schema registry.",
     "Современный тулинг Protocol Buffers: линтинг, детекция ломающих изменений и реестр схем.",
     "Its breaking-change detector in CI is what prevents an accidental incompatible schema deploy."),
    ("lib-msgpack", "MessagePack", "Backend и API", "https://msgpack.org/", "openSource", "serialization,binary,compact,schemaless", "npm i @msgpack/msgpack",
     "Compact binary serialization format, schemaless like JSON but smaller and faster.",
     "Компактный бинарный формат сериализации, без схемы как JSON, но меньше и быстрее.",
     "Good middle ground when you want JSON's flexibility without its size, and no schema registry."),
    ("lib-socket-io-2", "ws", "Backend и API", "https://github.com/websockets/ws", "openSource", "websocket,node,minimal,performance", "npm i ws",
     "Minimal, fast WebSocket implementation for Node without Socket.IO's extra protocol.",
     "Минимальная быстрая реализация WebSocket для Node без дополнительного протокола Socket.IO.",
     "Use it over Socket.IO when both ends are yours and you do not need automatic reconnect and fallbacks."),

    # ---------- Утилиты: infra libs ----------
    ("lib-caddy", "Caddy", "Облако и деплой", "https://caddyserver.com/docs/", "openSource", "web-server,https,automatic-tls,reverse-proxy", "",
     "Web server with fully automatic HTTPS certificate provisioning and renewal.",
     "Веб-сервер с полностью автоматическим получением и обновлением HTTPS-сертификатов.",
     "Automatic TLS with zero configuration is the single reason most people pick it over nginx."),
    ("lib-traefik", "Traefik", "Облако и деплой", "https://doc.traefik.io/traefik/", "openSource", "reverse-proxy,dynamic,kubernetes,docker", "",
     "Reverse proxy that discovers services dynamically from Docker and Kubernetes labels.",
     "Обратный прокси, динамически обнаруживающий сервисы по меткам Docker и Kubernetes.",
     "Routes update automatically as containers start and stop — no config reload step at all."),
    ("lib-nginx", "nginx", "Облако и деплой", "https://nginx.org/en/docs/", "openSource", "web-server,reverse-proxy,load-balancer,classic", "",
     "The long-standing high-performance web server and reverse proxy.",
     "Давно устоявшийся высокопроизводительный веб-сервер и обратный прокси.",
     "Test config with nginx -t before every reload — a syntax error takes the whole server down otherwise."),
    ("lib-envoy", "Envoy", "Service mesh и Kubernetes", "https://www.envoyproxy.io/docs/envoy/latest/", "openSource", "proxy,service-mesh,l7,observability", "",
     "L7 proxy and communication bus, the data plane inside most service meshes.",
     "L7-прокси и коммуникационная шина, data plane внутри большинства service mesh.",
     "You usually configure it through Istio or another control plane rather than writing its config directly."),
    ("lib-pgbouncer", "PgBouncer", "Базы данных и ORM", "https://www.pgbouncer.org/config.html", "openSource", "postgres,connection-pooling,performance,proxy", "",
     "Lightweight connection pooler for PostgreSQL.",
     "Лёгкий пулер соединений для PostgreSQL.",
     "Essential in front of serverless functions, which otherwise exhaust Postgres connections almost immediately."),
    ("lib-litestream", "Litestream", "Базы данных и ORM", "https://litestream.io/", "openSource", "sqlite,replication,backup,s3", "",
     "Streaming replication for SQLite to S3-compatible object storage.",
     "Потоковая репликация SQLite в S3-совместимое объектное хранилище.",
     "Makes single-server SQLite genuinely production-viable by making the data recoverable."),
]
