# -*- coding: utf-8 -*-
"""Stage 5 skills pack H: learning paths, practice platforms, engineering references, web standards."""

SKILLS_5H = [
    # ---------- Учебные маршруты ----------
    ("skill-roadmap-sh", "roadmap.sh", "Гайды и практики", "https://roadmap.sh/", "free", "learning-paths,visual,roles,community", "",
     "Visual learning roadmaps for developer roles and technologies.",
     "Визуальные учебные маршруты по ролям разработчика и технологиям.",
     "Use them to find gaps in what you know, not as a checklist to complete in order."),
    ("skill-odin-project", "The Odin Project", "Гайды и практики", "https://www.theodinproject.com/", "free", "full-stack,curriculum,projects,free", "",
     "Free full-stack curriculum built around projects rather than lectures.",
     "Бесплатная full-stack программа, построенная вокруг проектов, а не лекций.",
     "It sends you to official documentation rather than replacing it, which builds a durable habit."),
    ("skill-freecodecamp", "freeCodeCamp", "Гайды и практики", "https://www.freecodecamp.org/learn", "free", "curriculum,certifications,interactive,nonprofit", "",
     "Free interactive curriculum with project-based certifications.",
     "Бесплатная интерактивная программа с проектными сертификациями.",
     "Its certification projects are portfolio pieces, which the quizzes alone are not."),
    ("skill-awesome-lists", "Awesome Lists", "Каталоги skills", "https://github.com/sindresorhus/awesome", "free", "curated,directories,community,discovery", "",
     "Community-curated lists of tools and resources for almost every topic.",
     "Курируемые сообществом списки инструментов и ресурсов почти по любой теме.",
     "Check the last commit date — many lists are years stale and quietly recommend dead projects."),

    # ---------- Практика ----------
    ("skill-exercism", "Exercism", "Гайды и практики", "https://exercism.org/", "free", "practice,mentoring,languages,free", "",
     "Practice exercises across many languages with volunteer mentoring.",
     "Практические упражнения на множестве языков с наставничеством волонтёров.",
     "Human code review on your solutions is what separates it from other exercise sites."),
    ("skill-leetcode", "LeetCode", "Гайды и практики", "https://leetcode.com/", "freeTier", "algorithms,interviews,practice,contests", "",
     "Algorithm practice problems widely used for interview preparation.",
     "Задачи по алгоритмам, широко используемые для подготовки к собеседованиям.",
     "Study patterns rather than grinding problem count — the patterns are what transfer."),
    ("skill-codewars", "Codewars", "Гайды и практики", "https://www.codewars.com/", "freeTier", "kata,practice,community,ranks", "",
     "Coding practice through community-authored challenges called kata.",
     "Практика программирования через задачи от сообщества, называемые ката.",
     "Reading other solutions after solving is where most of the learning actually happens."),
    ("skill-advent-of-code", "Advent of Code", "Гайды и практики", "https://adventofcode.com/", "free", "puzzles,annual,december,community", "",
     "Annual programming puzzle calendar running through December.",
     "Ежегодный календарь программистских головоломок на протяжении декабря.",
     "A good excuse to try an unfamiliar language on problems small enough to finish."),
    ("skill-project-euler", "Project Euler", "Гайды и практики", "https://projecteuler.net/", "free", "mathematics,algorithms,puzzles,archive", "",
     "Mathematical and computational problems requiring efficient solutions.",
     "Математические и вычислительные задачи, требующие эффективных решений.",
     "Brute force stops working after the first few, which is precisely the lesson."),

    # ---------- Инженерные справочники ----------
    ("skill-system-design-primer", "System Design Primer", "Гайды и практики", "https://github.com/donnemartin/system-design-primer", "free", "system-design,interviews,scalability,reference", "",
     "Open reference on designing large-scale systems.",
     "Открытый справочник по проектированию крупномасштабных систем.",
     "Its trade-off discussions are more useful than the diagrams — the reasoning is the content."),
    ("skill-ddia", "Designing Data-Intensive Applications", "Гайды и практики", "https://dataintensive.net/", "paid", "distributed-systems,databases,foundational,book", "",
     "The reference book on data systems, consistency and distributed storage.",
     "Справочная книга по системам данных, согласованности и распределённому хранению.",
     "Its chapter on replication and consistency explains failures you will otherwise debug blind."),
    ("skill-refactoring-guru", "Refactoring Guru", "Гайды и практики", "https://refactoring.guru/", "freeTier", "design-patterns,refactoring,examples,illustrated", "",
     "Illustrated guide to design patterns and refactoring techniques.",
     "Иллюстрированное руководство по паттернам проектирования и техникам рефакторинга.",
     "Its code smell catalogue is the more practical half — patterns are easy to over-apply."),
    ("skill-patterns-dev", "Patterns.dev", "Гайды и практики", "https://www.patterns.dev/", "free", "web,patterns,performance,rendering", "",
     "Modern web design, rendering and performance patterns.",
     "Современные паттерны проектирования, рендеринга и производительности в вебе.",
     "Its rendering patterns section explains the tradeoffs behind every framework's defaults."),
    ("skill-google-eng-practices", "Google Engineering Practices", "Гайды и практики", "https://google.github.io/eng-practices/", "free", "code-review,standards,culture,guidelines", "",
     "Google's published guidance on code review standards.",
     "Опубликованные рекомендации Google по стандартам code review.",
     "Its 'approve when it improves the codebase' rule resolves most review deadlocks."),
    ("skill-google-sre-book", "Google SRE Book", "Гайды и практики", "https://sre.google/books/", "free", "sre,reliability,slo,operations", "",
     "Google's freely readable books on site reliability engineering.",
     "Свободно доступные книги Google по site reliability engineering.",
     "The error budget chapter is the one that changes how teams argue about reliability."),
    ("skill-twelve-factor", "The Twelve-Factor App", "Гайды и практики", "https://12factor.net/", "free", "methodology,saas,deployment,configuration", "",
     "Methodology for building portable, deployable software services.",
     "Методология создания переносимых и легко развёртываемых сервисов.",
     "Its configuration-in-environment rule is why containerized deployment works as smoothly as it does."),

    # ---------- Конвенции проектов ----------
    ("skill-conventional-commits", "Conventional Commits", "Git и совместная работа", "https://www.conventionalcommits.org/", "free", "commits,convention,automation,changelog", "",
     "Commit message convention that machines can parse.",
     "Соглашение о сообщениях коммитов, разбираемое машинами.",
     "Adopting it unlocks automated versioning and changelogs, which is the actual payoff."),
    ("skill-semver", "Semantic Versioning", "Git и совместная работа", "https://semver.org/", "free", "versioning,specification,compatibility,standard", "",
     "The version numbering specification communicating compatibility.",
     "Спецификация нумерации версий, сообщающая о совместимости.",
     "A breaking change in a minor release breaks the contract other tooling relies on."),
    ("skill-keep-a-changelog", "Keep a Changelog", "Git и совместная работа", "https://keepachangelog.com/", "free", "changelog,convention,human-readable,releases", "",
     "Convention for writing changelogs people can actually read.",
     "Соглашение о написании changelog, которые люди действительно читают.",
     "A dumped commit log is not a changelog — the distinction is what the convention exists for."),
    ("skill-contributor-covenant", "Contributor Covenant", "Git и совместная работа", "https://www.contributor-covenant.org/", "free", "code-of-conduct,community,open-source,standard", "",
     "The widely adopted code of conduct for open-source projects.",
     "Широко принятый кодекс поведения для open-source проектов.",
     "Adopting it means little without naming who enforces it and how reports are handled."),
    ("skill-choose-a-license", "Choose a License", "Гайды и практики", "https://choosealicense.com/", "free", "licensing,open-source,comparison,github", "",
     "Plain-language guide to choosing an open-source licence.",
     "Понятное руководство по выбору open-source лицензии.",
     "A repository with no licence is not open source — default copyright reserves all rights."),
    ("skill-spdx", "SPDX", "Безопасность и секреты", "https://spdx.dev/", "free", "licensing,sbom,identifiers,standard", "",
     "Standard for communicating licence and software bill of materials data.",
     "Стандарт передачи данных о лицензиях и software bill of materials.",
     "Its licence identifiers are what let automated tooling reason about compliance at all."),
    ("skill-reuse-software", "REUSE", "Безопасность и секреты", "https://reuse.software/", "free", "licensing,compliance,automation,fsfe", "",
     "Specification for making licence information machine-readable per file.",
     "Спецификация машиночитаемой информации о лицензии для каждого файла.",
     "Per-file licence headers resolve the ambiguity a single root LICENSE file leaves."),

    # ---------- Спецификации ----------
    ("skill-openapi-spec", "OpenAPI Specification", "Документация и контекст", "https://spec.openapis.org/", "free", "api,specification,rest,standard", "",
     "The standard specification for describing REST APIs.",
     "Стандартная спецификация описания REST API.",
     "Writing the spec before the implementation catches interface problems while they are still cheap."),
    ("skill-json-schema", "JSON Schema", "Утилиты", "https://json-schema.org/", "free", "validation,specification,structure,standard", "",
     "Vocabulary for validating and documenting JSON data structures.",
     "Словарь для валидации и документирования структур данных JSON.",
     "One schema drives validation, documentation and code generation at once."),
    ("skill-asyncapi", "AsyncAPI", "Документация и контекст", "https://www.asyncapi.com/docs", "free", "event-driven,specification,messaging,kafka", "",
     "Specification for documenting event-driven and message-based APIs.",
     "Спецификация документирования событийных и основанных на сообщениях API.",
     "It fills the gap OpenAPI leaves, since REST specs cannot describe a Kafka topic."),
    ("skill-graphql-spec", "GraphQL Specification", "Документация и контекст", "https://spec.graphql.org/", "free", "graphql,specification,reference,standard", "",
     "The formal GraphQL language and execution specification.",
     "Формальная спецификация языка и исполнения GraphQL.",
     "Reading the execution section explains why resolver performance behaves as it does."),
    ("skill-rfc-editor", "RFC Editor", "Документация и контекст", "https://www.rfc-editor.org/", "free", "internet-standards,protocols,ietf,reference", "",
     "The archive of internet standards and protocol specifications.",
     "Архив интернет-стандартов и спецификаций протоколов.",
     "When documentation and implementation disagree about a protocol, the RFC settles it."),
    ("skill-w3c-specs", "W3C Specifications", "Документация и контекст", "https://www.w3.org/TR/", "free", "web-standards,html,css,reference", "",
     "The technical reports and standards defining the web platform.",
     "Технические отчёты и стандарты, определяющие веб-платформу.",
     "Specs describe intended behaviour; browsers describe actual behaviour — you often need both."),

    # ---------- Веб-платформа ----------
    ("skill-mdn", "MDN Web Docs", "Документация и контекст", "https://developer.mozilla.org/", "free", "reference,web,browser,compatibility", "",
     "The reference documentation for web platform technologies.",
     "Справочная документация по технологиям веб-платформы.",
     "Its per-feature browser compatibility tables answer most 'can I use this' questions inline."),
    ("skill-web-dev", "web.dev", "Гайды и практики", "https://web.dev/", "free", "google,performance,best-practices,core-web-vitals", "",
     "Google's guidance on web performance and modern best practices.",
     "Рекомендации Google по производительности веба и современным лучшим практикам.",
     "Its Core Web Vitals guidance maps directly to what search ranking actually measures."),
    ("skill-caniuse", "Can I Use", "Документация и контекст", "https://caniuse.com/", "free", "compatibility,browsers,support-tables,reference", "",
     "Browser support tables for web platform features.",
     "Таблицы поддержки браузерами возможностей веб-платформы.",
     "Import your own analytics to see support weighted by your actual audience, not global share."),
    ("skill-baseline", "Baseline", "Документация и контекст", "https://web.dev/baseline", "free", "compatibility,web-features,interoperable,standard", "",
     "Signals which web features are safely usable across major browsers.",
     "Показывает, какие возможности веба безопасно использовать во всех основных браузерах.",
     "It replaces per-feature support research with one interoperability signal."),
    ("skill-web-almanac", "Web Almanac", "Гайды и практики", "https://almanac.httparchive.org/", "free", "research,statistics,http-archive,annual", "",
     "Annual report on the state of the web, built from real crawl data.",
     "Ежегодный отчёт о состоянии веба на основе реальных данных обхода сайтов.",
     "Its data settles arguments about what techniques are actually used in production."),
    ("skill-state-of-js", "State of JS", "Гайды и практики", "https://stateofjs.com/", "free", "survey,ecosystem,trends,annual", "",
     "Annual survey of JavaScript ecosystem usage and satisfaction.",
     "Ежегодный опрос об использовании и удовлетворённости в экосистеме JavaScript.",
     "Its retention metric predicts a tool's trajectory better than raw usage numbers."),
    ("skill-stackoverflow-survey", "Stack Overflow Developer Survey", "Гайды и практики", "https://survey.stackoverflow.co/", "free", "survey,industry,salaries,trends", "",
     "Annual survey of developer tools, salaries and working practices.",
     "Ежегодный опрос об инструментах разработчиков, зарплатах и практиках работы.",
     "Its salary data by technology and region is the most cited part for good reason."),

    # ---------- Доступность ----------
    ("skill-wcag", "WCAG", "Доступность (a11y)", "https://www.w3.org/WAI/standards-guidelines/wcag/", "free", "accessibility,standard,compliance,guidelines", "",
     "The web accessibility guidelines most legal requirements reference.",
     "Руководство по доступности веба, на которое ссылается большинство законодательных требований.",
     "Level AA is the compliance target in most jurisdictions, not level AAA."),
    ("skill-aria-practices", "ARIA Authoring Practices", "Доступность (a11y)", "https://www.w3.org/WAI/ARIA/apg/", "free", "aria,patterns,keyboard,components", "",
     "Reference patterns for building accessible interface components.",
     "Эталонные паттерны создания доступных компонентов интерфейса.",
     "Its keyboard interaction specifications are what most custom components get wrong."),
    ("skill-inclusive-components", "Inclusive Components", "Доступность (a11y)", "https://inclusive-components.design/", "free", "accessibility,components,patterns,practical", "",
     "Practical guide to building accessible interface components.",
     "Практическое руководство по созданию доступных компонентов интерфейса.",
     "It reasons from first principles rather than reciting rules, which transfers to new components."),
    ("skill-a11y-project", "The A11Y Project", "Доступность (a11y)", "https://www.a11yproject.com/", "free", "accessibility,checklist,community,resources", "",
     "Community-driven accessibility resources and a practical checklist.",
     "Ресурсы по доступности от сообщества и практический чек-лист.",
     "Its checklist is short enough to actually work through before a release."),
]
