# -*- coding: utf-8 -*-
"""Stage 5 library pack AB: dataframe engines, query languages, lakehouse formats, sync databases."""

LIBS_5AB = [
    # ---------- Датафреймы и вычисления ----------
    ("lib-daft", "Daft", "Data engineering", "https://docs.daft.ai/", "openSource", "dataframe,distributed,multimodal,rust", "pip install daft",
     "Distributed dataframe engine handling multimodal data such as images and embeddings.",
     "Распределённый движок датафреймов, работающий с мультимодальными данными вроде изображений и эмбеддингов.",
     "Treating images and tensors as ordinary columns is what separates it from tabular-only engines."),
    ("lib-vaex", "Vaex", "Data engineering", "https://vaex.io/docs/", "openSource", "dataframe,out-of-core,lazy,memory-mapped", "pip install vaex",
     "Out-of-core dataframes processing datasets larger than memory via memory mapping.",
     "Датафреймы out-of-core: обрабатывают наборы данных больше объёма памяти через отображение в память.",
     "Memory mapping means opening a 100 GB file is instant — only the columns you touch are read."),
    ("lib-modin", "Modin", "Data engineering", "https://modin.readthedocs.io/", "openSource", "pandas,parallel,drop-in,scaling", "pip install modin",
     "Parallelizes pandas by changing a single import line.",
     "Распараллеливает pandas изменением одной строки импорта.",
     "A genuine drop-in for existing pandas code, though coverage of rarer methods is incomplete."),
    ("lib-cudf", "cuDF", "Data engineering", "https://docs.rapids.ai/api/cudf/stable/", "openSource", "gpu,pandas,rapids,nvidia", "",
     "GPU dataframe library with a pandas-compatible API, part of NVIDIA RAPIDS.",
     "GPU-библиотека датафреймов с pandas-совместимым API, часть NVIDIA RAPIDS.",
     "Its pandas accelerator mode falls back to CPU automatically for unsupported operations."),
    ("lib-dask", "Dask", "Data engineering", "https://docs.dask.org/", "openSource", "parallel,python,scaling,scheduler", "pip install dask",
     "Parallel computing for Python, scaling NumPy, pandas and scikit-learn workloads.",
     "Параллельные вычисления для Python, масштабирующие задачи NumPy, pandas и scikit-learn.",
     "Its familiar APIs ease adoption, but a single-machine Polars job often beats a small Dask cluster."),
    ("lib-narwhals", "Narwhals", "Data engineering", "https://narwhals-dev.github.io/narwhals/", "openSource", "compatibility,dataframe,library-authors,zero-dependency", "pip install narwhals",
     "Compatibility layer letting a library support pandas, Polars and others from one code path.",
     "Слой совместимости, позволяющий библиотеке поддерживать pandas, Polars и другие через один код.",
     "Aimed at library authors — it removes the 'which dataframe do you support' question entirely."),

    # ---------- Языки запросов ----------
    ("lib-sqlparse", "sqlparse", "Базы данных и ORM", "https://sqlparse.readthedocs.io/", "openSource", "sql,parsing,formatting,python", "pip install sqlparse",
     "Non-validating SQL parser and formatter for Python.",
     "Невалидирующий парсер и форматтер SQL для Python.",
     "Fine for splitting and prettifying statements; use SQLGlot when you need real dialect awareness."),
    ("lib-malloy", "Malloy", "Data engineering", "https://docs.malloydata.dev/documentation/", "openSource", "query-language,semantic,analytics,composable", "",
     "Experimental analytical language expressing nested, reusable data models.",
     "Экспериментальный аналитический язык для вложенных переиспользуемых моделей данных.",
     "Nested query results avoid the join-and-flatten dance that SQL forces on hierarchical questions."),
    ("lib-prql", "PRQL", "Data engineering", "https://prql-lang.org/book/", "openSource", "query-language,pipeline,compiles-to-sql,readable", "",
     "Pipelined relational query language that compiles to SQL.",
     "Конвейерный реляционный язык запросов, компилируемый в SQL.",
     "Reads top-to-bottom in execution order, which makes long analytical chains far easier to follow."),

    # ---------- Форматы озёр данных ----------
    ("lib-apache-iceberg", "Apache Iceberg", "Data engineering", "https://iceberg.apache.org/docs/latest/", "openSource", "table-format,acid,time-travel,lakehouse", "",
     "Open table format bringing ACID transactions and schema evolution to data lakes.",
     "Открытый табличный формат, приносящий ACID-транзакции и эволюцию схемы в озёра данных.",
     "Hidden partitioning means queries stay correct when you change the partition scheme later."),
    ("lib-delta-lake", "Delta Lake", "Data engineering", "https://docs.delta.io/latest/index.html", "openSource", "table-format,acid,databricks,time-travel", "pip install deltalake",
     "Transactional storage layer over object storage, originating at Databricks.",
     "Транзакционный слой хранения поверх объектного хранилища, созданный в Databricks.",
     "Time travel makes 'what did this table look like last Tuesday' a query rather than a restore."),
    ("lib-apache-hudi", "Apache Hudi", "Data engineering", "https://hudi.apache.org/docs/overview", "openSource", "table-format,upserts,incremental,cdc", "",
     "Lakehouse format specialising in upserts and incremental data processing.",
     "Формат lakehouse, специализирующийся на upsert и инкрементальной обработке данных.",
     "Its incremental pull model suits CDC ingestion better than full-snapshot table formats."),
    ("lib-apache-paimon", "Apache Paimon", "Data engineering", "https://paimon.apache.org/docs/master/", "openSource", "table-format,streaming,flink,lakehouse", "",
     "Streaming-first lakehouse format designed to work closely with Apache Flink.",
     "Формат lakehouse с приоритетом потоковой обработки, тесно работающий с Apache Flink.",
     "Built for streaming updates first, where Iceberg and Delta started from batch workloads."),

    # ---------- Аналитические движки ----------
    ("lib-trino", "Trino", "Data engineering", "https://trino.io/docs/current/", "openSource", "sql,federated,query-engine,connectors", "",
     "Distributed SQL engine querying across many data sources without moving the data.",
     "Распределённый SQL-движок, выполняющий запросы по множеству источников без перемещения данных.",
     "Joining a warehouse table to a Kafka topic in one query is the capability people adopt it for."),
    ("lib-presto", "Presto", "Data engineering", "https://prestodb.io/docs/current/", "openSource", "sql,distributed,facebook,federated", "",
     "Distributed SQL query engine, the project Trino forked from.",
     "Распределённый движок SQL-запросов, из которого был форкнут Trino.",
     "Trino carries most of the active development — check both before starting something new."),
    ("lib-apache-drill", "Apache Drill", "Data engineering", "https://drill.apache.org/docs/", "openSource", "sql,schema-free,files,json", "",
     "Schema-free SQL engine querying files and NoSQL stores without predefined schemas.",
     "SQL-движок без схемы, запрашивающий файлы и NoSQL-хранилища без предварительных определений.",
     "Querying a directory of JSON files directly is useful for exploration before any modelling."),
    ("lib-starrocks", "StarRocks", "Data engineering", "https://docs.starrocks.io/", "openSource", "olap,mysql-protocol,real-time,joins", "",
     "High-performance OLAP database with strong multi-table join performance.",
     "Высокопроизводительная OLAP-база с сильной производительностью многотабличных join.",
     "Fast joins let you keep a normalized model, where many OLAP stores force wide denormalized tables."),
    ("lib-apache-doris", "Apache Doris", "Data engineering", "https://doris.apache.org/docs/gettingStarted/what-is-apache-doris", "openSource", "olap,mpp,real-time,mysql-compatible", "",
     "MPP analytical database with MySQL protocol compatibility.",
     "MPP-аналитическая база данных с совместимостью по протоколу MySQL.",
     "MySQL wire compatibility means existing BI tools connect with no new driver."),
    ("lib-apache-pinot", "Apache Pinot", "Data engineering", "https://docs.pinot.apache.org/", "openSource", "olap,real-time,low-latency,user-facing", "",
     "Real-time OLAP store built for user-facing analytics at very low latency.",
     "OLAP-хранилище реального времени для пользовательской аналитики с очень низкой задержкой.",
     "Designed for analytics shown to end users, where a two-second dashboard query is already too slow."),
    ("lib-apache-druid", "Apache Druid", "Data engineering", "https://druid.apache.org/docs/latest/design/", "openSource", "olap,time-series,real-time,ingestion", "",
     "Real-time analytics database for event and time-series data at scale.",
     "База аналитики реального времени для событийных и временных данных большого объёма.",
     "Operationally heavy — several node types to run, which is the main cost of its ingestion speed."),
    ("lib-greptimedb", "GreptimeDB", "Data engineering", "https://docs.greptime.com/", "openSource", "time-series,metrics,logs,rust", "",
     "Unified time-series database for metrics, logs and events, written in Rust.",
     "Единая база временных рядов для метрик, логов и событий, написанная на Rust.",
     "Handling metrics and logs in one engine removes a whole second system from an observability stack."),

    # ---------- Распределённые и serverless базы ----------
    ("lib-yugabytedb", "YugabyteDB", "Базы данных и ORM", "https://docs.yugabyte.com/", "openSource", "distributed,postgres-compatible,ha,sql", "",
     "Distributed SQL database with PostgreSQL wire compatibility.",
     "Распределённая SQL-база с совместимостью по протоколу PostgreSQL.",
     "Reuses the actual PostgreSQL query layer, so extension and syntax support is unusually complete."),
    ("lib-tidb", "TiDB", "Базы данных и ORM", "https://docs.pingcap.com/tidb/stable/", "openSource", "distributed,mysql-compatible,htap,scaling", "",
     "Distributed MySQL-compatible database supporting both transactional and analytical queries.",
     "Распределённая MySQL-совместимая база, поддерживающая транзакционные и аналитические запросы.",
     "Its HTAP design runs analytics on a columnar replica without touching transactional performance."),
    ("lib-edgedb-gel", "Gel (EdgeDB)", "Базы данных и ORM", "https://docs.geldata.com/", "openSource", "graph-relational,typed,query-language,postgres", "",
     "Graph-relational database on Postgres with its own strongly typed query language.",
     "Графово-реляционная база на Postgres с собственным строго типизированным языком запросов.",
     "Its query language returns nested object shapes directly, removing most ORM mapping code."),
    ("lib-pglite", "PGlite", "Базы данных и ORM", "https://pglite.dev/docs/", "openSource", "postgres,wasm,browser,embedded", "npm i @electric-sql/pglite",
     "Full Postgres compiled to WebAssembly, running in the browser or Node.",
     "Полноценный Postgres, скомпилированный в WebAssembly, работает в браузере или Node.",
     "Real Postgres in a test process starts in milliseconds and needs no Docker container."),

    # ---------- Локальная синхронизация данных ----------
    ("lib-electric-sql", "Electric SQL", "Состояние и данные", "https://electric-sql.com/docs/intro", "openSource", "sync,postgres,local-first,partial-replication", "",
     "Syncs subsets of a Postgres database into local clients for local-first apps.",
     "Синхронизирует подмножества базы Postgres в локальные клиенты для local-first приложений.",
     "Partial replication is the hard part it solves — syncing a whole database to a client never scales."),
    ("lib-powersync", "PowerSync", "Состояние и данные", "https://docs.powersync.com/", "mixed", "sync,offline-first,sqlite,postgres", "",
     "Offline-first sync between server databases and on-device SQLite.",
     "Offline-first синхронизация между серверными базами и локальным SQLite на устройстве.",
     "Its sync rules define per-user data scope declaratively rather than in hand-written sync code."),
    ("lib-zero-sync", "Zero", "Состояние и данные", "https://zero.rocicorp.dev/docs/introduction", "openSource", "sync,queries,local-first,realtime", "",
     "Sync engine running queries locally against a synced subset of server data.",
     "Движок синхронизации, выполняющий запросы локально по синхронизированному подмножеству серверных данных.",
     "Queries resolve instantly from the local cache and reconcile in the background, hiding network latency."),
    ("lib-rxdb", "RxDB", "Состояние и данные", "https://rxdb.info/quickstart.html", "mixed", "offline-first,reactive,replication,nosql", "npm i rxdb",
     "Reactive offline-first NoSQL database for JavaScript with pluggable replication.",
     "Реактивная offline-first NoSQL база для JavaScript с подключаемой репликацией.",
     "Queries are observables, so the UI updates on replicated changes without any manual refresh."),
    ("lib-tinybase", "TinyBase", "Состояние и данные", "https://tinybase.org/guides/the-basics/", "openSource", "local-first,reactive,tiny,structured", "npm i tinybase",
     "Small reactive data store for local-first apps, with optional persistence and sync.",
     "Небольшое реактивное хранилище данных для local-first приложений с опциональной персистентностью и синхронизацией.",
     "A few kilobytes, which makes it viable where a full local database would dominate the bundle."),
]
