# -*- coding: utf-8 -*-
"""Stage 5 library pack AS: documentation sites, static generators, slides, diagrams, code rendering."""

LIBS_5AS = [
    # ---------- Документация ----------
    ("lib-nextra", "Nextra", "Документация и контекст", "https://nextra.site/docs", "openSource", "nextjs,mdx,docs,themes", "npm i nextra",
     "Next.js documentation framework driven by MDX files.",
     "Фреймворк документации на Next.js, работающий на MDX-файлах.",
     "React components inside documentation pages let you embed live examples rather than screenshots."),
    ("lib-starlight", "Starlight", "Документация и контекст", "https://starlight.astro.build/", "openSource", "astro,docs,fast,accessible", "npm create astro@latest -- --template starlight",
     "Astro's documentation theme, fast and accessible by default.",
     "Тема документации для Astro, быстрая и доступная по умолчанию.",
     "Ships with search, dark mode and internationalization configured, which is most of the setup work."),
    ("lib-material-mkdocs", "Material for MkDocs", "Документация и контекст", "https://squidfunk.github.io/mkdocs-material/", "mixed", "mkdocs,theme,search,python", "pip install mkdocs-material",
     "The dominant MkDocs theme, with search, tabs and annotations.",
     "Доминирующая тема для MkDocs с поиском, вкладками и аннотациями.",
     "Some features sit behind sponsorship, which is worth knowing before designing around them."),
    ("lib-readthedocs", "Read the Docs", "Документация и контекст", "https://docs.readthedocs.com/", "freeTier", "hosting,versioning,sphinx,free-for-oss", "",
     "Documentation hosting with automatic versioning and pull request previews.",
     "Хостинг документации с автоматическим версионированием и превью для pull request.",
     "Free for open-source projects, and its per-version docs match what library users actually need."),
    ("lib-gitbook", "GitBook", "Документация и контекст", "https://gitbook.com/docs", "freeTier", "docs,collaboration,git-sync,editor", "",
     "Documentation platform with a visual editor and Git synchronization.",
     "Платформа документации с визуальным редактором и синхронизацией через Git.",
     "Non-engineers edit in the browser while the content still lands in your repository."),
    ("lib-docsify", "Docsify", "Документация и контекст", "https://docsify.js.org/", "openSource", "markdown,no-build,runtime,lightweight", "npm i -g docsify-cli",
     "Renders Markdown documentation at runtime with no build step.",
     "Отрисовывает документацию Markdown во время выполнения, без этапа сборки.",
     "No build means no pipeline, at the cost of client-side rendering that search engines index poorly."),
    ("lib-antora", "Antora", "Документация и контекст", "https://docs.antora.org/", "openSource", "asciidoc,multi-repo,versioning,modular", "npm i -g @antora/cli",
     "Documentation site generator assembling content from many repositories.",
     "Генератор сайтов документации, собирающий контент из множества репозиториев.",
     "Multi-repository aggregation is its distinguishing feature, which suits large product suites."),

    # ---------- Статические генераторы ----------
    ("lib-jekyll", "Jekyll", "Документация и контекст", "https://jekyllrb.com/docs/", "openSource", "ruby,static,github-pages,blogging", "gem install jekyll",
     "Ruby static site generator with native GitHub Pages support.",
     "Генератор статических сайтов на Ruby с нативной поддержкой GitHub Pages.",
     "GitHub Pages builds it server-side, so a repository alone is enough to publish a site."),
    ("lib-zola", "Zola", "Документация и контекст", "https://www.getzola.org/documentation/", "openSource", "rust,static,single-binary,fast", "",
     "Fast static site generator shipped as a single Rust binary.",
     "Быстрый генератор статических сайтов в виде одного бинарника на Rust.",
     "No Node or Ruby toolchain to install, which makes CI configuration trivially simple."),
    ("lib-pelican", "Pelican", "Документация и контекст", "https://docs.getpelican.com/", "openSource", "python,static,blogging,restructuredtext", "pip install pelican",
     "Python static site generator supporting Markdown and reStructuredText.",
     "Генератор статических сайтов на Python с поддержкой Markdown и reStructuredText.",
     "A natural fit for a Python team that would rather not add a JavaScript toolchain."),
    ("lib-gatsby", "Gatsby", "UI и frontend", "https://www.gatsbyjs.com/docs/", "openSource", "react,graphql,static,plugins", "npm i -g gatsby-cli",
     "React static site generator with a GraphQL data layer.",
     "Генератор статических сайтов на React с GraphQL-слоем данных.",
     "Development has slowed considerably since Netlify acquired it — check activity before starting."),
    ("lib-nuxt-content", "Nuxt Content", "CMS и контент", "https://content.nuxt.com/docs", "openSource", "nuxt,markdown,file-based,queries", "npm i @nuxt/content",
     "File-based content system for Nuxt with a query API over Markdown.",
     "Файловая система контента для Nuxt с API запросов к Markdown.",
     "Querying Markdown files like a database avoids standing up a CMS for a content site."),

    # ---------- Презентации ----------
    ("lib-slidev", "Slidev", "Документация и контекст", "https://sli.dev/guide/", "openSource", "markdown,presentations,vue,developer", "npm i -g @slidev/cli",
     "Presentation slides written in Markdown, aimed at developers.",
     "Слайды презентаций на Markdown для разработчиков.",
     "Live code execution and diagrams in slides make technical talks far easier to keep accurate."),
    ("lib-revealjs", "reveal.js", "Документация и контекст", "https://revealjs.com/", "openSource", "html,presentations,web,framework", "npm i reveal.js",
     "HTML presentation framework with nested slides and transitions.",
     "HTML-фреймворк презентаций с вложенными слайдами и переходами.",
     "Slides are a web page, so anything embeddable in a browser can go on a slide."),
    ("lib-marp", "Marp", "Документация и контекст", "https://marp.app/", "openSource", "markdown,slides,export,cli", "npm i -g @marp-team/marp-cli",
     "Markdown presentation ecosystem with PDF and HTML export.",
     "Экосистема презентаций на Markdown с экспортом в PDF и HTML.",
     "Its CLI renders slides in CI, so a deck can be built from a repository automatically."),

    # ---------- Диаграммы ----------
    ("lib-excalidraw", "Excalidraw", "Изображения и дизайн", "https://docs.excalidraw.com/", "openSource", "whiteboard,hand-drawn,collaborative,embeddable", "npm i @excalidraw/excalidraw",
     "Virtual whiteboard with a hand-drawn look, embeddable as a component.",
     "Виртуальная доска с рисунком от руки, встраиваемая как компонент.",
     "The sketchy style signals a draft, which invites feedback that a polished diagram discourages."),
    ("lib-tldraw", "tldraw", "Изображения и дизайн", "https://tldraw.dev/", "mixed", "canvas,sdk,collaborative,react", "npm i tldraw",
     "Infinite canvas SDK for building drawing and diagramming features.",
     "SDK бесконечного холста для создания функций рисования и построения диаграмм.",
     "Free for non-commercial use; a licence is required to ship it in a commercial product."),
    ("lib-mermaid", "Mermaid", "Документация и контекст", "https://mermaid.js.org/intro/", "openSource", "diagrams,text,markdown,flowcharts", "npm i mermaid",
     "Generates diagrams from text, rendered natively by GitHub and many docs tools.",
     "Генерирует диаграммы из текста, отрисовывается нативно в GitHub и многих инструментах документации.",
     "Diagrams live in the same file as the prose, so they get reviewed and updated with it."),
    ("lib-plantuml", "PlantUML", "Документация и контекст", "https://plantuml.com/", "openSource", "uml,diagrams,text,java", "",
     "Text-based UML and architecture diagram generator.",
     "Генератор UML и архитектурных диаграмм из текста.",
     "Covers formal UML diagram types that lighter text-to-diagram tools do not attempt."),
    ("lib-d2", "D2", "Документация и контекст", "https://d2lang.com/", "openSource", "diagrams,declarative,layout,go", "",
     "Modern declarative diagram language with automatic layout.",
     "Современный декларативный язык диаграмм с автоматической раскладкой.",
     "Its layout engines produce noticeably cleaner results than Mermaid on dense diagrams."),
    ("lib-graphviz", "Graphviz", "Документация и контекст", "https://graphviz.org/documentation/", "openSource", "graphs,dot,layout,foundational", "",
     "The foundational graph layout toolkit, driven by the DOT language.",
     "Фундаментальный набор инструментов раскладки графов на языке DOT.",
     "Many diagram tools use its layout engines underneath, so learning DOT transfers widely."),
    ("lib-structurizr", "Structurizr", "Документация и контекст", "https://docs.structurizr.com/", "mixed", "c4-model,architecture,diagrams-as-code,views", "",
     "Architecture diagrams as code, built around the C4 model.",
     "Архитектурные диаграммы как код на основе модели C4.",
     "One model generates every zoom level, so the context and container views can never disagree."),
    ("lib-drawio", "draw.io", "Изображения и дизайн", "https://www.drawio.com/doc/", "openSource", "diagrams,editor,offline,integrations", "",
     "Free diagramming editor that works offline and embeds in other tools.",
     "Бесплатный редактор диаграмм, работающий офлайн и встраиваемый в другие инструменты.",
     "Its files are XML, so diagrams can be diffed in version control, if awkwardly."),
    ("lib-kroki", "Kroki", "Документация и контекст", "https://kroki.io/", "openSource", "diagrams,api,unified,self-host", "",
     "Unified HTTP API rendering diagrams from many text formats.",
     "Единый HTTP API, отрисовывающий диаграммы из множества текстовых форматов.",
     "One endpoint covers Mermaid, PlantUML, D2 and others, so docs tooling needs a single integration."),

    # ---------- Код в документации ----------
    ("lib-asciinema", "asciinema", "Документация и контекст", "https://docs.asciinema.org/", "openSource", "terminal,recording,text-based,embeddable", "",
     "Records terminal sessions as text rather than video.",
     "Записывает сессии терминала как текст, а не как видео.",
     "Viewers can select and copy the commands, which a screen recording never allows."),
    ("lib-vhs", "VHS", "Документация и контекст", "https://github.com/charmbracelet/vhs", "openSource", "terminal,gif,scripted,reproducible", "",
     "Generates terminal GIFs from a script, reproducibly.",
     "Генерирует GIF терминала из скрипта, воспроизводимо.",
     "Scripted recordings regenerate when the CLI changes, so demo GIFs never go stale."),
    ("lib-carbon-sh", "Carbon", "Изображения и дизайн", "https://carbon.now.sh/", "openSource", "code-images,sharing,themes,screenshots", "",
     "Creates shareable images of source code.",
     "Создаёт изображения исходного кода для публикации.",
     "Good for social posts, though a real code block is better anywhere text is selectable."),
    ("lib-ray-so", "ray.so", "Изображения и дизайн", "https://ray.so/", "free", "code-images,raycast,themes,fast", "",
     "Fast code image generator from the Raycast team.",
     "Быстрый генератор изображений кода от команды Raycast.",
     "Its presets produce a clean result without the tweaking Carbon tends to invite."),
    ("lib-shiki", "Shiki", "UI и frontend", "https://shiki.style/", "openSource", "syntax-highlighting,textmate,accurate,build-time", "npm i shiki",
     "Syntax highlighter using the same grammars as VS Code.",
     "Подсветка синтаксиса на тех же грамматиках, что и в VS Code.",
     "Highlighting at build time ships zero JavaScript, unlike client-side highlighters."),
    ("lib-prismjs", "Prism.js", "UI и frontend", "https://prismjs.com/", "openSource", "syntax-highlighting,lightweight,plugins,browser", "npm i prismjs",
     "Lightweight client-side syntax highlighter with a plugin system.",
     "Лёгкая клиентская подсветка синтаксиса с системой плагинов.",
     "Load only the languages you use — the full bundle is far larger than most pages need."),
    ("lib-highlightjs", "highlight.js", "UI и frontend", "https://highlightjs.org/", "openSource", "syntax-highlighting,auto-detect,browser,node", "npm i highlight.js",
     "Syntax highlighter with automatic language detection.",
     "Подсветка синтаксиса с автоматическим определением языка.",
     "Auto-detection is convenient and unreliable — specify the language when you know it."),
    ("lib-monaco-editor", "Monaco Editor", "UI и frontend", "https://microsoft.github.io/monaco-editor/", "openSource", "vscode,editor,intellisense,typescript", "npm i monaco-editor",
     "The editor that powers VS Code, embeddable in a web page.",
     "Редактор, лежащий в основе VS Code, встраиваемый в веб-страницу.",
     "Its IntelliSense is unmatched, at a bundle size that only suits a genuine code-editing surface."),
    ("lib-sandpack", "Sandpack", "UI и frontend", "https://sandpack.codesandbox.io/docs", "openSource", "live-code,bundler,react,embeddable", "npm i @codesandbox/sandpack-react",
     "Embeddable live coding environment from CodeSandbox.",
     "Встраиваемая среда живого написания кода от CodeSandbox.",
     "It bundles in the browser, so live examples work with no backend at all."),
    ("lib-webcontainers", "WebContainers", "UI и frontend", "https://webcontainers.io/", "mixed", "stackblitz,node-in-browser,wasm,sandbox", "",
     "Runs Node.js entirely inside the browser via WebAssembly.",
     "Запускает Node.js полностью внутри браузера через WebAssembly.",
     "A real Node runtime in a tab means full-stack tutorials need no server or install step."),
]
