# -*- coding: utf-8 -*-
"""Stage 5 library pack R: auth libs, validation, ORMs, misc backend/frontend depth."""

LIBS_5R = [
    # ---------- Аутентификация: libraries ----------
    ("lib-passport-js", "Passport.js", "Аутентификация", "https://www.passportjs.org/docs/", "openSource", "node,auth,strategies,oauth", "npm i passport",
     "Authentication middleware for Node with hundreds of pluggable strategies.",
     "Middleware аутентификации для Node с сотнями подключаемых стратегий.",
     "Its strategy ecosystem is the value — but many community strategies are unmaintained, so check activity."),
    ("lib-lucia-auth", "Lucia", "Аутентификация", "https://lucia-auth.com/", "openSource", "auth,typescript,sessions,learning", "",
     "Session-based auth reference for TypeScript, now positioned as a learning resource.",
     "Session-ориентированная аутентификация для TypeScript, теперь позиционируется как обучающий ресурс.",
     "It deliberately teaches you to own the auth code rather than depending on a library long-term."),
    ("lib-oauthlib", "Authlib", "Аутентификация", "https://docs.authlib.org/", "openSource", "python,oauth,oidc,jwt", "pip install authlib",
     "OAuth and OpenID Connect implementation for Python, both client and server side.",
     "Реализация OAuth и OpenID Connect для Python, и клиент, и сервер.",
     "Covers building an OAuth provider, not just consuming one, which most Python auth libraries do not."),
    ("lib-python-jose", "PyJWT", "Аутентификация", "https://pyjwt.readthedocs.io/", "openSource", "python,jwt,tokens,encoding", "pip install pyjwt",
     "JSON Web Token encoding and decoding for Python.",
     "Кодирование и декодирование JSON Web Token для Python.",
     "Always pass the algorithms parameter explicitly on decode — omitting it has caused real CVEs."),
    ("lib-casbin", "Casbin", "Аутентификация", "https://casbin.org/docs/overview", "openSource", "authorization,rbac,abac,policy", "pip install casbin",
     "Authorization library supporting RBAC, ABAC and custom access control models.",
     "Библиотека авторизации с поддержкой RBAC, ABAC и собственных моделей контроля доступа.",
     "Policy lives in a config file rather than scattered if-statements, which makes permissions auditable."),
    ("lib-oso", "Oso", "Аутентификация", "https://www.osohq.com/docs", "freeTier", "authorization,policy,rbac,fine-grained", "",
     "Authorization as code with a dedicated policy language for fine-grained permissions.",
     "Авторизация как код со специальным языком политик для тонкой настройки разрешений.",
     "Its policy language handles relationship-based rules (\"editors of this document\") that RBAC alone cannot."),
    ("lib-openfga", "OpenFGA", "Аутентификация", "https://openfga.dev/docs", "openSource", "authorization,zanzibar,relationships,cncf", "",
     "Relationship-based authorization modeled on Google Zanzibar, a CNCF project.",
     "Авторизация на основе отношений по модели Google Zanzibar, проект CNCF.",
     "The right model when permissions come from object relationships rather than static user roles."),

    # ---------- Базы данных и ORM (deepen further) ----------
    ("lib-kysely-2", "Kysely Codegen", "Базы данных и ORM", "https://github.com/RobinBlomberg/kysely-codegen", "openSource", "typescript,sql,types,generation", "npm i -D kysely-codegen",
     "Generates TypeScript types for Kysely directly from your live database schema.",
     "Генерирует TypeScript-типы для Kysely прямо из живой схемы базы данных.",
     "Regenerate types in CI so a schema change that breaks a query fails the build, not production."),
    ("lib-sequelize", "Sequelize", "Базы данных и ORM", "https://sequelize.org/docs/v6/", "openSource", "node,orm,sql,migrations", "npm i sequelize",
     "Long-established Node ORM supporting Postgres, MySQL, SQLite and SQL Server.",
     "Давно устоявшийся ORM для Node с поддержкой Postgres, MySQL, SQLite и SQL Server.",
     "Its TypeScript support is weaker than Drizzle or Prisma — prefer those for new TypeScript projects."),
    ("lib-pony-orm", "Peewee", "Базы данных и ORM", "https://docs.peewee-orm.com/", "openSource", "python,orm,small,expressive", "pip install peewee",
     "Small, expressive Python ORM, a lighter alternative to SQLAlchemy.",
     "Небольшой выразительный Python ORM, более лёгкая альтернатива SQLAlchemy.",
     "Good fit for small scripts and services where SQLAlchemy's power is more than the project needs."),
    ("lib-atlas-schema", "Atlas", "Базы данных и ORM", "https://atlasgo.io/docs", "openSource", "migrations,schema,declarative,versioning", "",
     "Declarative database schema management, applying migrations like Terraform applies infrastructure.",
     "Декларативное управление схемой базы данных, применяет миграции как Terraform — инфраструктуру.",
     "Its migration linting catches destructive changes before they run against production data."),
    ("lib-sqlglot", "SQLGlot", "Data engineering", "https://sqlglot.com/", "openSource", "sql,parser,transpiler,python", "pip install sqlglot",
     "SQL parser and transpiler translating between many SQL dialects.",
     "Парсер и транспилятор SQL, переводящий между множеством диалектов SQL.",
     "Useful for migrating queries between warehouses, and for programmatically analysing SQL safely."),

    # ---------- Утилиты: validation and schema ----------
    ("lib-json-schema", "Ajv", "Утилиты", "https://ajv.js.org/", "openSource", "json-schema,validation,javascript,fast", "npm i ajv",
     "The fastest JSON Schema validator for JavaScript, used across the tooling ecosystem.",
     "Самый быстрый валидатор JSON Schema для JavaScript, используется во всей экосистеме тулинга.",
     "Compile schemas once at startup — compiling per request throws away most of its speed advantage."),
    ("lib-typia", "Typia", "Утилиты", "https://typia.io/docs/", "openSource", "typescript,validation,compile-time,fast", "npm i typia",
     "Generates runtime validators from TypeScript types at compile time, extremely fast.",
     "Генерирует рантайм-валидаторы из TypeScript-типов на этапе компиляции, очень быстро.",
     "No separate schema to maintain — your TypeScript interface is the validation source of truth."),
    ("lib-cerberus", "Cerberus", "Утилиты", "https://docs.python-cerberus.org/", "openSource", "python,validation,schema,dictionaries", "pip install cerberus",
     "Lightweight dictionary validation for Python with schema definitions as plain dicts.",
     "Лёгкая валидация словарей в Python со схемами в виде обычных dict.",
     "Simpler than Pydantic when you validate loose dicts rather than construct typed model objects."),
    ("lib-marshmallow", "marshmallow", "Утилиты", "https://marshmallow.readthedocs.io/", "openSource", "python,serialization,validation,schemas", "pip install marshmallow",
     "Object serialization and validation for Python with declarative schemas.",
     "Сериализация и валидация объектов в Python с декларативными схемами.",
     "Predates Pydantic and remains common in Flask projects; new projects usually pick Pydantic instead."),

    # ---------- CLI и терминал (deepen) ----------
    ("lib-gum", "Gum", "CLI и терминал", "https://github.com/charmbracelet/gum", "openSource", "shell,tui,interactive,charm", "brew install gum",
     "Adds interactive prompts, spinners and styling to plain shell scripts.",
     "Добавляет интерактивные подсказки, спиннеры и стилизацию в обычные shell-скрипты.",
     "Turns a bash script into a pleasant interactive tool without rewriting it in another language."),
    ("lib-glow", "Glow", "CLI и терминал", "https://github.com/charmbracelet/glow", "openSource", "markdown,terminal,rendering,charm", "brew install glow",
     "Renders markdown beautifully in the terminal.",
     "Красиво отображает markdown прямо в терминале.",
     "Handy for reading a repository's README without leaving the shell or opening a browser."),
    ("lib-bat", "bat", "CLI и терминал", "https://github.com/sharkdp/bat", "openSource", "cat,syntax-highlighting,rust,pager", "brew install bat",
     "A cat replacement with syntax highlighting and git integration.",
     "Замена cat с подсветкой синтаксиса и интеграцией с git.",
     "Alias cat to bat and file reading in the terminal becomes noticeably more readable."),
    ("lib-eza", "eza", "CLI и терминал", "https://eza.rocks/", "openSource", "ls,rust,colors,tree", "brew install eza",
     "A modern ls replacement with colors, icons and git status columns.",
     "Современная замена ls с цветами, иконками и колонками git-статуса.",
     "The maintained successor to exa, which is no longer developed."),
    ("lib-fd", "fd", "CLI и терминал", "https://github.com/sharkdp/fd", "openSource", "find,rust,fast,simple", "brew install fd",
     "A simpler, faster alternative to find with sensible defaults.",
     "Более простая и быстрая альтернатива find с разумными настройками по умолчанию.",
     "Respects gitignore by default, which is why it feels so much faster inside a real repository."),
]
