# -*- coding: utf-8 -*-
"""Stage 5 API pack L: AI providers depth, embeddings, guardrails, agent infra."""

APIS_5L = [
    # ---------- AI и агенты (deepen providers) ----------
    ("api-perplexity-2", "Perplexity Sonar API", "AI и агенты", "https://docs.perplexity.ai/", "mixed", "search,llm,citations,realtime", "",
     "LLM answers grounded in live web search with citations returned inline.",
     "Ответы LLM, основанные на живом веб-поиске, с цитатами прямо в ответе.",
     "Reach for it when an answer must reflect today's web, not the model's training cutoff."),
    ("api-nvidia-nim", "NVIDIA NIM", "AI и агенты", "https://docs.nvidia.com/nim/", "freeTier", "inference,nvidia,microservices,gpu", "",
     "Containerized inference microservices for running open models on your own GPUs.",
     "Контейнеризованные микросервисы инференса для запуска открытых моделей на своих GPU.",
     "Same OpenAI-compatible API whether hosted or self-run, which keeps client code portable."),
    ("api-sambanova", "SambaNova Cloud", "AI и агенты", "https://docs.sambanova.ai/", "freeTier", "inference,fast,open-models,rdu", "",
     "Fast open-model inference on custom dataflow hardware.",
     "Быстрый инференс открытых моделей на специализированном dataflow-железе.",
     "Another OpenAI-compatible endpoint — worth benchmarking against Groq and Cerebras for your specific model."),
    ("api-lambda-labs", "Lambda", "AI и агенты", "https://docs.lambda.ai/", "mixed", "gpu,cloud,training,inference", "",
     "On-demand GPU cloud aimed at ML training and inference, often cheaper than hyperscalers.",
     "GPU-облако по требованию для обучения и инференса ML, зачастую дешевле гиперскейлеров.",
     "Instance availability fluctuates — check capacity before planning a long training run on a specific GPU type."),
    ("api-runpod", "RunPod", "AI и агенты", "https://docs.runpod.io/", "mixed", "gpu,serverless,containers,inference", "",
     "GPU cloud with both persistent pods and serverless autoscaling inference endpoints.",
     "GPU-облако с постоянными подами и serverless-эндпоинтами инференса с автомасштабированием.",
     "Serverless endpoints scale to zero, so intermittent workloads cost far less than a persistent pod."),
    ("api-openai-embeddings", "OpenAI Embeddings", "Поиск и retrieval", "https://platform.openai.com/docs/guides/embeddings", "paid", "embeddings,vectors,rag,openai", "",
     "Text embedding models for semantic search and RAG pipelines.",
     "Модели текстовых эмбеддингов для семантического поиска и RAG-пайплайнов.",
     "The dimensions parameter lets you shorten vectors to cut storage cost with modest quality loss."),
    ("api-google-embeddings", "Gemini Embeddings", "Поиск и retrieval", "https://ai.google.dev/gemini-api/docs/embeddings", "freeTier", "embeddings,google,rag,multilingual", "",
     "Google's text embedding models, with a usable free tier via AI Studio.",
     "Модели текстовых эмбеддингов Google с рабочим бесплатным тарифом через AI Studio.",
     "Set task_type (retrieval_document vs retrieval_query) — asymmetric embeddings measurably improve recall."),
    ("api-mixedbread", "Mixedbread", "Поиск и retrieval", "https://www.mixedbread.com/api-reference", "freeTier", "embeddings,rerank,open-models,search", "",
     "Embedding and reranking models, with open-weight versions published alongside the API.",
     "Модели эмбеддингов и реранка, с открытыми весами, публикуемыми параллельно с API.",
     "Open weights mean you can prototype on the API and self-host the same model later without re-tuning."),

    # ---------- AI-оценка и safety (deepen) ----------
    ("api-openai-moderation", "OpenAI Moderation API", "AI-оценка и safety", "https://platform.openai.com/docs/guides/moderation", "free", "moderation,safety,content-policy,free", "",
     "Free content moderation endpoint classifying text and images against safety categories.",
     "Бесплатный эндпоинт модерации, классифицирующий текст и изображения по категориям безопасности.",
     "Free even without paid API usage, which makes it a cheap first filter on user-generated content."),
    ("api-perspective-api", "Perspective API", "AI-оценка и safety", "https://developers.perspectiveapi.com/", "free", "moderation,toxicity,jigsaw,google", "",
     "Toxicity scoring for comments and user content, from Google Jigsaw.",
     "Оценка токсичности комментариев и пользовательского контента от Google Jigsaw.",
     "Scores are probabilities, not verdicts — pick a threshold from your own data rather than trusting a default."),
    ("api-hive-moderation", "Hive Moderation", "AI-оценка и safety", "https://docs.thehive.ai/", "paid", "moderation,images,video,nsfw", "",
     "Visual and text moderation covering NSFW, violence and other content classes.",
     "Модерация изображений и текста: NSFW, насилие и другие категории контента.",
     "Its visual moderation is the differentiator — most free moderation APIs cover text only."),

    # ---------- Инфраструктура MCP / agent infra ----------
    ("api-e2b-sandboxes", "E2B Sandboxes", "Браузер и автоматизация", "https://e2b.dev/docs", "freeTier", "sandbox,code-execution,agents,isolation", "pip install e2b-code-interpreter",
     "Isolated cloud sandboxes for running AI-generated code safely.",
     "Изолированные облачные песочницы для безопасного запуска сгенерированного ИИ кода.",
     "Never run model-generated code on your own host — this is the specific problem E2B exists to solve."),
    ("api-daytona", "Daytona", "Браузер и автоматизация", "https://www.daytona.io/docs/", "freeTier", "sandbox,dev-environments,agents,isolation", "",
     "Fast, isolated development environments usable as agent sandboxes.",
     "Быстрые изолированные среды разработки, применимые как песочницы для агентов.",
     "Sub-second sandbox creation is the differentiator versus spinning up a container per task yourself."),
    ("api-modal-sandboxes", "Modal Sandboxes", "Браузер и автоматизация", "https://modal.com/docs/guide/sandbox", "freeTier", "sandbox,python,agents,serverless", "pip install modal",
     "Ephemeral sandboxes on Modal for running untrusted or agent-generated code.",
     "Эфемерные песочницы Modal для запуска недоверенного или сгенерированного агентом кода.",
     "Useful if you already run Modal for GPU work — one platform for both inference and sandboxing."),

    # ---------- Память и знания (deepen) ----------
    ("api-mem0", "Mem0", "Память и знания", "https://docs.mem0.ai/", "freeTier", "memory,agents,personalization,recall", "pip install mem0ai",
     "Memory layer for AI agents storing user preferences and facts across sessions.",
     "Слой памяти для ИИ-агентов, хранящий предпочтения и факты пользователя между сессиями.",
     "Store durable preferences and decisions, not raw transcripts — recall quality degrades as the store bloats."),
    ("api-zep", "Zep", "Память и знания", "https://help.getzep.com/", "freeTier", "memory,agents,knowledge-graph,temporal", "",
     "Temporal knowledge graph memory for agents, tracking how facts change over time.",
     "Темпоральный граф знаний как память агента, отслеживающий изменение фактов во времени.",
     "Its temporal model handles superseded facts correctly, which naive vector memory gets wrong."),
    ("api-letta", "Letta (MemGPT)", "Память и знания", "https://docs.letta.com/", "openSource", "memory,agents,stateful,memgpt", "pip install letta",
     "Stateful agents with self-editing long-term memory, the MemGPT research made practical.",
     "Агенты с состоянием и саморедактируемой долговременной памятью — практическое воплощение MemGPT.",
     "Agents manage their own memory paging, which suits long-lived assistants over one-shot task agents."),

    # ---------- Данные и ML (hosted) ----------
    ("api-huggingface-datasets", "Hugging Face Datasets Server", "Данные и ML", "https://huggingface.co/docs/dataset-viewer/", "free", "datasets,api,preview,huggingface", "",
     "REST API for previewing and querying any dataset on the Hugging Face Hub without downloading it.",
     "REST API для просмотра и запросов к любому датасету на Hugging Face Hub без скачивания.",
     "Query rows and filters server-side to inspect a huge dataset before committing disk space to it."),
    ("api-kaggle", "Kaggle API", "Данные и ML", "https://www.kaggle.com/docs/api", "free", "datasets,competitions,notebooks,kaggle", "pip install kaggle",
     "Programmatic access to Kaggle datasets, competitions and notebook execution.",
     "Программный доступ к датасетам, соревнованиям и запуску ноутбуков Kaggle.",
     "Dataset downloads need accepted competition rules for competition data — the API errors cryptically otherwise."),
]
