# -*- coding: utf-8 -*-
"""Stage 5 API pack V: banking-as-a-service, payments rails, market data, blockchain infra."""

APIS_5V = [
    # ---------- Финансы: банковские данные и открытый банкинг ----------
    ("api-teller", "Teller", "Финансы", "https://teller.io/docs", "freeTier", "banking,open-banking,accounts,us", "",
     "US bank account connectivity API positioned as a leaner Plaid alternative.",
     "API подключения к банковским счетам США, позиционируется как более лёгкая альтернатива Plaid.",
     "Direct bank connections rather than screen scraping, which makes link stability noticeably better."),
    ("api-gocardless-bank-data", "GoCardless Bank Account Data", "Финансы", "https://developer.gocardless.com/bank-account-data/overview", "freeTier", "open-banking,psd2,europe,accounts", "",
     "PSD2 open banking access to European bank account data, with a free tier.",
     "Доступ к данным банковских счетов Европы по PSD2 open banking с бесплатным тарифом.",
     "Free for a limited number of accounts per month, which is unusual in European open banking."),
    ("api-airwallex", "Airwallex", "Финансы", "https://www.airwallex.com/docs", "mixed", "payments,fx,global-accounts,cards", "",
     "Global payments, FX and business account APIs for cross-border commerce.",
     "API глобальных платежей, FX и бизнес-счетов для трансграничной коммерции.",
     "Local collection accounts in many countries avoid the FX conversion on every incoming payment."),
    ("api-nium", "Nium", "Финансы", "https://docs.nium.com/", "paid", "payouts,global,cards,embedded-finance", "",
     "Global payout and embedded finance infrastructure covering many corridors.",
     "Инфраструктура глобальных выплат и встроенных финансов, покрывающая множество коридоров.",
     "Corridor coverage and settlement speed vary widely — verify your specific country pairs."),
    ("api-rapyd", "Rapyd", "Финансы", "https://docs.rapyd.net/", "paid", "payments,local-methods,payouts,global", "",
     "Payment platform supporting many local payment methods across regions.",
     "Платёжная платформа с поддержкой множества локальных способов оплаты по регионам.",
     "Local method support is the reason to choose it over card-first processors in emerging markets."),

    # ---------- Финансы: банковская инфраструктура ----------
    ("api-modern-treasury", "Modern Treasury", "Финансы", "https://docs.moderntreasury.com/", "paid", "payment-operations,ledger,ach,reconciliation", "",
     "Payment operations and double-entry ledger APIs for money movement at scale.",
     "API платёжных операций и двойной бухгалтерии для перемещения денег в больших объёмах.",
     "Its ledger product is the part worth studying — most teams build this badly in-house first."),
    ("api-increase-bank", "Increase", "Финансы", "https://increase.com/documentation", "paid", "banking,ach,wire,api-first", "",
     "Direct bank infrastructure API for ACH, wires and real-time payments.",
     "API прямой банковской инфраструктуры для ACH, банковских переводов и платежей в реальном времени.",
     "Talks to the bank rails directly rather than through a BaaS middle layer, which reduces failure modes."),
    ("api-unit-banking", "Unit", "Финансы", "https://docs.unit.co/", "paid", "banking-as-a-service,accounts,cards,embedded", "",
     "Banking-as-a-service platform for embedding accounts, cards and payments in your product.",
     "Платформа banking-as-a-service для встраивания счетов, карт и платежей в ваш продукт.",
     "Compliance and sponsor-bank relationships are the real product — the API is the easy part."),
    ("api-column-bank", "Column", "Финансы", "https://column.com/docs", "paid", "bank,api,ach,developer-first", "",
     "Nationally chartered bank offering direct developer APIs without a middleman.",
     "Банк с национальной лицензией, предоставляющий прямые API для разработчиков без посредников.",
     "Being the bank itself removes the sponsor-bank layer that most BaaS providers depend on."),
    ("api-lithic", "Lithic", "Финансы", "https://docs.lithic.com/", "freeTier", "cards,issuing,virtual-cards,api", "",
     "Card issuing API for virtual and physical cards with programmable spend controls.",
     "API выпуска виртуальных и физических карт с программируемыми правилами трат.",
     "Its sandbox is genuinely usable without a signed contract, unlike most issuing platforms."),
    ("api-moov", "Moov", "Финансы", "https://docs.moov.io/", "freeTier", "payments,ach,wallets,open-source", "",
     "Payments platform with open-source components for ACH and wallet flows.",
     "Платёжная платформа с открытыми компонентами для ACH и кошельков.",
     "Its open-source ACH file libraries are useful on their own, even outside the hosted platform."),
    ("api-dwolla", "Dwolla", "Финансы", "https://developers.dwolla.com/", "paid", "ach,bank-transfers,us,white-label", "",
     "White-label ACH bank transfer API for US account-to-account payments.",
     "White-label API банковских переводов ACH для платежей между счетами в США.",
     "ACH is slow but far cheaper than cards, which is the whole reason to build on it."),

    # ---------- Финансы: рынки и брокеры ----------
    ("api-alpaca", "Alpaca", "Финансы", "https://docs.alpaca.markets/", "freeTier", "brokerage,trading,stocks,paper-trading", "",
     "Commission-free stock and crypto trading API with a full paper-trading environment.",
     "API безкомиссионной торговли акциями и криптовалютой с полноценной средой бумажной торговли.",
     "Paper trading uses the same endpoints as live, so a strategy is tested before any money moves."),
    ("api-tradier", "Tradier", "Финансы", "https://documentation.tradier.com/", "mixed", "brokerage,options,market-data,trading", "",
     "Brokerage and market data API with strong options chain support.",
     "API брокериджа и рыночных данных с сильной поддержкой опционных цепочек.",
     "Options chain data is where it beats general market data APIs that treat options as an afterthought."),
    ("api-intrinio", "Intrinio", "Финансы", "https://docs.intrinio.com/", "paid", "fundamentals,market-data,filings,institutional", "",
     "Institutional-grade fundamentals, filings and market data.",
     "Фундаментальные данные, отчётность и рыночные данные институционального уровня.",
     "Data is sold per feed, so cost depends heavily on which specific datasets you actually need."),
    ("api-tiingo", "Tiingo", "Финансы", "https://www.tiingo.com/documentation/general/overview", "freeTier", "market-data,eod,news,affordable", "",
     "Affordable end-of-day prices, fundamentals and financial news.",
     "Доступные цены на конец дня, фундаментальные данные и финансовые новости.",
     "Its free tier covers end-of-day history well enough for backtesting non-intraday strategies."),

    # ---------- Криптовалюты и рыночные данные ----------
    ("api-kraken", "Kraken API", "Финансы", "https://docs.kraken.com/api/", "free", "crypto,exchange,trading,websocket", "",
     "Crypto exchange REST and WebSocket APIs for market data and trading.",
     "REST и WebSocket API криптобиржи для рыночных данных и торговли.",
     "Public market data endpoints need no account, which makes them easy to prototype against."),
    ("api-coinbase-advanced", "Coinbase Advanced Trade API", "Финансы", "https://docs.cdp.coinbase.com/advanced-trade/docs/welcome", "free", "crypto,exchange,trading,coinbase", "",
     "Coinbase's trading API for orders, portfolios and real-time market data.",
     "Торговый API Coinbase для ордеров, портфелей и рыночных данных в реальном времени.",
     "Use the WebSocket feed for prices — polling REST for quotes hits rate limits fast."),
    ("api-binance", "Binance API", "Финансы", "https://developers.binance.com/docs", "free", "crypto,exchange,trading,high-volume", "",
     "Large crypto exchange API with deep market data and trading endpoints.",
     "API крупной криптобиржи с подробными рыночными данными и торговыми эндпоинтами.",
     "Availability varies by jurisdiction — confirm regional access before building on it."),

    # ---------- Web3 инфраструктура ----------
    ("api-infura", "Infura", "Web3 и блокчейн", "https://docs.metamask.io/services/", "freeTier", "ethereum,rpc,nodes,infrastructure", "",
     "Hosted RPC endpoints for Ethereum and other chains, so you run no node yourself.",
     "Размещённые RPC-эндпоинты для Ethereum и других сетей — свой узел запускать не нужно.",
     "Archive node access is the paid feature — normal RPC covers recent state only."),
    ("api-dune", "Dune Analytics API", "Web3 и блокчейн", "https://docs.dune.com/api-reference/overview/introduction", "freeTier", "blockchain,sql,analytics,queries", "",
     "Runs SQL queries over decoded blockchain data and returns results via API.",
     "Выполняет SQL-запросы к декодированным блокчейн-данным и возвращает результаты через API.",
     "Community-built queries cover most common metrics — fork one rather than writing from scratch."),
    ("api-helius", "Helius", "Web3 и блокчейн", "https://www.helius.dev/docs", "freeTier", "solana,rpc,webhooks,indexing", "",
     "Solana RPC, webhooks and enhanced transaction parsing.",
     "RPC для Solana, вебхуки и расширенный разбор транзакций.",
     "Its parsed transaction format saves decoding Solana's raw instruction data by hand."),
    ("api-blockdaemon", "Blockdaemon", "Web3 и блокчейн", "https://docs.blockdaemon.com/", "paid", "nodes,staking,institutional,multichain", "",
     "Institutional node infrastructure and staking APIs across many chains.",
     "Институциональная инфраструктура узлов и API стейкинга для множества сетей.",
     "Aimed at institutional SLAs — overkill for a hobby project versus a free-tier RPC provider."),
]
