# -*- coding: utf-8 -*-
"""Stage 5 pricing pack E: mobile attribution, experience analytics, product adoption."""

PAID_5E = [
("paid-appsflyer","AppsFlyer (pricing)","CDP и маркетинг-данные","https://www.appsflyer.com/pricing/","paid","attribution,pricing,per-conversion,mobile",
 "Mobile attribution billed per attributed conversion, with a free tier for low volume.",
 "Мобильная атрибуция с оплатой за атрибутированную конверсию и бесплатным тарифом при малых объёмах.",
 "The zero-cost tier covers early apps entirely — paid plans start once install volume grows.",
 "usage","from ~$0.05 per conversion","free tier up to 12k conversions/month","https://www.appsflyer.com/pricing/"),
("paid-adjust","Adjust (pricing)","CDP и маркетинг-данные","https://www.adjust.com/pricing/","paid","attribution,pricing,per-install,custom",
 "Mobile measurement priced per attributed install on annual contracts.",
 "Мобильные измерения с ценой за атрибутированную установку по годовым контрактам.",
 "Fraud prevention is bundled rather than a separate line, which matters when comparing quotes.",
 "custom","custom quote (per attributed install)","product demo","https://www.adjust.com/pricing/"),
("paid-singular","Singular (pricing)","CDP и маркетинг-данные","https://www.singular.net/pricing/","paid","marketing-analytics,pricing,volume,custom",
 "Marketing analytics priced by attributed volume and connected ad channels.",
 "Маркетинговая аналитика с ценой по атрибутированному объёму и числу подключённых рекламных каналов.",
 "Cost scales with the number of ad networks you connect, not only with install volume.",
 "custom","custom quote","product demo","https://www.singular.net/pricing/"),
("paid-fullstory","FullStory (pricing)","Мониторинг и аналитика","https://www.fullstory.com/pricing/","paid","session-replay,pricing,sessions,subscription",
 "Session replay and analytics billed by monthly captured sessions.",
 "Запись сессий и аналитика с оплатой по числу захваченных сессий в месяц.",
 "Sampling high-traffic pages keeps session counts, and therefore cost, under control.",
 "subscription","custom quote (by monthly sessions)","free trial","https://www.fullstory.com/pricing/"),
("paid-contentsquare","Contentsquare (pricing)","Мониторинг и аналитика","https://contentsquare.com/pricing/","paid","experience-analytics,pricing,enterprise,pageviews",
 "Digital experience analytics sold on enterprise contracts scaled to page views.",
 "Аналитика цифрового опыта по корпоративным контрактам, масштабируемым под просмотры страниц.",
 "Enterprise-only; Clarity and Hotjar cover the same basic questions at a fraction of the effort.",
 "custom","custom quote","free trial","https://contentsquare.com/pricing/"),
("paid-embrace-io","Embrace (pricing)","Mobile skills","https://embrace.io/pricing/","paid","mobile-observability,pricing,sessions,custom",
 "Mobile observability priced by monthly user sessions.",
 "Мобильная observability с ценой по числу пользовательских сессий в месяц.",
 "Justified where non-crash failures cost real revenue — Crashlytics is free and covers crashes alone.",
 "custom","custom quote (by monthly sessions)","free trial","https://embrace.io/pricing/"),
("paid-pendo","Pendo (pricing)","Мониторинг и аналитика","https://www.pendo.io/pricing/","paid","product-analytics,pricing,mau,subscription",
 "Product analytics and in-app guides billed by monthly active users.",
 "Продуктовая аналитика и внутриприложенческие подсказки с оплатой по активным пользователям в месяц.",
 "Its free plan covers a small user base fully, including the in-app guides.",
 "subscription","free up to 500 MAU, then custom quote","free tier","https://www.pendo.io/pricing/"),
("paid-appcues","Appcues (pricing)","UI и frontend","https://www.appcues.com/pricing","paid","onboarding,pricing,mau,subscription",
 "In-app onboarding flows billed by monthly active users.",
 "Онбординг внутри приложения с оплатой по активным пользователям в месяц.",
 "MAU pricing means a large free user base costs the same as a large paying one — check the fit.",
 "subscription","from ~$249 per month","free trial","https://www.appcues.com/pricing"),
("paid-userpilot","Userpilot (pricing)","UI и frontend","https://userpilot.com/pricing/","paid","onboarding,pricing,mau,subscription",
 "In-app engagement flows billed by monthly active users.",
 "Внутриприложенческие сценарии вовлечения с оплатой по активным пользователям в месяц.",
 "Generally cheaper per MAU than Appcues at small scale, with a narrower analytics layer.",
 "subscription","from ~$249 per month","free trial","https://userpilot.com/pricing/"),
("paid-chameleon","Chameleon (pricing)","UI и frontend","https://www.chameleon.io/pricing","paid","product-tours,pricing,mau,subscription",
 "Product tours and microsurveys billed by monthly active users.",
 "Продуктовые туры и микроопросы с оплатой по активным пользователям в месяц.",
 "Its styling flexibility is the reason to pay over the lighter open-source tour libraries.",
 "subscription","from ~$279 per month","free trial","https://www.chameleon.io/pricing"),
]
