# -*- coding: utf-8 -*-
"""Stage 5 API pack AE: 3D and avatar generation, motion capture, generative audio and video."""

APIS_5AE = [
    # ---------- Генерация 3D ----------
    ("api-tripo-ai", "Tripo AI", "Анимация и 3D", "https://platform.tripo3d.ai/docs", "freeTier", "text-to-3d,image-to-3d,mesh,api", "",
     "Generates 3D meshes from text prompts or a single image.",
     "Генерирует 3D-меши из текстовых промптов или одного изображения.",
     "Ask for a quad-topology mesh if the model will be rigged — triangulated output animates badly."),
    ("api-rodin-hyper3d", "Rodin (Hyper3D)", "Анимация и 3D", "https://developer.hyper3d.ai/", "freeTier", "text-to-3d,pbr,high-detail,api", "",
     "3D asset generation producing meshes with PBR material maps.",
     "Генерация 3D-ассетов с мешами и PBR-картами материалов.",
     "Generated PBR maps drop straight into a game engine, unlike bare untextured geometry."),
    ("api-sloyd", "Sloyd", "Анимация и 3D", "https://docs.sloyd.ai/", "freeTier", "parametric,real-time,game-assets,low-poly", "",
     "Parametric 3D model generation tuned for real-time game assets.",
     "Параметрическая генерация 3D-моделей для игровых ассетов реального времени.",
     "Parametric rather than diffusion-based, so the topology is predictable and genuinely game-ready."),
    ("api-kaedim", "Kaedim", "Анимация и 3D", "https://docs.kaedim3d.com/", "paid", "image-to-3d,production-ready,game-art,quality-control", "",
     "Converts 2D concept art into production-ready 3D models.",
     "Преобразует 2D концепт-арт в готовые к продакшну 3D-модели.",
     "Human quality control on each asset is what separates it from purely automated generators."),
    ("api-csm-ai", "Common Sense Machines", "Анимация и 3D", "https://docs.csm.ai/", "freeTier", "image-to-3d,scene-reconstruction,api,research", "",
     "Turns images and video into 3D assets and scene reconstructions.",
     "Превращает изображения и видео в 3D-ассеты и реконструкции сцен.",
     "Its multi-image mode reconstructs far more accurate geometry than a single-photo pipeline."),
    ("api-alpha3d", "Alpha3D", "Анимация и 3D", "https://www.alpha3d.io/", "paid", "2d-to-3d,ecommerce,ar,automation", "",
     "Automated 2D-to-3D conversion aimed at e-commerce and AR catalogues.",
     "Автоматическая конвертация 2D в 3D для каталогов e-commerce и AR.",
     "Product photos become AR-viewable models without a photogrammetry rig."),
    ("api-masterpiece-x", "Masterpiece X", "Анимация и 3D", "https://www.masterpiecex.com/", "freeTier", "text-to-3d,animated,rigged,generative", "",
     "Generates textured and rigged 3D models from text.",
     "Генерирует текстурированные и оснащённые скелетом 3D-модели из текста.",
     "Rigged output is rare among generators — most leave animation entirely to you."),
    ("api-spline", "Spline", "Анимация и 3D", "https://docs.spline.design/", "freeTier", "3d-design,web,interactive,no-code", "",
     "Browser-based 3D design tool that exports interactive web scenes.",
     "Браузерный инструмент 3D-дизайна, экспортирующий интерактивные веб-сцены.",
     "Its React export drops a 3D scene into a landing page without touching Three.js."),
    ("api-polycam", "Polycam", "Анимация и 3D", "https://learn.poly.cam/developers", "freeTier", "photogrammetry,lidar,scanning,capture", "",
     "3D scanning from phone photos and LiDAR, with an API for captures.",
     "3D-сканирование по фото с телефона и LiDAR с API для полученных моделей.",
     "Scanning a real object beats generating one when the object actually exists."),

    # ---------- Аватары и захват движения ----------
    ("api-ready-player-me", "Ready Player Me", "Анимация и 3D", "https://docs.readyplayer.me/", "freeTier", "avatars,cross-game,glb,customization", "",
     "Cross-application 3D avatar platform with a customization flow.",
     "Платформа кроссплатформенных 3D-аватаров с настройкой внешности.",
     "One avatar works across applications, which is the point — building your own creator is weeks of work."),
    ("api-avaturn", "Avaturn", "Анимация и 3D", "https://docs.avaturn.me/", "freeTier", "avatars,photorealistic,selfie,rigged", "",
     "Creates realistic rigged avatars from a single selfie.",
     "Создаёт реалистичных оснащённых аватаров по одному селфи.",
     "Its output is standard rigged glTF, so it drops into Unity or Three.js unchanged."),
    ("api-move-ai", "Move AI", "Анимация и 3D", "https://www.move.ai/", "paid", "motion-capture,markerless,video,animation", "",
     "Markerless motion capture from ordinary video footage.",
     "Безмаркерный захват движения из обычного видео.",
     "Multi-camera capture without a suit or studio is what makes it cheaper than traditional mocap."),
    ("api-deepmotion", "DeepMotion", "Анимация и 3D", "https://docs.deepmotion.com/", "freeTier", "motion-capture,video-to-animation,api,3d", "",
     "Converts video into 3D character animation through an API.",
     "Преобразует видео в 3D-анимацию персонажа через API.",
     "Its API makes video-to-animation a pipeline step rather than a manual studio session."),
    ("api-plask", "Plask", "Анимация и 3D", "https://plask.ai/", "freeTier", "motion-capture,browser,ai,animation", "",
     "Browser-based AI motion capture and animation editor.",
     "AI-захват движения и редактор анимации в браузере.",
     "Nothing to install, which lowers the barrier for a small team without a mocap budget."),
    ("api-rokoko", "Rokoko", "Анимация и 3D", "https://docs.rokoko.com/", "paid", "motion-capture,suits,live-streaming,unity", "",
     "Motion capture suits with live streaming into game engines.",
     "Костюмы захвата движения с потоковой передачей в игровые движки.",
     "Hardware-based, so it stays accurate where video capture degrades under occlusion."),
    ("api-cascadeur", "Cascadeur", "Анимация и 3D", "https://cascadeur.com/help", "freeTier", "animation,physics,ai-assisted,keyframe", "",
     "Physics-aware character animation software with AI-assisted posing.",
     "Программа анимации персонажей с учётом физики и AI-помощью в позировании.",
     "Its physics checks catch poses that look wrong but are hard to diagnose by eye."),
    ("api-scenario", "Scenario", "Изображения и дизайн", "https://docs.scenario.com/", "freeTier", "game-assets,style-consistency,training,api", "",
     "Generates game assets in a consistent trained art style.",
     "Генерирует игровые ассеты в едином обученном художественном стиле.",
     "Training on your own art is what keeps a generated asset set visually coherent."),
    ("api-layer-ai", "Layer.ai", "Изображения и дизайн", "https://layer.ai/", "paid", "game-art,style,production,collaboration", "",
     "Game art production platform with style-consistent generation.",
     "Платформа производства игрового арта с генерацией в едином стиле.",
     "Built around a studio pipeline rather than one-off prompting, which is a different workflow entirely."),

    # ---------- Генеративное аудио ----------
    ("api-mubert", "Mubert", "Музыка и медиа", "https://mubert.com/render/docs", "freeTier", "generative-music,royalty-free,streaming,api", "",
     "Generative royalty-free music via API, including endless streams.",
     "Генеративная музыка без роялти через API, включая бесконечные потоки.",
     "Its licensing is explicit, which matters — most music generators leave commercial rights vague."),
    ("api-soundraw", "Soundraw", "Музыка и медиа", "https://soundraw.io/", "paid", "music-generation,customizable,royalty-free,video", "",
     "AI music generation with per-section customization.",
     "Генерация музыки с настройкой по частям композиции.",
     "Editing individual sections lets you fit a track to video timing rather than the reverse."),
    ("api-beatoven", "Beatoven.ai", "Музыка и медиа", "https://docs.beatoven.ai/", "freeTier", "mood-based,music,api,royalty-free", "",
     "Mood-based background music generation with an API.",
     "Генерация фоновой музыки по настроению с API.",
     "Mood parameters are easier to drive programmatically than free-text music prompts."),
    ("api-aiva", "AIVA", "Музыка и медиа", "https://www.aiva.ai/", "freeTier", "composition,classical,soundtracks,midi", "",
     "AI composition tool producing orchestral and soundtrack music.",
     "Инструмент AI-композиции для оркестровой и саундтрек-музыки.",
     "MIDI export means a composer can take the output and finish it properly."),
    ("api-stable-audio", "Stable Audio", "Музыка и медиа", "https://stability.ai/stable-audio", "freeTier", "stability,audio-generation,sound-effects,api", "",
     "Audio and sound effect generation from Stability AI.",
     "Генерация аудио и звуковых эффектов от Stability AI.",
     "Its sound effect generation is more immediately useful than its music for most products."),
    ("api-loudly", "Loudly", "Музыка и медиа", "https://loudly.com/music-api", "freeTier", "music-api,generation,licensing,catalog", "",
     "Music generation and licensed catalogue access through one API.",
     "Генерация музыки и доступ к лицензированному каталогу через один API.",
     "Combining generated and catalogue tracks covers cases where generation alone sounds wrong."),

    # ---------- Генеративное видео и аватары ----------
    ("api-pika", "Pika", "Видео и медиа", "https://pika.art/", "freeTier", "video-generation,effects,text-to-video,creative", "",
     "Text and image to video generation with stylized effects.",
     "Генерация видео из текста и изображений со стилизованными эффектами.",
     "Its effect presets produce more consistent results than free-form prompting."),
    ("api-minimax-hailuo", "MiniMax Hailuo", "Видео и медиа", "https://www.minimax.io/platform/document/video_generation", "paid", "video-generation,motion,api,realistic", "",
     "Video generation API with strong motion coherence.",
     "API генерации видео с хорошей связностью движения.",
     "Motion coherence across frames is where most video generators visibly fail."),
    ("api-genmo", "Genmo", "Видео и медиа", "https://www.genmo.ai/", "openSource", "video-generation,open-weights,mochi,research", "",
     "Open-weight video generation models, including Mochi.",
     "Модели генерации видео с открытыми весами, включая Mochi.",
     "Open weights mean you can self-host, which no closed video API allows."),
    ("api-ltx-studio", "LTX Studio", "Видео и медиа", "https://ltx.studio/", "freeTier", "storyboard,video,production,consistency", "",
     "AI video production with storyboarding and character consistency.",
     "AI-производство видео с раскадровкой и постоянством персонажей.",
     "Character consistency across shots is the hard part of AI video, and it targets that directly."),
    ("api-higgsfield", "Higgsfield", "Видео и медиа", "https://higgsfield.ai/", "freeTier", "camera-control,video,motion,cinematic", "",
     "Video generation with explicit cinematic camera controls.",
     "Генерация видео с явным управлением кинематографичной камерой.",
     "Naming a camera move gives far more control than describing it in a prompt."),
    ("api-heygen", "HeyGen", "Видео и медиа", "https://docs.heygen.com/", "freeTier", "avatars,talking-head,translation,api", "",
     "AI avatar video generation with voice cloning and translation.",
     "Генерация видео с AI-аватарами, клонированием голоса и переводом.",
     "Its translation keeps lip sync, which makes localized video viable at scale."),
    ("api-synthesia", "Synthesia", "Видео и медиа", "https://docs.synthesia.io/", "paid", "avatars,corporate,training-videos,api", "",
     "Avatar video platform aimed at corporate training content.",
     "Платформа видео с аватарами для корпоративного обучающего контента.",
     "Updating a script regenerates the video, which removes the reshoot from documentation updates."),
    ("api-d-id", "D-ID", "Видео и медиа", "https://docs.d-id.com/", "freeTier", "talking-heads,photo-animation,streaming,api", "",
     "Animates still photos into talking head video, including live streaming.",
     "Оживляет статичные фото в говорящие головы, включая потоковый режим.",
     "Its streaming mode drives a real-time avatar, which batch generation cannot do."),
    ("api-hedra", "Hedra", "Видео и медиа", "https://docs.hedra.com/", "freeTier", "character-video,expressive,audio-driven,api", "",
     "Audio-driven expressive character video generation.",
     "Генерация выразительного видео персонажа по аудиодорожке.",
     "Expression follows the audio's emotion, not just its phonemes, which reads far less robotic."),
    ("api-captions-ai", "Captions", "Видео и медиа", "https://www.captions.ai/", "freeTier", "video-editing,subtitles,eye-contact,mobile", "",
     "AI video editing with automatic subtitles and eye contact correction.",
     "AI-монтаж видео с автосубтитрами и коррекцией зрительного контакта.",
     "Its eye contact correction fixes the reading-from-script look that ruins talking-head video."),
    ("api-argil", "Argil", "Видео и медиа", "https://docs.argil.ai/", "paid", "avatar-clones,content,api,social", "",
     "Creates a video avatar clone for repeatable content production.",
     "Создаёт видеоклон-аватар для повторяемого производства контента.",
     "Cloning your own likeness needs explicit consent handling if anyone else appears in the footage."),
]
