# -*- coding: utf-8 -*-
"""Stage 5 library pack V: embedded, IoT, RTOS, device build systems."""

LIBS_5V = [
    # ---------- Встраиваемые системы и RTOS ----------
    ("lib-freertos", "FreeRTOS", "Языки и рантаймы", "https://www.freertos.org/Documentation/00-Overview", "openSource", "rtos,embedded,microcontroller,scheduler", "",
     "The most widely deployed real-time kernel for microcontrollers, MIT-licensed.",
     "Самое распространённое ядро реального времени для микроконтроллеров, лицензия MIT.",
     "Its permissive licence is why it appears in commercial products where GPL RTOSes cannot."),
    ("lib-mbed-os", "Mbed OS", "Языки и рантаймы", "https://os.mbed.com/docs/mbed-os/latest/introduction/index.html", "openSource", "rtos,arm,embedded,cpp", "",
     "Arm's embedded operating system with drivers, networking and security built in.",
     "Встраиваемая операционная система Arm с драйверами, сетью и безопасностью из коробки.",
     "Development has slowed considerably — check project activity before starting something new on it."),
    ("lib-embassy-rs", "Embassy", "Языки и рантаймы", "https://embassy.dev/book/", "openSource", "rust,embedded,async,no-std", "",
     "Async embedded framework for Rust, bringing async/await to bare-metal microcontrollers.",
     "Асинхронный встраиваемый фреймворк для Rust, приносящий async/await на bare-metal микроконтроллеры.",
     "Async replaces the traditional RTOS task model, often with smaller binaries and no separate scheduler."),
    ("lib-embedded-hal", "embedded-hal", "Языки и рантаймы", "https://docs.rs/embedded-hal/latest/embedded_hal/", "openSource", "rust,embedded,traits,portable", "cargo add embedded-hal",
     "Trait definitions letting Rust device drivers work across any supported microcontroller.",
     "Определения трейтов, позволяющие драйверам устройств на Rust работать на любом поддерживаемом микроконтроллере.",
     "Write a sensor driver once against the traits and it compiles for STM32, ESP32 and RP2040 alike."),
    ("lib-tinygo", "TinyGo", "Языки и рантаймы", "https://tinygo.org/docs/", "openSource", "go,embedded,wasm,small-binaries", "",
     "Go compiler targeting microcontrollers and WebAssembly with much smaller output.",
     "Компилятор Go для микроконтроллеров и WebAssembly с существенно меньшим размером вывода.",
     "Not all of the Go standard library is supported — check package compatibility before porting code."),
    ("lib-arduino-cli", "Arduino CLI", "Разработка и DevOps", "https://arduino.github.io/arduino-cli/latest/", "openSource", "arduino,cli,build,ci", "",
     "Command-line interface for compiling and uploading Arduino sketches, usable in CI.",
     "Интерфейс командной строки для компиляции и загрузки скетчей Arduino, применим в CI.",
     "Makes firmware builds reproducible in CI, which the Arduino IDE alone cannot do."),

    # ---------- Сборка образов устройств ----------
    ("lib-yocto", "Yocto Project", "Разработка и DevOps", "https://docs.yoctoproject.org/", "openSource", "linux,embedded,build-system,images", "",
     "Build system for creating custom Linux distributions for embedded hardware.",
     "Система сборки кастомных Linux-дистрибутивов для встраиваемого оборудования.",
     "The learning curve is steep and builds are slow, but it is the industry standard for shipping devices."),
    ("lib-buildroot", "Buildroot", "Разработка и DevOps", "https://buildroot.org/docs.html", "openSource", "linux,embedded,build-system,simple", "",
     "Simpler alternative to Yocto for generating embedded Linux root filesystems.",
     "Более простая альтернатива Yocto для генерации корневых файловых систем встраиваемого Linux.",
     "Far easier to learn than Yocto, but it rebuilds from scratch rather than supporting incremental layers."),
    ("lib-balena-os", "balenaOS", "Разработка и DevOps", "https://docs.balena.io/reference/OS/overview/2.x/", "openSource", "iot,containers,fleet,linux", "",
     "Container-focused Linux OS for IoT devices, designed for remote fleet management.",
     "Linux-ОС на контейнерах для IoT-устройств, рассчитанная на удалённое управление парком.",
     "Running device software as containers makes over-the-air updates behave like a normal deploy."),
    ("lib-mender", "Mender", "Разработка и DevOps", "https://docs.mender.io/", "mixed", "ota,updates,embedded,robustness", "",
     "Over-the-air update manager for embedded Linux with atomic rollback.",
     "Менеджер OTA-обновлений для встраиваемого Linux с атомарным откатом.",
     "Its A/B partition scheme means a failed update reboots into the previous working image automatically."),

    # ---------- IoT платформы и брокеры ----------
    ("lib-home-assistant", "Home Assistant", "Умный дом и IoT", "https://developers.home-assistant.io/", "openSource", "smart-home,automation,python,integrations", "",
     "Open-source home automation platform with thousands of device integrations.",
     "Открытая платформа домашней автоматизации с тысячами интеграций устройств.",
     "Its local-first design keeps automations working when the internet or a vendor cloud goes down."),
    ("lib-zigbee2mqtt", "Zigbee2MQTT", "Умный дом и IoT", "https://www.zigbee2mqtt.io/guide/getting-started/", "openSource", "zigbee,mqtt,smart-home,bridge", "",
     "Bridges Zigbee devices onto MQTT, freeing them from vendor hubs.",
     "Мост Zigbee-устройств в MQTT, освобождающий их от вендорских хабов.",
     "Removes the vendor cloud from the loop entirely, which is the main reason to run it over a stock hub."),
    ("lib-emqx", "EMQX", "Умный дом и IoT", "https://docs.emqx.com/en/emqx/latest/", "openSource", "mqtt,broker,clustered,scalable", "",
     "Distributed MQTT broker built to handle millions of concurrent device connections.",
     "Распределённый MQTT-брокер, рассчитанный на миллионы одновременных подключений устройств.",
     "Clustering and rule engine are what you move to Mosquitto from once device count grows."),
    ("lib-vernemq", "VerneMQ", "Умный дом и IoT", "https://docs.vernemq.com/", "openSource", "mqtt,broker,erlang,clustered", "",
     "Erlang-based clustered MQTT broker with a plugin system for auth and routing.",
     "Кластерный MQTT-брокер на Erlang с системой плагинов для аутентификации и маршрутизации.",
     "The BEAM runtime gives it graceful degradation under connection storms rather than hard failure."),
    ("lib-thingsboard", "ThingsBoard", "Умный дом и IoT", "https://thingsboard.io/docs/", "openSource", "iot,dashboards,telemetry,rules", "",
     "IoT platform for device management, telemetry collection and dashboards.",
     "IoT-платформа для управления устройствами, сбора телеметрии и дашбордов.",
     "Its rule engine handles alerting and transformation server-side, keeping device firmware simple."),
    ("lib-opcua", "OPC UA (open62541)", "Умный дом и IoT", "https://www.open62541.org/documentation/", "openSource", "opc-ua,industrial,protocol,c", "",
     "Open-source implementation of the OPC UA industrial automation protocol.",
     "Открытая реализация промышленного протокола автоматизации OPC UA.",
     "The protocol of record for factory-floor equipment — expect it in any industrial integration."),
    ("lib-zenoh", "Zenoh", "Умный дом и IoT", "https://zenoh.io/docs/", "openSource", "pubsub,robotics,edge,protocol", "",
     "Pub/sub, storage and query protocol unifying cloud, edge and robotics data flows.",
     "Протокол pub/sub, хранения и запросов, объединяющий потоки данных облака, edge и робототехники.",
     "Lower overhead than MQTT or DDS on constrained links, which is why ROS 2 adopted it as a transport."),
    ("lib-blynk", "Blynk", "Умный дом и IoT", "https://docs.blynk.io/", "freeTier", "iot,mobile-app,dashboards,no-code", "",
     "Builds mobile apps for IoT devices with a drag-and-drop widget interface.",
     "Создаёт мобильные приложения для IoT-устройств через drag-and-drop интерфейс виджетов.",
     "Fastest path to a phone UI for a hobby device, without writing any mobile code."),
    ("lib-golioth", "Golioth", "Умный дом и IoT", "https://docs.golioth.io/", "freeTier", "iot,device-management,zephyr,cloud", "",
     "Device management cloud for embedded firmware, with first-class Zephyr support.",
     "Облако управления устройствами для встраиваемой прошивки с полноценной поддержкой Zephyr.",
     "Handles OTA, logging and settings so firmware teams do not build a device backend themselves."),
    ("lib-losant", "Losant", "Умный дом и IoT", "https://docs.losant.com/", "freeTier", "iot,workflows,dashboards,enterprise", "",
     "Enterprise IoT platform with a visual workflow engine and end-user dashboards.",
     "Корпоративная IoT-платформа с визуальным движком workflow и дашбордами для конечных пользователей.",
     "Its white-label experience layer is what separates it from purely internal telemetry platforms."),

    # ---------- Потоковая обработка ----------
    ("lib-kafka-streams", "Kafka Streams", "Очереди и события", "https://kafka.apache.org/documentation/streams/", "openSource", "kafka,streaming,java,stateful", "",
     "Java library for stateful stream processing directly on Kafka topics.",
     "Java-библиотека для stateful-обработки потоков прямо поверх топиков Kafka.",
     "It is a library, not a cluster — your app is the processor, which removes a whole deployment tier."),
    ("lib-debezium", "Debezium", "Data engineering", "https://debezium.io/documentation/", "openSource", "cdc,kafka,databases,change-events", "",
     "Change data capture streaming database row changes into Kafka as events.",
     "Change data capture: потоковая передача изменений строк базы данных в Kafka как событий.",
     "Reads the database's replication log, so it captures every change without polling or triggers."),
    ("lib-benthos", "Redpanda Connect (Benthos)", "Очереди и события", "https://docs.redpanda.com/redpanda-connect/about/", "openSource", "stream-processing,yaml,connectors,glue", "",
     "Declarative stream processor connecting queues, databases and APIs with YAML pipelines.",
     "Декларативный потоковый процессор, связывающий очереди, базы и API через YAML-пайплайны.",
     "Replaces a surprising amount of bespoke glue-code services with one config file and no deploy pipeline."),
]
