# -*- coding: utf-8 -*-
"""Stage 5 MCP + skills pack C."""

MCPS_5C = [
    ("mcp-gitlab-official", "GitLab MCP (official)", "Git и совместная работа", "https://docs.gitlab.com/user/gitlab_duo/model_context_protocol/mcp_server/", "openSource", "gitlab,git,official,issues", "",
     "Official server for GitLab projects, issues, merge requests and pipelines.",
     "Официальный сервер для проектов, issues, merge request и пайплайнов GitLab.",
     "Works against self-managed GitLab instances too — point it at your own host, not just gitlab.com."),
    ("mcp-bitbucket-community", "Bitbucket MCP (community)", "Git и совместная работа", "https://github.com/aashari/mcp-server-atlassian-bitbucket", "openSource", "bitbucket,git,atlassian,community", "npx -y @aashari/mcp-server-atlassian-bitbucket",
     "Community server for Bitbucket repositories, pull requests and pipelines.",
     "Сервер сообщества для репозиториев, pull request и пайплайнов Bitbucket.",
     "Useful specifically for teams still on Bitbucket rather than GitHub or GitLab."),
    ("mcp-jira-community", "Jira MCP (community)", "Git и совместная работа", "https://github.com/sooperset/mcp-atlassian", "openSource", "jira,confluence,atlassian,community", "uvx mcp-atlassian",
     "Community server covering both Jira issues and Confluence pages in one integration.",
     "Сервер сообщества, покрывающий и issues Jira, и страницы Confluence в одной интеграции.",
     "Read-only mode is the sane default — Jira write access from an agent needs careful workflow review first."),
    ("mcp-circleci-official", "CircleCI MCP (official)", "Разработка и DevOps", "https://circleci.com/docs/mcp-server/", "freeTier", "circleci,ci,official,pipelines", "",
     "Official server for CircleCI pipeline status, logs and configuration.",
     "Официальный сервер для статуса пайплайнов, логов и конфигурации CircleCI.",
     "Let the agent read a failed build's logs directly instead of pasting the CI output into the chat."),
    ("mcp-buildkite-official", "Buildkite MCP (official)", "Разработка и DevOps", "https://buildkite.com/docs/apis/mcp-server", "freeTier", "buildkite,ci,official,pipelines", "",
     "Official server for Buildkite pipeline builds, jobs and logs.",
     "Официальный сервер для сборок, задач и логов пайплайнов Buildkite.",
     "Combine with a PreToolUse hook if you want to gate which pipelines an agent can trigger."),
    ("mcp-digitalocean-official", "DigitalOcean MCP (official)", "Облако и деплой", "https://github.com/digitalocean/digitalocean-mcp", "openSource", "digitalocean,deploy,official,droplets", "",
     "Official server for managing DigitalOcean droplets, apps and databases.",
     "Официальный сервер для управления droplets, приложениями и базами данных DigitalOcean.",
     "Scope the API token narrowly — a full-access token lets an agent delete production droplets."),
    ("mcp-fly-io-community", "Fly.io MCP (community)", "Облако и деплой", "https://github.com/superfly/fly-mcp", "openSource", "flyio,deploy,community,logs", "",
     "Community server for Fly.io app deployment, logs and machine management.",
     "Сервер сообщества для деплоя приложений, логов и управления машинами Fly.io.",
     "Machine start/stop tools are destructive by nature — review them before granting write access."),
    ("mcp-fireworks-ai", "Fireworks AI MCP", "AI и агенты", "https://docs.fireworks.ai/tools-sdks/mcp/overview", "freeTier", "fireworks,inference,models,official", "",
     "Official server exposing Fireworks-hosted open model inference as agent tools.",
     "Официальный сервер, отдающий инференс открытых моделей на Fireworks как инструменты агента.",
     "Useful when an agent needs to delegate a sub-task to a cheaper open-weight model mid-workflow."),
    ("mcp-replicate-official", "Replicate MCP", "Изображения и дизайн", "https://replicate.com/docs/reference/mcp", "mixed", "replicate,models,official,generation", "",
     "Official server for running any Replicate-hosted model — image, video, audio — from an agent.",
     "Официальный сервер для запуска любой модели на Replicate — изображения, видео, аудио — из агента.",
     "Check the per-model cost before looping an agent over many generations — costs vary widely by model."),
    ("mcp-convex-official", "Convex MCP (official)", "Инфраструктура MCP", "https://docs.convex.dev/ai/using-cursor#mcp-server", "openSource", "convex,database,official,realtime", "",
     "Official server for managing Convex functions, data and deployments.",
     "Официальный сервер для управления функциями, данными и деплоями Convex.",
     "Convex's own schema validation means an agent's bad write attempt fails loudly rather than corrupting data."),
]

SKILLS_5C = [
    ("skill-claude-skills-marketplace", "Claude Skills Marketplace", "Каталоги skills", "https://claude.com/marketplace", "free", "skills,plugins,marketplace,discovery", "",
     "Browse and install skills and plugins published for Claude and Claude Code.",
     "Просмотр и установка skills и плагинов, опубликованных для Claude и Claude Code.",
     "Check here before writing a skill from scratch — a maintained one for the same task may already exist."),
    ("skill-claude-code-statusline", "Claude Code Status Line", "Установка и миграция", "https://docs.claude.com/en/docs/claude-code/statusline", "free", "claude-code,customization,ui,statusline", "",
     "Customize the terminal status line shown during a Claude Code session.",
     "Настройка строки статуса терминала, отображаемой во время сессии Claude Code.",
     "Surface the current git branch and model name here — the two facts you check most often mid-session."),
    ("skill-claude-code-permissions", "Claude Code Permission Modes", "Гайды и практики", "https://docs.claude.com/en/docs/claude-code/iam", "free", "claude-code,permissions,security,modes", "",
     "The permission model: ask/allow/deny rules, and the difference between interactive modes.",
     "Модель разрешений: правила ask/allow/deny и разница между интерактивными режимами.",
     "Start new, unfamiliar codebases in the default ask-first mode before switching to a more autonomous one."),
    ("skill-claude-code-troubleshooting", "Claude Code Troubleshooting", "Гайды и практики", "https://docs.claude.com/en/docs/claude-code/troubleshooting", "free", "claude-code,debugging,common-issues", "",
     "Common Claude Code failure modes and their fixes: auth, permissions, performance.",
     "Типичные сбои Claude Code и их решения: авторизация, разрешения, производительность.",
     "Check the diagnostic command listed here before assuming a bug — most issues are environment, not the tool."),
    ("skill-writing-good-claude-md", "Writing a Good CLAUDE.md", "Гайды и практики", "https://docs.claude.com/en/docs/claude-code/best-practices", "free", "claude-md,conventions,documentation,claude-code", "",
     "Practical guidance on what belongs in a project's CLAUDE.md and what doesn't.",
     "Практические советы, что должно быть в CLAUDE.md проекта, а что нет.",
     "Document the non-obvious constraints (why, not what) — obvious things from reading the code don't need repeating."),
    ("skill-token-efficient-tools", "Token-Efficient Tool Use", "Гайды и практики", "https://docs.claude.com/en/docs/agents-and-tools/tool-use/token-efficient-tool-use", "free", "tools,tokens,efficiency,claude", "",
     "Reduces token overhead from tool-use turns without changing tool behavior.",
     "Снижает расход токенов на ходах с вызовом инструментов без изменения поведения инструментов.",
     "Worth enabling by default for any agent that makes many small tool calls in a loop."),
]
