# -*- coding: utf-8 -*-
"""Stage 5 library pack Z: component libraries, headless primitives, CSS-in-JS, design systems."""

LIBS_5Z = [
    # ---------- Headless примитивы ----------
    ("lib-radix-ui", "Radix UI", "UI и frontend", "https://www.radix-ui.com/primitives/docs/overview/introduction", "openSource", "react,headless,accessible,primitives", "npm i radix-ui",
     "Unstyled, accessible React primitives handling focus, keyboard and ARIA correctly.",
     "Нестилизованные доступные React-примитивы, корректно обрабатывающие фокус, клавиатуру и ARIA.",
     "The accessibility work in a dialog or combobox is the hard part — this is why shadcn/ui builds on it."),
    ("lib-zag-js", "Zag.js", "UI и frontend", "https://zagjs.com/", "openSource", "state-machines,headless,framework-agnostic,accessible", "",
     "Component behaviour modelled as state machines, usable from React, Vue or Solid.",
     "Поведение компонентов как конечные автоматы, доступно из React, Vue и Solid.",
     "One machine drives every framework binding, so component behaviour cannot drift between them."),
    ("lib-melt-ui", "Melt UI", "UI и frontend", "https://melt-ui.com/docs/introduction", "openSource", "svelte,headless,builders,accessible", "npm i @melt-ui/svelte",
     "Headless, accessible component builders for Svelte.",
     "Headless-конструкторы доступных компонентов для Svelte.",
     "Builders return attribute spreads rather than components, which keeps your markup fully yours."),
    ("lib-kobalte", "Kobalte", "UI и frontend", "https://kobalte.dev/docs/core/overview/introduction", "openSource", "solidjs,headless,accessible,primitives", "npm i @kobalte/core",
     "Accessible unstyled component primitives for SolidJS.",
     "Доступные нестилизованные примитивы компонентов для SolidJS.",
     "The Solid equivalent of Radix — same design goals, framework-native reactivity."),

    # ---------- Компонентные библиотеки ----------
    ("lib-heroui", "HeroUI", "UI и frontend", "https://www.heroui.com/docs/guide/introduction", "openSource", "react,tailwind,components,themeable", "npm i @heroui/react",
     "React component library built on Tailwind, formerly NextUI.",
     "Библиотека React-компонентов на Tailwind, ранее известная как NextUI.",
     "Themeable through Tailwind config rather than a separate theme object, which keeps styling in one place."),
    ("lib-flowbite", "Flowbite", "UI и frontend", "https://flowbite.com/docs/getting-started/introduction/", "openSource", "tailwind,components,html,multi-framework", "npm i flowbite",
     "Tailwind component library with React, Vue and Svelte bindings.",
     "Библиотека компонентов Tailwind с биндингами для React, Vue и Svelte.",
     "The plain-HTML variants work in server-rendered templates with no JavaScript framework at all."),
    ("lib-preline", "Preline UI", "UI и frontend", "https://preline.co/docs/index.html", "openSource", "tailwind,components,plugin,html", "npm i preline",
     "Tailwind CSS component set delivered as a plugin with interactive behaviours.",
     "Набор компонентов Tailwind CSS в виде плагина с интерактивным поведением.",
     "Its JavaScript layer is optional — the markup works statically if you only need the styling."),
    ("lib-primereact", "PrimeReact", "UI и frontend", "https://primereact.org/installation/", "openSource", "react,components,datatable,enterprise", "npm i primereact",
     "Large React component suite including a very capable data table.",
     "Большой набор React-компонентов, включая весьма мощную таблицу данных.",
     "Its DataTable covers filtering, grouping and virtual scroll out of the box, which saves weeks."),
    ("lib-vuetify", "Vuetify", "UI и frontend", "https://vuetifyjs.com/en/", "openSource", "vue,material-design,components,comprehensive", "npm i vuetify",
     "Comprehensive Material Design component framework for Vue.",
     "Полный фреймворк компонентов Material Design для Vue.",
     "Opinionated Material styling is a poor fit if you have your own design language — check that first."),
    ("lib-quasar", "Quasar", "UI и frontend", "https://quasar.dev/docs", "openSource", "vue,components,multi-platform,cli", "npm i quasar",
     "Vue framework targeting web, mobile and desktop from one component codebase.",
     "Vue-фреймворк, собирающий web, мобильные и desktop-приложения из одной кодовой базы компонентов.",
     "Its multi-target build story is the differentiator, not just the component set."),
    ("lib-naive-ui", "Naive UI", "UI и frontend", "https://www.naiveui.com/en-US/os-theme/docs/introduction", "openSource", "vue,typescript,themeable,tree-shakeable", "npm i naive-ui",
     "TypeScript-first Vue 3 component library with deep runtime theming.",
     "Библиотека компонентов Vue 3 с приоритетом TypeScript и глубокой рантайм-темизацией.",
     "Themes are plain objects adjusted at runtime, so a dark mode toggle needs no CSS rebuild."),
    ("lib-element-plus", "Element Plus", "UI и frontend", "https://element-plus.org/en-US/guide/design.html", "openSource", "vue,components,admin,mature", "npm i element-plus",
     "Mature Vue 3 component library widely used for admin and internal tools.",
     "Зрелая библиотека компонентов Vue 3, широко используемая для админок и внутренних инструментов.",
     "Its form and table components are tuned for dense data-entry screens rather than marketing pages."),

    # ---------- Дизайн-системы ----------
    ("lib-carbon-design", "Carbon Design System", "Дизайн-системы", "https://carbondesignsystem.com/", "openSource", "ibm,design-system,components,enterprise", "",
     "IBM's open-source design system with components, tokens and guidelines.",
     "Открытая дизайн-система IBM с компонентами, токенами и руководствами.",
     "The written guidelines are useful even if you never use the components — they explain the reasoning."),
    ("lib-fluent-ui", "Fluent UI", "Дизайн-системы", "https://react.fluentui.dev/", "openSource", "microsoft,design-system,react,components", "npm i @fluentui/react-components",
     "Microsoft's design system and React components used across Microsoft 365.",
     "Дизайн-система Microsoft и React-компоненты, используемые в Microsoft 365.",
     "The obvious pick if your app lives inside Teams or Office and should feel native there."),
    ("lib-adobe-spectrum", "Adobe Spectrum", "Дизайн-системы", "https://spectrum.adobe.com/", "openSource", "adobe,design-system,accessible,tokens", "",
     "Adobe's design system, backed by the React Aria accessibility primitives.",
     "Дизайн-система Adobe, построенная на примитивах доступности React Aria.",
     "React Aria underneath it is arguably the more valuable export — usable without Spectrum's visuals."),
    ("lib-shopify-polaris", "Shopify Polaris", "Дизайн-системы", "https://polaris.shopify.com/", "openSource", "shopify,design-system,admin,react", "npm i @shopify/polaris",
     "Shopify's design system for building apps that live inside the Shopify admin.",
     "Дизайн-система Shopify для приложений, встроенных в админку Shopify.",
     "Required in practice for embedded Shopify apps — merchants expect the native admin look."),
    ("lib-stencil", "Stencil", "UI и frontend", "https://stenciljs.com/docs/introduction", "openSource", "web-components,compiler,typescript,output-targets", "npm i @stencil/core",
     "Compiler that generates standards-based web components with framework wrappers.",
     "Компилятор, генерирующий стандартные веб-компоненты с обёртками под фреймворки.",
     "Its output targets emit React and Vue wrappers automatically from one component source."),

    # ---------- Стилизация ----------
    ("lib-stitches", "Stitches", "UI и frontend", "https://stitches.dev/docs/introduction", "openSource", "css-in-js,variants,near-zero-runtime,typed", "npm i @stitches/react",
     "CSS-in-JS with a first-class variants API and near-zero runtime.",
     "CSS-in-JS с полноценным API вариантов и почти нулевым рантаймом.",
     "Development has stopped — treat it as a reference for the variants pattern rather than a new dependency."),
    ("lib-linaria", "Linaria", "UI и frontend", "https://linaria.dev/", "openSource", "css-in-js,zero-runtime,build-time,tagged-templates", "npm i @linaria/core",
     "Zero-runtime CSS-in-JS extracting styles to real CSS files at build time.",
     "CSS-in-JS без рантайма: извлекает стили в настоящие CSS-файлы на этапе сборки.",
     "Familiar tagged-template syntax without shipping a styling runtime to the browser."),
    ("lib-emotion", "Emotion", "UI и frontend", "https://emotion.sh/docs/introduction", "openSource", "css-in-js,runtime,react,composable", "npm i @emotion/react",
     "Popular runtime CSS-in-JS library with composable style objects.",
     "Популярная рантайм CSS-in-JS библиотека с композируемыми объектами стилей.",
     "Runtime style injection conflicts with React Server Components — check that before adopting it now."),
    ("lib-styled-components", "styled-components", "UI и frontend", "https://styled-components.com/docs", "openSource", "css-in-js,react,tagged-templates,theming", "npm i styled-components",
     "The library that popularised CSS-in-JS via tagged template literals.",
     "Библиотека, популяризировавшая CSS-in-JS через тегированные шаблонные литералы.",
     "Now in maintenance mode — the maintainers themselves point new projects at build-time alternatives."),
    ("lib-cva", "class-variance-authority", "UI и frontend", "https://cva.style/docs", "openSource", "variants,tailwind,typed,classnames", "npm i class-variance-authority",
     "Builds type-safe class name variants, the standard companion to Tailwind components.",
     "Строит типобезопасные варианты имён классов — стандартный спутник Tailwind-компонентов.",
     "Turns a sprawl of conditional class strings into one declarative variant table."),
    ("lib-tailwind-variants", "Tailwind Variants", "UI и frontend", "https://www.tailwind-variants.org/", "openSource", "tailwind,variants,slots,conflict-resolution", "npm i tailwind-variants",
     "Variant API for Tailwind with slots and automatic class conflict resolution.",
     "API вариантов для Tailwind со слотами и автоматическим разрешением конфликтов классов.",
     "Conflict resolution means a passed-in override actually wins, which raw string concatenation cannot guarantee."),
    ("lib-clsx", "clsx", "UI и frontend", "https://github.com/lukeed/clsx", "openSource", "classnames,tiny,utility,conditional", "npm i clsx",
     "Tiny utility for building conditional class name strings.",
     "Крошечная утилита для построения условных строк имён классов.",
     "Under 300 bytes and used almost universally — a faster drop-in for the older classnames package."),

    # ---------- Разработка компонентов ----------
    ("lib-ladle", "Ladle", "UI и frontend", "https://ladle.dev/docs/", "openSource", "stories,vite,fast,storybook-alternative", "npm i @ladle/react",
     "Fast Vite-based environment for developing React components in isolation.",
     "Быстрая среда на Vite для разработки React-компонентов в изоляции.",
     "Reads Storybook's CSF story format, so migrating existing stories is mostly a config change."),
    ("lib-histoire", "Histoire", "UI и frontend", "https://histoire.dev/", "openSource", "stories,vite,vue,svelte", "npm i histoire",
     "Vite-native component story environment focused on Vue and Svelte.",
     "Нативная для Vite среда историй компонентов с фокусом на Vue и Svelte.",
     "Considerably lighter than Storybook if you only need isolated component development."),
]
