# -*- coding: utf-8 -*-
"""Stage 5 pricing pack F: scraping infrastructure, SEO data, technology profiling."""

PAID_5F = [
("paid-zyte","Zyte (pricing)","Браузер и автоматизация","https://www.zyte.com/pricing/","paid","scraping,pricing,usage,api",
 "Scraping platform billed by request volume and extraction complexity.",
 "Платформа скрейпинга с оплатой по объёму запросов и сложности извлечения.",
 "Automatic extraction costs more per request than raw fetching — enable it only where it earns its keep.",
 "usage","from ~$100 per month","free trial credit","https://www.zyte.com/pricing/"),
("paid-oxylabs","Oxylabs (pricing)","Браузер и автоматизация","https://oxylabs.io/pricing","paid","proxies,pricing,per-gb,residential",
 "Proxy network billed per gigabyte of traffic, varying by proxy type.",
 "Прокси-сеть с оплатой за гигабайт трафика, ставка зависит от типа прокси.",
 "Residential traffic costs many times datacenter traffic — route only what genuinely needs it.",
 "usage","from ~$4 per GB (residential)","free trial","https://oxylabs.io/pricing"),
("paid-smartproxy","Decodo (pricing)","Браузер и автоматизация","https://decodo.com/pricing","paid","proxies,pricing,per-gb,residential",
 "Proxy pools billed per gigabyte with lower entry pricing than enterprise providers.",
 "Прокси-пулы с оплатой за гигабайт и более низким порогом входа, чем у корпоративных провайдеров.",
 "Cheaper per gigabyte, with smaller pools that get blocked more often on well-defended sites.",
 "usage","from ~$1.5 per GB","free trial","https://decodo.com/pricing"),
("paid-dataforseo","DataForSEO (pricing)","Поиск и retrieval","https://dataforseo.com/pricing","paid","seo,pricing,per-request,prepaid",
 "SEO data sold as prepaid credits consumed per API request.",
 "SEO-данные в виде предоплаченных кредитов, расходуемых за каждый API-запрос.",
 "Per-request pricing beats seat-based SEO suites when you are building your own tooling.",
 "credits","from ~$0.0006 per SERP request","free trial credit","https://dataforseo.com/pricing"),
("paid-ahrefs","Ahrefs (pricing)","Поиск и retrieval","https://ahrefs.com/pricing","paid","seo,pricing,subscription,api-units",
 "Backlink and keyword data requiring a subscription plus API unit purchases.",
 "Данные об обратных ссылках и ключевых словах: подписка плюс покупка API-юнитов.",
 "API access is billed on top of the base subscription, which surprises most first-time buyers.",
 "subscription","from ~$129 per month plus API units","free webmaster tools for own site","https://ahrefs.com/pricing"),
("paid-semrush","Semrush (pricing)","Поиск и retrieval","https://www.semrush.com/prices/","paid","seo,pricing,subscription,api-add-on",
 "Competitive research suite with API access sold as a paid add-on.",
 "Набор конкурентного анализа с доступом к API в виде платного дополнения.",
 "The API add-on costs more than the base plan, so budget for both before designing an integration.",
 "subscription","from ~$139 per month plus API add-on","free limited account","https://www.semrush.com/prices/"),
("paid-moz","Moz (pricing)","Поиск и retrieval","https://moz.com/products/api/pricing","paid","seo,pricing,per-row,subscription",
 "Link metrics API billed by rows of data returned.",
 "API метрик ссылок с оплатой по числу возвращённых строк данных.",
 "Row-based billing makes bulk domain scoring predictable to estimate in advance.",
 "subscription","from ~$99 per month","free tier with limited rows","https://moz.com/products/api/pricing"),
("paid-builtwith","BuiltWith (pricing)","Открытые данные","https://builtwith.com/pricing","paid","technology-profiling,pricing,subscription,lists",
 "Technology profiling billed monthly, with technology lists on higher tiers.",
 "Профилирование технологий с месячной оплатой; списки по технологиям — на старших тарифах.",
 "Free lookup for a single site; the paid value is bulk lists of every site using a technology.",
 "subscription","from ~$295 per month","free single-site lookup","https://builtwith.com/pricing"),
("paid-wappalyzer","Wappalyzer (pricing)","Открытые данные","https://www.wappalyzer.com/pricing/","paid","technology-detection,pricing,credits,lookups",
 "Technology detection sold as monthly lookup credits.",
 "Определение технологий в виде месячных кредитов на проверки.",
 "Its detection rules are open source, so self-hosting is a real option for high volumes.",
 "credits","from ~$149 per month","free browser extension","https://www.wappalyzer.com/pricing/"),
("paid-stainless","Stainless (pricing)","Backend и API","https://www.stainless.com/pricing","paid","sdk,pricing,languages,subscription",
 "SDK generation billed monthly by the number of target languages.",
 "Генерация SDK с месячной оплатой по числу целевых языков.",
 "Worth it when SDK quality is customer-facing; open-source generators cover internal clients fine.",
 "subscription","from ~$250 per month","free tier for one language","https://www.stainless.com/pricing"),
("paid-sidekiq-enterprise","Sidekiq Enterprise (pricing)","Очереди и события","https://sidekiq.org/products/enterprise.html","paid","ruby,pricing,subscription,per-thread",
 "Commercial Sidekiq tier sold as an annual subscription scaled to worker threads.",
 "Коммерческий уровень Sidekiq по годовой подписке, масштабируемой под число рабочих потоков.",
 "The free Sidekiq covers most applications — pay when job loss on restart actually costs money.",
 "subscription","from ~$229 per month","free open-source edition","https://sidekiq.org/products/enterprise.html"),
("paid-aws-step-functions","AWS Step Functions (pricing)","Очереди и события","https://aws.amazon.com/step-functions/pricing/","paid","aws,pricing,per-transition,serverless",
 "Standard workflows billed per state transition; Express workflows billed by duration.",
 "Standard-workflow оплачиваются за переход состояния, Express — по длительности выполнения.",
 "Express workflows are orders of magnitude cheaper for short high-volume runs — pick the type deliberately.",
 "usage","from ~$0.025 per 1000 state transitions","free tier of 4000 transitions/month","https://aws.amazon.com/step-functions/pricing/"),
("paid-azure-durable-functions","Azure Durable Functions (pricing)","Очереди и события","https://azure.microsoft.com/en-us/pricing/details/functions/","paid","azure,pricing,executions,storage",
 "Billed as ordinary Azure Functions executions plus the storage its state uses.",
 "Оплачивается как обычные выполнения Azure Functions плюс хранилище, используемое для состояния.",
 "The storage transactions behind replays are a real cost line that surprises people at scale.",
 "usage","from ~$0.20 per million executions","free grant of 1M executions/month","https://azure.microsoft.com/en-us/pricing/details/functions/"),
("paid-google-cloud-workflows","Google Cloud Workflows (pricing)","Очереди и события","https://cloud.google.com/workflows/pricing","paid","gcp,pricing,per-step,serverless",
 "Billed per workflow step executed, with internal and external steps priced differently.",
 "Оплата за выполненный шаг workflow, внутренние и внешние шаги тарифицируются по-разному.",
 "External HTTP steps cost several times internal ones — batch calls where the logic allows.",
 "usage","from ~$0.01 per 1000 internal steps","free tier of 5000 steps/month","https://cloud.google.com/workflows/pricing"),
("paid-tonic-ai","Tonic.ai (pricing)","Data engineering","https://www.tonic.ai/pricing","paid","synthetic-data,pricing,enterprise,custom",
 "Synthetic and anonymized data platform sold on enterprise contracts.",
 "Платформа синтетических и анонимизированных данных по корпоративным контрактам.",
 "Priced for regulated organizations; the open-source anonymizers cover ordinary staging needs.",
 "custom","custom quote","free trial","https://www.tonic.ai/pricing"),
("paid-datagrip","DataGrip (pricing)","Базы данных и ORM","https://www.jetbrains.com/datagrip/buy/","paid","ide,pricing,subscription,per-user",
 "Database IDE sold as a per-user annual subscription.",
 "IDE баз данных по годовой подписке на пользователя.",
 "Included in the JetBrains All Products pack, which is cheaper if you already use another of their IDEs.",
 "subscription","from ~$9.99 per user per month","free 30-day trial","https://www.jetbrains.com/datagrip/buy/"),
]
