# -*- coding: utf-8 -*-
"""Stage 5 MCP + skills pack: more servers and skills for the 4-5x expansion."""

MCPS_5 = [
    ("mcp-notion-official", "Notion MCP (official)", "Инфраструктура MCP", "https://github.com/makenotion/notion-mcp-server", "openSource", "notion,docs,database,official", "npx -y @notionhq/notion-mcp-server",
     "Official Notion server: pages, databases and blocks as MCP tools.",
     "Официальный сервер Notion: страницы, базы данных и блоки как MCP-инструменты.",
     "Scope the integration to specific pages in Notion's UI — it otherwise sees the whole workspace."),
    ("mcp-supabase-official", "Supabase MCP (official)", "Инфраструктура MCP", "https://github.com/supabase-community/supabase-mcp", "openSource", "supabase,postgres,database,official", "npx -y @supabase/mcp-server-supabase@latest",
     "Manage Supabase projects, tables and migrations through MCP.",
     "Управление проектами, таблицами и миграциями Supabase через MCP.",
     "Read-only mode exists — start there before granting an agent schema-write access."),
    ("mcp-figma-official", "Figma MCP (official)", "Инфраструктура MCP", "https://help.figma.com/hc/en-us/articles/32132100833559", "freeTier", "figma,design,official,dev-mode", "",
     "Official Figma Dev Mode server exposing selected frames as structured design data.",
     "Официальный сервер Figma Dev Mode, отдающий выбранные фреймы как структурированные данные дизайна.",
     "Select a specific frame before asking the agent to implement it — full-file context is too broad."),
    ("mcp-linear-official", "Linear MCP (official)", "Инфраструктура MCP", "https://linear.app/docs/mcp", "freeTier", "linear,issues,project-management,official", "",
     "Official Linear server: issues, projects and cycles as agent tools.",
     "Официальный сервер Linear: issues, проекты и циклы как инструменты агента.",
     "Let the agent file issues from a debugging session directly instead of copy-pasting notes."),
    ("mcp-cloudflare-official", "Cloudflare MCP (official)", "Инфраструктура MCP", "https://github.com/cloudflare/mcp-server-cloudflare", "openSource", "cloudflare,workers,dns,official", "",
     "Official servers for Workers, KV, R2, D1 and DNS management.",
     "Официальные серверы для Workers, KV, R2, D1 и управления DNS.",
     "Each Cloudflare product ships its own focused server — install only the ones you actually use."),
    ("mcp-docker-official", "Docker MCP (official)", "Инфраструктура MCP", "https://docs.docker.com/ai/mcp-catalog-and-toolkit/", "openSource", "docker,containers,official,catalog", "",
     "Docker's own MCP toolkit and curated server catalog, run via Docker Desktop.",
     "Официальный MCP-тулкит и каталог серверов Docker, запускается через Docker Desktop.",
     "Servers run in containers by default, which sandboxes them from the host filesystem."),
    ("mcp-vercel-official", "Vercel MCP (official)", "Инфраструктура MCP", "https://vercel.com/docs/mcp", "freeTier", "vercel,deploy,official,logs", "",
     "Official server for Vercel deployments, logs and project configuration.",
     "Официальный сервер для деплоев, логов и конфигурации проектов Vercel.",
     "Pull deployment logs directly into the agent's context instead of copy-pasting from the dashboard."),
    ("mcp-mongodb-official", "MongoDB MCP (official)", "Инфраструктура MCP", "https://www.mongodb.com/docs/mcp-server/", "openSource", "mongodb,database,official,atlas", "npx -y mongodb-mcp-server",
     "Official server for querying and managing MongoDB and Atlas clusters.",
     "Официальный сервер для запросов и управления кластерами MongoDB и Atlas.",
     "Point it at a read-only user for exploration; grant write access only when you mean it."),
    ("mcp-neon-official", "Neon MCP (official)", "Инфраструктура MCP", "https://neon.tech/docs/ai/neon-mcp-server", "freeTier", "neon,postgres,serverless,official", "",
     "Official server for Neon's serverless Postgres: branches, queries, migrations.",
     "Официальный сервер для serverless Postgres от Neon: ветки, запросы, миграции.",
     "Have the agent branch the database before a risky migration — branches are cheap and instant."),
    ("mcp-perplexity", "Perplexity MCP", "Инфраструктура MCP", "https://github.com/ppl-ai/modelcontextprotocol", "freeTier", "search,perplexity,answers,web", "",
     "Perplexity's search-and-answer API exposed as an MCP tool.",
     "API поиска и ответов Perplexity в виде MCP-инструмента.",
     "Useful when an agent needs a synthesized answer with citations, not just raw search results."),
    ("mcp-stripe-official", "Stripe MCP (official)", "Инфраструктура MCP", "https://docs.stripe.com/mcp", "freeTier", "stripe,payments,official,testing", "",
     "Official server for Stripe: customers, payments, subscriptions as agent tools.",
     "Официальный сервер Stripe: клиенты, платежи, подписки как инструменты агента.",
     "Point it at a test-mode key while iterating — every tool call is a live API request otherwise."),
    ("mcp-render-official", "Render MCP (official)", "Инфраструктура MCP", "https://render.com/docs/mcp-server", "freeTier", "render,deploy,official,logs", "",
     "Official server for Render services, deploys and logs.",
     "Официальный сервер для сервисов, деплоев и логов Render.",
     "Ask the agent to fetch the latest deploy log directly instead of pasting it in by hand."),
    ("mcp-brightdata", "Bright Data MCP", "Браузер и автоматизация", "https://github.com/luminati-io/brightdata-mcp", "paid", "scraping,proxy,browser,official", "",
     "Web scraping and proxy infrastructure exposed as MCP tools for agent-driven browsing.",
     "Инфраструктура веб-скрапинга и прокси в виде MCP-инструментов для браузинга агентом.",
     "Reach for this specifically for sites that block plain headless browsers — the residential proxy pool helps."),
    ("mcp-e2b-2", "E2B Code Interpreter MCP", "Браузер и автоматизация", "https://e2b.dev/docs/legacy/hosting/mcp-server", "freeTier", "sandbox,code-execution,e2b,python", "",
     "Runs agent-generated Python in an isolated cloud sandbox with file and package support.",
     "Запускает сгенерированный Python-код агента в изолированной облачной песочнице с файлами и пакетами.",
     "State persists across calls within a session, so an agent can build up a notebook-like workflow."),
    ("mcp-context7-2", "Context7 (community mirror)", "Документация и контекст", "https://github.com/upstash/context7", "freeTier", "docs,versions,context,community", "",
     "Up-to-date library documentation pulled into context by exact version, avoiding stale training data.",
     "Актуальная документация библиотек в контекст по точной версии — без устаревших данных обучения.",
     "Pin the library version in the query when a project depends on an older release."),
    ("mcp-graphlit", "Graphlit MCP", "Память и знания", "https://github.com/graphlit/graphlit-mcp-server", "freeTier", "knowledge-graph,ingestion,rag,memory", "",
     "Ingests documents, feeds and media into a queryable knowledge graph for agents.",
     "Загружает документы, фиды и медиа в графовую базу знаний, доступную агенту для запросов.",
     "Point it at a whole document set once, then let the agent query instead of re-reading files each turn."),
    ("mcp-todoist", "Todoist MCP", "Планирование и календари", "https://github.com/abhiz123/todoist-mcp-server", "freeTier", "todoist,tasks,productivity,community", "npx -y @abhiz123/todoist-mcp-server",
     "Create, complete and query Todoist tasks and projects from an agent.",
     "Создание, завершение и запрос задач и проектов Todoist из агента.",
     "Natural-language due dates (\"next Monday\") pass straight through to Todoist's own parser."),
    ("mcp-airtable-official", "Airtable MCP (official)", "Инфраструктура MCP", "https://airtable.com/developers/web/api/mcp-server", "freeTier", "airtable,database,official,records", "",
     "Official server for reading and writing Airtable bases and records.",
     "Официальный сервер для чтения и записи баз и записей Airtable.",
     "Fetch the base schema once per session — field types differ enough between bases to matter."),
    ("mcp-google-workspace", "Google Workspace MCP", "Инфраструктура MCP", "https://github.com/taylorwilsdon/google_workspace_mcp", "openSource", "gmail,calendar,drive,google", "uvx workspace-mcp",
     "Gmail, Calendar, Drive and Docs access for agents via one OAuth flow.",
     "Доступ к Gmail, Calendar, Drive и Docs для агентов через один OAuth-поток.",
     "Scope the OAuth consent to only the specific services the task actually needs."),
    ("mcp-huggingface-hub", "Hugging Face Hub MCP", "Инфраструктура MCP", "https://huggingface.co/docs/hub/en/mcp", "free", "huggingface,models,datasets,search", "",
     "Search and inspect models, datasets and Spaces on the Hugging Face Hub.",
     "Поиск и просмотр моделей, датасетов и Spaces на Hugging Face Hub.",
     "Useful for letting an agent pick a model by task and license rather than guessing a name."),
    ("mcp-wandb", "Weights & Biases MCP", "MLOps и эксперименты", "https://github.com/wandb/wandb-mcp-server", "freeTier", "wandb,experiments,mlops,official", "",
     "Query experiment runs, metrics and reports from Weights & Biases.",
     "Запрос прогонов экспериментов, метрик и отчётов из Weights & Biases.",
     "Have the agent compare two runs' metrics directly instead of eyeballing two dashboard tabs."),
    ("mcp-slack-official", "Slack MCP (official)", "Инфраструктура MCP", "https://github.com/modelcontextprotocol/servers-archived/tree/main/src/slack", "openSource", "slack,messaging,official,channels", "",
     "Read and post to Slack channels and threads from an agent.",
     "Чтение и отправка сообщений в каналы и треды Slack из агента.",
     "Restrict the bot token's channel scope in Slack's admin panel before wiring it to an agent."),
    ("mcp-terraform-registry", "Terraform Registry MCP", "Инфраструктура как код", "https://developer.hashicorp.com/terraform/docs/tools/mcp-server", "openSource", "terraform,iac,registry,official", "",
     "Looks up provider and module documentation from the Terraform Registry.",
     "Поиск документации провайдеров и модулей в Terraform Registry.",
     "Stops an agent from guessing resource argument names — it reads the real schema first."),
    ("mcp-datadog", "Datadog MCP", "Мониторинг и аналитика", "https://docs.datadoghq.com/bits_ai/mcp_server/", "paid", "datadog,monitoring,official,metrics", "",
     "Query Datadog metrics, logs and monitors from an agent session.",
     "Запрос метрик, логов и мониторов Datadog из сессии агента.",
     "Scope the API key to read-only if the agent's task is diagnosis, not changing alert configs."),
]

SKILLS_5 = [
    ("skill-anthropic-cookbook", "Anthropic Cookbook", "Гайды и практики", "https://github.com/anthropics/anthropic-cookbook", "free", "examples,claude,cookbook,recipes", "",
     "Worked examples for retrieval, tool use, evaluation and other common Claude patterns.",
     "Готовые примеры retrieval, tool use, оценки и других типовых паттернов работы с Claude.",
     "Start from the closest example instead of a blank prompt — most patterns here transfer directly."),
    ("skill-claude-cookbook-agents", "Claude Agents Cookbook", "Гайды и практики", "https://github.com/anthropics/claude-cookbooks/tree/main/patterns/agents", "free", "agents,patterns,claude,cookbook", "",
     "Worked implementations of the orchestrator, evaluator and routing agent patterns.",
     "Готовые реализации паттернов оркестратора, оценщика и роутинга агентов.",
     "Read the routing pattern before building a multi-tool agent — it usually beats one giant prompt."),
    ("skill-mcp-quickstart", "MCP Quickstart", "Инфраструктура MCP", "https://modelcontextprotocol.io/quickstart/server", "free", "mcp,quickstart,server,tutorial", "",
     "The official first-server tutorial: minimal Python and TypeScript examples.",
     "Официальный туториал по первому серверу: минимальные примеры на Python и TypeScript.",
     "Follow this before reading the full spec — a working toy server makes the spec's abstractions concrete."),
    ("skill-mcp-authorization", "MCP Authorization Spec", "Инфраструктура MCP", "https://modelcontextprotocol.io/specification/latest/basic/authorization", "free", "mcp,oauth,security,spec", "",
     "The OAuth-based authorization flow for remote MCP servers.",
     "OAuth-based поток авторизации для удалённых MCP-серверов.",
     "Required reading before exposing any MCP server beyond localhost to more than yourself."),
    ("skill-computer-use", "Computer Use", "Гайды и практики", "https://docs.claude.com/en/docs/agents-and-tools/tool-use/computer-use-tool", "free", "computer-use,gui,automation,claude", "",
     "Screen-based tool use: Claude sees screenshots and issues mouse/keyboard actions.",
     "Работа с инструментами через экран: Claude видит скриншоты и выдаёт действия мыши/клавиатуры.",
     "Run it in an isolated VM or container — it can click and type anywhere on the screen it's given."),
    ("skill-extended-thinking", "Extended Thinking", "Гайды и практики", "https://docs.claude.com/en/docs/build-with-claude/extended-thinking", "free", "reasoning,thinking,claude,budget", "",
     "How Claude's extended thinking budget works and when it actually helps.",
     "Как работает бюджет extended thinking у Claude и когда он реально помогает.",
     "Reserve it for genuinely hard reasoning steps — routine tasks pay latency for no quality gain."),
    ("skill-pdf-support", "PDF Support", "Документы и PDF", "https://docs.claude.com/en/docs/build-with-claude/pdf-support", "free", "pdf,vision,claude,documents", "",
     "Sending PDFs directly to Claude, including scanned pages read via vision.",
     "Отправка PDF напрямую в Claude, включая сканированные страницы через vision.",
     "Claude reads PDF layout visually, so tables and figures survive better than with plain text extraction."),
    ("skill-vision-guide", "Vision Guide", "Гайды и практики", "https://docs.claude.com/en/docs/build-with-claude/vision", "free", "vision,images,claude,multimodal", "",
     "Practical guidance for image inputs: sizing, multiple images, and common failure modes.",
     "Практические советы по работе с изображениями: размер, несколько изображений, типичные ошибки.",
     "Resize large images before sending — oversized inputs cost tokens without adding useful detail."),
    ("skill-files-api", "Files API", "Документы и PDF", "https://docs.claude.com/en/docs/build-with-claude/files", "free", "files,upload,claude,api", "",
     "Upload files once and reference them across multiple API calls instead of resending bytes.",
     "Загружай файл один раз и ссылайся на него в нескольких вызовах API вместо повторной отправки.",
     "Combine with prompt caching for a document an agent revisits many times in one session."),
    ("skill-batch-api", "Message Batches API", "Гайды и практики", "https://docs.claude.com/en/docs/build-with-claude/batch-processing", "free", "batch,cost,claude,async", "",
     "Asynchronous bulk processing at roughly half the cost of synchronous calls.",
     "Асинхронная массовая обработка примерно за половину стоимости синхронных вызовов.",
     "Use it for anything that doesn't need a same-second answer — the discount is substantial at scale."),
    ("skill-token-counting", "Token Counting", "Гайды и практики", "https://docs.claude.com/en/docs/build-with-claude/token-counting", "free", "tokens,cost,claude,api", "",
     "Count tokens before sending a request to predict cost and stay under context limits.",
     "Подсчёт токенов перед отправкой запроса — для прогноза стоимости и лимита контекста.",
     "Count the whole request including tools and system prompt, not just the user message."),
    ("skill-citations", "Citations", "Гайды и практики", "https://docs.claude.com/en/docs/build-with-claude/citations", "free", "citations,rag,grounding,claude", "",
     "Grounds Claude's answers in source documents with exact, verifiable citations.",
     "Привязывает ответы Claude к исходным документам с точными проверяемыми цитатами.",
     "Use this instead of asking Claude to quote sources in prose — the citations are structurally verified."),
    ("skill-structured-outputs-claude", "Structured Outputs", "Гайды и практики", "https://docs.claude.com/en/docs/build-with-claude/structured-outputs", "free", "json,schema,claude,tool-use", "",
     "Reliable JSON output from Claude constrained to a provided schema.",
     "Надёжный JSON-вывод от Claude, ограниченный заданной схемой.",
     "Prefer this over parsing free-text JSON from a prompt — it removes the whole class of malformed output."),
    ("skill-context-editing", "Context Editing", "Гайды и практики", "https://docs.claude.com/en/docs/build-with-claude/context-editing", "free", "context,memory,claude,long-sessions", "",
     "Automatically trims stale tool results from context to keep long agent sessions efficient.",
     "Автоматически убирает устаревшие результаты инструментов из контекста для эффективных долгих сессий.",
     "Turn this on for any agent loop that runs many tool calls in one conversation."),
    ("skill-mcp-connector", "MCP Connector (API)", "Инфраструктура MCP", "https://docs.claude.com/en/docs/agents-and-tools/mcp-connector", "free", "mcp,api,remote,claude", "",
     "Connects the Messages API directly to remote MCP servers without running your own client.",
     "Подключает Messages API напрямую к удалённым MCP-серверам без своего клиента.",
     "Simplest path when the server is already hosted remotely and you don't need local tool execution."),
]
