# -*- coding: utf-8 -*-
"""Stage 5 library pack A: computer vision/OCR libs, forms, video players, web3, IoT."""

LIBS_5A = [
    # ---------- Компьютерное зрение ----------
    ("lib-ultralytics", "Ultralytics YOLO", "Компьютерное зрение", "https://docs.ultralytics.com/", "openSource", "yolo,detection,segmentation,realtime", "pip install ultralytics",
     "The reference real-time object detection family, now with segmentation and pose.",
     "Эталонное семейство детекции объектов в реальном времени, теперь с сегментацией и позой.",
     "Start from a pretrained checkpoint and fine-tune; training from scratch rarely pays off."),
    ("lib-opencv", "OpenCV", "Компьютерное зрение", "https://docs.opencv.org/", "openSource", "vision,classical,image-processing,cpp", "pip install opencv-python",
     "The classical computer-vision toolkit: filters, transforms, contours, camera calibration.",
     "Классический тулкит компьютерного зрения: фильтры, преобразования, контуры, калибровка камер.",
     "Reach for this before a deep model when the task is really just image processing."),
    ("lib-mediapipe", "MediaPipe", "Компьютерное зрение", "https://ai.google.dev/edge/mediapipe", "openSource", "pose,hands,face,realtime", "pip install mediapipe",
     "Real-time pose, hand and face landmark tracking that runs on-device.",
     "Трекинг позы, рук и лица в реальном времени, работающий на устройстве.",
     "The landmark models are small enough for a browser tab — try the JS build before native."),
    ("lib-detectron2", "Detectron2", "Компьютерное зрение", "https://detectron2.readthedocs.io/", "openSource", "detection,segmentation,research,pytorch", "pip install detectron2",
     "Meta's research-grade detection and segmentation framework built on PyTorch.",
     "Исследовательский фреймворк детекции и сегментации от Meta на PyTorch.",
     "Config-driven: most experiments are a YAML edit, not new code."),
    ("lib-albumentations", "Albumentations", "Компьютерное зрение", "https://albumentations.ai/docs/", "openSource", "augmentation,training,pytorch,fast", "pip install albumentations",
     "Fast image augmentation library used across most vision training pipelines.",
     "Быстрая библиотека аугментации изображений, используемая почти во всех vision-пайплайнах.",
     "Compose transforms once as a pipeline object and reuse it across train and validation."),
    ("lib-dlib", "dlib", "Компьютерное зрение", "https://github.com/davisking/dlib", "openSource", "vision,face-landmarks,cpp,classical", "pip install dlib",
     "C++ toolkit with strong face-landmark detection, still widely used for that one task.",
     "C++ тулкит с сильной детекцией лицевых точек, до сих пор широко используется именно для этого.",
     "Its 68-point facial landmark model remains a common baseline despite the library's age."),

    # ---------- OCR и распознавание документов ----------
    ("lib-tesseract-ocr", "Tesseract OCR", "OCR и распознавание документов", "https://tesseract-ocr.github.io/", "openSource", "ocr,offline,multilingual,cli", "apt install tesseract-ocr",
     "The open-source OCR engine most other tools wrap or compare themselves against.",
     "Открытый движок OCR, который оборачивают или с которым сравнивают почти все остальные.",
     "Preprocessing (deskew, binarize) matters more than engine choice for accuracy on scans."),
    ("lib-easyocr", "EasyOCR", "OCR и распознавание документов", "https://github.com/JaidedAI/EasyOCR", "openSource", "ocr,python,multilingual,deep-learning", "pip install easyocr",
     "Deep-learning OCR supporting 80+ languages with a two-line Python API.",
     "OCR на основе глубокого обучения, поддерживает 80+ языков, API в две строки Python.",
     "GPU inference is dramatically faster; CPU-only is fine for occasional single-page use."),
    ("lib-paddleocr", "PaddleOCR", "OCR и распознавание документов", "https://github.com/PaddlePaddle/PaddleOCR", "openSource", "ocr,chinese,lightweight,mobile", "pip install paddleocr",
     "Lightweight multilingual OCR with particularly strong Chinese and mobile-friendly models.",
     "Лёгкий мультиязычный OCR с особенно сильными моделями для китайского и мобильных устройств.",
     "The mobile-optimized model runs on-device in under 10MB — check it before shipping the full model."),
    ("lib-marker", "Marker", "OCR и распознавание документов", "https://github.com/VikParuchuri/marker", "openSource", "ocr,pdf,markdown,layout", "pip install marker-pdf",
     "Converts PDFs to clean Markdown, keeping tables and equations intact.",
     "Конвертирует PDF в чистый Markdown, сохраняя таблицы и формулы.",
     "Runs a layout model first, which is why it keeps structure that raw text extraction loses."),

    # ---------- Стриминг видео ----------
    ("lib-hls-js", "hls.js", "Стриминг видео", "https://github.com/video-dev/hls.js/", "openSource", "hls,streaming,player,javascript", "npm i hls.js",
     "Plays HLS streams in browsers that lack native support, via Media Source Extensions.",
     "Проигрывает HLS-потоки в браузерах без нативной поддержки через Media Source Extensions.",
     "Native HLS already works in Safari — feature-detect and skip hls.js there to save bytes."),
    ("lib-video-js", "Video.js", "Стриминг видео", "https://videojs.com/guides/", "openSource", "player,html5,plugins,customizable", "npm i video.js",
     "The standard open-source HTML5 video player, extensible via a large plugin ecosystem.",
     "Стандартный открытый HTML5-плеер видео, расширяемый большой экосистемой плагинов.",
     "Skip building custom controls — the default skin covers accessibility work you'd otherwise redo."),
    ("lib-dash-js", "dash.js", "Стриминг видео", "https://github.com/Dash-Industry-Forum/dash.js/", "openSource", "dash,streaming,adaptive,mpeg", "npm i dashjs",
     "Reference MPEG-DASH player, the open alternative to HLS for adaptive streaming.",
     "Эталонный плеер MPEG-DASH — открытая альтернатива HLS для адаптивного стриминга.",
     "Pick DASH over HLS when you need finer control over ABR logic — its API exposes more knobs."),

    # ---------- Формы и опросы ----------
    ("lib-formik", "Formik", "Формы и опросы", "https://formik.org/docs/overview", "openSource", "forms,react,validation,state", "npm i formik",
     "Form state, validation and submission handling for React without the boilerplate.",
     "Состояние формы, валидация и отправка для React без шаблонного кода.",
     "Pair it with Yup for schema-based validation — that combination covers almost every form."),
    ("lib-vee-validate", "VeeValidate", "Формы и опросы", "https://vee-validate.logaretm.com/v4/", "openSource", "forms,vue,validation,schema", "npm i vee-validate",
     "Form validation for Vue with composable rules and schema support.",
     "Валидация форм для Vue с composable-правилами и поддержкой схем.",
     "Works with both the Composition API and the older Options API without rewrites."),

    # ---------- Web3 и блокчейн ----------
    ("lib-ethers-js", "Ethers.js", "Web3 и блокчейн", "https://docs.ethers.org/", "openSource", "ethereum,web3,wallet,contracts", "npm i ethers",
     "Compact, well-typed library for interacting with Ethereum and EVM chains.",
     "Компактная, хорошо типизированная библиотека для работы с Ethereum и EVM-цепями.",
     "Prefer this over web3.js for new projects — smaller bundle, better TypeScript types."),
    ("lib-viem", "Viem", "Web3 и блокчейн", "https://viem.sh/docs/introduction", "openSource", "ethereum,typescript,evm,lightweight", "npm i viem",
     "Type-safe, tree-shakeable Ethereum library built as a modern alternative to ethers.js.",
     "Типобезопасная, tree-shakeable библиотека Ethereum как современная альтернатива ethers.js.",
     "The underlying library for Wagmi — reach for it directly when you don't need React hooks."),
    ("lib-wagmi", "Wagmi", "Web3 и блокчейн", "https://wagmi.sh/react/getting-started", "openSource", "ethereum,react,hooks,wallet", "npm i wagmi",
     "React hooks for wallet connection, contract reads/writes and chain state.",
     "React-хуки для подключения кошельков, чтения/записи контрактов и состояния сети.",
     "Connectors handle MetaMask, WalletConnect and Coinbase Wallet through one consistent hook API."),
    ("lib-web3js", "web3.js", "Web3 и блокчейн", "https://docs.web3js.org/", "openSource", "ethereum,web3,contracts,legacy", "npm i web3",
     "The original Ethereum JavaScript library, still common in existing codebases.",
     "Оригинальная JavaScript-библиотека Ethereum, всё ещё встречается в существующем коде.",
     "New projects should default to viem or ethers.js; this is mainly relevant for maintaining older code."),
    ("lib-hardhat", "Hardhat", "Web3 и блокчейн", "https://hardhat.org/docs", "openSource", "ethereum,development,testing,solidity", "npm i --save-dev hardhat",
     "Ethereum development environment: local network, testing, deployment scripts.",
     "Среда разработки Ethereum: локальная сеть, тестирование, скрипты деплоя.",
     "The console.log-in-Solidity plugin makes contract debugging vastly less painful."),
    ("lib-foundry", "Foundry", "Web3 и блокчейн", "https://book.getfoundry.sh/", "openSource", "ethereum,solidity,testing,fast", "curl -L https://foundry.paradigm.xyz | bash",
     "Rust-based Ethereum toolkit: write tests in Solidity itself, extremely fast execution.",
     "Ethereum-тулкит на Rust: тесты пишутся прямо на Solidity, очень быстрое выполнение.",
     "Fuzz testing is built in and free — add invariant tests before shipping any contract."),
    ("lib-openzeppelin", "OpenZeppelin Contracts", "Web3 и блокчейн", "https://docs.openzeppelin.com/contracts/", "openSource", "solidity,security,standards,tokens", "npm i @openzeppelin/contracts",
     "Audited, standard smart-contract building blocks: ERC20, ERC721, access control.",
     "Аудированные стандартные строительные блоки контрактов: ERC20, ERC721, контроль доступа.",
     "Extend these contracts rather than writing token logic from scratch — the audits are the whole value."),
    ("lib-thirdweb", "thirdweb", "Web3 и блокчейн", "https://portal.thirdweb.com/", "freeTier", "web3,sdk,contracts,deploy", "npm i thirdweb",
     "Web3 SDK covering contract deployment, wallets and onchain interactions in one toolkit.",
     "Web3 SDK, покрывающий деплой контрактов, кошельки и ончейн-взаимодействия в одном тулките.",
     "Prebuilt, audited contracts deploy without writing Solidity, useful for a first onchain feature."),
    ("lib-anchor-solana", "Anchor", "Web3 и блокчейн", "https://www.anchor-lang.com/docs", "openSource", "solana,rust,framework,contracts", "cargo install anchor-cli",
     "Framework for Solana program development, roughly Solana's equivalent of Hardhat.",
     "Фреймворк для разработки программ Solana, примерный аналог Hardhat для Solana.",
     "IDL generation gives you a typed TypeScript client for free from the same source."),
    ("lib-solana-web3js", "Solana Web3.js", "Web3 и блокчейн", "https://solana-labs.github.io/solana-web3.js/", "openSource", "solana,web3,transactions,wallet", "npm i @solana/web3.js",
     "JavaScript library for building Solana transactions and reading chain state.",
     "JavaScript-библиотека для сборки транзакций Solana и чтения состояния сети.",
     "Use a connection pool with fallback RPC endpoints — public Solana RPC nodes rate-limit aggressively."),

    # ---------- IoT и встраиваемые системы ----------
    ("lib-platformio", "PlatformIO", "IoT и встраиваемые системы", "https://docs.platformio.org/", "openSource", "embedded,arduino,esp32,build", "pip install platformio",
     "Cross-platform build system and IDE integration for embedded and IoT development.",
     "Кроссплатформенная система сборки и интеграция с IDE для embedded и IoT разработки.",
     "One platformio.ini covers dozens of boards — switch target hardware by changing one line."),
    ("lib-esp-idf", "ESP-IDF", "IoT и встраиваемые системы", "https://docs.espressif.com/projects/esp-idf/", "openSource", "esp32,firmware,espressif,c", "",
     "Espressif's official development framework for the ESP32 family of chips.",
     "Официальный фреймворк разработки Espressif для семейства чипов ESP32.",
     "Use this over Arduino-for-ESP32 once you need real FreeRTOS control or low-power modes."),
    ("lib-zephyr-rtos", "Zephyr RTOS", "IoT и встраиваемые системы", "https://docs.zephyrproject.org/", "openSource", "rtos,embedded,linux-foundation,portable", "",
     "Linux Foundation real-time OS aimed at resource-constrained IoT devices.",
     "RTOS от Linux Foundation для устройств IoT с ограниченными ресурсами.",
     "Board support is broad — check the supported-boards list before committing hardware."),
    ("lib-micropython", "MicroPython", "IoT и встраиваемые системы", "https://docs.micropython.org/", "openSource", "python,microcontroller,embedded,scripting", "",
     "Python 3 reimplementation that runs directly on microcontrollers.",
     "Реализация Python 3, работающая прямо на микроконтроллерах.",
     "REPL over serial makes interactive hardware debugging far faster than flash-and-print cycles."),
    ("lib-circuitpython", "CircuitPython", "IoT и встраиваемые системы", "https://docs.circuitpython.org/", "openSource", "python,adafruit,beginner,microcontroller", "",
     "Adafruit's beginner-friendly MicroPython fork with broad board and sensor library support.",
     "Дружелюбный к новичкам форк MicroPython от Adafruit с широкой поддержкой плат и сенсоров.",
     "Drag-and-drop firmware updates over USB make it the easiest path for a first hardware project."),
    ("lib-esphome", "ESPHome", "IoT и встраиваемые системы", "https://esphome.io/", "openSource", "esp32,esp8266,yaml,home-assistant", "pip install esphome",
     "YAML-configured firmware for ESP boards that integrates directly with Home Assistant.",
     "Прошивка ESP-плат, настраиваемая через YAML, напрямую интегрируется с Home Assistant.",
     "No C++ required for common sensors — most integrations are a YAML block copied from the docs."),
    ("lib-mosquitto", "Eclipse Mosquitto", "IoT и встраиваемые системы", "https://mosquitto.org/documentation/", "openSource", "mqtt,broker,iot,self-host", "apt install mosquitto",
     "The reference open-source MQTT broker for IoT messaging.",
     "Эталонный открытый MQTT-брокер для обмена сообщениями в IoT.",
     "Enable TLS and auth by default — an open MQTT broker on the public internet gets found fast."),
    ("lib-node-red", "Node-RED", "IoT и встраиваемые системы", "https://nodered.org/docs/", "openSource", "flow,iot,visual,automation", "npm i -g node-red",
     "Visual flow-based programming for wiring together IoT devices, APIs and services.",
     "Визуальное потоковое программирование для связывания IoT-устройств, API и сервисов.",
     "Community-contributed nodes cover most protocols — check the flow library before writing a custom node."),
    ("lib-tasmota", "Tasmota", "IoT и встраиваемые системы", "https://tasmota.github.io/docs/", "openSource", "esp,firmware,smart-home,mqtt", "",
     "Open-source firmware replacement for cheap smart-home devices, with local MQTT control.",
     "Открытая прошивка-замена для дешёвых устройств умного дома с локальным управлением через MQTT.",
     "Flashing it removes cloud dependency from budget smart plugs — check device compatibility first."),

    # ---------- Дизайн-системы ----------
    ("lib-style-dictionary", "Style Dictionary", "Дизайн-системы", "https://styledictionary.com/", "openSource", "design-tokens,build,cross-platform", "npm i -D style-dictionary",
     "Transforms one set of design tokens into platform-specific formats (CSS, iOS, Android).",
     "Превращает один набор дизайн-токенов в форматы для разных платформ (CSS, iOS, Android).",
     "Define tokens once as JSON; the build step is what keeps web and native colors in sync."),
    ("lib-figma-tokens", "Tokens Studio for Figma", "Дизайн-системы", "https://docs.tokens.studio/", "freeTier", "design-tokens,figma,sync,plugin", "",
     "Figma plugin that manages design tokens and syncs them to code via Style Dictionary or GitHub.",
     "Плагин Figma для управления дизайн-токенами с синхронизацией в код через Style Dictionary или GitHub.",
     "Push tokens to a GitHub branch and open a PR automatically — that closes the design-to-code loop."),

    # ---------- Игровые движки ----------
    ("lib-godot", "Godot Engine", "Игровые движки", "https://docs.godotengine.org/", "openSource", "game-engine,2d,3d,gdscript", "",
     "Fully free, MIT-licensed game engine with a friendly scripting language and no royalties.",
     "Полностью бесплатный движок под MIT-лицензией со своим языком скриптов и без роялти.",
     "GDScript is the fastest path to a first prototype; C# is there once performance matters."),
    ("lib-unity", "Unity", "Игровые движки", "https://docs.unity3d.com/", "freeTier", "game-engine,csharp,2d,3d", "",
     "Industry-standard engine for 2D, 3D and mixed-reality games with a huge asset ecosystem.",
     "Индустриальный стандарт для 2D, 3D и mixed-reality игр с огромной экосистемой ассетов.",
     "The free Personal tier covers indie projects until revenue crosses the plan's threshold."),
    ("lib-unreal-engine", "Unreal Engine", "Игровые движки", "https://dev.epicgames.com/documentation/unreal-engine", "freeTier", "game-engine,cpp,blueprints,3d", "",
     "AAA-grade engine with visual scripting (Blueprints) and best-in-class rendering.",
     "AAA-движок с визуальным скриптингом (Blueprints) и лучшим в классе рендерингом.",
     "Blueprints prototype fast; drop to C++ only for the systems that actually need the performance."),
    ("lib-bevy", "Bevy", "Игровые движки", "https://bevyengine.org/learn/", "openSource", "rust,ecs,game-engine,data-oriented", "cargo add bevy",
     "Data-driven Rust game engine built around an entity-component-system architecture.",
     "Rust-движок для игр, построенный на архитектуре entity-component-system.",
     "The ECS model rewards designing data and systems before writing any gameplay code."),
    ("lib-defold", "Defold", "Игровые движки", "https://defold.com/manuals/introduction/", "freeTier", "game-engine,2d,lua,lightweight", "",
     "Free, lightweight 2D engine scripted in Lua, with small build sizes across platforms.",
     "Бесплатный лёгкий 2D-движок на Lua с маленьким размером сборки на всех платформах.",
     "Build sizes stay small even for full games, which matters for web and mobile distribution."),
]
