# -*- coding: utf-8 -*-
"""Stage 5 library pack M: Java/Kotlin/Swift, WASM, game dev libs, misc runtimes."""

LIBS_5M = [
    # ---------- Мобильная и desktop разработка: Swift/iOS ----------
    ("lib-swiftui", "SwiftUI", "Мобильная и desktop разработка", "https://developer.apple.com/documentation/swiftui/", "free", "swift,ios,declarative,apple", "",
     "Apple's declarative UI framework for iOS, macOS, watchOS and visionOS.",
     "Декларативный UI-фреймворк Apple для iOS, macOS, watchOS и visionOS.",
     "One layout adapts across Apple platforms, but platform-specific polish still needs conditional code."),
    ("lib-swift-composable-architecture", "Composable Architecture (TCA)", "Мобильная и desktop разработка", "https://pointfreeco.github.io/swift-composable-architecture/", "openSource", "swift,state,architecture,testable", "",
     "Redux-like state management for SwiftUI with a strong emphasis on testability.",
     "Redux-подобное управление состоянием для SwiftUI с сильным упором на тестируемость.",
     "Its exhaustive testing model catches unhandled state transitions that ad-hoc SwiftUI state hides."),
    ("lib-alamofire", "Alamofire", "Мобильная и desktop разработка", "https://alamofire.github.io/Alamofire/", "openSource", "swift,networking,http,ios", "",
     "The standard Swift HTTP networking library, wrapping URLSession ergonomically.",
     "Стандартная Swift-библиотека HTTP-сети, эргономичная обёртка над URLSession.",
     "Modern async/await URLSession covers many cases natively now — check if you actually need the dependency."),
    ("lib-kotlin-coroutines", "Kotlin Coroutines", "JVM экосистема", "https://kotlinlang.org/docs/coroutines-overview.html", "openSource", "kotlin,async,concurrency,structured", "",
     "Kotlin's structured concurrency model for asynchronous programming.",
     "Модель структурированной конкурентности Kotlin для асинхронного программирования.",
     "Scopes tie coroutine lifetime to a component's lifecycle, which prevents the classic leaked-async-task bug."),
    ("lib-jetpack-compose-2", "Jetpack Compose Multiplatform", "Мобильная и desktop разработка", "https://www.jetbrains.com/compose-multiplatform/", "openSource", "kotlin,compose,multiplatform,ui", "",
     "JetBrains' port of Compose UI to desktop, web and iOS beyond Android.",
     "Порт Compose UI от JetBrains на desktop, web и iOS помимо Android.",
     "Unlike KMM (which shares logic only), this shares the UI layer too — a different tradeoff entirely."),

    # ---------- WebAssembly ----------
    ("lib-wasmtime", "Wasmtime", "Языки и рантаймы", "https://docs.wasmtime.dev/", "openSource", "wasm,runtime,bytecode-alliance,sandboxing", "",
     "Standalone WebAssembly runtime from the Bytecode Alliance, usable as an embedded sandbox.",
     "Автономный рантайм WebAssembly от Bytecode Alliance, применим как встраиваемая песочница.",
     "WASM's capability-based sandbox makes it a strong option for running untrusted plugin code safely."),
    ("lib-wasmer", "Wasmer", "Языки и рантаймы", "https://docs.wasmer.io/", "openSource", "wasm,runtime,universal,embeddable", "",
     "WebAssembly runtime with bindings for many host languages and a package registry.",
     "Рантайм WebAssembly с биндингами для многих языков и реестром пакетов.",
     "Its multi-language embedding story is the main differentiator versus Wasmtime."),
    ("lib-emscripten", "Emscripten", "Языки и рантаймы", "https://emscripten.org/docs/", "openSource", "wasm,c,cpp,compiler", "",
     "Compiles C and C++ to WebAssembly, the toolchain behind most ported native web apps.",
     "Компилирует C и C++ в WebAssembly — тулчейн большинства портированных нативных веб-приложений.",
     "Its emulated filesystem and SDL layers are why large native codebases port with modest changes."),
    ("lib-wasm-pack", "wasm-pack", "Языки и рантаймы", "https://rustwasm.github.io/wasm-pack/", "openSource", "wasm,rust,npm,bindings", "cargo install wasm-pack",
     "Builds Rust into WebAssembly npm packages with generated JavaScript bindings.",
     "Собирает Rust в npm-пакеты WebAssembly с автогенерируемыми JavaScript-биндингами.",
     "Generates TypeScript definitions automatically, so the WASM module feels like a normal typed npm package."),

    # ---------- Игровые движки: libraries ----------
    ("lib-matter-js", "Matter.js", "Игровые движки", "https://brm.io/matter-js/docs/", "openSource", "physics,2d,javascript,rigid-body", "npm i matter-js",
     "2D rigid body physics engine for the browser.",
     "2D физический движок твёрдых тел для браузера.",
     "Tune the timestep carefully — physics engines behave very differently on inconsistent frame rates."),
    ("lib-excalibur-js", "Excalibur.js", "Игровые движки", "https://excaliburjs.com/docs/", "openSource", "typescript,2d,game-engine,browser", "npm i excalibur",
     "TypeScript-first 2D game engine for the browser with batteries included.",
     "2D игровой движок для браузера на TypeScript со всем необходимым из коробки.",
     "Fuller than PixiJS (scenes, actors, collision built in) if you want an engine rather than a renderer."),
    ("lib-kaboom-js", "KAPLAY (Kaboom.js)", "Игровые движки", "https://kaplayjs.com/", "openSource", "javascript,2d,beginner,fast-prototyping", "npm i kaplay",
     "Fun, beginner-friendly JavaScript game library for quick 2D prototypes.",
     "Дружелюбная к новичкам JavaScript-библиотека для быстрых 2D-прототипов.",
     "Its terse API makes game jams and teaching much faster than a full engine's setup."),

    # ---------- Языки и рантаймы (deepen) ----------
    ("lib-zig", "Zig", "Языки и рантаймы", "https://ziglang.org/documentation/master/", "openSource", "systems,c-interop,compiler,manual-memory", "",
     "Systems programming language with manual memory management and excellent C interop.",
     "Язык системного программирования с ручным управлением памятью и отличной совместимостью с C.",
     "Its C compiler mode alone is useful — zig cc works as a drop-in cross-compiling C toolchain."),
    ("lib-nim", "Nim", "Языки и рантаймы", "https://nim-lang.org/documentation.html", "openSource", "compiled,python-like,performance,metaprogramming", "",
     "Statically typed compiled language with Python-like syntax and strong metaprogramming.",
     "Статически типизированный компилируемый язык с синтаксисом в духе Python и сильным метапрограммированием.",
     "Compiles to C, which is why binaries are small and it runs almost anywhere C does."),
    ("lib-crystal-lang", "Crystal", "Языки и рантаймы", "https://crystal-lang.org/reference/", "openSource", "compiled,ruby-like,static-typing,fast", "",
     "Compiled language with Ruby-inspired syntax and static type inference.",
     "Компилируемый язык с синтаксисом в духе Ruby и статическим выводом типов.",
     "Familiar to Ruby developers while running roughly an order of magnitude faster."),
    ("lib-gleam", "Gleam", "Elixir экосистема", "https://gleam.run/documentation/", "openSource", "beam,type-safe,functional,erlang", "",
     "Statically typed functional language for the BEAM (Erlang VM), interoperable with Elixir.",
     "Статически типизированный функциональный язык для BEAM (Erlang VM), совместим с Elixir.",
     "Brings compile-time type safety to the BEAM, which Elixir and Erlang deliberately lack."),
    ("lib-bun-ffi", "Bun FFI", "Языки и рантаймы", "https://bun.com/docs/api/ffi", "openSource", "bun,ffi,native,performance", "",
     "Call native C libraries directly from Bun without writing a native addon.",
     "Вызов нативных C-библиотек прямо из Bun без написания нативного аддона.",
     "Avoids the node-gyp build step entirely, which is the usual pain point for native modules in Node."),
]
