# -*- coding: utf-8 -*-
"""Stage 5 library pack AQ: rich text editors, CRDT collaboration, realtime transports, WebRTC."""

LIBS_5AQ = [
    # ---------- Редакторы текста ----------
    ("lib-tiptap", "Tiptap", "UI и frontend", "https://tiptap.dev/docs", "mixed", "editor,prosemirror,headless,extensions", "npm i @tiptap/core",
     "Headless rich text editor built on ProseMirror with an extension system.",
     "Headless-редактор форматированного текста на ProseMirror с системой расширений.",
     "Headless means you own every pixel of the toolbar, unlike editors that ship a fixed interface."),
    ("lib-prosemirror", "ProseMirror", "UI и frontend", "https://prosemirror.net/docs/", "openSource", "editor,schema,transactions,foundation", "npm i prosemirror-view",
     "Toolkit for building rich text editors around an explicit document schema.",
     "Набор инструментов для создания редакторов форматированного текста вокруг явной схемы документа.",
     "Its schema guarantees the document can never enter an invalid state, which contenteditable cannot."),
    ("lib-slate", "Slate", "UI и frontend", "https://docs.slatejs.org/", "openSource", "editor,react,customizable,plugin", "npm i slate slate-react",
     "Completely customizable framework for building React text editors.",
     "Полностью настраиваемый фреймворк для создания текстовых редакторов на React.",
     "Maximum flexibility and correspondingly more work — you implement behaviours others ship built in."),
    ("lib-quill", "Quill", "UI и frontend", "https://quilljs.com/docs/quickstart", "openSource", "editor,wysiwyg,delta,simple", "npm i quill",
     "Straightforward WYSIWYG editor with a clean document model.",
     "Простой WYSIWYG-редактор с чистой моделью документа.",
     "Its Delta format describes changes rather than state, which makes diffing and syncing simpler."),
    ("lib-ckeditor", "CKEditor 5", "UI и frontend", "https://ckeditor.com/docs/ckeditor5/latest/", "mixed", "editor,wysiwyg,collaboration,enterprise", "npm i ckeditor5",
     "Mature WYSIWYG editor with optional real-time collaboration features.",
     "Зрелый WYSIWYG-редактор с опциональной совместной работой в реальном времени.",
     "Open source under GPL; a commercial licence is needed for closed-source products."),
    ("lib-tinymce", "TinyMCE", "UI и frontend", "https://www.tiny.cloud/docs/tinymce/latest/", "mixed", "editor,wysiwyg,plugins,mature", "npm i tinymce",
     "Long-established WYSIWYG editor with an extensive plugin catalogue.",
     "Давно устоявшийся WYSIWYG-редактор с обширным каталогом плагинов.",
     "Its self-hosted core is free; the cloud features and premium plugins are what you pay for."),
    ("lib-editorjs", "Editor.js", "UI и frontend", "https://editorjs.io/", "openSource", "block-editor,json,clean-output,plugins", "npm i @editorjs/editorjs",
     "Block-style editor producing clean JSON rather than HTML.",
     "Блочный редактор, выдающий чистый JSON вместо HTML.",
     "JSON output is safe to render anywhere, which sidesteps the sanitization problem HTML brings."),
    ("lib-milkdown", "Milkdown", "UI и frontend", "https://milkdown.dev/docs/guide/getting-started", "openSource", "markdown,wysiwyg,prosemirror,plugin-driven", "npm i @milkdown/core",
     "Plugin-driven WYSIWYG Markdown editor built on ProseMirror.",
     "WYSIWYG-редактор Markdown на плагинах, построенный на ProseMirror.",
     "It edits Markdown visually while keeping Markdown as the source of truth on disk."),
    ("lib-blocknote", "BlockNote", "UI и frontend", "https://www.blocknotejs.org/docs", "openSource", "block-editor,notion-like,react,collaboration", "npm i @blocknote/core",
     "Notion-style block editor for React with collaboration support.",
     "Блочный редактор в стиле Notion для React с поддержкой совместной работы.",
     "Ships with a working interface, unlike headless editors that leave the UI entirely to you."),
    ("lib-plate", "Plate", "UI и frontend", "https://platejs.org/docs", "openSource", "slate,react,plugins,components", "npm i platejs",
     "Rich text editor framework layering plugins and components over Slate.",
     "Фреймворк редактора форматированного текста: плагины и компоненты поверх Slate.",
     "It supplies the behaviours Slate leaves unimplemented, which is most of the work in practice."),

    # ---------- CRDT и совместная работа ----------
    ("lib-yjs", "Yjs", "Состояние и данные", "https://docs.yjs.dev/", "openSource", "crdt,collaboration,offline,realtime", "npm i yjs",
     "CRDT framework for building collaborative applications.",
     "CRDT-фреймворк для создания приложений с совместной работой.",
     "Concurrent edits merge without a central authority, which is what makes offline editing work."),
    ("lib-automerge", "Automerge", "Состояние и данные", "https://automerge.org/docs/", "openSource", "crdt,local-first,json,rust", "npm i @automerge/automerge",
     "CRDT library for local-first applications, with a JSON-like data model.",
     "CRDT-библиотека для local-first приложений с моделью данных в духе JSON.",
     "Its full edit history enables time travel, which Yjs discards by default for size."),
    ("lib-liveblocks", "Liveblocks", "Состояние и данные", "https://liveblocks.io/docs", "freeTier", "collaboration,presence,comments,hosted", "npm i @liveblocks/client",
     "Hosted collaboration infrastructure with presence, comments and notifications.",
     "Размещённая инфраструктура совместной работы с присутствием, комментариями и уведомлениями.",
     "Presence and cursors are the fiddly part of collaboration, and it handles them out of the box."),
    ("lib-partykit", "PartyKit", "Состояние и данные", "https://docs.partykit.io/", "freeTier", "realtime,durable-objects,edge,multiplayer", "npm i partykit",
     "Realtime multiplayer backends running on Cloudflare Durable Objects.",
     "Realtime-бэкенды для многопользовательских приложений на Cloudflare Durable Objects.",
     "Each room is a stateful object at the edge, which removes the usual pub/sub coordination layer."),
    ("lib-y-sweet", "Y-Sweet", "Состояние и данные", "https://docs.jamsocket.com/y-sweet/", "openSource", "yjs,server,persistence,s3", "",
     "Yjs synchronization server with persistence to object storage.",
     "Сервер синхронизации Yjs с сохранением в объектное хранилище.",
     "Persisting documents to S3 makes a Yjs deployment durable without running a database."),
    ("lib-hocuspocus", "Hocuspocus", "Состояние и данные", "https://tiptap.dev/docs/hocuspocus/introduction", "openSource", "yjs,backend,extensions,tiptap", "npm i @hocuspocus/server",
     "Yjs collaboration backend from the Tiptap team.",
     "Бэкенд совместной работы Yjs от команды Tiptap.",
     "Its extension hooks cover authentication and persistence, which raw Yjs providers leave open."),
    ("lib-sharedb", "ShareDB", "Состояние и данные", "https://share.github.io/sharedb/", "openSource", "operational-transform,realtime,json,database", "npm i sharedb",
     "Realtime database backend using operational transformation.",
     "Realtime-бэкенд базы данных на операционных преобразованиях.",
     "OT requires a central server to order operations, unlike CRDTs which merge peer to peer."),
    ("lib-jazz-tools", "Jazz", "Состояние и данные", "https://jazz.tools/docs", "openSource", "local-first,collaboration,encryption,sync", "npm i jazz-tools",
     "Local-first framework with built-in sync, permissions and end-to-end encryption.",
     "Local-first фреймворк со встроенной синхронизацией, правами доступа и сквозным шифрованием.",
     "Permissions are part of the data model, which most local-first frameworks leave to the application."),
    ("lib-triplit", "Triplit", "Состояние и данные", "https://www.triplit.dev/docs", "openSource", "local-first,sync,relational,typescript", "npm i @triplit/client",
     "Full-stack database with realtime sync and relational queries on the client.",
     "Full-stack база данных с realtime-синхронизацией и реляционными запросами на клиенте.",
     "Relational queries against local data are what most sync engines cannot offer."),
    ("lib-replicache", "Replicache", "Состояние и данные", "https://doc.replicache.dev/", "openSource", "sync,offline,optimistic,rollback", "npm i replicache",
     "Sync framework with optimistic mutations and automatic rollback on conflict.",
     "Фреймворк синхронизации с оптимистичными мутациями и автоматическим откатом при конфликте.",
     "Optimistic updates make the interface instant, and the rollback keeps it correct when the server disagrees."),

    # ---------- Realtime транспорты ----------
    ("lib-uwebsockets", "uWebSockets.js", "Backend и API", "https://github.com/uNetworking/uWebSockets.js", "openSource", "websocket,performance,c-plus-plus,node", "",
     "Extremely fast WebSocket and HTTP server for Node.",
     "Крайне быстрый WebSocket и HTTP-сервер для Node.",
     "Handles far more concurrent connections per process than the standard ws library."),
    ("lib-centrifugo", "Centrifugo", "Очереди и события", "https://centrifugal.dev/docs/getting-started/introduction", "openSource", "realtime,pubsub,language-agnostic,scalable", "",
     "Standalone realtime messaging server usable from any backend language.",
     "Автономный сервер realtime-сообщений, используемый из любого языка бэкенда.",
     "Running it beside an existing backend adds realtime without rewriting anything in Node."),
    ("lib-soketi", "Soketi", "Очереди и события", "https://docs.soketi.app/", "openSource", "pusher-compatible,websocket,self-host,fast", "npm i -g @soketi/soketi",
     "Self-hosted WebSocket server compatible with the Pusher protocol.",
     "Self-hosted WebSocket-сервер, совместимый с протоколом Pusher.",
     "Drop-in for Pusher client libraries, so migrating off Pusher is a configuration change."),
    ("lib-pubnub", "PubNub", "Очереди и события", "https://www.pubnub.com/docs", "freeTier", "realtime,global,presence,managed", "",
     "Managed realtime messaging network with global points of presence.",
     "Управляемая сеть realtime-сообщений с точками присутствия по всему миру.",
     "Its global edge network keeps latency low for geographically spread users."),
    ("lib-phoenix-channels", "Phoenix Channels", "Elixir экосистема", "https://hexdocs.pm/phoenix/channels.html", "openSource", "elixir,realtime,websocket,scalable", "",
     "Elixir's realtime abstraction, handling very large numbers of connections.",
     "Realtime-абстракция Elixir, выдерживающая очень большое число соединений.",
     "The BEAM's lightweight processes are why a single node holds hundreds of thousands of sockets."),
    ("lib-signalr", "SignalR", ".NET экосистема", "https://learn.microsoft.com/en-us/aspnet/core/signalr/introduction", "openSource", "dotnet,realtime,hubs,fallback", "",
     "Realtime communication library for .NET with automatic transport fallback.",
     "Библиотека realtime-коммуникации для .NET с автоматическим переключением транспорта.",
     "Falling back from WebSocket to long polling keeps it working behind restrictive proxies."),
    ("lib-mercure", "Mercure", "Очереди и события", "https://mercure.rocks/docs", "openSource", "sse,protocol,push,open-standard", "",
     "Open protocol for server-sent updates, built on Server-Sent Events.",
     "Открытый протокол серверных обновлений на основе Server-Sent Events.",
     "Simpler than WebSocket when updates only flow from server to client."),
    ("lib-server-sent-events", "Server-Sent Events", "Backend и API", "https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events", "free", "sse,http,one-way,built-in", "",
     "Browser-native one-way streaming from server to client over plain HTTP.",
     "Нативная для браузера односторонняя потоковая передача от сервера к клиенту по обычному HTTP.",
     "Automatic reconnection is built in, which you would otherwise implement yourself over WebSocket."),
    ("lib-webtransport", "WebTransport", "Backend и API", "https://developer.mozilla.org/en-US/docs/Web/API/WebTransport_API", "free", "http3,quic,streams,datagrams", "",
     "Modern low-latency transport over HTTP/3, supporting streams and datagrams.",
     "Современный транспорт с низкой задержкой поверх HTTP/3 с потоками и датаграммами.",
     "Unreliable datagrams suit games and live media where a late packet is worse than a lost one."),

    # ---------- WebRTC ----------
    ("lib-peerjs", "PeerJS", "Видеоконференции", "https://peerjs.com/docs/", "openSource", "webrtc,peer-to-peer,simple,signalling", "npm i peerjs",
     "Simplifies WebRTC peer connections with a small friendly API.",
     "Упрощает WebRTC-соединения между пирами с небольшим удобным API.",
     "You still need a TURN server for users behind restrictive network address translation."),
    ("lib-simple-peer", "simple-peer", "Видеоконференции", "https://github.com/feross/simple-peer", "openSource", "webrtc,minimal,streams,node", "npm i simple-peer",
     "Minimal WebRTC wrapper with a Node stream interface.",
     "Минималистичная обёртка WebRTC с интерфейсом потоков Node.",
     "Small enough to read completely, which helps a great deal when debugging WebRTC negotiation."),
    ("lib-mediasoup", "mediasoup", "Видеоконференции", "https://mediasoup.org/documentation/v3/", "openSource", "sfu,webrtc,scalable,node", "npm i mediasoup",
     "WebRTC selective forwarding unit for scalable multi-party video.",
     "WebRTC SFU для масштабируемого многостороннего видео.",
     "An SFU is required past a handful of participants — peer-to-peer mesh stops scaling quickly."),
    ("lib-janus-webrtc", "Janus WebRTC Server", "Видеоконференции", "https://janus.conf.meetecho.com/docs/", "openSource", "webrtc,gateway,plugins,c", "",
     "General-purpose WebRTC server with a plugin architecture.",
     "Универсальный WebRTC-сервер с архитектурой плагинов.",
     "Its plugins cover streaming, recording and SIP gateway roles in one deployment."),
    ("lib-pion", "Pion", "Видеоконференции", "https://github.com/pion/webrtc", "openSource", "webrtc,go,pure-go,building-blocks", "go get github.com/pion/webrtc/v4",
     "Pure Go implementation of WebRTC.",
     "Реализация WebRTC на чистом Go.",
     "No cgo dependency means it cross-compiles as easily as any other Go program."),
]
