# -*- coding: utf-8 -*-
"""Stage 5 library pack AI: test runners, browser automation, mocking, property testing, load testing."""

LIBS_5AI = [
    # ---------- Тест-раннеры ----------
    ("lib-mocha", "Mocha", "Тестирование и качество", "https://mochajs.org/", "openSource", "node,test-runner,flexible,mature", "npm i -D mocha",
     "Long-established flexible JavaScript test runner with pluggable assertions.",
     "Давно устоявшийся гибкий JavaScript-раннер тестов с подключаемыми библиотеками утверждений.",
     "It brings no assertion library, so pair it with Chai — that flexibility is the point."),
    ("lib-ava", "AVA", "Тестирование и качество", "https://github.com/avajs/ava", "openSource", "node,concurrent,minimal,isolated", "npm i -D ava",
     "Concurrent test runner executing each file in its own process.",
     "Конкурентный раннер тестов, выполняющий каждый файл в отдельном процессе.",
     "Process isolation makes shared-state leakage between tests structurally impossible."),
    ("lib-node-test-runner", "Node Test Runner", "Тестирование и качество", "https://nodejs.org/api/test.html", "free", "node,built-in,zero-dependency,stable", "",
     "Test runner built into Node, requiring no external dependency.",
     "Раннер тестов, встроенный в Node и не требующий внешних зависимостей.",
     "Enough for a library with modest needs, and it removes a whole dependency tree from CI."),
    ("lib-unittest", "unittest", "Тестирование и качество", "https://docs.python.org/3/library/unittest.html", "free", "python,standard-library,xunit,built-in", "",
     "Python's built-in xUnit-style testing framework.",
     "Встроенный в Python фреймворк тестирования в стиле xUnit.",
     "pytest runs unittest tests unchanged, so migrating is additive rather than a rewrite."),
    ("lib-tox", "tox", "Тестирование и качество", "https://tox.wiki/", "openSource", "python,matrix,environments,automation", "pipx install tox",
     "Runs Python test suites across multiple interpreter versions and environments.",
     "Запускает наборы тестов Python на нескольких версиях интерпретатора и в разных окружениях.",
     "Catches version-specific breakage locally, before a CI matrix finds it for you."),
    ("lib-nox", "nox", "Тестирование и качество", "https://nox.thea.codes/", "openSource", "python,sessions,configuration-as-code,automation", "pipx install nox",
     "Test automation where environments are configured in ordinary Python.",
     "Автоматизация тестирования, где окружения настраиваются на обычном Python.",
     "Python configuration handles conditional logic that tox's INI format cannot express."),

    # ---------- Браузерная автоматизация ----------
    ("lib-webdriverio", "WebdriverIO", "Тестирование и качество", "https://webdriver.io/docs/gettingstarted", "openSource", "webdriver,e2e,mobile,extensible", "npm init wdio@latest",
     "Automation framework covering web and mobile via WebDriver and DevTools.",
     "Фреймворк автоматизации для веба и мобильных устройств через WebDriver и DevTools.",
     "One framework across browsers and native mobile apps, which most competitors do not span."),
    ("lib-selenium", "Selenium", "Тестирование и качество", "https://www.selenium.dev/documentation/", "openSource", "webdriver,standard,cross-browser,mature", "",
     "The original browser automation standard, with bindings in every major language.",
     "Оригинальный стандарт автоматизации браузера с биндингами на всех основных языках.",
     "WebDriver is a W3C standard, which is why it survives where vendor-specific tools do not."),
    ("lib-nightwatch", "Nightwatch.js", "Тестирование и качество", "https://nightwatchjs.org/guide/", "openSource", "e2e,integrated,webdriver,component-testing", "npm i -D nightwatch",
     "Integrated end-to-end testing framework with its own runner and assertions.",
     "Интегрированный фреймворк E2E-тестирования с собственным раннером и утверждениями.",
     "Batteries-included setup avoids assembling a runner, driver and assertion library yourself."),
    ("lib-testcafe", "TestCafe", "Тестирование и качество", "https://testcafe.io/documentation/", "openSource", "e2e,no-webdriver,automatic-waits,proxy", "npm i -D testcafe",
     "End-to-end testing that needs no WebDriver and waits for elements automatically.",
     "E2E-тестирование без WebDriver с автоматическим ожиданием элементов.",
     "Its proxy-based approach means no browser driver to install or keep in version sync."),
    ("lib-jsdom", "jsdom", "Тестирование и качество", "https://github.com/jsdom/jsdom", "openSource", "dom,node,standards,simulation", "npm i -D jsdom",
     "Pure JavaScript implementation of web standards for Node environments.",
     "Реализация веб-стандартов на чистом JavaScript для окружений Node.",
     "The most standards-complete option, and the default DOM behind Jest's test environment."),

    # ---------- Моки и тестовые данные ----------
    ("lib-sinon", "Sinon.JS", "Тестирование и качество", "https://sinonjs.org/releases/latest/", "openSource", "spies,stubs,mocks,timers", "npm i -D sinon",
     "Standalone spies, stubs, mocks and fake timers for JavaScript tests.",
     "Автономные шпионы, заглушки, моки и фиктивные таймеры для JavaScript-тестов.",
     "Its fake timers make time-dependent code testable without any real waiting."),
    ("lib-polly-js", "Polly.JS", "Тестирование и качество", "https://netflix.github.io/pollyjs/", "openSource", "http,record-replay,netflix,fixtures", "npm i -D @pollyjs/core",
     "Records and replays HTTP interactions for deterministic tests.",
     "Записывает и воспроизводит HTTP-взаимодействия для детерминированных тестов.",
     "Recorded fixtures keep tests fast and offline while still matching the real API's responses."),
    ("lib-wiremock", "WireMock", "Тестовые и mock API", "https://wiremock.org/docs/", "openSource", "http,mocking,stubbing,java", "",
     "HTTP mock server for stubbing and verifying service interactions.",
     "HTTP mock-сервер для заглушек и проверки взаимодействий между сервисами.",
     "Its fault and delay injection tests how your client behaves when a dependency misbehaves."),
    ("lib-prism-mock", "Prism", "Тестовые и mock API", "https://docs.stoplight.io/docs/prism/", "openSource", "openapi,mocking,validation,stoplight", "npm i -g @stoplight/prism-cli",
     "Mock server generated directly from an OpenAPI description.",
     "Mock-сервер, генерируемый напрямую из OpenAPI-описания.",
     "Frontend work can start against the spec before the backend exists, with no hand-written mocks."),
    ("lib-fishery", "Fishery", "Тестирование и качество", "https://github.com/thoughtbot/fishery", "openSource", "factories,typescript,test-data,thoughtbot", "npm i -D fishery",
     "Typed test data factories for TypeScript.",
     "Типизированные фабрики тестовых данных для TypeScript.",
     "Factories keep tests readable by naming only the fields a given test actually cares about."),
    ("lib-factory-boy", "factory_boy", "Тестирование и качество", "https://factoryboy.readthedocs.io/", "openSource", "python,fixtures,django,factories", "pip install factory_boy",
     "Test fixture factories for Python, with strong Django ORM support.",
     "Фабрики тестовых фикстур для Python с сильной поддержкой Django ORM.",
     "Its sub-factories build related object graphs, which flat fixture files handle badly."),

    # ---------- Property-based тестирование ----------
    ("lib-fast-check", "fast-check", "Тестирование и качество", "https://fast-check.dev/docs/introduction/", "openSource", "property-based,javascript,shrinking,generators", "npm i -D fast-check",
     "Property-based testing for JavaScript with automatic counterexample shrinking.",
     "Property-based тестирование для JavaScript с автоматическим упрощением контрпримеров.",
     "Shrinking reduces a random failure to a minimal reproducible case, which is what makes it usable."),
    ("lib-quickcheck", "QuickCheck", "Тестирование и качество", "https://hackage.haskell.org/package/QuickCheck", "openSource", "haskell,property-based,original,generators", "",
     "The original property-based testing library, from Haskell.",
     "Оригинальная библиотека property-based тестирования из Haskell.",
     "Every property testing tool in other languages traces its design back to this one."),
    ("lib-jqwik", "jqwik", "Тестирование и качество", "https://jqwik.net/docs/current/user-guide.html", "openSource", "java,property-based,junit5,generators", "",
     "Property-based testing for Java, integrated with JUnit 5.",
     "Property-based тестирование для Java, интегрированное с JUnit 5.",
     "Runs alongside ordinary JUnit tests, so adoption can be one test class at a time."),
    ("lib-proper", "PropEr", "Тестирование и качество", "https://proper-testing.github.io/", "openSource", "erlang,elixir,property-based,state-machines", "",
     "Property-based testing for Erlang and Elixir, including stateful models.",
     "Property-based тестирование для Erlang и Elixir, включая модели с состоянием.",
     "Its state machine testing explores interleavings that hand-written concurrency tests never reach."),

    # ---------- Контрактное тестирование ----------
    ("lib-pact", "Pact", "Тестирование и качество", "https://docs.pact.io/", "openSource", "contract-testing,consumer-driven,microservices,broker", "",
     "Consumer-driven contract testing between services.",
     "Контрактное тестирование между сервисами, управляемое потребителем.",
     "Catches breaking API changes in CI without standing up every service in an integration environment."),
    ("lib-spring-cloud-contract", "Spring Cloud Contract", "JVM экосистема", "https://docs.spring.io/spring-cloud-contract/reference/", "openSource", "contract-testing,spring,jvm,stubs", "",
     "Contract testing and stub generation for Spring-based services.",
     "Контрактное тестирование и генерация заглушек для сервисов на Spring.",
     "Generates both the provider test and the consumer stub from one contract definition."),
    ("lib-karate", "Karate", "Тестирование и качество", "https://karatelabs.github.io/karate/", "openSource", "api-testing,bdd,no-code,java", "",
     "API test automation with a readable DSL requiring no Java code.",
     "Автоматизация тестирования API на читаемом DSL, не требующем Java-кода.",
     "Its DSL is approachable enough that testers write API suites without a developer."),
    ("lib-rest-assured", "REST Assured", "JVM экосистема", "https://rest-assured.io/", "openSource", "java,api-testing,fluent,validation", "",
     "Fluent Java DSL for testing REST services.",
     "Текучий Java-DSL для тестирования REST-сервисов.",
     "Its given/when/then chaining keeps API assertions readable inside ordinary JUnit tests."),
    ("lib-newman", "Newman", "Тестирование и качество", "https://github.com/postmanlabs/newman", "openSource", "postman,cli,collections,ci", "npm i -g newman",
     "Command-line runner executing Postman collections in CI.",
     "Раннер командной строки, выполняющий коллекции Postman в CI.",
     "Turns collections your team already maintains into automated CI checks with no rewriting."),

    # ---------- Нагрузочное тестирование ----------
    ("lib-gatling", "Gatling", "Тестирование и качество", "https://docs.gatling.io/", "openSource", "load-testing,scala,jvm,reports", "",
     "High-performance load testing on the JVM with detailed HTML reports.",
     "Высокопроизводительное нагрузочное тестирование на JVM с подробными HTML-отчётами.",
     "Its async engine drives far more virtual users per machine than thread-per-user tools."),
    ("lib-vegeta", "Vegeta", "Тестирование и качество", "https://github.com/tsenart/vegeta", "openSource", "load-testing,go,constant-rate,cli", "",
     "HTTP load testing tool that sustains a constant request rate.",
     "Инструмент HTTP-нагрузки, удерживающий постоянную частоту запросов.",
     "Constant-rate testing reveals latency under a fixed load, which concurrency-based tools obscure."),
    ("lib-wrk", "wrk", "Тестирование и качество", "https://github.com/wg/wrk", "openSource", "benchmarking,http,c,lua", "",
     "Minimal high-performance HTTP benchmarking tool.",
     "Минималистичный высокопроизводительный инструмент HTTP-бенчмаркинга.",
     "Its Lua scripting covers custom request patterns without leaving the single-binary model."),
    ("lib-autocannon", "autocannon", "Тестирование и качество", "https://github.com/mcollina/autocannon", "openSource", "benchmarking,node,http,fast", "npm i -g autocannon",
     "Fast HTTP benchmarking tool written in Node.",
     "Быстрый инструмент HTTP-бенчмаркинга, написанный на Node.",
     "Scriptable from Node, so benchmarks can live in the same repository as the service."),
]
