# -*- coding: utf-8 -*-
"""Stage 5 library pack W: security scanning, supply chain, secrets, authz engines."""

LIBS_5W = [
    # ---------- Безопасность: сканирование кода и образов ----------
    ("lib-grype", "Grype", "Безопасность и секреты", "https://github.com/anchore/grype", "openSource", "vulnerabilities,containers,sbom,scanner", "brew install grype",
     "Vulnerability scanner for container images and filesystems, driven by SBOM data.",
     "Сканер уязвимостей для образов контейнеров и файловых систем на основе данных SBOM.",
     "Pairs with Syft: generate the SBOM once, then rescan it as new CVEs are published without rebuilding."),
    ("lib-syft", "Syft", "Безопасность и секреты", "https://github.com/anchore/syft", "openSource", "sbom,inventory,containers,supply-chain", "brew install syft",
     "Generates a software bill of materials from container images and source trees.",
     "Генерирует software bill of materials из образов контейнеров и исходных деревьев.",
     "An SBOM committed with each release is what makes 'are we affected by this CVE' answerable in minutes."),
    ("lib-checkov", "Checkov", "Безопасность и секреты", "https://www.checkov.io/1.Welcome/What%20is%20Checkov.html", "openSource", "iac,policy,terraform,static-analysis", "pip install checkov",
     "Static analysis for infrastructure as code, catching misconfigurations before apply.",
     "Статический анализ infrastructure as code, ловящий ошибки конфигурации до применения.",
     "Run it in the PR check rather than pre-apply — a public S3 bucket caught in review costs nothing."),
    ("lib-tfsec", "tfsec", "Безопасность и секреты", "https://aquasecurity.github.io/tfsec/", "openSource", "terraform,security,static-analysis,iac", "brew install tfsec",
     "Terraform-focused security scanner, now merged into the Trivy project.",
     "Сканер безопасности, ориентированный на Terraform, теперь объединён с проектом Trivy.",
     "New work goes into Trivy's IaC mode — prefer that for greenfield rather than the standalone binary."),
    ("lib-trufflehog", "TruffleHog", "Безопасность и секреты", "https://github.com/trufflesecurity/trufflehog", "openSource", "secrets,scanning,git-history,verification", "",
     "Scans repositories and history for leaked credentials, then verifies whether they still work.",
     "Сканирует репозитории и историю на утёкшие учётные данные и проверяет, работают ли они ещё.",
     "Live verification is the differentiator — it separates real active leaks from expired noise."),
    ("lib-nuclei", "Nuclei", "Безопасность и секреты", "https://docs.projectdiscovery.io/tools/nuclei/overview", "openSource", "scanning,templates,dast,community", "",
     "Template-driven vulnerability scanner with a large community template library.",
     "Сканер уязвимостей на шаблонах с большой библиотекой шаблонов от сообщества.",
     "Only scan systems you own or are authorized to test — the templates are genuinely intrusive."),
    ("lib-owasp-zap", "OWASP ZAP", "Безопасность и секреты", "https://www.zaproxy.org/docs/", "openSource", "dast,web-security,proxy,owasp", "",
     "Open-source dynamic application security testing proxy for web applications.",
     "Открытый прокси динамического тестирования безопасности веб-приложений.",
     "Its baseline scan runs in CI in a couple of minutes, unlike the full active scan."),
    ("lib-openvas", "OpenVAS / Greenbone", "Безопасность и секреты", "https://greenbone.github.io/docs/", "openSource", "vulnerability-scanning,network,infrastructure,open-source", "",
     "Open-source network vulnerability scanner with a large regularly updated test feed.",
     "Открытый сетевой сканер уязвимостей с большим регулярно обновляемым набором тестов.",
     "Feed synchronization is the slow part of setup — plan for the initial sync before the first scan."),
    ("lib-burp-suite", "Burp Suite", "Безопасность и секреты", "https://portswigger.net/burp/documentation", "mixed", "web-security,proxy,pentest,intercept", "",
     "The standard interception proxy and web security testing toolkit.",
     "Стандартный перехватывающий прокси и набор инструментов тестирования веб-безопасности.",
     "The Community edition covers manual testing; the scanner and automation are what the licence buys."),

    # ---------- Безопасность: runtime и мониторинг ----------
    ("lib-falco", "Falco", "Безопасность и секреты", "https://falco.org/docs/", "openSource", "runtime-security,kubernetes,ebpf,detection", "",
     "Runtime security monitoring detecting anomalous behaviour in containers via kernel events.",
     "Мониторинг безопасности во время выполнения: выявляет аномальное поведение контейнеров по событиям ядра.",
     "Tune the default ruleset before enabling alerts — out of the box it is noisy on normal workloads."),
    ("lib-osquery", "osquery", "Безопасность и секреты", "https://osquery.readthedocs.io/", "openSource", "endpoint,sql,visibility,fleet", "",
     "Exposes operating system state as SQL tables you can query across a fleet.",
     "Представляет состояние операционной системы как SQL-таблицы, доступные для запросов по всему парку машин.",
     "Asking 'which hosts run this vulnerable version' becomes one SQL query rather than a survey."),
    ("lib-wazuh", "Wazuh", "Безопасность и секреты", "https://documentation.wazuh.com/", "openSource", "siem,xdr,endpoint,compliance", "",
     "Open-source SIEM and XDR platform with agents for endpoint detection and compliance.",
     "Открытая платформа SIEM и XDR с агентами для обнаружения на конечных точках и комплаенса.",
     "A full SIEM without licence cost, at the price of running and tuning the whole stack yourself."),
    ("lib-crowdsec", "CrowdSec", "Безопасность и секреты", "https://docs.crowdsec.net/", "openSource", "ips,behavioral,community,blocklists", "",
     "Behaviour-based intrusion prevention that shares attacker signals across a community network.",
     "Предотвращение вторжений на основе поведения с обменом сигналами об атакующих внутри сообщества.",
     "The shared blocklist means you benefit from attacks against other participants, not just your own logs."),
    ("lib-suricata", "Suricata", "Безопасность и секреты", "https://docs.suricata.io/", "openSource", "ids,ips,network,packet-inspection", "",
     "High-performance network IDS/IPS with deep packet inspection and protocol parsing.",
     "Высокопроизводительная сетевая IDS/IPS с глубоким анализом пакетов и разбором протоколов.",
     "Multi-threaded, unlike Snort's classic engine, which is why it keeps up on high-bandwidth links."),
    ("lib-zeek", "Zeek", "Безопасность и секреты", "https://docs.zeek.org/", "openSource", "network-monitoring,logs,forensics,scripting", "",
     "Network analysis framework producing rich connection logs rather than firing alerts.",
     "Фреймворк сетевого анализа, выдающий подробные логи соединений, а не срабатывающие оповещения.",
     "Its logs are the forensic record — you use them after an incident, where an IDS alert tells you nothing."),

    # ---------- Цепочка поставок ПО ----------
    ("lib-sigstore", "Sigstore", "Безопасность и секреты", "https://docs.sigstore.dev/", "openSource", "signing,supply-chain,transparency,keyless", "",
     "Keyless artifact signing backed by a public transparency log.",
     "Подписание артефактов без ключей с публичным журналом прозрачности.",
     "Keyless signing removes long-lived private keys entirely, which is where most signing schemes fail in practice."),
    ("lib-cosign", "cosign", "Безопасность и секреты", "https://docs.sigstore.dev/cosign/signing/overview/", "openSource", "containers,signing,verification,sigstore", "brew install cosign",
     "Signs and verifies container images and other OCI artifacts.",
     "Подписывает и проверяет образы контейнеров и другие OCI-артефакты.",
     "Enforce verification in an admission controller — signing without verification changes nothing."),
    ("lib-in-toto", "in-toto", "Безопасность и секреты", "https://in-toto.io/docs/", "openSource", "supply-chain,attestation,provenance,framework", "",
     "Framework for cryptographically attesting each step of a software supply chain.",
     "Фреймворк криптографического подтверждения каждого шага цепочки поставок ПО.",
     "Proves the artifact came from the build you think it did, not merely that someone signed it."),
    ("lib-slsa", "SLSA", "Безопасность и секреты", "https://slsa.dev/spec/v1.0/", "free", "supply-chain,levels,provenance,framework", "",
     "Graded framework of supply chain security levels, from source to build provenance.",
     "Градуированный фреймворк уровней безопасности цепочки поставок — от исходников до провенанса сборки.",
     "Start at level 1 (provenance exists) — the higher levels require build-platform changes, not just policy."),
    ("lib-ossf-scorecard", "OpenSSF Scorecard", "Безопасность и секреты", "https://github.com/ossf/scorecard", "openSource", "supply-chain,health,checks,open-source", "",
     "Automated checks scoring an open-source project's security practices.",
     "Автоматические проверки, оценивающие практики безопасности open-source проекта.",
     "Useful as a dependency-selection input — a low score is a signal about maintenance, not just security."),
    ("lib-age-encryption", "age", "Безопасность и секреты", "https://github.com/FiloSottile/age", "openSource", "encryption,files,simple,modern", "brew install age",
     "Simple modern file encryption tool with no configuration knobs to get wrong.",
     "Простой современный инструмент шифрования файлов без настроек, которые можно испортить.",
     "Deliberately has no options — that is the security feature, versus GPG's many footguns."),

    # ---------- Секреты и идентификация ----------
    ("lib-keycloak", "Keycloak", "Аутентификация", "https://www.keycloak.org/documentation", "openSource", "sso,oidc,saml,identity", "",
     "Full-featured open-source identity and access management server.",
     "Полнофункциональный открытый сервер управления идентификацией и доступом.",
     "Covers SAML alongside OIDC, which is what enterprise customers ask for and lighter alternatives lack."),
    ("lib-ory-kratos", "Ory Kratos", "Аутентификация", "https://www.ory.sh/docs/kratos", "openSource", "identity,self-hosted,api-first,flows", "",
     "Headless identity server handling registration, login and account recovery flows.",
     "Headless-сервер идентификации, обрабатывающий регистрацию, вход и восстановление аккаунта.",
     "API-first with no bundled UI — you own the login screens, which is exactly why teams pick it."),
    ("lib-ory-hydra", "Ory Hydra", "Аутентификация", "https://www.ory.sh/docs/hydra", "openSource", "oauth2,oidc,provider,certified", "",
     "Certified OAuth 2.0 and OpenID Connect provider, deliberately without its own user store.",
     "Сертифицированный провайдер OAuth 2.0 и OpenID Connect, намеренно без собственного хранилища пользователей.",
     "Pairs with Kratos or your existing user database — it issues tokens, it does not manage accounts."),
    ("lib-authentik", "authentik", "Аутентификация", "https://docs.goauthentik.io/", "openSource", "sso,idp,proxy,self-host", "",
     "Self-hosted identity provider with SSO, a forward-auth proxy and flexible flows.",
     "Self-hosted провайдер идентификации с SSO, forward-auth прокси и гибкими сценариями.",
     "Its proxy provider adds authentication in front of apps that have none of their own."),
    ("lib-zitadel", "Zitadel", "Аутентификация", "https://zitadel.com/docs", "openSource", "identity,multi-tenant,go,cloud-native", "",
     "Cloud-native identity platform with multi-tenancy and audit trails built in.",
     "Cloud-native платформа идентификации со встроенной мультиарендностью и журналами аудита.",
     "Multi-tenancy at the core makes it a better fit than Keycloak for B2B SaaS with customer organizations."),

    # ---------- Авторизация и политики ----------
    ("lib-opa", "Open Policy Agent", "Аутентификация", "https://www.openpolicyagent.org/docs/", "openSource", "policy,rego,authorization,cncf", "",
     "General-purpose policy engine using the Rego language, decoupled from your application.",
     "Универсальный движок политик на языке Rego, отделённый от вашего приложения.",
     "Rego has a real learning curve — write tests for policies, they are as easy to get wrong as code."),
    ("lib-cedar-policy", "Cedar", "Аутентификация", "https://docs.cedarpolicy.com/", "openSource", "authorization,policy,aws,verifiable", "",
     "AWS's authorization policy language, designed to be analyzable and fast to evaluate.",
     "Язык политик авторизации от AWS, спроектированный анализируемым и быстрым в вычислении.",
     "Formal analysis tooling can prove properties about your policies, which Rego cannot offer."),
    ("lib-spicedb", "SpiceDB", "Аутентификация", "https://authzed.com/docs", "openSource", "zanzibar,relationships,fine-grained,graph", "",
     "Google Zanzibar-inspired database for fine-grained relationship-based permissions.",
     "База данных на идеях Google Zanzibar для детальных разрешений на основе отношений.",
     "The right model when permissions are graph-shaped ('editors of the parent folder'), not role-shaped."),
    ("lib-cerbos", "Cerbos", "Аутентификация", "https://docs.cerbos.dev/", "openSource", "authorization,policy,yaml,stateless", "",
     "Stateless authorization service with policies defined in readable YAML.",
     "Stateless-сервис авторизации с политиками в читаемом YAML.",
     "Policies in YAML are reviewable by non-engineers, unlike Rego — often the deciding factor over OPA."),
    ("lib-permit-io", "Permit.io", "Аутентификация", "https://docs.permit.io/", "freeTier", "authorization,rbac,rebac,ui", "",
     "Authorization platform with a UI for managing RBAC and ReBAC policies across services.",
     "Платформа авторизации с интерфейсом управления политиками RBAC и ReBAC между сервисами.",
     "The admin UI lets product owners change permissions without a deploy, which is its main selling point."),
    ("lib-wiz-security", "Wiz", "Безопасность и секреты", "https://www.wiz.io/", "paid", "cnapp,cloud-security,agentless,enterprise", "",
     "Agentless cloud security platform scanning workloads and mapping attack paths.",
     "Безагентная платформа облачной безопасности: сканирует нагрузки и строит пути атак.",
     "Attack-path analysis prioritizes the handful of findings that actually chain into a breach."),
]
