# -*- coding: utf-8 -*-
"""Stage 5 API pack O: social platforms, dev community, package registries, misc."""

APIS_5O = [
    # ---------- Новости и сообщества (deepen) ----------
    ("api-linkedin", "LinkedIn API", "Новости и сообщества", "https://learn.microsoft.com/linkedin/", "mixed", "linkedin,social,professional,oauth", "",
     "Profile, sharing and marketing APIs for the professional network.",
     "API профилей, публикаций и маркетинга для профессиональной сети.",
     "Most useful scopes need Partner Program approval — check eligibility before designing around them."),
    ("api-x-twitter", "X API", "Новости и сообщества", "https://docs.x.com/", "paid", "twitter,social,posts,streaming", "",
     "Post, read and stream content on X (formerly Twitter).",
     "Публикация, чтение и стриминг контента в X (бывший Twitter).",
     "The free tier is write-only with tight caps — reading timelines at any volume requires a paid plan."),
    ("api-threads", "Threads API", "Новости и сообщества", "https://developers.facebook.com/docs/threads", "free", "threads,meta,social,posting", "",
     "Publish and read posts on Meta's Threads platform.",
     "Публикация и чтение постов на платформе Threads от Meta.",
     "Rate limits are per-user, not per-app, which shapes how a multi-user scheduling tool must be designed."),
    ("api-instagram-graph", "Instagram Graph API", "Новости и сообщества", "https://developers.facebook.com/docs/instagram-platform", "free", "instagram,meta,media,business", "",
     "Media publishing and insights for Instagram Business and Creator accounts.",
     "Публикация медиа и аналитика для бизнес- и креатор-аккаунтов Instagram.",
     "Personal accounts are not supported at all — the account must be converted to Business or Creator first."),
    ("api-tiktok", "TikTok for Developers", "Новости и сообщества", "https://developers.tiktok.com/doc/overview/", "free", "tiktok,video,social,content-posting", "",
     "Content posting, login and display APIs for TikTok.",
     "API публикации контента, входа и отображения для TikTok.",
     "App review is required before production access, and the review process is genuinely strict."),

    # ---------- Разработка и DevOps: package registries ----------
    ("api-jsr", "JSR", "Разработка и DevOps", "https://jsr.io/docs", "free", "registry,typescript,deno,modules", "",
     "TypeScript-first package registry working across Deno, Node and Bun.",
     "Реестр пакетов с приоритетом TypeScript, работает в Deno, Node и Bun.",
     "It publishes TypeScript source directly, so consumers get real types rather than generated declarations."),
    ("api-nuget", "NuGet API", "Разработка и DevOps", "https://learn.microsoft.com/nuget/api/overview", "free", "dotnet,packages,registry,versions", "",
     "Package metadata and versions for the .NET ecosystem.",
     "Метаданные и версии пакетов экосистемы .NET.",
     "The service index endpoint is the entry point — resource URLs are discovered from it, not hardcoded."),
    ("api-maven-central", "Maven Central Search", "Разработка и DevOps", "https://central.sonatype.org/search/rest-api-guide/", "free", "java,packages,maven,search", "",
     "Search and metadata API for Java artifacts on Maven Central.",
     "API поиска и метаданных Java-артефактов в Maven Central.",
     "Useful for automating dependency-version checks in a JVM project without scraping the web UI."),
    ("api-rubygems", "RubyGems API", "Разработка и DevOps", "https://guides.rubygems.org/rubygems-org-api/", "free", "ruby,gems,packages,versions", "",
     "Gem metadata, versions and download statistics for the Ruby ecosystem.",
     "Метаданные, версии и статистика загрузок гемов Ruby.",
     "The versions endpoint returns the full release history in one call, which suits changelog tooling."),
    ("api-homebrew", "Homebrew Formulae API", "Разработка и DevOps", "https://formulae.brew.sh/docs/api/", "free", "homebrew,macos,packages,json", "",
     "JSON metadata for every Homebrew formula and cask.",
     "JSON-метаданные для каждой формулы и cask в Homebrew.",
     "Analytics endpoints expose install counts, which is a rough proxy for a macOS tool's real-world popularity."),

    # ---------- Утилиты (deepen) ----------
    ("api-ipify", "ipify", "Утилиты", "https://www.ipify.org/", "noKey", "ip,simple,no-key,utility", "",
     "Returns the caller's public IP address, no key and no rate limit.",
     "Возвращает публичный IP-адрес вызывающего, без ключа и без лимитов.",
     "About as simple as an API gets, which makes it a reliable connectivity check in scripts."),
    ("api-urlscan", "urlscan.io", "Безопасность и секреты", "https://urlscan.io/docs/api/", "freeTier", "security,scanning,urls,phishing", "",
     "Scans and analyses URLs, capturing screenshots, requests and detected technologies.",
     "Сканирует и анализирует URL, сохраняя скриншоты, запросы и обнаруженные технологии.",
     "Public scans are visible to everyone — mark scans private when the URL contains anything sensitive."),
    ("api-shodan", "Shodan", "Безопасность и секреты", "https://developer.shodan.io/", "paid", "security,scanning,devices,recon", "",
     "Search engine for internet-connected devices and exposed services.",
     "Поисковая система по устройствам и открытым сервисам в интернете.",
     "Use it to audit your own exposed surface — searching others' infrastructure has legal implications."),
    ("api-securitytrails", "SecurityTrails", "Безопасность и секреты", "https://docs.securitytrails.com/", "freeTier", "dns,domains,security,history", "",
     "Historical DNS and domain intelligence data.",
     "Исторические данные DNS и доменной разведки.",
     "DNS history is useful for verifying infrastructure changes during an incident postmortem."),
    ("api-cloudmersive", "Cloudmersive", "Утилиты", "https://api.cloudmersive.com/", "freeTier", "conversion,validation,virus-scan,utility", "",
     "Grab-bag utility APIs: document conversion, validation, virus scanning, OCR.",
     "Набор утилитарных API: конвертация документов, валидация, антивирус, OCR.",
     "Convenient for one-off needs, but a dedicated service usually wins on quality for any single task."),
]
