# -*- coding: utf-8 -*-
"""Stage 5 library pack D: mobile/desktop, more AI-frameworks, CLI/testing depth."""

LIBS_5D = [
    # ---------- Мобильная и desktop разработка (deepen) ----------
    ("lib-nativescript", "NativeScript", "Мобильная и desktop разработка", "https://docs.nativescript.org/", "openSource", "mobile,native,javascript,cross-platform", "npm i -g nativescript",
     "Cross-platform native mobile apps from JavaScript/TypeScript, with direct native API access.",
     "Кроссплатформенные нативные мобильные приложения на JavaScript/TypeScript с прямым доступом к нативному API.",
     "Direct native API access from JS means you rarely need a plugin for platform-specific features."),
    ("lib-maui", ".NET MAUI", "Мобильная и desktop разработка", "https://learn.microsoft.com/dotnet/maui/", "openSource", "mobile,desktop,csharp,cross-platform", "",
     "Microsoft's cross-platform framework for mobile and desktop apps in C# and XAML.",
     "Кроссплатформенный фреймворк Microsoft для мобильных и desktop-приложений на C# и XAML.",
     "Shares most code with existing Xamarin.Forms apps, easing migration for teams already on that stack."),
    ("lib-neutralinojs", "NeutralinoJS", "Мобильная и desktop разработка", "https://neutralino.js.org/docs/", "openSource", "desktop,lightweight,webview,no-node", "npx @neutralinojs/neu create",
     "Lightweight desktop app framework with no Node.js runtime bundled, using the system webview.",
     "Лёгкий фреймворк desktop-приложений без встроенного Node.js рантайма, использует системный webview.",
     "No bundled runtime means smaller binaries than Electron or even Tauri in some configurations."),
    ("lib-kotlin-multiplatform-mobile", "Kotlin Multiplatform Mobile", "Мобильная и desktop разработка", "https://www.jetbrains.com/kotlin-multiplatform/", "openSource", "kotlin,mobile,shared-logic,jetbrains", "",
     "Share business logic between iOS and Android while keeping fully native UI on each.",
     "Общая бизнес-логика между iOS и Android при полностью нативном UI на каждой платформе.",
     "Share only the logic layer, not the UI — that's the specific tradeoff KMM makes versus Flutter/React Native."),
    ("lib-expo-router", "Expo Router", "Мобильная и desktop разработка", "https://docs.expo.dev/router/introduction/", "openSource", "react-native,expo,routing,file-based", "npx create-expo-app",
     "File-based routing for React Native and web, built by the Expo team.",
     "Файловая маршрутизация для React Native и web от команды Expo.",
     "One route tree targets iOS, Android and web simultaneously — no separate router setup per platform."),

    # ---------- AI-фреймворки (deepen) ----------
    ("lib-autogen-2", "AutoGen", "AI-фреймворки", "https://microsoft.github.io/autogen/", "openSource", "agents,microsoft,conversation,multi-agent", "pip install autogen-agentchat",
     "Microsoft Research's framework for conversational multi-agent workflows.",
     "Фреймворк Microsoft Research для диалоговых мультиагентных workflow.",
     "The conversation-based model fits debate/critique patterns better than strict sequential pipelines."),
    ("lib-txtai", "txtai", "AI-фреймворки", "https://neuml.github.io/txtai/", "openSource", "embeddings,search,rag,all-in-one", "pip install txtai",
     "All-in-one embeddings database: search, RAG and workflows in a single lightweight library.",
     "Универсальная база эмбеддингов: поиск, RAG и workflow в одной лёгкой библиотеке.",
     "It runs fully embedded with no external vector-database service — good for a single-process prototype."),

    # ---------- CLI и терминал (deepen) ----------
    ("lib-charm-bubbletea", "Bubble Tea", "CLI и терминал", "https://github.com/charmbracelet/bubbletea", "openSource", "go,tui,terminal,framework", "go get github.com/charmbracelet/bubbletea",
     "Elm-architecture terminal UI framework for Go, behind many modern polished CLIs.",
     "TUI-фреймворк для Go на архитектуре Elm, лежит в основе многих современных CLI с хорошим UI.",
     "The model-update-view pattern from Elm keeps even complex terminal UIs testable and predictable."),
    ("lib-ratatui", "Ratatui", "CLI и терминал", "https://ratatui.rs/", "openSource", "rust,tui,terminal,framework", "cargo add ratatui",
     "Rust terminal UI library, the modern successor to tui-rs.",
     "Библиотека TUI для Rust, современный преемник tui-rs.",
     "Immediate-mode rendering means you redraw the whole frame each tick — simpler to reason about than diffing."),
    ("lib-textual", "Textual", "CLI и терминал", "https://textual.textualize.io/", "openSource", "python,tui,terminal,css", "pip install textual",
     "Python TUI framework styled with CSS-like rules, from the Rich library's authors.",
     "Python-фреймворк TUI со стилизацией в духе CSS от авторов библиотеки Rich.",
     "Apps built with it also run as a web page unmodified via textual serve — handy for quick sharing."),
    ("lib-oclif", "oclif", "CLI и терминал", "https://oclif.io/docs/introduction", "openSource", "cli,node,framework,plugins", "npm i -g oclif",
     "CLI framework used to build the Heroku and Salesforce CLIs, with a plugin architecture.",
     "Фреймворк для CLI, на котором построены Heroku и Salesforce CLI, с архитектурой плагинов.",
     "The plugin system is what lets a CLI grow commands over time without one monolithic codebase."),
    ("lib-clap-rust", "clap", "CLI и терминал", "https://docs.rs/clap/latest/clap/", "openSource", "rust,cli,argument-parsing,derive", "cargo add clap",
     "The standard Rust argument parser, with a derive macro for defining CLIs from structs.",
     "Стандартный парсер аргументов Rust с derive-макросом для описания CLI через структуры.",
     "The derive API generates --help output automatically — write the struct, get the CLI UX for free."),
    ("lib-click-python", "Click", "CLI и терминал", "https://click.palletsprojects.com/", "openSource", "python,cli,decorators,composable", "pip install click",
     "Composable command-line interfaces for Python via simple decorators.",
     "Композируемые интерфейсы командной строки для Python через простые декораторы.",
     "Nested command groups let a CLI grow subcommands (git-style) without restructuring existing code."),
    # ---------- Тестирование и качество (deepen) ----------
    ("lib-vitest-2", "Vitest UI", "Тестирование и качество", "https://vitest.dev/guide/ui.html", "openSource", "testing,vitest,ui,browser", "npm i -D @vitest/ui",
     "Browser-based test result UI for Vitest, with live re-runs and coverage view.",
     "Браузерный интерфейс результатов тестов для Vitest с живым перезапуском и просмотром покрытия.",
     "Leave it running in a second monitor during TDD — failures highlight instantly without switching windows."),
    ("lib-nock", "nock", "Тестирование и качество", "https://github.com/nock/nock", "openSource", "mocking,http,node,testing", "npm i -D nock",
     "HTTP mocking for Node.js tests, intercepting outgoing requests at the network layer.",
     "Мокинг HTTP для тестов Node.js, перехватывает исходящие запросы на сетевом уровне.",
     "Assert nock's interceptors were actually called — an unused mock silently means your code took a different path."),
    ("lib-faker-python", "Faker (Python)", "Тестирование и качество", "https://faker.readthedocs.io/", "openSource", "fake-data,testing,python,seed", "pip install Faker",
     "Generates realistic fake data for tests and seed scripts: names, addresses, text.",
     "Генерирует реалистичные фейковые данные для тестов и seed-скриптов: имена, адреса, текст.",
     "Seed the random generator for reproducible test data — unseeded runs make flaky failures hard to reproduce."),
]
