# -*- coding: utf-8 -*-
"""Stage 5 library pack Q: frontend meta-frameworks, CSS tooling, animation, a11y depth."""

LIBS_5Q = [
    # ---------- UI и frontend: meta-frameworks ----------
    ("lib-analog-js", "Analog", "UI и frontend", "https://analogjs.org/docs", "openSource", "angular,meta-framework,vite,ssr", "npm create analog@latest",
     "Full-stack meta-framework for Angular built on Vite.",
     "Full-stack мета-фреймворк для Angular на базе Vite.",
     "Brings file-based routing and SSR to Angular, which Angular core historically left to you."),
    ("lib-enhance-dev", "Enhance", "UI и frontend", "https://enhance.dev/docs", "openSource", "web-components,html-first,ssr,progressive", "",
     "HTML-first framework using web components with server-side rendering.",
     "HTML-first фреймворк на web components с серверным рендерингом.",
     "It leans on platform standards rather than a framework runtime, which ages better over time."),
    ("lib-eleventy-2", "Eleventy (11ty)", "UI и frontend", "https://www.11ty.dev/docs/", "openSource", "static-site,templating,zero-config,flexible", "npm i -D @11ty/eleventy",
     "Flexible static site generator supporting many templating languages, zero client JS by default.",
     "Гибкий генератор статических сайтов с поддержкой многих шаблонизаторов, без клиентского JS по умолчанию.",
     "It ships no JavaScript unless you add it, which is why 11ty sites score so well on performance metrics."),

    # ---------- Изображения и дизайн: CSS tooling ----------
    ("lib-postcss", "PostCSS", "UI и frontend", "https://postcss.org/", "openSource", "css,transform,plugins,build", "npm i -D postcss",
     "CSS transformation toolchain, the plugin platform Tailwind and Autoprefixer run on.",
     "Тулчейн трансформации CSS, платформа плагинов, на которой работают Tailwind и Autoprefixer.",
     "Most projects use it indirectly through a framework — you rarely configure it by hand any more."),
    ("lib-autoprefixer", "Autoprefixer", "UI и frontend", "https://github.com/postcss/autoprefixer", "openSource", "css,prefixes,compatibility,postcss", "npm i -D autoprefixer",
     "Adds vendor prefixes to CSS automatically based on your browserslist targets.",
     "Автоматически добавляет вендорные префиксы в CSS по вашим browserslist-таргетам.",
     "Keep browserslist honest — targeting ancient browsers silently bloats every stylesheet."),
    ("lib-lightningcss", "Lightning CSS", "UI и frontend", "https://lightningcss.dev/", "openSource", "css,rust,fast,minification", "npm i lightningcss",
     "Rust-based CSS parser, transformer and minifier, dramatically faster than PostCSS.",
     "Парсер, трансформер и минификатор CSS на Rust, значительно быстрее PostCSS.",
     "It handles prefixing and minification in one pass, replacing several PostCSS plugins at once."),
    ("lib-stylelint", "Stylelint", "Тестирование и качество", "https://stylelint.io/", "openSource", "css,linting,conventions,quality", "npm i -D stylelint",
     "Linter for CSS and CSS-like syntaxes, enforcing conventions and catching errors.",
     "Линтер CSS и CSS-подобных синтаксисов, обеспечивает соблюдение конвенций и ловит ошибки.",
     "The standard config catches genuine mistakes; add ordering rules only if your team actually wants them."),

    # ---------- Анимация и 3D (deepen further) ----------
    ("lib-auto-animate", "AutoAnimate", "Анимация и 3D", "https://auto-animate.formkit.com/", "openSource", "animation,zero-config,transitions,layout", "npm i @formkit/auto-animate",
     "One-line layout transitions for lists and elements, no keyframes needed.",
     "Анимация перестроений списков и элементов в одну строку, без keyframes.",
     "Adding it to a list gives smooth add/remove/reorder transitions with essentially zero configuration."),
    ("lib-react-spring", "React Spring", "Анимация и 3D", "https://www.react-spring.dev/docs", "openSource", "animation,physics,react,springs", "npm i @react-spring/web",
     "Spring-physics animation library for React, animating outside the React render cycle.",
     "Библиотека анимации на пружинной физике для React, анимирует вне цикла рендера React.",
     "Physics-based springs feel more natural than duration-based easing for interactive gestures."),
    ("lib-popmotion", "Motion One", "Анимация и 3D", "https://motion.dev/docs/quick-start", "openSource", "animation,web-animations-api,tiny,performance", "npm i motion",
     "Tiny animation library built on the native Web Animations API.",
     "Крошечная библиотека анимации на нативном Web Animations API.",
     "Using the browser's own animation engine means animations run off the main thread where possible."),
    ("lib-three-drei-2", "Threlte", "Анимация и 3D", "https://threlte.xyz/docs/learn/getting-started/introduction", "openSource", "svelte,three,3d,declarative", "npm i @threlte/core",
     "Declarative Three.js components for Svelte, the Svelte counterpart to React Three Fiber.",
     "Декларативные Three.js-компоненты для Svelte, аналог React Three Fiber в мире Svelte.",
     "Svelte's fine-grained reactivity fits 3D scene updates well, avoiding unnecessary re-render work."),

    # ---------- Доступность (deepen further) ----------
    ("lib-reakit", "Ariakit", "Доступность (a11y)", "https://ariakit.org/", "openSource", "react,accessible,components,unstyled", "npm i @ariakit/react",
     "Unstyled accessible React components following WAI-ARIA authoring practices closely.",
     "Неоформленные доступные React-компоненты, строго следующие практикам WAI-ARIA.",
     "Its ARIA implementation is unusually faithful to spec, which matters for compliance-driven projects."),
    ("lib-focus-trap", "focus-trap", "Доступность (a11y)", "https://github.com/focus-trap/focus-trap", "openSource", "focus,modals,keyboard,accessibility", "npm i focus-trap",
     "Traps keyboard focus inside a modal or dialog, a core accessibility requirement.",
     "Удерживает фокус клавиатуры внутри модального окна — базовое требование доступности.",
     "Every custom modal needs this — without it, keyboard users tab straight out into the page behind."),
    ("lib-accessible-astro", "Accessible Astro Components", "Доступность (a11y)", "https://accessible-astro.dev/", "openSource", "astro,accessible,components,starter", "",
     "Accessible component set and starter templates for Astro projects.",
     "Набор доступных компонентов и стартовые шаблоны для проектов Astro.",
     "Useful as a reference implementation even outside Astro — the ARIA patterns transfer."),

    # ---------- Тестирование (deepen) ----------
    ("lib-storybook-test", "Storybook Test", "Тестирование и качество", "https://storybook.js.org/docs/writing-tests", "openSource", "storybook,testing,interactions,components", "",
     "Runs component interaction tests directly against Storybook stories.",
     "Запускает тесты взаимодействия компонентов прямо на Storybook-историях.",
     "Stories double as test fixtures, so you maintain one set of component states rather than two."),
    ("lib-happy-dom", "happy-dom", "Тестирование и качество", "https://github.com/capricorn86/happy-dom", "openSource", "dom,testing,jsdom-alternative,fast", "npm i -D happy-dom",
     "Faster DOM implementation for Node tests, an alternative to jsdom.",
     "Более быстрая реализация DOM для тестов в Node, альтернатива jsdom.",
     "Vitest defaults to it for a reason — test suites run measurably faster than with jsdom."),
    ("lib-checkly-cli", "Playwright Test Fixtures", "Тестирование и качество", "https://playwright.dev/docs/test-fixtures", "openSource", "playwright,fixtures,setup,testing", "",
     "Playwright's fixture system for sharing setup and teardown across tests.",
     "Система фикстур Playwright для общей подготовки и очистки между тестами.",
     "Worker-scoped fixtures let expensive setup (like login) run once per worker rather than per test."),
]
