# -*- coding: utf-8 -*-
"""Stage 5 library pack AZ: vision models, face and pose, OCR engines, PDF and table extraction."""

LIBS_5AZ = [
    # ---------- Модели компьютерного зрения ----------
    ("lib-mmdetection", "MMDetection", "Компьютерное зрение", "https://mmdetection.readthedocs.io/", "openSource", "detection,openmmlab,pytorch,benchmarks", "pip install mmdet",
     "Object detection toolbox with a very large collection of implemented models.",
     "Набор инструментов детекции объектов с очень большой коллекцией реализованных моделей.",
     "Its config system makes swapping backbones and heads a configuration change, not a rewrite."),
    ("lib-openmmlab", "OpenMMLab", "Компьютерное зрение", "https://openmmlab.com/", "openSource", "toolkits,research,pytorch,ecosystem", "",
     "Family of computer vision toolboxes spanning detection, segmentation and more.",
     "Семейство наборов инструментов компьютерного зрения: детекция, сегментация и другое.",
     "Its shared configuration conventions mean learning one toolbox transfers to the rest."),
    ("lib-segment-anything", "Segment Anything", "Компьютерное зрение", "https://github.com/facebookresearch/segment-anything", "openSource", "segmentation,meta,zero-shot,promptable", "pip install segment-anything",
     "Promptable segmentation model that works without task-specific training.",
     "Промптируемая модель сегментации, работающая без обучения под конкретную задачу.",
     "Zero-shot segmentation removes the mask annotation step that segmentation projects usually start with."),
    ("lib-grounding-dino", "Grounding DINO", "Компьютерное зрение", "https://github.com/IDEA-Research/GroundingDINO", "openSource", "detection,open-vocabulary,text-prompt,zero-shot", "",
     "Detects objects described in free text, without a fixed class list.",
     "Обнаруживает объекты, описанные свободным текстом, без фиксированного списка классов.",
     "Pairing it with Segment Anything gives text-prompted segmentation with no training at all."),
    ("lib-clip", "CLIP", "Компьютерное зрение", "https://github.com/openai/CLIP", "openSource", "embeddings,multimodal,zero-shot,openai", "pip install clip",
     "Joint image and text embedding model enabling zero-shot classification.",
     "Модель совместных эмбеддингов изображений и текста для zero-shot классификации.",
     "Its shared embedding space is what makes text-based image search work without labels."),
    ("lib-openclip", "OpenCLIP", "Компьютерное зрение", "https://github.com/mlfoundations/open_clip", "openSource", "clip,reproduction,checkpoints,training", "pip install open_clip_torch",
     "Open reproduction of CLIP with many trained checkpoints.",
     "Открытое воспроизведение CLIP со множеством обученных чекпоинтов.",
     "Its checkpoint variety lets you trade model size against accuracy for your own constraints."),
    ("lib-siglip", "SigLIP", "Компьютерное зрение", "https://huggingface.co/docs/transformers/model_doc/siglip", "openSource", "google,embeddings,sigmoid-loss,efficient", "",
     "Image-text model using a sigmoid loss, improving on CLIP's efficiency.",
     "Модель изображение-текст с сигмоидной функцией потерь, эффективнее CLIP.",
     "It trains well at smaller batch sizes, which CLIP's contrastive loss does not."),
    ("lib-dinov2", "DINOv2", "Компьютерное зрение", "https://github.com/facebookresearch/dinov2", "openSource", "self-supervised,features,meta,backbone", "",
     "Self-supervised vision features that transfer well without fine-tuning.",
     "Самообучаемые визуальные признаки, хорошо переносящиеся без дообучения.",
     "Its frozen features often beat a fine-tuned supervised model on small datasets."),
    ("lib-depth-anything", "Depth Anything", "Компьютерное зрение", "https://github.com/DepthAnything/Depth-Anything-V2", "openSource", "depth-estimation,monocular,zero-shot,robust", "",
     "Monocular depth estimation that generalizes across scene types.",
     "Оценка глубины по одному изображению, обобщающаяся на разные типы сцен.",
     "Depth from a single ordinary photo enables effects that previously required a depth sensor."),
    ("lib-controlnet", "ControlNet", "Изображения и дизайн", "https://github.com/lllyasviel/ControlNet", "openSource", "diffusion,conditioning,structure,poses", "",
     "Conditions image generation on structure such as edges, depth or pose.",
     "Обусловливает генерацию изображений структурой: контурами, глубиной или позой.",
     "It is what turns prompting from a lottery into controllable composition."),
    ("lib-ip-adapter", "IP-Adapter", "Изображения и дизайн", "https://github.com/tencent-ailab/IP-Adapter", "openSource", "diffusion,image-prompt,style,subject", "",
     "Conditions diffusion models on a reference image rather than only text.",
     "Обусловливает диффузионные модели референсным изображением, а не только текстом.",
     "Style transfer from a reference image needs no fine-tuning with it, unlike a LoRA."),
    ("lib-lora", "LoRA", "Данные и ML", "https://huggingface.co/docs/peft/conceptual_guides/lora", "openSource", "fine-tuning,efficient,adapters,low-rank", "",
     "Low-rank adaptation for fine-tuning large models cheaply.",
     "Низкоранговая адаптация для дешёвого дообучения больших моделей.",
     "It trains a fraction of the parameters, so fine-tuning fits on a single consumer graphics card."),

    # ---------- Лица и позы ----------
    ("lib-insightface", "InsightFace", "Компьютерное зрение", "https://github.com/deepinsight/insightface", "openSource", "face-recognition,detection,embeddings,research", "pip install insightface",
     "Face analysis toolkit covering detection, recognition and alignment.",
     "Набор инструментов анализа лиц: детекция, распознавание и выравнивание.",
     "Face recognition is regulated in many jurisdictions — check the law before deploying it."),
    ("lib-deepface", "DeepFace", "Компьютерное зрение", "https://github.com/serengil/deepface", "openSource", "face-recognition,python,attributes,wrapper", "pip install deepface",
     "Lightweight Python wrapper over several face recognition models.",
     "Лёгкая Python-обёртка над несколькими моделями распознавания лиц.",
     "One line to compare two faces, which makes it a good way to evaluate the underlying models."),
    ("lib-face-api-js", "face-api.js", "Компьютерное зрение", "https://github.com/justadudewhohacks/face-api.js", "openSource", "browser,tensorflow-js,detection,landmarks", "npm i face-api.js",
     "Face detection and recognition running in the browser.",
     "Детекция и распознавание лиц прямо в браузере.",
     "Running client-side means face images never leave the user's device, which matters legally."),
    ("lib-mediapipe-tasks", "MediaPipe Tasks", "Компьютерное зрение", "https://ai.google.dev/edge/mediapipe/solutions/guide", "openSource", "google,on-device,vision,cross-platform", "",
     "Google's ready-made on-device vision, audio and text solutions.",
     "Готовые решения Google для зрения, аудио и текста на устройстве.",
     "Its pose and hand tracking run in real time on a phone, which most models cannot."),
    ("lib-movenet", "MoveNet", "Компьютерное зрение", "https://www.kaggle.com/models/google/movenet", "openSource", "pose,fast,tensorflow,real-time", "",
     "Fast single-person pose detection model.",
     "Быстрая модель определения позы одного человека.",
     "Fast enough for real-time feedback in fitness applications on modest hardware."),
    ("lib-posenet", "PoseNet", "Компьютерное зрение", "https://github.com/tensorflow/tfjs-models/tree/master/posenet", "openSource", "pose,browser,tensorflow-js,legacy", "",
     "Browser-based pose estimation model from TensorFlow.js.",
     "Модель оценки позы в браузере из TensorFlow.js.",
     "Superseded by MoveNet, which is both faster and more accurate."),
    ("lib-openpose", "OpenPose", "Компьютерное зрение", "https://github.com/CMU-Perceptual-Computing-Lab/openpose", "mixed", "pose,multi-person,research,cmu", "",
     "Multi-person pose estimation covering body, hands and face.",
     "Оценка позы нескольких людей: тело, руки и лицо.",
     "Free for academic use only — commercial deployment requires a licence from CMU."),

    # ---------- OCR ----------
    ("lib-surya-ocr", "Surya", "OCR и распознавание документов", "https://github.com/datalab-to/surya", "openSource", "ocr,layout,multilingual,accurate", "pip install surya-ocr",
     "Modern OCR with layout analysis and reading order detection.",
     "Современный OCR с анализом раскладки и определением порядка чтения.",
     "Reading order matters for multi-column documents, which plain OCR jumbles."),
    ("lib-doctr", "docTR", "OCR и распознавание документов", "https://mindee.github.io/doctr/", "openSource", "ocr,pytorch,tensorflow,end-to-end", "pip install python-doctr",
     "End-to-end document text recognition in PyTorch and TensorFlow.",
     "Сквозное распознавание текста документов на PyTorch и TensorFlow.",
     "Its two-stage detection and recognition design makes each stage independently replaceable."),
    ("lib-kraken-ocr", "Kraken", "OCR и распознавание документов", "https://kraken.re/", "openSource", "ocr,historical,manuscripts,training", "pip install kraken",
     "OCR system built for historical documents and manuscripts.",
     "Система OCR для исторических документов и рукописей.",
     "Trainable on a specific scribe's hand, which general OCR models never handle."),
    ("lib-calamari-ocr", "Calamari", "OCR и распознавание документов", "https://github.com/Calamari-OCR/calamari", "openSource", "ocr,ensembles,historical,tensorflow", "pip install calamari-ocr",
     "OCR engine using model ensembles for higher accuracy.",
     "Движок OCR, использующий ансамбли моделей для повышения точности.",
     "Voting across models measurably reduces errors on degraded historical scans."),
    ("lib-tesseract-js", "Tesseract.js", "OCR и распознавание документов", "https://github.com/naptha/tesseract.js", "openSource", "ocr,browser,wasm,javascript", "npm i tesseract.js",
     "Tesseract OCR compiled to WebAssembly for the browser.",
     "Tesseract OCR, скомпилированный в WebAssembly для браузера.",
     "Client-side OCR keeps scanned documents off your servers entirely."),

    # ---------- PDF и таблицы ----------
    ("lib-pdfplumber", "pdfplumber", "Документы и PDF", "https://github.com/jsvine/pdfplumber", "openSource", "pdf,extraction,tables,python", "pip install pdfplumber",
     "Extracts text, tables and layout details from PDFs.",
     "Извлекает текст, таблицы и детали раскладки из PDF.",
     "Its character-level positions let you reconstruct structure that plain text extraction loses."),
    ("lib-pdfjs", "PDF.js", "Документы и PDF", "https://mozilla.github.io/pdf.js/", "openSource", "pdf,browser,rendering,mozilla", "npm i pdfjs-dist",
     "Mozilla's PDF renderer, built into Firefox.",
     "Рендерер PDF от Mozilla, встроенный в Firefox.",
     "It renders PDFs without a plugin, which is why it became the browser standard."),
    ("lib-pdfbox", "Apache PDFBox", "Документы и PDF", "https://pdfbox.apache.org/", "openSource", "java,pdf,manipulation,extraction", "",
     "Java library for creating and manipulating PDF documents.",
     "Java-библиотека для создания и изменения PDF-документов.",
     "Its form-filling support handles the AcroForm documents that many enterprises still use."),
    ("lib-camelot", "Camelot", "Документы и PDF", "https://camelot-py.readthedocs.io/", "openSource", "tables,pdf,extraction,python", "pip install camelot-py",
     "Extracts tables from text-based PDFs.",
     "Извлекает таблицы из текстовых PDF.",
     "Its lattice mode needs ruled lines; stream mode handles tables without them, less reliably."),
    ("lib-tabula", "Tabula", "Документы и PDF", "https://tabula.technology/", "openSource", "tables,pdf,java,gui", "",
     "Table extraction from PDFs, with both a GUI and libraries.",
     "Извлечение таблиц из PDF с графическим интерфейсом и библиотеками.",
     "Its interface lets a non-programmer pull tables out of a report in minutes."),
    ("lib-img2table", "img2table", "OCR и распознавание документов", "https://github.com/xavctn/img2table", "openSource", "tables,images,ocr,detection", "pip install img2table",
     "Detects and extracts tables from images and scanned PDFs.",
     "Обнаруживает и извлекает таблицы из изображений и сканированных PDF.",
     "It handles the scanned tables that text-based extractors cannot read at all."),
    ("lib-layoutlm", "LayoutLM", "OCR и распознавание документов", "https://huggingface.co/docs/transformers/model_doc/layoutlmv3", "openSource", "document-ai,microsoft,multimodal,forms", "",
     "Document understanding model combining text, layout and image signals.",
     "Модель понимания документов, объединяющая текст, раскладку и изображение.",
     "Position matters in forms and invoices, which is exactly what pure text models discard."),
    ("lib-donut", "Donut", "OCR и распознавание документов", "https://github.com/clovaai/donut", "openSource", "ocr-free,document-understanding,end-to-end,transformer", "",
     "OCR-free document understanding that reads images directly.",
     "Понимание документов без OCR: модель читает изображения напрямую.",
     "Skipping OCR removes its errors from the pipeline, at the cost of needing task-specific training."),
    ("lib-nougat", "Nougat", "OCR и распознавание документов", "https://github.com/facebookresearch/nougat", "openSource", "academic,pdf,markdown,formulas", "pip install nougat-ocr",
     "Converts academic PDFs to markup, including mathematical formulas.",
     "Преобразует академические PDF в разметку, включая математические формулы.",
     "Formula recognition is where it beats general OCR, which turns equations into noise."),
]
