# -*- coding: utf-8 -*-
"""Stage 5 API pack Y: geocoding, IP intelligence, currency, scraping infrastructure, SEO and recon."""

APIS_5Y = [
    # ---------- Геокодирование и места ----------
    ("api-locationiq", "LocationIQ", "Карты и навигация", "https://docs.locationiq.com/", "freeTier", "geocoding,osm,reverse,affordable", "",
     "Geocoding and reverse geocoding on OpenStreetMap data with a generous free tier.",
     "Прямое и обратное геокодирование на данных OpenStreetMap с щедрым бесплатным тарифом.",
     "Its free tier allows commercial use, which most geocoding free tiers explicitly forbid."),
    ("api-radar-io", "Radar", "Карты и навигация", "https://radar.com/documentation", "freeTier", "geofencing,sdk,location,tracking", "",
     "Location platform with geofencing, trip tracking and place detection SDKs.",
     "Платформа геолокации с геозонами, отслеживанием поездок и SDK определения мест.",
     "Its on-device geofencing avoids the constant location polling that drains mobile batteries."),
    ("api-what3words", "what3words", "Карты и навигация", "https://developer.what3words.com/public-api", "freeTier", "addressing,three-words,precise,global", "",
     "Addresses every three-metre square on earth with a unique three-word phrase.",
     "Адресует каждый трёхметровый квадрат на Земле уникальной фразой из трёх слов.",
     "Useful for delivery in places with no street addresses, though it is a proprietary scheme."),

    # ---------- IP и телеком-данные ----------
    ("api-ipapi", "ipapi", "Открытые данные", "https://ipapi.com/documentation", "freeTier", "geolocation,ip,json,simple", "",
     "IP geolocation returning country, region, city and network details.",
     "IP-геолокация, возвращающая страну, регион, город и сведения о сети.",
     "City-level accuracy is unreliable on mobile networks — treat country as the only firm signal."),
    ("api-maxmind-geoip2", "MaxMind GeoIP2", "Открытые данные", "https://dev.maxmind.com/geoip", "mixed", "geolocation,ip,offline-database,accuracy", "",
     "IP intelligence available both as an API and as a downloadable local database.",
     "IP-аналитика, доступная и как API, и как загружаемая локальная база данных.",
     "The local database means lookups add no network latency, which suits per-request use."),
    ("api-abstractapi", "AbstractAPI", "Утилиты", "https://docs.abstractapi.com/", "freeTier", "validation,utilities,multi-api,suite", "",
     "Suite of small utility APIs for email, phone, IP and address validation.",
     "Набор небольших утилитарных API для проверки email, телефонов, IP и адресов.",
     "Each API has its own quota, so a free plan covers several different validations at once."),
    ("api-neutrino", "Neutrino API", "Утилиты", "https://www.neutrinoapi.com/api/api-basics/", "freeTier", "utilities,validation,security,multi-purpose", "",
     "General-purpose API collection covering validation, security and data tools.",
     "Универсальная коллекция API для валидации, безопасности и работы с данными.",
     "Self-hostable as a container, which is unusual for a utility API service."),
    ("api-apilayer", "APILayer", "Утилиты", "https://apilayer.com/", "freeTier", "marketplace,utilities,currency,validation", "",
     "Marketplace of small production APIs under a single account and key.",
     "Маркетплейс небольших продакшн-API под одним аккаунтом и ключом.",
     "One key across many APIs simplifies credential handling for a project using several of them."),

    # ---------- Валюты и финансовые данные ----------
    ("api-fixer-io", "Fixer.io", "Финансы", "https://fixer.io/documentation", "freeTier", "exchange-rates,currency,historical,simple", "",
     "Foreign exchange rates with historical data and conversion endpoints.",
     "Курсы валют с историческими данными и эндпоинтами конвертации.",
     "Its free tier is HTTP-only and euro-based, which rules it out for most production use."),
    ("api-open-exchange-rates", "Open Exchange Rates", "Финансы", "https://docs.openexchangerates.org/", "freeTier", "exchange-rates,currency,reliable,historical", "",
     "Reliable exchange rate data with a long historical archive.",
     "Надёжные данные о курсах валют с обширным историческим архивом.",
     "Rates update hourly on lower tiers — not suitable for anything trading-sensitive."),
    ("api-currencylayer", "Currencylayer", "Финансы", "https://currencylayer.com/documentation", "freeTier", "exchange-rates,currency,real-time,conversion", "",
     "Real-time and historical exchange rates for many world currencies.",
     "Курсы валют в реальном времени и исторические данные по многим мировым валютам.",
     "Always compare against the free Frankfurter API before paying — it covers many of the same pairs."),
    ("api-vatlayer", "Vatlayer", "Юридические и налоговые API", "https://vatlayer.com/documentation", "freeTier", "vat,validation,eu,tax-rates", "",
     "EU VAT number validation and VAT rate lookup.",
     "Проверка номеров НДС ЕС и получение ставок НДС.",
     "Validating a customer's VAT number is what allows the reverse-charge exemption on B2B invoices."),

    # ---------- Скрейпинг и прокси-инфраструктура ----------
    ("api-scraperapi", "ScraperAPI", "Браузер и автоматизация", "https://docs.scraperapi.com/", "freeTier", "scraping,proxies,rendering,rotation", "",
     "Handles proxy rotation, CAPTCHAs and browser rendering behind one request.",
     "Берёт на себя ротацию прокси, CAPTCHA и рендеринг браузера за один запрос.",
     "Enable JavaScript rendering only where needed — it costs several times a plain request."),
    ("api-zyte", "Zyte", "Браузер и автоматизация", "https://docs.zyte.com/", "paid", "scraping,scrapy,extraction,ai", "",
     "Web scraping platform from the Scrapy team, with automatic extraction.",
     "Платформа веб-скрейпинга от команды Scrapy с автоматическим извлечением данных.",
     "Its automatic extraction infers product and article fields without site-specific selectors."),
    ("api-oxylabs", "Oxylabs", "Браузер и автоматизация", "https://developers.oxylabs.io/", "paid", "proxies,scraping,residential,enterprise", "",
     "Large proxy network and scraping APIs aimed at enterprise data collection.",
     "Крупная прокси-сеть и API скрейпинга для корпоративного сбора данных.",
     "Residential proxies raise real legal and ethical questions — confirm your use case is permitted."),
    ("api-smartproxy", "Decodo (Smartproxy)", "Браузер и автоматизация", "https://help.decodo.com/docs", "paid", "proxies,residential,scraping,rotation", "",
     "Proxy network with residential and datacenter pools for data collection.",
     "Прокси-сеть с резидентными и датацентровыми пулами для сбора данных.",
     "Cheaper than the enterprise providers, with correspondingly smaller pools and less support."),
    ("api-crawlbase", "Crawlbase", "Браузер и автоматизация", "https://crawlbase.com/docs/crawling-api/", "freeTier", "scraping,crawling,proxies,storage", "",
     "Crawling and scraping API with built-in proxy handling and storage.",
     "API краулинга и скрейпинга со встроенной работой с прокси и хранилищем.",
     "Its free tier of a thousand requests is enough to validate a scraper before committing."),

    # ---------- Поисковая выдача и SEO ----------
    ("api-searchapi", "SearchApi", "Поиск и retrieval", "https://www.searchapi.io/docs/google", "freeTier", "serp,google,structured,real-time", "",
     "Structured search engine results from Google, Bing and others.",
     "Структурированные результаты поисковой выдачи Google, Bing и других систем.",
     "Structured JSON avoids parsing search HTML, which changes without warning."),
    ("api-zenserp", "Zenserp", "Поиск и retrieval", "https://app.zenserp.com/documentation", "freeTier", "serp,scraping,google,rankings", "",
     "Search engine results API for rank tracking and SERP analysis.",
     "API результатов поисковой выдачи для отслеживания позиций и анализа SERP.",
     "Results vary by location parameter, so always pin the locale when tracking rankings over time."),
    ("api-dataforseo", "DataForSEO", "Поиск и retrieval", "https://docs.dataforseo.com/v3/", "paid", "seo,serp,keywords,backlinks", "",
     "Comprehensive SEO data APIs covering SERPs, keywords and backlinks.",
     "Полные SEO-API с данными по выдаче, ключевым словам и обратным ссылкам.",
     "Priced per request rather than per seat, which suits building your own SEO tooling."),
    ("api-ahrefs", "Ahrefs API", "Поиск и retrieval", "https://docs.ahrefs.com/docs/api/reference/introduction", "paid", "seo,backlinks,keywords,authority", "",
     "Backlink and keyword data from one of the largest web crawl indexes.",
     "Данные об обратных ссылках и ключевых словах из одного из крупнейших индексов веб-краулинга.",
     "Its backlink index is the main draw — few competitors crawl at comparable depth."),
    ("api-semrush", "Semrush API", "Поиск и retrieval", "https://developer.semrush.com/api/", "paid", "seo,competitive,keywords,traffic", "",
     "Competitive research data on keywords, traffic and advertising.",
     "Данные конкурентного анализа по ключевым словам, трафику и рекламе.",
     "Its paid-advertising data is the differentiator over backlink-focused competitors."),
    ("api-moz", "Moz API", "Поиск и retrieval", "https://moz.com/products/api", "paid", "seo,domain-authority,links,metrics", "",
     "Link metrics including the widely cited Domain Authority score.",
     "Метрики ссылок, включая широко цитируемый показатель Domain Authority.",
     "Domain Authority is Moz's own model, not a Google signal — useful comparatively, not absolutely."),

    # ---------- Производительность и технологический профиль ----------
    ("api-pagespeed-insights", "PageSpeed Insights API", "Мониторинг и аналитика", "https://developers.google.com/speed/docs/insights/v5/get-started", "free", "performance,lighthouse,core-web-vitals,google", "",
     "Runs Lighthouse audits and returns real-world Core Web Vitals data.",
     "Запускает аудиты Lighthouse и возвращает реальные данные Core Web Vitals.",
     "Its field data comes from real Chrome users, which lab scores alone never reflect."),
    ("api-webpagetest", "WebPageTest API", "Мониторинг и аналитика", "https://docs.webpagetest.org/api/", "freeTier", "performance,waterfall,locations,filmstrip", "",
     "Detailed performance testing from many real locations and devices.",
     "Детальное тестирование производительности из множества реальных локаций и на разных устройствах.",
     "Its waterfall and filmstrip views diagnose why a page is slow, where a score only says that it is."),
    ("api-cloudflare-radar", "Cloudflare Radar", "Открытые данные", "https://developers.cloudflare.com/radar/", "free", "internet-trends,traffic,security,free", "",
     "Free internet traffic, security and adoption trend data from Cloudflare's network.",
     "Бесплатные данные о трафике, безопасности и трендах интернета из сети Cloudflare.",
     "A rare free window into internet-scale traffic patterns, including outages by country."),
    ("api-builtwith", "BuiltWith", "Открытые данные", "https://api.builtwith.com/", "paid", "technology-profiling,lead-generation,stacks,detection", "",
     "Detects which technologies a website is built with.",
     "Определяет, на каких технологиях построен веб-сайт.",
     "Widely used for lead generation — finding every site running a competitor's product."),
    ("api-wappalyzer", "Wappalyzer", "Открытые данные", "https://www.wappalyzer.com/docs/api/v2/", "paid", "technology-detection,stacks,lookup,enrichment", "",
     "Technology stack detection with company enrichment data.",
     "Определение технологического стека с обогащением данными о компаниях.",
     "Its open-source detection rules are public, so you can self-host the detection logic."),
    ("api-censys", "Censys", "Безопасность и секреты", "https://docs.censys.com/", "freeTier", "internet-scanning,hosts,certificates,recon", "",
     "Internet-wide scan data on hosts, services and certificates.",
     "Данные интернет-сканирования по хостам, сервисам и сертификатам.",
     "Useful for auditing your own external attack surface, not only for researching others."),
]
