# -*- coding: utf-8 -*-
# (id, name, category, url, access, tags, summary_en, summary_ru, tip_en,
#  model, from_price, free_quota, pricing_url)
# model: usage | subscription | hybrid | commission | credits
PAID = [
# ---------- LLM / AI ----------
("paid-openai","OpenAI Platform (paid tiers)","AI и агенты","https://platform.openai.com/docs/pricing","paid","llm,tokens,gpt,vision",
 "Token-priced access to GPT models, embeddings, images and audio.",
 "Потокенный доступ к моделям GPT, эмбеддингам, изображениям и аудио.",
 "Mini models are roughly an order of magnitude cheaper: benchmark them before paying for the flagship.",
 "usage","from ~$0.15 / 1M input tokens (mini class)","$5 trial credit for new orgs","https://openai.com/api/pricing/"),
("paid-anthropic","Anthropic Claude API","AI и агенты","https://docs.claude.com/en/docs/about-claude/pricing","paid","llm,claude,tokens,caching",
 "Claude models priced per million input and output tokens.",
 "Модели Claude с оплатой за миллион входных и выходных токенов.",
 "Prompt caching and batch mode cut real bills far more than switching model tiers.",
 "usage","Sonnet class ~$3 / 1M in, ~$15 / 1M out","Free tier in the Console for testing","https://www.anthropic.com/pricing"),
("paid-gemini","Google Gemini API (paid)","AI и агенты","https://ai.google.dev/pricing","paid","llm,google,tokens,multimodal",
 "Gemini models with a genuinely usable free tier and cheap Flash pricing.",
 "Модели Gemini с реально пригодным free tier и дешёвым тарифом Flash.",
 "The free tier has hard rate limits: paid keys mainly buy you throughput, not better models.",
 "usage","Flash class from ~$0.10 / 1M input tokens","Free tier with daily request limits","https://ai.google.dev/pricing"),
("paid-mistral","Mistral La Plateforme","AI и агенты","https://mistral.ai/pricing","paid","llm,europe,tokens,gdpr",
 "European LLM provider with EU data residency options.",
 "Европейский LLM-провайдер с опцией хранения данных в ЕС.",
 "Often the easiest vendor to justify in a German GDPR review.",
 "usage","Small models from ~$0.20 / 1M tokens","Limited free experimentation tier","https://mistral.ai/pricing"),
("paid-groq","GroqCloud","AI и агенты","https://groq.com/pricing","paid","llm,fast,inference,tokens",
 "Very low latency inference for open models on custom hardware.",
 "Инференс open-моделей с очень низкой задержкой на собственном железе.",
 "Pick it when time-to-first-token matters more than raw model quality.",
 "usage","from ~$0.05 / 1M tokens on small models","Free developer tier with rate limits","https://groq.com/pricing"),
("paid-openrouter","OpenRouter","AI и агенты","https://openrouter.ai/models","paid","router,llm,multi-provider,fallback",
 "One key and one API in front of hundreds of models from many vendors.",
 "Один ключ и один API перед сотнями моделей разных вендоров.",
 "Automatic fallback between providers is the feature worth the small routing fee.",
 "usage","Provider price plus a small routing fee","Several free-to-use community models","https://openrouter.ai/docs/faq"),
("paid-deepseek","DeepSeek Platform","AI и агенты","https://api-docs.deepseek.com/quick_start/pricing","paid","llm,cheap,reasoning,tokens",
 "Very cheap chat and reasoning models with off-peak discounts.",
 "Очень дешёвые чат- и reasoning-модели со скидками в непиковые часы.",
 "Cache hits are billed separately and much lower: structure prompts so prefixes repeat.",
 "usage","from well under $1 / 1M input tokens","No standing free tier","https://api-docs.deepseek.com/quick_start/pricing"),
("paid-xai","xAI API","AI и агенты","https://docs.x.ai/docs/models","paid","grok,llm,tokens,realtime",
 "Grok models with large context and live search integration.",
 "Модели Grok с большим контекстом и интеграцией живого поиска.",
 "Live search is billed on top of tokens: measure it separately in your cost dashboard.",
 "usage","Comparable to mid-tier frontier models","Promotional credits at times","https://x.ai/api"),
("paid-replicate","Replicate","Изображения и дизайн","https://replicate.com/docs","paid","models,gpu,images,video",
 "Run thousands of open models billed by the second of GPU time.",
 "Запуск тысяч open-моделей с оплатой по секундам GPU.",
 "Cold starts are billed too: keep a model warm if you call it constantly.",
 "usage","Per-second GPU billing, fractions of a cent","Small free allowance for testing","https://replicate.com/pricing"),
("paid-fal","fal.ai","Изображения и дизайн","https://fal.ai/models","paid","images,video,fast,inference",
 "Fast hosted inference for image and video generation models.",
 "Быстрый хостинг-инференс моделей генерации изображений и видео.",
 "Per-image pricing makes budgeting far easier than per-second GPU billing.",
 "usage","Per image or per second of output","Free credits on sign-up","https://fal.ai/pricing"),
("paid-stability","Stability AI Platform","Изображения и дизайн","https://platform.stability.ai/docs/api-reference","paid","images,diffusion,credits,generation",
 "Stable Diffusion family image generation billed in credits.",
 "Генерация изображений семейства Stable Diffusion с оплатой кредитами.",
 "Credits expire on some plans: buy in small batches until your volume is predictable.",
 "credits","Credit packs, a few cents per image","Free credits on registration","https://platform.stability.ai/pricing"),
("paid-elevenlabs","ElevenLabs","Аудио и голос","https://elevenlabs.io/docs","paid","tts,voice,cloning,audio",
 "High quality speech synthesis and voice cloning by character quota.",
 "Качественный синтез речи и клонирование голоса с квотой по символам.",
 "Character quotas, not minutes: long punctuation-heavy scripts cost more than they sound.",
 "subscription","from ~$5 / month (Starter)","10k characters per month free","https://elevenlabs.io/pricing"),
("paid-deepgram","Deepgram","Аудио и голос","https://developers.deepgram.com/docs","paid","stt,transcription,streaming,audio",
 "Speech to text billed per minute of audio processed.",
 "Speech-to-text с оплатой за минуту обработанного аудио.",
 "Pre-recorded transcription is much cheaper than streaming: batch whatever is not live.",
 "usage","from ~$0.004 / minute of audio","$200 free credit on sign-up","https://deepgram.com/pricing"),
("paid-assemblyai","AssemblyAI","Аудио и голос","https://www.assemblyai.com/docs","paid","stt,diarization,summary,audio",
 "Transcription plus speaker labels, chapters and summarisation.",
 "Транскрипция плюс метки спикеров, главы и суммаризация.",
 "Each extra model (summary, sentiment, entities) adds its own per-hour charge.",
 "usage","from ~$0.15 / hour of audio","Free tier with limited hours","https://www.assemblyai.com/pricing"),
# ---------- Search / scraping / data ----------
("paid-tavily","Tavily","Поиск и retrieval","https://docs.tavily.com/","paid","search,agents,credits,research",
 "Search API designed for agent pipelines, billed in credits.",
 "Поисковый API для агентных пайплайнов с оплатой кредитами.",
 "Advanced search depth costs several credits per call: use basic depth for simple lookups.",
 "credits","Paid plans from ~$30 / month","1000 free credits per month","https://www.tavily.com/#pricing"),
("paid-exa","Exa","Поиск и retrieval","https://docs.exa.ai/","paid","neural-search,contents,research,agents",
 "Neural web search with page contents, priced per search and per page.",
 "Нейропоиск по вебу с контентом страниц, оплата за поиск и страницу.",
 "Contents are billed on top of the search itself: request only the pages you will actually read.",
 "usage","from ~$5 / 1000 searches","$10 free credit to start","https://exa.ai/pricing"),
("paid-serpapi","SerpApi","Поиск и retrieval","https://serpapi.com/search-api","paid","serp,google,scraping,structured",
 "Structured Google and other search engine results without scraping yourself.",
 "Структурированная выдача Google и других поисковиков без своего скрапинга.",
 "Cheaper competitors exist, but this one is the most reliable on hard captcha-heavy pages.",
 "subscription","from ~$75 / month for 5000 searches","100 free searches per month","https://serpapi.com/pricing"),
("paid-serper","Serper","Поиск и retrieval","https://serper.dev/","paid","serp,google,fast,cheap",
 "Low cost Google search API popular in agent stacks.",
 "Дешёвый Google search API, популярный в агентных стеках.",
 "Prepaid credits never expire, which suits bursty side projects better than a subscription.",
 "credits","around $1 per 1000 queries","2500 free queries on sign-up","https://serper.dev/"),
("paid-firecrawl","Firecrawl","Браузер и автоматизация","https://docs.firecrawl.dev/","paid","scrape,crawl,markdown,llm",
 "Turns whole websites into clean markdown for LLM ingestion.",
 "Превращает целые сайты в чистый markdown для загрузки в LLM.",
 "Crawling a large docs site burns credits fast: cap depth and page count explicitly.",
 "subscription","from ~$16 / month","500 free credits","https://www.firecrawl.dev/pricing"),
("paid-scrapingbee","ScrapingBee","Браузер и автоматизация","https://www.scrapingbee.com/documentation/","paid","scraping,proxy,javascript,html",
 "Managed scraping with proxy rotation and JavaScript rendering.",
 "Управляемый скрапинг с ротацией прокси и рендерингом JavaScript.",
 "JavaScript rendering multiplies the credit cost: disable it for static pages.",
 "subscription","from ~$49 / month","1000 free API credits","https://www.scrapingbee.com/#pricing"),
("paid-apify","Apify","Браузер и автоматизация","https://docs.apify.com/","paid","actors,scraping,automation,platform",
 "Marketplace of ready scrapers running on a managed platform.",
 "Маркетплейс готовых скраперов на управляемой платформе.",
 "Community actors have their own rental price on top of platform compute units.",
 "hybrid","from ~$39 / month plus per-actor fees","$5 free platform credit monthly","https://apify.com/pricing"),
("paid-brightdata","Bright Data","Браузер и автоматизация","https://docs.brightdata.com/","paid","proxy,scraping,datasets,enterprise",
 "Enterprise proxy and web data platform with large datasets.",
 "Корпоративная платформа прокси и веб-данных с большими датасетами.",
 "Priced per gigabyte on most products: measure payload size before committing.",
 "usage","Pay-as-you-go per GB or per record","Free trial credits","https://brightdata.com/pricing"),
("paid-algolia","Algolia","Поиск и retrieval","https://www.algolia.com/doc/","paid","search,instant,saas,ranking",
 "Hosted instant search with ranking rules and analytics.",
 "Хостинговый мгновенный поиск с правилами ранжирования и аналитикой.",
 "Billing counts both records and searches: trim unused attributes from your index.",
 "hybrid","from ~$0.50 per 1000 searches","10k free searches per month","https://www.algolia.com/pricing"),
("paid-pinecone","Pinecone","Векторные базы","https://docs.pinecone.io/","paid","vector,rag,embeddings,serverless",
 "Managed vector database for retrieval augmented generation.",
 "Управляемая векторная база для retrieval augmented generation.",
 "Serverless billing is read and write heavy: batch upserts instead of writing per document.",
 "usage","Serverless from ~$0.33 per million reads","Free starter index","https://www.pinecone.io/pricing/"),
("paid-weaviate","Weaviate Cloud","Векторные базы","https://weaviate.io/developers/weaviate","paid","vector,hybrid-search,rag,cloud",
 "Vector database with hybrid keyword plus vector search.",
 "Векторная база с гибридным поиском: ключевые слова плюс векторы.",
 "Hybrid search usually beats pure vector search on product and code data.",
 "subscription","Serverless from ~$25 / month","14-day free sandbox","https://weaviate.io/pricing"),
("paid-qdrant-cloud","Qdrant Cloud","Векторные базы","https://qdrant.tech/documentation/","paid","vector,rust,filtering,cloud",
 "Managed hosting for the open source Qdrant vector engine.",
 "Управляемый хостинг открытого векторного движка Qdrant.",
 "You can always self-host the same engine later: no data format lock-in.",
 "hybrid","Paid clusters from ~$25 / month","1GB free cluster forever","https://qdrant.tech/pricing/"),
# ---------- Cloud / hosting / data ----------
("paid-vercel","Vercel Pro","Облако и деплой","https://vercel.com/docs","paid","hosting,nextjs,edge,ci",
 "Frontend hosting with previews, edge functions and analytics.",
 "Хостинг фронтенда с превью-деплоями, edge-функциями и аналитикой.",
 "Watch function invocation and bandwidth overage: those, not the seat, cause surprise bills.",
 "subscription","$20 / month per member","Hobby plan free for personal projects","https://vercel.com/pricing"),
("paid-netlify","Netlify Pro","Облако и деплой","https://docs.netlify.com/","paid","hosting,forms,functions,ci",
 "Static and function hosting with forms and split testing.",
 "Хостинг статики и функций с формами и сплит-тестами.",
 "Build minutes are the usual overage: cache dependencies to keep builds short.",
 "subscription","from ~$19 / month per member","Free tier with 100GB bandwidth","https://www.netlify.com/pricing/"),
("paid-render","Render","Облако и деплой","https://render.com/docs","paid","hosting,containers,postgres,cron",
 "Managed containers, databases and cron jobs with a simple pricing grid.",
 "Управляемые контейнеры, базы и cron-задачи с простой сеткой тарифов.",
 "Free web services sleep when idle: the first paid tier exists mainly to stop that.",
 "subscription","Instances from ~$7 / month","Free tier for static sites","https://render.com/pricing"),
("paid-railway","Railway","Облако и деплой","https://docs.railway.com/","paid","hosting,usage-based,databases,deploy",
 "Usage-based hosting for apps and databases with quick deploys.",
 "Хостинг приложений и баз с оплатой по потреблению и быстрым деплоем.",
 "Billing follows memory and CPU seconds: idle services still cost money if left running.",
 "usage","from ~$5 / month plus usage","Limited trial credit","https://railway.com/pricing"),
("paid-flyio","Fly.io","Облако и деплой","https://fly.io/docs/","paid","hosting,edge,machines,global",
 "Run containers close to users in many regions.",
 "Запуск контейнеров рядом с пользователями во многих регионах.",
 "Machines can auto-stop between requests, which makes small side projects genuinely cheap.",
 "usage","Pay per machine second and volume GB","Small free allowance","https://fly.io/docs/about/pricing/"),
("paid-cloudflare-workers","Cloudflare Workers Paid","Облако и деплой","https://developers.cloudflare.com/workers/","paid","edge,serverless,kv,r2",
 "Edge serverless platform with KV, D1, R2 and Durable Objects.",
 "Edge-serverless платформа с KV, D1, R2 и Durable Objects.",
 "R2 charges no egress fee, which is the main reason teams move media off S3.",
 "subscription","$5 / month including generous quotas","100k free requests per day","https://developers.cloudflare.com/workers/platform/pricing/"),
("paid-supabase","Supabase Pro","Базы данных и backend","https://supabase.com/docs","paid","postgres,auth,storage,realtime",
 "Hosted Postgres with auth, storage, realtime and edge functions.",
 "Хостинг Postgres с auth, storage, realtime и edge-функциями.",
 "Free projects pause after inactivity: Pro exists mainly to keep a demo permanently online.",
 "subscription","$25 / month per organisation","Free tier with two active projects","https://supabase.com/pricing"),
("paid-neon","Neon","Базы данных и backend","https://neon.com/docs","paid","postgres,serverless,branching,scale-to-zero",
 "Serverless Postgres with database branching per pull request.",
 "Serverless Postgres с ветвлением базы под каждый pull request.",
 "Branching a database per preview deploy is the feature that justifies the price.",
 "hybrid","Paid plans from ~$19 / month","Free tier with limited compute hours","https://neon.com/pricing"),
("paid-planetscale","PlanetScale","Базы данных и backend","https://planetscale.com/docs","paid","mysql,vitess,branching,scale",
 "MySQL platform built on Vitess with schema branching.",
 "Платформа MySQL на Vitess с ветвлением схемы.",
 "There is no free tier any more: budget from the first day of the project.",
 "subscription","from ~$39 / month","No permanent free tier","https://planetscale.com/pricing"),
("paid-mongodb-atlas","MongoDB Atlas","Базы данных и backend","https://www.mongodb.com/docs/atlas/","paid","mongodb,cloud,cluster,search",
 "Managed MongoDB clusters with full text and vector search.",
 "Управляемые кластеры MongoDB с полнотекстовым и векторным поиском.",
 "The free M0 cluster is enough for a portfolio project and never expires.",
 "hybrid","Dedicated clusters from ~$57 / month","Free shared M0 cluster","https://www.mongodb.com/pricing"),
("paid-upstash","Upstash","Базы данных и backend","https://upstash.com/docs","paid","redis,kafka,serverless,per-request",
 "Serverless Redis and queues billed per request.",
 "Serverless Redis и очереди с оплатой за запрос.",
 "Per-request billing suits spiky workloads far better than a rented instance.",
 "usage","from ~$0.20 per 100k commands","10k free commands per day","https://upstash.com/pricing"),
("paid-firebase","Firebase Blaze","Базы данных и backend","https://firebase.google.com/docs","paid","google,realtime,auth,functions",
 "Google app platform with realtime database, auth and functions.",
 "Платформа приложений Google с realtime-базой, auth и функциями.",
 "Blaze is pay-as-you-go with no hard cap: set budget alerts before launch day.",
 "usage","Pay-as-you-go after free quotas","Generous Spark free tier","https://firebase.google.com/pricing"),
("paid-cloudinary","Cloudinary","Изображения и дизайн","https://cloudinary.com/documentation","paid","images,video,cdn,transform",
 "Media CDN with on-the-fly transformation and optimisation.",
 "Медиа-CDN с трансформацией и оптимизацией на лету.",
 "Credits mix storage, bandwidth and transformations: one runaway loop can drain a month.",
 "subscription","Paid plans from ~$89 / month","Free tier with 25 monthly credits","https://cloudinary.com/pricing"),
("paid-mux","Mux","Видео и медиа","https://docs.mux.com/","paid","video,streaming,encoding,analytics",
 "Video encoding, streaming and player analytics as an API.",
 "Кодирование, стриминг и аналитика видео в виде API.",
 "Storage plus delivery are billed separately: short-lived content is much cheaper than an archive.",
 "usage","from ~$0.005 per minute delivered","Free trial credit","https://www.mux.com/pricing"),
# ---------- Communication / payments ----------
("paid-twilio","Twilio","Коммуникации","https://www.twilio.com/docs","paid","sms,voice,whatsapp,verify",
 "SMS, voice, WhatsApp and verification APIs worldwide.",
 "SMS, голос, WhatsApp и верификация по всему миру.",
 "Per-message price varies enormously by country: check German rates specifically.",
 "usage","Per message and per minute, country dependent","Trial balance on sign-up","https://www.twilio.com/en-us/pricing"),
("paid-sendgrid","SendGrid","Коммуникации","https://www.twilio.com/docs/sendgrid","paid","email,transactional,marketing,smtp",
 "Transactional and marketing email at scale.",
 "Транзакционная и маркетинговая почта в больших объёмах.",
 "Set up domain authentication before the first send or your mail lands in spam.",
 "subscription","from ~$20 / month","Limited free plan","https://sendgrid.com/en-us/pricing"),
("paid-resend","Resend","Коммуникации","https://resend.com/docs","paid","email,react,transactional,dx",
 "Developer-first transactional email with React email templates.",
 "Транзакционная почта для разработчиков с React-шаблонами писем.",
 "The free tier covers most side projects: 3000 emails a month goes further than it sounds.",
 "hybrid","from ~$20 / month","3000 emails per month free","https://resend.com/pricing"),
("paid-postmark","Postmark","Коммуникации","https://postmarkapp.com/developer","paid","email,deliverability,transactional",
 "Transactional email focused on deliverability and speed.",
 "Транзакционная почта с упором на доставляемость и скорость.",
 "It refuses bulk marketing mail on purpose, which is why inbox rates stay high.",
 "subscription","from ~$15 / month for 10k emails","100 test emails per month","https://postmarkapp.com/pricing"),
("paid-stripe-fees","Stripe (transaction fees)","Платежи и commerce","https://docs.stripe.com/payments","paid","payments,fees,subscriptions,checkout",
 "Card processing charged as a percentage plus a fixed fee per transaction.",
 "Приём карт с оплатой в виде процента плюс фиксированный сбор за транзакцию.",
 "European card rates are much lower than international ones: model both in your unit economics.",
 "commission","around 1.5% + €0.25 for EEA cards","No monthly fee","https://stripe.com/pricing"),
("paid-paddle","Paddle","Платежи и commerce","https://developer.paddle.com/","paid","merchant-of-record,tax,saas,subscriptions",
 "Merchant of record that handles VAT and sales tax for you.",
 "Merchant of record, который берёт на себя НДС и налоги с продаж.",
 "For a solo developer selling into the EU, outsourced VAT often beats a lower percentage.",
 "commission","around 5% + $0.50 per transaction","No monthly fee","https://www.paddle.com/pricing"),
("paid-lemonsqueezy","Lemon Squeezy","Платежи и commerce","https://docs.lemonsqueezy.com/","paid","merchant-of-record,digital-goods,saas",
 "Merchant of record for digital products and subscriptions.",
 "Merchant of record для цифровых товаров и подписок.",
 "Simplest legal path to selling a small tool internationally without a company setup.",
 "commission","around 5% + $0.50 per transaction","No monthly fee","https://www.lemonsqueezy.com/pricing"),
# ---------- Maps / weather / translation ----------
("paid-google-maps","Google Maps Platform","Карты и навигация","https://developers.google.com/maps/documentation","paid","maps,places,directions,geocoding",
 "Maps, Places, Routes and Geocoding under one billing account.",
 "Maps, Places, Routes и Geocoding под одним биллинг-аккаунтом.",
 "The monthly free credit covers small apps, but always set a hard quota cap in the console.",
 "usage","Per 1000 calls, varies by product","Monthly free usage credit","https://mapsplatform.google.com/pricing/"),
("paid-mapbox","Mapbox","Карты и навигация","https://docs.mapbox.com/","paid","maps,vector,navigation,styles",
 "Custom styled maps, navigation and geocoding.",
 "Кастомные стилизованные карты, навигация и геокодирование.",
 "Map loads are counted per session, not per tile: caching styles saves real money.",
 "hybrid","Per 1000 map loads after free tier","50k free map loads per month","https://www.mapbox.com/pricing"),
("paid-here","HERE Location Services","Карты и навигация","https://www.here.com/docs","paid","maps,routing,traffic,fleet",
 "Routing, traffic and fleet-grade location services.",
 "Маршрутизация, трафик и логистические геосервисы уровня автопарков.",
 "Strong truck and fleet routing, which is where it beats the better known providers.",
 "hybrid","Usage tiers after the free allowance","1000 free transactions per day","https://www.here.com/get-started/pricing"),
("paid-openweather","OpenWeather (paid plans)","Погода и геоданные","https://openweathermap.org/api","paid","weather,forecast,history,onecall",
 "Forecast, historical and specialised weather products.",
 "Прогноз, история и специализированные погодные продукты.",
 "One Call has its own subscription separate from the classic endpoints: read the plan table carefully.",
 "hybrid","from ~$40 / month for professional tiers","1000 free calls per day","https://openweathermap.org/price"),
("paid-deepl-pro","DeepL API Pro","Переводы и языки","https://developers.deepl.com/docs","paid","translation,quality,glossary,de",
 "Professional translation with glossaries and document translation.",
 "Профессиональный перевод с глоссариями и переводом документов.",
 "Glossaries are what make product terminology consistent across a whole site.",
 "hybrid","fixed monthly fee plus per-character cost","500k characters per month free","https://www.deepl.com/pro-api"),
("paid-google-translate","Google Cloud Translation","Переводы и языки","https://cloud.google.com/translate/docs","paid","translation,languages,cloud,batch",
 "Machine translation for over a hundred languages.",
 "Машинный перевод более чем для сотни языков.",
 "Billed per character including spaces: strip markup before sending text.",
 "usage","around $20 per million characters","500k free characters monthly","https://cloud.google.com/translate/pricing"),
# ---------- Product / monitoring / auth ----------
("paid-clerk","Clerk","Аутентификация","https://clerk.com/docs","paid","auth,users,ui,organizations",
 "Drop-in authentication with prebuilt user interface components.",
 "Готовая аутентификация с преднастроенными UI-компонентами.",
 "Billed per monthly active user, so growth is what raises the bill, not signups.",
 "hybrid","from ~$25 / month plus per active user","10k monthly active users free","https://clerk.com/pricing"),
("paid-auth0","Auth0","Аутентификация","https://auth0.com/docs","paid","auth,enterprise,sso,identity",
 "Enterprise identity platform with SSO and compliance features.",
 "Корпоративная платформа идентификации с SSO и требованиями комплаенса.",
 "Enterprise SSO connections are the expensive part: price them before promising a B2B feature.",
 "hybrid","Paid plans from ~$35 / month","Free tier up to 25k monthly users","https://auth0.com/pricing"),
("paid-sentry","Sentry","Мониторинг и аналитика","https://docs.sentry.io/","paid","errors,tracing,replay,monitoring",
 "Error tracking, performance tracing and session replay.",
 "Отслеживание ошибок, трассировка производительности и session replay.",
 "Sample traces and replays aggressively: full capture is what blows the event quota.",
 "hybrid","from ~$26 / month","5000 free errors per month","https://sentry.io/pricing/"),
("paid-posthog","PostHog","Мониторинг и аналитика","https://posthog.com/docs","paid","analytics,flags,replay,experiments",
 "Product analytics, feature flags, replays and experiments in one tool.",
 "Продуктовая аналитика, feature flags, реплеи и эксперименты в одном инструменте.",
 "The free monthly event allowance is unusually large: many side projects never pay at all.",
 "usage","Pay per event after the free allowance","1M free events per month","https://posthog.com/pricing"),
("paid-plausible","Plausible Analytics","Мониторинг и аналитика","https://plausible.io/docs","paid","analytics,privacy,gdpr,lightweight",
 "Privacy-friendly analytics with no cookies and a tiny script.",
 "Аналитика, дружелюбная к приватности: без cookies и с крошечным скриптом.",
 "No cookie banner required, which matters a lot for German and EU sites.",
 "subscription","from ~€9 / month","30-day free trial","https://plausible.io/#pricing"),
("paid-datadog","Datadog","Мониторинг и аналитика","https://docs.datadoghq.com/","paid","apm,logs,metrics,enterprise",
 "Full observability platform for infrastructure, logs and traces.",
 "Полноценная observability-платформа для инфраструктуры, логов и трейсов.",
 "Log ingestion is the line item that surprises teams: filter before shipping, not after.",
 "subscription","from ~$15 per host per month","14-day free trial","https://www.datadoghq.com/pricing/"),
("paid-figma","Figma","Изображения и дизайн","https://www.figma.com/developers","paid","design,collaboration,api,handoff",
 "Design tool with an API for tokens, assets and developer handoff.",
 "Дизайн-инструмент с API для токенов, ассетов и передачи в разработку.",
 "The read-only REST API is enough to sync design tokens into code automatically.",
 "subscription","Paid seats from ~$3 / month (Viewer)","Free plan with limited files","https://www.figma.com/pricing/"),
("paid-zapier","Zapier","Разработка и DevOps","https://docs.zapier.com/","paid","automation,integrations,workflows,saas",
 "Connects thousands of SaaS apps without writing integration code.",
 "Соединяет тысячи SaaS-приложений без написания интеграционного кода.",
 "Priced per task run: a chatty trigger can consume a month of quota in a day.",
 "subscription","from ~$20 / month","100 free tasks per month","https://zapier.com/pricing"),
("paid-airtable","Airtable","Базы данных и backend","https://airtable.com/developers/web/api/introduction","paid","database,no-code,records,automation",
 "Collaborative database with an API, used as a lightweight backend.",
 "Совместная база с API, используемая как лёгкий бэкенд.",
 "Record limits per base, not per workspace, are what force the upgrade.",
 "subscription","from ~$20 per seat per month","Free plan with 1000 records per base","https://airtable.com/pricing"),

# ==================== Stage 4 additions ====================
# These all merge onto an entry added in data_apis.py, so they contribute a
# pricing block rather than a new card. Where a headline number moves too often
# to quote responsibly, `from` describes the shape of the charge instead.

("paid-revenuecat","RevenueCat","Платежи и commerce","https://www.revenuecat.com/pricing/","paid","subscriptions,mobile,iap,revenue",
 "In-app subscription infrastructure priced as a share of tracked revenue.",
 "Инфраструктура подписок в приложениях с оплатой как долей от учтённой выручки.",
 "Because billing follows revenue, it costs nothing until the app earns something.",
 "commission","share of tracked revenue","free below the monthly revenue threshold","https://www.revenuecat.com/pricing/"),
("paid-polar","Polar","Платежи и commerce","https://polar.sh/docs","paid","merchant-of-record,payments,tax,saas",
 "Merchant-of-record checkout with per-transaction pricing and no monthly platform fee.",
 "Merchant of record checkout с оплатой за транзакцию и без месячной платы за платформу.",
 "As merchant of record they handle sales tax registration, which is the real cost being avoided.",
 "commission","per-transaction fee","no monthly platform fee","https://polar.sh/docs/merchant-of-record/tax"),
("paid-brevo","Brevo","Почта и уведомления","https://www.brevo.com/pricing/","paid","email,sms,volume,marketing",
 "Email and SMS sending priced by monthly volume.",
 "Отправка email и SMS с оплатой по месячному объёму.",
 "The daily cap on the free plan, not the monthly total, is what forces the first upgrade.",
 "subscription","paid tiers above the free daily cap","300 emails per day","https://www.brevo.com/pricing/"),
("paid-mailgun","Mailgun","Почта и уведомления","https://www.mailgun.com/pricing/","paid","email,smtp,deliverability,volume",
 "Transactional email with volume tiers and deliverability tooling.",
 "Транзакционная почта с тарифами по объёму и инструментами доставляемости.",
 "Log retention is short on the cheaper tiers, which matters the day you debug a bounce.",
 "subscription","volume-based monthly plans","trial sending allowance","https://www.mailgun.com/pricing/"),
("paid-langfuse","Langfuse","AI и агенты","https://langfuse.com/pricing","paid","llm-ops,tracing,evals,observability",
 "Hosted LLM tracing and evaluation, with a fully open-source self-hosted option.",
 "Хостинг трассировки и оценки LLM с полностью открытым self-hosted вариантом.",
 "Self-hosting is free and complete here, so the paid plan buys operations, not features.",
 "subscription","paid cloud tiers by trace volume","self-hosting is free and open source","https://langfuse.com/pricing"),
("paid-helicone","Helicone","AI и агенты","https://www.helicone.ai/pricing","paid","llm-ops,proxy,logs,caching",
 "Proxy-based logging for model calls, priced by request volume.",
 "Логирование вызовов моделей через прокси с оплатой по числу запросов.",
 "Caching identical calls can pay for the tool outright on a repetitive workload.",
 "usage","paid above the free request allowance","free monthly request allowance","https://www.helicone.ai/pricing"),
("paid-imagekit","ImageKit","Изображения и дизайн","https://imagekit.io/plans","paid","images,cdn,bandwidth,transformations",
 "Media CDN and transformations billed on delivered bandwidth.",
 "Медиа-CDN и трансформации с оплатой по отданному трафику.",
 "Bandwidth, not storage, is the meter: set output quality before you set cache headers.",
 "subscription","paid above the free bandwidth","20 GB media bandwidth per month","https://imagekit.io/plans"),
("paid-cloudconvert","CloudConvert","Документы и PDF","https://cloudconvert.com/pricing","paid","conversion,pdf,credits,files",
 "File conversion sold as prepaid conversion minutes or a subscription.",
 "Конвертация файлов, продаваемая как предоплаченные минуты или подписка.",
 "Prepaid packages suit bursty batch jobs better than a monthly plan you underuse.",
 "credits","prepaid conversion minutes","limited free daily conversions","https://cloudconvert.com/pricing"),
("paid-maptiler","MapTiler Cloud","Карты и навигация","https://www.maptiler.com/cloud/pricing/","paid","maps,tiles,map-loads,geocoding",
 "Map tiles and geocoding metered by map loads and API requests.",
 "Тайлы карт и геокодирование с учётом по загрузкам карты и запросам к API.",
 "One page that re-initialises the map on every render burns the free allowance fast.",
 "subscription","paid above the free map loads","limited monthly map loads","https://www.maptiler.com/cloud/pricing/"),
("paid-uptimerobot","UptimeRobot","Мониторинг и аналитика","https://uptimerobot.com/pricing/","paid","uptime,monitoring,intervals,alerts",
 "Availability monitoring where the check interval is what you pay for.",
 "Мониторинг доступности, в котором платишь за частоту проверок.",
 "Five-minute checks are free and adequate for a side project; one-minute checks are the upsell.",
 "subscription","paid for shorter check intervals","50 monitors at 5-minute checks","https://uptimerobot.com/pricing/"),
("paid-voyage","Voyage AI","Поиск и retrieval","https://docs.voyageai.com/docs/pricing","paid","embeddings,rerank,tokens,rag",
 "Embedding and reranking models billed per token.",
 "Модели эмбеддингов и реранка с оплатой за токены.",
 "Reranking touches only the shortlist, so it stays cheap even on a large corpus.",
 "usage","per-token pricing by model","starter token allowance","https://docs.voyageai.com/docs/pricing"),
]
