# -*- coding: utf-8 -*-
"""Generates `lib/i18n/categories.dart` from the taxonomy.

Category labels are needed before any database is open — the filter bar builds
itself from them at start-up — so they stay compiled into the app rather than
being read back out of SQLite.
"""
from __future__ import annotations

import pathlib

from .model import Catalog

HEADER = '// GENERATED by tool/build_catalog.py — do not edit by hand.'


def _dart_string(value: str) -> str:
    escaped = value.replace('\\', '\\\\').replace("'", r"\'").replace('$', r'\$')
    return f"'{escaped}'"


def write_categories(catalog: Catalog, path: pathlib.Path) -> pathlib.Path:
    groups = catalog.taxonomy.groups
    categories = sorted(catalog.taxonomy.categories, key=lambda entry: entry['name'])

    lines = [
        HEADER,
        "import 'app_language.dart';",
        '',
        'const categoryGroupOf = <String, String>{',
    ]
    lines += [
        f'  {_dart_string(entry["name"])}: {_dart_string(entry["group"])},'
        for entry in categories
    ]
    lines += ['};', '', 'const groupLabels = <String, Map<AppLanguage, String>>{']
    lines += [
        f'  {_dart_string(group["id"])}: {{'
        f'AppLanguage.en: {_dart_string(group["labels"]["en"])}, '
        f'AppLanguage.ru: {_dart_string(group["labels"]["ru"])}, '
        f'AppLanguage.de: {_dart_string(group["labels"]["de"])}}},'
        for group in groups
    ]
    lines += ['};', '', 'const categoryLabels = <String, Map<AppLanguage, String>>{']
    lines += [
        f'  {_dart_string(entry["name"])}: {{'
        f'AppLanguage.en: {_dart_string(entry["labels"]["en"])}, '
        f'AppLanguage.ru: {_dart_string(entry["labels"]["ru"])}, '
        f'AppLanguage.de: {_dart_string(entry["labels"]["de"])}}},'
        for entry in categories
    ]
    lines += ['};', '']

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text('\n'.join(lines), encoding='utf-8')
    return path
