// GENERATED by tool/build_catalog.py — do not edit by hand.

/// Version of this build, taken from pubspec.yaml.
const appVersion = '0.7.0';

/// Catalog compiled into `assets/catalog.db`.
///
/// Compared against the installed database on start-up: a fresh app build
/// carrying a newer catalog replaces the file an older install left behind,
/// without waiting for a download.
const bundledCatalogVersion = '2026.08.19';

/// Layout of the database this build knows how to read.
const bundledCatalogSchema = 4;

/// Entries in the bundled catalog, for the empty and error states.
const bundledCatalogItemCount = 2889;
